### ISSUE TITLE
I have installed Visual Studio 2022, but this error still occurs

### ISSUE THREAD

**Issue by ye-pei-sheng** [ltdrdata/ComfyUI-Impact-Pack#1]
![pm](https://user-images.githubusercontent.com/128130872/230704714-dbd1da4c-16f3-4659-ad73-47088fdaef07.png)

**Comment by spikeliu1984** [comment]
I had the same problem. It requires visual C++ 14.0 or greater, visual studio 2022 may not installed this component. I installed latest version of visual c++, but there's still an error.
![image](https://user-images.githubusercontent.com/41976672/230705237-0156be24-9ce2-4015-b53a-ab6889c73b66.png)

**Comment by ye-pei-sheng** [comment]
> I had the same problem. It requires visual C++ 14.0 or greater, visual studio 2022 may not installed this component. I installed latest version of visual c++, but there's still an error. ![image](https://user-images.githubusercontent.com/41976672/230705237-0156be24-9ce2-4015-b53a-ab6889c73b66.png)

Thank you for your reply. I reinstalled VS and checked C++, but the same problem occurred as you.

**Comment by TheNeObr** [comment]
Same problem Here....

**Comment by ltdrdata** [comment]
I fixed package issue on Windows. Try now.
You don't need install Visual Studio on this version.

**Comment by ye-pei-sheng** [comment]
> 我修复了Windows上的软件包问题。现在就试试。您不需要在此版本上安装 Visual Studio。

Good, Successfully run!
