### ISSUE TITLE
ComfyUI-Impact-Pack not installing now via Manager nor manual installation?

### ISSUE THREAD

**Issue by TxRxFx** [ltdrdata/ComfyUI-Impact-Pack#100]
I've tried the ComfyUI Manager to pull it down and install and also followed the [optional manual approach](https://github.com/ltdrdata/ComfyUI-Impact-Pack#installation)
but I get this error every time either way:

```bash
fatal: reference is not a tree: 2ca0ad6509bc951707807538923258d78403d6f7
Unable to checkout '2ca0ad6509bc951707807538923258d78403d6f7' in submodule path 'subpack'
```

Is there any guidance on how to work round this?

I'm using a Virtualenv with Python 3.10.12 and all other elements are working. I'm on Centos 7 and my version of Git is 1.8.3.1 (which I appreciate is bit old)

**Comment by ltdrdata** [comment]
I recommend remove it and reinstall it
The repo is broken temporarily..

**Comment by TxRxFx** [comment]
Thanks for the update I'll check in later. Can appreciate these things can happen.

**Comment by ltdrdata** [comment]
> Thanks for the update I'll check in later. Can appreciate these things can happen.

Oh... I found that you are trying install not updating..

In that case you need to update Git first.
Old git version doesn't support submodule.

**Comment by ltdrdata** [comment]
Since Impact Pack no longer use the submodule, this issue does not occur.
