### ISSUE TITLE
Noise Injection during Iterative Upscale

### ISSUE THREAD

**Issue by Xyem** [ltdrdata/ComfyUI-Impact-Pack#102]
I've experimented a bit recently with Iterative Upscale nodes and often end up with images that look either very smooth (lack of small details), are blurry or have lost significant detail from the input (for example, a brick wall with lose the brick pattern and just become a flat red-orange wall).

Is there a way of injecting noise at each stage of the upscale to give the Sampler something to work with at lower denoise?

**Comment by ltdrdata** [comment]
Actually, I'm planning to make such an update. I'm thinking of going in the direction of adding the PK_HOOK module for additional implementation.

**Comment by ltdrdata** [comment]
![noise](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/80302bf6-f569-49c2-88e1-d4673aa2ce73)

This node requires the `ComfyUI Noise` extension, which can be found at https://github.com/BlenderNeko/ComfyUI_Noise.
