### ISSUE TITLE
Not a bug. VAE merging

### ISSUE THREAD

**Issue by miasik** [ltdrdata/ComfyUI-Impact-Pack#103]
I've asked you on youtube and I'd like to continue here.
VAE is just a part of a model and usually get merged as a part of BASE block. I may be wrong but I believe that VAE is a set of the elements "first_stage_model."

It's easy to see merging a modelA with VAE and a modelB which requires an external VAE. When you get more and more from B you see that your images fades to gray.

Please, make VAE output for model merging

**Comment by ltdrdata** [comment]
![vae](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/854d5a75-ffa1-4a70-946b-bbab73b05b3f)

You can use the VAE output from the checkpoint provided or the output from the VAE Loader as it originally is.

**Comment by miasik** [comment]
> You can use the VAE output from the checkpoint provided or the output from the VAE Loader as it originally is.

Sure, I can! Actually, I'm asking because I'd like to use the merged VAE.

**Comment by ltdrdata** [comment]
FYI, ComfyUI added `VAESave` node.
