### ISSUE TITLE
Help with settings for hands with detailer please

### ISSUE THREAD

**Issue by AIMusicExperiment** [ltdrdata/ComfyUI-Impact-Pack#104]
![_00001](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/133187055/66ec4d9c-e884-4ddd-8657-c3d682720151)
Most of the time detailer is working pretty well for hands, but I get stuff like this sometimes. How can I prevent this from happening?

**Comment by ltdrdata** [comment]
First, increase the crop_factor significantly. Since the portion of the hand is too small, if the crop_factor is not increased sufficiently, there won't be enough context for inpainting.
