### ISSUE TITLE
The latest version of embedded comfy is using just one "d" in python_embeded

### ISSUE THREAD

**Issue by HerderOfCode** [ltdrdata/ComfyUI-Impact-Pack#105]
The install guide says "..\..\..\python_embe**d**ded\python.exe install.py" but the path in the latest download from comfy is "..\..\..\python_embeded\python.exe install.py". I don't know if the typo has always been there in "embedded", but it's in the current version on https://github.com/comfyanonymous/ComfyUI

**Comment by ltdrdata** [comment]
fixed. thank you.
