### ISSUE TITLE
Boolean widgets as inputs

### ISSUE THREAD

**Issue by Pos13** [ltdrdata/ComfyUI-Impact-Pack#108]
Every BOOLEAN type widget is forced into input mode, and cannot be turn back into widget:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/64479446/e02dc0ea-a188-4c83-b419-5535a417d6fc)

**Comment by Pos13** [comment]
This is especially inconvenient with parameters, whose meaning is unknown without labels: ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/64479446/533e897f-b538-4f47-93f2-8497640776ea)

**Comment by ltdrdata** [comment]
That requires latest version of ComfyUI.

**Comment by Pos13** [comment]
Updating works, thanks, no problems now.
I was sure I had the latest version of ComfyUI...
