### ISSUE TITLE
ImpactWildcardProcessor node unable to process wildcards with '-' in the filename

### ISSUE THREAD

**Issue by PhoenixFanta** [ltdrdata/ComfyUI-Impact-Pack#111]
So as the title says, any filenames with a '-' in the name will not process as a wildcard.  The automatic1111 dynamic prompts extension had a bunch of wildcard files that contained a '-' in the name, so I ended up using that as substitute for space in multi word file names as well. Wildcards that don't have a '-' in the filename have no issue being processed in the ImpactWildcardProcessor node.

**Comment by PhoenixFanta** [comment]
On line 64 of the replace_wildcard function in wildcards.py ,  I just added a backslash '\\' before the '-' in the regex pattern, so it would include the '-' in the match as '-' means range otherwise. 
        pattern = r"__([\w.\\-/]+)__"

**Comment by ltdrdata** [comment]
The corresponding bug has been fixed.
