### ISSUE TITLE
Errors with ONNX Detector

### ISSUE THREAD

**Issue by Pos13** [ltdrdata/ComfyUI-Impact-Pack#112]
1) "dilation" parameter in ONNX Detector node does nothing. Looks like this variable is not used.
2) "crop factor" below one fails to scale segs down. Result raises error in the next node instead. It's probably because of negative width and height of cropped mask.
3) "crop factor" above one does nothing for me, and I have no idea why.

**Comment by ltdrdata** [comment]
I will verify this issue later on.

**Comment by ltdrdata** [comment]
1. `crop factor` can not be negative value.
2. now `dilation` is fixed and improved.
- you can set negative value for dilation

7c2038b3d346a49fa734ac425d88cd5b1a6fea62
