### ISSUE TITLE
Not a bug. SEGS to MASK batch

### ISSUE THREAD

**Issue by Pos13** [ltdrdata/ComfyUI-Impact-Pack#113]
Maybe I missed something, but is there a way to convert segs to masks _not_ combined?
I know there is "SEGS To Mask List" node, but lists are difficult to process: you can't merge items from list into a single batch or a single mask.

I'm trying to perform a very simple task: bboxes from NudeNet are too large, so I want to scale them down. But if I combine the masks, I can't scale them individually. And if I make a list, I can't merge them back into a single mask.

**Comment by ltdrdata** [comment]
I will add this functionality to the todo list.

**Comment by ltdrdata** [comment]
I'd updated various SEGS manipulation nodes...

![segs](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/e6b84c4a-0b08-4624-b660-8b9a66aecf27)

Certainly, here's the grammatically corrected English sentence:
Now, dilation parameters support negative values to erode masks, so you don't need these nodes.
