### ISSUE TITLE
Feature request: Mask input for "Image Preview" node

### ISSUE THREAD

**Issue by Pos13** [ltdrdata/ComfyUI-Impact-Pack#115]
I frequently see in tutorials that, in order to show mask on image, you use "VAE Encode (for inpaint)" into "VAE Decode". Wouldn't it be better to have a mask input for "Image Preview" node?
It will also make manual fine-tuning of already generated masks so much easier! For now, there is no real way to send a mask into Mask editor.

**Comment by ltdrdata** [comment]
Using `VAE Encode (for inpaint)` to display masks is an outdated workflow. Instead, you can utilize `Mask To Image` for conversion and use `Preview Image`.

Currently, the preview node doesn't have a input that can receive masks. It seems that in the future, an expansion to the PreviewBridge might be necessary to allow for mask input.

**Comment by ltdrdata** [comment]
This feature is already provided through `MaskPreview+` at https://github.com/cubiq/ComfyUI_essentials, so I will close it.
