### ISSUE TITLE
FaceDetailer, FaceDetailerPipe loses png metadata

### ISSUE THREAD

**Issue by mythicalartist** [ltdrdata/ComfyUI-Impact-Pack#117]
It seems even when the image going into facedetailer has the png image metadata (and this can be verified by saving the image before facedetailer), the image coming out of face detailer is stripped of all png metadata. This is inconvenient if the image needs to be uploaded to civitai for example. If this is an actual bug (i.e not intended feature) would be happy to put in a pull request to fix this.

**Comment by ltdrdata** [comment]
That's not the case. Metadata is the responsibility of the SaveImage node. All the activities before that don't have any role.
The output "IMAGE" originally exists as data in the form of a tensor, and metadata is actually assigned at the point of saving.

metadata is always passed to the backend in the form of a .json when performing a queue prompt, and it exists in an accessible format across all nodes. If the vanilla save image node is unable to store metadata, it implies that there might be an extension that allows manipulation of metadata among the extension features. Test by adding them one by one in a state where the installation of each custom node has been removed (including the part in web/extensions).

I have tested and confirmed through experimentation that at the very least, when the custom nodes I manage are installed, this issue doesn't occur.

**Comment by mythicalartist** [comment]
Hmm... You are correct. I created a very simple workflow and saved the image before and after face detail and they both have the metadata. So something else in my workflow is probably causing this. Will try to debug and see if I can find more. Closing this for now.
