### ISSUE TITLE
Switch select by input not possible anymore

### ISSUE THREAD

**Issue by zymox** [ltdrdata/ComfyUI-Impact-Pack#118]
I was using Latent Switch to switch between latents at multiple locations in the workflow.

I had the select (1,2,3,..) converted to an input INT so I could set it only at one primitive in my inputs area in the workflow.

After updating Impact Pack today, this doesn't work anymore. The "select" input automatically turns to "input 5" and the switch stops working.

I think these variable inputs are a very cool idea, but it shouldn't break functionality and/or make it impossible to turn widgets into inputs. Maybe you can make it so that the inputs from converted widgets are first in the list of inputs instead of last, so that they don't make new inputs appear when connected?

**Comment by ltdrdata** [comment]
Oh... I'd forgot primitive thing... I'll patch it

**Comment by ltdrdata** [comment]
This is fixed. Try this.

**Comment by ltdrdata** [comment]
Fixed again... bb783d4947546d53a1912e2d28ca62e6ab9624ee

**Comment by zymox** [comment]
Works again! Thank you
