### ISSUE TITLE
SEGS Filter not working on descending order

### ISSUE THREAD

**Issue by Pos13** [ltdrdata/ComfyUI-Impact-Pack#119]
SEGS Filter (ordered) with ascending order works normal. But in descending it throws an error:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/64479446/5acb0f8d-ffd8-4906-8ede-085a742ed9b1)

> Traceback (most recent call last):
>   File "D:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "D:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "D:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 392, in doit
>     remained_list = [item[1] for item in sorted_list if item[1] not in result_list]
>   File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 392, in <listcomp>
>     remained_list = [item[1] for item in sorted_list if item[1] not in result_list]
> **ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()**

**Comment by ltdrdata** [comment]
Can you share your workflow? I cannot reproduce this.

It seems that the issue lies not with the `SEGS Filter` itself, but with the SEGS being passed to the `SEGS Filter`, which appears to be already corrupted.

**Comment by Pos13** [comment]
@ltdrdata, here is the link to the workflow and source image: [https://file.io/Jy7RkQ8lOVjW](https://file.io/Jy7RkQ8lOVjW)
Note that one node works (upper), while other doesn't (lower). Both set to "descending".

**Comment by ltdrdata** [comment]
> @ltdrdata, here is the link to the workflow and source image: https://file.io/Jy7RkQ8lOVjW Note that one node works (upper), while other doesn't (lower). Both set to "descending".

The `MasksToSEGS` used in your workflow has been corrupted due to the use of an incorrect version of the node. Please add a new `MasksToSEGS` node and reconnect accordingly.

Before proceeding, please double-check that both ComfyUI and Impact Pack are on their latest versions.

**Comment by Pos13** [comment]
@ltdrdata Yes, that was it, thank you. Workflow was outdated.
