### ISSUE TITLE
[Bug] Mask operations may provide negative values

### ISSUE THREAD

**Issue by clyce** [ltdrdata/ComfyUI-Impact-Pack#120]
## Reproducing the bug

This is a pipeline for generating mask from ClipSeg:
![mask](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/1068472/25bf3745-fd85-4504-ace9-40c419ed080f)

When applied to inpainting pipeline with `Set Latent Noise Mask`, generates image shown below:
![buggy](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/1068472/17b01284-72cb-436e-a07b-36f0356a4c35)
The latent space is affected by negative values. 

Checked the code, changed the `utils.py/subtract_masks` to clamp the result:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/1068472/fa731264-689d-4dd4-8341-10c3e42fd9c2)

And it produces the below result:
![fixed](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/1068472/c3dc6d2c-f41f-4448-9a92-04bbac4ea981)

## Solution:

There can be two optional solutions, 
1. Apply clamping to all mask operation functions
2. A new node called `Regularize Mask`

**Comment by ltdrdata** [comment]
This is fixed. Thank you.
