### ISSUE TITLE
Q: FaceDetailer - Use resolution to determine face details?

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#125]
Is there a method to have more resolution designated to the replacement face?  Seems like it would be ideal to work on this at a larger size and then downscale to fit the masked area.

**Comment by ltdrdata** [comment]
Simply, you can increase the guide_size and max_size.

https://youtu.be/KvZ8ucBqyqw?feature=shared

**Comment by sedetweiler** [comment]
I never got this to work very well.  While using a 1024 SDXL generation, the face is always blurry even if values like 4096 are used for max_size

**Comment by ltdrdata** [comment]
> I never got this to work very well. While using a 1024 SDXL generation, the face is always blurry even if values like 4096 are used for max_size

Have you also checked in the terminal how much the scale up has been?
