### ISSUE TITLE
Are all SEGS types interchangeable? (Issue with SEGSToImageList)

### ISSUE THREAD

**Issue by curiousjp** [ltdrdata/ComfyUI-Impact-Pack#128]
Hi there,

I have written a workflow using your nodes that lets me load an image, use a combination of ultralytics / SAM to find the faces in it, and then separate them out using SEGS Filter and refine each individually with its own prompt. These are then joined back together using two layers of SEGS Concat and pasted back onto the original. The workflow works well (thank you for your hard work), but while I was developing it I ran into an odd issue.

After I use ImpactSEGSOrderedFilter to split out the subjects, I use SEGSToImageList on the filtered_SEGS output to preview which face is which. This works fine, even without a fallback_image_opt. But once the same filtered_SEGS has been through SEGSDetailer, this no longer works because it appears that the seg items now store their representations differently.  I get this error:

```
Error occurred when executing SEGSToImageList:

expected np.ndarray (got Image)

  File "/home/[...]/ComfyUI/execution.py", line 158, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[...]/ComfyUI/execution.py", line 88, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[...]/ComfyUI/execution.py", line 81, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[...]/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 475, in doit
    cropped_image = torch.from_numpy(seg.cropped_image)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I've attached a PNG with an embedded minimal version (all the LoRA loading stuff stripped out) of my workflow that displays this behavior - the broken SEGSToImageList node is off to the right. Is this expected behavior or something else?
![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/48515264/41b54b00-8927-4c95-b11f-f8499f0fac4c)

**Comment by ltdrdata** [comment]
This is fixed on 19ba1b36047cd13f4767c98d2cb30d4778279808
Thank you for the report.
