### ISSUE TITLE
[suggestion] "style prompt" support for ImpactWildcardEncode (and ImpactWildcardProcessor)

### ISSUE THREAD

**Issue by Ratinod** [ltdrdata/ComfyUI-Impact-Pack#135]
ImpactWildcardEncode is an incredibly handy node! It allows you to conveniently use LORA. It allows you to use wildcards. And only one small thing is missing for this node to become perfect - style prompt support.
Of course, there are already nodes that allow you to add all this to ComfyUI:
![style_right_now](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/12137233/c64474c5-c7fe-4802-ae6a-7bc6420ea853)
But... I can't get them to make friends with ImpactWildcardEncode. They also use different file formats (.csv (like in the automatic1111) and .json).
I propose to add support for style prompt. And add your own node to select the style prompt file.
It should probably look something like this:
![style_su](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/12137233/2678dc88-648d-4fd7-ade4-35ebf1ef03fe)
example:
![style_work](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/12137233/679834af-7c69-48ab-8e94-43690b79eb28)

**Comment by ltdrdata** [comment]
There is a somewhat complex issue here. Currently, the decision for `ImpactWildcard...` to pass execution from the browser to the workflow in order to record the determined prompt happens at the moment of execution. On the other hand, for the styler nodes, the execution occurs once the values have been determined. I will consider how to support style feature within `ImpactWildcard...`

**Comment by Ratinod** [comment]
Yes. It's a pity that ComfyUI doesn't support live preview (dynamic change) in nodes at least for text. Then something like this could be done:
![style_dynpre](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/12137233/2859c312-7d41-43e7-b994-fcff402eed2d)
The gray text is a preview of the added style. White text is your prompt.
I hope you find the best solution.

**Comment by Ratinod** [comment]
Yes. It's a pity that ComfyUI doesn't support live preview (dynamic change) in nodes at least for text. Then something like this could be done:
![style_dynpre](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/12137233/3acff188-281d-44bb-9165-98cc2878c841)
The gray text is a preview of the added style. White text is your prompt.
I hope you find the best solution.

**Comment by ltdrdata** [comment]
Using the 2b20654cddd68a414b50ee2812775730547afa4d update, you can incorporate the styler as follows.

![styler](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/19df95c3-0e0c-455e-978d-f7f43d16289e)

populated_text is added.
