### ISSUE TITLE
Missing argument 'tile_size'

### ISSUE THREAD

**Issue by tsen9731** [ltdrdata/ComfyUI-Impact-Pack#136]
`TypeError: VAEEncodeTiled.encode() missing 1 required positional argument: 'tile_size'`
Raised when using PixelTiledKSampleUpscalerProviderPipe with IterativeImageUpscale

**Comment by BundoBytes** [comment]
I'm getting the same issue as well. It seems to be due to this [commit](https://github.com/comfyanonymous/ComfyUI/commit/9196588088f69bcdd90b3b2e571f120409c43bcd), which adds tile_size as a new parameter.

**Comment by ltdrdata** [comment]
I'd patched this on f58449d73bcfed11179df6861d8f134815f26ee5
