### ISSUE TITLE
Possible Enhancement?

### ISSUE THREAD

**Issue by AIMusicExperiment** [ltdrdata/ComfyUI-Impact-Pack#137]
I use lots of your nodes, and I think that you are nothing short of Genius  when it comes to ComfyUI. My main thing is deforum-like  Hybrid video animation. I like to use your face detailer and I think it is one of the best nodes on Comfy. Often the characters in my source video will be singing, and making facial expressions. Unfortunately the detailed lip and face movements get "lost in translation." Media pipe is capable of tracking these, but it is tricky and basically useless to apply before the detailer. My quandary, is if someone like you with your brilliant ways could isolate the face from the frame, like you do in the detailer, then apply media pipe to it for detection and finally apply the result to the conditioning for your detailer. To my knowledge no one has figured this out, and it often comes up as a discussion on the deforum discord. It certainly can't be done in A1111, but I believe that with the resources in ComfyUI you could make it happen.  If you could figure out how to make your detailer do this, it would be beyond epic.

**Comment by ltdrdata** [comment]
It seems that utilizing the ControlNet preprocessor instead of Mediapipe to extract facial expression information from the original and then applying ControlNet to SEGS could be a necessary approach.

I will consider an extension that adds ControlNet conditioning to SEGS.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/SEGSControlNet.md
https://github.com/ltdrdata/ComfyUI-extension-tutorials/tree/Main/ComfyUI-Inspire-Pack/workflow

**Comment by ltdrdata** [comment]
I'd added `MediaPipeFaceMeshToSEGS` into Impact Pack. and `MediaPipeFaceMeshDetectorProvider` into Inspire Pack.
They are depend on ControlNet Auxiliary Preprocessors.

![mp](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/1af2a027-8938-45d7-a2ba-108a2b78d04b)

**Comment by AIMusicExperiment** [comment]
Thank you so much! this should really enhance the ability!

**Comment by AIMusicExperiment** [comment]
I've been working with trying to get this right for several hours, and I keep failing. I have put a SEGSpreview on the output and I can see that it is not analyzing my input correctly. Regardless of the settings I can't get the face centered, and with some setting it tiles the image in haphazard way. I sure that it is my setting that are wrong, but I can't figure them out. Could it be the lack of a BBOX input that is causing this? I would LOVE to get this working as it would really enhance my work flows. Please help me to figure out how to set this up properly!

**Comment by ltdrdata** [comment]
> I've been working with trying to get this right for several hours, and I keep failing. I have put a SEGSpreview on the output and I can see that it is not analyzing my input correctly. Regardless of the settings I can't get the face centered, and with some setting it tiles the image in haphazard way. I sure that it is my setting that are wrong, but I can't figure them out. Could it be the lack of a BBOX input that is causing this? I would LOVE to get this working as it would really enhance my work flows. Please help me to figure out how to set this up properly! 

mediapipe detects not only face it also detects parts of faces. if you want just detect face then turn off all options except face.

![mediapipe.png](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/ea1aa15a-821a-45f4-bbd5-60bdf358004a)

This is an odd eye workflow.

**Comment by AIMusicExperiment** [comment]
Turns out that I had my cropping adjustments incorrect and it is now working as prescribed! I cannot overstate how valuable this is to the core of the work that I do! And I am not, "blowing smoke up your ass!" This really is ground breaking. This allows ComfyUi to do what Deforum really can't.  Now because I'm a needy little girl. . Ha Ha. . will you make one for hands?

**Comment by AIMusicExperiment** [comment]
I have been wondering: Can you use one segs detailer and one debug to do bothe face and hands? If so it would really cut down the node count for my workflows. . .

**Comment by ltdrdata** [comment]
You can use SEGSConcat.

**Comment by AIMusicExperiment** [comment]
where in the chain do I put that? Before the detailer I'm guessing

**Comment by ltdrdata** [comment]
> where in the chain do I put that? Before the detailer I'm guessing

Sure. It makes multiple SEGS to single SEGS
And you can separate then through SEGSFilters.

**Comment by AIMusicExperiment** [comment]
I'm testing this now, if I can make this work, in conjunction with the contronet that you did on faces, then we have just conquered the universe! Well, a little tiny part of the Universe anyway.

**Comment by ltdrdata** [comment]
> I'm testing this now, if I can make this work, in conjunction with the contronet that you did on faces, then we have just conquered the universe! Well, a little tiny part of the Universe anyway. 
> 

Ah.. You should update to latest version both Impact Pack and Inspire Pack.

I'd fixed mediapipe bug last night.

**Comment by AIMusicExperiment** [comment]
I already did, it is always the first thing I do when designing! Having a little trouble, but I will probably get it all sorted out. . .Do I need both a SEGs Detailer and a Detailer Debug? Or is that redundant? I've been putting the init image into the detailer and the image to be corrected int to debug. . .

**Comment by ltdrdata** [comment]
> I already did, it is always the first thing I do when designing! Having a little trouble, but I will probably get it all sorted out. . .Do I need both a SEGs Detailer and a Detailer Debug? Or is that redundant? I've been putting the init image into the detailer and the image to be corrected int to debug. . .

The output of SEGS Detailer comes in the form of SEGS. Detailer integrates this with the process of pasting SEGS onto the original image. If you're not going to perform separate processing with SEGS, there's no need to use SEGS Detailer.
