### ISSUE TITLE
Please update to the latest ComfyUI_TiledKSampler

### ISSUE THREAD

**Issue by hortom** [ltdrdata/ComfyUI-Impact-Pack#14]
Hi,
Could you please update your amazing nodes to be compatible with the latest [ComfyUI_TiledKSampler](https://github.com/BlenderNeko/ComfyUI_TiledKSampler)?
BlenderNeko has introduced a new parameter `tiling_strategy` and possibly removed the `concurrent_tiles`.
Thank you and keep up the good work!

**Comment by ltdrdata** [comment]
Oh.. I missed that change. I just commit. Try that.
