### ISSUE TITLE
About mediapipe_face_full.pt

### ISSUE THREAD

**Issue by fr0nky0ng** [ltdrdata/ComfyUI-Impact-Pack#143]
Hello  Dr.Lt.Data, I am a beginer from webui. 
In webui， when using Adetailer for face restoration, mediapipe_face_full.pt is recommended for real faces. I want to try it in ComfyUI-Impact-Pack, but didn't find this model file. Is there any solution specifically for real faces? or just use bbox/face_yolov8m.pt is OK?

**Comment by ltdrdata** [comment]
If Ultralytics fails to detect a face, there's no need to use MediaPipe, unless necessary. Ultralytics primarily handles the detection of facial positions and ranges, while intricate silhouettes are achieved through SAM.

**Comment by fr0nky0ng** [comment]
ok, let me study. Thank you.

**Comment by ltdrdata** [comment]
I'd added `MediaPipeFaceMeshToSEGS` into *Impact Pack*. and `MediaPipeFaceMeshDetectorProvider` into *Inspire Pack*.
They are depend on *ControlNet Auxiliary Preprocessors*.

![mp](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/146b988a-2d36-4e44-a2cd-0361baefce7c)
