### ISSUE TITLE
Wildcard + Seed

### ISSUE THREAD

**Issue by gobshyte** [ltdrdata/ComfyUI-Impact-Pack#145]
Hi
Is it possible/reasonable to add a seed input to the wildcard nodes? So that when populate is selected, if the same seed (and input files) are present, the same output is produced? This would be really nice when you are trying to use the same set of seeds etc.

**Comment by ltdrdata** [comment]
I am considering this.

**Comment by ltdrdata** [comment]
This is implmented on 1c2974c4277d423f831b65ff9d23ec321687da81

**Comment by gobshyte** [comment]
Yay! Awesome work!
