### ISSUE TITLE
FaceDetailer: apply different prompt in order of face appearance

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Impact-Pack#148]
I am using several ConditioningSetAreaPercentage nodes to create an image with three characters, appearing from left to right in a single image. I would like to apply a different (but specific, not random) FaceDetailer prompt to each.

Is there something that makes this possible?

I know in adetailer one can use the `[SEP]` keyword, like `green eyes [SEP] blue eyes [SEP] red eyes`: https://github.com/Bing-su/adetailer/wiki/Advanced. Is there something like this in FaceDetailer?

Or maybe a special type of wildcard, but which would obey the order instead of picking at random, like `[green eyes|blue eyes|red eyes]`, in that order?

Obviously it would fail if any of the faces fail to detect, but let's assume correct detection.

**Comment by ltdrdata** [comment]
If you want to have such meticulous control, you should use Detailer instead of FaceDetailer. 
You can use SimpleDetector to detect faces and create SEGS, then separate them one by one using a filter. 
You can apply a completely separate Detailer for each SEGS. 
It's possible to process them cumulatively by sending the results of each Detailer to the next one in line.

**Comment by alexopus** [comment]
Thanks, that works nicely.
Although of course the graph becomes quite verbose :)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/30ff87f5-3a42-4aed-9f50-5c867393cc09)

**Comment by ltdrdata** [comment]
> Thanks, that works nicely. Although of course the graph becomes quite verbose :)
> 
> ![image](https://user-images.githubusercontent.com/25933468/266380250-30ff87f5-3a42-4aed-9f50-5c867393cc09.png)

I plan to improve the scenario in the future.
However, using this approach allows for more detailed adjustments than using `[SEP]`, so it will still be useful.

**Comment by ltdrdata** [comment]
FYI, I'd implemented `[SEP]` feature on V4.37.1.
But, the syntax is little bit different so check this.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md#special-syntax-for-detailer-wildcard

**Comment by UnshackledAI** [comment]
> Thanks, that works nicely. Although of course the graph becomes quite verbose :)
> 
> ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/30ff87f5-3a42-4aed-9f50-5c867393cc09)

Hey. This is an old issue now but that screenshot was IMMENSELY helpful. I've been using face detailer and losing my shit when I can't get the face separation to occur. Would you be able to post your workflow please if it's no trouble?  I have a working workflow but curious to see how what I have compares when tried with yours. 

Thank You
