### ISSUE TITLE
Mismatched tensor size

### ISSUE THREAD

**Issue by aaron9412** [ltdrdata/ComfyUI-Impact-Pack#15]
Hi, I am running https://raw.githubusercontent.com/ltdrdata/ComfyUI-extension-tutorials/Main/ComfyUI-Impact-Pack/images/simple.png as an example and got this:

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 20 but got size 19 for tensor number 1 in the list.

I have tried setting it up on my own and using different models but no luck. Any ideas?
Windows 10, comfy portable, I have tried different models.

Thanks!
-Aaron

**Comment by ltdrdata** [comment]
1. Ensure, your ComfyUI is latest version.

2. Please, share your workflow if your ComfyUI is already latest version.
- In that case, It can be a bug which is occurred in specific settings.

3. Download this file: https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/images/simple-refined.png 
4. Drag that image and drop into ComfyUI.
5. Execute on the loaded workflow. 
- Is the error occurs persistently?

**Comment by aaron9412** [comment]
Welp. I installed it on a fresh standalone copy, ran the simple-refined again (I had run that before), and it didn't happen. Copied all my stuff over to the new copy and it still works fine. If there is a way to check my version of comfy (downloaded ~01MAY2023 maybe?) I can post the one that had the issue for future troubleshooting.

Thank you : )

**Comment by ltdrdata** [comment]
> Welp. I installed it on a fresh standalone copy, ran the simple-refined again (I had run that before), and it didn't happen. Copied all my stuff over to the new copy and it still works fine. If there is a way to check my version of comfy (downloaded ~01MAY2023 maybe?) I can post the one that had the issue for future troubleshooting.
> 
> Thank you : )

In the last two weeks, ComfyUI has had a tremendous update. :)
