### ISSUE TITLE
Skip model download

### ISSUE THREAD

**Issue by wangdong2023** [ltdrdata/ComfyUI-Impact-Pack#150]
Hi, I'm wondering if you can add an option in `install.py` to skip model downloading. The reason is I want to use it in docker, and all the models will be mounted as volume later on. So I only want code in the image.

**Comment by ltdrdata** [comment]
If the `skip_download_model` file exists in the `custom_nodes` directory, the `install.py` script will skip the model download.

25e3a12480e87be212315f1e6d17fa34105b5156
