### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by h3clikejava** [ltdrdata/ComfyUI-Impact-Pack#151]
### ComfyUI-Impact-Pack: Check dependencies

...

Traceback (most recent call last):
  File "/home/timehut/Documents/ComfyUI/nodes.py", line 1694, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 312, in <module>
    from impact.mmdet_nodes import *
  File "/home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/mmdet_nodes.py", line 5, in <module>
    from mmdet.apis import (inference_detector, init_detector)
  File "/home/timehut/.local/lib/python3.10/site-packages/mmdet/__init__.py", line 17, in <module>
    and mmcv_version < digit_version(mmcv_maximum_version)), \
AssertionError: MMCV==1.3.17 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

Cannot import /home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: MMCV==1.3.17 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.
### ComfyUI Revision: 1352 [0faee118]
17:47:27 - ReActor Node - STATUS - Running v0.1.1b in ComfyUI

...

Import times for custom nodes:
   0.0 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/masquerade-nodes-comfyui
   0.0 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI-Manager
   0.0 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.1 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/SeargeSDXL
   0.2 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/comfyui-reactor-node
   0.3 seconds: /home/timehut/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui
  15.1 seconds (IMPORT FAILED): /home/timehut/Documents/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

Starting server

**Comment by ltdrdata** [comment]
Your mmcv environment is too old.
You should remove mmcv environments and reset.
Otherwise just keep the mmcv_skip as True.

I don't recommend turn on that option.

**Comment by h3clikejava** [comment]
How can I modify my mmcv environment? After upgrading to mmcv==2.0.0rc4 and restarting comfyui, it will be forcefully reverted back to mmcv==2.0.0.

**Comment by ltdrdata** [comment]
> How can I modify my mmcv environment? After upgrading to mmcv==2.0.0rc4 and restarting comfyui, it will be forcefully reverted back to mmcv==2.0.0.

uninstall mmcv, openmim, mmdet, mmengine

and restart ComfyUI.

Then impact will try reinstall.

**Comment by h3clikejava** [comment]
I did it step by step according to your method, but it still doesn't work, so I gave up 😭

**Comment by ltdrdata** [comment]
I recommend not using mmdet as it has consistently caused issues. Instead, I've replaced it with Ultralytics, which offers a more versatile model. Ultralytics excels in every aspect compared to mmdet. mmdet has been deprecated.
