### ISSUE TITLE
requirements: Ultralytics requirement ['dill'] not found, attempting AutoUpdate...

### ISSUE THREAD

**Issue by Gavr728** [ltdrdata/ComfyUI-Impact-Pack#157]
Using extensions inside Ultimate workflow v 3.1
Getting this error while try to load my custom bbox_detector models.

The models were trained not on a standard 640x640 resolution, so I think error may be coming from here. Because my first two models that were trained in 640x640 are working fine.

```
AutoInstall will run now for 'dill' but this feature will be removed in the future.

Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['dill'] not found, attempting AutoUpdate...

[notice] A new release of pip is available: 23.0 -> 23.2.1
[notice] To update, run: C:\Users\Gavr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
Requirement already satisfied: dill in c:\users\gavr\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (0.3.7)

requirements: AutoUpdate success  2.6s, installed 1 package: ['dill']
requirements:  Restart runtime or rerun command for updates to take effect

WARNING  D:\ComfyUI_windows_portable\ComfyUI\models\ultralytics\bbox\best.pt appears to require 'dill', which is not in ultralytics requirements. 

```

**Comment by ltdrdata** [comment]
Your situation appears similar to this:
https://github.com/ultralytics/ultralytics/issues/2571

**Comment by Gavr728** [comment]
> Your situation appears similar to this: [ultralytics/ultralytics#2571](https://github.com/ultralytics/ultralytics/issues/2571)

Tried to reinstall Ultralytics, got the same error. 
Also, I can confirm that both models that don't work inside Comfy work correctly from the CLI.

**Comment by ltdrdata** [comment]
> > Your situation appears similar to this: [ultralytics/ultralytics#2571](https://github.com/ultralytics/ultralytics/issues/2571)
> 
> Tried to reinstall Ultralytics, got the same error. Also, I can confirm that both models that don't work inside Comfy work correctly from the CLI.

You'd better report that issue to this repo:
https://github.com/ultralytics/ultralytics/
