### ISSUE TITLE
Inverted Mask Not Respected

### ISSUE THREAD

**Issue by aaron9412** [ltdrdata/ComfyUI-Impact-Pack#16]
Hey, I've been trying to use the mask output from FaceDetailer followed by invert mask and it kinda works but not well.
I am trying to keep faces but change the rest.
If I don't invert the mask, only the face is changed, so I know that part is correct.
If I do invert the mask, the rest of the image is changed, but so the face is also changed to a lesser extent.
I can't find any examples of anyone doing this anywhere and I haven't figured it out yet.
I'll keep working on it but I'm posting this here in case anyone knows what I should do to make the inverted mask 100% respected.
I am using inpainting models.

Thanks for these awesome nodes,
-Aaron

![image](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/27147792/ce0d1271-6500-4fd5-812b-bccd527d3da6)
![image](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/27147792/e704bfaa-9c52-40d8-82e0-ebbc10edb10f)

**Comment by aaron9412** [comment]
I think this may be related to this issue:
https://github.com/comfyanonymous/ComfyUI/issues/673

And not actually a problem with the mask, but I'm not sure.

**Comment by ltdrdata** [comment]
I confirmed that weird action of VAEEncodeForInpaint.
Don't use that.

use VAEEncode and SetLatentNoiseMask.

<img width="779" alt="inpaint2" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/033a6c8b-e92f-4581-aa16-bc0cc2086afc">
<img width="654" alt="inpaint" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/9af834c2-25d2-49be-bc2b-0de2b1f4561e">
<img width="779" alt="inpaint2" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/17134fbe-7f35-40d1-a1e4-0160d4829f0a">
