### ISSUE TITLE
switch any reset slot name any reconect link

### ISSUE THREAD

**Issue by pvp-by** [ltdrdata/ComfyUI-Impact-Pack#160]
Not a critical problem, but an unpleasant event when in an already configured workflow "switch any" when changing links resets the names of all slots.

When a link is removed and the number of slots is reduced, name reset is an appropriate event. but those that remain active should not lose their name.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/10133995/28119b45-223f-49df-b58f-dc9c0e9cd5c4)

**Comment by ltdrdata** [comment]
This is fixed on ac9589837f903756d855ab96ea5fa76d4aa9bcfe
