### ISSUE TITLE
[SAMDetectorSegmented]: Why two different output types

### ISSUE THREAD

**Issue by procule** [ltdrdata/ComfyUI-Impact-Pack#162]
In this node:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/152512/98c65d97-7c07-42fb-bf10-145ec3e1e8fc)

What is the reason to have a tensor of shape `[H, W], dtype float32, range 0. to 1.` in the `combined_mask` output but a tensor of shape `[N, 1, H, W], dtype boolean` in the `batch_masks` output ?

Here we can see at lines `570`, `578`, `580` and `586` that the first output is indeed a `float` torch tensor:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/dbe77553a8d4abea018ab8e543fca64a710cab36/modules/impact/core.py#L570-L586

While on line `584`, the second output `batch_masks` goes through `convert_and_stack_masks` and then `merge_and_stack_masks` functions.
Specifically, in the `convert_and_stack_masks`, at line `481`, the mask is converted to a `boolean` before being appended to the array and then stacked.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/dbe77553a8d4abea018ab8e543fca64a710cab36/modules/impact/core.py#L474-L487

Yours truly.

**Comment by ltdrdata** [comment]
This is something I missed in the PR review. Thanks.
This is fixed on 5bbd3e141ccfab2e679601ca43d109406d9a9ad8

**Comment by procule** [comment]
I confirm that this same change I did on my end is working :+1: 

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/dbe77553a8d4abea018ab8e543fca64a710cab36/modules/impact/core.py#L481

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/5bbd3e141ccfab2e679601ca43d109406d9a9ad8/modules/impact/core.py#L481
