### ISSUE TITLE
UltralyticsDetectorProvider not found

### ISSUE THREAD

**Issue by HenryFroio** [ltdrdata/ComfyUI-Impact-Pack#163]
Yesteday was working just fine, but when i turned on comfyui today it was not working.

![Captura de tela 2023-09-13 172145](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/94875647/f0886272-c700-4f0e-bf2c-40e85ab4edce)

**Comment by sCarita** [comment]
Having the same issue, not sure why...

**Comment by bebuk** [comment]
Seems `ultralytics` introduced a faulty release, check your version with `pip freeze` and if you have version `8.0.177` try running `pip install ultralytics==8.0.176` to downgrade to working version.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/7099742/38d2d037-92d3-49a4-949b-79d95b246924)

**Comment by sCarita** [comment]
Worked for me. Thank you for the support.

**Comment by ltdrdata** [comment]
> Seems `ultralytics` introduced a faulty release, check your version with `pip freeze` and if you have version `8.0.177` try running `pip install ultralytics==8.0.176` to downgrade to working version.
> 
> ![image](https://user-images.githubusercontent.com/7099742/267792779-38d2d037-92d3-49a4-949b-79d95b246924.png)

Thank you for the answer. I'd modified requirements.txt to skip that version.

**Comment by MrMax7** [comment]
<img width="685" alt="Screenshot 2023-09-30 at 7 09 05 PM" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/145134851/42a45e0f-639d-4dbe-b078-e78093461041">


I am new with ComfyUI and after doing all the steps to get here I am still blocked here. Is this still an issue for anyone?

**Comment by ltdrdata** [comment]
How did you install Impact Pack?
And what messages were displayed on ComfyUI startup terminal?

**Comment by MrMax7** [comment]
I installed it directly from within the comfyUI Manager by checking the box "Use local DB" since when unchecked it says it is updating. 

Thanks for the assistance!
<img width="1278" alt="Screenshot 2023-09-30 at 7 43 36 PM" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/145134851/3ab8dda4-f382-4710-90cd-50318acdba68">
<img width="1408" alt="Screenshot 2023-09-30 at 7 45 05 PM" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/145134851/8dd14e1a-32da-4732-8486-851891c0f5be">

**Comment by ltdrdata** [comment]
> I installed it directly from within the comfyUI Manager by checking the box "Use local DB" since when unchecked it says it is updating.
> 
> Thanks for the assistance! <img alt="Screenshot 2023-09-30 at 7 43 36 PM" width="1278" src="https://user-images.githubusercontent.com/145134851/271799268-3ab8dda4-f382-4710-90cd-50318acdba68.png"> <img alt="Screenshot 2023-09-30 at 7 45 05 PM" width="1408" src="https://user-images.githubusercontent.com/145134851/271799339-8dd14e1a-32da-4732-8486-851891c0f5be.png">

Try uninstall and reinstall.

**Comment by MrMax7** [comment]
> > I installed it directly from within the comfyUI Manager by checking the box "Use local DB" since when unchecked it says it is updating.
> > Thanks for the assistance! <img alt="Screenshot 2023-09-30 at 7 43 36 PM" width="1278" src="https://user-images.githubusercontent.com/145134851/271799268-3ab8dda4-f382-4710-90cd-50318acdba68.png"> <img alt="Screenshot 2023-09-30 at 7 45 05 PM" width="1408" src="https://user-images.githubusercontent.com/145134851/271799339-8dd14e1a-32da-4732-8486-851891c0f5be.png">
> 
> Try uninstall and reinstall.

I disabled and then uninstalled it. Then reboot the page+Terminal. Then downloaded and rebooted the terminal+page and the same error still persists.

Is there an equivalent that could make the workflow work? I am quite new to this so I am not yet fully familiar with the system.

**Comment by ltdrdata** [comment]
> > > I installed it directly from within the comfyUI Manager by checking the box "Use local DB" since when unchecked it says it is updating.
> > > Thanks for the assistance! <img alt="Screenshot 2023-09-30 at 7 43 36 PM" width="1278" src="https://user-images.githubusercontent.com/145134851/271799268-3ab8dda4-f382-4710-90cd-50318acdba68.png"> <img alt="Screenshot 2023-09-30 at 7 45 05 PM" width="1408" src="https://user-images.githubusercontent.com/145134851/271799339-8dd14e1a-32da-4732-8486-851891c0f5be.png">
> > 
> > 
> > Try uninstall and reinstall.
> 
> I disabled and then uninstalled it. Then reboot the page+Terminal. Then downloaded and rebooted the terminal+page and the same error still persists.
> 
> Is there an equivalent that could make the workflow work? I am quite new to this so I am not yet fully familiar with the system.

Upload `comfyui.log` file in ComfyUI directory or portable directory if you are using portable version.
And `comfyui.prev.log`, `comfyui.prev2.log`, too. if you restarted ComfyUI after reinstall, several times.

**Comment by MrMax7** [comment]
> > > > I installed it directly from within the comfyUI Manager by checking the box "Use local DB" since when unchecked it says it is updating.
> > > > Thanks for the assistance! <img alt="Screenshot 2023-09-30 at 7 43 36 PM" width="1278" src="https://user-images.githubusercontent.com/145134851/271799268-3ab8dda4-f382-4710-90cd-50318acdba68.png"> <img alt="Screenshot 2023-09-30 at 7 45 05 PM" width="1408" src="https://user-images.githubusercontent.com/145134851/271799339-8dd14e1a-32da-4732-8486-851891c0f5be.png">
> > > 
> > > 
> > > Try uninstall and reinstall.
> > 
> > 
> > I disabled and then uninstalled it. Then reboot the page+Terminal. Then downloaded and rebooted the terminal+page and the same error still persists.
> > Is there an equivalent that could make the workflow work? I am quite new to this so I am not yet fully familiar with the system.
> 
> Upload `comfyui.log` file in ComfyUI directory or portable directory if you are using portable version. And `comfyui.prev.log`, `comfyui.prev2.log`, too. if you restarted ComfyUI after reinstall, several times.

I uploaded it hope it was the right place I am also very new to GitHub. 

Thank you.

**Comment by ShivaeAI** [comment]
/
![屏幕截图 2023-11-02 155225](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129743485/4942a821-f703-4bdc-9cc5-2c489c3bbddb)help

**Comment by ShivaeAI** [comment]
Prestartup times for custom nodes:
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 32581 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.28.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
### Loading: ComfyUI-Inspire-Pack (V0.33)
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: 1643 [dd116abf] | Released on '2023-11-02'
Traceback (most recent call last):
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\__init__.py", line 8, in <module>
    import custom_mmpkg.custom_mmcv as mmcv
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\__init__.py", line 4, in <module>
    from .fileio import *
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\fileio\__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\fileio\file_client.py", line 15, in <module>
    from custom_mmpkg.custom_mmcv.utils.misc import has_method
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\utils\__init__.py", line 3, in <module>
    from .config import Config, ConfigDict, DictAction
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\utils\config.py", line 17, in <module>
    from yapf.yapflib.yapf_api import FormatCode
ModuleNotFoundError: No module named 'yapf'

Cannot import D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff module for custom nodes: No module named 'yapf'
Traceback (most recent call last):
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\__init__.py", line 2, in <module>
    from .vae import VAEDecodeBatched, VAEEncodeBatched
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\vae.py", line 5, in <module>
    from .model.iter import try_get_iter
  File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\model\iter.py", line 4, in <module>
    from comfy.sd import ModelPatcher, CLIP, VAE
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)

Cannot import D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
FizzleDorf Custom Nodes: Loaded
__name__ : ComfyUI_node_Lilly
__file__ : D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  D:\qiuye\ComfyUI\ComfyUI_windows_portable
─────────────────────────────────────────────────────  init start  ─────────────────────────────────────────────────────
__name__ : custom_nodes.ComfyUI_node_Lilly
__file__ : D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  D:\qiuye\ComfyUI\ComfyUI_windows_portable
[15:59:17] Load ok   : CheckpointLoaderRandom                                                             __init__.py:83
           Load ok   : CheckpointLoaderSimpleText                                                         __init__.py:83
[15:59:17] wildcards card_path :                                                                         wildcards.py:36
           D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\..\..\wildc
           ards\**\*.txt
           cards file count :  0                                                                        wildcards.py:187
           wildcards test : aest                                                                        wildcards.py:218
           wildcards test : *test                                                                       wildcards.py:219
           wildcards test : ?est                                                                        wildcards.py:220
           wildcards test : test                                                                        wildcards.py:221
           wildcards test : /test                                                                       wildcards.py:222
           wildcards test : /0/test                                                                     wildcards.py:223
           Load ok   : CLIPTextEncodeWildcards                                                            __init__.py:83
           Load ok   : LoraLoaderText                                                                     __init__.py:83
           Load ok   : LoraLoaderTextRandom                                                               __init__.py:83
           Load ok   : Random_Sampler                                                                     __init__.py:83
           Load ok   : VAELoaderDecode                                                                    __init__.py:83
           Load ok   : VAELoaderText                                                                      __init__.py:83
Total VRAM 24564 MB, total RAM 32581 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
           Load ok   : SimpleSampler                                                                      __init__.py:83
           Load ok   : SaveImageSimple                                                                    __init__.py:83
           Load ok   : TextWildcards                                                                      __init__.py:83
──────────────────────────────────────────────────────  init end  ──────────────────────────────────────────────────────

Import times for custom nodes:
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-nodes
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Loopchain
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds (IMPORT FAILED): D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds (IMPORT FAILED): D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff
   0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.1 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly
   0.1 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.2 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by ShivaeAI** [comment]
@ltdrdata

**Comment by ltdrdata** [comment]
> Prestartup times for custom nodes: 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 24564 MB, total RAM 32581 MB Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync VAE dtype: torch.bfloat16 Using pytorch cross attention
> 
> ### Loading: ComfyUI-Impact-Pack (V4.28.2)
> ### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
> ### Loading: ComfyUI-Inspire-Pack (V0.33)
> ### Loading: ComfyUI-Manager (V0.36)
> ### ComfyUI Revision: 1643 [dd116abf] | Released on '2023-11-02'
> Traceback (most recent call last): File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff__init__.py", line 8, in import custom_mmpkg.custom_mmcv as mmcv File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv__init__.py", line 4, in from .fileio import * File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\fileio__init__.py", line 2, in from .file_client import BaseStorageBackend, FileClient File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\fileio\file_client.py", line 15, in from custom_mmpkg.custom_mmcv.utils.misc import has_method File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\utils__init__.py", line 3, in from .config import Config, ConfigDict, DictAction File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff\custom_mmpkg\custom_mmcv\utils\config.py", line 17, in from yapf.yapflib.yapf_api import FormatCode ModuleNotFoundError: No module named 'yapf'
> 
> Cannot import D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff module for custom nodes: No module named 'yapf' Traceback (most recent call last): File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr__init__.py", line 2, in from .vae import VAEDecodeBatched, VAEEncodeBatched File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\vae.py", line 5, in from .model.iter import try_get_iter File "D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr\model\iter.py", line 4, in from comfy.sd import ModelPatcher, CLIP, VAE ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)
> 
> Cannot import D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py) FizzleDorf Custom Nodes: Loaded **name** : ComfyUI_node_Lilly **file** : D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly__init__.py os.path.basename(**file**) : **init**.py os.path.splitext(os.path.basename(**file**))[0] : **init** working directory : D:\qiuye\ComfyUI\ComfyUI_windows_portable ───────────────────────────────────────────────────── init start ───────────────────────────────────────────────────── **name** : custom_nodes.ComfyUI_node_Lilly **file** : D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly__init__.py os.path.basename(**file**) : **init**.py os.path.splitext(os.path.basename(**file**))[0] : **init** working directory : D:\qiuye\ComfyUI\ComfyUI_windows_portable [15:59:17] Load ok : CheckpointLoaderRandom **init**.py:83 Load ok : CheckpointLoaderSimpleText **init**.py:83 [15:59:17] wildcards card_path : wildcards.py:36 D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly....\wildc ards***.txt cards file count : 0 wildcards.py:187 wildcards test : aest wildcards.py:218 wildcards test : *test wildcards.py:219 wildcards test : ?est wildcards.py:220 wildcards test : test wildcards.py:221 wildcards test : /test wildcards.py:222 wildcards test : /0/test wildcards.py:223 Load ok : CLIPTextEncodeWildcards **init**.py:83 Load ok : LoraLoaderText **init**.py:83 Load ok : LoraLoaderTextRandom **init**.py:83 Load ok : Random_Sampler **init**.py:83 Load ok : VAELoaderDecode **init**.py:83 Load ok : VAELoaderText **init**.py:83 Total VRAM 24564 MB, total RAM 32581 MB Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync VAE dtype: torch.bfloat16 Load ok : SimpleSampler **init**.py:83 Load ok : SaveImageSimple **init**.py:83 Load ok : TextWildcards **init**.py:83 ────────────────────────────────────────────────────── init end ──────────────────────────────────────────────────────
> 
> Import times for custom nodes: 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-nodes 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Loopchain 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_experiments 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts 0.0 seconds (IMPORT FAILED): D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite 0.0 seconds (IMPORT FAILED): D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff 0.0 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts 0.1 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly 0.1 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes 0.2 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager 0.3 seconds: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188 FETCH DATA from: D:\qiuye\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

It's not belongs to Impact-Pack.

Ask on here:
https://github.com/Fannovel16/ComfyUI-MotionDiff/issues

**Comment by hhh315xxx** [comment]
mybe you keep these vision:torch 2.1.2+cu118,torchaudio 2.1.2,torchvision 0.16.2,ultralytics 8.0.176,AND DO NOT UPDATE THEM!!!
I tried many times,when torch>=2.2.*,ultralytics=8.1.45,It doens't work anymore,and new erro:Loading: ComfyUI-Impact-Pack (V4.87.5)
module 'cv2' has no attribute 'setNumThreads'.
so,don't update them.

if still miss"ultralytics",but you sure it exists.

import ultralytics
print(ultralytics.__file__)

it prints "path\to\site-packages\ultralytics\__init__.py",
###it's ultralytics path will be needed next step"####
find the file "path\to\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py",
EDIT "subcore.py"

import sys
sys.path.append(r"path\to\site-packages")

###ultralyics's path#####

BEFORE

try:
    from ultralytics import YOLO
except Exception as e:
    print(e)
    print(f"\n!!!!!\n\n[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:\n\thttps://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md\n\n!!!!!\n")
    raise e
*****
*****
then save,restart comfyui.ultralytics will be found.
