### ISSUE TITLE
How to use MediaPipe Facemesh > SEGS

### ISSUE THREAD

**Issue by dalmackay** [ltdrdata/ComfyUI-Impact-Pack#164]
My goal is to make an automated eye-inpainting workflow. NOT the whole face, just the eyes. 

I started with a regular bbox>sam>mask>detailer workflow for the face and replaced the bbox node with mediapipe facemesh. This seemed to be the correct way of doing it. But no matter what parameters, the detailer is now skipped entirely (gives no errors, just outputs black squares in the alpha previews. 

How do I use the Facemesh node/ is there a better way of auto-inpainting eyes only?

**Comment by ltdrdata** [comment]
check force inpaint.
and drop_size.

I am preparing tutorial for that.

**Comment by ltdrdata** [comment]
I just read your question again in detail. When you mention that a black image appears, it means that MediaPipe FaceMesh did not detect anything. MediaPipe also has its limitations in detection.

First, try lowering the confidence threshold. If that doesn't work, another option is to use tricky way such as ksampling to transform the input into a form that MediaPipe can detect.

**Comment by Kinglord** [comment]
I'm having the same issue with the latest ComfyUI (as of today) and Impact pack (4.8.1). I updated my mediapipe in case that would solve the issue but I still get nothing but a small black box as my output from the bboxdetector (I'd guess 128x128). I'm using a high res (2k) portrait image of a face and I've lowered the threshold to as low as .10 and it still does not pick up any face or details. I also tried messing with the drop size from as low as 1 with no change. I can confirm it's not the detailer, I'm outputting the raw segs to an image list and it's just this black box.

**Comment by ltdrdata** [comment]
> I'm having the same issue with the latest ComfyUI (as of today) and Impact pack (4.8.1). I updated my mediapipe in case that would solve the issue but I still get nothing but a small black box as my output from the bboxdetector (I'd guess 128x128). I'm using a high res (2k) portrait image of a face and I've lowered the threshold to as low as .10 and it still does not pick up any face or details. I also tried messing with the drop size from as low as 1 with no change. I can confirm it's not the detailer, I'm outputting the raw segs to an image list and it's just this black box.

Take a look at the image processed by the Mediapipe preprocessor of the 'cnet aux' once. The Impact pack can only recognize what is detected there. Because the recognition performance of Mediapipe is not perfect, sometimes it may miss even when it seems quite obvious.

**Comment by Kinglord** [comment]
UPDATE - Got it working, see below.

~~I would if I could :) Neither node is working for me and I'm not sure why. If Impact Pack just uses the controlnet_aux mediapipe implementation then I will happily move my bug over there, but right now the cnet_aux and the Impact pack nodes are both doing nothing but outputting a full black 128x128 segs result. (i get one of these for each option I have enabled) The image I'm using works 100% fine when I run it through a hosted mediapipe facemesh pre-processor like on hugging face so I know my source image should be OK. I'm either doing something really wrong and dumb on the ComfyUI side or something else is up. If this is really a cnet_aux thing please let me know and I'll shuffle this over to the right spot. :)~~

I'd normally be happy to troubleshoot this myself but cnet_aux has no workflow shared that uses mediapipe (the full test workflow is missing it) and I'm not getting any kind of output I can see from the server when I run the node, certainly no errors.

I made sure to get the latest mediapipe as cnet_aux has it required, so I'm running 0.9.1.0 there, if that matters.

**Comment by Kinglord** [comment]
OK, I got it working! There was one thing that was throwing me for a major loop.

- SEGSToImage nodes don't work with the mediapipe result from SEGS nodes, they always return a small black box. Piping them through a a Mask List node into a mask to image node, works fine.

After wiring up the mask list to mask to image flow I was able to get both a proper SEGM Detector result and BBOX result. So I think we're good here! In case it helps I'll post a pic of the node flow.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/597488/d0bc08a1-7037-4562-bbfb-d925649d00f1)

**Comment by dalmackay** [comment]
> OK, I got it working! There was one thing that was throwing me for a major loop.
> 
> * SEGSToImage nodes don't work with the mediapipe result from SEGS nodes, they always return a small black box. Piping them through a a Mask List node into a mask to image node, works fine.
> 
> After wiring up the mask list to mask to image flow I was able to get both a proper SEGM Detector result and BBOX result. So I think we're good here! In case it helps I'll post a pic of the node flow.
> 
> ![image](https://user-images.githubusercontent.com/597488/268826594-d0bc08a1-7037-4562-bbfb-d925649d00f1.png)

I don't have "MediaPipeFaceMesh Detector Provider", that node doesnt exist. I'm up to date

**Comment by ltdrdata** [comment]
> > OK, I got it working! There was one thing that was throwing me for a major loop.
> > 
> > * SEGSToImage nodes don't work with the mediapipe result from SEGS nodes, they always return a small black box. Piping them through a a Mask List node into a mask to image node, works fine.
> > 
> > After wiring up the mask list to mask to image flow I was able to get both a proper SEGM Detector result and BBOX result. So I think we're good here! In case it helps I'll post a pic of the node flow.
> > ![image](https://user-images.githubusercontent.com/597488/268826594-d0bc08a1-7037-4562-bbfb-d925649d00f1.png)
> 
> I don't have "MediaPipeFaceMesh Detector Provider", that node doesnt exist. I'm up to date

This node belongs to `Inspire Pack` not the `Impact Pack`.
