### ISSUE TITLE
Detailer node bugging out, not respecting max_size

### ISSUE THREAD

**Issue by dalmackay** [ltdrdata/ComfyUI-Impact-Pack#166]
As I understand it, guide size is basically minimum size. If the detected face is smaller than guide size on the shortest side, it ignores it. If it's larger than guide size, it is SUPPOSED to upscale to the "max size".  It was doing this correctly for the past 2 days but suddenly did this. completely ignoring max size and just upscaling to some random arbitrary number, regardless of what i set as max_size or guide_size. I have a second pass of Detailer right after this that is set up the EXACT same way and it correctly upscales the region to max size. how do 2 clones of 1 node perform drastically different calculations? How can I guarantee that the max_size is respected? I can detect a **tiny** face and it doesnt upscale whatsoever before inpainting. just stays 100px or whatever. No matter what max_size is set at. 

![Screenshot 2023-09-14 124048](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/112755662/49fa1fdb-9f0a-4be0-a92e-f820c9a7841a)
![Screenshot 2023-09-14 124021](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/112755662/69b5f1eb-e769-4ac3-a01f-5bbb0b0db3b6)

**Comment by ltdrdata** [comment]
When guide_size_for is set as bbox, guide_size determines how much to upscale the shorter side of the bbox.

Originally, since the main purpose was for the face detailer, it was considered meaningless unless it drew larger. Therefore, if it's already sufficiently large, it is skipped.

Additionally, the forceInpaint feature was added later, making it useful for simple inpainting purposes as well.

Max_size serves as a safeguard against extreme enlargement due to elongated bboxes during the process of scaling down large variations to guide_size. It helps ensure that the enlargement value for larger variations remains smaller than max_size.

**Comment by dalmackay** [comment]
Ah okay, I had it backwards. Guide size determines what the box is scaled to, not max size. Thank you

Another question, how can i limit the process to only one face? if the image is a portrait but theres a crowd in the background, it starts with the main face but then inpaints every face in the background. I don't see a way to limit SAM/bbox/detailer to one mask. I thought thats what SAM_detector_Segmented was for, but no luck.

**Comment by ltdrdata** [comment]
> Ah okay, I had it backwards. Guide size determines what the box is scaled to, not max size. Thank you
> 
> Another question, how can i limit the process to only one face? if the image is a portrait but theres a crowd in the background, it starts with the main face but then inpaints every face in the background. I don't see a way to limit SAM/bbox/detailer to one mask. I thought thats what SAM_detector_Segmented was for, but no luck.

There are multiple ways. I'd explained approaches.

https://www.youtube.com/watch?v=9GSQlxZFrLI

**Comment by dalmackay** [comment]
> > Ah okay, I had it backwards. Guide size determines what the box is scaled to, not max size. Thank you
> > Another question, how can i limit the process to only one face? if the image is a portrait but theres a crowd in the background, it starts with the main face but then inpaints every face in the background. I don't see a way to limit SAM/bbox/detailer to one mask. I thought thats what SAM_detector_Segmented was for, but no luck.
> 
> There are multiple ways. I'd explained approaches.
> 
> https://www.youtube.com/watch?v=9GSQlxZFrLI

Thank you. One last question, do you know a way of doing this for Codeformer? It affects blurred background faces as well but I really need it in my workflow

**Comment by ltdrdata** [comment]
> > > Ah okay, I had it backwards. Guide size determines what the box is scaled to, not max size. Thank you
> > > Another question, how can i limit the process to only one face? if the image is a portrait but theres a crowd in the background, it starts with the main face but then inpaints every face in the background. I don't see a way to limit SAM/bbox/detailer to one mask. I thought thats what SAM_detector_Segmented was for, but no luck.
> > 
> > 
> > There are multiple ways. I'd explained approaches.
> > https://www.youtube.com/watch?v=9GSQlxZFrLI
> 
> Thank you. One last question, do you know a way of doing this for Codeformer? It affects blurred background faces as well but I really need it in my workflow

If you want to prevent Codeformer from affecting the background, you can select the desired SEGS using SEGSFilter, then create a mask using `SEGS to MASK (combined)`, and finally apply Codeformer to blend the modified image with the original image using `ImageCompositeMasked`.

When performing detection, it is recommended to slightly increase the mask size using dilation.
