### ISSUE TITLE
The processing speed of facedetailer, which only changes SEED, is very different between the two speeds.

### ISSUE THREAD

**Issue by suede299** [ltdrdata/ComfyUI-Impact-Pack#167]
Is this normal?
The processing speed of facedetailer, which only changes SEED, is very different between the two speeds.PresumablyProbably relevantProbably related 4Probably related 4-Probably 4-5 times more relevantProbably correlating 4-5 timesListen.Listen to the computerListen to the computer fanListening to the computer fan.Listening to the computer fan, likeListening to the computer fan, it looks like dryListening to the computer fan, it's like drying aListen to the computer fan, like dry for a whileListening to the computer fan, it's like doing a little bit of work and thenListening to the computer fan, it's like doing a little bit of work and thenListening to the computer fan, it's like working for a while and then taking a breakListening to the computer fan, it's like doing a bit of work and then resting for a fewListening to the computer fan, it's like working for a while and then resting for a few seconds
There is no error message from the console.
使用了sam model

**Comment by suede299** [comment]
The processing speed of FaceDetailer is bound to be very fast after starting Comfyui for the first time.

**Comment by ltdrdata** [comment]
It's not clear exactly what you're trying to say. Are you referring to changing the seed of FaceDetailer or changing the seed for the initial image generation upfront?

If the speed starts fast and then becomes extremely slow for the same image, it might be worth checking if your memory is running low.

**Comment by suede299** [comment]
Disabling xformers and switching to pytorch2.1 works fine. mem usage is causing it, I think.
