### ISSUE TITLE
How to use Person-Mask2Former? 'ConfigDict' object has no attribute 'layer_cfg'

### ISSUE THREAD

**Issue by poisenbery** [ltdrdata/ComfyUI-Impact-Pack#17]
Heyo, I was having lots of luck with the AnimeFace detector with the detailer node. It seems that it detects each face, and does an img2img on EACH one, resulting in very high quality outputs.
I downloaded the Person-Mask2Former model, thinking that it would work the same, but I get an error no matter what I try doing:

``` Traceback (most recent call last):
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  [Previous line repeated 1 more time]
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_pack.py", line 55, in load_mmdet
    model = core.load_mmdet(mmdet_path)
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_core.py", line 35, in load_mmdet
    model = init_detector(model_config, model_path, device="cpu")
  File "/home/poisenbery/AI_Stuff/ComfyUI/venv/lib/python3.10/site-packages/mmdet/apis/inference.py", line 61, in init_detector
    model = MODELS.build(config.model)
  File "/home/poisenbery/AI_Stuff/ComfyUI/venv/lib/python3.10/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/poisenbery/AI_Stuff/ComfyUI/venv/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/poisenbery/AI_Stuff/ComfyUI/venv/lib/python3.10/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
AttributeError: class `Mask2Former` in mmdet/models/detectors/mask2former.py: class `Mask2FormerHead` in mmdet/models/dense_heads/mask2former_head.py: 'ConfigDict' object has no attribute 'layer_cfg
```

How can I use Person-Mask2Former to achieve similar effect on multiple subjects?

**Comment by ltdrdata** [comment]
Unfortunately, the old mmdet model is no longer compatible with mmdet 3.0. Instead, there is an alternative approach using CLIPSeg. CLIPSeg generates masks based on prompts. For example, if you input "person," it will find the rough silhouette of a person. This can be converted and applied in the form of a binary mask, allowing for further applications.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/clipseg.md

**Comment by poisenbery** [comment]
I'm able to get that to work with "Face" prompt, but once I try to do something more complex, I get this error:

``` # of Detected SEGS: 1
Detailer: segment skip
Detailer: segment skip [determined upscale factor=0.5695216907675195]
Traceback (most recent call last):
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/poisenbery/AI_Stuff/ComfyUI/nodes.py", line 946, in save_images
    filename_prefix = compute_vars(filename_prefix)
  File "/home/poisenbery/AI_Stuff/ComfyUI/nodes.py", line 942, in compute_vars
    input = input.replace("%width%", str(images[0].shape[1]))
TypeError: 'NoneType' object is not subscriptable
```

I have been unable to get this workflow to work consistently. When I try to type "person" with multiple subjects, the console will tell me that it detects more SEGS than there are people, and it works for a while, but the output image looks unchanged, and the output "Cropped Refined" is a tiny box with barely any of the original image.

I'm following the node setup exactly but do not understand what I am doing wrong

**Comment by ltdrdata** [comment]
> I'm able to get that to work with "Face" prompt, but once I try to do something more complex, I get this error:
> 
> ```
> Detailer: segment skip
> Detailer: segment skip [determined upscale factor=0.5695216907675195]
> Traceback (most recent call last):
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 257, in execute
>     recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 128, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 75, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 68, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "/home/poisenbery/AI_Stuff/ComfyUI/nodes.py", line 946, in save_images
>     filename_prefix = compute_vars(filename_prefix)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/nodes.py", line 942, in compute_vars
>     input = input.replace("%width%", str(images[0].shape[1]))
> TypeError: 'NoneType' object is not subscriptable
> ```
> 
> I have been unable to get this workflow to work consistently. When I try to type "person" with multiple subjects, the console will tell me that it detects more SEGS than there are people, and it works for a while, but the output image looks unchanged, and the output "Cropped Refined" is a tiny box with barely any of the original image.
> 
> I'm following the node setup exactly but do not understand what I am doing wrong

Can you share your workflow? I need to reproduce that state.

**Comment by poisenbery** [comment]
![ComfyUI_00065_(1)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/d8dcb170-1a14-41d1-8e82-8d85d0eeebe6)

This is one of many attempts. I've been trying with multiple different node setups but cannot figure out how to do multi-subject detailing

**Comment by poisenbery** [comment]
I've been using the ClipSEG node with the HeatMap output to make sure that I'm not making some stupid user error, but it always manages to positively identify the prompt.
I have no idea what I am doing wrong.

I tried changing some settings and lowering threshold, but now console displays "# of Detected SEGS: 289"
But the image only has 2 or 3 people. So I'm VERY confused on what I am doing wrong.

**Comment by poisenbery** [comment]
![ComfyUI_00073_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/d2a9150a-1229-4c5c-ac68-4aea802ac961)
Here is another workflow where the ClipSEG model shows what I want, but the console has an error with 156 SEG detection.

**Comment by ltdrdata** [comment]
> ![ComfyUI_00073_](https://user-images.githubusercontent.com/78466408/239433026-d2a9150a-1229-4c5c-ac68-4aea802ac961.png) Here is another workflow where the ClipSEG model shows what I want, but the console has an error with 156 SEG detection.

The results of clipseg are not clear and are captured in a probabilistic form. Due to the fluctuating nature, there may be a phenomenon where many small masks, such as 1-pixel masks, are detected. This phenomenon can be improved by initially refining the mask using ToBinaryMask.

Furthermore, when fragmentation occurs, dilating the mask through dilation can prevent disconnected parts from being fragmented and allow them to be connected.

Rather than that, a more significant issue seems to arise when using CLIPSeg for human recognition, where it becomes challenging to distinguish and recognize overlapping individuals. In this case, the approach involves using the centroid of the mask points identified by CLIPSeg as the reference point to attempt detection with SAM.

**Comment by poisenbery** [comment]
@ltdrdata how do I get JUST a silhouette?

I managed to get a very convoluted setup to produce a silhouette, but it is not consistent and it makes me feel like I am not doing it correctly.

I tried looking at tutorials examples and the issue where other person got a silhouette, but I am very unclear on how to do it properly.
Here, it sort of works
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/89a6d56f-d8b5-4934-b5b2-48cd91d9f390)

But here it doesn't really work at all
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/21841bd7-c65a-4ca1-b4fe-fbd314cdec5a)

**Comment by ltdrdata** [comment]
> @ltdrdata how do I get JUST a silhouette?
> 
> I managed to get a very convoluted setup to produce a silhouette, but it is not consistent and it makes me feel like I am not doing it correctly.
> 
> I tried looking at tutorials examples and the issue where other person got a silhouette, but I am very unclear on how to do it properly.
> Here, it sort of works
> ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/89a6d56f-d8b5-4934-b5b2-48cd91d9f390)
> 
> But here it doesn't really work at all
> ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/21841bd7-c65a-4ca1-b4fe-fbd314cdec5a)
> 

You can adjust detect_hint, threshold to enhance silhouette. And you can use interactive SAM detector when you need highly precise mask.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/sam_with_preview_bridge.md

**Comment by poisenbery** [comment]
I still can't figure out how to do it with your nodes. I'm not clear on what any of the settings do, like "mask_hint" or "Mask_hint_use_negative" settings.

I found it much easier to just use semseg + math with masks and color channels to isolate the person

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/b8bf633f-47de-4246-8baa-e305e648b356)
