### ISSUE TITLE
ComfyUI completely freezes after render

### ISSUE THREAD

**Issue by CaptainGrock** [ltdrdata/ComfyUI-Impact-Pack#172]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/142545094/36b00deb-4efe-43e3-b4e0-4fbcfe25c9fe)

For some reason after having multiple render points, immediately after KSampler renders, the entire ComfyUI environment freezes. Browser still can operate but can't drag around or anything. Inspecting the interface points to an error with Impact nodes.  Anyone else experiencing this?

**Comment by ltdrdata** [comment]
This is fixed on 278fd6303c82b9a75451df23254ec49d7d5c1863.
