### ISSUE TITLE
HELP: cannot verify certificate/IMPORT FAILED

### ISSUE THREAD

**Issue by enaayyet** [ltdrdata/ComfyUI-Impact-Pack#179]
This is ending of my terminal code ending in a failed import with the impact pack...
 I'd greatly appreciate any help. I've been trying to fix this problem for the past month and nothing has worked. I've updated ComfUI, I've uninstalled and reinstalled it 5 times and don't know what's wrong. 
 Thank you in advance.
 
 File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

Cannot import /Users/keanudiaz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
Registered sys.path: ['/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_pycocotools', '/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_oneformer', '/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/__init__.py', '/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mmpkg', '/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_midas_repo', '/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_detectron2', '/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux', '/Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux/src', '/Users/keanudiaz/ComfyUI/custom_nodes/was-node-suite-comfyui/was_node_suite_comfyui', '/Users/keanudiaz/ComfyUI/comfy', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/git/ext/gitdb', '/Users/keanudiaz/ComfyUI', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages', '/var/folders/3j/0b6q6c_n0m97zlrpj619s3w00000gn/T/tmpwjy16psu', '../..', '/Users/keanudiaz/ComfyUI', '/Users/keanudiaz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules', '/Users/keanudiaz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules', '/Users/keanudiaz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/../..']

Import times for custom nodes:
   0.0 seconds: /Users/keanudiaz/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.1 seconds: /Users/keanudiaz/ComfyUI/custom_nodes/ComfyUI-Manager
   0.4 seconds (IMPORT FAILED): /Users/keanudiaz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   1.0 seconds: /Users/keanudiaz/ComfyUI/custom_nodes/was-node-suite-comfyui

**Comment by ltdrdata** [comment]
This is related to your computer's network settings.

First, try updating to the latest version. I've made sure that even if the installation process fails, you can proceed to the next steps. However, automatic installation doesn't guarantee the installation. You should manually install all the dependencies to ensure smooth execution.

And create an `impact-pack.ini` file in the ComfyUI-Impact-Pack directory and save the following:
```
[default]
dependency_version = 11
mmdet_skip = True
sam_editor_cpu = False
sam_editor_model = sam_vit_b_01ec64.pth
```

This step is merely a workaround for network issues and assumes that everything has been successfully installed. Network issues will need to be resolved on your end.

**Comment by enaayyet** [comment]
OK IT WORKED. THANK YOU. However, I now have a new problem. This error pops up:

When loading the graph, the following node types were not found:
UltralyticsDetectorProvider
Nodes that have failed to load will show as red on the graph.

**Comment by ltdrdata** [comment]
> OK IT WORKED. THANK YOU. However, I now have a new problem. This error pops up:
> 
> When loading the graph, the following node types were not found: UltralyticsDetectorProvider Nodes that have failed to load will show as red on the graph.

goto ComfyUI-Impact-Pack dir.
and execute this.
`git clone https://github.com/ltdrdata/ComfyUI-Impact-Subpack impact_subpack`

**Comment by enaayyet** [comment]
FIXED thank you.
