### ISSUE TITLE
The example with the *.ommx file does not work

### ISSUE THREAD

**Issue by lodinv** [ltdrdata/ComfyUI-Impact-Pack#18]
The example from [https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ONNX.md](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ONNX.md) [https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/misc/onnx.json](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/misc/onnx.json) does not work:

Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 981, in doit
    return (core.segs_to_combined_mask(segs), )
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_core.py", line 628, in segs_to_combined_mask
    shape = segs[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by ltdrdata** [comment]
Please check this error message before that error message

"ONNXDetector: unable to execute."

And during installation, the onnx model does not automatically download. Please also make sure to check if you have downloaded the model and placed it in ComfYUI/models/onnx.
( https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_base_checkpoint.onnx )

reference: https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ONNX.md

**Comment by lodinv** [comment]
Here is the full output of the messages in the console:

got prompt
ONNXDetector: unable to execute.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Restored from ../stable-diffusion-webui/models/VAE\vae-ft-mse-840000-ema-pruned.ckpt
Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 981, in doit
    return (core.segs_to_combined_mask(segs), )
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_core.py", line 628, in segs_to_combined_mask
    shape = segs[0]
TypeError: 'NoneType' object is not subscriptable

Prompt executed in 1.26 seconds

And of course I downloaded the file detector_v2_base_checkpoint.onnx in the folder H:\ComfyUI_windows_portable\ComfyUI\models\onnx

**Comment by lodinv** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8284477/25af6fea-93d5-4ba3-8452-4c39edce148a)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8284477/e7f3b211-fcc7-4e10-b6d5-14c0578f0be1)

**Comment by ltdrdata** [comment]
> Here is the full output of the messages in the console:
> 
> got prompt
> ONNXDetector: unable to execute.
> making attention of type 'vanilla-xformers' with 512 in_channels
> building MemoryEfficientAttnBlock with 512 in_channels...
> Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
> making attention of type 'vanilla-xformers' with 512 in_channels
> building MemoryEfficientAttnBlock with 512 in_channels...
> Restored from ../stable-diffusion-webui/models/VAE\vae-ft-mse-840000-ema-pruned.ckpt
> Traceback (most recent call last):
>   File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 257, in execute
>     recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
>   File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
>     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
>   File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
>     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
>   File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
>     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
>   File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 128, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 981, in doit
>     return (core.segs_to_combined_mask(segs), )
>   File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_core.py", line 628, in segs_to_combined_mask
>     shape = segs[0]
> TypeError: 'NoneType' object is not subscriptable
> 
> Prompt executed in 1.26 seconds
> 
> And of course I downloaded the file detector_v2_base_checkpoint.onnx in the folder H:\ComfyUI_windows_portable\ComfyUI\models\onnx
> 

Latest version gives you more detailed error message. Please, provide that infotmation.

**Comment by lodinv** [comment]
> Latest version gives you more detailed error message. Please, provide that infotmation.

got prompt
ONNXDetector: unable to execute.
This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Restored from ../stable-diffusion-webui/models/VAE\vae-ft-mse-840000-ema-pruned.ckpt
Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 983, in doit
    return (core.segs_to_combined_mask(segs), )
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_core.py", line 628, in segs_to_combined_mask
    shape = segs[0]
TypeError: 'NoneType' object is not subscriptable

Prompt executed in 2.11 seconds

**Comment by ltdrdata** [comment]
I just fixed this. Try latest version.

**Comment by lodinv** [comment]
Yes, it works now!
