### ISSUE TITLE
Add a 'select' as output to the "Switch(Any)" node

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#181]
I tried to have different "Switch(Any)" nodes use the same 'select', but when I converted the 'Switch(Any)' node's 'Select' to an input, the 'sel_mode' failed and was fixed to 'select_on_execution'. Please fix it and add a 'select' output.
Thank you so much for the node!

**Comment by ltdrdata** [comment]
![switch](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/8694fb60-2751-4872-9474-2ca33763b2d2)

I have no problem.
What is your workflow?

**Comment by mijuku233** [comment]
@ltdrdata  What I mean is that if 'select' is converted to input, even if 'sel_mode' is 'select_on_prompt', the "Switch(Any)" node is still fixed to run in 'select_on_execution' mode

**Comment by mijuku233** [comment]
@ltdrdata  This seems to happen when int is entered in other custom nodes. I will try to replace the int node to see if the effect is correct. If there is no problem, I will close this issue.
But I think it is a useful function to add select as output to "Switch(Any)"

**Comment by ltdrdata** [comment]
> @ltdrdata This seems to happen when int is entered in other custom nodes. I will try to replace the int node to see if the effect is correct. If there is no problem, I will close this issue. But I think it is a useful function to add select as output to "Switch(Any)"

When using 'select' as an input for `Switch (Any)`, it is restricted to cases involving  `Switch (Any)` and `Primitive`. For custom nodes of a third party, since the value is determined at execution time rather than at the prompt, the 'on prompt' functionality cannot be applied.

What is the reason for needing a `select` output?

**Comment by mijuku233** [comment]
@ltdrdata  I checked my workflow and the unexpected behavior was not due to other custom nodes.

When I output the value of the first 'Switch (Any)' to the 'select' of the second 'Switch (Any)', the situation mentioned above happens.

**Comment by ltdrdata** [comment]
> @ltdrdata I checked my workflow and the unexpected behavior was not due to other custom nodes.
> 
> When I output the value of the first 'Switch (Any)' to the 'select' of the second 'Switch (Any)', the situation mentioned above happens.

Yeah. It's the same situation. Even if 'select' itself is determined on prompt, however the value passed through the next `Switch (any)` is determined during execution.

**Comment by mijuku233** [comment]
@ltdrdata I built a simple workflow to show you the specific situation. I couldn't upload images, so I packaged the workflow into a zip file and uploaded it.

Under normal circumstances, only one 'Upscale Image (using Model)' node will be run. When both are run, it means that 'sel_mode' is fixed to 'select_on_execution'
[Switch.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12724391/Switch.zip)

**Comment by mijuku233** [comment]
So adding 'select' output to 'Switch (Any)' can effectively solve the problem

**Comment by mijuku233** [comment]
This workflow looks stupid. If directly use int to output to select, no unexpected problems will occur. But I did it to prevent others from entering values outside the 'select' range, because the workflow I built is for many people. For novices

**Comment by ltdrdata** [comment]
> This workflow looks stupid. If directly use int to output to select, no unexpected problems will occur. But I did it to prevent others from entering values outside the 'select' range, because the workflow I built is for many people. For novices

How about adding a cautionary note to the int node that goes into 'select'?

**Comment by mijuku233** [comment]
@ltdrdata  This is a minor problem and has little impact.
But it is still useful to add the 'select' output to the 'Switch (Any)' node, because many times I want to get the value of 'select', but I can only convert the 'selected label' to what I want in a troublesome way, and Since I have the AGLTranslation node installed, when I switch languages, the 'selected label' changes together, causing some unexpected behavior.

Also, I remembered that 'Preprocessor Provider (SEGS)' is missing 'lineart', will it be added in the future?

**Comment by ltdrdata** [comment]
> @ltdrdata  This is a minor problem and has little impact.
> But it is still useful to add the 'select' output to the 'Switch (Any)' node, because many times I want to get the value of 'select', but I can only convert the 'selected label' to what I want in a troublesome way, and Since I have the AGLTranslation node installed, when I switch languages, the 'selected label' changes together, causing some unexpected behavior.
> 
> Also, I remembered that 'Preprocessor Provider (SEGS)' is missing 'lineart', will it be added in the future?

Yeah. I am adding preprocessor provider one by one.

**Comment by ltdrdata** [comment]
> @ltdrdata This is a minor problem and has little impact. But it is still useful to add the 'select' output to the 'Switch (Any)' node, because many times I want to get the value of 'select', but I can only convert the 'selected label' to what I want in a troublesome way, and Since I have the AGLTranslation node installed, when I switch languages, the 'selected label' changes together, causing some unexpected behavior.
> 
> Also, I remembered that 'Preprocessor Provider (SEGS)' is missing 'lineart', will it be added in the future?

`selected_index` is added on 2263985df93c3ac81edb5c4ec477a44d2c5d5dcd.

![impactswitch](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/eeff50d4-4b94-4d6e-b929-768d4cc0aad9)


And 3 lineart preprocessor provider is implmented on latest `Inspire Pack`
