### ISSUE TITLE
ImageBatch node type not found

### ISSUE THREAD

**Issue by andreszs** [ltdrdata/ComfyUI-Impact-Pack#182]
Trying to test this [Instant Lora generator](https://civitai.com/articles/2345), I get missing node errors in both workflows.

**AloeVera_Insta-LoRA_workflow:**

- ImageBatch

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/10298071/22a714a9-5e78-4301-8b17-771379558af0)

Apparently, that node is used to combine several images and feed them to the Load IPAdapter node.

**AloeVera's_Instant-LoRA_V2:**

- ImpactWildcardProcessor
- LoadImagesFromDir //Inspire

I have alread set mmdet_skip = False in the INI file and restarted ComfyUI countless times. The Install Missing Custom Nodes option from ComfyUI Manager of course shows nothing, I just installed following the author's advice and it was pointless.

**Comment by ltdrdata** [comment]
ImageBatch is belongs to vanilla ComfyUI. You need to update ComfyUI.
And `LoadImagesFromDir //Inspire` is belongs to ComfyUI-Inspire-Pack.

I don't recommend turn off `mmdet_skip = False`. I will remove them eventually.
