### ISSUE TITLE
Error occurred when executing MaskToSEGS

### ISSUE THREAD

**Issue by 9nate-drake** [ltdrdata/ComfyUI-Impact-Pack#183]
`Cannot select an axis to squeeze out which has size not equal to one`

This is when doing img->mask and then mask->segs. It wasn't happening before the latest comfyui update as far as I'm aware

**Comment by ltdrdata** [comment]
Update your Impact Pack to latest version. That was already fixed.

**Comment by 9nate-drake** [comment]
Thanks, I had updated through gui but git pull worked
