### ISSUE TITLE
Inversed switch wont let me add an input to it

### ISSUE THREAD

**Issue by filliptm** [ltdrdata/ComfyUI-Impact-Pack#185]
for some reason, it won't let me add an input to the switch. when i change the selector to an input i can add a primitive, but i cant add anything else to the node

**Comment by ltdrdata** [comment]
> for some reason, it won't let me add an input to the switch. when i change the selector to an input i can add a primitive, but i cant add anything else to the node

Are you saying that it won't connect? Or that even when you connect, it doesn't add an input slot?

If you are referring former one.
When you first connect something, the type becomes fixed. Try adding a different Switch node to test it.

If you are referring latter one.
Share me the log to here.

Settings > Logging > View Logs > Export Logs

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/30b10254-28fe-43dc-a4fd-ff7041451e0e)

**Comment by filliptm** [comment]
so i fixed the problem. Not sure why the nodes get stuck, but sometimes im forced to delete and reload a noad in order for it to accept a connection (input)

The former btw^

something for you to look at, seems like a bug of sorts
