### ISSUE TITLE
REQ: improve wildcard processor - case insensitive, nested wildcards, globbing

### ISSUE THREAD

**Issue by halr9000** [ltdrdata/ComfyUI-Impact-Pack#186]
Looking at some of the wildcards I've collected, I see a few features they make use of which your processor doesn't have. Would be cool to look at some of them, starting with [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts/tree/main) [wildcards syntax](https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md#wildcards), such as: 

- case insensitive filename matching
- globbing in wildcard names
- nested wildcards - line from wildcard file can contain its own wildcard reference, which are usually going to assume relative paths

here's a live example: https://civitai.com/models/35438?modelVersionId=41660

Here's a quick peek at that wildcard set. I didn't give it camelcase, that was the author 🤷‍♂️ 

```
PS D:\hal\stable-diffusion\wildcards> ls .\battleCars\

    Directory: D:\hal\stable-diffusion\wildcards\battleCars

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           4/11/2023  4:51 AM           9176 battlecar.txt
-a---           4/11/2023  5:19 AM           1000 car.txt
-a---           4/11/2023  5:15 AM           3113 paintjob.txt

PS D:\hal\stable-diffusion\wildcards> type .\battleCars\battlecar.txt | select -First 5
(battlecar:1.1), __car__, __paintjob__, vehicle focus, no humans, car, wheel, tire, debris, fire, spike, debris, rock, dirty
(battlecar:1.1), __car__, __paintjob__, vehicle focus, no humans, car, wheel, tire, debris, fire, spike, debris, rock, clean
(battlecar:1.1), __car__, __paintjob__, vehicle focus, no humans, car, wheel, tire, debris, grass, rock, dirty
(battlecar:1.1), __car__, __paintjob__, vehicle focus, no humans, car, wheel, tire, debris, grass, rock, night, starry sky, moon, dirty
(battlecar:1.1), __car__, __paintjob__, vehicle focus, no humans, car, wheel, tire, debris, smooth floor, reflection, dirty 
```

Probably obvious, but  when I do this:

`__battlecars/battlecar__`

I get no match at all. When I do this:

`__battleCars/battlecar__`

I get this:

`(battlecar:1.1), __car__, __paintjob__, vehicle focus, no humans, car, wheel, tire, debris, green flames, blacktop, clean`

**Comment by ltdrdata** [comment]
Wildcard nesting feature is already provided.
And other features are under consideration.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/6497dccf-d9cb-4db2-aac4-fc3e6c759e6d)

Updated on 2275de80a81643960391258cad890081a6a551a8

**Comment by halr9000** [comment]
thx @ltdrdata you are awesome
