### ISSUE TITLE
annot handle this data type: (1, 1, 432, 3), |u1

### ISSUE THREAD

**Issue by filliptm** [ltdrdata/ComfyUI-Impact-Pack#187]
Im trying to use your nodes on an animate Diff pipeline im working on, is this just not possible or am i doing something wrong? Iv followed the Tut #2 on youtube

<img width="1007" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/55672949/10f63d00-4e8b-443b-8511-3a4eb711ff67">

**Comment by ltdrdata** [comment]
If you are handling batch latents you need to convert it to list.

You can change it through Rebatch Latent.
And Impact Pack provides other batch<->list converting nodes.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md

**Comment by filliptm** [comment]
> If you are handling batch latents you need to convert it to list.
> 
> You can change it through Rebatch Latent. And Impact Pack provides other batch<->list converting nodes.
> 
> https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md


I tried last night implementing your suggestion, i took the images instead of the latents and did the face fix on them, but when i went to combine the images with the Diff combine node, it didnt gif them, it turned it into a long string of images, one on top of the other. If you have time, having an example workflow of utilizing your detail fixers would be sick. 

Your nodes and work is amazing btw, much appreciateed

**Comment by ltdrdata** [comment]
I am traveling for few days.
I'll show when I back to home.

**Comment by ltdrdata** [comment]
Maybe you are same situation with this. https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/191
Check this.

**Comment by filliptm** [comment]
> Maybe you are same situation with this. #191 Check this.

so that WAS The problem, but Id like to request your nodes supporting batch ins, the problem is that when input as a list, it loses context in an animation context. You get the classic flicker effect because each frame is treated individually, defeating the purpose of animateDiff

**Comment by ltdrdata** [comment]
> > Maybe you are same situation with this. #191 Check this.
> 
> so that WAS The problem, but Id like to request your nodes supporting batch ins, the problem is that when input as a list, it loses context in an animation context. You get the classic flicker effect because each frame is treated individually, defeating the purpose of animateDiff

Strictly speaking, this is not a problem of list vs batch. The Detailer operates in the pixel space. To work in conjunction with AnimateDiff, a new form of Detailer for AnimateDiff, rather than the current one, will likely be needed.

I do have an idea, but I can only truly determine its effectiveness once I've actually tried it out.

**Comment by filliptm** [comment]
> > > Maybe you are same situation with this. #191 Check this.
> > 
> > 
> > so that WAS The problem, but Id like to request your nodes supporting batch ins, the problem is that when input as a list, it loses context in an animation context. You get the classic flicker effect because each frame is treated individually, defeating the purpose of animateDiff
> 
> Strictly speaking, this is not a problem of list vs batch. The Detailer operates in the pixel space. To work in conjunction with AnimateDiff, a new form of Detailer for AnimateDiff, rather than the current one, will likely be needed.
> 
> I do have an idea, but I can only truly determine its effectiveness once I've actually tried it out.

awesome, thanks for the breakdown! really interested to see what you come up with, your stuff has been amazing thus far
