### ISSUE TITLE
FaceDetailer feminizing male faces

### ISSUE THREAD

**Issue by albamuth** [ltdrdata/ComfyUI-Impact-Pack#189]
I have an img2img set up with Conditioning (Set Mask) where I apply "man with facial hair" to one character, and another conditioning mask for a woman in the same scene. Ultimate SD upscaler gives me an output of a man with facial hair and a woman that looks like the textual embedding, but then after FaceDetailer, the man's face is pretty much replaced with the woman's, and the woman's face is improved (as it should be). Attached workflow -- had to rename it from .json to .txt to upload.

It doesn't happen all the time, maybe about 60-70% when the faces are less than 100px.

[TG SD1.5 render to real 0.6.1.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12769082/TG.SD1.5.render.to.real.0.6.1.txt)
![ComfyUI_temp_puero_00415_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30302177/dd01bdd5-2978-4a80-8ed8-2d969df3ac17)
![ComfyUI_temp_zzsbn_00415_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30302177/1e806667-3b3a-4c03-b8e8-e55165eaebcb)

**Comment by ltdrdata** [comment]
Show me the screenshot of your workflow.
I cannot use computer for a while.

**Comment by ltdrdata** [comment]
I inspected your workflow
One combined text prompt contains this 
```
embedding:LivaHendriks woman
```

That feminize the mans face.
You should separate facedetailer's prompt with SD Upscaler's prompt.

Face Detailer only affect to face portion unlike upscaler.
The `woman` prompt will affect strongly than upscaler.

**Comment by albamuth** [comment]
The conditioning for the embedding was set to a mask, as you can see in the
workflow. I have a different condition mask set for any areas that the
ClipSEG detects "man" and that embedding was for areas detecting "woman".
It was working for Upscaler, because in images with both men and women,
they were being conditioned properly. It seems that Facedetailer was
ignoring the condutioning masks.

**Comment by ltdrdata** [comment]
FaceDetailer generates its own crop region and mask region, applying the prompt entered into the detailer. External masks are ignored.

If you want separated detailing. You need Detailer+SEGSFilter instead of FaceDetailer.

https://youtu.be/9GSQlxZFrLI
https://youtu.be/9ih35D2exMU
