### ISSUE TITLE
Mask to Segs not working?

### ISSUE THREAD

**Issue by poisenbery** [ltdrdata/ComfyUI-Impact-Pack#19]
I have a binary mask that I am passing through the Mask to Segs node, but it only shows a very small sliver of the mask.

I have literally no idea what I am doing wrong. This worked fine before with other sections of the body.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/e5516abf-5f19-4326-aa61-bcfd7e052d6f)

**Comment by ltdrdata** [comment]
It seems a bug. I need to check.

**Comment by ltdrdata** [comment]
I fixed this issue. Try this.
This issue occurred when the crop region exceeded the image area.
Thank you for the report.
