### ISSUE TITLE
AttributeError: 'PromptServer' object has no attribute 'add_on_prompt_handler'

### ISSUE THREAD

**Issue by webhappy99** [ltdrdata/ComfyUI-Impact-Pack#190]
Image Pack isn't showing at all, and I'm getting this error in the log file:

### Loading: ComfyUI-Impact-Pack (V4.13.2)
Traceback (most recent call last):
  File "C:\Users\xxx\pinokio\api\comfyui.pinokio.git\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxx\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 66, in <module>
    import impact.impact_server  # to load server api
  File "C:\Users\xxx\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 243, in <module>
    server.PromptServer.instance.add_on_prompt_handler(onprompt)
AttributeError: 'PromptServer' object has no attribute 'add_on_prompt_handler'

Cannot import C:\Users\xxx\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: 'PromptServer' object has no attribute 'add_on_prompt_handler'
### ComfyUI Revision: 1336 [443402c3] | Released on '2023-08-23'

ComfyUI is up to date.

Did git reset --hard
git pull
as suggested here: https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/178

It just shows "Already up to date."

What else can I try?

Thanks!

**Comment by ltdrdata** [comment]
Your ComfyUI version is old.
That revision should be over 1500. But your version is around 1300.

**Comment by ltdrdata** [comment]
> Your ComfyUI version is old.
> That revision should be over 1500. But your version is around 1300.

Updating was failed or your ComfyUI is invalid clone.

**Comment by ltdrdata** [comment]
Your ComfyUI version is outdated.
That revision should be over 1500. But your version is around 1300.

Updating was failed or your ComfyUI is invalid clone.

**Comment by webhappy99** [comment]
Thanks for the quick reply!

It looks like the one click installer that's in Pinokio hasn't been updated for a bit. I'll try reinstalling Comfy another way.
