### ISSUE TITLE
Animatediff Discussion

### ISSUE THREAD

**Issue by ardha27** [ltdrdata/ComfyUI-Impact-Pack#191]
How to use it with https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved ??
Because animatediff input is batch image, FaceDetailer can't process it. i try to use rebatch latents but it make the image become glitch
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/48845217/8a2cdad6-2955-45bb-a080-ae8d665db8bf)

**Comment by ltdrdata** [comment]
In that case ImpactImageToBatchToImageList is more easy.

Remove RebatchLatent and add ImageBatchToImageList right before of FaceDetailer.

**Comment by ardha27** [comment]
![AnimateDiff_00022_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/48845217/708e1a29-0f49-4fe4-bf72-40e00e19c122)
![AnimateDiff_00021_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/48845217/4c3ffdac-6a65-4d83-a087-3bce4f3e828c)

Thanks it's work but i think i need to improve some parts

**Comment by ardha27** [comment]
![AnimateDiff_00023_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/48845217/dbce1f3e-6edb-43e7-8c8a-c66d29c60601)

nvm, adding character name on wildcard fix it

**Comment by APZmedia** [comment]
I'm also interested in a batch approach into Animatediff. When working in  batches of images, sadly animatediff "forgets" its context window, so if you make a batch of 10 images, every 10 images continuity is lost.  Is there any workaround for this? Some way to infuse the last frame of the batch into the next 10 images, or something in order for animatediff to pick up where it left on the last batch?
