### ISSUE TITLE
 UltralyticsDetectorProvider Error 

### ISSUE THREAD

**Issue by MrMax7** [ltdrdata/ComfyUI-Impact-Pack#192]
[comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12775796/comfyui.log)
[comfyui.prev.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12775797/comfyui.prev.log)
[comfyui.prev2.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12775798/comfyui.prev2.log)

@ltdrdata Thank you for taking the time with me.

**Comment by ltdrdata** [comment]
> [comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12775796/comfyui.log)
> [comfyui.prev.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12775797/comfyui.prev.log)
> [comfyui.prev2.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12775798/comfyui.prev2.log)
> 
> @ltdrdata Thank you for taking the time with me. 

Oh... Your certificate is failing..
There are 2 options.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/179
https://github.com/ltdrdata/ComfyUI-Manager/issues/102

**Comment by MrMax7** [comment]
Man FIXED! Thank you so much! @ltdrdata
