### ISSUE TITLE
OSError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by webhappy99** [ltdrdata/ComfyUI-Impact-Pack#193]
After installing the windows portable version of ComfyUI, I'm now getting the following issue:

[!] DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
 Installing collected packages: opencv-python, pandas, thop, seaborn, ultralytics
[!] ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'A:\\Comfy\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd'
[!] Consider using the `--user` option or check the permissions.

Comfy and extensions are all up to date.

Any ideas?

**Comment by ltdrdata** [comment]
Deprecation is not important.
We cannot handle such problems.

Problem is the permission problem.
There are 2 possibilities.

One is real permission problem.

Another reason is that some custom nodes of ComfyUI are already using that package, causing a lock. When installing using Manager, it installs dependencies when ComfyUI is restarted, so it doesn't trigger this issue.

If you've tried reinstalling using Manager or reinstalling the dependency package while ComfyUI is turned off and you still have the issue, then you should check the your file permissions.

**Comment by webhappy99** [comment]
Thanks for the quick reply.

I closed ComfyUI, changed the permissions of that file (gave it full control for that user), and reinstalled Impact Pack via the Manager.

Unfortunately, its still giving me the same error! :(

**Comment by ltdrdata** [comment]
Upload your comfy.log, comfy.prev.log, comfy.prev.log.

Then I'll take a look at that.

**Comment by webhappy99** [comment]
Thank you, I really appreciate it! :)

[comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12776592/comfyui.log)
[comfyui.prev.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12776593/comfyui.prev.log)
[comfyui.prev2.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12776594/comfyui.prev2.log)

**Comment by ultimatech-cn** [comment]
you can try to install the package by following command
..\python_embeded\python -m pip install

**Comment by webhappy99** [comment]
Thanks, I appreciate your help, but that's a bit beyond my skill level.

I've tried a few other things to get it working, but at this point in time I've wasted enough time on ComfyUI, and decided just to go back to A1111. Its slower, but less hassle!
