### ISSUE TITLE
Failed to download lbpcascade_animeface.xml 

### ISSUE THREAD

**Issue by thecat99z** [ltdrdata/ComfyUI-Impact-Pack#194]
Since a recent git pull a few days ago I now get this message each time I launch ComfyUI

**Failed to download lbpcascade_animeface.xml so please download it yourself.**

I would do it but is this the one from this repo ? https://github.com/nagadomi/lbpcascade_animeface

And then where do I put this 'lbpcascade_animeface.xml' file ?

**Comment by ltdrdata** [comment]
That is not related to Impact Pack.
