### ISSUE TITLE
I cannot install it. Please help

### ISSUE THREAD

**Issue by SekaizaEarthza** [ltdrdata/ComfyUI-Impact-Pack#196]
![Screenshot 2023-10-02 195447](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/126684089/08c1bf75-1463-43d0-8499-b6f7dd453bd5)
![Screenshot 2023-10-02 195526](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/126684089/0a45e826-312e-40a4-a69f-ba15c78910e3)

**Comment by SekaizaEarthza** [comment]
![Screenshot (5228)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/126684089/f87a847c-f900-462a-b81e-03c24c3f49ed)

**Comment by ltdrdata** [comment]
I recommend install through ComfyUI-Manager.

https://github.com/ltdrdata/ComfyUI-Manager
