### ISSUE TITLE
Mask to Segs Error

### ISSUE THREAD

**Issue by var1ableX** [ltdrdata/ComfyUI-Impact-Pack#197]
I'm feeding an image with a mask to the Mast To Segs node and am getting the following error:

- "cannot select an axis to squeeze out which has size not equal to one"
- Seems to work if the Mask comes from Face Detailer but not from Load Image as Mask or Load Image etc.
Any advice much appreciated.

**Comment by ltdrdata** [comment]
First, please check if your `ComfyUI` and `Impact Pack` are up to date.

**Comment by var1ableX** [comment]
Yes they're up to date - I use colab and mostly everything is updated every time. That said I went through the fetch updates etc process to confirm. Workflow attached in image.

I'm mostly curious to see whether using SEGSDetailer for inpainting results in higher quality output (I notice the way I'm doing it right now every inpainting iteration is slight worse than the last.

![segsdetailer_workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/839040/4c32eefc-270a-4f94-b45b-9a609a68e652)

**Comment by var1ableX** [comment]
It's working - my Impact Pack was out of date - seems the fetch updates approach to updating isn't reliable - needed to uninstall / reinstall. Thanks.

**Comment by ltdrdata** [comment]
> It's working - my Impact Pack was out of date - seems the fetch updates approach to updating isn't reliable - needed to uninstall / reinstall. Thanks.

The "fetch update" is not actually performing an update but simply fetching update information. The actual update process requires unchecking the "skip update check" option and manually updating through the "Install custom nodes" dialog.

Due to environments where the fetch and update check processes take several minutes, it was changed to be performed explicitly.

Your ComfyUI-Manager is probably outdated as well. If you update it, you'll find an additional menu called "Update All." This menu not only fetches but also performs actual updates.

**Comment by var1ableX** [comment]
> > It's working - my Impact Pack was out of date - seems the fetch updates approach to updating isn't reliable - needed to uninstall / reinstall. Thanks.
> 
> The "fetch update" is not actually performing an update but simply fetching update information. The actual update process requires unchecking the "skip update check" option and manually updating through the "Install custom nodes" dialog.
> 
> Due to environments where the fetch and update check processes take several minutes, it was changed to be performed explicitly.
> 
> Your ComfyUI-Manager is probably outdated as well. If you update it, you'll find an additional menu called "Update All." This menu not only fetches but also performs actual updates.

I didn't realize the significance of the checkbox. Here's what I did:
1. I fetched updates
2. I waited a while and it said updates fetched everything is up to date (but i recall having been through this before)
3. I clicked on Install Custom Nodes and got the "updating database etc message" (waited quite a long time and eventually tried refreshing browser but it continued to be in updating database state")
4. Finally I got into the list of custom nodes and I filtered on "Updates" but nothing appeared in the list anyway...?

I guess I need to check the checkbox as well for all of that to work...

**Comment by ltdrdata** [comment]
if it says `everything is up to date` it means you don't have any updates. Then you don't need to try update.
