### ISSUE TITLE
Edit DetailerPipe has basic_pipe as output

### ISSUE THREAD

**Issue by Harebat** [ltdrdata/ComfyUI-Impact-Pack#20]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132880886/88084f1f-c0cd-43d1-865a-df49c46fa2ed)

If I want to use FaceDetailer with CLIPSegDetectorProvider to target other thing than faces it obviously can't connect and I'm unsure if the bbox_detector and the sam_model will be in the basic_pipe.

**Comment by ltdrdata** [comment]
This issue is fixed.
