### ISSUE TITLE
Plz make the ImpactWildcardEncode find the path automatic(if without)

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#201]
Plz make the ImpactWildcardEncode find the path automatic(if without)

![Sp231006-075632](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/5c277a6d-fa62-46a6-bd87-d8a499dcb0e9)

for example power prompt
https://github.com/rgthree/rgthree-comfy 
and 
https://github.com/skfoo/ComfyUI-Coziness/

**Comment by ltdrdata** [comment]
I'll update it later.

**Comment by xueqing0622** [comment]
Thx, plz make wildcard find the path automatic too

**Comment by ltdrdata** [comment]
> Thx, plz make wildcard find the path automatic too

I plan to allow omitting the subfolder path only when the Lora name is unique, and not has a subfolder specification in prompt.

**Comment by xueqing0622** [comment]
> > Thx, plz make wildcard find the path automatic too
> 
> I plan to allow omitting the subfolder path only when the Lora name is unique, and not has a subfolder specification in prompt.

we can let it have judgment, if there is a path, then the priority of the path, 
if it can not find the lora, and then go to auto search. 
There are many friends used sdwebui befores, or directly paste the civitai's prompt for testing lora and checkpoint , 
they really need to have no path to auto search for features

but, it is your choice, 
how about "add  wildcard to prompt" button just like "select to add Lora" button

Still thx for such good extension, have a nice day!

**Comment by ltdrdata** [comment]
> > > Thx, plz make wildcard find the path automatic too
> > 
> > 
> > I plan to allow omitting the subfolder path only when the Lora name is unique, and not has a subfolder specification in prompt.
> 
> we can let it have judgment, if there is a path, then the priority of the path, if it can not find the lora, and then go to auto search. There are many friends used sdwebui befores, or directly paste the civitai's prompt for testing lora and checkpoint , they really need to have no path to auto search for features
> 
> but, it is your choice, how about "add wildcard to prompt" button just like "select to add Lora" button
> 
> Still thx for such good extension, have a nice day!

If you're talking about wildcards instead of Lora, you can use an asterisk (*).
Both `__*flower__` and `__*/Flower__` are possible. In this case, all items belonging to that name pattern wildcard will be the targets.

It is updated, recently.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md#syntax

**Comment by xueqing0622** [comment]
no I mean to add a button like this
![Sp231006-185036](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/1975b287-adfa-4206-84fc-3a63023019b5)
![Sp231006-185238](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/eaa23f97-c491-44d9-a67f-dbffd23a7510)

**Comment by ltdrdata** [comment]
> no I mean to add a button like this ![Sp231006-185036](https://user-images.githubusercontent.com/114840118/273186842-1975b287-adfa-4206-84fc-3a63023019b5.jpg) ![Sp231006-185238](https://user-images.githubusercontent.com/114840118/273186882-eaa23f97-c491-44d9-a67f-dbffd23a7510.jpg)

This is added on 6391fcb4577a0d79db09f3ba665f47a5aad9e132

**Comment by xueqing0622** [comment]
no show add wildcard button, but show error"

Prompt outputs failed validation
ImpactWildcardEncode:
- Required input is missing: Select to add Wildcard

**Comment by ltdrdata** [comment]
> no show add wildcard button, but show error"
> 
> Prompt outputs failed validation ImpactWildcardEncode:
> 
> * Required input is missing: Select to add Wildcard

Refresh your browser.

**Comment by ltdrdata** [comment]
> no show add wildcard button, but show error"
> 
> Prompt outputs failed validation ImpactWildcardEncode:
> 
> * Required input is missing: Select to add Wildcard

That is fixed now.
The issue was due to the Wildcard selector being improperly initialized. Now, the newly added ImpactWildcard should not trigger any errors. For the Wildcard nodes that have already been added, please ensure to touch the combo that is currently set to null or undefined at least once.

**Comment by xueqing0622** [comment]
yes, it works! 

Hope you can add  ImpactWildcardEncode  lora find the path automatic

https://civitai.com/models/45448/full-feature-fantasy-prompts-characters

you can take a look of this wildcard: it use lora too:
but the lora have no path,  I download the loras and need to Put it in some sort of folder.

[full-prompt-fantasy.txt](https://githubfast.com/ltdrdata/ComfyUI-Impact-Pack/files/12832327/full-prompt-fantasy.txt)

**Comment by ltdrdata** [comment]
> yes, it works!
> 
> Hope you can add ImpactWildcardEncode lora find the path automatic
> 
> https://civitai.com/models/45448/full-feature-fantasy-prompts-characters
> 
> you can take a look of this wildcard: it use lora too: but the lora have no path, I download the loras and need to Put it in some sort of folder.
> 
> [full-prompt-fantasy.txt](https://githubfast.com/ltdrdata/ComfyUI-Impact-Pack/files/12832327/full-prompt-fantasy.txt)

Now auto detection of lora supported on d2c2aa061a6cbf86dd4baf815dd73dd14feb3665

**Comment by xueqing0622** [comment]
Yes, it works!
Thx a lot!

**Comment by xueqing0622** [comment]
By the way, if the wild card or path have "space (keyboard)" , it will ignore the wildcard
![Sp231007-121047](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/873bf158-d3d0-41d2-a8fa-efdc281d00af)

**Comment by xueqing0622** [comment]
![Sp231007-121606](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/db384786-be95-4879-b944-19508bd6c5b9)
wildcard path auto-detection no finish!
if your have time, plz make wildcard path auto-detection too,

https://civitai.com/models/45448/full-feature-fantasy-prompts-characters
Because I also download the wildcards and need to Put it in some sort of folder, 

and in some case, wildcard include other wildcards: 
for example:the "character" wildcard include "eyecolor, hair-color, hair-female" wildcards, 
but they all in path "fullfeaturecharacter_v13/", 
so it can't read include wildcard if without wildcard path auto-detection
![Sp231007-121712](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/09c7c6af-1bce-476a-8987-fdfa52bac44b)

[character.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12836769/character.txt)
[eyecolor.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12836770/eyecolor.txt)
[hair-color.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12836771/hair-color.txt)
[hair-female.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12836768/hair-female.txt)

**Comment by xueqing0622** [comment]
you can see, with lora  wildcard path auto-detection, 
just  one wildcard have such good result,
![Sp231007-123438](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/4c5f9015-f0c9-4d66-85e4-0a3157919a2e)

![Sp231007-124128](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/0cc294d2-9390-4777-8f5a-f25e1474b799)

**Comment by ltdrdata** [comment]
> By the way, if the wild card or path have "space (keyboard)" , it will ignore the wildcard ![Sp231007-121047](https://user-images.githubusercontent.com/114840118/273362579-873bf158-d3d0-41d2-a8fa-efdc281d00af.jpg)

Yup. That is not allowed. It leads confusing of prompt. So. I have no plan to support it.

**Comment by xueqing0622** [comment]
There are a little bug when convert wildcardText to input and convert back to widget,
it is not work !
![Sp231007-135230](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/c87a6a63-1cd3-48f0-903a-ea1a37015061)

**Comment by ltdrdata** [comment]
> There are a little bug when convert wildcardText to input and convert back to widget, it is not work ! ![Sp231007-135230](https://user-images.githubusercontent.com/114840118/273366387-c87a6a63-1cd3-48f0-903a-ea1a37015061.jpg)

This is a conflict between pythongosssss's script. I recommend just don't do that.
