### ISSUE TITLE
if wildcard folder have some *.txt file format not right, (IMPORT FAILED)

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#202]
like this file, because the artist name, I use ANSI
[special.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12825875/special.txt)

And it make all [ComfyUI-Impact-Pack]  (IMPORT FAILED)
![Sp231006-080715](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/02e482a8-fdc5-4edd-9e2c-8fdbe287432d)

perhaps there are some other reason, plz make no so harshly  

for example, Random Prompts form comfyui-dynamicprompts have no such problem
https://github.com/adieyal/comfyui-dynamicprompts

but I like to use the ImpactWildcardEncode, it is best prompt tool for comfyui

**Comment by ltdrdata** [comment]
This is fixed on ac7472f25f3e92d2479bf421770e22640a0ff801

**Comment by xueqing0622** [comment]
Thx, it works! 
have a nice day
