### ISSUE TITLE
ControlNet Switch

### ISSUE THREAD

**Issue by BuffMcBigHuge** [ltdrdata/ComfyUI-Impact-Pack#203]
I'm trying to build a ControlNet switch system where I can switch between different preprocessors by changing the switch value.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/20268348/4ec22300-c767-44e9-a066-04a7040c94ed)

The `ImpactSwitch` and `ImpactInversedSwitch` tend to work well with similar node arrangements, however it fails when used with the preprocessors in this way.

```
TypeError: 'NoneType' object is not iterable
```

Seems like the DWPreprocessor errors when given 0 images. I would presume the switch wouldn't activate the node it at all. 

Note that if I remove the inverse switch, the system works however it needlessly preprocesses through the unused ControlNets.

**Comment by ltdrdata** [comment]
For the 'select' operation, only the original 'Primitive' and 'ImpactInt' are allowed as inputs. 

'selected_index' has been added as an output solely in response to a request for providing selected information and is not compatible with 'select_on_prompt.' 

However, in this update(bca582bcbf516e45b2dbdf8f5932d79e813e71ed), I have made an exception to allow the 'selected_index' of 'ImpactSwitch' when 'select' is a widget and not indirectly connected.

**Comment by BuffMcBigHuge** [comment]
Works great thank you!
