### ISSUE TITLE
[Bug]KeyError occurs when using ImpactSwitch in workflow and calling through API

### ISSUE THREAD

**Issue by MoYiha** [ltdrdata/ComfyUI-Impact-Pack#205]
**Versions:**
  ComfyUI-Impact-Pack (V4.16.3)
  ComfyUI-Impact-Pack (Subpack: V0.2.3)
  ComfyUI-Inspire-Pack (V0.25)
  ComfyUI-Manager (V0.33)
  ComfyUI Revision: 1544 [1f2f4eaa] | Released on '2023-10-08'

**Error:**
  File "D:\AI\StableDiffusion\UI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\util_nodes.py", line 30, in doit
    nodelist = kwargs['extra_pnginfo']['workflow']['nodes']
KeyError: 'extra_pnginfo'

Workflow and json files:
[ImpactSwitch.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12840858/ImpactSwitch.zip)

Best Regards

**Comment by ltdrdata** [comment]
Do you use API mode?

Unfortunately, `ImpactSwitch`, `ImpactInversedSwitch` operate in a way that manipulates the workflow, so it cannot be used unless `extra_pnginfo` is appropriately provided in the API.

After PR931 is merged, nodes that can be used without such tricks will become available.

**Comment by MoYiha** [comment]
> Do you use API mode?

Yes, please check zip file, I tested it many times. Without using ImpactSwitch API works fine.
Thank you for replying so quickly.
