### ISSUE TITLE
how about make the ImpactWildcardEncode wildcard support  YAML-format

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#208]
how about make the ImpactWildcardEncode wildcard support  YAML-format

https://civitai.com/models/138970/billions-of-wildcards-all-in-one

**Comment by ltdrdata** [comment]
I'll update it later

**Comment by ltdrdata** [comment]
This is supported on aa3efdb4c379c728121026e99769fa342a049e2b
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md

**Comment by xueqing0622** [comment]
yes, it work,  you use "__astronomy.Celestial-Bodies__" to replace "__astronomy.Celestial-Bodies__" in write.

but it is easy to get bug than before: after I write some wrong wildcard, it don't work again.
And show error in CMD:

Error handling request
Traceback (most recent call last):
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 193, in populate_wildcards
    populated = wildcards.process(data['text'], data.get('seed', None))
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 127, in process
    text, is_replaced2 = replace_wildcard(pass1)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 96, in replace_wildcard
    replacement = random.choice(wildcard_dict[keyword])
  File "random.py", line 378, in choice

**Comment by xueqing0622** [comment]
And the yaml support not so perfect:
just try More on the sub-content
like"__BoMachines/random-machine__"  in your node should be "__BoMachines.random-machine__"
Not support good
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/604b1d51-c3ed-4c64-9d5b-fd354205bc4e)

and how to deal with this format: "__BoChars*/female/modern__"   "__clothings*__"
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/eb76d6b5-4055-42d1-aa27-e8e93fa76aef)

**Comment by ltdrdata** [comment]
> And the yaml support not so perfect: just try More on the sub-content like"**BoMachines/random-machine**" in your node should be "**BoMachines.random-machine**" Not support good ![image](https://user-images.githubusercontent.com/114840118/274267822-604b1d51-c3ed-4c64-9d5b-fd354205bc4e.png)
> 
> and how to deal with this format: "**BoChars*/female/modern**" "**clothings***" ![image](https://user-images.githubusercontent.com/114840118/274269632-eb76d6b5-4055-42d1-aa27-e8e93fa76aef.png)

Syntax is updated on 331ce16ddf23b1f856ae69e3417d736b0910fc92

Now use `/` instead of `.` and supports `$$` syntax.

**Comment by xueqing0622** [comment]
still bug, work with yaml easy to no  queue with any error output. 

use "__BoChars*/female/modern__"  or "__clothings*__" like this, will dead can queue without  any error output in CMD
Must restart comfyui

**Comment by ltdrdata** [comment]
> still bug, work with yaml easy to no queue with any error output.
> 
> use "**BoChars*/female/modern**" or "**clothings***" like this, will dead can queue without any error output in CMD Must restart comfyui

It's just fixed. Update and try again.

**Comment by xueqing0622** [comment]
yes, it fixed! thanks
but still one problem:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/fb7e591e-b66a-4a73-b87e-3ca7085215aa)
If yaml have sub __wildcard__ define, you should read it again

**Comment by ltdrdata** [comment]
> yes, it fixed! thanks but still one problem: ![image](https://user-images.githubusercontent.com/114840118/274315356-fb7e591e-b66a-4a73-b87e-3ca7085215aa.png) If yaml have sub **wildcard** define, you should read it again

That should be populated. I guess the problem is `____`.

**Comment by ltdrdata** [comment]
Yeah. It was it... I've changed default sepeartor to ' ' instead of ''. The issue won't be appeared.

**Comment by xueqing0622** [comment]
You work so fast, I tested it many times, it's perfect Thanks for the modifications, it makes comfyui work even better!

I wish you a happy life and good health.
