### ISSUE TITLE
FR: Custom Workflows embed into the metadata

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#209]
My biggest concern about the Component (which is AMAZING!) is that I have to deal with distribution of the ## file.  Any plans to embed this into the metadata in some way?  I was thinking at the very least, they could be dropped to a group.

**Comment by ltdrdata** [comment]
When you "save full", the component will be included within the workflow.

When you drag and drop a workflow that contains these components, the components will automatically load and become available for use.

One thing to be aware of is that the current workflow component is in the experimental stage, and it may not be compatible once the structure changes in the future.
