### ISSUE TITLE
_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.

### ISSUE THREAD

**Issue by filipemeneses** [ltdrdata/ComfyUI-Impact-Pack#21]
With the workflow:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/10226292/d98e73e3-fca0-413c-a0d1-3488abb2e72e)
![1684851922_ComfyUI_00001_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/10226292/728e53fb-6102-42d0-b2bf-ba237928482b)

I get the following error:

```
Loads checkpoint by local backend from path: E:\code\stable-difusion\ComfyUI\models\mmdets\bbox/mmdet_anime-face_yolov3.pth
Traceback (most recent call last):
  File "E:\code\stable-difusion\ComfyUI\execution.py", line 197, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "E:\code\stable-difusion\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "E:\code\stable-difusion\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "E:\code\stable-difusion\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "E:\code\stable-difusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 109, 
in load_model
    sam = sam_model_registry[model_kind](checkpoint=modelname)
  File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\segment_anything\build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
  File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "E:\code\stable-difusion\ComfyUI\custom_nodes\ComfyUI_tagger\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "E:\code\stable-difusion\ComfyUI\custom_nodes\ComfyUI_tagger\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

**Comment by ltdrdata** [comment]
> With the workflow:
> 
> ![image](https://user-images.githubusercontent.com/10226292/240316348-d98e73e3-fca0-413c-a0d1-3488abb2e72e.png) ![1684851922_ComfyUI_00001_](https://user-images.githubusercontent.com/10226292/240316475-728e53fb-6102-42d0-b2bf-ba237928482b.png)
> 
> I get the following error:
> 
> ```
> Loads checkpoint by local backend from path: E:\code\stable-difusion\ComfyUI\models\mmdets\bbox/mmdet_anime-face_yolov3.pth
> Traceback (most recent call last):
>   File "E:\code\stable-difusion\ComfyUI\execution.py", line 197, in execute
>     recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
>   File "E:\code\stable-difusion\ComfyUI\execution.py", line 58, in recursive_execute
>     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
>   File "E:\code\stable-difusion\ComfyUI\execution.py", line 58, in recursive_execute
>     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
>   File "E:\code\stable-difusion\ComfyUI\execution.py", line 67, in recursive_execute
>     outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
>   File "E:\code\stable-difusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 109, 
> in load_model
>     sam = sam_model_registry[model_kind](checkpoint=modelname)
>   File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\segment_anything\build_sam.py", line 38, in build_sam_vit_b
>     return _build_sam(
>   File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
>     state_dict = torch.load(f)
>   File "E:\code\stable-difusion\ComfyUI\custom_nodes\ComfyUI_tagger\modules\safe.py", line 106, in load
>     return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
>   File "E:\code\stable-difusion\ComfyUI\custom_nodes\ComfyUI_tagger\modules\safe.py", line 151, in load_with_extra
>     return unsafe_torch_load(filename, *args, **kwargs)
>   File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 713, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: A load persistent id instruction was encountered,
> but no persistent_load function was specified.
> ```

I'd tested this.
I confirmed that this is caused by **ComfyUI_tagger** extension.

https://github.com/gamert/ComfyUI_tagger/blob/9f0e837ef0ca2db4375813e7dda92a36995e96ca/modules/safe.py#LL109C12-L109C12

Above code breaks, loading of SAM model.

The extension hook **normal torch.load** function like this.

https://github.com/gamert/ComfyUI_tagger/blob/9f0e837ef0ca2db4375813e7dda92a36995e96ca/modules/safe.py#LL190C1-L190C18

**Comment by filipemeneses** [comment]
Spot on! I didn't read the logs properly, a quick workaround was to remove the ComfyUI_tagger extension
