### ISSUE TITLE
Preview Bridge (and others) never cache on first run, and always re-execute a second time.

### ISSUE THREAD

**Issue by rgthree** [ltdrdata/ComfyUI-Impact-Pack#212]
Preview Bridge (and perhaps any other node with IMAGES input and output) always re-runs at least a second time even if nothing has changed. This has an effect on downstream nodes that may be more expensive to run (upscale, inpaint, etc).

Here's an overly-done example, which take five executions until absolutely no work is done, despite the fact that nothing changes in between each execution.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/476360/46654ba1-2975-49ff-9ee9-bafa9654deae

(Here's the workflow from the video):
![ComfyUI_00190_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/476360/c8131c27-2aad-4352-b2f7-fb04d2516cdf)

**Comment by ltdrdata** [comment]
Interestingly, I'm unable to reproduce it.

Anyway, I'd created PreviewBridge during a time when my understanding of the ComfyUI structure was lacking, so I anticipate potential issues and plan to review and update it.

**Comment by rgthree** [comment]
Weird; I cannot repro either now. I wonder what was going on..

**Comment by ltdrdata** [comment]
I have refactor the structure of `PreviewBridge` into a much simpler and more stable one that no longer relies on front.
