### ISSUE TITLE
Regional Prompt Noise Issue - KSamplerAdvancedProvider 

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#218]
I am trying to work with the regional prompt injection and am running into an issue with the KSamplerAdvancedProvider not resolving the noise from the region.  It seems to be missing something, but the workflow seems to be valid.  Thoughts?
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8366665/dcaff350-3aed-4b14-9cc4-b4eb01b46b6f)

**Comment by ltdrdata** [comment]
I can load that workflow. Can you upload workflow file?

**Comment by sedetweiler** [comment]
[workflow (19).json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12881734/workflow.19.json)

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/5bc4f6af-d6cf-461c-880c-617394ceaeb1)

Convert the CLIPSeg mask to binary mask. It will solve that issue.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/201a7353-07b2-434d-9bbb-216debd254de)

**Comment by ltdrdata** [comment]
If you're not planning to change the "negative" part, there's no need for the "New Prompt For Inpaint" section. You can directly write it in the wildcard section of Regional Prompt Simple.

**Comment by ltdrdata** [comment]
I found and fixed a bug where RegionalPromptSimple's wildcard was always ignoring the positive in basic_pipe, even when it was empty. Please update the `Inspire Pack`.

**Comment by sedetweiler** [comment]
Thank you!  You keep on kicking ass my friend!

**Comment by sedetweiler** [comment]
Did you notice a huge shift in the contrast of the resulting regionally corrected image as well?  It is always quite a bit different even if the schedulers, steps, and CFG are the same.  Any ideas on preventing that?

**Comment by sedetweiler** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8366665/581bfddf-6df6-4f17-acc8-3a74d83d20a2)

**Comment by sedetweiler** [comment]
I plan to get a video out about this today (hopefully).

**Comment by sedetweiler** [comment]
Yeah, I can't seem to get away from the contrast increase using the same workflow using the advanced regional prompt.  It's huge!   My example will make you laugh I bet. :-)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8366665/36f97f92-8f76-4340-8a95-f02854fd2e74)

**Comment by sedetweiler** [comment]
Just looking at the flowers for example shows a large increase in contrast with no other changes.

**Comment by ltdrdata** [comment]
> Just looking at the flowers for example shows a large increase in contrast with no other changes.

It's probably due to the overlapping areas caused by the overlap_factor. The overlapping areas have both region sample and base sample sampling applied. This can result in oversampling compared to other areas.

On the other hand, if you reduce the overlap areas too much, artifacts can appear at the boundary.

**Comment by sedetweiler** [comment]
I have not found that overlap to be a setting I can alter much, or things go sideways quickly.  Perhaps we need more control here in some way?

**Comment by ltdrdata** [comment]
`Regional Sampler` is a node that I, too, am still researching for its usage.

**Comment by sedetweiler** [comment]
Perhaps a clamp distance where the region prompt can't alter?  I really think this is a pretty great idea, and I plan to also try some large bands across the image to test how we can use this rather than the composite prompting methods we have elsewhere.

**Comment by ltdrdata** [comment]
> Perhaps a clamp distance where the region prompt can't alter? I really think this is a pretty great idea, and I plan to also try some large bands across the image to test how we can use this rather than the composite prompting methods we have elsewhere.

How about applying Dynamic Thresholding once?

![dt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/04c35b39-e6d5-4ae9-9123-6df414a3b47a)

Be cautious that the base sampler and regional sampler should either share a common model or use completely separate loaded checkpoints. If you load a single checkpoint and use one version with patches like DT/Lora/FreeU, and the other without model patches, the overhead of swapping models for each sampler becomes significantly high.

**Comment by sedetweiler** [comment]
Dynamic Thresholding seems to help a bit, but it is also doing a lot of other damage.  While it is fixing one issue, it is causing others.

**Comment by sedetweiler** [comment]
It might just be a limitation of this method over other forms of inpainting.  It's still pretty great!
