### ISSUE TITLE
plz add preset text button like add lora and wildcard button in ImpactWildcardEncode

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#219]
the wildcard change to input easy to make error:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/f0cc1c1a-51f0-4e81-b97d-fdaeedb00585)

plz add preset text button like add lora and wildcard button in ImpactWildcardEncode

**Comment by ltdrdata** [comment]
Try connecting it to the populated_text, not the wildcard_text.
The wildcard_text is used for generation, while processing is done through populated_text. Also, unlike `ImpactWildcardEncode`, unlike `ImpactWildcardPreprocessor`, contains internal functionality to interpret and process wildcards, allowing it to be used in that manner.

**Comment by xueqing0622** [comment]
ok, as you sad, I think this is the way I can get presetText/wildcard/lora together:
![Sp231012-170548](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/0a72a114-3512-49dd-8516-c3539b6017cf)

so, if I want to add lora or wildcard, I should add button from ImpactWildcardEncode, and copy to ImpactWildcardPreprocessor,
how about give ImpactWildcardPreprocessor add lora and wildcard button.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/5735da31-3eb3-4e8a-876a-c74714a1f558)

**Comment by xueqing0622** [comment]
Yes, I get better idea, just write one preset as one wildcard, give a folder to them, and it easy to find by your ImpactWildcardEncode

I love to use ImpactWildcardEncode, Super super cool and handy just one node

**Comment by ltdrdata** [comment]
> ok, as you sad, I think this is the way I can get presetText/wildcard/lora together: ![Sp231012-170548](https://user-images.githubusercontent.com/114840118/274545859-0a72a114-3512-49dd-8516-c3539b6017cf.jpg)
> 
> so, if I want to add lora or wildcard, I should add button from ImpactWildcardEncode, and copy to ImpactWildcardPreprocessor, how about give ImpactWildcardPreprocessor add lora and wildcard button. ![image](https://user-images.githubusercontent.com/114840118/274546474-5735da31-3eb3-4e8a-876a-c74714a1f558.png)

I do plan to add a button in `ImpactWildcardPreprocessor` that allows you to add wildcards, similar to ImpactWildcardEncode. However, the Preprocessor is a node that deals purely with text, so it won't be able to incorporate LoRA-related functionality.

**Comment by xueqing0622** [comment]
of cause,  lora must have model output. It is my mistake, thx to take my advise.

**Comment by ltdrdata** [comment]
This is updated on V4.28.1
