### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by daizhuo** [ltdrdata/ComfyUI-Impact-Pack#22]
I used this version ComfyUI_windows_portable_nvidia_cu118_or_cpu, and run update_comfyui.bat
But still don't work.
Could you help me to solve this? Thank you so much!

Everytime I start ComfyUI, these message would come out.
What should I do?
I'm not a programmer, I don't know what are these means.
Thank you so much!

### ComfyUI-Impact-Pack: Check dependencies
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting openmim (from -r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b9/19/f7436e610163f65ff83de5a768180e73765e54bdaee5f5f37983aa3171b9/openmim-0.3.7-py2.py3-none-any.whl (51 kB)
Collecting segment-anything (from -r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/75/77/8e0c16abf151a1dd076b562febc0da2ecf1132b0b41826087af96f101f42/segment_anything-1.0-py3-none-any.whl (36 kB)
Requirement already satisfied: scikit-image in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from -r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (0.20.0)
Collecting Click (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl (96 kB)
Requirement already satisfied: colorama in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (0.4.6)
Collecting model-index (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0f/a6/4d4cbbef704f186d143e2859296a610a355992e4eae71582bd598093b36a/model_index-0.1.11-py3-none-any.whl (34 kB)
Collecting pandas (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/90/30/8b857447b0f4b59d5bd84e934e82ef8c82b73d71d1c9611c8aaaa8d44a50/pandas-2.0.1-cp310-cp310-win_amd64.whl (10.7 MB)
Requirement already satisfied: pip>=19.3 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (23.1.2)
Requirement already satisfied: requests in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (2.29.0)
Collecting rich (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/39/03/6de23bdd88f5ee7f8b03f94f6e88108f5d7ffe6d207e95cdb06d9aa4cd57/rich-13.3.5-py3-none-any.whl (238 kB)
Requirement already satisfied: tabulate in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (0.9.0)
Requirement already satisfied: numpy>=1.21.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (1.24.3)
Requirement already satisfied: scipy>=1.8 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (1.10.1)
Requirement already satisfied: networkx>=2.8 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (3.1)
Requirement already satisfied: pillow>=9.0.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (9.5.0)
Requirement already satisfied: imageio>=2.4.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (2.28.0)
Requirement already satisfied: tifffile>=2019.7.26 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (2023.4.12)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (1.4.1)
Requirement already satisfied: packaging>=20.0 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (23.1)
Requirement already satisfied: lazy_loader>=0.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3)) (0.2)
Requirement already satisfied: pyyaml in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from model-index->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (6.0)
Collecting markdown (from model-index->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9a/a1/1352b0e5a3c71a79fa9265726e2217f69df9fd4de0bcb5725cc61f62a5df/Markdown-3.4.3-py3-none-any.whl (93 kB)
Collecting ordered-set (from model-index->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/33/55/af02708f230eb77084a299d7b08175cff006dea4f2721074b92cdb0296c0/ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (2.8.2)
Collecting pytz>=2020.1 (from pandas->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7f/99/ad6bd37e748257dd70d6f85d916cafe79c0b0f5e2e95b11f7fbc82bf3110/pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d5/fb/a79efcab32b8a1f1ddca7f35109a50e4a80d42ac1c9187ab46522b2407d7/tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (2022.12.7)
Collecting markdown-it-py<3.0.0,>=2.2.0 (from rich->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bf/25/2d88e8feee8e055d015343f9b86e370a1ccbec546f2865c98397aaef24af/markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/34/a7/37c8d68532ba71549db4212cb036dbd6161b40e463aba336770e80c72f84/Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting mdurl~=0.1 (from markdown-it-py<3.0.0,>=2.2.0->rich->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: six>=1.5 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from python-dateutil>=2.8.2->pandas->openmim->-r D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1)) (1.16.0)
Installing collected packages: segment-anything, pytz, tzdata, pygments, ordered-set, mdurl, markdown, Click, pandas, model-index, markdown-it-py, rich, openmim
  WARNING: The script pygmentize.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mi.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown-it.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mim.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Click-8.1.3 markdown-3.4.3 markdown-it-py-2.2.0 mdurl-0.1.2 model-index-0.1.11 openmim-0.3.7 ordered-set-4.1.0 pandas-2.0.1 pygments-2.15.1 pytz-2023.3 rich-13.3.5 segment-anything-1.0 tzdata-2023.3
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pycocotools==2.0.6
  Downloading https://github.com/Bing-su/dddetailer/releases/download/pycocotools/pycocotools-2.0.6-cp310-cp310-win_amd64.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.0/76.0 kB 831.8 kB/s eta 0:00:00
Requirement already satisfied: matplotlib>=2.1.0 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from pycocotools==2.0.6) (3.7.1)
Requirement already satisfied: numpy in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from pycocotools==2.0.6) (1.24.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (1.0.7)
Requirement already satisfied: cycler>=0.10 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (1.4.4)
Requirement already satisfied: packaging>=20.0 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (23.1)
Requirement already satisfied: pillow>=6.2.0 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (9.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=2.1.0->pycocotools==2.0.6) (2.8.2)
Requirement already satisfied: six>=1.5 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools==2.0.6) (1.16.0)
Installing collected packages: pycocotools
Successfully installed pycocotools-2.0.6
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting openmim
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b9/19/f7436e610163f65ff83de5a768180e73765e54bdaee5f5f37983aa3171b9/openmim-0.3.7-py2.py3-none-any.whl (51 kB)
Collecting Click (from openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl (96 kB)
Requirement already satisfied: colorama in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim) (0.4.6)
Collecting model-index (from openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0f/a6/4d4cbbef704f186d143e2859296a610a355992e4eae71582bd598093b36a/model_index-0.1.11-py3-none-any.whl (34 kB)
Collecting pandas (from openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/90/30/8b857447b0f4b59d5bd84e934e82ef8c82b73d71d1c9611c8aaaa8d44a50/pandas-2.0.1-cp310-cp310-win_amd64.whl (10.7 MB)
Requirement already satisfied: pip>=19.3 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim) (23.1.2)
Requirement already satisfied: requests in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim) (2.29.0)
Collecting rich (from openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/39/03/6de23bdd88f5ee7f8b03f94f6e88108f5d7ffe6d207e95cdb06d9aa4cd57/rich-13.3.5-py3-none-any.whl (238 kB)
Requirement already satisfied: tabulate in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from openmim) (0.9.0)
Requirement already satisfied: pyyaml in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from model-index->openmim) (6.0)
Collecting markdown (from model-index->openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9a/a1/1352b0e5a3c71a79fa9265726e2217f69df9fd4de0bcb5725cc61f62a5df/Markdown-3.4.3-py3-none-any.whl (93 kB)
Collecting ordered-set (from model-index->openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/33/55/af02708f230eb77084a299d7b08175cff006dea4f2721074b92cdb0296c0/ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas->openmim) (2.8.2)
Collecting pytz>=2020.1 (from pandas->openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7f/99/ad6bd37e748257dd70d6f85d916cafe79c0b0f5e2e95b11f7fbc82bf3110/pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas->openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d5/fb/a79efcab32b8a1f1ddca7f35109a50e4a80d42ac1c9187ab46522b2407d7/tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: numpy>=1.21.0 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas->openmim) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->openmim) (2022.12.7)
Collecting markdown-it-py<3.0.0,>=2.2.0 (from rich->openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bf/25/2d88e8feee8e055d015343f9b86e370a1ccbec546f2865c98397aaef24af/markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich->openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/34/a7/37c8d68532ba71549db4212cb036dbd6161b40e463aba336770e80c72f84/Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting mdurl~=0.1 (from markdown-it-py<3.0.0,>=2.2.0->rich->openmim)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Requirement already satisfied: six>=1.5 in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from python-dateutil>=2.8.2->pandas->openmim) (1.16.0)
Installing collected packages: pytz, tzdata, pygments, ordered-set, mdurl, markdown, Click, pandas, model-index, markdown-it-py, rich, openmim
  WARNING: The script pygmentize.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown_py.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mi.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script markdown-it.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script mim.exe is installed in 'C:\Users\PC\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Click-8.1.3 markdown-3.4.3 markdown-it-py-2.2.0 mdurl-0.1.2 model-index-0.1.11 openmim-0.3.7 ordered-set-4.1.0 pandas-2.0.1 pygments-2.15.1 pytz-2023.3 rich-13.3.5 tzdata-2023.3
D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe: No module named mim
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 83, in ensure_mmdet_package
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1354, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 16, in <module>
    import install  # to install dependencies
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 124, in <module>
    install()
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 96, in install
    ensure_mmdet_package()
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 88, in ensure_mmdet_package
    subprocess.check_call(mim_install + ['mmcv==2.0.0'])
  File "subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['D:\\AI\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'mim', 'install', '--user', 'mmcv==2.0.0']' returned non-zero exit status 1.

Cannot import D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: Command '['D:\\AI\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'mim', 'install', '--user', 'mmcv==2.0.0']' returned non-zero exit status 1.

**Comment by aaron9412** [comment]
I remember seeing something like this. If you aren't using copys of comfy and impact-pack from this week, update. If you're using the standalone version of comfy on windows, you can download new copies and copy your old standalone (with the same folder name) to the new one (and click don't replace duplicate files) which will merge the files and leave your old installation as a backup.

**Comment by daizhuo** [comment]
> I remember seeing something like this. If you aren't using copys of comfy and impact-pack from this week, update. If you're using the standalone version of comfy on windows, you can download new copies and copy your old standalone (with the same folder name) to the new one (and click don't replace duplicate files) which will merge the files and leave your old installation as a backup.

Thank you so much!
I tried, but still not working.
ComfyUI come with update_comfyui.bat, this should update our ComfyUI, right?

**Comment by ltdrdata** [comment]
> I remember seeing something like this. If you aren't using copys of comfy and impact-pack from this week, update. If you're using the standalone version of comfy on windows, you can download new copies and copy your old standalone (with the same folder name) to the new one (and click don't replace duplicate files) which will merge the files and leave your old installation as a backup.

It seems that the symptoms are caused by a conflict between an external Python installation and the portable version of Python. Are you using it together with A1111?

**Comment by daizhuo** [comment]
> > I remember seeing something like this. If you aren't using copys of comfy and impact-pack from this week, update. If you're using the standalone version of comfy on windows, you can download new copies and copy your old standalone (with the same folder name) to the new one (and click don't replace duplicate files) which will merge the files and leave your old installation as a backup.
> 
> It seems that the symptoms are caused by a conflict between an external Python installation and the portable version of Python. Are you using it together with A1111?

I shared the model folder between Comfy and A1111. 
Even I don't run A1111, it still show these error messages.
What should I do? 
Thank you so much!

**Comment by daizhuo** [comment]
Try open "ComfyUI-Impact-Pack/install.py" 
First Step, del this:
pip_install = [sys.executable, '-s', '-m', 'pip', 'install', '--user']
mim_install = [sys.executable, '-s', '-m', 'mim', 'install', '--user']
Keep this:
pip_install = [sys.executable, '-s', '-m', 'pip', 'install']
mim_install = [sys.executable, '-s', '-m', 'mim', 'install']

Finally, it works.

**Comment by ltdrdata** [comment]
> Try open "ComfyUI-Impact-Pack/install.py" 
> First Step, del this:
> pip_install = [sys.executable, '-s', '-m', 'pip', 'install', '--user']
> mim_install = [sys.executable, '-s', '-m', 'mim', 'install', '--user']
> Keep this:
> pip_install = [sys.executable, '-s', '-m', 'pip', 'install']
> mim_install = [sys.executable, '-s', '-m', 'mim', 'install']
> 
> Finally, it works.

I reflected this.
