### ISSUE TITLE
RegionalSampler Inference Issue

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#221]
In this example, the region is not rendering as expected as the noise seems to be halted early and refined without detail. I will attach the workflow.

**Comment by sedetweiler** [comment]
[workflow (20).json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12894495/workflow.20.json)

**Comment by sedetweiler** [comment]
Green armor?  Nope, and no matter the prompt, it always stays like this undetailed blanket.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8366665/d49486b0-f13b-4871-b4b1-c5038e077945)

**Comment by ltdrdata** [comment]
> Green armor? Nope, and no matter the prompt, it always stays like this undetailed blanket.

I was conducting an experiment before this issue emerged, and it seems to be a very effective solution. I set up the structure for the initial 1-3 steps, where strong denoising is done using KSamplerAdvanced, and then filled in the remaining steps through RegionalSamplerAdvanced.

Additionally, I added a strong CFG of about 13 to the armor region.

In fact, based on the results of this experiment, I have been preparing an upgrade for the RegionalSampler, where only the initial n steps would use the base sampler.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/58fa8221-5696-4b90-8e31-06880eb6f296)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/a97e488c-0696-471d-ba87-f897f9b964bf)

![rs-workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/1a18c04f-6d56-4ecf-9597-c1d57250d771)

And this is the result I personally tested last night.
Certainly, it seems that applying the `Regional Sampler` after the structure has been established yields more natural results, as opposed to applying it before the structure is defined.

![rs2](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/82e51f1d-4b87-4b42-b911-7755c86ca4be)
![rs3](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/c2969dbe-03cc-4539-9e6f-9c96a28f61f0)

**Comment by ltdrdata** [comment]
This is the result of increasing the application of the 'base sampler only stage' from initial step 2 to step 3.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/03a11b2c-b945-4ce8-a58f-d48243d82d51)

**Comment by ltdrdata** [comment]
Ah, there was one mistake. The original basic usage is to set `return_with_leftover_noise` to true in KSamplerAdvanced and set `add_noise` to false in RegionalSamplerAdvanced. What I showed in the earlier example was meant for the purpose of closing noise once and then applying new noise to aim for the randomization effect of the second sampler.

With the basic configuration for sampling, you can achieve results like this.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/5276b745-612e-45aa-ae45-5cb2a8652cf8)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/b0157fdc-bae8-455b-98cd-2e3f9c6ae7f3)

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/60a643a3-4e9e-4d16-b76d-345c670e54f7)

Additional information is provided following the update of `RegionalSampler`.

`base_only_steps` sets the number of steps to sample using only the base sampler, as mentioned earlier.
`seed_2nd` is an option that applies only when `seed_2nd_mode` is not set to `ignore`. When this option is active, after sampling for the number of steps specified in `base_only_steps`, noise is first closed and then new noise is added with this seed. Please note that `randomize`, `increment`, and `decrement` options are related to `control_before_generate`, so be cautious. `seed±seed_2nd` adjusts the base seed relative to it, ensuring it changes together whenever the base seed changes.

With this update, the parameters of the previously created workflow's `RegionalSampler` have shifted, necessitating readjustment.
Setting `base_only_steps` to 0 and `seed_2nd_mode` to `ignore` will generate the same results as before.
