### ISSUE TITLE
Increase the "select" maximum value of “switch(any)” by 1

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#222]
**In some cases, the maximum value of `select` of `Switch(any)` is not enough, such as the following situation:** 

![4](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/423ead3b-a5f2-4635-8543-c51ddef56a98)

So please increase the maximum value of `select` by 1, thank you very much!

**Comment by ltdrdata** [comment]
This is modified on 7da864f88fb5099d02bbd41ec6e3137ea13c1fef
