### ISSUE TITLE
aliyunsdkcore error

### ISSUE THREAD

**Issue by THtianhao** [ltdrdata/ComfyUI-Impact-Pack#223]
Dear authors,

I am a plugin developer for ComfyUI. Recently, I have developed a plugin,

[[Portrait-Maker](https://github.com/THtianhao/ComfyUI-Portrait-Maker)](https://github.com/THtianhao/ComfyUI-Portrait-Maker)
My project needs to use modelscope pipeline, and in the requirement.txt, I need to install modelscope. 
However, it depends on  [aliyun-python-sdk-core](https://pypi.org/project/aliyun-python-sdk-core/)

and many users have reported encountering the aliyunsdkcore issue when using the `Windows integration package`(creating a virtual environment manually does not have this problem). like this:

```
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.13.36.tar.gz (440 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\albam\AppData\Local\Temp\pip-install-025cd5tn\aliyun-python-sdk-core_78b82f9b135341b1a2825e5884118385\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]
```

I have noticed that some situations are similar to those discussed in the issues, 
[https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/85](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/85)

and you have quickly resolved them. 
I would like to inquire about your solution. Thank you very much.

**Comment by ltdrdata** [comment]
This issue arises when trying to use a package based on `openmim`. Previously, the `Impact Pack` used it to work with `mmcv`, but now it's left in legacy mode, and support for it has been discontinued by default.

`mmcv` has such terrible backward compatibility issues when it updates that you often can't use models created with previous versions, requiring a fresh round of training. Additionally, there are many challenging situations with installations, such as pycocotools and aliyun packages, which can't be installed via pip and need to be installed through `openmim` and `mim` to work properly.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/84

In the past, this approach could work, but with the rise of `pytorch` and `python` versions, it's impossible to predict when compatibility issues might arise.

**Comment by zcfire2017** [comment]
E:\sd\comfyui\ComfyUI_windows_portable\python_embeded\python.exe -m pip install aliyun-python-sdk-core-v3==2.13.10
