### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by murphylanga** [ltdrdata/ComfyUI-Impact-Pack#225]
Since the last update my large workflow can no longer be displayed. After a browser update, I can move the window again, but when I want to change the zoom the browser freezes.

Here is the error message:

FETCH DATA from: C:\Spezial\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "C:\Spezial\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Spezial\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Spezial\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\Spezial\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "C:\Spezial\ComfyUI_windows_portable\ComfyUI\server.py", line 258, in view_image
    if filename[0] == '/' or '..' in filename:
IndexError: string index out of range

**Comment by ltdrdata** [comment]
There isn't enough information in this to assess the situation. Please provide a reproducible workflow file.

**Comment by rgthree** [comment]
I think this is `PreviewBridge` and I can +1; though it could have been the latest ComfyUI changes and not necessarily latest PreviewBridge changes.

(I was seeing #212 again so pulled ComfyUI and Impact and restarted, and am getting this error in the server. You should be able to repro with the workflow from #212.)

I see the same errors in the terminal, and the browser is locked (with partially drawn nodes) and console errors about not found temp files (because restart cleared them) and then a canvas error(s):

```
GET 404 http://127.0.0.1:8188/view?filename=$PB-_temp_pufsd_00001_.png [temp]&type=temp&subfolder=
```

Followed by:
```
app.js:631 Uncaught DOMException: CanvasRenderingContext2D.drawImage: Passed-in image is "broken"
    onDrawBackground http://127.0.0.1:8188/scripts/app.js:631
    drawNodeShape http://127.0.0.1:8188/lib/litegraph.core.js:8981
    drawNodeShape http://127.0.0.1:8188/scripts/app.js:1019
    drawNodeShape http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:84
    drawNode http://127.0.0.1:8188/lib/litegraph.core.js:8504
    drawNode http://127.0.0.1:8188/extensions/core/snapToGrid.js:86
    drawNode http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:28
    drawNode http://127.0.0.1:8188/scripts/app.js:1110
    drawFrontCanvas http://127.0.0.1:8188/lib/litegraph.core.js:7800
    draw http://127.0.0.1:8188/lib/litegraph.core.js:7715
    draw Choo
    onload http://127.0.0.1:8188/lib/litegraph.extensions.js:14
    updateBackground http://127.0.0.1:8188/lib/litegraph.extensions.js:13
    onChange http://127.0.0.1:8188/extensions/core/colorPalette.js:546
    addSetting http://127.0.0.1:8188/scripts/ui.js:252
    addCustomNodeDefs http://127.0.0.1:8188/extensions/core/colorPalette.js:407
    invokeExtensionsAsync http://127.0.0.1:8188/scripts/app.js:229
    #invokeExtensionsAsync http://127.0.0.1:8188/scripts/app.js:226
    registerNodesFromDefs http://127.0.0.1:8188/scripts/app.js:1336
    registerNodes http://127.0.0.1:8188/scripts/app.js:1331
    setup http://127.0.0.1:8188/scripts/app.js:1290
    async* http://127.0.0.1:8188/:14

```

**Comment by ltdrdata** [comment]
This is fixed already. `### Loading: ComfyUI-Impact-Pack (V4.21)`
What's you Impact Pack version?

**Comment by rgthree** [comment]
I've 4.22. I found the error (for me, at least), which can be mitigated by not adding to `node.imgs` if the image isn't found. [PR](https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/226)

**Comment by murphylanga** [comment]
Hello,
I have uploaded an example workflow.
I hope you can find the error with this.
Thank you very much for your effort.
If I use my “backup” Version 4.12  I have no problems.


[Murphylanga-SDXL_xx_fully_2023_Oct_13.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12908966/Murphylanga-SDXL_xx_fully_2023_Oct_13.json)



I removed the PreviewBridgeNodes from my workflow and replaced them with the standard preview. This is my workaround. Thank you for the fast reaction.

**Comment by ltdrdata** [comment]
This requires patch of `widgetInputs.js`. 
Upon further investigation, it turns out that it's not just my node that's causing the workflow to collapse. No matter how I try to resolve my part, eventually, the same issue causes a collapse in other nodes as well. I've reported it to pythongosssss for now. He will handle this.

**Comment by murphylanga** [comment]
Thanks a lot
