### ISSUE TITLE
Is the 'Preview Bridge' node broken?

### ISSUE THREAD

**Issue by Trobinou** [ltdrdata/ComfyUI-Impact-Pack#227]
When I run my workflow, the image appears in the 'Preview Bridge' node. I edit a mask using the 'Open In MaskEditor' function, then save my work using 'Save To Node'.

When I return to the workflow, the image no longer appears in the node. I just have the grey background of the node.

If I redo 'Open In MaskEditor', I don't have an image in the editor. There's no error message in the console, it's as if clicking on 'Save To Node' in the editor the first time deleted the image before closing.

**Comment by ltdrdata** [comment]
What is your Impact Pack version and ComfyUI version?
If it is not the latest version, update and retry.
If it is already latest version V4.23.8 then share me the workflow.

**Comment by Trobinou** [comment]
Here are the versions I had when this problem appeared:
ComfyUI-Impact-Pack (V4.23.7)
ComfyUI-Impact-Pack (Subpack: V0.2.4)
ComfyUI-Inspire-Pack (V0.30)
ComfyUI-Manager (V0.35.1)
ComfyUI Revision: 1575 [2231edec] | Released on '2023-10-14'

I've just updated everything, here are the current versions:
ComfyUI-Impact-Pack (V4.23.8)
ComfyUI-Impact-Pack (Subpack: V0.2.4)
ComfyUI-Inspire-Pack (V0.30)
ComfyUI-Manager (V0.36)
ComfyUI Revision: 1585 [88ceeb3f] | Released on '2023-10-17'

The problem has changed. Instead of having the image displayed in the node when I first run my workflow, I no longer have this image in the node and the image name displays $33-1.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132901709/d183e9cc-4d9c-4289-9d1d-8847f48463f2)

Here is the workflow: https://drive.google.com/file/d/1-JSmjbtYZGQajoUiqnXIHcDjPG9UD9jt/view?usp=sharing

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/e149f82f-a263-4e4d-a9bb-a46c05745f93)
![work](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/43ac70c5-2e1a-448e-80ef-eb9971fa9fb6)

Unfortunately, I failed to reproduce your issue. If you are using Colab, image loading may be slow or unstable due to network transfer speed issues. If you go to the settings and provide export logs, I will analyze them.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/e4541529-6ea5-4f10-9c79-3f96434933b0)

**Comment by Trobinou** [comment]
I understand your difficulty in locating this problem 😢
I'm using ComfyUI locally, it's the portable version on Windows 10 with Firefox 118.02 (but the result is the same with Edge).
Here's the link for the logs: https://drive.google.com/file/d/1-KJfoop7MRt2AMYSA8lXCCYxZmQtCSOq/view?usp=sharing
This corresponds to the launch of ComfyUI and then an execution of the workflow. 
Note that the name of the image, in the 'Preview Bridge' node, has changed since the last time. The name is now '$33-2'.

**Comment by ltdrdata** [comment]
> I understand your difficulty in locating this problem 😢
> I'm using ComfyUI locally, it's the portable version on Windows 10 with Firefox 118.02 (but the result is the same with Edge).
> Here's the link for the logs: https://drive.google.com/file/d/1-KJfoop7MRt2AMYSA8lXCCYxZmQtCSOq/view?usp=sharing
> This corresponds to the launch of ComfyUI and then an execution of the workflow. 
> Note that the name of the image, in the 'Preview Bridge' node, has changed since the last time. The name is now '$33-2'.

The new name format is intentional. It's not a problem. Physical file name cause several problem.

**Comment by Trobinou** [comment]
I may have the beginnings of a solution: I've tried again with the Edge browser and now everything's working! 
I've deduced that it could be coming from Firefox. So I started by deactivating all the extensions, without success. Using private browsing doesn't work either, nor does launching Firefox in 'safe' mode.

So for the moment I'm no further ahead but at least we've got a clue...

**Comment by ltdrdata** [comment]
> I may have the beginnings of a solution: I've tried again with the Edge browser and now everything's working! I've deduced that it could be coming from Firefox. So I started by deactivating all the extensions, without success. Using private browsing doesn't work either, nor does launching Firefox in 'safe' mode.
> 
> So for the moment I'm no further ahead but at least we've got a clue...

Oh.. I reproduced symptom on firefox. Gotcha.

**Comment by Trobinou** [comment]
The fact that you can reproduce this problem is good news 😊

**Comment by ltdrdata** [comment]
I just fixed this.
But, I found a ComfyUI bug related to firefox.

https://github.com/comfyanonymous/ComfyUI/pull/1797

It worked correctly when this patch was applied.

**Comment by Trobinou** [comment]
Fantastic! 💯👏👏👏
Many thanks 🙋‍♂️
