### ISSUE TITLE
Wildcard directory should be more flexible and allow for wildcards located outside of Comfy install

### ISSUE THREAD

**Issue by halr9000** [ltdrdata/ComfyUI-Impact-Pack#229]
I've got many wildcards which I maintain in a folder outside of my comfy install, been doing it that way forever w/auto1111 etc. I symlink that folder to impact/wildcards folder as shown below, and that's working for text files. However I'm getting a weird case where yaml file references are not working, and instead have `*/` inserted by the processor instead of a wildcard from that file.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/18482/3ccd19f6-dd26-4e35-a5c8-4f201e5087c8)

**Comment by halr9000** [comment]
Repro for what doesn't work with symlinks:

1. install comfy & impact
2. remove existing impact wildcards folder
3. create a symlink to an outside wildcards folder [howto [1](https://serverfault.com/q/7109/7096) and [2](https://stackoverflow.com/a/34905638/6637)]
4. try to use a wildcard syntax, eg. `__folder/filename__` or `__filename__`

I can get symlinks to work only by placing a symlink inside the wildcards folder, which then forces you to do `__symlinkname/folder/filename__` which isn't great. Or you can put symlinks to _folders inside your other wildcard folder_ into the impact wildcards folder. But that's high maintenance and also not great.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/18482/698e5c53-3aad-4386-b93e-4d4f199a2d98)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/18482/496aaf92-6a73-4121-bab5-caaba4a735b8)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/18482/16bdd45f-f1c3-4353-82da-c8de47cb4150)

**Comment by halr9000** [comment]
Wait a second -- it's working for files now, but not yaml. Updating OP.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/18482/20ab1cfb-8081-4001-a48a-fec0b302e2e3)

**Comment by ltdrdata** [comment]
The entries marked with `*/` are traces of unsuccessful wildcard populating attempts without the `*/` and retried by adding `*/` to them.

In the case of YAML wildcards, it does not match by the YAML file name; it matches only for the items contained within it.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/208

**Comment by ltdrdata** [comment]
Anyway you can now change custom_nodes dir on `impact-pack.ini`
