### ISSUE TITLE
can't run impact-pack

### ISSUE THREAD

**Issue by thezveroboy** [ltdrdata/ComfyUI-Impact-Pack#23]
i'm getting this error:

D:\ComfyUI_windows_portable\python_embeded\python.exe: No module named mim
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 83, in ensure_mmdet_package
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1195, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\__init__.py", line 16, in <module>
    import install  # to install dependencies
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 124, in <module>
    install()
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 96, in install
    ensure_mmdet_package()
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 88, in ensure_mmdet_package
    subprocess.check_call(mim_install + ['mmcv==2.0.0'])
  File "subprocess.py", line 369, in check_call
subprocess.CalledProcessError: Command '['D:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'mim', 'install', '--user', 'mmcv==2.0.0']' returned non-zero exit status 1.

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main module for custom nodes: Command '['D:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'mim', 'install', '--user', 'mmcv==2.0.0']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1195, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\__init__.py", line 3, in <module>
    from .sample import KSamplerSetting, KSamplerOverrided, KSamplerXYZ
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main\sample.py", line 5, in <module>
    import comfy.sample
ModuleNotFoundError: No module named 'comfy.sample'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr-main module for custom nodes: No module named 'comfy.sample'

**Comment by Nezarik-Intmax** [comment]
Try open "ComfyUI-Impact-Pack/install.py" and replace 22 and 23 lines from
`pip_install = [sys.executable, '-s', '-m', 'pip', 'install', '--user']`
`mim_install = [sys.executable, '-s', '-m', 'mim', 'install', '--user']`
 to
 `pip_install = [sys.executable, '-s', '-m', 'pip', 'install']`
`mim_install = [sys.executable, '-s', '-m', 'mim', 'install']`

**Comment by ltdrdata** [comment]
> Try open "ComfyUI-Impact-Pack/install.py" and replace 22 and 23 lines from
> `pip_install = [sys.executable, '-s', '-m', 'pip', 'install', '--user']`
> `mim_install = [sys.executable, '-s', '-m', 'mim', 'install', '--user']`
>  to
>  `pip_install = [sys.executable, '-s', '-m', 'pip', 'install']`
> `mim_install = [sys.executable, '-s', '-m', 'mim', 'install']`


Is --user option make trouble on portable version?

**Comment by Nezarik-Intmax** [comment]
> > Try open "ComfyUI-Impact-Pack/install.py" and replace 22 and 23 lines from
> > `pip_install = [sys.executable, '-s', '-m', 'pip', 'install', '--user']`
> > `mim_install = [sys.executable, '-s', '-m', 'mim', 'install', '--user']`
> > to
> > `pip_install = [sys.executable, '-s', '-m', 'pip', 'install']`
> > `mim_install = [sys.executable, '-s', '-m', 'mim', 'install']`
> 
> Is --user option make trouble on portable version?

Yes. The plugin does not work with --user. On portable version it does not let to install some packages because of access error. On the regular version if you connect it to venv from the portable version too. In my case at least...

**Comment by thezveroboy** [comment]
> Try open "ComfyUI-Impact-Pack/install.py" and replace 22 and 23 lines
thank you for answer but it doesn't work for me

**Comment by ltdrdata** [comment]
I noticed something was wrong from the early stages based on the error message.

```D:\ComfyUI_windows_portable\python_embeded\python.exe: No module named mim```

**openmim** should be installed during auto install process.
Show me the full startup log.

**Comment by Suzie1** [comment]
Hello, I'm getting a similar problem.

I get this error when I start ComfyUI:

Installing collected packages: opencv-python, mmengine, mmcv
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'F:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 23, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

In install.py the lines already have --user removed

if "python_embeded" in sys.executable or "python_embedded" in sys.executable:
    pip_install = [sys.executable, '-s', '-m', 'pip', 'install']
    mim_install = [sys.executable, '-s', '-m', 'mim', 'install']
else:
    pip_install = [sys.executable, '-s', '-m', 'pip', 'install']
    mim_install = [sys.executable, '-s', '-m', 'mim', 'install']

**Comment by ltdrdata** [comment]
> Hello, I'm getting a similar problem.
> 
> I get this error when I start ComfyUI:
> 
> Installing collected packages: opencv-python, mmengine, mmcv ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'F:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\cv2.pyd' Consider using the `--user` option or check the permissions.
> 
> Traceback (most recent call last): File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack__init__.py", line 23, in import mmcv ModuleNotFoundError: No module named 'mmcv'
> 
> In install.py the lines already have --user removed
> 
> if "python_embeded" in sys.executable or "python_embedded" in sys.executable: pip_install = [sys.executable, '-s', '-m', 'pip', 'install'] mim_install = [sys.executable, '-s', '-m', 'mim', 'install'] else: pip_install = [sys.executable, '-s', '-m', 'pip', 'install'] mim_install = [sys.executable, '-s', '-m', 'mim', 'install']

Show me the full error log.
It seems several errors occurred from other custom nodes.
And I am guessing some other custom node disturbing normal installation process.

ps. maybe you can solve this issue.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

If you could provide the error logs beforehand, it would be helpful for improving the installation script.

**Comment by Suzie1** [comment]
Hello, thank you, I think you were right, I was doing multiple installs on the same day, and a few of them had similar problems. I'm not sure where the error logs are, but I'll try find them. I managed to fix the problem with the help of my boyfriend. He installed the missing packages on his Python build and then sent me the files over Discord. We could identify the packages from the error messages in CMD. I just copied them into site-packages and it all works fine now. The packages were mmcv, mmdet, mmengine , terminaltables and shapely.
Btw, I absolutely love your ComfyUI Manager. Its awesome! All my friends are installing it now.

**Comment by ltdrdata** [comment]
> Hello, thank you, I think you were right, I was doing multiple installs on the same day, and a few of them had similar problems. I'm not sure where the error logs are, but I'll try find them. I managed to fix the problem with the help of my boyfriend. He installed the missing packages on his Python build and then sent me the files over Discord. We could identify the packages from the error messages in CMD. I just copied them into site-packages and it all works fine now. The packages were mmcv, mmdet, mmengine , terminaltables and shapely. Btw, I absolutely love your ComfyUI Manager. Its awesome! All my friends are installing it now.

Recently, it has been noticed that when multiple custom nodes are installed, conflicts can occur between them. Sometimes, instead of the install script of the Impact Pack being executed, the install script of another custom node is triggered. Therefore, the structure of the Impact Pack is currently being modified. In the future, installation will become easier and more streamlined.
