### ISSUE TITLE
Batch of images from a folder to Face Detailer pipeline?

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#231]
Hi. Amazing custom node suites. Thank you for sharing them with the community. 

I'm trying to understand if it's possible to load all the images from a specified folder and pass them, one by one, to the Face Detailer pipeline I created following your tutorials. 

I've seen the `Rebatch Latents` node, which doesn't apply to my use case, and the`Image List to Image Batch` node, which doesn't load the images from a folder. 

I also tried to use the `Load Image Batch` node in the WAS Node Suite, but it doesn't seem to pass the images in the folder to the `Simple Detector SEGS` node as I hoped. 

<img width="510" alt="Screenshot 2023-10-19 at 12 39 26" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/4d7cd72c-3774-4a22-8339-4bca35292a7a">

Clearly, I'm missing something. 

Any suggestion would be greatly appreciated. Thank you.

**Comment by ltdrdata** [comment]
![batch_to_list](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/193f2083-d23c-490d-9b16-f2aa5953ec41)

This is an example.

**Comment by alessandroperilli** [comment]
Yes, I arrived at the same conclusion shortly after opening the issue. Sorry about that and thank you for the quick confirmation.
