### ISSUE TITLE
latentsender/latentreciever doesnt work with inpaint?

### ISSUE THREAD

**Issue by mysteriousHerb** [ltdrdata/ComfyUI-Impact-Pack#232]
The preview window works - showing the mask etc.
But the actual latent image being sent to the ksampler seems to be the non masked vae?

**Comment by ltdrdata** [comment]
The delivery through LatentSender results in the loss of additional information other than the latent during the process of writing to a file. Try utilizing backend cache as a solution.

https://youtu.be/7wfe1DBAkoA?feature=shared
