### ISSUE TITLE
Regional Sampler why spend so many time? 

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#234]
Regional Sampler why spend so many time? 
I've tested it, and almost every regional prompt is computed separately and then cross-fired together, and it takes too long to call back and forth, so I'm not sure if it's a good idea to use it for the first time.
4 Regional prompts spend time: Prompt executed in 241.68 seconds
2 Regional prompts spend time: Prompt executed in 139.20 seconds

I've used this plugin before, they specify the number of different Regions, just a unified operation can be out of the map, only takes more than 10 seconds, even if there are more than 10 Regions, and do not have to crossfire, do not have to go back and forth calls
https://github.com/hako-mikan/sd-webui-regional-prompter

I wonder if there is a good way to fix this?

**Comment by ltdrdata** [comment]
They are totally different concept. A1111's `Regional Prompter` is equivalent to `attention couple`
https://github.com/laksjdjf/attention-couple-ComfyUI.

The `Regional Sampler` is, as the name suggests, applying completely independent samplers to each area. These areas include CFG, model (checkpoint, lora, freeu, dynamic thresholding, ipadatper, ...), prompt, sampler, and scheduler.

The `Regional Prompter` for A1111 is capable of separating and applying only prompts.

When using the `Regional Sampler`, it's important to be aware that you should either use the same checkpoint or completely independent checkpoints. Loading a checkpoint for one region and applying model patches such as `lora, freeu, DT, ipadapter, etc.`, while not applying them to another region or the base sampler, can result in significantly longer checkpoint transition times.

If such adjustments are not necessary and you simply want to separate prompts using a single sampler, you can also utilize the attention couple introduced earlier or make use of regional conditioning. These methods do not incur any additional overhead.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/regional-conditioning-img2img.png

**Comment by xueqing0622** [comment]
Thank you for answering my questions, I've benefited a lot from your tutorials and nodes.
