### ISSUE TITLE
FaceDetailer not working as of today

### ISSUE THREAD

**Issue by Piscabo** [ltdrdata/ComfyUI-Impact-Pack#236]
_** ComfyUI start up time: 2023-10-20 23:13:01.809618

Total VRAM 12288 MB, total RAM 32706 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention_

**Error occurred when executing FaceDetailer:**

Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:290 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:296 [backend fallback]
AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:382 [backend fallback]
AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:157 [backend fallback]

File "A:\AI_Files\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "A:\AI_Files\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "A:\AI_Files\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 422, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face
segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size)
File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 100, in detect
detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
File "A:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 27, in inference_bbox
pred = model(image, conf=confidence, device=device)
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\model.py", line 101, in __call__
return self.predict(source, stream, **kwargs)
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\model.py", line 242, in predict
return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\predictor.py", line 196, in __call__
return list(self.stream_inference(source, model, *args, **kwargs)) # merge list of Result into one
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
response = gen.send(None)
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\ultralytics\engine\predictor.py", line 263, in stream_inference
self.results = self.postprocess(preds, im, im0s)
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
preds = ops.non_max_suppression(preds,
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\ultralytics\utils\ops.py", line 243, in non_max_suppression
i = torchvision.ops.nms(boxes, scores, iou_thres) # NMS
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
File "A:\AI_Files\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 692, in __call__
return self._op(*args, **kwargs or {})

Close

**Comment by ltdrdata** [comment]
This issue is due to an incorrect version of your `torch`.

**Comment by Piscabo** [comment]
> This issue is due to an incorrect version of your `torch`.

Thank you. What must the version be? The requirements.txt does not have an entry for that?

**Comment by surebert** [comment]
How did you resolve this?

**Comment by jasongx0000** [comment]
解决了？

**Comment by jasongx0000** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/66294745/1c201f68-49bf-481b-ae15-b0202d23f278)
同样的情况，请问是哪里出了问题？

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/66294745/298090190-1c201f68-49bf-481b-ae15-b0202d23f278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTQwNTgsIm5iZiI6MTcwNTcxMzc1OCwicGF0aCI6Ii82NjI5NDc0NS8yOTgwOTAxOTAtMWMyMDFmNjgtNDliZi00ODFiLWFlMTUtYjAyMDJkMjNmMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDAxMjIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNjc4NjUzZTk3MzJkYmJhNmVlZTBlODBlM2I4MDY3ZWM4NTUwMTA3MTVmOWM0NjUyNDllOWQyOTUzNzA0MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n7WZCPTFNfPirUbWJPzcqs2XSNtOXjCuPkJoAndNt1g) 同样的情况，请问是哪里出了问题？

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/405

**Comment by serget2** [comment]
My car won't run, it's got no fuel in it. what fuel does it need? Complete silence no answer....
Seriously if you do not want to help shut up and stand by the sidelines, instead of dropping a faint hint and nothing more

**Comment by ltdrdata** [comment]
> My car won't run, it's got no fuel in it. what fuel does it need? Complete silence no answer.... Seriously if you do not want to help shut up and stand by the sidelines, instead of dropping a faint hint and nothing more

It means you need to reinstall torch.
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing

The method to reinstall torch depends on the environment you are in.
