### ISSUE TITLE
SEGM Detector (combined) node, add the classes option

### ISSUE THREAD

**Issue by hben35096** [ltdrdata/ComfyUI-Impact-Pack#238]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/105c3206-f0a7-4d89-be59-d6a69eabb9f5)

  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: airplane
  5: bus
  6: train
  7: truck
  8: boat
  9: traffic light
  10: fire hydrant
  11: stop sign
  12: parking meter
  13: bench
  14: bird
  15: cat
  16: dog
  17: horse
  18: sheep
  19: cow
  20: elephant
  21: bear
  22: zebra
  23: giraffe
  24: backpack
  25: umbrella
  26: handbag
  27: tie
  28: suitcase
  29: frisbee
  30: skis
  31: snowboard
  32: sports ball
  33: kite
  34: baseball bat
  35: baseball glove
  36: skateboard
  37: surfboard
  38: tennis racket
  39: bottle
  40: wine glass
  41: cup
  42: fork
  43: knife
  44: spoon
  45: bowl
  46: banana
  47: apple
  48: sandwich
  49: orange
  50: broccoli
  51: carrot
  52: hot dog
  53: pizza
  54: donut
  55: cake
  56: chair
  57: couch
  58: potted plant
  59: bed
  60: dining table
  61: toilet
  62: tv
  63: laptop
  64: mouse
  65: remote
  66: keyboard
  67: cell phone
  68: microwave
  69: oven
  70: toaster
  71: sink
  72: refrigerator
  73: book
  74: clock
  75: vase
  76: scissors
  77: teddy bear
  78: hair drier
  79: toothbrush

coco8-seg supports 79 types of selection, if add this "classes" option to the SEGM Detector (combined) node, using a model such as yolov8m-seg.pt, you can freely choose what to check, such as only the cat in the image above.
https://docs.ultralytics.com/modes/predict/#inference-sources

**Comment by ltdrdata** [comment]
This feature is added.
Now, `SEGM Detector` and `BBOX Detector` include the functionality of `SEGSLabelFilter`.

**Comment by hben35096** [comment]
I was very moved！
Thank you, thank you, thank you!

**Comment by hben35096** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/a9bc93bc-4f00-4f57-8691-59bfdff87bf2)
Great feature, the important thing is that the detection speed is very, very fast!

**Comment by hben35096** [comment]
I shared several yolo-seg models that have just been trained, including segmentation detection of faces, skin, and hair. Thanks again for creating such a great plugin.

https://github.com/hben35096/assets/releases/tag/yolo8

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/6bbc1bdd-b86a-4cb8-bd53-62ab6e5a5b6d)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/7edf32a2-5c9e-4bd9-a04e-8ef3457df563)

**Comment by ltdrdata** [comment]
> I shared several yolo-seg models that have just been trained, including segmentation detection of faces, skin, and hair. Thanks again for creating such a great plugin.
> 
> https://github.com/hben35096/assets/releases/tag/yolo8
> 
> ![image](https://user-images.githubusercontent.com/139383150/281426739-6bbc1bdd-b86a-4cb8-bd53-62ab6e5a5b6d.png) ![image](https://user-images.githubusercontent.com/139383150/281426927-7edf32a2-5c9e-4bd9-a04e-8ef3457df563.png)

These models are so good. We can skip use of SAM. :)
I'd registered these models to Manager.

Thank you for the sharing.

**Comment by hben35096** [comment]
It's my pleasure :D
