### ISSUE TITLE
 ComfyUI-CLIPSeg is no more update for the latest ComfyUI

### ISSUE THREAD

**Issue by daizhuo** [ltdrdata/ComfyUI-Impact-Pack#24]
Hi.... ComfyUI-CLIPSeg is no more update for the latest ComfyUI.
I can't install this plugin.
What's your plan for this？
Thank you！

**Comment by ltdrdata** [comment]
In that case I have to include into impact pack.

**Comment by ltdrdata** [comment]
> Hi.... ComfyUI-CLIPSeg is no more update for the latest ComfyUI. I can't install this plugin. What's your plan for this？ Thank you！

https://github.com/biegert/ComfyUI-CLIPSeg/issues/2

I checked this issue.
I have no problem with latest ComfyUI.

What kind of error message are you experiencing?

**Comment by daizhuo** [comment]
> > Hi.... ComfyUI-CLIPSeg is no more update for the latest ComfyUI. I can't install this plugin. What's your plan for this？ Thank you！
> 
> [biegert/ComfyUI-CLIPSeg#2](https://github.com/biegert/ComfyUI-CLIPSeg/issues/2)
> 
> I checked this issue. I have no problem with latest ComfyUI.
> 
> What kind of error message are you experiencing?


Thank you so much for your help!
My CMD window shows these message.
Sorry, I'm not a programmer, so I don't know what's going on.

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1375, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'

Cannot import D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'

**Comment by ltdrdata** [comment]
Oh.. you should not clone that repo.
Just download single .py file into custom\_nodes directory.

And I introduce this.

https://github.com/ltdrdata/ComfyUI-Manager

**Comment by daizhuo** [comment]
Wow.....
That's great!
I can use it now!
Thank you so much!
