### ISSUE TITLE
Does MediaPIpe FaceMesh Detector support nose?

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#240]
I learn to use MediaPIpe FaceMesh Detector from your tutor
https://www.youtube.com/watch?v=etsHl2TFEiQ
In special cases, I need to create templates for noses with segs, but there is no option for that.
Because I want to keep part of the skin material and the original nose.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/4ba1fdda-09ae-4dee-b18e-9d066fdd6372)
if no nose seg, the result is no good
Does MediaPIpe FaceMesh Detector support nose?
Or is there any way to automate the detection?

**Comment by ltdrdata** [comment]
MediaPipe FaceMesh doesn't provide nose info.
Maybe you can use clipseg to detect nose.

**Comment by xueqing0622** [comment]
clipseg can't do it ,  use  a couple  depth maps to compose it?

**Comment by xueqing0622** [comment]
the  segment_anything can detect nose:
https://github.com/storyicon/comfyui_segment_anything
