### ISSUE TITLE
Impact pack prevents ComfyUI opening

### ISSUE THREAD

**Issue by Drommer-Kille** [ltdrdata/ComfyUI-Impact-Pack#241]
If impact pack custom nodes are installed the start of ComfyUI stops here:
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V4.26.1)

After that it's back to command prompt. Both ComfyUI and Impact pack are latest versions. ComfyUI has no problems, but when opening a workflow that uses Impact pack, it can be installed bu comfy ui cannot be re-started.

**Comment by ltdrdata** [comment]
if you are using chrome.
Press F12. And show me the error log.

**Comment by drommerkiller** [comment]
I mean it stops to that. It never loads ComfyUI so there is nothing in chrome error log. In order to open comfyui again, i need to delete impact pack folder.

**Comment by ltdrdata** [comment]
> I mean it stops to that. It never loads ComfyUI so there is nothing in chrome error log. In order to open comfyui again, i need to delete impact pack folder.

It's a bit confusing. Wasn't there an issue reported when opening the workflow?

**Comment by Drommer-Kille** [comment]
I meant when i open a workflow that has Impact Pack nodes i get error for not having it, then i install it via manager and reload, but Comfy never opens as it gets stuck on loading impact pack. And only way to open comfy again is to delete impact pack folder.

**Comment by thecat99z** [comment]
Maybe a conflict with some other custom node ? 

Move all the other custom nodes you have into a backup directory and try with only impact-pack as custom node and see if it works.
If it works then re-add one by one the other custom nodes, launch comfyui and so on until you find what node is generating a conflict.

**Comment by ltdrdata** [comment]
> I meant when i open a workflow that has Impact Pack nodes i get error for not having it, then i install it via manager and reload, but Comfy never opens as it gets stuck on loading impact pack. And only way to open comfy again is to delete impact pack folder.

If an error occurs in the workflow, it may be due to a problem in the web browser's script. Since a workflow that has been opened once is stored in the browser's state, attempting to reopen that workflow may cause it to become unresponsive. Therefore, it is suggested to open the browser's developer console to check for any issues.

The symptoms you are describing are too vague for me to provide any specific assistance at the moment.

**Comment by rkjack** [comment]
I have the same issue, it only started happening after I updated a few days ago.

With the impact pack loading, it never gets past the custom nodes loading line for the impact pack on the console.  Typically it would then have a message waiting for connections to the web service it starts.

It never gets to that point where you can open comfyui on the browser.  After removing all of the plugins except manager, everything starts fine.  If I add comfyui-impact-pack back, then the problem comes back.  (I haven't tested other custom nodes yet, but this was the one it hits and bails back to the console prompt.

**Comment by rkjack** [comment]
I did try to add the WAS node suite and it also crashed, which leads me to believe that there might have been a breaking change made to ComfyUI that is affecting some custom node code.

**Comment by ltdrdata** [comment]
> I did try to add the WAS node suite and it also crashed, which leads me to believe that there might have been a breaking change made to ComfyUI that is affecting some custom node code.

What environment did you test this in?
local, colab, runpod, ...?

And would you be willing to test it with all custom nodes removed and only the `Impact Pack` installed?

**Comment by ltdrdata** [comment]
> > I did try to add the WAS node suite and it also crashed, which leads me to believe that there might have been a breaking change made to ComfyUI that is affecting some custom node code.
> 
> What environment did you test this in? local, colab, runpod, ...?
> 
> And would you be willing to test it with all custom nodes removed and only the `Impact Pack` installed?

**Comment by malibujack** [comment]
Sorry was on my work account before.  Yes, it is local, python 3.10, it was working up until a few days ago when I updated everything.  

I did indeed remove everything except the manager and impact pack and it still abruptly ended.  No messages or anything. I turned on verbose and didn't see much useful output before it just stopped. 

Disabling the impact pack (renaming the folder to xxxxx.disabled ) Comfy started working again.  Reinstalled all the other custom nodes and then disabled each and the only two that had issues were Impact-Pack and the WAS pack which I don't typically use so I removed it for now.

Something definitely changed, but I couldn't find the change set in Comfy, nor the impact pack where it was working again before I ran out of time to mess with it

**Comment by ltdrdata** [comment]
Update Impact Pack to latest version.

[__init__.py.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13211814/__init__.py.zip)

Extract and overwrite the `__init__.py` file in `custom_nodes/ComfyUI-Impact-Pack/` with this file.
By closely logging, I can determine at which stage it gets stuck.

**Comment by Drommer-Kille** [comment]
Here is the log with that init file:
Total VRAM 24576 MB, total RAM 130913 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
[Allor]: 0 standard nodes was overridden.
[Allor]: 12 modules enabled.
[Allor]: 95 nodes was loaded.
Using xformers cross attention
[IMPACT-DBG] STEP1
[IMPACT-DBG] STEP2
[IMPACT-DBG] STEP3
[IMPACT-DBG] STEP4
### Loading: ComfyUI-Impact-Pack (V4.27.8)
[IMPACT-DBG] STEP5
[IMPACT-DBG] STEP6

I'm running it local on Win11.

**Comment by ltdrdata** [comment]
> Here is the log with that init file: Total VRAM 24576 MB, total RAM 130913 MB xformers version: 0.0.21 Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync VAE dtype: torch.bfloat16 Using xformers cross attention [Allor]: 0 standard nodes was overridden. [Allor]: 12 modules enabled. [Allor]: 95 nodes was loaded. Using xformers cross attention [IMPACT-DBG] STEP1 [IMPACT-DBG] STEP2 [IMPACT-DBG] STEP3 [IMPACT-DBG] STEP4
> 
> ### Loading: ComfyUI-Impact-Pack (V4.27.8)
> [IMPACT-DBG] STEP5 [IMPACT-DBG] STEP6
> 
> I'm running it local on Win11.

[config.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13213062/config.zip)

Ok. Now overwrite this file. `ComfyUI-Impact-Pack\modules\impact\config.py`

Also, please upload the `ComfyUI-Impact-Pack\impact-pack.ini` file along with the log, and try deleting that file and restarting.

**Comment by rkjack** [comment]
[debugoutput.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13216925/debugoutput.txt)
[debugoutput_ok.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13216926/debugoutput_ok.txt)

both the config and __init__ added, debugoutput is when it abends with the pack,  debugoutput_ok is all custom nodes disabled (but it also works properly when everything but ComfyUI-Impact-Pack is enabled)

**Comment by rkjack** [comment]
Hopefully this helps.

**Comment by ltdrdata** [comment]
> Hopefully this helps.

This issue is fixed on V4.28.2.

goto `ComfyUI-Impact-Pack` in cmd.
and execute `git reset --hard && git pull`

**Comment by rkjack** [comment]
Can confirm fixed

**Comment by LLMfolders** [comment]
Still got the same issue guys! I just updated ComyUI Impact Pack in the Manager.
```
FETCH DATA from: C:\Users\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: C:\Users\...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
[WARN] ComfyUI-Impact-Pack: Error on prompt - several features will not work.
'prompt'
```

...
What was the problem that was fixed?
How to fix it today?

**Comment by LLMfolders** [comment]
Nevermind it worked.
Its because I tried to change the name of "prompt" into another value (json).
Thanks
