### ISSUE TITLE
Add step widget to queue trigger

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#242]
Add a 'steps' widget to 'Queue Trigger' for easily setting the number of iteration steps.
His logic is like this:
![queue 2023-10-25 024606](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/1d0cc668-508f-482c-9af3-fc74fe58bf94)
(When the number of steps is 0, this function is not enabled)

Finally, add the ‘steps’ to the output(Number of steps being iterated).

**Comment by ltdrdata** [comment]
You can turn it off through SetWidgetValue node.

I might consider adding a counter-type trigger later, but I don't think I'll be able to work on it until Saturday as I'll be out of home.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/6153e070-0633-4694-b450-4c2e119323d5)

Countdown Queue Trigger is added on V4.33
