### ISSUE TITLE
FaceDetailer use controlnet tile or dwopenpose not get the right position

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#245]
FaceDetailer use controlnet tile or dwopenpose not get the right position
no use controlnet 
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/74ac2802-ed35-47de-923c-14a8022a9d40)
use controlnet 
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/6fa3e316-ca2c-48b6-b894-5290f947c935)

use segs to detailer same error
It seems no align the position controlnet and facedetailer

but ok in kSampler use set latent noise mask
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/3973e409-f142-47c1-9021-614a514a6377)

this is the workflow
[facedetailer+controlnet_test.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13167550/facedetailer%2Bcontrolnet_test.json)

and this is source image 
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/784a385b-9241-4b5c-a7da-036f13437022)

**Comment by xueqing0622** [comment]
![Image text](https://i.imgur.com/E9kdRtd.gif)

**Comment by ltdrdata** [comment]
This is a version compatibility issue.

What are the versions of Impact Pack, Inspire Pack, and ControlNet Aux?

**Comment by xueqing0622** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/3c814349-e6a6-4c2b-9f76-9d33d06fc939)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/d40543c1-dcba-4507-af4d-3b0c7cdd0635)

**Comment by xueqing0622** [comment]
every version is latest

**Comment by ltdrdata** [comment]
> every version is latest

show me the `cnet_images` output.

**Comment by xueqing0622** [comment]
cnet_images output? do you mean output image from my computer

facedetailer
![t_00019_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/5b7b51e4-bd97-48f0-a7e6-b10b77d12af6)

Detailer(seg/pipe)
![t_00020_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/91511546-dc65-4b2f-961b-7b068c42e336)

kSampler with set latent noise mask
![ComfyUI_temp_ylojz_00001_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/0f5e56a3-387a-4dfe-a41d-1230fa67b745)

**Comment by ltdrdata** [comment]
![Screenshot_20231026_140815_Samsung Internet](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/b78abbc7-350f-4c71-910c-7c7720e554f1)

**Comment by xueqing0622** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/af11ea40-91ca-42c1-b185-0586c3c807dc)

It is mean no detected the face?

**Comment by ltdrdata** [comment]
> 
> ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/af11ea40-91ca-42c1-b185-0586c3c807dc)
> 
> It is mean no detected the face?

yup..
Try another controlnet.

**Comment by xueqing0622** [comment]
without controlnet the cnet-img also black

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/d291fe27-6b26-4296-a2d3-48969a49bea2)

but simple detector can read it

**Comment by xueqing0622** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/604b6889-5735-4f3c-a672-6eb448819375)
 Simplified to the simplest process, still can't recognize cnet-img.

this is workflow
[test-faceDetailer.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13173681/test-faceDetailer.json)

**Comment by ltdrdata** [comment]
> without controlnet the cnet-img also black
> 
> ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/d291fe27-6b26-4296-a2d3-48969a49bea2)
> 
> but simple detector can read it

In the absence of a controlnet, black is the natural. What I mentioned is that the detection capabilities vary for each controlnet preprocessor, so I recommend attaching a different controlnet and testing it.

**Comment by xueqing0622** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/9fa0f7b3-883d-4ec2-913d-50014f046b3b)

yes, so ,
The conclusion is can detected the face but can not work well with controlnet

**Comment by ltdrdata** [comment]
https://youtu.be/RoWzBo9I0MQ

You'd better watch this to apply ControlNet

**Comment by xueqing0622** [comment]
ok, use controlnet apply(segs) and  segsDetailer, thank you very much

**Comment by xueqing0622** [comment]
I suggest, you need to take the time to integrate these nodes, 
there is too much stuff to learn and it's easy to miss this stuff or that stuff

like the impactwildcardEncode, 
after you integrate it (prompt, lora, __wildcard__ ), and now it easy for use, 
I use every workflow, 

I think I've tried hard to learn it, but it's still hard to miss a few things 
Thank you very much for making so many great nodes and contributions to comfyui!

**Comment by ltdrdata** [comment]
> I suggest, you need to take the time to integrate these nodes, 
> there is too much stuff to learn and it's easy to miss this stuff or that stuff
> 
> like the impactwildcardEncode, 
> after you integrate it (prompt, lora, __wildcard__ ), and now it easy for use, 
> I use every workflow, 
> 
> I think I've tried hard to learn it, but it's still hard to miss a few things 
> Thank you very much for making so many great nodes and contributions to comfyui!

It serves completely different purposes.

FaceDetailer is designed for simplicity, while breaking it down into nodes is for a much wider range of combinations and finer control.

All-In-One node cannot be basic method. It's just a convenient node which has clear limitation.

**Comment by xueqing0622** [comment]
Yeah, I went from sdwebui to comfyui,  it was for the freedom and workflow.

Thanks for the node, I'll try to keep learning  with you.

**Comment by xueqing0622** [comment]
works now, thx

how about tilePreProcessor provider(segs)
I can't find this node  "tilePreProcessor provider(segs)"

**Comment by xueqing0622** [comment]
and how to use 2 control net?
Is it like this?
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/ec141c4c-fa09-4421-b0d7-49b2aaae3062)

**Comment by mijuku233** [comment]
> and how to use 2 control net? Is it like this? ![image](https://user-images.githubusercontent.com/114840118/278251242-ec141c4c-fa09-4421-b0d7-49b2aaae3062.png)

Yes, in addition, I noticed that there is a bug in `Simple Detector (SEGS)`, which causes the detected `seg` to be incorrect. Until the bug is fixed, additional steps are required when detailing the face/hands with `Detailer (SEGS)`. Add `SAMDetector (combined)` to get the correct effect.

The author answered the reason for the different effects. There is no problem with `Simple Detector (SEGS)`, but you need to pay attention to modifying `sub_threshold` to 0.93 so that you can obtain normal face refinement.

**Comment by xueqing0622** [comment]
> > and how to use 2 control net? Is it like this? ![image](https://usercontent.githubfast.com/user-images/114840118/278251242-ec141c4c-fa09-4421-b0d7-49b2aaae3062.png)
> 
> Yes, in addition, I noticed that there is a bug in `Simple Detector (SEGS)`, which causes the detected `seg` to be incorrect. Until the bug is fixed, additional steps are required when detailing the face/hands with `Detailer (SEGS)`. Add `SAMDetector (combined)` to get the correct effect.
> 
> The author answered the reason for the different effects. There is no problem with `Simple Detector (SEGS)`, but you need to pay attention to modifying `sub_threshold` to 0.93 so that you can obtain normal face refinement.

谢谢你的答疑,, mijuku233

**Comment by xueqing0622** [comment]
> works now, thx
> 
> how about tilePreProcessor provider(segs) I can't find this node "tilePreProcessor provider(segs)"

I find the inspire pack have no TilePreProcessor provider(segs)

**Comment by ltdrdata** [comment]
> > works now, thx
> > how about tilePreProcessor provider(segs) I can't find this node "tilePreProcessor provider(segs)"
> 
> I find the inspire pack have no TilePreProcessor provider(segs)

This is implemented on `Inspire Pack` V0.33

**Comment by xueqing0622** [comment]
Thx!
