### ISSUE TITLE
The segs detected by Simple Detector (SEGS) seem wrong

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#246]
Before, I didn't realize that the `segs` output by `Simple Detector (SEGS)` were wrong until I connected `BBOX Detector (SEGS)` and `SAMDetector (combined)` separately and with `Simple Detector (SEGS) `Compare.

![seg 2023-10-26 192617](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/89350747/3ffc77c1-2815-4178-8030-5098c6d15dfa)

The following is the workflow used for testing:
[segdetector.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13176856/segdetector.json)

Until it is fixed, adding an additional `SAMDetector` will give the correct effect.

**Comment by ltdrdata** [comment]
Your settings are different. Simple Detector's `sub_threshold` is 0.5 but SAMDetector's `threshold` is 0.93.
