### ISSUE TITLE
DPMDD-2M-SDE with PixelTiledKSampleUpscaleProvider

### ISSUE THREAD

**Issue by poisenbery** [ltdrdata/ComfyUI-Impact-Pack#25]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/a75d48f3-a947-4338-93b0-820e35112611)

``` Traceback (most recent call last):
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 257, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 120, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 128, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_pack.py", line 846, in doit
    refined_latent = IterativeLatentUpscale().doit(latent, upscale_factor, steps, temp_prefix, upscaler, unique_id)
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_pack.py", line 801, in doit
    current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_core.py", line 1106, in upscale_shape
    refined_latent = self.tiled_ksample(upscaled_latent)
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_core.py", line 1073, in tiled_ksample
    return TiledKSampler().sample(model, seed, tile_width, tile_height, tiling_strategy, steps, cfg, sampler_name, scheduler,
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI_TiledKSampler/nodes.py", line 266, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0)
  File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI_TiledKSampler/nodes.py", line 230, in sample_common
    tile_result = sampler.sample(tiled_noise, pos, neg, cfg=cfg, latent_image=tiled_latent, start_step=start_at_step + i * tile_steps, last_step=start_at_step + i*tile_steps + tile_steps, force_full_denoise=force_full_denoise and i+1 == end_at_step - start_at_step, denoise_mask=tiled_mask, callback=callback, disable_pbar=True)
  File "/home/poisenbery/AI_Stuff/ComfyUI/comfy/samplers.py", line 684, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "/home/poisenbery/AI_Stuff/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/poisenbery/AI_Stuff/ComfyUI/comfy/k_diffusion/sampling.py", line 649, in sample_dpmpp_2m_sde
    h_last = h
UnboundLocalError: local variable 'h' referenced before assignment
```

I'm not sure if this goes in this repo or the tiledKsampler repo
dmpdd_2m_sde will always give me this error

**Comment by ltdrdata** [comment]
> ![image](https://user-images.githubusercontent.com/78466408/243072511-a75d48f3-a947-4338-93b0-820e35112611.png)
> 
> ```
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 257, in execute
>     recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed, prompt_id, self.outputs_ui)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 120, in recursive_execute
>     recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed, prompt_id, outputs_ui)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 128, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 75, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/execution.py", line 68, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_pack.py", line 846, in doit
>     refined_latent = IterativeLatentUpscale().doit(latent, upscale_factor, steps, temp_prefix, upscaler, unique_id)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_pack.py", line 801, in doit
>     current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_core.py", line 1106, in upscale_shape
>     refined_latent = self.tiled_ksample(upscaled_latent)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_core.py", line 1073, in tiled_ksample
>     return TiledKSampler().sample(model, seed, tile_width, tile_height, tiling_strategy, steps, cfg, sampler_name, scheduler,
>   File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI_TiledKSampler/nodes.py", line 266, in sample
>     return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/custom_nodes/ComfyUI_TiledKSampler/nodes.py", line 230, in sample_common
>     tile_result = sampler.sample(tiled_noise, pos, neg, cfg=cfg, latent_image=tiled_latent, start_step=start_at_step + i * tile_steps, last_step=start_at_step + i*tile_steps + tile_steps, force_full_denoise=force_full_denoise and i+1 == end_at_step - start_at_step, denoise_mask=tiled_mask, callback=callback, disable_pbar=True)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/comfy/samplers.py", line 684, in sample
>     samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/poisenbery/AI_Stuff/ComfyUI/comfy/k_diffusion/sampling.py", line 649, in sample_dpmpp_2m_sde
>     h_last = h
> UnboundLocalError: local variable 'h' referenced before assignment
> ```
> 
> I'm not sure if this goes in this repo or the tiledKsampler repo dmpdd_2m_sde will always give me this error

You should update to latest version of ComfyUI.
It's related to this patch.

https://github.com/ltdrdata/ComfyUI/blob/700491d81a9faf5370a0c54d869e902bbfc839ec/comfy/k_diffusion/sampling.py#L623

**Comment by poisenbery** [comment]
Yeah, you're correct.
My bad.
