### ISSUE TITLE
e: module 'sys' has no attribute '__comfyui_manager_register_message_collapse'

### ISSUE THREAD

**Issue by emourdavid** [ltdrdata/ComfyUI-Impact-Pack#253]
Hi guy, 

I git pull the latest version but still get this warning. May I know how to remove this problem? Thanks.

### Loading: ComfyUI-Impact-Pack (V4.27.5)
e: module 'sys' has no attribute '__comfyui_manager_register_message_collapse'

Here is code ComfyUI-Impact-Pack\modules\impact\logics.py:
```
error_skip_flag = False
try:
    import sys
    def filter_message(str):
        global error_skip_flag

        if "IMPACT-PACK-SIGNAL: STOP CONTROL BRIDGE" in str:
            return True
        elif error_skip_flag and "ERROR:root:!!! Exception during processing !!!\n" == str:
            error_skip_flag = False
            return True
        else:
            return False

    sys.__comfyui_manager_register_message_collapse(filter_message)

except Exception as e:
    print(f"e: {e}")
    pass
```
ComfyUI, Manager is latest version

**Comment by ltdrdata** [comment]
Make sure your manager version is V0.36.

`### Loading: ComfyUI-Manager (V0.36)`

If it is. Your ComfyUI is outdated version.

This error doesn't have any impact on the functionality, so the error message has been improved to display a simple guidance message. 

NOTE:
If you are running ComfyUI using something like Pinokio, it includes a modified version of ComfyUI that is not the official version and is quite outdated.

**Comment by emourdavid** [comment]
Thank you. I upgraded to ComfyUI-Manager (V0.36) and this warning gone.
