### ISSUE TITLE
ImpactWildcardProcessor not picking a random entry

### ISSUE THREAD

**Issue by GamingDaveUk** [ltdrdata/ComfyUI-Impact-Pack#256]
Before updating today the text at the top could be {option 1| option 2| option 3} and it would pick say Option 1, the bottom box would show "option 1" and it would pass that on as a string. Now it just copies the top box into the bottom and passes that on as the string.

has the format changed?

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/769f8ecd-39cc-4736-8f3c-4a03c4e5ca90)

There is no problem on my test.
Maybe there is a conflict with other custom node.

Is the workflow of wildcard node something that was created a long time ago? If so, try recreating it.

**Comment by GamingDaveUk** [comment]
Hmmm, it used to work fine and started after the last update. At work now
but will test again tonight and see if I can find what custom node is now
conflicting with it

**Comment by GamingDaveUk** [comment]
Well this is odd.

Loading my old images where the wildcards worked its [option1|option2]
I checked a ton of them and all were [ ]
I disabled and uninstalled tons of custom nodes... to no avail...
I see in my original message i said { } by accident. Then i saw in your example you too had used { } not [ ] hmmm says me... and tries { }.... it works... 
I promise hand upon heart that before [ ] was working fine for me, switching to { }'s though is not big deal. 
This "issue" can be { closed | ignored | deleted | sent to silicon heaven to live with all the little calculators}.

**Comment by ltdrdata** [comment]
> Well this is odd.
> 
> Loading my old images where the wildcards worked its [option1|option2]
> I checked a ton of them and all were [ ]
> I disabled and uninstalled tons of custom nodes... to no avail...
> I see in my original message i said { } by accident. Then i saw in your example you too had used { } not [ ] hmmm says me... and tries { }.... it works... 
> I promise hand upon heart that before [ ] was working fine for me, switching to { }'s though is not big deal. 
> This "issue" can be { closed | ignored | deleted | sent to silicon heaven to live with all the little calculators}.

[] syntax is deprecated due to prompt editing syntax uses [].
