### ISSUE TITLE
I have encountered an issue with the "switch any" node.

### ISSUE THREAD

**Issue by usaking12** [ltdrdata/ComfyUI-Impact-Pack#258]
In the program that encapsulates the workflow in comfyui (branch) and other workflow encapsulation programs, the "switch any" node always throws an error (the branch has replaced the node, but it doesn't feel right). Is there a good way to avoid this? Or is it possible to upgrade the "switch any" node, as it is a very important node after all!

I have encountered situations where the "switch any" node throws an error and prevents the execution of the encapsulated workflow when using the built-in encapsulation component module of comfyui, ComfyUI-Workflow-Component, and even what I consider the best ComfyuiFlowApp.

Thank you for recognizing my hard work.

**Comment by ltdrdata** [comment]
In fact, those nodes are provided for convenience temporarily, bypassing certain structural aspects of ComfyUI. After the merge of [pr931](https://github.com/comfyanonymous/ComfyUI/pull/931), it should be possible to resolve this issue in a much smoother way.

**Comment by ltdrdata** [comment]
This is solved since v7.2.1.
