### ISSUE TITLE
How about add prompt weight interpretation in ImpactWildcardEncodea and ImpactWildcardPreprocessor

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#259]
How about add prompt weight interpretation ImpactWildcardEncodea and ImpactWildcardPreprocessor
https://civitai.com/models/46229/prompt-weighting-interpretations-for-comfyui
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/9ba83e02-0091-4fc8-b7e7-3462a85af97c)

**Comment by xueqing0622** [comment]
when add lora and prompt weight near 1.5, it will get some no good effect if have no weight interpretation
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/7a496cbb-0f24-4102-91c3-84de60746cf1)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/46824bf8-8cb2-4f6f-93b7-1a4607f0119e)

**Comment by xueqing0622** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/cb56fd7f-1af1-4a9e-878b-7090ea3789df)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/4f0979a0-e0bb-48a6-8097-6b2be7231e95)

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/897625b7-7531-483e-8e18-45ea36b5224f)

`Wildcard Encode (Inspire)` relies on `ImpactWildcardEncode` and BlenderNeko's Advanced CLIPText Encode.

And LoRA is completely distinct from CLIP.
CLIP and LoRA should not have weights applied in the same way, as they operate on entirely different principles.

Technically, all occurrence of "LoRA" in the prompt text are extracted, and they are applied to the model patch and clip patch through LoadLoRA before being passed to `CLIPTextEncode` for application.

**Comment by xueqing0622** [comment]
of cause, I get your idea,
ask you one more question, how to add weight interpretation in your regional conditioning by color mask(Inspire)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/ff6c2a4c-f764-494b-af87-b2f44b885905)

**Comment by xueqing0622** [comment]
I use this way now, 
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/4ea2f76d-df03-40b2-bd65-94dc0d6e7a1c)

**Comment by xueqing0622** [comment]
Thx, ltdrdata, It help me a lot!
