### ISSUE TITLE
FaceDetailer consistent error when using SD Upscale Node

### ISSUE THREAD

**Issue by poisenbery** [ltdrdata/ComfyUI-Impact-Pack#26]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/3a05d12e-9afa-44ad-85b7-a552b8e79ecf)

Only occurs when I use this: https://github.com/ssitu/ComfyUI_UltimateSDUpscale

[workflow.json.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/11647339/workflow.json.txt)

**Comment by poisenbery** [comment]
Temporary workaround: use VAE Encode node to convert Ultimate SD Upscale image to latent, then use VAE Decode to convert back to image.**
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/13538ed2-1c6c-437b-97d5-d38f6a836e1e)
**

**Comment by ltdrdata** [comment]
This error appears to be an issue that occurs when the image is too large. I will notify you if there are any improvements made regarding this issue.

**Comment by ltdrdata** [comment]
I cannot reproduce the symptoms, can you share you workflow?

**Comment by poisenbery** [comment]
My bad, I forgot to close this. It was an issue with the SD Upscale node
https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/2#issuecomment-1579187889
