### ISSUE TITLE
WISH: remove the tooltip text from ImpactWildcardProcessor

### ISSUE THREAD

**Issue by BaronFalke** [ltdrdata/ComfyUI-Impact-Pack#260]
The ImpactWildcardProcessor (and I think other nodes too) have these "tooltips" which are pretty annoying:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/6080245/4c1fdd9d-d9d4-437f-af18-2df5150b60d4)
I would like to remove/disable these.

**Comment by ltdrdata** [comment]
In my opinion, I believe this issue should eventually be patched by updating `litegraph` to ensure that the graphics of the nodes do not break.
