### ISSUE TITLE
FEATURE REQ: Added tag selection function

### ISSUE THREAD

**Issue by hben35096** [ltdrdata/ComfyUI-Impact-Pack#261]
I was pleasantly surprised to find that the "SEGS Filter (label)" node is a very great node, and I think it could do more with it, such as:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/af003148-2ad8-4e69-beff-773906f6505b)

Regarding the prompt words, I have done some tidying up:
category:
picture quality, Composition form, angle of view, shot, style, picture effect

=============================================================

picture quality:
UHD, retina, masterpiece, ccurate, anatomically correct, textured skin, super detail, high details, high quality, award winning, best quality, highres, 1080P, HD, 4K, 8k, 16k

Composition form:
afterimage, border, framed, outside border, fading border, rounded corners, viewfinder, chart, character chart, reference sheet, diagram, move chart, relationship graph, seating chart, stats, collage, column lineup, bust chart, cropped, fake scrollbar, head out of frame, out of frame, feet out of frame, isometric, letterboxed, pillarboxed, lineup, mosaic art, photomosaic, negative space, omake, partially underwater shot, social media composition, symmetry, polar opposites, rotational symmetry, tachi-e, trim marks, zoom layer, projected inset

angle of view:
first-person view, pov, three sided view, multiple views, cut-in, blurry foreground, close-up, cowboy shot, dutch angle, fisheye, hatching (texture), vanishing point, wide shot, from above, from behind, from below, from outside, from side, atmospheric perspective, panorama, perspective, rotated, sideways, upside-down

shot:
lens flare, overexposure, bokeh, caustics, diffraction spikes, foreshortening, emphasis lines, satellite image, macro photo, 360 view, Wide-Angle, Ultra-Wide Angle, Eye-Level Shot, f/1.2, f/1.8, f/2.8, f/4.0, f/16, 35mm, 85mm, 135mm, Nikon, Canon, Fujifilm, Hasselblad, Sony FE, Sony FE GM

style:
Surrealism, Color Field painting, Art Deco, rococo style, high detail, blind box toy style, Cubist Futurism, Conceptual art, Futurism, Social realism, interior architecture, Renaissance, Neoclassicism, modern, anime, Minimalism, Romanticism, Gothic art, American propaganda poster, Tonalism, Baroque, Fauvism, Expressionism, Carl Larsson, Op art, Realism, Contemporary art, Genre painting, Constructivism, Mannerism, Bauhaus, Action painting, by Alfons Mucha, Dutch Golden Age painting, Pop art, Monet, Northern Renaissance, Dadaism, Ukiyo-e, Luminism, Abstract expressionism, Impressionism, Pre-Raphaelite Brotherhood, Classicism, Ghibli-like colours, Hyperrealism, Art Nouveau, Suprematism, Abstractionism, pre-rephaëlite painting, anime style, Post-Impressionism, En plein air, Pointillism, Verism, raised fist, Ashcan School, Pixar, Cubism

picture effect:
chiaroscuro, depth of field, cinematic lighting, motion blur, chromatic aberration, sparkle, jpeg artifacts, blurry, glowing light, god rays, ray tracing, reflection light, backlighting, blending, bloom, chromatic aberration abuse, dithering, drop shadow, film grain, Fujicolor, halftone, image fill, motion lines, multiple monochrome, optical illusion, anaglyph, stereogram, scanlines, silhouette, speed lines, vignetting

**Comment by hben35096** [comment]
I don't know the code, this is a preview image I made with Photoshop, and the STRING in the output interface is to facilitate the translation into other languages after the output.

**Comment by ltdrdata** [comment]
Are you looking for the ability to fill in style prompt text using a combo?

**Comment by hben35096** [comment]
> Are you looking for the ability to fill in style prompt text using a combo?

Thank you for your reply. Yes, this is the first time I've seen a node like "SEGS Filter (label)" that allows the cumulative addition of prompts through the selection menu, while allowing manual input.
Do you know of a node that has the same functionality?

**Comment by ltdrdata** [comment]
> > Are you looking for the ability to fill in style prompt text using a combo?
> 
> Thank you for your reply. Yes, this is the first time I've seen a node like "SEGS Filter (label)" that allows the cumulative addition of prompts through the selection menu, while allowing manual input.
> Do you know of a node that has the same functionality?

I am providing cumulative input for wildcard and lora in ImpactWildcard... nodes.

There is various Prompt Styler nodes. But AFAIK, There is no cumulative style nodes.

**Comment by hben35096** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/5a4b1e3b-b129-4dcf-9c40-c059cde2923b)

I was worried that what I said would be incomprehensible when translated into English, so I made some attempts to make "SEGS Filter (label)" output prompt words, and I thought that such a node that can select prompt words is very convenient for beginners.

**Comment by ltdrdata** [comment]
> ![image](https://user-images.githubusercontent.com/139383150/279986422-5a4b1e3b-b129-4dcf-9c40-c059cde2923b.png)
> 
> I was worried that what I said would be incomprehensible when translated into English, so I made some attempts to make "SEGS Filter (label)" output prompt words, and I thought that such a node that can select prompt words is very convenient for beginners.

I understand what you mean. This feature is likely to be added in the Inspire Pack.

**Comment by hben35096** [comment]
> > ![image](https://user-images.githubusercontent.com/139383150/279986422-5a4b1e3b-b129-4dcf-9c40-c059cde2923b.png)
> > I was worried that what I said would be incomprehensible when translated into English, so I made some attempts to make "SEGS Filter (label)" output prompt words, and I thought that such a node that can select prompt words is very convenient for beginners.
> 
> I understand what you mean. This feature is likely to be added in the Inspire Pack.

Thank you very much for your patience and look forward to seeing such a new feature one day

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/65523521-cafd-487e-ae01-c70c7cdf1dad)

This node is added into `Inspire Pack`.
You can modify `resources/prompt-builder.yaml`

**Comment by hben35096** [comment]
Thank you very much. I think I can organize my own vocabulary and add it to it :D

**Comment by hben35096** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/042167ba-be15-4169-ae3a-4da892033dc2)


It doesn't seem to support this way of writing. I tried using "AIGODLIKE-COMFYUI-TRANSLATION" for translation, but the content in the options did not work.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/e9877694-11f2-4cc4-96eb-86d923648057)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/17d9faf0-0d77-4bb7-b975-bec8f63e4fbb)

**Comment by ltdrdata** [comment]
> ![image](https://user-images.githubusercontent.com/139383150/281406428-042167ba-be15-4169-ae3a-4da892033dc2.png)
> 
> It doesn't seem to support this way of writing. I tried using "AIGODLIKE-COMFYUI-TRANSLATION" for translation, but the content in the options did not work.
> 
> ![image](https://user-images.githubusercontent.com/139383150/281407528-e9877694-11f2-4cc4-96eb-86d923648057.png) ![image](https://user-images.githubusercontent.com/139383150/281407908-17d9faf0-0d77-4bb7-b975-bec8f63e4fbb.png)

Use single quote(')
```
- 'aaa: test'
```

**Comment by hben35096** [comment]
Sorry, I didn't express myself clearly.
What I mean is that "aaa" is the language of our country. It is only convenient for browsing and does not need to be output; and "test" is the final output word.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/67b94507-b7a7-4947-951f-03b362146b72)

If I use:
- 'aaa: test'
What I get instead is a whole line of text:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/d2778ab6-8a4c-49dd-af0f-cd32de595f79)

**Comment by ltdrdata** [comment]
This is updated.
if you select 'aaa: test' then only 'test' will be input.

**Comment by hben35096** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/052e6693-a0ab-40a0-b350-419b96755d6a)
Other languages ​​don't seem to be supported, I used Chinese and Japanese and in node they became gibberish.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/14378b80-89f8-41d6-bf5f-e3cf3d7ec59b)

You can use UTF-8 on `Inspire Pack V0.38.2`

**Comment by hben35096** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/d9124e99-37e9-4d8b-b70c-9d71339d1bea)

Great, it works perfectly, thanks for everything 👍
