### ISSUE TITLE
How to recognize more objects with Ultralytics Provider and SEGM Detector?

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#263]
From what I understand, the Ultralytics pretrained models can recognize a remarkable number of objects out-of-the-box, according to [this documentation](https://docs.ultralytics.com/tasks/segment/).

However, when I try to identify the segments with the workflow below, I can't recognize much beyond a basic set of entities. And even in that case, I can't identify some entities that are clearly there.

In this case, for example, I am trying to identify just the eyes, but I fail.

<img width="1094" alt="Screenshot 2023-11-03 at 15 06 28" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/60c5b70e-8290-417f-9ca5-54d964625c5e">

What am I doing wrong/not understanding? 

Thank you!

**Comment by hben35096** [comment]
The model includes a total of 79 categories, but does not include the category of “eyes”
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/datasets/coco.yaml

**Comment by alessandroperilli** [comment]
But then, @hben35096, where does the category list included in the `SEGS Label Filter `node come from? 

Eyes are there. In fact, even individual eyes:

<img width="615" alt="Screenshot 2023-11-03 at 20 17 25" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/567c999c-4f41-4f45-802b-af9923363101">

If that category list doesn't refer to Ultralytics pretrained models, what models can we use to isolate just the eyes?

**Comment by ltdrdata** [comment]
> But then, @hben35096, where does the category list included in the `SEGS Label Filter `node come from?
> 
> Eyes are there. In fact, even individual eyes:
> 
> <img alt="Screenshot 2023-11-03 at 20 17 25" width="615" src="https://user-images.githubusercontent.com/9775949/280404673-567c999c-4f41-4f45-802b-af9923363101.png">
> If that category list doesn't refer to Ultralytics pretrained models, what models can we use to isolate just the eyes?

It's just a hardcoded list for convenient.
And `SEGS Label Filter` is not just for Ultralytics detector. 
The reason it was initially introduced was for CLIPSeg and MediaPipe FaceMesh.

https://www.youtube.com/watch?v=etsHl2TFEiQ
