### ISSUE TITLE
Prompt outputs failed validation RegionalSampler: 

### ISSUE THREAD

**Issue by yovsac** [ltdrdata/ComfyUI-Impact-Pack#264]
Hello,

I keep getting the following error when trying to use the regional sampler.

- Value not in list: seed_2nd_mode: '1' not in ['ignore', 'fixed', 'seed+seed_2nd', 'seed-seed_2nd', 'increment', 'decrement', 'randomize']

Using SDXL base checkpoint.

Any thoughts?

Thank you in advance.

**Comment by ltdrdata** [comment]
> Hello,
> 
> I keep getting the following error when trying to use the regional sampler.
> 
> * Value not in list: seed_2nd_mode: '1' not in ['ignore', 'fixed', 'seed+seed_2nd', 'seed-seed_2nd', 'increment', 'decrement', 'randomize']
> 
> Using SDXL base checkpoint.
> 
> Any thoughts?
> 
> Thank you in advance.

It seems that the compatibility has been compromised as the workflow was created a long time ago, and now the node shapes have changed. I recommend creating a new node and inserting it.

**Comment by yovsac** [comment]
Thank you for your reply. Not sure how to do that, could you please explain further?

**Comment by ltdrdata** [comment]
> Thank you for your reply. Not sure how to do that, could you please explain further?

Just add new node and move connection to new node and remove old node.

**Comment by yovsac** [comment]
You mean deleting the regional sampler node and adding a new one?

**Comment by ltdrdata** [comment]
> You mean deleting the regional sampler node and adding a new one?

Exactly.
However, perform the task of adding and moving before deleting. It would be quite cumbersome if you attempt to delete first and then add.

**Comment by yovsac** [comment]
Thank you so much! Congrats on your great tools. Love them.
