### ISSUE TITLE
Image Sender / Receiver do not cause operations to occur and can lead to incomplete workflow

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#265]
I have a situation where I am using a receiver to handle a function, but it doesn't fire until the next image, so it is always one image behind as the process is not sampling.  Is there a way, other than adding some fake process, to insure that the sender always processes the image?

**Comment by ltdrdata** [comment]
Do you want the receiver to always be re-executed even without being renewed?

**Comment by sedetweiler** [comment]
Yes, I think so.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/30c060d9-a547-473b-848e-4af3d9e47e94)

`trigger_always` is added on V4.30.1

**Comment by sedetweiler** [comment]
you rock!  thank you, sir!

**Comment by sedetweiler** [comment]
What I find happening is I have an upscaler later in the workflow, and the receiver doesn't fire because the image was not dirty.  I am now finding that the sender does update, but often after the job has completed so the upscaler still does not fire until the next job is started, so it is always one behind.

**Comment by ltdrdata** [comment]
> What I find happening is I have an upscaler later in the workflow, and the receiver doesn't fire because the image was not dirty. I am now finding that the sender does update, but often after the job has completed so the upscaler still does not fire until the next job is started, so it is always one behind.

Have you looked into the `Queue Trigger` node?
I recommend referring to the 'logics' section of the README.

**Comment by sedetweiler** [comment]
I will check it out.  I have been adding in a random number node and getting a value from that to force the progression, but that is a total hack.
