### ISSUE TITLE
[Feature request] : Add noise mode to face detailer (GPU - for A1111 compatibility/CPU)

### ISSUE THREAD

**Issue by thecat99z** [ltdrdata/ComfyUI-Impact-Pack#267]
The face detailer node uses the default comfy CPU mode. Problem is when using the Inspire pack Ksampler with noise mode = GPU(=A1111) faces can be drastically different than internal CPU comfy's mode.
In result, the face characteristics from the original image can be lost and the final result looks more like a faceswap than a face detailer enhance.

Would be nice to have the A1111 compatibility also in the Impact pack. Thanks.

Or is there already some workaround to force the face detailer internal sampler to use GPU noise mode ?

**Comment by ltdrdata** [comment]
This has nothing to do with whether noise is CPU or GPU. It's a matter of how strong the denoise is and what model or algorithm you use.
