### ISSUE TITLE
Dilation In SEGM/BBOX Detector causes lockup

### ISSUE THREAD

**Issue by Nlar** [ltdrdata/ComfyUI-Impact-Pack#268]
When using the SEGM Detector ComfyUI will lock up if the dilation is not set to 0.  The issue appeared after updating to the current version of ComfyUI-Impact-Pack and did not correct with updates to system, pip and comfyui.  

This workflow was created for testing, but the issue occurred in a working workflow before the upgrade. 
![SEGM_workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/6274034/d14d9eda-5cc2-4d43-9ce5-56ae6a5db04e)

A generic image was replaced in this workflow, but an image with face/hands/body was used for all testing.  

Traced down the freeze to the statement for SEGM to  `gpu_kernel = cv2.UMat(kernel)`.  This is Line 116 in the [modules/impact/utils.py](https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/modules/impact/utils.py) file.  Everything locks up when this line is executed.  

No error messages, just a lockup.  My IDE reported issue that that variable kernel being passed to UMAT was the wrong type.  Changing the input to `gpu_kernel = cv2.UMAT(2,2, np.uint8)` didn't change anything.  This is expected as both kernel variable and this change match accepted constructors in the opencv docs.  

With the dialation at 0, my original workflow responds correctly for person (SEGM), hand (BBOX Detector) and face (BBOX Detector).  Changing dialation to 0 in the attached workflow will also work as expected.  

I have updated everything to the current version.  pip list is attached.  
[pip_list.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13289895/pip_list.txt)

System info:
ComfyUI Revision: 1662 [0134657f] | Released on '2023-11-07, Linux sdn 6.5.9-arch2-1, GPU: NVIDIA GeForce RTX 4070, 31GB RAM, headless machine running inside a QEMU container.  Shutdown/reboots have been performed.  Addon list [add_on_list.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13290001/add_on_list.txt) attached for completeness, but not reason.

**Comment by ltdrdata** [comment]
Try creating a simple workflow using `ImpactDilateMask` like this and give it a try.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/d20e1d41-f864-424f-9aef-832db7acf0ef)

In my case, -10, 0, 10 all worked fine. 
Is the issue occurring at specific parameters?

`cv2.UMat` is simply used to speed up mask operations using the GPU and does not involve changing the values.

**Comment by Nlar** [comment]
Thanks for the help.  I am having the same issue with your suggested workflow.  The only change in behavior is that the segm detector gets highlighted and stops in the original.  The highlight doesn't move from the load image in the new workflow.  The issue occurs for all values except 0 
![simple_dilate_workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/6274034/18d4d360-32c2-4e08-8720-89cf3f2cd03f)
.  I would assume -10 is equal to 10 as the code calls abs().  

I'll ~try~ tried a new venv and attempted again.  I feel like this is a versioning issue for opencv, but don't know how to zero in more.  

The new list of installed packages is a lot cleaner, but did not change anything.  
[pip_list_02.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13291148/pip_list_02.txt)
The only addons are ComfyUI Manager which I used to pull in the Impact Pack.   

Is there a list of pip package versions I should be checking?

**Comment by Nlar** [comment]
I am going to close this as user issue.  I ran this code in my virtual machine and host.  The virtual machine is having issues with it.  
```
import numpy as np

dilation_factor = 10
kernel` = np.ones((abs(dilation_factor), abs(dilation_factor)), np.uint8)
gpu_kernel = cv2.UMat(kernel)
```

I'll post a reply if it is a version issue, but it isn't this project issue.  Thanks for the help!

**Comment by ltdrdata** [comment]
FYI,

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md#if-the-nodes-of-the-impact-pack-hang-during-execution
