### ISSUE TITLE
[NVIDIA Driver] Error occurred when executing FaceDetailer

### ISSUE THREAD

**Issue by sumback** [ltdrdata/ComfyUI-Impact-Pack#27]
Hi, i have this error : 

> Error occurred when executing FaceDetailer:
> 
> CUDA error: unknown error
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
> 
> 
> `File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 141, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 388, in doit
> enhanced_img, cropped_enhanced, mask = FaceDetailer.enhance_face(
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 373, in enhance_face
> DetailerForEach.do_detail(image, segs, model, vae, guide_size, guide_size_for, seed, steps, cfg,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 186, in do_detail
> enhanced_pil = core.enhance_detail(cropped_image, model, vae, guide_size, guide_size_for, seg.bbox,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_core.py", line 235, in enhance_detail
> refined_image = vae.decode(refined_latent['samples'])
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 551, in decode
> pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(1. / self.scale_factor * samples) + 1.0) / 2.0, min=0.0, max=1.0).cpu()

> RuntimeError: CUDA error: unknown error
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 
> Prompt executed in 1004.94 seconds
> Exception in thread Thread-7 (prompt_worker):
> Traceback (most recent call last):
>   File "threading.py", line 1016, in _bootstrap_inner
>   File "threading.py", line 953, in run
>   File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\main.py", line 37, in prompt_worker
>     e.execute(item[2], item[1], item[3], item[4])
>   File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 366, in execute
>     comfy.model_management.soft_empty_cache()
>   File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 436, in soft_empty_cache
>     torch.cuda.empty_cache()
>   File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
>     torch._C._cuda_emptyCache()
> RuntimeError: CUDA error: unknown error
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I use : 
- [ComfyUI Standalone Portable Windows Build (For NVIDIA or CPU only)](https://github.com/comfyanonymous/ComfyUI/releases/tag/latest)
- ComfyUI-Impact-Pack (V2.9.1)
  - B:\ComfyUI\ComfyUI_windows_portable\python_embeded/python.exe -s -m pip install -r requirements.txt

The used workspace works fine before i update everything.

**Comment by ltdrdata** [comment]
I think this is related to core ComfyUI.
Is your ComfyUI the latest version?

**Comment by sumback** [comment]
yes, i have ComfyUI on last update 
Commit: ee62b4ecc2eb04bb62772110a2cc704897dbcee8
Date: Wed Jun 07 2023 08:08:07 GMT+0200 (Central European Summer Time)

**Comment by ltdrdata** [comment]
Try this version.

https://github.com/comfyanonymous/ComfyUI/commit/08abd838b82ea8d08a7e6f1484140d1694180381

**Comment by sumback** [comment]
I don't know if there were any dependencies to update. I just switch to backup branchs.

On backup_branch_2023-06-06_15_20_59 (the one you asked for) https://github.com/comfyanonymous/ComfyUI/commit/08abd838b82ea8d08a7e6f1484140d1694180381

> Error occurred when executing FaceDetailer:
> 
> CUDA error: the launch timed out and was terminated
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 141, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 388, in doit
> enhanced_img, cropped_enhanced, mask = FaceDetailer.enhance_face(
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 373, in enhance_face
> DetailerForEach.do_detail(image, segs, model, vae, guide_size, guide_size_for, seed, steps, cfg,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 186, in do_detail
> enhanced_pil = core.enhance_detail(cropped_image, model, vae, guide_size, guide_size_for, seg.bbox,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_core.py", line 230, in enhance_detail
> refined_latent = sampler.sample(model, seed, steps, cfg, sampler_name, scheduler,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 981, in sample
> return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 952, in common_ksampler
> samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 88, in sample
> samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 630, in sample
> samples = uni_pc.sample_unipc(self.model_wrap, noise, latent_image, sigmas, sampling_function=sampling_function, max_denoise=max_denoise, extra_args=extra_args, noise_mask=denoise_mask, callback=callback, variant='bh2', disable=disable_pbar)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\extra_samplers\uni_pc.py", line 882, in sample_unipc
> x = uni_pc.sample(img, timesteps=timesteps, skip_type="time_uniform", method="multistep", order=order, lower_order_final=True, callback=callback, disable_pbar=disable)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\extra_samplers\uni_pc.py", line 731, in sample
> model_prev_list = [self.model_fn(x, vec_t)]
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\extra_samplers\uni_pc.py", line 422, in model_fn
> return self.data_prediction_fn(x, t)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\extra_samplers\uni_pc.py", line 404, in data_prediction_fn
> noise = self.noise_prediction_fn(x, t)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\extra_samplers\uni_pc.py", line 398, in noise_prediction_fn
> return self.model(x, t)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\extra_samplers\uni_pc.py", line 330, in model_fn
> return noise_pred_fn(x, t_continuous)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\extra_samplers\uni_pc.py", line 298, in noise_pred_fn
> output = sampling_function(model, x, t_input, **model_kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 274, in sampling_function
> cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 251, in calc_cond_uncond_batch
> output = model_function(input_x, timestep_, cond=c).chunk(batch_chunks)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\diffusion\ddpm.py", line 859, in apply_model
> x_recon = self.model(x_noisy, t, **cond)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> return forward_call(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\diffusion\ddpm.py", line 1337, in forward
> out = self.diffusion_model(x, t, context=cc, control=control, transformer_options=transformer_options)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> return forward_call(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 844, in forward
> h = forward_timestep_embed(module, h, emb, context, transformer_options, output_shape)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 97, in forward_timestep_embed
> x = layer(x, context, transformer_options)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> return forward_call(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
> output = old_forward(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 634, in forward
> x = block(x, context=context[i], transformer_options=transformer_options)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> return forward_call(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
> output = old_forward(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 523, in forward
> return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\util.py", line 123, in checkpoint
> return func(*inputs)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 553, in _forward
> n = self.attn1(n, context=context_attn1, value=value_attn1)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> return forward_call(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
> output = old_forward(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 448, in forward
> return self.to_out(out)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> return forward_call(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
> output = old_forward(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
> input = module(input)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
> return forward_call(*args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\hooks.py", line 160, in new_forward
> args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\hooks.py", line 273, in pre_forward
> set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
> File "B:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\accelerate\utils\modeling.py", line 149, in set_module_tensor_to_device
> new_value = value.to(device)

On backup_branch_2023-06-06_15_20_59 (before last update of ComfyUI and custom_nodes)  https://github.com/comfyanonymous/ComfyUI/commit/2ec980bb9f3e63fbc605e632d1ebe8837083aaaf
And backup_branch_2023-06-07_20_22_17   https://github.com/comfyanonymous/ComfyUI/commit/a3a713b6c581f4c0487c58c5a20eca2a5e8e6bde

> Error occurred when executing FaceDetailer:
> 
> CUDA error: the launch timed out and was terminated
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 141, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 388, in doit
> enhanced_img, cropped_enhanced, mask = FaceDetailer.enhance_face(
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 373, in enhance_face
> DetailerForEach.do_detail(image, segs, model, vae, guide_size, guide_size_for, seed, steps, cfg,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 186, in do_detail
> enhanced_pil = core.enhance_detail(cropped_image, model, vae, guide_size, guide_size_for, seg.bbox,
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_core.py", line 235, in enhance_detail
> refined_image = vae.decode(refined_latent['samples'])
> File "B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 562, in decode
> pixel_samples[x:x+batch_number] = torch.clamp((self.first_stage_model.decode(1. / self.scale_factor * samples) + 1.0) / 2.0, min=0.0, max=1.0).cpu()

I will have to stop there for today, I will try to make a new instal tomorrow.

**Comment by sumback** [comment]
Unfortunately, I reinstall ComfyUI and i still have this problem.

**Comment by ltdrdata** [comment]
> Unfortunately, I reinstall ComfyUI and i still have this problem.


Could you please provide the preceding logs that record the level of resolution at which the face detailer is being enlarged before the occurrence of that error?

**Comment by ltdrdata** [comment]
The issue may be related to the GPU driver. Please check if you have recently updated the GPU driver and consider switching to a different version that was previously working properly.

**Comment by sumback** [comment]
> Could you please provide the preceding logs that record the level of resolution at which the face detailer is being enlarged before the occurrence of that error?

Yes, of course.

Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Global Step: 0
Loads checkpoint by local backend from path: B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\mmdets\bbox\mmdet_anime-face_yolov3.pth
Loads SAM model: B:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\sams\sam_vit_b_01ec64.pth
Detailer: segment upscale for ((146.4263, 153.24536)) | crop region (439, 459) x 2.4585747224368326 -> (1079, 1128)
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [03:26<00:00,  6.88s/it]
!!! Exception during processing !!!

> The issue may be related to the GPU driver. Please check if you have recently updated the GPU driver and consider switching to a different version that was previously working properly.

Let's try this

NVIDIA GeForce GTX 970 Pilote geforce game ready version 535.98 05/30/2023 :x: :bug:
NVIDIA GeForce GTX 970 Pilote geforce game ready version 532.03 05/24/2023 :heavy_check_mark:

@ltdrdata Thank you very much for the help ! And thank you for all yours custom_node.
