### ISSUE TITLE
I want to modify the path of the Sams model

### ISSUE THREAD

**Issue by Lin1031** [ltdrdata/ComfyUI-Impact-Pack#270]
I want to modify the path of the Sams model, but I found that it seems to be only available under the/comfyUI/models/sams path. I checked the impact pack. ini file and did not find that I can modify the models/sams path. There are additional modifications to sam_editor_model is the default path for the model

**Comment by ltdrdata** [comment]
This is patched already.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/262
