### ISSUE TITLE
FaceDetailer is creating a directory outside the ComfyUI directory (customnodes/facedetailer/yolo)

### ISSUE THREAD

**Issue by aegis72** [ltdrdata/ComfyUI-Impact-Pack#271]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/118572301/d0af02cd-3a60-43de-a48d-3a7e212e8244)

When I start ComfyUI, an additional "custom nodes" directory is getting added to the root, containing nothing but a facedetailer/yolo folder, in which it downloads the dependency face_yolov8n.pt.

If I delete this folder, it gets recreated each time. The system runs fine, so it isn't breaking, but it does seem like weird behavior.

**Comment by ltdrdata** [comment]
Impact Pack doesn't create directory which is named "facedetailer". Check other custom_nodes.

**Comment by aegis72** [comment]
Man, sorry----wrong repo. Mind if I leave this here so I can direct the other maintainer?
