### ISSUE TITLE
Trouble loading dependencies for Impact Pack

### ISSUE THREAD

**Issue by elikagan** [ltdrdata/ComfyUI-Impact-Pack#272]
This is what im seeing:

### ComfyUI-Impact-Pack: Check basic models
[ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually.
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

I tried to troubleshoot the SSL stuff but wasn't able to solve. any ideas?

**Comment by ltdrdata** [comment]
Update `ComfyUI-Manager` to `V0.43`.
And add `bypass_ssl = true` to `ComfyUI-Manager/config.ini`.

Then this issue will be fixed.

**Comment by VipCrazyMaster** [comment]
对于mac M系列电脑建议用这种解决办法：https://github.com/ltdrdata/ComfyUI-Manager/issues/102
