### ISSUE TITLE
Wildcard not resolved

### ISSUE THREAD

**Issue by AsuraAce** [ltdrdata/ComfyUI-Impact-Pack#273]
it seems some wildcards can't be resolved because of the naming scheme. 

__camera/p+2__ (not working because of the "+" i think, tried renaming it to __camera/p_2__ and it worked )
__camera/p-2__ (this one works)

example:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/13394741/0788c56f-5f13-4e0e-9ba5-8fcac80f7d91)

renamed wildcard example (works with an underscore instead of a + sign):

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/13394741/1bd65488-2d11-4064-a67b-87378221fd2a)

**Comment by ltdrdata** [comment]
This support added on `V4.30.3`
