### ISSUE TITLE
UltralyticsDetectorProvider node type not found

### ISSUE THREAD

**Issue by cllCush** [ltdrdata/ComfyUI-Impact-Pack#274]
Coming from a fresh install of ComfyUi - I can't get the UltralyticsDetectorProvider node type to appear. 

To reproduce: 
1. Install ComfyUI Windows Standalone via .Zip extraction from https://github.com/comfyanonymous/ComfyUI/releases
2. Install ComfyUi Manager from https://github.com/ltdrdata/ComfyUI-Manager using provided install-manager-for-portable-version.bat
3. Run ComfyUi, install ComfyUi Impact Pack from ComfyUi Manager menu. Restart ComfyUi to apply changes.
4. UltralyticsDetectorProvider is not available as a custom node to add to the graph, console spits out errors (listed below)

Any help would be appreciated, I've been up all night trying to figure this out and I'm finally giving up and asking for help, I'm stumped. At one point I even installed the ComfyUi Impact Subpack because I thought I needed it, but that was prior to the fresh install of ComfyUi. At another point I changed "mmdet_skip = True" to "mmdet_skip = False" in impact-pack.ini to try and use the legacy nodes as the notes in the ComfyUi manager suggest, but that ended up breaking every custom node in ComfyUi Impact Pack and spat out a whole host of errors. I reverted that change.

Console: 
C:\Ai\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-11-10 12:53:43.104294
Failed to execute startup-script: C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / 'default'

Prestartup times for custom nodes:
   0.0 seconds (PRESTARTUP FAILED): C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10240 MB, total RAM 32683 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI-Impact-Pack: Check dependencies
Collecting segment-anything (from -r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 1))
  Using cached segment_anything-1.0-py3-none-any.whl (36 kB)
Collecting scikit-image (from -r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2))
  Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting piexif (from -r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 3))
  Using cached piexif-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: transformers in c:\ai\comfyui\python_embeded\lib\site-packages (from -r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (4.35.0)
Collecting opencv-python-headless (from -r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 5))
  Using cached opencv_python_headless-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: numpy>=1.22 in c:\ai\comfyui\python_embeded\lib\site-packages (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2)) (1.26.1)
Requirement already satisfied: scipy>=1.8 in c:\ai\comfyui\python_embeded\lib\site-packages (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2)) (1.11.3)
Requirement already satisfied: networkx>=2.8 in c:\ai\comfyui\python_embeded\lib\site-packages (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: pillow>=9.0.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2)) (10.1.0)
Collecting imageio>=2.27 (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2))
  Using cached imageio-2.32.0-py3-none-any.whl.metadata (4.9 kB)
Collecting tifffile>=2022.8.12 (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2))
  Using cached tifffile-2023.9.26-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: packaging>=21 in c:\ai\comfyui\python_embeded\lib\site-packages (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2)) (23.2)
Collecting lazy_loader>=0.3 (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2))
  Using cached lazy_loader-0.3-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: filelock in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (0.17.3)
Requirement already satisfied: pyyaml>=5.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (2023.10.3)
Requirement already satisfied: requests in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: tokenizers<0.15,>=0.14 in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in c:\ai\comfyui\python_embeded\lib\site-packages (from transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (4.66.1)
Requirement already satisfied: fsspec in c:\ai\comfyui\python_embeded\lib\site-packages (from huggingface-hub<1.0,>=0.16.4->transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (2023.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\ai\comfyui\python_embeded\lib\site-packages (from huggingface-hub<1.0,>=0.16.4->transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (4.8.0)
Collecting pillow>=9.0.1 (from scikit-image->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 2))
  Using cached Pillow-10.0.1-cp311-cp311-win_amd64.whl.metadata (9.6 kB)
Requirement already satisfied: colorama in c:\ai\comfyui\python_embeded\lib\site-packages (from tqdm>=4.27->transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests->transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests->transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests->transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests->transformers->-r C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt (line 4)) (2023.7.22)
Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl (24.5 MB)
Using cached opencv_python_headless-4.8.1.78-cp37-abi3-win_amd64.whl (38.0 MB)
Using cached imageio-2.32.0-py3-none-any.whl (313 kB)
Using cached lazy_loader-0.3-py3-none-any.whl (9.1 kB)
Using cached Pillow-10.0.1-cp311-cp311-win_amd64.whl (2.5 MB)
Using cached tifffile-2023.9.26-py3-none-any.whl (222 kB)
Installing collected packages: segment-anything, tifffile, pillow, piexif, opencv-python-headless, lazy_loader, imageio, scikit-image
  WARNING: The scripts lsm2bin.exe, tiff2fsspec.exe, tiffcomment.exe and tifffile.exe are installed in 'C:\Ai\ComfyUI\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: pillow
    Found existing installation: Pillow 10.1.0
    Uninstalling Pillow-10.1.0:
      Successfully uninstalled Pillow-10.1.0
  WARNING: Failed to remove contents in a temporary directory 'C:\Ai\ComfyUI\python_embeded\Lib\site-packages\~il'.
  You can safely remove it manually.
  WARNING: The scripts imageio_download_bin.exe and imageio_remove_bin.exe are installed in 'C:\Ai\ComfyUI\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed imageio-2.32.0 lazy_loader-0.3 opencv-python-headless-4.8.1.78 piexif-1.1.3 pillow-10.0.1 scikit-image-0.22.0 segment-anything-1.0 tifffile-2023.9.26
### ComfyUI-Impact-Pack: Check basic models
Downloading https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth to C:\Ai\ComfyUI\ComfyUI\models\sams\sam_vit_b_01ec64.pth
100%|█████████████████████████████████████████████████████████████| 375042383/375042383 [00:03<00:00, 109323843.88it/s]
### ComfyUI-Impact-Pack: Updating subpack
Downloading https://cdn-lfs.huggingface.co/repos/0d/db/0ddb8d3fcb6ee9737d9dd7e090e6c6cb6e40728d12307180160e7f654cb345de/e3893a92c5c1907136b6cc75404094db767c1e0cfefe1b43e87dad72af2e4c9f?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27face_yolov8m.pt%3B+filename%3D%22face_yolov8m.pt%22%3B&Expires=1699897656&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTg5NzY1Nn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy8wZC9kYi8wZGRiOGQzZmNiNmVlOTczN2Q5ZGQ3ZTA5MGU2YzZjYjZlNDA3MjhkMTIzMDcxODAxNjBlN2Y2NTRjYjM0NWRlL2UzODkzYTkyYzVjMTkwNzEzNmI2Y2M3NTQwNDA5NGRiNzY3YzFlMGNmZWZlMWI0M2U4N2RhZDcyYWYyZTRjOWY%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=bNjZYZ2HZ4plqi9uu4JHv7z4UPFC3Xz0cMy-EjEY8aByCLBTvlxoQqFk8JQhqgLyJf2cCwt3c613dIpSlMLXJD%7ETc7YU9WXdIc7NKKHuOAJANo1R22TlIfyroYatGGlB1rTJpOHZpHc9MWJ1ALvxfhCePWOie8gHHq7Tqf9fJZ7FBDuE62kbzpr%7EfN2Rp1yfsWY6KrV-hiWuhQx-VbT-Bsv57errEWzZvuCJt4C9VVl5x0EAMGvUC3M0547-wrrk86-TcBuYAn-V-aj5sOsP2gXSSrZq-SeSRDnArNfNIH7jsWN47LScN5HR7TJgf16w6SRrkNH2IYCCQ%7Ei-Yi5W2A__&Key-Pair-Id=KVTP0A1DKRTAX to C:\Ai\ComfyUI\ComfyUI\models\ultralytics\bbox\face_yolov8m.pt
100%|████████████████████████████████████████████████████████████████| 51996128/51996128 [00:00<00:00, 89619110.49it/s]
Downloading https://cdn-lfs.huggingface.co/repos/0d/db/0ddb8d3fcb6ee9737d9dd7e090e6c6cb6e40728d12307180160e7f654cb345de/30878cea9870964d4a238339e9dcff002078bbbaa1a058b07e11c167f67eca1c?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27hand_yolov8s.pt%3B+filename%3D%22hand_yolov8s.pt%22%3B&Expires=1699891715&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTg5MTcxNX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy8wZC9kYi8wZGRiOGQzZmNiNmVlOTczN2Q5ZGQ3ZTA5MGU2YzZjYjZlNDA3MjhkMTIzMDcxODAxNjBlN2Y2NTRjYjM0NWRlLzMwODc4Y2VhOTg3MDk2NGQ0YTIzODMzOWU5ZGNmZjAwMjA3OGJiYmFhMWEwNThiMDdlMTFjMTY3ZjY3ZWNhMWM%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=zo54g%7E1qOQVXmJ1qe2Owa1rBUsB5JG2h-6uV18Ge-BpZk3RqZrpUlijDTH5rI69pn5gJM%7Ei8ih-iyMzQpaA7OJRbPYmUp05gUj0sCEZ0eNICKIuvOmwis3125gY3ORH3HEg5IxNXu34LHa8WKL6qsHLcmDrtyWME2TQoaMR8rfluSe%7EhlwFc1PyY5YcfEeZuXiybhWLg-nS7M6UV8tGqWtTgGFvfJyOiNvnm70nPKMSq1zs0sm17nRDtODDjtHf81VfWtTUnTjrtL1xLdG9QcPjrqddYCj5PhHg08mG%7ExmusgMyXBXJXd%7EFQwmaFZRDNPyRpTsmKl9nPZmvcAHyIyA__&Key-Pair-Id=KVTP0A1DKRTAX to C:\Ai\ComfyUI\ComfyUI\models\ultralytics\bbox\hand_yolov8s.pt
100%|████████████████████████████████████████████████████████████████| 22484536/22484536 [00:00<00:00, 68697609.59it/s]
Downloading https://cdn-lfs.huggingface.co/repos/0d/db/0ddb8d3fcb6ee9737d9dd7e090e6c6cb6e40728d12307180160e7f654cb345de/1fd7e562f240a5debd48bf737753de6fb60c63f8664121bb522f090a885d8254?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27person_yolov8m-seg.pt%3B+filename%3D%22person_yolov8m-seg.pt%22%3B&Expires=1699893309&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5OTg5MzMwOX19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy8wZC9kYi8wZGRiOGQzZmNiNmVlOTczN2Q5ZGQ3ZTA5MGU2YzZjYjZlNDA3MjhkMTIzMDcxODAxNjBlN2Y2NTRjYjM0NWRlLzFmZDdlNTYyZjI0MGE1ZGViZDQ4YmY3Mzc3NTNkZTZmYjYwYzYzZjg2NjQxMjFiYjUyMmYwOTBhODg1ZDgyNTQ%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=qcGRPIFOmtd1HyXMZ3mtkF%7Emygd8i3OTZYgff9yy18oBYYW0qZMPIVhJSXLLQlRV6iUz9-WM2rSTzi1p5xbptBt0Kx1HJozTXYGUYrw8SfyhUmtnJJdRTWDSKGF0I7wMykftk8OhrwWERpPSsJotakP4s6ruT-pRMUrZ5xNAtBDoEawUPY4WPRHGRMvu04BJt7ujunwleSLKa853PpoVt2AAzTOZyGQ28-Y3tKZnajnpdiPT6L70DZaJK6gwfcZCDdmg%7EvdTUPiUXXFkSB2qp36VajXFOPWuWqr-NmjFCKbXvFlRMUjqu39e3LLPLP1wHc89XbbE5I1AmaSXGlIisg__&Key-Pair-Id=KVTP0A1DKRTAX to C:\Ai\ComfyUI\ComfyUI\models\ultralytics\segm\person_yolov8m-seg.pt
100%|████████████████████████████████████████████████████████████████| 54791722/54791722 [00:00<00:00, 87403987.09it/s]
Collecting ultralytics!=8.0.177 (from -r requirements.txt (line 1))
  Using cached ultralytics-8.0.208-py3-none-any.whl.metadata (31 kB)
Collecting matplotlib>=3.3.0 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached matplotlib-3.8.1-cp311-cp311-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: numpy>=1.22.2 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.1)
Collecting opencv-python>=4.6.0 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: pillow>=7.1.2 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (10.0.1)
Requirement already satisfied: pyyaml>=5.3.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.0+cu121)
Requirement already satisfied: torchvision>=0.9.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.16.0+cu121)
Requirement already satisfied: tqdm>=4.64.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.66.1)
Collecting pandas>=1.1.4 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached pandas-2.1.2-cp311-cp311-win_amd64.whl.metadata (18 kB)
Collecting seaborn>=0.11.0 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached seaborn-0.13.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: psutil in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (5.9.6)
Collecting py-cpuinfo (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Collecting thop>=0.1.1 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached fonttools-4.44.0-cp311-cp311-win_amd64.whl.metadata (156 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: packaging>=20.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (23.2)
Collecting pyparsing>=2.3.1 (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.7 (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: filelock in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.13.1)
Requirement already satisfied: typing-extensions in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: jinja2 in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.10.0)
Requirement already satisfied: colorama in c:\ai\comfyui\python_embeded\lib\site-packages (from tqdm>=4.64.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.4.6)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\ai\comfyui\python_embeded\lib\site-packages (from sympy->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.3.0)
Using cached ultralytics-8.0.208-py3-none-any.whl (645 kB)
Using cached matplotlib-3.8.1-cp311-cp311-win_amd64.whl (7.6 MB)
Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl (38.1 MB)
Using cached pandas-2.1.2-cp311-cp311-win_amd64.whl (10.6 MB)
Using cached seaborn-0.13.0-py3-none-any.whl (294 kB)
Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl (187 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.44.0-cp311-cp311-win_amd64.whl (2.1 MB)
Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl (56 kB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Installing collected packages: pytz, py-cpuinfo, tzdata, six, pyparsing, opencv-python, kiwisolver, fonttools, cycler, contourpy, python-dateutil, thop, pandas, matplotlib, seaborn, ultralytics
  WARNING: The script cpuinfo.exe is installed in 'C:\Ai\ComfyUI\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Ai\\ComfyUI\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

### ComfyUI Revision: 1650 [a6c83b3c] | Released on '2023-11-05'

Import times for custom nodes:
   0.2 seconds: C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
  24.2 seconds: C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Ai\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by CrimsonYoshi** [comment]
Adding that I'm also unable to find the UltralyticsDetectorProvidor node. I encountered the same "ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\Ai\ComfyUI\python_embeded\Lib\site-packages\cv2\cv2.pyd'"

I ran "python install.py" from the ComfyUI-Impact-Pack folder, which got everything successfully installed, but the Ultralytics node is still MIA

**Comment by ltdrdata** [comment]
> Adding that I'm also unable to find the UltralyticsDetectorProvidor node. I encountered the same "ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\Ai\ComfyUI\python_embeded\Lib\site-packages\cv2\cv2.pyd'"
> 
> I ran "python install.py" from the ComfyUI-Impact-Pack folder, which got everything successfully installed, but the Ultralytics node is still MIA

Oh, it seems like the issue occurred because the install script ran at an inconvenient time due to my latest Manager update. If you update the manager to the latest version and reinstall the Impact Pack, the issue should be resolved.

**Comment by Sleazus-Crust** [comment]
Found the solution: the problem seems to be with the ComfyManager automatic installer zip, once I git cloned the repo for ComfyUi manager into my ComfyUi custom nodes directory I was able to install Comfy Ui impact pack through the manager without encountering any errors. After this, I restarted ComfyUi, but the UltrayticsDetectorProvider node was still nowhere to be found. I added the sub pack through the manager and, voilà, bingo, cash money. Everything working as intended.

**Comment by CrimsonYoshi** [comment]
Worked like a charm! 

Thank you!

**Comment by radoslawg** [comment]
Seems it is not connected to manager - at least for me. I had to do fresh install of ComfyUI on windows (portable version). When I git clone Impact Pack I get error when starting Comfy:

`
Installing collected packages: opencv-python, thop, seaborn, ultralytics
ERROR: Could not install packages due to an OSError: [WinError 5] Permission Denied: 'e:\\ai\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.
`

Not sure why though. Also, I tried with manager, same result. Everything is up to date with CUDA 11.8 version. Also I don't know how to "add the sub pack through the manager" as there is no "subpack" available in the list.

**Comment by radoslawg** [comment]
Ok, figured it out.. after couple of hours of fiddling. If anybody is interested. Go to command line and manually install requirements.

`
python_embeded\Scripts\pip.exe install -r ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
`

If you encouter problems that pip tries to access python at some stupid, non existent path, then go ahead and delete pip exe files from Scripts and run:

`
.\python_embeded\python .\python_embeded\get-pip.py
`

YMMV. I spent too much time on this ;)

**Comment by Sleazus-Crust** [comment]
Hey @radoslawg, my bad, I didn't install the subpack through the "install custom nodes" button but rather the "install via Git URL" feature. In hindsight I'm not sure this was necessary, as having the ComfyUi impact subpack installed was throwing me an error about a missing \_init_.py. Currently I just have the ComfyUi impact pack (NOT the subpack) installed and I can't find any features that are missing or anything broken yet, so this is probably all you need.

**Comment by ltdrdata** [comment]
> Hey @radoslawg, my bad, I didn't install the subpack through the "install custom nodes" button but rather the "install via Git URL" feature. In hindsight I'm not sure this was necessary, as having the ComfyUi impact subpack installed was throwing me an error about a missing \_init_.py. Currently I just have the ComfyUi impact pack (NOT the subpack) installed and I can't find any features that are missing or anything broken yet, so this is probably all you need. 

That subpack should be installed through Impact Pack itself. What was the log message?

**Comment by Sleazus-Crust** [comment]
> That subpack should be installed through Impact Pack itself. What was the log message?

After your fix the impact pack and all subdirectories installed correctly with no problems :)
However, afterwards I got confused and somehow got it in my head to install the subpack directly into comfyui/custom_nodes, so when it was running from there it was looking in the wrong place for the init file. The log message was FileNotFoundError: [Errno 2] No such file or directory: C:\\Ai\\ComfyUi\\ComfyUI\\custom_nodes\\impact_subpack\\__init__.py. I deleted the subpack folder from my custom_nodes directory and ran comfyui, and the impact pack took care of placing it in the _correct_ location, under custom_nodes/ComfyUI-impact-pack. 

Apologies for the confusion, I'm rather embarrassed at this mistake. It's working correctly and it's really really cool what it can do, thank you :)

**Comment by cllCush** [comment]
> > That subpack should be installed through Impact Pack itself. What was the log message?
> 
> After your fix the impact pack and all subdirectories installed correctly with no problems :) However, afterwards I got confused and somehow got it in my head to install the subpack directly into comfyui/custom_nodes, so when it was running from there it was looking in the wrong place for the init file. The log message was your standard "Could not find directory ... File does not exist." I deleted the subpack folder from my custom_nodes directory and ran comfyui, and the impact pack took care of placing it in the _correct_ location, under custom_nodes/ComfyUI-impact-pack.
> 
> Apologies for the confusion, I'm rather embarrassed at this mistake. It's working correctly and it's really really cool what it can do, thank you :)
