### ISSUE TITLE
Error on CLIPSegDetectorProvider:  object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by wastelandlab** [ltdrdata/ComfyUI-Impact-Pack#275]
I followed a guide on youtube to use the impact pack and 4 components (SAM Loader, SAM Detector combined, BBOX Detector SEGS & CLIPSegDetectorProvider)  to segment the image with the SAM model and then inpaint the segment later. 

But when I try to put the image into the BBOX Detector SEGS, the CLIPSegDetectorProvider shows me this error: 

Error occurred when executing CLIPSegDetectorProvider:

object of type 'NoneType' has no len()

  File "/content/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ComfyUI/execution.py", line 97, in get_output_data
    output_is_list = [False] * len(results[0])

    
<img width="685" alt="Screenshot 2023-11-11 at 11 32 40" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/121642306/8708ca6e-c4f1-4b8a-96a4-843275b26f28">

<img width="943" alt="Screenshot 2023-11-11 at 11 44 43" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/121642306/24614a89-b542-489b-a35e-725b532b3d12">

I don't no why the length of the object is None, since I put the image from the first generation into it and also tried different ways. 

I tried to add some obj checks for the functions get_input_data and get_output_data in execution.py but nothing really helped so far. 

Can someone help?

**Comment by ltdrdata** [comment]
If you look at the error message in the terminal, it will likely indicate that 'CLIPSeg' needs to be installed.

**Comment by bjsongzhen** [comment]
https://github.com/biegert/ComfyUI-CLIPSeg.git

**Comment by ltdrdata** [comment]
> https://github.com/biegert/ComfyUI-CLIPSeg.git

You should not `git clone` to install that extension. Just install through ComfyUI-Manager.
