### ISSUE TITLE
FaceDetailer OOM

### ISSUE THREAD

**Issue by CrimsonYoshi** [ltdrdata/ComfyUI-Impact-Pack#276]
When running workflows with FaceDetailer included, I'll run out of VRAM at the FaceDetailer node, but upon queueing the same prompt again, changing nothing, it runs through successfully without any memory errors. 

Any idea what would be causing this? Having to go through KSampler twice is effectively halving the workflow speed.

**Comment by ltdrdata** [comment]
If you are using SAM Loader, try switching it to CPU mode and see if that resolves the issue.
