### ISSUE TITLE
UltralyticsDetectorProvider node missing

### ISSUE THREAD

**Issue by alchemist616** [ltdrdata/ComfyUI-Impact-Pack#277]
I've installed the latest ComfyUI Impact Pack. Trying to use UltralyticsDetectorProvider with FaceDetailer but UltralyticsDetectorProvider is not available in nodes. Also installed the subpack but UltralyticsDetectorProvider is still missing. How do I use it?

**Comment by ltdrdata** [comment]
Can you share comfyui log files?

**Comment by alchemist616** [comment]
Loading subpack failed, it seems.
-------------------------------------------------------------------------------------------------
### Loading: ComfyUI-Impact-Pack (V4.30.3)
Traceback (most recent call last):
  File "E:\SDXL\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\SDXL\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Subpack\\__init__.py'

Cannot import E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack module for custom nodes: [Errno 2] No such file or directory: 'E:\\SDXL\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Subpack\\__init__.py'
### Loading: ComfyUI-Inspire-Pack (V0.43)
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1680 [eb0407e8] | Released on '2023-11-13'

Import times for custom nodes:
   0.0 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds (IMPORT FAILED): E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
   0.0 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.3 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by ltdrdata** [comment]
The `Impact Pack` is set up to automatically install subpacks. Have you manually cloned the subpack using git? If so, that's not the correct approach. (Especially, that is wrong place)

The simplest solution is to clone the subpack as `ComfyUI-Impact-Pack/impact_subpack`. 
However, the reason for the automatic installation not working is what I'm curious about, which is why I requested the logs. Issues like this have been reported occasionally lately.

Before applying this solution, please provide the complete execution logs.

**Comment by alchemist616** [comment]
Ah ok. Yes I can actually see the subpack contents in the ComfyUI-Impact-Pack/impact_subpack, so it is installed automatically. I did also manually clone it when I saw UltralyticsDetectorProvider node missing (which was done wrong as you pointed out). Therefore the issue appears to be that I do have the subpack installed but somehow UltralyticsDetectorProvider node is not available to use. 

Impact Pack was installed via ComfyUI manager, so it was all done automatically. Should I uninstall the Impact Pack and manually clone it from its git repository?

**Comment by alchemist616** [comment]
Ok, I uninstalled the Impack Pack and Subpack, then manually cloned the both from the repository. When I launch ComfyUI, I get the following in the log which I think may points to why it's not working properly. I'm very new to all this, what should I do next?

Using cached ultralytics-8.0.209-py3-none-any.whl (645 kB)
Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl (38.1 MB)
Using cached seaborn-0.13.0-py3-none-any.whl (294 kB)
Installing collected packages: opencv-python, thop, seaborn, ultralytics
  WARNING: The scripts ultralytics.exe and yolo.exe are installed in 'E:\SDXL\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed opencv-python-4.8.1.78 seaborn-0.13.0 thop-0.1.1.post2209072238 ultralytics-8.0.209
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: Updating subpack

**Comment by ltdrdata** [comment]
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Does the log that appeared when you ran this with `run_cpu.bat` or `run_gpu.bat` look correct? 
And posting only a portion of the log instead of the entire log makes it challenging to comprehend the situation.

**Comment by alchemist616** [comment]
I'm sorry. It's a bit long so I didn't copy the entire log but yes I should have done so - I've copied the entire log below now. I ran run_nvidia_gpu.bat

E:\SDXL\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-11-14 16:03:58.821197

Prestartup times for custom nodes:
   0.0 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 32533 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.30.3)
## ComfyUI-Impact-Pack: Updating dependencies
### ComfyUI-Impact-Pack: Check dependencies
Collecting ultralytics!=8.0.177 (from -r requirements.txt (line 1))
  Using cached ultralytics-8.0.209-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: matplotlib>=3.3.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: numpy>=1.22.2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.0)
Collecting opencv-python>=4.6.0 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: pillow>=7.1.2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (10.0.1)
Requirement already satisfied: pyyaml>=5.3.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.0+cu118)
Requirement already satisfied: torchvision>=0.9.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.16.0+cu118)
Requirement already satisfied: tqdm>=4.64.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.66.1)
Requirement already satisfied: pandas>=1.1.4 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.3)
Collecting seaborn>=0.11.0 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached seaborn-0.13.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: psutil in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (5.9.5)
Requirement already satisfied: py-cpuinfo in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (9.0.0)
Collecting thop>=0.1.1 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Requirement already satisfied: contourpy>=1.0.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: cycler>=0.10 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.44.0)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: filelock in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.12.4)
Requirement already satisfied: typing-extensions in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.9.2)
Requirement already satisfied: colorama in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.64.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: six>=1.5 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.3.0)
Using cached ultralytics-8.0.209-py3-none-any.whl (645 kB)
Using cached opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl (38.1 MB)
Using cached seaborn-0.13.0-py3-none-any.whl (294 kB)
Installing collected packages: opencv-python, thop, seaborn, ultralytics
  WARNING: The scripts ultralytics.exe and yolo.exe are installed in 'E:\SDXL\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed opencv-python-4.8.1.78 seaborn-0.13.0 thop-0.1.1.post2209072238 ultralytics-8.0.209
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: Updating subpack
Requirement already satisfied: ultralytics!=8.0.177 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (8.0.209)
Requirement already satisfied: matplotlib>=3.3.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: numpy>=1.22.2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.0)
Requirement already satisfied: opencv-python>=4.6.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.8.1.78)
Requirement already satisfied: pillow>=7.1.2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (10.0.1)
Requirement already satisfied: pyyaml>=5.3.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.0+cu118)
Requirement already satisfied: torchvision>=0.9.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.16.0+cu118)
Requirement already satisfied: tqdm>=4.64.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.66.1)
Requirement already satisfied: pandas>=1.1.4 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: seaborn>=0.11.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.13.0)
Requirement already satisfied: psutil in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (5.9.5)
Requirement already satisfied: py-cpuinfo in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (9.0.0)
Requirement already satisfied: thop>=0.1.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.1.1.post2209072238)
Requirement already satisfied: contourpy>=1.0.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: cycler>=0.10 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.44.0)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: filelock in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.12.4)
Requirement already satisfied: typing-extensions in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.8.0)
Requirement already satisfied: sympy in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.9.2)
Requirement already satisfied: colorama in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.64.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: six>=1.5 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in e:\sdxl\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.3.0)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
### Loading: ComfyUI-Inspire-Pack (V0.43)
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1680 [eb0407e8] | Released on '2023-11-13'

Import times for custom nodes:
   0.0 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.2 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
  16.2 seconds: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by alchemist616** [comment]
Oh actually - I tried manually cloned it again and the node is there now. I don't know how... and the log looks identical to the previous one so I'm not sure what happened differently. However, thank you very much for your help!

**Comment by ltdrdata** [comment]
> Oh actually - I tried manually cloned it again and the node is there now. I don't know how... and the log looks identical to the previous one so I'm not sure what happened differently. However, thank you very much for your help!

I'm very confused. If you did it correctly, there shouldn't be the same logs as before.

```
File "E:\SDXL\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 879, in exec_module
File "", line 1016, in get_code
File "", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack\init.py'
...
0.0 seconds (IMPORT FAILED): E:\SDXL\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
```

**Comment by alchemist616** [comment]
Yeh I'm confused too, like I mentioned I'm new to a lot of this. Since the node is there now, instead wasting more of your time, I will continue to do some digging on my end to see if I can make sense of it! I'll reach out if I have more issues. Once again, thank you very much!
