### ISSUE TITLE
There is difficulty in understanding this matter, w

### ISSUE THREAD

**Issue by HASAN3DG** [ltdrdata/ComfyUI-Impact-Pack#278]
There is difficulty in understanding this matter, why the path of the model is not known even though it is downloaded ☹️ ☹️ ☹️
![Screenshot 2023-11-14 090054](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/74836845/7fb96e74-b194-46ee-9dd7-bd3f605222be)

**Comment by HASAN3DG** [comment]
When I go to the manager and ask to install the problem, this message comes, knowing that it has been installed
![Screenshot 2023-11-14 090329](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/74836845/5b74881b-a91b-4226-80e1-ea2f2f23a3e7)

**Comment by ltdrdata** [comment]
Your installed `Impact Pack` is either a very outdated version or has failed to import. Please show the complete execution log from ComfyUI.

**Comment by HASAN3DG** [comment]
![Screenshot 2023-11-14 100438](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/74836845/b0c13fab-d49f-4e93-aeee-7da176b46a99)

**Comment by ltdrdata** [comment]
Nope. It's not important log. I need the **full log**. If you are using ComfyUI-Manager. You can find `comfyui.log` file on execution path.

**Comment by HASAN3DG** [comment]
When loading the graph, the following node types were not found:
UltralyticsDetectorProvider
CLIPSeg
## make-basic_pipe [2c8c61]
Nodes that have failed to load will show as red on the graph.

Close
Queue size: 0⚙️
Queue Prompt
Extra options
Queue FrontView QueueView History
Save
Load
Refresh
Clipspace
Clear
Load Default
Manager
Source
Type
Timestamp
Message
ComfyUI.Logging
debug
14:01:19.004Z
{
  "UserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
}
Comfy.App
debug
14:01:19.073Z
{
  "Extensions": [
    "/extensions/core/clipspace.js",
    "/extensions/core/colorPalette.js",
    "/extensions/core/contextMenuFilter.js",
    "/extensions/core/dynamicPrompts.js",
    "/extensions/core/editAttention.js",
    "/extensions/core/groupOptions.js",
    "/extensions/core/invertMenuScrolling.js",
    "/extensions/core/keybinds.js",
    "/extensions/core/linkRenderMode.js",
    "/extensions/core/maskeditor.js",
    "/extensions/core/nodeTemplates.js",
    "/extensions/core/noteNode.js",
    "/extensions/core/rerouteNode.js",
    "/extensions/core/saveImageExtraOutput.js",
    "/extensions/core/slotDefaults.js",
    "/extensions/core/snapToGrid.js",
    "/extensions/core/uploadImage.js",
    "/extensions/core/widgetInputs.js",
    "/extensions/ComfyUI-AnimateDiff-Evolved/js/gif_preview.js",
    "/extensions/ComfyUI-Impact-Pack/comboBoolMigration.js",
    "/extensions/ComfyUI-Impact-Pack/common.js",
    "/extensions/ComfyUI-Impact-Pack/impact-image-util.js",
    "/extensions/ComfyUI-Impact-Pack/impact-pack.js",
    "/extensions/ComfyUI-Impact-Pack/impact-sam-editor.js",
    "/extensions/ComfyUI-Impact-Pack/impact-segs-picker.js",
    "/extensions/ComfyUI-Manager-main/a1111-alter-downloader.js",
    "/extensions/ComfyUI-Manager-main/comfyui-manager.js",
    "/extensions/ComfyUI-Manager-main/comfyui-share.js",
    "/extensions/ComfyUI-Manager-main/common.js",
    "/extensions/ComfyUI-Manager-main/custom-nodes-downloader.js",
    "/extensions/ComfyUI-Manager-main/model-downloader.js",
    "/extensions/ComfyUI-Manager-main/snapshot.js"
  ]
}
ComfyUI.Logging
debug
14:01:19.088Z
{
  "system": {
    "os": "nt",
    "python_version": "3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]",
    "embedded_python": true
  },
  "devices": {
    "name": "cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync",
    "type": "cuda",
    "index": 0,
    "vram_total": 12884246528,
    "vram_free": 11624513536,
    "torch_vram_total": 0,
    "torch_vram_free": 0
  }
}
Comfy.App
warn
14:01:19.236Z
{
  "MissingNodes": [
    "UltralyticsDetectorProvider",
    "CLIPSeg",
    "## make-basic_pipe [2c8c61]"
  ]
}

Clear
Export logs...
View exported logs...
Close
all
This node is simply a combination of CheckpointLoaderSimple and CLIPTextEncode using ToBasicPipe, so you can replace it without using Workflow-Component.
To prevent any impact on the face during hair restyling, we create a face mask.
By removing the face mask from the hair mask and introducing flexibility to the hair mask, we create a mask that maintains the hair's fluidity while not affecting the face.
First, extract the mask of the hair to be restyled.
To introduce flexibility to the hair restyling, we increase the dilation to create a broader mask for the hair.
Using the refined mask, it is possible to change the hairstyle with a strong denoising effect, affecting only the hair without impacting the face.
Using the inverted face mask, the discrepancies caused by the detailer are resolved with a lower denoise level.

** Discrepancies occur only when the crop_factor is set to a lower value.
Strong denoising around the hair mask is causing distortion in the background. To address this, an inverted mask of the face is generated to inpaint the entire region excluding the face, aiming to seamlessly integrate it.
wildcard spec: if kept empty, this option will be ignored
long straight hair / 0.75 / 376934336013155
braid hair / 0.6 / 376934336013155
blond curly hair / 0.9 / 376934336013155
bun hair / 0.6 / 376934336013155

bob hair / 0.7 / 376934336013157

simple plaits hair / 0.7 / 376934336013158

pony tail / 0.7 / 376934336013163
wildcard spec: if kept empty, this option will be ignored

**Comment by ltdrdata** [comment]
> When loading the graph, the following node types were not found:
> UltralyticsDetectorProvider
> CLIPSeg

Oh, the logs I'm referring to are not the ones from the browser; those logs pertain to the server side, which is what I'm talking about.

And if you run it through `run_gpu.bat` with `ComfyUI-Manager` installed, there should be a file named `comfyui.log` in the directory where `run_gpu.bat` is located.

**Comment by Vegansaregrassfed** [comment]
I think this is the same problem I had yesterday.

My fix- via Comfy Manager uninstall Impact-Pack
-restart comfy
-via Comfy Manager reinstall Impact-Pack
