### ISSUE TITLE
AITemplate compatibility

### ISSUE THREAD

**Issue by MaxLanc** [ltdrdata/ComfyUI-Impact-Pack#28]
¡Hello!

I have been using AITemplate for a bit now. This repo: https://github.com/hlky/AIT

And now I started testing the detailing nodes and they throw up an error with AITemplate.
AITemplate requires sizes to be on multiples of 64 and so far FaceDetailer has generated non compatible sizes, is there a way to add AITemplate compatibility by having a node that enforces sizes to be on multiples of 64, or is it already possible to have it generate on said multiples?

EDIT: Got a workaround by switching to crop_region and set guide size to 512, AIT generates on multiples of 64 STARTING on 512 it seems.

On pic related it generated an area of 766, 832 which are no go for AIT

![error1](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/95586248/6f279617-686f-4a10-b0ef-c2c3555fc2f9)
![error2](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/95586248/5810c1a2-f381-45a0-bbd7-178bc2d6539e)

**Comment by ltdrdata** [comment]
I am currently considering this issue. In the existing ComfyUI structure, the **Impact Pack** was implemented under the assumption that there would be constraints in multiples of 64. However, as those constraints are now eliminated, the **Impact Pack** was patched to increase flexibility.

If there are such constraints in AITemplate, it is necessary to apply them only when using AITemplate. To do this, it is necessary to determine whether the model is being used by AITemplate.

For this purpose, a separate hidden input is needed to convey whether the constraint of multiples of 64 is required.
https://github.com/comfyanonymous/ComfyUI/blob/fb4bf7f591e4c0917e66814370216ef7858c6b6a/execution.py#L32

Also, originally there was a constraint that the original image itself had to be 64x64. However, currently, we cannot guarantee this. In cases where the size is smaller than that, I will need to implement a form of skip processing.

What happens if the EmptyLatent of AITemplate is not a multiple of 64?

**Comment by MaxLanc** [comment]
> What happens if the EmptyLatent of AITemplate is not a multiple of 64?

It errors out with invalid input size, AITemplate needs to generate at multiples of 64, AIT dev has said he might eventually try creating the modules on multiples of 8 but so far its not a given.

Maybe a separate node for AITemplate? Because I've managed to get it working with some manipulation of the parameters in the nodes, but is mostly a guessing game. As long as it manages to become a multiple of 64 it works

**Comment by ltdrdata** [comment]
> > What happens if the EmptyLatent of AITemplate is not a multiple of 64?
> 
> It errors out with invalid input size, AITemplate needs to generate at multiples of 64, AIT dev has said he might eventually try creating the modules on multiples of 8 but so far its not a given.
> 
> Maybe a separate node for AITemplate? Because I've managed to get it working with some manipulation of the parameters in the nodes, but is mostly a guessing game. As long as it manages to become a multiple of 64 it works

We need a feature that can provide separate options for frontend or backend to enforce the constraint of being a multiple of 64, whether it's in 64-multiple mode or not.

**Comment by MaxLanc** [comment]
Yeah, that seems to be the case, afaik ComfyDev has AITemplate support on the to do list, it seems the plan is for users to choose either pytorch or AITemplate if for whatever reason there are no AIT modules for your GPU or using CPU mode

**Comment by MaxLanc** [comment]
So I began asking around and got a nice, fix for this quirk when working with AIT.

Adding this two lines after new_w and new_h on enhance_detail on the core.py file:

` new_w = int(np.ceil(new_w / 64) * 64)
    new_h = int(np.ceil(new_h / 64) * 64)`

This workaround kinda "fixes" the issue at hand, thought it would be best to share here!

**Comment by ltdrdata** [comment]
> So I began asking around and got a nice, fix for this quirk when working with AIT.
> 
> Adding this two lines after new_w and new_h on enhance_detail on the core.py file:
> 
> ` new_w = int(np.ceil(new_w / 64) * 64) new_h = int(np.ceil(new_h / 64) * 64)`
> 
> This workaround kinda "fixes" the issue at hand, thought it would be best to share here!

It is possible to implement a similar approach. It used to be done that way in the past. Of course, it was slightly more complex than that. To be a multiple of 64, the width and height ratios are also restricted. There was an adjustment logic based on that.

In fact, that aspect falls into the realm of somewhat tedious coding, and policy is more important regarding this issue. The question is whether to restrict it explicitly for users to recognize size constraints from the front end or to apply it in the backend without the user's knowledge, which may slightly deviate from the user's intention.

In fact, from a purely implementation perspective, it is more convenient to apply it broadly without users having to worry about it. Even if constraints are imposed at the front end, there is always a possibility of incorrect values being passed to the backend through workflows or data stored with incorrect inputs.

**Comment by MaxLanc** [comment]
I see I see.

Maybe having it as a separate compatibility "patch" for AiTemplate could be an alternative until we get more flexible AIT modules?
