### ISSUE TITLE
Failed to import subpack

### ISSUE THREAD

**Issue by Deus1Rex** [ltdrdata/ComfyUI-Impact-Pack#281]
I've tried updating everything, deleting and having it redownload the subpack, and i've gone through several issue reports on here looking for something similar to see if the resolution was the same as my issue, so far no luck. I'm sure it's probably something simple, but i'm very new to all this.

** ComfyUI start up time: 2023-11-14 16:30:36.696892

Prestartup times for custom nodes:
   0.0 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 32708 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 406, in <module>
    import impact.subpack_nodes
  File "G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'
---------------------------------

### ComfyUI Revision: 1688 [728613bb] | Released on '2023-11-14'

Import times for custom nodes:
   0.0 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\example_node.py
   0.2 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.8 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by ltdrdata** [comment]
It seems to be a similar situation to this issue. However, providing precise instructions is challenging as your setup doesn't involve using 'portable.' Are you using venv?

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/280#issuecomment-1811815688

**Comment by Deus1Rex** [comment]
I just retried uninstalling and reinstalling ultralytics as suggested by your link. I'm not using a venv nor have i. I just double checked and i think i am running the portable version? i got it from this: https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z .Is it possible this is some kind of permissions issue? new log after uninstalling and reinstalling ultralytics, it looks identical to the previous log to me but it might help:

** ComfyUI start up time: 2023-11-14 20:04:30.676250

Prestartup times for custom nodes:
   0.0 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 32708 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.30.6)
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 406, in <module>
    import impact.subpack_nodes
  File "G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'
---------------------------------

### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1688 [728613bb] | Released on '2023-11-14'

Import times for custom nodes:
   0.0 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\example_node.py
   0.2 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.8 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by ltdrdata** [comment]
then do you have `G:\Programs\SD ComfyUI\python_embeded` directory?

**Comment by Deus1Rex** [comment]
yes, i do.

**Comment by ltdrdata** [comment]
> yes, i do.

Then did you reinstall ultrayltics through like below?

```
G:\Programs\SD ComfyUI\python_embeded\python.exe -m pip uninstall ultralytics
G:\Programs\SD ComfyUI\python_embeded\python.exe -m pip install ultralytics
```

**Comment by Deus1Rex** [comment]
> Then did you reinstall ultrayltics through like below?
> 
> ```
> G:\Programs\SD ComfyUI\python_embeded\python.exe -m pip uninstall ultralytics
> G:\Programs\SD ComfyUI\python_embeded\python.exe -m pip install ultralytics
> ```

Yes, thats exactly what i did.

**Comment by ltdrdata** [comment]
> > Then did you reinstall ultrayltics through like below?
> > ```
> > G:\Programs\SD ComfyUI\python_embeded\python.exe -m pip uninstall ultralytics
> > G:\Programs\SD ComfyUI\python_embeded\python.exe -m pip install ultralytics
> > ```
> 
> Yes, thats exactly what i did.

What message is displayed during then?

**Comment by Deus1Rex** [comment]
i reinstalled ultralytics again to get the messages:

Dylan@Dyl-Desktop MINGW64 /g/Programs/SD ComfyUI/python_embeded
$ python.exe -m pip uninstall ultralytics
Found existing installation: ultralytics 8.0.209
Uninstalling ultralytics-8.0.209:
  Would remove:
    g:\programs\python\python 3.10.6\lib\site-packages\ultralytics-8.0.209.dist-info\*
    g:\programs\python\python 3.10.6\lib\site-packages\ultralytics\*
    g:\programs\python\python 3.10.6\scripts\ultralytics.exe
    g:\programs\python\python 3.10.6\scripts\yolo.exe
Proceed (Y/n)? y
  Successfully uninstalled ultralytics-8.0.209
  
  
  Dylan@Dyl-Desktop MINGW64 /g/Programs/SD ComfyUI/python_embeded
$ python.exe -m pip install ultralytics
Collecting ultralytics
  Using cached ultralytics-8.0.209-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: matplotlib>=3.3.0 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (3.8.1)
Requirement already satisfied: numpy>=1.22.2 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (1.26.2)
Requirement already satisfied: opencv-python>=4.6.0 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (4.8.1.78)
Requirement already satisfied: pillow>=7.1.2 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (10.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (2.1.1+cu118)
Requirement already satisfied: torchvision>=0.9.0 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (0.16.1+cu118)
Requirement already satisfied: tqdm>=4.64.0 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (4.66.1)
Requirement already satisfied: pandas>=1.1.4 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (2.1.3)
Requirement already satisfied: seaborn>=0.11.0 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (0.13.0)
Requirement already satisfied: psutil in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (5.9.6)
Requirement already satisfied: py-cpuinfo in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (9.0.0)
Requirement already satisfied: thop>=0.1.1 in g:\programs\python\python 3.10.6\lib\site-packages (from ultralytics) (0.1.1.post2209072238)
Requirement already satisfied: contourpy>=1.0.1 in g:\programs\python\python 3.10.6\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.2.0)
Requirement already satisfied: cycler>=0.10 in g:\programs\python\python 3.10.6\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in g:\programs\python\python 3.10.6\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (4.44.1)
Requirement already satisfied: kiwisolver>=1.3.1 in g:\programs\python\python 3.10.6\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
Requirement already satisfied: packaging>=20.0 in g:\programs\python\python 3.10.6\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in g:\programs\python\python 3.10.6\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in g:\programs\python\python 3.10.6\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in g:\programs\python\python 3.10.6\lib\site-packages (from pandas>=1.1.4->ultralytics) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in g:\programs\python\python 3.10.6\lib\site-packages (from pandas>=1.1.4->ultralytics) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in g:\programs\python\python 3.10.6\lib\site-packages (from requests>=2.23.0->ultralytics) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in g:\programs\python\python 3.10.6\lib\site-packages (from requests>=2.23.0->ultralytics) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in g:\programs\python\python 3.10.6\lib\site-packages (from requests>=2.23.0->ultralytics) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in g:\programs\python\python 3.10.6\lib\site-packages (from requests>=2.23.0->ultralytics) (2023.7.22)
Requirement already satisfied: filelock in g:\programs\python\python 3.10.6\lib\site-packages (from torch>=1.8.0->ultralytics) (3.13.1)
Requirement already satisfied: typing-extensions in g:\programs\python\python 3.10.6\lib\site-packages (from torch>=1.8.0->ultralytics) (4.8.0)
Requirement already satisfied: sympy in g:\programs\python\python 3.10.6\lib\site-packages (from torch>=1.8.0->ultralytics) (1.12)
Requirement already satisfied: networkx in g:\programs\python\python 3.10.6\lib\site-packages (from torch>=1.8.0->ultralytics) (3.2.1)
Requirement already satisfied: jinja2 in g:\programs\python\python 3.10.6\lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.2)
Requirement already satisfied: fsspec in g:\programs\python\python 3.10.6\lib\site-packages (from torch>=1.8.0->ultralytics) (2023.10.0)
Requirement already satisfied: colorama in g:\programs\python\python 3.10.6\lib\site-packages (from tqdm>=4.64.0->ultralytics) (0.4.6)
Requirement already satisfied: six>=1.5 in g:\programs\python\python 3.10.6\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in g:\programs\python\python 3.10.6\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in g:\programs\python\python 3.10.6\lib\site-packages (from sympy->torch>=1.8.0->ultralytics) (1.3.0)
Using cached ultralytics-8.0.209-py3-none-any.whl (645 kB)
Installing collected packages: ultralytics
Successfully installed ultralytics-8.0.209

**Comment by Deus1Rex** [comment]
i also get this when i try to use the python.exe in the python_embedded folder:

Python 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>> -m pip uninstall ultralytics
  File "<stdin>", line 1
    -m pip uninstall ultralytics
       ^^^
SyntaxError: invalid syntax
>> -m pip install ultralytics
  File "<stdin>", line 1
    -m pip install ultralytics
       ^^^
SyntaxError: invalid syntax
>> pip uninstall ultralytics
  File "<stdin>", line 1
    pip uninstall ultralytics
        ^^^^^^^^^
SyntaxError: invalid syntax
>> pip install ultralytics
  File "<stdin>", line 1
    pip install ultralytics
        ^^^^^^^
SyntaxError: invalid syntax
>>

**Comment by ltdrdata** [comment]
Try this command.

`G:\Programs\SD ComfyUI\python_embeded\python.exe -c "from ultralytics import YOLO"`

**Comment by Deus1Rex** [comment]
Output after "python.exe -c "from ultralytics import YOLO"" :



Dylan@Dyl-Desktop MINGW64 /g/Programs/SD ComfyUI/python_embeded
$ python.exe -c "from ultralytics import YOLO"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\Programs\Python\python 3.10.6\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "G:\Programs\Python\python 3.10.6\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "G:\Programs\Python\python 3.10.6\lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "G:\Programs\Python\python 3.10.6\lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "G:\Programs\Python\python 3.10.6\lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "G:\Programs\Python\python 3.10.6\lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "G:\Programs\Python\python 3.10.6\lib\site-packages\ultralytics\utils\__init__.py", line 5, in <module>
    import logging.config
  File "G:\Programs\Python\python 3.10.6\lib\logging\config.py", line 30, in <module>
    import logging.handlers
  File "G:\Programs\Python\python 3.10.6\lib\logging\handlers.py", line 26, in <module>
    import io, logging, socket, os, pickle, struct, time, re
  File "G:\Programs\Python\python 3.10.6\lib\socket.py", line 51, in <module>
    import _socket
ImportError: Module use of python311.dll conflicts with this version of Python.

Dylan@Dyl-Desktop MINGW64 /g/Programs/SD ComfyUI/python_embeded
$

**Comment by ltdrdata** [comment]
MINGW64??? Why don't you execute it natively?"
And in that case you should `./python.exe -c "from ultralytics import YOLO"`

**Comment by Deus1Rex** [comment]
This is the output. its MINGW64 because for some reason that's what i have a right click option for, and it's whats most convenient.

Dylan@Dyl-Desktop MINGW64 /g/Programs/SD ComfyUI/python_embeded
$ ./python.exe -c "from ultralytics import YOLO"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ultralytics'

**Comment by ltdrdata** [comment]
Try reinstalling Ultralytics as follows:

```
./python.exe -m pip uninstall ultralytics
./python.exe -m pip install ultralytics
./python.exe -m pip list
./python.exe -c "from ultralytics import YOLO"
```

**Comment by ltdrdata** [comment]
> This is the output. its MINGW64 because for some reason that's what i have a right click option for, and it's whats most convenient.

Since mingw64 is also a kind of virtual environment, we cannot guarantee what hidden issues may arise here.
That's why I recommended running it natively.

**Comment by Deus1Rex** [comment]
> Try reinstalling Ultralytics as follows:
> 
> ```
> ./python.exe -m pip uninstall ultralytics
> ./python.exe -m pip install ultralytics
> ./python.exe -m pip list
> ./python.exe -c "from ultralytics import YOLO"
> ```


It seems like "python.exe -m pip install ultralytics" without the ./ was just installing everything in the main python directory and wasn't putting it in the Python_embedded directory. Convenience has failed me once again, MINGW64 was the problem.

** ComfyUI start up time: 2023-11-14 21:30:48.684209

Prestartup times for custom nodes:
   0.0 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 32708 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.30.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1688 [728613bb] | Released on '2023-11-14'

Import times for custom nodes:
   0.0 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\example_node.py
   0.7 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.8 seconds: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: G:\Programs\SD ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json


After running those commands it all works like it should, thanks so much for your help. I really appreciate it.
