### ISSUE TITLE
MESA-LOADER: failed to retrieve device information

### ISSUE THREAD

**Issue by jerrytt** [ltdrdata/ComfyUI-Impact-Pack#282]
commit 5d60566efeefc5fe27c7e3f18880de3a7185edb2

when using bbox detector (segs)
comfyui hang forever .

backend cmd show :
MESA-LOADER: failed to retrieve device information

**Comment by ltdrdata** [comment]
Can you check if there are no issues in version 62c5a66b41a47897c8a991871e5b044dc2b1497a?

**Comment by jerrytt** [comment]
verify the issue commit should be this one :
commit 1e7b87b00d29a1c253efca309d91f494b00d3256 (HEAD -> old_2)
Author: Dr.Lt.Data <dr.lt.data@gmail.com>
Date:   Sun Nov 5 12:11:52 2023 +0900

    optimize: use gpu for dilation/erosion
    fix: mask cache didn't work on regional sampler
    fix: erosion didn't work on ultralytics detectors

after use just use early commit than this one,   all works .

**Comment by ltdrdata** [comment]
> verify the issue commit should be this one : commit [1e7b87b](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/1e7b87b00d29a1c253efca309d91f494b00d3256) (HEAD -> old_2) Author: Dr.Lt.Data [dr.lt.data@gmail.com](mailto:dr.lt.data@gmail.com) Date: Sun Nov 5 12:11:52 2023 +0900
> 
> ```
> optimize: use gpu for dilation/erosion
> fix: mask cache didn't work on regional sampler
> fix: erosion didn't work on ultralytics detectors
> ```
> 
> after use just use early commit than this one, all works .

Do you happen to use a virtual machine or something similar? There is a reported issue in that case.

The improvement was made to enable GPU acceleration for mask operations, but it seems necessary to adjust it to be used optionally.

**Comment by jerrytt** [comment]
> > verify the issue commit should be this one : commit [1e7b87b](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/1e7b87b00d29a1c253efca309d91f494b00d3256) (HEAD -> old_2) Author: Dr.Lt.Data [dr.lt.data@gmail.com](mailto:dr.lt.data@gmail.com) Date: Sun Nov 5 12:11:52 2023 +0900
> > ```
> > optimize: use gpu for dilation/erosion
> > fix: mask cache didn't work on regional sampler
> > fix: erosion didn't work on ultralytics detectors
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after use just use early commit than this one, all works .
> 
> Do you happen to use a virtual machine or something similar? There is a reported issue in that case.
> 
> The improvement was made to enable GPU acceleration for mask operations, but it seems necessary to adjust it to be used optionally.

just baremetal machine.
but I use external GPU . thunderbolt connection.

I have 1 intergate Intel GPU, and  2  nvidia GPU.

```
drwxr-xr-x  2 root root        160 Nov 15 09:21 by-path
crw-rw----+ 1 root video  226,   0 Nov 15 09:21 card0
crw-rw----+ 1 root video  226,   1 Nov 15 09:21 card1
crw-rw----+ 1 root video  226,   2 Nov 15 09:21 card2
crw-rw-rw-  1 root render 226, 128 Nov 15 09:21 renderD128
crw-rw-rw-  1 root render 226, 129 Nov 15 09:21 renderD129
crw-rw-rw-  1 root render 226, 130 Nov 15 09:21 renderD130
```

**Comment by ltdrdata** [comment]
I just patched. Update and apply this option.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md#if-the-nodes-of-the-impact-pack-hang-during-execution

**Comment by jerrytt** [comment]
```
    kernel = np.ones((abs(dilation_factor), abs(dilation_factor)), np.uint8)
    gpu_kernel = cv2.UMat(kernel)
    ```
hung code

**Comment by jerrytt** [comment]
> I just patched. Update and apply this option.
> 
> https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md#if-the-nodes-of-the-impact-pack-hang-during-execution

still hung ,  after add " disable_gpu_opencv = True"  in impact-pack.ini

**Comment by jerrytt** [comment]
> I just patched. Update and apply this option.
> 
> https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md#if-the-nodes-of-the-impact-pack-hang-during-execution

oh, forget back to Main branch.


Thanks  fix works
