### ISSUE TITLE
mask-editor , can NOT append the exist  mask to the Editor page 

### ISSUE THREAD

**Issue by jerrytt** [ltdrdata/ComfyUI-Impact-Pack#284]
image load -> right click -> mask-editor 

draw some mask and save, mask show on the preview window.

if you want add more mask area, image load->right click -> mask-editor .    the old mask was clean .!

**Comment by ltdrdata** [comment]
This is same issue with this.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/283

I'll fix it.

**Comment by ltdrdata** [comment]
This fixed on latest ComfyUI. Update ComfyUI.

https://github.com/comfyanonymous/ComfyUI/pull/2171
