### ISSUE TITLE
FaceDetailer node freezes ComfyUI.

### ISSUE THREAD

**Issue by bazettfraga** [ltdrdata/ComfyUI-Impact-Pack#285]
Hello, I am having an issue when using the FaceDetailer node. After it prints the following message

```
0: 640x640 1 face, 15.6ms
Speed: 4.6ms preprocess, 15.6ms inference, 42.4ms postprocess per image at shape (1, 3, 640, 640)
```

ComfyUI hangs and cannot be killed unless sending a SIGKILL signal. I am on commits 6145e0b2b27a366f494181145a7461fdf62ece67 and https://github.com/comfyanonymous/ComfyUI/commit/629e4c552cc30a75d2756cbff8095640af3af163, so I do not believe it is any outdated version.
I am running Arch-Linux with kernel 6.6.1, NVIDIA Driver Version: 545.29.02 and CUDA Version: 12.3.
The custom nodes which are running are the following:
```
   0.0 seconds: /mnt/2TBDa/SDSoftware/ComfyUI/custom_nodes/wd14tagger.py
   0.0 seconds: /mnt/2TBDa/SDSoftware/ComfyUI/custom_nodes/advanced_model_merging.py
   0.0 seconds: /mnt/2TBDa/SDSoftware/ComfyUI/custom_nodes/ComfyUI-ImageGlitcher
   0.1 seconds: /mnt/2TBDa/SDSoftware/ComfyUI/custom_nodes/ComfyUI-Manager
   3.1 seconds: /mnt/2TBDa/SDSoftware/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
```
none of which I believe would conflict with Impact Pack.
The bbox detector being provided is `face_yolovn.pt`.

Here is a catbox of an extremely simple workflow which I tested this on and experienced the same issue.
https://files.catbox.moe/qkmrrl.png

**Comment by ltdrdata** [comment]
Try just a simple workflow like this:

load image -> dilate mask -> mask to image -> preview image

If this workflow hang, also.
See troubleshooting section.

**Comment by bazettfraga** [comment]
I apologize for my lack of due diligence ^^', this has resolved the issue!
Before closing, could I ask for a bit of insight as to why OpenCV could be causing an issue with my current GPU/setup?

**Comment by ltdrdata** [comment]
I also don't know the exact cause, but I suspect it could be a driver issue. There have been situations where such issues occurred in a virtual machine, but it's not necessarily always the case.

It seems that based on recent reports coming in, it might be advisable to move in the direction of disabling the default settings.
