### ISSUE TITLE
 "UltralyticsDetectorProvider" missing in Impact-Pack

### ISSUE THREAD

**Issue by agiusthomas** [ltdrdata/ComfyUI-Impact-Pack#290]
Running into issues finding "UltralyticsDetectorProvider" in Impact-Pack. Did a fresh manual install for Comfy UI and also tested it on portable ComfyUI - the node does not appear to be there. Attached a recording showing that it is installed and that it does not appear in search.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/65650245/4bd63102-6a03-4412-9c5d-fc876f358b15

**Comment by 253701** [comment]
Similarly, this error still occurs when reinstalling the latest version of the Manager and this plugin using various methods




### Loading: ComfyUI-Impact-Pack (V4.30.8)
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 406, in <module>
    import impact.subpack_nodes
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils\__init__.py", line 248, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
  File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    sys.stdout.reconfigure(encoding='utf-8')
AttributeError: 'Logger' object has no attribute 'reconfigure'
---------------------------------

### Loading: ComfyUI-Inspire-Pack (V0.45)
### Loading: ComfyUI-Manager (V1.0.1)
### ComfyUI Revision: 1700 [8a451234] | Released on '2023-11-18'

**Comment by ltdrdata** [comment]
> Similarly, this error still occurs when reinstalling the latest version of the Manager and this plugin using various methods
> 
> ### Loading: ComfyUI-Impact-Pack (V4.30.8)
> ### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack
> The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete. Recommended to delete the path and restart ComfyUI. If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.
> 
> ## Traceback (most recent call last):
> File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack__init__.py", line 406, in
> import impact.subpack_nodes
> File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in
> import impact.subcore as subcore
> File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in
> from ultralytics import YOLO
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics__init__.py", line 5, in
> from ultralytics.models import RTDETR, SAM, YOLO
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models__init__.py", line 3, in
> from .rtdetr import RTDETR
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr__init__.py", line 3, in
> from .model import RTDETR
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in
> from ultralytics.engine.model import Model
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\engine\model.py", line 8, in
> from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\cfg__init__.py", line 10, in
> from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py", line 248, in
> LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE) # define globally (used in train.py, val.py, predict.py, etc.)
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py", line 233, in set_logging
> sys.stdout.reconfigure(encoding='utf-8')
> AttributeError: 'Logger' object has no attribute 'reconfigure'
> ### Loading: ComfyUI-Inspire-Pack (V0.45)
> ### Loading: ComfyUI-Manager (V1.0.1)
> ### ComfyUI Revision: 1700 [8a451234] | Released on '2023-11-18'

This is a very peculiar error. It seems like something installed in the packages is causing a conflict. Keep the current portable version as it is, and install a completely new portable version in a different location. Try installing only the manager and impact pack there.

If there are no issues, it is recommended to reinstall the existing other custom node and fully migrate it.

**Comment by ltdrdata** [comment]
> Similarly, this error still occurs when reinstalling the latest version of the Manager and this plugin using various methods
> 
> ### Loading: ComfyUI-Impact-Pack (V4.30.8)
> ### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack
> The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete. Recommended to delete the path and restart ComfyUI. If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.
> 
> ## Traceback (most recent call last):
> File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack__init__.py", line 406, in
> import impact.subpack_nodes
> File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in
> import impact.subcore as subcore
> File "J:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in
> from ultralytics import YOLO
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics__init__.py", line 5, in
> from ultralytics.models import RTDETR, SAM, YOLO
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models__init__.py", line 3, in
> from .rtdetr import RTDETR
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr__init__.py", line 3, in
> from .model import RTDETR
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in
> from ultralytics.engine.model import Model
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\engine\model.py", line 8, in
> from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\cfg__init__.py", line 10, in
> from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py", line 248, in
> LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE) # define globally (used in train.py, val.py, predict.py, etc.)
> File "J:\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py", line 233, in set_logging
> sys.stdout.reconfigure(encoding='utf-8')
> AttributeError: 'Logger' object has no attribute 'reconfigure'
> ### Loading: ComfyUI-Inspire-Pack (V0.45)
> ### Loading: ComfyUI-Manager (V1.0.1)
> ### ComfyUI Revision: 1700 [8a451234] | Released on '2023-11-18'

Update `ComfyUI-Manager` to latest version(v1.0.2) 

This issue has been confirmed to be caused by ComfyUI-Manager conflicting with the recent Ultralytics package in the Windows environment.

**Comment by 253701** [comment]
> > 同样，使用各种方法重新安装最新版本的管理器和此插件时，仍然会出现此错误
> > ### 加载：ComfyUI-Impact-Pack （v4.30.8）
> > ### ComfyUI-Impact-Pack：（导入失败）子包
> > 路径中的模块似乎不完整。建议删除路径并重启 ComfyUI。如果问题仍然存在，请向 https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues 报告。`custom_nodes/ComfyUI-Impact-Pack/impact_subpack`
> > ## 回溯（最近一次调用最后一次）：
> > 文件“J：\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack__init__.py”，第 406 行，导入impact.subpack_nodes文件“J：\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py”，第 4 行，导入 impact.subcore 作为子核心 文件“J：\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py”，第 10 行，从ultralytics 导入 YOLO 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics__init__.py”， 第 5 行， in from ultralytics.models import RTDETR， SAM， YOLO 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models__init__.py”， 第 3 行， in from .rtdetr import RTDETR 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr__init__.py”， 第 3 行，从 .model 导入 RTDETR 文件“J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\model.py”，第 10 行，从 ultralytics.engine.model 导入模型文件“J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\engine\model.py”，第 8 行，从 ultralytics 导入.cfg TASK2DATA、get_cfg get_save_dir文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\cfg__init__.py”，第 10 行，在 from ultralytics.utils import （ASSETS， DEFAULT_CFG， DEFAULT_CFG_DICT， DEFAULT_CFG_PATH， LOGGER， RANK， ROOT， RUNS_DIR， 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py”， line 248， in LOGGER = set_logging（LOGGING_NAME， verbose=VERBOSE） # 全局定义 （在 train.py， val.py、predict.py 等）文件“J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py”，第 233 行，set_logging sys.stdout.reconfigure（encoding='utf-8'） AttributeError：“Logger”对象没有属性“reconfigure”
> > ### 加载中： ComfyUI-Inspire-Pack （V0.45）
> > ### 加载中： ComfyUI-Manager （V1.0.1）
> > ### ComfyUI 修订版：1700 [8a451234] |发布于 '2023-11-18'
> 
> 更新到最新版本（v1.0.2）`ComfyUI-Manager`
> 
> 此问题已被确认是由 ComfyUI-Manager 与 Windows 环境中最新的 Ultralytics 软件包冲突引起的。

thank

**Comment by 253701** [comment]
> > 同样，使用各种方法重新安装最新版本的管理器和此插件时，仍然会出现此错误
> > ### 加载：ComfyUI-Impact-Pack （v4.30.8）
> > ### ComfyUI-Impact-Pack：（导入失败）子包
> > 路径中的模块似乎不完整。建议删除路径并重启 ComfyUI。如果问题仍然存在，请向 https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues 报告。`custom_nodes/ComfyUI-Impact-Pack/impact_subpack`
> > ## 回溯（最近一次调用最后一次）：
> > 文件“J：\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack__init__.py”，第 406 行，导入impact.subpack_nodes文件“J：\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py”，第 4 行，导入 impact.subcore 作为子核心 文件“J：\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py”，第 10 行，从ultralytics 导入 YOLO 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics__init__.py”， 第 5 行， in from ultralytics.models import RTDETR， SAM， YOLO 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models__init__.py”， 第 3 行， in from .rtdetr import RTDETR 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr__init__.py”， 第 3 行，从 .model 导入 RTDETR 文件“J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\model.py”，第 10 行，从 ultralytics.engine.model 导入模型文件“J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\engine\model.py”，第 8 行，从 ultralytics 导入.cfg TASK2DATA、get_cfg get_save_dir文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\cfg__init__.py”，第 10 行，在 from ultralytics.utils import （ASSETS， DEFAULT_CFG， DEFAULT_CFG_DICT， DEFAULT_CFG_PATH， LOGGER， RANK， ROOT， RUNS_DIR， 文件 “J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py”， line 248， in LOGGER = set_logging（LOGGING_NAME， verbose=VERBOSE） # 全局定义 （在 train.py， val.py、predict.py 等）文件“J：\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils__init__.py”，第 233 行，set_logging sys.stdout.reconfigure（encoding='utf-8'） AttributeError：“Logger”对象没有属性“reconfigure”
> > ### 加载中： ComfyUI-Inspire-Pack （V0.45）
> > ### 加载中： ComfyUI-Manager （V1.0.1）
> > ### ComfyUI 修订版：1700 [8a451234] |发布于 '2023-11-18'
> 
> 更新到最新版本（v1.0.2）`ComfyUI-Manager`
> 
> 此问题已被确认是由 ComfyUI-Manager 与 Windows 环境中最新的 Ultralytics 软件包冲突引起的。

Thank you, the problem has been perfectly resolved
