### ISSUE TITLE
哥们 你该升级了

### ISSUE THREAD

**Issue by easeclick** [ltdrdata/ComfyUI-Impact-Pack#292]
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html

**Comment by easeclick** [comment]
Cannot import E:\a\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: MMCV==2.1.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

**Comment by ltdrdata** [comment]
This is fixed on `V4.31.3`
