### ISSUE TITLE
Can't find UltralyticsDetectorProvider node

### ISSUE THREAD

**Issue by lijin1679** [ltdrdata/ComfyUI-Impact-Pack#293]
`
D:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-11-19 21:49:29.218732

Prestartup times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 15610 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints D:\AI\webuiAI\sd-webui-aki-v4.2\models/Stable-diffusion
Adding extra search path configs D:\AI\webuiAI\sd-webui-aki-v4.2\models/Stable-diffusion
Adding extra search path vae D:\AI\webuiAI\sd-webui-aki-v4.2\models/VAE
Adding extra search path loras D:\AI\webuiAI\sd-webui-aki-v4.2\models/Lora
Adding extra search path loras D:\AI\webuiAI\sd-webui-aki-v4.2\models/LyCORIS
Adding extra search path upscale_models D:\AI\webuiAI\sd-webui-aki-v4.2\models/ESRGAN
Adding extra search path upscale_models D:\AI\webuiAI\sd-webui-aki-v4.2\models/RealESRGAN
Adding extra search path upscale_models D:\AI\webuiAI\sd-webui-aki-v4.2\models/SwinIR
Adding extra search path embeddings D:\AI\webuiAI\sd-webui-aki-v4.2\embeddings
Adding extra search path hypernetworks D:\AI\webuiAI\sd-webui-aki-v4.2\models/hypernetworks
Adding extra search path controlnet D:\AI\webuiAI\sd-webui-aki-v4.2\extensions\sd-webui-controlnet\models
Error:
[WinError 1314] 客户端没有所需的特权。: 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to D:\AI\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: D:\AI\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
### ComfyUI-Impact-Pack: Updating subpack
[ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually.
[WinError 5] 拒绝访问。: 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack\\.git\\objects\\pack\\pack-4c9f30a0973e8c9b7d2a5f5e118537c7716a8c09.idx'
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 408, in <module>
    import impact.subpack_nodes
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 248, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    sys.stdout.reconfigure(encoding='utf-8')
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'reconfigure'
---------------------------------

### ComfyUI Revision: 1629 [41b07ff8] | Released on '2023-10-29'
Comfyroll Custom Nodes: Loaded
Registered sys.path: ['D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\nodes\\comfy', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts', 'D:\\AI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\git\\ext\\gitdb', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\comfy', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI', 'D:\\AI\\ComfyUI_windows_portable\\python_embeded\\python311.zip', 'D:\\AI\\ComfyUI_windows_portable\\python_embeded', 'D:\\AI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages', 'D:\\AI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\win32', 'D:\\AI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\win32\\lib', 'D:\\AI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\Pythonwin', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI', '../..']
D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:28: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Prompt_Translate_to_English\__init__.py", line 1, in <module>
    from .BaiduTranslate import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Prompt_Translate_to_English\BaiduTranslate.py", line 7, in <module>
    import execjs
ModuleNotFoundError: No module named 'execjs'

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Prompt_Translate_to_English module for custom nodes: No module named 'execjs'
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work." - Steve Jobs

Import times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Prompt_Translate_to_English
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.3 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   2.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
`

**Comment by JustaLampPost** [comment]
Hi i had the same error,but its  have the **_solution_** too: 
**_ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack_**
**_The module at the custom_nodes/ComfyUI-Impact-Pack/impact_subpack path appears to be incomplete.
### Recommended to delete the path and restart ComfyUI.

**Comment by ltdrdata** [comment]
Update `ComfyUI-Manager`.
