### ISSUE TITLE
How to recombine MULTIPLE refined alpha images with ONE original image?

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#295]
I'm working on the future AP Workflow 6.1 and I'm trying something that is a bit challenging.

I use the _Object Swapper_ function to detect certain elements of a source image. Those elements are isolated as masks.
Then, I turn those elements into SEGS. Those SEGS are then passed to a dedicated _Detailer_ node for inpainting.
So, I end up with different portions of the same image inpainted in different ways. Which is exactly what I want:

<img width="1199" alt="Screenshot 2023-11-19 at 17 10 53" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/d287e3a7-499c-4e8f-b8a6-e7fdef353ab0">

The challenge I have is how to recombine those alpha images with the original image (here in the workflow called "Final Image"). I tried a few different nodes but I'm not getting anywhere.

Any suggestion (please be specific)?

**Please notice that I MUST have separated detailer nodes to treat each SEGS independently.**

Thank you!

**Comment by alessandroperilli** [comment]
Found an answer: `Paste by Mask` node, from the `Masquerade` custom node suite. But if there's any other way, please let me know.

**Comment by ltdrdata** [comment]
> Found an answer: `Paste by Mask` node, from the `Masquerade` custom node suite. But if there's any other way, please let me know.

You can use this way
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/segs-detailer.png

**Comment by alessandroperilli** [comment]
The SEGSPaste is the first thing I tried, but for some reason, it doesn't do anything. I have the same exact configuration in your screenshot and I can't make it work.

**Comment by ltdrdata** [comment]
> The SEGSPaste is the first thing I tried, but for some reason, it doesn't do anything. I have the same exact configuration in your screenshot and I can't make it work.

Does running this workflow and encountering an error imply that there is an issue?

**Comment by alessandroperilli** [comment]
Your example workflow works just fine. I discovered the issue: 

If, instead of a `SEGSDetailer` node, I use a `DetailerForEachDebugPipe` node (which is my preference), then the SEGS output of that node is ignored by the `SEGSPaste` node.

If I use a `SEGSDetailer` node, like in the example workflow you provided, everything works fine.

**Comment by ltdrdata** [comment]
> Your example workflow works just fine. I discovered the issue:
> 
> If, instead of a `SEGSDetailer` node, I use a `DetailerForEachDebugPipe` node (which is my preference), then the SEGS output of that node is ignored by the `SEGSPaste` node.
> 
> If I use a `SEGSDetailer` node, like in the example workflow you provided, everything works fine.

Ah... so the SEGS output of DetailerForEachDebugPipe seems to be incomplete. I'll have to check on this when I get home.

**Comment by ltdrdata** [comment]
This is fixed on V4.31.1.

**Comment by alessandroperilli** [comment]
It works perfectly now. Thank you.
