### ISSUE TITLE
[FEATURE REQUEST] - SEGSPaste accepting 4 or 7 SEGS inputs

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#296]
According to the scenario I described in #295, I'm in a situation where I need to treat multiple SEGS from the same image in independent parallel pipelines. So they can't can't all go into a single Detailer node.

After the manipulation, I need to recombine all of them back into the original image, which I do through a cascade of `SEGSPaste` nodes.
<img width="681" alt="Screenshot 2023-11-20 at 16 16 56" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/c767ab17-069f-41b9-9062-e6d9ef817507">

It would be easier if the SEGSPaste node would accept multiple input SEGS, pasting them back into the original image in one single go. 

1. Is this possible?
2. If it's possible, can this hypothetical node have a mechanism that ignores empty input SEGS rather than generating a halting error?

Thank you!

**Comment by ltdrdata** [comment]
> According to the scenario I described in #295, I'm in a situation where I need to treat multiple SEGS from the same image in independent parallel pipelines. So they can't can't all go into a single Detailer node.
> 
> After the manipulation, I need to recombine all of them back into the original image, which I do through a cascade of `SEGSPaste` nodes. <img alt="Screenshot 2023-11-20 at 16 16 56" width="681" src="https://user-images.githubusercontent.com/9775949/284326982-c767ab17-069f-41b9-9062-e6d9ef817507.png">
> 
> It would be easier if the SEGSPaste node would accept multiple input SEGS, pasting them back into the original image in one single go.
> 
> 1. Is this possible?
> 2. If it's possible, can this hypothetical node have a mechanism that ignores empty input SEGS rather than generating a halting error?
> 
> Thank you!

You can combine segs into singles segs through `SEGSConcat`.
Currently, `SEGSConcat` is designed to concatenate only two SEGS, but in the future, I will expand it to allow the concatenation of an arbitrary number of SEGS.

**Comment by alessandroperilli** [comment]
I suppose I could concatenate two SEGS at a time until I reach the desired number, but the second issue remain: if one of the two input SEGS is empty, the `SEGSConcat` doesn't pass along the non-null input:

<img width="1269" alt="Screenshot 2023-11-21 at 10 39 33" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/a7d1d130-b52c-4f12-93f6-9eae699121f3">

So the entire waterfall is blocked. It would be great if the future version of `SEGSConcat` would tolerate null inputs.

The workaround I have in place for now is to have an `EmptySEGS` node together with an `Any Switch` node:

<img width="980" alt="Screenshot 2023-11-21 at 11 25 00" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/5f3fd9c7-264c-4249-a359-0cde8ae41a6d">

Thank you!

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/2b00e51e-fd0f-4fa7-a40f-ab21db6cbd4e)

Now `SEGSConcat` support arbitrary number of inputs.

**Comment by alessandroperilli** [comment]
It works great, thank you! 

The only issue is that, differently from your example above, only the last SEG appears in alpha mode of a SEGSPreview node. I tried with and without fallback image.

<img width="963" alt="Screenshot 2023-11-22 at 17 57 43" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/60797844-a91f-4c7c-9859-caa6af1e3ab4">
<img width="943" alt="Screenshot 2023-11-22 at 17 57 50" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/f39dc294-0227-4087-b9e7-63bc14c9242a">
<img width="898" alt="Screenshot 2023-11-22 at 17 59 06" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/12a80769-3c05-4575-ae5f-86b27ca537b9">

**Comment by ltdrdata** [comment]
> It works great, thank you!
> 
> The only issue is that, differently from your example above, only the last SEG appears in alpha mode of a SEGSPreview node. I tried with and without fallback image.
> 
> <img alt="Screenshot 2023-11-22 at 17 57 43" width="963" src="https://user-images.githubusercontent.com/9775949/284999778-60797844-a91f-4c7c-9859-caa6af1e3ab4.png"> <img alt="Screenshot 2023-11-22 at 17 57 50" width="943" src="https://user-images.githubusercontent.com/9775949/284999783-f39dc294-0227-4087-b9e7-63bc14c9242a.png"> <img alt="Screenshot 2023-11-22 at 17 59 06" width="898" src="https://user-images.githubusercontent.com/9775949/284999789-12a80769-3c05-4575-ae5f-86b27ca537b9.png">

Check the mask through `SEGS to Mask List`

**Comment by alessandroperilli** [comment]
Nevermind. Now it works just fine without any additional modification. Not sure why it didn't work before. Thanks again. It's great.
