### ISSUE TITLE
Issue with Ultralytics Detector Provider Not Appearing in ComfyUI on C Drive

### ISSUE THREAD

**Issue by hamster-poodle** [ltdrdata/ComfyUI-Impact-Pack#298]
[comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13420797/comfyui.log)
<img width="430" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/67736737/421107cd-8833-4b80-ac63-adaa7164add8">
<img width="1164" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/67736737/fc04fa47-46b6-40dd-9b1e-d15b560f225a">
<img width="487" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/67736737/6334586e-39b9-412c-9acb-fb0668997d8b">

Very Confusing!! ComfyUI. The log file is attached. I'm using portable version.
"I did updated all things. I tried to use ComfyUI in some directories on C drive, but but all attempts failed."
1. There is a Ultralytics folder in general models folder.
2. There is a Ultralystics folder like → python_embeded\Lib\site-packages\ultralytics. (dist-info existing as well)
3. There is a script "ultralytics.exe" in python_embeded\Scripts

I had been using ComfyUI on a secondary SSD for some time, but I installed ComfyUI on the C drive as well to resolve issues with memory allocation for window sizes. However, the Ultralytics Detector Provider from the Impact Pack, which is part of my usual workflow, does not appear, nor does it show up in the add node tab that appears when right-clicking. There are no problems with other nodes. When I checked ComfyUI on the original secondary SSD, the Ultralytics Detector Provider appears as usual there.

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager to `V1.1.2`.
This is fixed.

Same issue: https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/297?notification_referrer_id=NT_kwDOB6Y16LQ4NDg0MjQ3MjU0OjEyODMzMzI4OA#event-11018516497

**Comment by Seifertrolo** [comment]
And hello again, Ultralystics is not showing up in the ComfyUI workspace - is the node dead or just glitching? Everything is loaded, everything is updated, I just downloaded ComfyUI, manager, impact pack, and subpack - all files are in place, but in the workspace there are no words like Ultralystics or similar. Maybe there are some working alternatives?
