### ISSUE TITLE
plz add "wait __ seconds" node for Logics (experimental) 

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#307]
I think Logics (experimental)  need a "wait"  node. 
Sometimes, when executing logic, it is necessary to "wait" to better avoid unnecessary operations and avoid errors that may occur at the time. Or a better time to access logic

**Comment by ltdrdata** [comment]
This is added on V4.33.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/ee9f85f6-bfc0-4e8c-91e5-51b037fa425b)

**Comment by xueqing0622** [comment]
ok, thx, sleep!
