### ISSUE TITLE
Name 'YOLO' not found error

### ISSUE THREAD

**Issue by anagilabs** [ltdrdata/ComfyUI-Impact-Pack#309]
Installed impackt pack in comfyui via manager v1.1, got this error while running nodes:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 27, in doit
    model = subcore.load_yolo(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 21, in load_yolo
    return YOLO(model_path)
           ^^^^
NameError: name 'YOLO' is not defined

installed ultralytics 8.0.177 as mentioned in requirements.txt ... cant understand whats the problem, any help is highly appreciated, thanks.

**Comment by ltdrdata** [comment]
You did it exactly the opposite way; Ultralytics should be installed excluding version 8.0.177.

`ultralytics!=8.0.177` 
`!=` meaning not equal

**Comment by anagilabs** [comment]
Thanks for the reply. My bad, didn't notice '!' over there. However, on my first install of the node, i had ultralytics 8.0.226, it didn't work for that either. got same error. only then i checked the requirements.txt and mistook it for v8.0.177

**Comment by ltdrdata** [comment]
> Thanks for the reply. My bad, didn't notice '!' over there. However, on my first install of the node, i had ultralytics 8.0.226, it didn't work for that either. got same error. only then i checked the requirements.txt and mistook it for v8.0.177

uninstall ultralytics and restart ComfyUI.

**Comment by ltdrdata** [comment]
> Thanks for the reply. My bad, didn't notice '!' over there. However, on my first install of the node, i had ultralytics 8.0.226, it didn't work for that either. got same error. only then i checked the requirements.txt and mistook it for v8.0.177

The issue did not originate there. Please carefully review the initial startup message.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

**Comment by anagilabs** [comment]
Thanks, after removing impact_subpack folder, restarting ComfyUI, and updating the manager, not showing any error.
