### ISSUE TITLE
Failed import: No module named 'comfy.latent_formats'?

### ISSUE THREAD

**Issue by Starnub** [ltdrdata/ComfyUI-Impact-Pack#31]
Hi, I've got a fresh install of ComfyUI and followed the installation instructions here but it says import failed after I launch ComfyUI. I tried other custom nodes and they work but for some reason I can't get this one working. Any help would be appreciated!

Here's the full log:

```
C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 10240 MB, total RAM 16306 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V2.15.3)
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1416, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 48, in <module>
    import impact.impact_server  # to load server api
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 8, in <module>
    import impact.core as core
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1166, in <module>
    import comfy.latent_formats as latent_formats
ModuleNotFoundError: No module named 'comfy.latent_formats'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'comfy.latent_formats'

Import times for custom nodes:
   1.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by ltdrdata** [comment]
> Hi, I've got a fresh install of ComfyUI and followed the installation instructions here but it says import failed after I launch ComfyUI. I tried other custom nodes and they work but for some reason I can't get this one working. Any help would be appreciated!
> 
> Here's the full log:
> 
> ```
> C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
> Total VRAM 10240 MB, total RAM 16306 MB
> xformers version: 0.0.20
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 3080
> Using xformers cross attention
> ### Loading: ComfyUI-Impact-Pack (V2.15.3)
> Traceback (most recent call last):
>   File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1416, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 48, in <module>
>     import impact.impact_server  # to load server api
>   File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 8, in <module>
>     import impact.core as core
>   File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1166, in <module>
>     import comfy.latent_formats as latent_formats
> ModuleNotFoundError: No module named 'comfy.latent_formats'
> 
> Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'comfy.latent_formats'
> 
> Import times for custom nodes:
>    1.0 seconds (IMPORT FAILED): C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> ```

Have you updated to latest version of ComfyUI?
Recent update relies on latest version of ComfyUI.

**Comment by Starnub** [comment]
> Have you updated to latest version of ComfyUI? Recent update relies on latest version of ComfyUI.

Oh wow, didn't realise you had to manually update it after downloading. That fixed it, thank you!
