### ISSUE TITLE
Error occurred when executing UltralyticsDetectorProvider:  name 'YOLO' is not defined

### ISSUE THREAD

**Issue by SimoneTruglia** [ltdrdata/ComfyUI-Impact-Pack#311]
Hi, I've installed the node from the manager and I've followed all the steps of the installation as explained here: https://github.com/ltdrdata/ComfyUI-Impact-Pack#installation

Now, I'm trying to use the face detailer feautr and I'm following this workflow on the youtube channel https://www.youtube.com/watch?v=z4JzuuFyr1Y

The issue is then when it arrives to the node UltralyticsDetectorPipe it thorw this error:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Stable Diffusion\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable Diffusion\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable Diffusion\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 27, in doit
    model = subcore.load_yolo(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Stable Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 20, in load_yolo
    return YOLO(model_path)
           ^^^^
NameError: name 'YOLO' is not defined
```

The yolo model has been installed either from ComfyUI and from https://github.com/ultralytics/assets/releases/ and bbox/face_yolov8m.pt has been selected.

I don't know if it's a bug or it's just me doing something wrong.

Thanks

**Comment by ltdrdata** [comment]
The issue did not originate there. Please carefully review the initial startup message.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

**Comment by SimoneTruglia** [comment]
Hi and thanks for your replay. Sorry to bother but, I'm quite new to all of this. Can you just pointing me in the right direction to solve my problem?

I read what in https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md but I was unable to identify my error

**Comment by ltdrdata** [comment]
> Hi and thanks for your replay. Sorry to bother but, I'm quite new to all of this. Can you just pointing me in the right direction to solve my problem?
> 
> I read what in https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md but I was unable to identify my error

Your case is one of these.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md#an-issue-has-occurred-with-importing-ultralytics

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md#an-issue-has-occurred-about-cv2

You can see error case cleary if update Impact Pack to latest version.
