### ISSUE TITLE
The problem with the Ultralitics node

### ISSUE THREAD

**Issue by Gwara-Gwara** [ltdrdata/ComfyUI-Impact-Pack#312]
After installing Impact Pack, there was no ultralytics node in the menu. When I rebooted the os, the  ultralytics node appeared, but an attempt to start it gives an error
![Снимок экрана 2023-11-23 161125](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/100960949/edcabcfe-41bd-4378-903c-c876611a7008)
[comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13450322/comfyui.log)

**Comment by ltdrdata** [comment]
The issue did not originate there. Please carefully review the initial startup message.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

**Comment by SimoneTruglia** [comment]
ltdrdata I think it's not very nice the way you're handling this problem.
 
 You got the same issue reported 3 different time in less than 24 hours and you are just copy/pasting the same message and immediatly closing the issue.
 
 In my opinion, you should care a bit more about this specific issue.

**Comment by ltdrdata** [comment]
> ltdrdata I think it's not very nice the way you're handling this problem.
> 
> You got the same issue reported 3 different time in less than 24 hours and you are just copy/pasting the same message and immediatly closing the issue.
> 
> In my opinion, you should care a bit more about this specific issue.

I am providing this guidance because the review has already concluded, and a solution is in place. In your opinion, what would be an appropriate way to address this?


To help you understand, I will explain the current situation and my response measures.

The current issue is occurring because users (a) who are using an outdated Manager are being affected by latest verision of 'Ultralytics' package, (b) who are using a certain version of 'cv2' that triggers issues in latest version of 'Ultralytics' package.

It is anticipated that users who typically use existing outdated extensions/packages are encountering this issue when installing the  'Impact Pack', newly. The issue with (b) is particularly challenging. If I only consider the Impact Pack, it would be much simpler to automate the response by updating the package to the latest version. However, users who have installed reactor/roop nodes or WAS nodes would face a serious problem of these nodes becoming unusable. 

Due to the rather complex situation, a separate troubleshooting section has been created, and users are being guided to that page for assistance. And moreover, in the event of an expected import error associated with this error situation when using the latest Impact Pack, measures have been taken to guide users through the troubleshooting URL.

**Comment by Gwara-Gwara** [comment]
> > ltdrdata Я думаю, что то, как вы решаете эту проблему, не очень хорошо.
> > Вы получили сообщение об одной и той же проблеме 3 раза в течение менее чем 24 часов, и вы просто копируете/вставляете одно и то же сообщение и немедленно закрываете проблему.
> > На мой взгляд, вам следует уделять больше внимания этому конкретному вопросу.
> 
> Я предоставляю это руководство, поскольку проверка уже завершена и решение существует. По вашему мнению, какой способ решения этой проблемы был бы подходящим?
> 
> Чтобы помочь вам понять, я объясню текущую ситуацию и мои меры реагирования.
> 
> Текущая проблема возникает из-за того, что на пользователей (а) которые используют устаревший менеджер, влияет последняя версия пакета Ultralytics, (б) которые используют определенную версию cv2, которая вызывает проблемы в последней версии Ultralytics. ' упаковка.
> 
> Ожидается, что пользователи, которые обычно используют существующие устаревшие расширения/пакеты, столкнутся с этой проблемой при новой установке «Impact Pack». Проблема с (b) особенно сложна. Если рассматривать только Impact Pack, было бы гораздо проще автоматизировать ответ, обновив пакет до последней версии. Однако пользователи, установившие узлы реактора/петли или узлы WAS, столкнутся с серьезной проблемой, когда эти узлы станут непригодными для использования.
> 
> Из-за довольно сложной ситуации был создан отдельный раздел по устранению неполадок, и пользователи направляются на эту страницу за помощью. Более того, в случае ожидаемой ошибки импорта, связанной с этой ошибкой при использовании последней версии пакета Impact, были приняты меры, помогающие пользователям пройти через URL-адрес для устранения неполадок.

At first I installed a new manager on top of the old one, but there was no result. Everything worked out after deleting the manager and reinstalling it. This point was not obvious to me. Thank you so much for helping me figure it out!

> > ltdrdata I think it's not very nice the way you're handling this problem.
> > You got the same issue reported 3 different time in less than 24 hours and you are just copy/pasting the same message and immediatly closing the issue.
> > In my opinion, you should care a bit more about this specific issue.
> 
> I am providing this guidance because the review has already concluded, and a solution is in place. In your opinion, what would be an appropriate way to address this?
> 
> To help you understand, I will explain the current situation and my response measures.
> 
> The current issue is occurring because users (a) who are using an outdated Manager are being affected by latest verision of 'Ultralytics' package, (b) who are using a certain version of 'cv2' that triggers issues in latest version of 'Ultralytics' package.
> 
> It is anticipated that users who typically use existing outdated extensions/packages are encountering this issue when installing the 'Impact Pack', newly. The issue with (b) is particularly challenging. If I only consider the Impact Pack, it would be much simpler to automate the response by updating the package to the latest version. However, users who have installed reactor/roop nodes or WAS nodes would face a serious problem of these nodes becoming unusable.
> 
> Due to the rather complex situation, a separate troubleshooting section has been created, and users are being guided to that page for assistance. And moreover, in the event of an expected import error associated with this error situation when using the latest Impact Pack, measures have been taken to guide users through the troubleshooting URL.

At first I installed a new manager on top of the old one, but there was no result. Everything worked out after deleting the manager and reinstalling it. This point was not obvious to me. Thank you so much for helping me figure it out!

**Comment by Gwara-Gwara** [comment]
> > ltdrdata I think it's not very nice the way you're handling this problem.
> > You got the same issue reported 3 different time in less than 24 hours and you are just copy/pasting the same message and immediatly closing the issue.
> > In my opinion, you should care a bit more about this specific issue.
> 
> I am providing this guidance because the review has already concluded, and a solution is in place. In your opinion, what would be an appropriate way to address this?
> 
> To help you understand, I will explain the current situation and my response measures.
> 
> The current issue is occurring because users (a) who are using an outdated Manager are being affected by latest verision of 'Ultralytics' package, (b) who are using a certain version of 'cv2' that triggers issues in latest version of 'Ultralytics' package.
> 
> It is anticipated that users who typically use existing outdated extensions/packages are encountering this issue when installing the 'Impact Pack', newly. The issue with (b) is particularly challenging. If I only consider the Impact Pack, it would be much simpler to automate the response by updating the package to the latest version. However, users who have installed reactor/roop nodes or WAS nodes would face a serious problem of these nodes becoming unusable.
> 
> Due to the rather complex situation, a separate troubleshooting section has been created, and users are being guided to that page for assistance. And moreover, in the event of an expected import error associated with this error situation when using the latest Impact Pack, measures have been taken to guide users through the troubleshooting URL.

At first I installed a new manager on top of the old one, but there was no result. Everything worked out after deleting the manager and reinstalling it. This point was not obvious to me. Thank you so much for helping me figure it out!

**Comment by SimoneTruglia** [comment]
> > ltdrdata I think it's not very nice the way you're handling this problem.
> > You got the same issue reported 3 different time in less than 24 hours and you are just copy/pasting the same message and immediatly closing the issue.
> > In my opinion, you should care a bit more about this specific issue.
> 
> I am providing this guidance because the review has already concluded, and a solution is in place. In your opinion, what would be an appropriate way to address this?
> 
> To help you understand, I will explain the current situation and my response measures.
> 
> The current issue is occurring because users (a) who are using an outdated Manager are being affected by latest verision of 'Ultralytics' package, (b) who are using a certain version of 'cv2' that triggers issues in latest version of 'Ultralytics' package.
> 
> It is anticipated that users who typically use existing outdated extensions/packages are encountering this issue when installing the 'Impact Pack', newly. The issue with (b) is particularly challenging. If I only consider the Impact Pack, it would be much simpler to automate the response by updating the package to the latest version. However, users who have installed reactor/roop nodes or WAS nodes would face a serious problem of these nodes becoming unusable.
> 
> Due to the rather complex situation, a separate troubleshooting section has been created, and users are being guided to that page for assistance. And moreover, in the event of an expected import error associated with this error situation when using the latest Impact Pack, measures have been taken to guide users through the troubleshooting URL.

This is a better answer, and it helped me finding and solving my issue. So by implementing this message in the default message that you copy-paste, it could already be very useful for users.

Thanks :)
