### ISSUE TITLE
Segment skip causing error in FaceDetailer (pipe)

### ISSUE THREAD

**Issue by tsen9731** [ltdrdata/ComfyUI-Impact-Pack#313]
Seems like pil2numpy fails to handle None input.

> 0: 640x512 1 face, 10.0ms
Speed: 0.0ms preprocess, 10.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 512)
Detailer: segment skip (enough big)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File [xxxxx]\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File [xxxxx]\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File [xxxxx]\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File [xxxxx]\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 998, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File [xxxxx]\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 400, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
  File [xxxxx]\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 235, in do_detail
    new_seg = SEG(pil2numpy(enhanced_pil), seg.cropped_mask, seg.confidence, seg.crop_region, seg.bbox, seg.label, None)
  File [xxxxx]\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 12, in pil2numpy
    return (np.array(image).astype(np.float32) / 255.0)[np.newaxis, :, :, :]
IndexError: invalid index to scalar variable.

**Comment by ltdrdata** [comment]
This is fixed on V4.33.1
