### ISSUE TITLE
Suggestions for why this bbox is skipping one eye?

### ISSUE THREAD

**Issue by alenknight** [ltdrdata/ComfyUI-Impact-Pack#314]
running face detailer using the eyes.pth Detector.  works great for slightly larger heads... but if the head is small, like this image... i have to go down to like bbox threshold of < 0.10... and even then it's painting in one of the eyes VERY small (even if i go 0.11... it totally skips it)

not a bug or error. console looks fine.  just curious if you have any suggestions how i can get it to apply the inpainting to both eyes in situations like this.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/0c9b4bf1-7861-4b79-a118-5f32808b8d9e)

**Comment by ltdrdata** [comment]
You can use dilation. If you want to apply dilation to only one side, you can separate based on size using SEGSFilter and then apply dilation to only one side.

**Comment by alenknight** [comment]
ooohhhhhh that's why even when it catchs both eyes.... one eye is less inpainted than the other... because at the end of the day it's STILL just 1 inpaint.  do i understand that right?  so unless both eyes are clearly equally visible in the image.... it's basically applying inpainting to just one eye (usually left most as that has index=0)
thanks!  now, to look up how to do segs filtering!  (i saw the nodes and your video on it)  thanks!
