### ISSUE TITLE
why "Detailer for Animate Diff" is not good for svd

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#316]
ComfyUI-Inspire-Pack - Tutorial #12: Detailer for Animate Diff 
https://www.youtube.com/watch?v=LDXFOwGvjwk&ab_channel=Dr.Lt.Data%27sComfyUIExtension

I found that this "Detailer for Animate Diff" is very good for Animate Diff, no flickering, and the header position is correct.

But the sequence frame I generated with svd, which  basic result is better than Animate Diff, 
But it doesn't match "Detailer for Animate Diff", it flickers, and the header is in the right position 
https://githubfast.com/kijai/ComfyUI-SVD 
why Detailer for Animate Diff is not good for svd

I'm trying to use controlnetApply(segs), to fix the face effect, but it seems to work only on the first frame, but other frame doesn't get controlnet effect.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/53c7f057-8aac-4ccc-beb4-9f530775c4e2)

I hope you can answer my question

**Comment by ltdrdata** [comment]
This seems to require experimentation. At least in situations with high denoise, it is definitely not good.

**Comment by xueqing0622** [comment]
Ok! Thx!

**Comment by ltdrdata** [comment]
Now `ControlNetApply (SEGS)` will  support video properly.
