### ISSUE TITLE
ComfyUI- Impact pack issue with GUI

### ISSUE THREAD

**Issue by Thamimtommy** [ltdrdata/ComfyUI-Impact-Pack#317]
I install the ComfyUI impact pack using ComfyUI-manager, It install proper in the file path ==> ComfyUI/custom_node but I can't find in comfyUI add nodes GUI. I restarted the comfyUI multiple times but still facing this issue. Something issue the latest commit please check it.

**Comment by ltdrdata** [comment]
Check your startup terminal log.
You can see import error.

**Comment by PKS-formido** [comment]
<img width="973" alt="Screenshot 2023-11-25 at 1 08 59 PM" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116268671/574e6abc-2224-4283-9029-0e5c7f8051b4">

Does it involve any change in the docker files @ltdrdata

**Comment by Thamimtommy** [comment]
> Check your startup terminal log. You can see import error.
yes here is the screenshot of that import error please check it out and How to solve that issue @ltdrdata. 
<img width="612" alt="Screenshot 2023-11-25 at 1 58 30 PM" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116333932/50b8c7cb-57a2-49ad-b63a-26e72d2e1cf1">

**Comment by Thamimtommy** [comment]
How to solve the issue @ltdrdata

**Comment by ltdrdata** [comment]
> How to solve the issue @ltdrdata

Show me the full log

> <img alt="Screenshot 2023-11-25 at 1 08 59 PM" width="973" src="https://private-user-images.githubusercontent.com/116268671/285572752-574e6abc-2224-4283-9029-0e5c7f8051b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDE5NjUsIm5iZiI6MTcwMDkwMTY2NSwicGF0aCI6Ii8xMTYyNjg2NzEvMjg1NTcyNzUyLTU3NGU2YWJjLTIyMjQtNDI4My05MDI5LTBlNWM3ZjgwNTFiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwODQxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWE3NjNhOTZlYTIzMTU3OTExMzhjMzQzYmQ0NDU0YjVkMzM1MWM2YWNlOTYzOTAwMzZjZjQ0OTg0MjVhOTY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1FLEJuaZg9SU7zhwp7pdcizzgXa68evdE2gHjRkrKjs">
> Does it involve any change in the docker files @ltdrdata

if you are using ubuntu. You can install linux package through:
`sudo apt-get install libgl1-mesa-glx`

If it's not Ubuntu, you need to install packages suitable for each environment.

**Comment by ltdrdata** [comment]
> > Check your startup terminal log. You can see import error.
> > yes here is the screenshot of that import error please check it out and How to solve that issue @ltdrdata.
> 
> <img alt="Screenshot 2023-11-25 at 1 58 30 PM" width="612" src="https://private-user-images.githubusercontent.com/116333932/285574885-50b8c7cb-57a2-49ad-b63a-26e72d2e1cf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MDE5NjUsIm5iZiI6MTcwMDkwMTY2NSwicGF0aCI6Ii8xMTYzMzM5MzIvMjg1NTc0ODg1LTUwYjhjN2NiLTU3YTItNDlhZC1iNjNhLTI2ZTcyZDJlMWNmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwODQxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWI1NWEwZjZiMmQzYjQ2NThmMmM0NTc4NWUzNzU3NGYyNjJiODFiM2FlNzM1NGViOGUzNGFhM2VmY2U4MGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B9y8SGrjk3RsGd3oY2mpn3kCPZCFZYiAiXs6LCfJcFg">

Show me the full log.

**Comment by Thamimtommy** [comment]
** ComfyUI start up time: 2023-11-25 08:41:30.345488

Prestartup times for custom nodes:
   0.0 seconds: /home/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 48677 MB, total RAM 515805 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V1.3)
### ComfyUI Revision: 1629 [41b07ff8] | Released on '2023-10-29'
[93mEfficiency Nodes Warning:[0m Failed to import python package 'simpleeval'; related nodes disabled.

[92mBmad-DirtyUndoRedo Loaded.[0m
### Loading: ComfyUI-Impact-Pack (V4.34)
### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['/opt/conda/bin/python', 'install.py'] in '/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
req_path: /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
[Impact Pack] EXECUTE: ['/opt/conda/bin/python', '-m', 'pip', 'install', '-r', 'requirements.txt'] in '/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
Collecting ultralytics!=8.0.177 (from -r requirements.txt (line 1))
  Obtaining dependency information for ultralytics!=8.0.177 from https://files.pythonhosted.org/packages/57/3e/2453e560412051157abf11e3833509ead2b748fc116a6dbd83f8ae976aec/ultralytics-8.0.217-py3-none-any.whl.metadata
  Using cached ultralytics-8.0.217-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: matplotlib>=3.3.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: numpy>=1.22.2 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.0)
Collecting opencv-python>=4.6.0 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Obtaining dependency information for opencv-python>=4.6.0 from https://files.pythonhosted.org/packages/b7/8a/b2f7e1a434d56bf1d7570fc5941ace0847404e1032d7f1f0b8fed896568d/opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: pillow>=7.1.2 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (10.0.1)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: requests>=2.23.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: torchvision>=0.9.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: tqdm>=4.64.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.65.0)
Requirement already satisfied: pandas>=1.1.4 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.2)
Collecting seaborn>=0.11.0 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Obtaining dependency information for seaborn>=0.11.0 from https://files.pythonhosted.org/packages/7b/e5/83fcd7e9db036c179e0352bfcd20f81d728197a16f883e7b90307a88e65e/seaborn-0.13.0-py3-none-any.whl.metadata
  Using cached seaborn-0.13.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (5.9.0)
Collecting py-cpuinfo (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Collecting thop>=0.1.1 (from ultralytics!=8.0.177->-r requirements.txt (line 1))
  Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.9.0)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.1)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.9.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.3.0)
Using cached ultralytics-8.0.217-py3-none-any.whl (645 kB)
Using cached opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.7 MB)
Using cached seaborn-0.13.0-py3-none-any.whl (294 kB)
Installing collected packages: py-cpuinfo, opencv-python, thop, seaborn, ultralytics
Successfully installed opencv-python-4.8.1.78 py-cpuinfo-9.0.0 seaborn-0.13.0 thop-0.1.1.post2209072238 ultralytics-8.0.217
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
req_path: /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
[Impact Pack] EXECUTE: ['/opt/conda/bin/python', '-m', 'pip', 'install', '-r', 'requirements.txt'] in '/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
Requirement already satisfied: ultralytics!=8.0.177 in /opt/conda/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (8.0.217)
Requirement already satisfied: matplotlib>=3.3.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: numpy>=1.22.2 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.0)
Requirement already satisfied: opencv-python>=4.6.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.8.1.78)
Requirement already satisfied: pillow>=7.1.2 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (10.0.1)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: requests>=2.23.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.3)
Requirement already satisfied: torch>=1.8.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.0)
Requirement already satisfied: torchvision>=0.9.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: tqdm>=4.64.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.65.0)
Requirement already satisfied: pandas>=1.1.4 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: seaborn>=0.11.0 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.13.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (5.9.0)
Requirement already satisfied: py-cpuinfo in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (9.0.0)
Requirement already satisfied: thop>=0.1.1 in /opt/conda/lib/python3.10/site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.1.1.post2209072238)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.9.0)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.1)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.9.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
req_path: /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
[Impact Pack] EXECUTE: ['/opt/conda/bin/python', '-m', 'pip', 'install', '-r', '/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt'] in 'None'
Collecting segment-anything (from -r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 1))
  Using cached segment_anything-1.0-py3-none-any.whl (36 kB)
Requirement already satisfied: scikit-image in /opt/conda/lib/python3.10/site-packages (from -r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (0.22.0)
Collecting piexif (from -r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 3))
  Using cached piexif-1.1.3-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: transformers in /opt/conda/lib/python3.10/site-packages (from -r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (4.34.1)
Requirement already satisfied: opencv-python-headless in /opt/conda/lib/python3.10/site-packages (from -r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 5)) (4.8.1.78)
Requirement already satisfied: numpy>=1.22 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (1.26.0)
Requirement already satisfied: scipy>=1.8 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (1.11.3)
Requirement already satisfied: networkx>=2.8 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (3.1)
Requirement already satisfied: pillow>=9.0.1 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (10.0.1)
Requirement already satisfied: imageio>=2.27 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (2.31.6)
Requirement already satisfied: tifffile>=2022.8.12 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (2023.9.26)
Requirement already satisfied: packaging>=21 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (23.1)
Requirement already satisfied: lazy_loader>=0.3 in /opt/conda/lib/python3.10/site-packages (from scikit-image->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 2)) (0.3)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (3.9.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (0.17.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (2023.10.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: tokenizers<0.15,>=0.14 in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (0.14.1)
Requirement already satisfied: safetensors>=0.3.1 in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (4.65.0)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.16.4->transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (2023.9.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.16.4->transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers->-r /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt (line 4)) (2023.7.22)
Installing collected packages: segment-anything, piexif
Successfully installed piexif-1.1.3 segment-anything-1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[Impact Pack] EXECUTE: ['/opt/conda/bin/python', '-m', 'pip', 'install', 'opencv-python'] in 'None'
Requirement already satisfied: opencv-python in /opt/conda/lib/python3.10/site-packages (4.8.1.78)
Requirement already satisfied: numpy>=1.21.2 in /opt/conda/lib/python3.10/site-packages (from opencv-python) (1.26.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
### ComfyUI-Impact-Pack: Check basic models
Traceback (most recent call last):
  File "/home/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 73, in <module>
    import impact.impact_server  # to load server api
  File "/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_server.py", line 10, in <module>
    import impact.core as core
  File "/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 6, in <module>
    from impact.utils import *
  File "/home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/utils.py", line 2, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Cannot import /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: libGL.so.1: cannot open shared object file: No such file or directory

Import times for custom nodes:
   0.0 seconds: /home/ComfyUI/custom_nodes/ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds: /home/ComfyUI/custom_nodes/ComfyUI_NestedNodeBuilder
   0.0 seconds: /home/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.2 seconds: /home/ComfyUI/custom_nodes/ComfyUI-Manager
  15.3 seconds (IMPORT FAILED): /home/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://0.0.0.0:6006
FETCH DATA from: /home/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json

**Comment by Thamimtommy** [comment]
here is the full log @ltdrdata

**Comment by Thamimtommy** [comment]
[comfyui_6006.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13463395/comfyui_6006.log)

**Comment by ltdrdata** [comment]
> [comfyui_6006.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13463395/comfyui_6006.log)

Yeah.. It is a same issue.
You need to install linux package.

`sudo apt-get install libgl1-mesa-glx`
