### ISSUE TITLE
ImageReceiver FileNotFoundError

### ISSUE THREAD

**Issue by Bocian-1** [ltdrdata/ComfyUI-Impact-Pack#32]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/cffbc110-9e86-4ccf-895c-c7d596c8ff9e)
The right image is displayed on the node so it receives it correctly, but it looks in the wrong directory when trying to output it

**Comment by ltdrdata** [comment]
This is patched.

**Comment by Bocian-1** [comment]
I'm now getting this error in console:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/58974c8f-750d-45ab-b222-22ed004eadf0)

**Comment by ltdrdata** [comment]
> I'm now getting this error in console: ![image](https://user-images.githubusercontent.com/70019596/249506628-58974c8f-750d-45ab-b222-22ed004eadf0.png)

oops.. try again.

**Comment by Bocian-1** [comment]
Works well now, thank you!
