### ISSUE TITLE
Failed to install Segs & Mask custom node.

### ISSUE THREAD

**Issue by heorhiiberezovskyi** [ltdrdata/ComfyUI-Impact-Pack#320]
Hi, thank you for your tremendous work!

It seems I've managed to install all custom nodes except for the Segs & Masks

Could you please suggest what could go wrong?

![1](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23558352/965099cd-402f-46cf-a2b0-af1133552b5c)
![2](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23558352/0d408197-9a08-4bc6-82f5-d46d475c9e89)
![3](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23558352/40a5eb95-02dd-4ed4-aa51-c5231bc141cd)

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager and try reinstall.

**Comment by ltdrdata** [comment]
Oh... This is sanitizer issue... I need to change my node name.
This is related to recent security patch of ComfyUI.

**Comment by ltdrdata** [comment]
Update Impact Pack to Latest Version & Change that node to 'ImpactSegsAndMask'.

**Comment by heorhiiberezovskyi** [comment]
After updating Impact Pack to the latest version it works! Thank you!
