### ISSUE TITLE
Any way to limit the latent size for facedetailer to a specific size?

### ISSUE THREAD

**Issue by cchance27** [ltdrdata/ComfyUI-Impact-Pack#321]
I'm using the coreml nodes for comfy, but one of the limitations is that it requires being processed by a single latent size from the model say 512x512, but it seems like no matter what config i use in facedetailer it doesn't stick to a predefined latent size?

**Comment by ltdrdata** [comment]
Recently, a `CoreMLDetailerHookProvider` has been added to enforce four sizes (512x512, 512x768, 768x512, 768x768) to support `Core ML Suite for ComfyUI`. What is the purpose of the 64x64 size?

**Comment by cchance27** [comment]
I was referring to the underlying latent, never mind was a miswording, I removed that.

Didn't see the cormel detailer hook, when you drag off from the detailer_hook connection on the face detailer it doesn't come up with an option, but searching for it and then connecting it worked.

Thanks
