### ISSUE TITLE
[FEATURE REQUEST] ImpactSEGSConcat ignoring empty SEGS

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#322]
There are situations where an input SEGS might arrive empty into an `ImpactSEGSConcat` node. For example when it's generated by a group that I decide to temporarily mute.

When that happens, the `ImpactSEGSConcat` node raises an error as it doesn't tolerate empty SEGS. 

To work around the issue, I can use an rgthree `Any Switch` node that automatically falls back to an `EmptySEGS` node when the group is muted:

<img width="1198" alt="Screenshot 2023-11-26 at 14 09 10" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/631f9970-99f4-4da8-8cd7-7aad56b564c0">

Then, the problem becomes that the empty SEGS is not the same size of the other input SEGS, and so the `ImpactSEGSConcat` node raises another error. 

I suppose I could solve this new issue by creating an empty image of the same size of the original image, turn it into a SEG and use that as fall back for the `Any Switch` node. But it starts to become a lot of nodes just to handle this particular scenario.

I was wondering if the `ImpactSEGSConcat` node could simply accept (and ignore) empty SEGS. Either transparently, or via a switch visible in the node UI. Unless I'm missing something, it seems the easiest and cleanest way to address this use case.  

Thank you for considering it.

**Comment by ltdrdata** [comment]
`SEGSConcat` concatenates only SEGS with the same dimensions as the SEGS in the first input. SEGS with different dimensions may trigger an error, but the node ignores them. If `EmptySEGS` is passed as `segs3`, it should be ignored along with an error message. Is there any issue with this behavior?

**Comment by alessandroperilli** [comment]
The problem with the behaviour is that the error message is a halting message. Here's another example (same identical implementation as the first screenshot in this thread):

The group on the left in the following screenshot processes an image and generates a SEG that will go into a `SEGSConcat` node (see further down). I occasionally want to mute that particular group to not generate that SEG. 

The Any Switch node falls back to the `EmptySEGS` node and passes it to the `SEGSConcat` node.

<img width="1427" alt="Screenshot 2023-11-28 at 11 03 31" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/5dee8037-6037-4bc6-9cf5-c5fa0f5b397a">

The receiving `SEGSConcat` node is very upset about it:

<img width="696" alt="Screenshot 2023-11-28 at 11 03 17" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/fbd45360-1cd8-41fc-8d68-35aed71573f8">

and generates the halting error:

> File "xyz/ComfyUI/execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/segs_nodes.py", line 280, in doit
>     segs = core.segs_scale_match(segs, fallback_image_opt.shape)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xyz/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 665, in segs_scale_match
>     rh = th / h
>          ~~~^~~
> ZeroDivisionError: division by zero

**Comment by ltdrdata** [comment]
This is fixed on V4.36.2

**Comment by alessandroperilli** [comment]
It works fine now, thank you.
