### ISSUE TITLE
Batch Masks output of SAM Detector (segmented) cannot be attached to masks input of Bitwise (SEGS & MASKS) ForEach

### ISSUE THREAD

**Issue by vivin** [ltdrdata/ComfyUI-Impact-Pack#324]
When I loaded up my flow after updating, it said that the existing bitwise segs & masks ForEach was invalid. I found the new node, but I cannot attach the batch_masks output from SAM Detector (segmented) into the ForEach Bitwise SEGS & MASKS node.

**Comment by ltdrdata** [comment]
In a recent update to ComfyUI, some node names have been restricted due to security policies. The internal name of the SEGS & MASK node has been changed to ImpactSegsAndMask.

Please replace the node accordingly.

**Comment by skillsdead** [comment]
The same thing happens to me but I don't know how to do it, can you tell me how to do it?

**Comment by ltdrdata** [comment]
> The same thing happens to me but I don't know how to do it, can you tell me how to do it?

Update Impact Pack to latest version.
And remove old node and re-add new node.

**Comment by latrisgris** [comment]
Hello ltdrdata, can you let me know where is the node "SEGS & MASK" in my confyui folder to rename it please?

**Comment by ltdrdata** [comment]
> Hello ltdrdata, can you let me know where is the node "SEGS & MASK" in my confyui folder to rename it please?

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/86aa6b37-51aa-46da-8870-55334a4030e5)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/7352c805-6713-4469-b644-a6f38df9b959)

**Comment by latrisgris** [comment]
thank you!
