### ISSUE TITLE
Impact Wildcard Processor "Convert seed to input" doesn't work right

### ISSUE THREAD

**Issue by Kextrii** [ltdrdata/ComfyUI-Impact-Pack#325]
When I am using Impact Wildcard Processor, and I convert "seed" to input rather than a widget, it will ignore the input that gets routed in, if the input source isn't a primitive. It will instead use the underlying "widget" value that it remembers from before converting to input.

<img width="949" alt="Screenshot 2023-11-27 182441" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/28766772/26110de2-6ec5-4301-adf8-33404911f824">

In the attached screenshot, the three copies of ImpactWildcardProcessor on the left all started with "349687348" in the seed widget. After converting to an input, they ignored the external inputs of different seed values. The one on the right with the primitive attached to it actually changed its underlying seed widget value after the seed was changed in the primitive attached to it. (It began with 349687348, but after attaching the primitive, changing the seed, and converting the seed back to a widget, it had changed to 349687350.)

It would be useful to have this working, so that I can have multiple processors running the same prompt on different seeds in a predictable way (e.g. using Math Expressions to increment a single seed by different amounts).

**Comment by ltdrdata** [comment]
This is a limitation.

The `ImpactWildcardProcessor` node is designed to store prompts populated in the stored image. Therefore, actions dependent on back-end data that should be determined during execution are not allowed.

You can attach `Primitive Node` but, any other nodes.
