### ISSUE TITLE
refined mask without ksampler?

### ISSUE THREAD

**Issue by MrsHorrid** [ltdrdata/ComfyUI-Impact-Pack#326]
hello i was wondering if theres a way to get yolo8 person detection to work without a detailer to extract automatically a refined mask for each person ? 
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/88950077/48e109dc-61ba-4123-984a-c69e231f0fd6)
just like in the image above but without using a sd checkpoint just so i can get each person to have their own image automatically

**Comment by ltdrdata** [comment]
Take a look at this:
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/detectors.md
