### ISSUE TITLE
Wildcard spec input in DetailerForEachDebugPipe node gets bigger and bigger

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#327]
This is a bug that I had for a very long time. Possibly, it's unrelated to the node itself, but I'll report it anyway.

The size of the wildcard specification text input in the `DetailerForEachDebugPipe` node should remain constant over time. Example:

<img width="748" alt="Screenshot 2023-11-28 at 12 52 47" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/95d6c0d6-4ea4-40eb-84dd-1981c76a622e">

Instead, every time I restart ComfyUI, for example after a custom node suite update or after a git pull, that input box grows some amount:

<img width="808" alt="Screenshot 2023-11-28 at 12 52 37" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/c6b6e321-7766-4ad9-91b0-79913ac2e298">

After a few restarts, it can become truly huge and must be manually resized.

I'm not completely sure about the root cause of this, but it happens when I restart ComfyUI. Nothing else changes in the workflow in terms of inputs or parameters that go into the `DetailerForEachDebugPipe` node.

**Comment by ltdrdata** [comment]
This is fixed on ComfyUI.
Update your ComfyUI to latest version.

**Comment by alessandroperilli** [comment]
That is great, thank you!
