### ISSUE TITLE
Sampler tests with TwoAdvancedSamplersForMask

### ISSUE THREAD

**Issue by Bocian-1** [ltdrdata/ComfyUI-Impact-Pack#33]
I noticed that some samplers give very bad results with TwoAdvancedSamplersForMask so I did some tests.
![TwoAdvSamplers_denoising1](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/2719129b-200c-4811-b622-44acb1f7e98c)
![TwoAdvSamplers_denoising045](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/223d3db2-e90f-40a6-9657-f0ac9cf4b29b)
The first set is with denoising set to 1, second is using it with upscaling at 0.45 denoising. Different lora models are applied to each KSamplerAdvancedProvider. There is also the controlnet pose I was using to hold the character together, but it doesn't matter much without a bigger frame.

Several samplers produce very bad results.
 - ancestral samplers heavily distort the image
 - sde samplers only add noise
 - uni_pc samplers produce something similar in look to what you get by decoding an EmptyLatentImage, although the latter lacks lighter spots. Watching the preview, at first, the image seems to follow the prompt but quickly starts turning into the above.
 - DDIM is the most interesting, it produces distortions not unlike the ancestral samplers and heavy blur on the overlapping area. Additionally, the samplers seem to bleed into each other's areas:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/a89a07bc-f13a-4c14-b441-73443040d735

I also did a round with denoising at 1 using the normal TwoSamplersForMask:
![TwoSamplers_denoising1](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/fe76c9df-79e9-4c02-8619-31e8058c780b)
 - Some results above seem bad, but after a few reruns, all samplers are capable of returning good results given the right settings
 - DDIM visibly bleeds samplers like the Advanced node, which can be seen with previews, but later it corrects itself:
https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/70019596/d7129738-9b15-43c0-90bf-87566614fccd

On a slightly different note, with the addition of the TwoAdvancedSamplersForMask, it only seems fitting to have a TwoAdvancedSamplersFor Mask Upscaler Provider along with a pipe variant like with the simple version of the node. Unless there are issues with this?

**Comment by ltdrdata** [comment]
It seems that further research is still needed regarding this issue.

**Comment by ltdrdata** [comment]
This is enhanced on 7f21da704424df2c7cb22865568903ece348134c

SDE and uni-pc, due to their characteristics, are currently deemed impractical within the current structure. Therefore, we have considered incorporating additional sampling using different samplers.

I now plan to focus primarily on the more scalable and useful RegionalSamplers instead of TwoSamplersForMask.
The RegionalSampler/RegionalSamplerAdvanced are nodes that further advances TwoAdvancedSamplersForMask.
