### ISSUE TITLE
I can't find node ## make-basic-pipe

### ISSUE THREAD

**Issue by zhairy** [ltdrdata/ComfyUI-Impact-Pack#331]
Why can't I find this node?  ## make-basic-pipe
I made sure I had the impact pack installed
Other nodes are used normally.
Do I need to make any other settings?
please help me! !
![微信截图_20231130013001](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/112151101/5b3fd0ed-de4b-4f00-83a4-fc8a9ff8052a)

**Comment by ltdrdata** [comment]
It's not a node of Impact Pack.

https://github.com/ltdrdata/ComfyUI-Workflow-Component

**Comment by zhairy** [comment]
Thank you
