### ISSUE TITLE
ImpactWildcardProcessor - Bug

### ISSUE THREAD

**Issue by Nico53425342** [ltdrdata/ComfyUI-Impact-Pack#333]
ImpactWildcardProcessor, node need to be executed 2 time before it update.
that all...

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by Nico53425342** [comment]
![Capture d’écran 2023-11-30 152939](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/151887339/a7263515-4259-4b3c-9e5a-8b19edd11ece)

The Raw [ P ] is the output of the text prompt, Bypass is a Show Text node, then it go in the processor. But as you can see the Show Text work but the Processor won't update itself if i dont execute the workflow again.

I find another probleme with the Processor, sometime the widjet Mode change from Populate to Fixed on it's one, i don't know what is the cause of that...

**Comment by Hamsterun** [comment]
Pu, thought it's just me. Wildcard Processor doesn't Populate anymore. Wondered why the Wildcards don't change.

**Comment by ltdrdata** [comment]
> Pu, thought it's just me. Wildcard Processor doesn't Populate anymore. Wondered why the Wildcards don't change.

I've improved the functionality of the wildcard. Update to the latest version and give it another try.

**Comment by Hamsterun** [comment]
I did. At first, it still didn't work, Then i thought, i might have used too many wildcards.
Reduced the wildcards and it works again. Just me? Is there a limit on wildcards?

**Comment by ltdrdata** [comment]
> I did. At first, it still didn't work, Then i thought, i might have used too many wildcards. Reduced the wildcards and it works again. Just me? Is there a limit on wildcards?

Send me the workflow and wildcard dir.

**Comment by lucklobster** [comment]
Is there any update on this? I'm having the same issue where the Wildcard processor does not populate to the lower section.
![ImpactTextEncode node](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/141617432/34dc8869-a73e-4239-9f3b-7a79a7598482)

**Comment by ltdrdata** [comment]
> Is there any update on this? I'm having the same issue where the Wildcard processor does not populate to the lower section.
> ![ImpactTextEncode node](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/141617432/34dc8869-a73e-4239-9f3b-7a79a7598482)
> 

What is the path to `color.txt` file?

**Comment by ltdrdata** [comment]
> Is there any update on this? I'm having the same issue where the Wildcard processor does not populate to the lower section.
> ![ImpactTextEncode node](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/141617432/34dc8869-a73e-4239-9f3b-7a79a7598482)
> 

What node is connected to seed input?

**Comment by lucklobster** [comment]
The workflow was previously working relatively ok until I updated comfyUI and all custom nodes the other day.
It would sometimes not update the lower field display with new populated text, but the node would still produce the populated text on its outputs to other nodes.

The seed input is connected to a seed producing node just so I can keep a consistent seed throughout the graph.
The path for wildcards shouldn't be an issue. Even if the path to color.txt wasn't working, it should still show up in the populated field as "__color__" if nothing else. Instead I'm getting nothing at all.

**Comment by ltdrdata** [comment]
> The workflow was previously working relatively ok until I updated comfyUI and all custom nodes the other day. It would sometimes not update the lower field display with new populated text, but the node would still produce the populated text on its outputs to other nodes.
> 
> The seed input is connected to a seed producing node just so I can keep a consistent seed throughout the graph. The path for wildcards shouldn't be an issue. Even if the path to color.txt wasn't working, it should still show up in the populated field as "**color**" if nothing else. Instead I'm getting nothing at all.

You cannot connect any node to seed input other than Primitive node or ImpactInt.
In the past, it used to silently overlook issues that were not functioning correctly, but now it explicitly blocks them and displays errors in the terminal.
