### ISSUE TITLE
Detailing where masks vary greatly in position fails - AnimateDiff detailer

### ISSUE THREAD

**Issue by brandostrong** [ltdrdata/ComfyUI-Impact-Pack#334]
Hello, I'm trying to detail a face using animatediff and while it works quite well when the face does not move very much, it fails to improve quality where the face may move over a large distance through the frames. In the preview you can see instead of being zoomed into the face(with crop factor 1), it more or less details over the entire image(leading to no quality increase). Am I missing a setting? I've tried everything.

**Comment by ltdrdata** [comment]
It seems that I won't be able to diagnose your workflow and outputs without seeing them.
