### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics'

### ISSUE THREAD

**Issue by NOeSIS-yu** [ltdrdata/ComfyUI-Impact-Pack#335]
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 414, in <module>
    import impact.subpack_nodes
  File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in <module>
    raise e
  File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in <module>
    from ultralytics import YOLO
ModuleNotFoundError: No module named 'ultralytics'

**Comment by poisenbery** [comment]
Would a 'pip install ultralysics' in venv fix this? 
I usually just manually install any missing modules when I encounter these issues.

**Comment by ltdrdata** [comment]
> Would a 'pip install ultralysics' in venv fix this? I usually just manually install any missing modules when I encounter these issues.



> ### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack
> The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete. Recommended to delete the path and restart ComfyUI. If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.
> 
> Traceback (most recent call last): File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack__init__.py", line 414, in import impact.subpack_nodes File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in import impact.subcore as subcore File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in raise e File "E:\comfyui\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in from ultralytics import YOLO ModuleNotFoundError: No module named 'ultralytics'

First, perform "Update All" in the Manager and then try restarting. If the issue persists, please send the full log.

**Comment by geoff-m** [comment]
> First, perform "Update All" in the Manager and then try restarting.

For me, installing ComfyUI manager and clicking Update All was not enough, as it said all plugins are already up to date and did nothing. But clicking the Try Update button specifically for ComfyUI-Impact-Pack did do something, and then it finally loaded successfully after a restart.

These steps (installing ComfyUI-Manager and using its update functions) need to be added to this project's installation instructions, as they doesn't work as is. (btw, I didn't encounter this problem when using the Windows standalone version of ComfyUI.)
