### ISSUE TITLE
FaceDetailer denoise parameter

### ISSUE THREAD

**Issue by green-anger** [ltdrdata/ComfyUI-Impact-Pack#338]
Does it have any special meaning in the context of FaceDetailer and doesn't work as the "standard" denoise parameter for i2i?

Whatever I set there, it always runs all the steps. For example, first it generates an image for 32 steps in about 20 seconds and then runs the same 32 steps for about the same time in FaceDetailer. When I set denoise to 0.4 I expect it to run only 12-13 steps (depending on how it rounds numbers).

Is it possible to reduce number of steps with denoise? Are there extra condition to make it work as expected?

**Comment by ltdrdata** [comment]
FaceDetailer first crops and enlarges the area around the detected region, then applies KSampler, and finally resizes it back to the original size before pasting it onto the original image. Lowering the denoise parameter does not reduce the number of steps; instead, it reduces the amount of denoising applied.

If you want to reduce the number of steps, simply decrease the number of steps.

**Comment by green-anger** [comment]
Reducing number of steps may reduce quality of the final image. What I really want is somewhat described in [KSampler Advanced](https://blenderneko.github.io/ComfyUI-docs/Core%20Nodes/Sampling/KSampler%20Advanced/) in [ComfyUI Community Manual](https://blenderneko.github.io/ComfyUI-docs/):

```python
# Given that end_at_step >= steps a KSampler Advanced node will denoise a latent in the
# exact same way a KSampler node would with a denoise setting of:

denoise = (steps - start_at_step) / steps
```

This is how it usually works for i2i or inpainting (which is i2i with a mask). And I'd assume FaceDetailer is kind of masked inpainting. Is it possible to achieve the above, maybe in conjunction with other nodes?

Could you also explain what you mean by "it reduces the amount of denoising applied" from technical perspective? You said that it does not reduce the number of steps, so obviously it's not the above formula, does it have another definition?

**Comment by ltdrdata** [comment]
> Reducing number of steps may reduce quality of the final image. What I really want is somewhat described in [KSampler Advanced](https://blenderneko.github.io/ComfyUI-docs/Core%20Nodes/Sampling/KSampler%20Advanced/) in [ComfyUI Community Manual](https://blenderneko.github.io/ComfyUI-docs/):
> 
> ```python
> # Given that end_at_step >= steps a KSampler Advanced node will denoise a latent in the
> # exact same way a KSampler node would with a denoise setting of:
> 
> denoise = (steps - start_at_step) / steps
> ```
> 
> This is how it usually works for i2i or inpainting (which is i2i with a mask). And I'd assume FaceDetailer is kind of masked inpainting. Is it possible to achieve the above, maybe in conjunction with other nodes?
> 
> Could you also explain what you mean by "it reduces the amount of denoising applied" from technical perspective? You said that it does not reduce the number of steps, so obviously it's not the above formula, does it have another definition?

What you shouldn't be confused about is that in KSampler, specifying `20 steps` and `denoise 0.5` doesn't mean sampling for only 10 steps. Instead, it sets the **total steps to 40**, and by setting `start_at_step` to 20, it means sampling for only 20 steps.

In a different explanation, the sigma is an array representing the amount of denoising at each step. When you specify `steps 20, denoise 0.5`, it means that a sigma array is created based on the scheduler, aligned with a total of 40 steps. From this array, only the sigma values for the latter 20 steps are taken, and the sampling process is then performed.

Same way, if the denoise value decreases, the total steps will increase to align with the required number of steps to be performed.

That's what denoise means in KSampler.

**Comment by green-anger** [comment]
OK, I checked [KSampler](https://blenderneko.github.io/ComfyUI-docs/Core%20Nodes/Sampling/KSampler/) descriptions again, it says:
> First the latent is noised up according to the given seed and denoise strength, erasing some of the latent image.

Which is basically what you said:
> Lowering the denoise parameter does not reduce the number of steps; instead, it reduces the amount of denoising applied.

I must have misunderstood the concept, now it's clear, thanks for the explanation.

So, if I want to replace some of the steps with FaceDetailer, I set that exact amount in "steps" field and must calculate denoise value manually? For example, I generated an image in 32 steps and would like to replace last 8 steps of it, the denoise would be 0.25 making KSampler erase 0.25 * 32 = 8 last steps and resample it, is it correct?

Wouldn't it be useful to have a boolean option in FaceDetailer to make it auto calculate the denoise value in the above "replace" scenario? I'm not sure if it's easy or worth it and how useful it can be, but intuitively this is how I see it: we replace some of the image with a better version. And when number of the replacement steps is low the quality will likely suffer, and making too many steps won't bring great improvement but will waste resources.

In any case, thank you for all your work, I've been using FaceDetailer node since my first days with Comfy!

**Comment by ltdrdata** [comment]
You don't need to overthink it. Just consider how much denoise you want to apply and over how many steps it should be applied.

**Comment by green-anger** [comment]
Does it mean you cannot confirm the above calculation or don't know how it's calculated?

**Comment by ltdrdata** [comment]
> Does it mean you cannot confirm the above calculation or don't know how it's calculated?

The implementation of this feature is not particularly useful. On the contrary, there is a high possibility that it may cause confusion.

**Comment by green-anger** [comment]
> The implementation of this feature is not particularly useful. On the contrary, there is a high possibility that it may cause confusion.

I agree, that's why I mentioned it may not worth it. If you think it'll be confusing for most users, then ignore it, better spend energy on more useful features.

It's just your assumption was a bit off:
> You don't need to overthink it.

My end goal is to understand the underlying processes and be able to generate images in console without any UI. I'd really appreciate if you could say if my line of though with the "replace" scenario is correct or there's still some misunderstanding.

**Comment by ltdrdata** [comment]
> > The implementation of this feature is not particularly useful. On the contrary, there is a high possibility that it may cause confusion.
> 
> I agree, that's why I mentioned it may not worth it. If you think it'll be confusing for most users, then ignore it, better spend energy on more useful features.
> 
> It's just your assumption was a bit off:
> 
> > You don't need to overthink it.
> 
> My end goal is to understand the underlying processes and be able to generate images in console without any UI. I'd really appreciate if you could say if my line of though with the "replace" scenario is correct or there's still some misunderstanding.

You can experiment with denoise and steps even without FaceDetailer by using KSamplerAdvanced. Please give it a try. With KSamplerAdvanced, you can apply the denoise schedule in a more conventional way, which might be impossible otherwise.

Internally, Detailer is a simple process that involves cropping a specific portion of the image, applying KSampler, and then resizing before pasting it back onto the original image. There is no special magic involved.

Recently, there was a discussion in the issues related to inpaint model, specifically in A1111, mentioning that reducing denoise amount in turn reduces the number of steps. I'm not sure if this behavior is optional or always applies.

**Comment by green-anger** [comment]
That's what I initially used - KSamplerAdvanced - for generation and inpainting, hence the confusion with simple KSampler.

I tried reduced number of steps in FaceDetailer with denoise 0.4 - 0.5 and it still gave good results, so at least now I can generate faster.

> Recently, there was a discussion in the issues related to inpaint model, specifically in A1111, mentioning that reducing denoise amount in turn reduces the number of steps

Looks like the same as with KSamplerAdvanced, linear dependency between denoise and number of sampling steps.

Thanks again for all the info, it was very useful!
