### ISSUE TITLE
Picker (Segs) reference image not loading correctly for previews

### ISSUE THREAD

**Issue by poisenbery** [ltdrdata/ComfyUI-Impact-Pack#340]
Expected Behaviour: 
1.) Make Image and do segs
2.) Click "Pick" on Picker (Segs) Node
3.) Look at previews of bbox and select the things
4.) make NEW image and do segs
5.) click "pick" on picker (segs) node
6.) New BBOX detections show up

Current Behaviour:
1.) Make Image and do segs
2.) Click "Pick" on Picker (Segs) Node
3.) Look at previews of bbox and select the things
4.) make NEW image and do segs
5.) click "pick" on picker (segs) node
6.) The same BBOX detections from [3] are displaying

**Comment by ltdrdata** [comment]
What is your workflow?
