### ISSUE TITLE
[Request] NudeNet V3 Support + Labels

### ISSUE THREAD

**Issue by poisenbery** [ltdrdata/ComfyUI-Impact-Pack#341]
I've been trying to do this myself ever since the V3 got released, but it seems that I do not have the python experience necessary to actually do it.

NudeNet has a V3 with Labels: https://github.com/notAI-tech/NudeNet

I think it would be nice if we could use this new version.
The detection is much better and the labels are very useful.

I would be more than happy to do it myself if someone can just tell me how because I am not smart enough to figure out on my own.

**Comment by ltdrdata** [comment]
Alright, I'll check it out when I get home later.

**Comment by ltdrdata** [comment]
After checking, I found that when loading and using the existing ONNX model in the repository, the labels do not match at all, and there is a difference in detection capabilities compared to the nudenet installed via pip.

While creating a node based on the nudet pip package seems to be a straightforward implementation, I am considering whether to make it a separate extension.

**Comment by poisenbery** [comment]
> separate extension

That might be within my capabilities. The main issue I was having was getting it integrated with the rest of the Impact Pack.

Is there anything I need to know about the return types or the segs output when doing this?

**Comment by ltdrdata** [comment]
SEGS is structured as (image dimension, SEG list). For example, if the original image size is 800x600,

`((800, 600), SEG list)`



is what it would look like.

And the type of SEG is as follows.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/cbbbb41be577d92ad2e38536b74ac88650c40b31/modules/impact/core.py#L19

And you can create SEG as follows:

```python
item = SEG(None, cropped_mask, scores, crop_region, item_bbox, label_string, None)
```

You can refer to the ONNX Detector for the method of creating SEG.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/cbbbb41be577d92ad2e38536b74ac88650c40b31/modules/impact/core.py#L948

Since `make_crop_region` is located here, feel free to copy and use it as needed.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/cbbbb41be577d92ad2e38536b74ac88650c40b31/modules/impact/utils.py#L202

And it's preferable to create it in the form of `NudenetDetectorProvider` rather than a node that directly returns SEGS when you intend to use it alongside other nodes.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/cbbbb41be577d92ad2e38536b74ac88650c40b31/modules/impact/impact_pack.py#L43

**Comment by poisenbery** [comment]
@ltdrdata
Status Update: I can't even figure out how to save image. It turns out, my Blender API experience does not translate into comfyUI programming skills.

I will not be working on this any longer. I apologize.

**Comment by poisenbery** [comment]
I changed my mind. I'm going to see if modifying the nudenet's code to use PIL for tensor instead of CV2 for filepath will make this easier.

**Comment by poisenbery** [comment]
@ltdrdata Sorry to bug you, but I was going over the onnx module and there is a line with "Caffe mode image preprocessing" https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/e089110464e34d6cc708b462a16f3263a2f10e52/modules/impact/onnx.py#L15C34-L15C34

What does this do exactly? I was reading the [Caffe Image Preprocessing](https://caffe2.ai/docs/tutorial-image-pre-processing.html) page but was unable to find the numbers you used.

**Comment by ltdrdata** [comment]
It is came from original code. Anyway you don't need concern about that.
When you use nudenet python package.

**Comment by poisenbery** [comment]
> When you use nudenet python package.

I don't think the python package is the best route for this, because it expects a file path. My plan was to convert tensor to PIL and modify the Nudenet.py so it uses PIL instead of CV2
If I used the python package, I would need to save the images to temp every time it needs to run, which isn't exactly efficient.

**Comment by poisenbery** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/78466408/0a20c46d-100f-43fd-83be-36c99d22dc36)
Sorry for taking so long on this.
But converting to PIL and then to numpy array seems to "work."
I have managed to get it to run in ComfyUI (Thanks for the Logger nodes btw. They helped a lot).

I'm going to start working on the rest of the code for the BBOX detector provider.

**Comment by poisenbery** [comment]
I got a detector provider to "work" but SEGS breaks whenever dialation is not 0.
I borrowed code from segs_nodes so it will take me some extra time to troubleshoot this.

**Comment by poisenbery** [comment]
https://github.com/poisenbery/NudeNet-Detector-Provider

"It just works"
Will throw errors if:
Dilation not set to 0
No detections in segs

I'm not sure if someone else wants to take a look at my frankenstein code and fix my beginner errors

**Comment by ltdrdata** [comment]
> https://github.com/poisenbery/NudeNet-Detector-Provider
> 
> "It just works" Will throw errors if: Dilation not set to 0 No detections in segs
> 
> I'm not sure if someone else wants to take a look at my frankenstein code and fix my beginner errors

Please don't create it in subdirectory form. There should be `__init__.py` at the root of the repository so that it can be directly installed using `git clone`.

And maybe `seggs` is typo?

**Comment by poisenbery** [comment]
> Please don't create it in subdirectory form. There should be `__init__.py` at the root of the repository so that it can be directly installed using `git clone`.
> 
> And maybe `seggs` is typo?

Sorry. This is my first time doing something like this.

**Comment by poisenbery** [comment]
I had another idea for a new node and was hoping for feedback/suggestions:

Open Pose uses very specific color codes for the body parts and joints. I would like to create a node that is similar to your [MediaPipeFaceMesh](https://github.com/ltdrdata/ComfyUI-Inspire-Pack/blob/d6af2f10eba0b849c1adaacf3d2a2c8ab7da97ea/inspire/segs_support.py#L429) in Inspire Pack, so that users can define specific body parts, and return a segs for them.


Would it be rude of me to ask if you can review [my homework](https://github.com/poisenbery/NudeNet-Detector-Provider) so I can make corrections, and work on new detectors/nodes?

**Comment by ltdrdata** [comment]
I'll take a look.
