### ISSUE TITLE
Question about using LoRAs

### ISSUE THREAD

**Issue by charliebrown777** [ltdrdata/ComfyUI-Impact-Pack#342]
I've been switching from automatic1111 to ComfyUI in recent days. I found your suite very useful, but I have some problems with using LoRAs. In automatic1111, I usually put LoRAs in wildcard lines so that it will automatically trigger in batch generations. How can I do it in ComfyUI since the LoRA Loader is always needed to trigger a LoRA? I found this setting very convoluted because, in Automatic1111, I can either use text prompts or additional networks(work similar to LoRA loaders in ComfyUI) to trigger LoRAs. Any solution to my needs? Thanks.

**Comment by ltdrdata** [comment]
You can use `ImpactWildcardEncode`.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md

**Comment by charliebrown777** [comment]
> You can use `ImpactWildcardEncode`. https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md

Perfect, thank you.

**Comment by charliebrown777** [comment]
Now I know how to activate LoRAs using the text prompts. A further question here: How to activate the combination mode of the wildcards: i.e. generate all the combinations of two wildcards using each line one by one?

**Comment by ltdrdata** [comment]
In that case you need this.
https://github.com/adieyal/comfyui-dynamicprompts

Connect that output to the populated_text of ImpactWildcardEncode.

**Comment by charliebrown777** [comment]
> In that case you need this. https://github.com/adieyal/comfyui-dynamicprompts
> 
> Connect that output to the populated_text of ImpactWildcardEncode.

Thank you!

**Comment by charliebrown777** [comment]
> In that case you need this. https://github.com/adieyal/comfyui-dynamicprompts
> 
> Connect that output to the populated_text of ImpactWildcardEncode.

![微信图片_20231207021752](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/36913431/5d9a6186-f9a0-43e0-bc03-de88c6769fd0)
OK, I have tried the combinational prompt generator. On the contrary, you should input the text in the combinational prompt generator and use it as input of the wildcard encoder, because the output of populated text of ImpactWildcardEncode has already been randomized and no longer contains wildcard inputs. This is somewhat convoluted because your encoder is very convenient in inputting wildcards/LoRAs from the files, while you'll have to copy/paste the text prompt back to the generator to do the combination, and the wildcard function in the wildcard encoder becomes redundant because the input text no longer contains wildcards as well. If your ImpactWildcardEncode has a combinational function switch then it will be perfect and I can just discard the combinational prompt generator directly. For the generator, if it should become perfect then it will need the text Lora function, add wildcards from files, and become an encoder, which is a longer way to go. Just my opinion here. The connection method I have above seems the best solution I can have for now.

**Comment by ltdrdata** [comment]
> > In that case you need this. https://github.com/adieyal/comfyui-dynamicprompts
> > Connect that output to the populated_text of ImpactWildcardEncode.
> 
> ![微信图片_20231207021752](https://private-user-images.githubusercontent.com/36913431/288667756-5d9a6186-f9a0-43e0-bc03-de88c6769fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzY4NjQsIm5iZiI6MTcwMTkzNjU2NCwicGF0aCI6Ii8zNjkxMzQzMS8yODg2Njc3NTYtNWQ5YTYxODYtZjlhMC00M2UwLWJjMDMtZGU4OGM2NzY5ZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA4MDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MjVhOWQ4MzE0MjRjYjgwODgyODY0YjliNzk3ODBjNjBlMTg1MThiNDVkNWNjMzU5YjYzMzI2MDA5NDM2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aS2w5BeDr-dSOaSfDr7rvxc4CnJCsHwo63Ld6De4Q6c) OK, I have tried the combinational prompt generator. On the contrary, you should input the text in the combinational prompt generator and use it as input of the wildcard encoder, because the output of populated text of ImpactWildcardEncode has already been randomized and no longer contains wildcard inputs. This is somewhat convoluted because your encoder is very convenient in inputting wildcards/LoRAs from the files, while you'll have to copy/paste the text prompt back to the generator to do the combination, and the wildcard function in the wildcard encoder becomes redundant because the input text no longer contains wildcards as well. If your ImpactWildcardEncode has a combinational function switch then it will be perfect and I can just discard the combinational prompt generator directly. For the generator, if it should become perfect then it will need the text Lora function, add wildcards from files, and become an encoder, which is a longer way to go. Just my opinion here. The connection method I have above seems the best solution I can have for now.

No... don't connect to `wildcard` input. connect to `populated` input

**Comment by charliebrown777** [comment]
> > > In that case you need this. https://github.com/adieyal/comfyui-dynamicprompts
> > > Connect that output to the populated_text of ImpactWildcardEncode.
> > 
> > 
> > ![微信图片_20231207021752](https://private-user-images.githubusercontent.com/36913431/288667756-5d9a6186-f9a0-43e0-bc03-de88c6769fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MzY4NjQsIm5iZiI6MTcwMTkzNjU2NCwicGF0aCI6Ii8zNjkxMzQzMS8yODg2Njc3NTYtNWQ5YTYxODYtZjlhMC00M2UwLWJjMDMtZGU4OGM2NzY5ZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA4MDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MjVhOWQ4MzE0MjRjYjgwODgyODY0YjliNzk3ODBjNjBlMTg1MThiNDVkNWNjMzU5YjYzMzI2MDA5NDM2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aS2w5BeDr-dSOaSfDr7rvxc4CnJCsHwo63Ld6De4Q6c) OK, I have tried the combinational prompt generator. On the contrary, you should input the text in the combinational prompt generator and use it as input of the wildcard encoder, because the output of populated text of ImpactWildcardEncode has already been randomized and no longer contains wildcard inputs. This is somewhat convoluted because your encoder is very convenient in inputting wildcards/LoRAs from the files, while you'll have to copy/paste the text prompt back to the generator to do the combination, and the wildcard function in the wildcard encoder becomes redundant because the input text no longer contains wildcards as well. If your ImpactWildcardEncode has a combinational function switch then it will be perfect and I can just discard the combinational prompt generator directly. For the generator, if it should become perfect then it will need the text Lora function, add wildcards from files, and become an encoder, which is a longer way to go. Just my opinion here. The connection method I have above seems the best solution I can have for now.
> 
> No... don't connect to `wildcard` input. connect to `populated` input

To the populated input is actually the same because the text has finished randomized in the combinational prompt generator. I mean, if your ImpactWildcardEncode has the combinational function then I will not need the combinational prompt generator at all.

**Comment by charliebrown777** [comment]
![微信图片_20231207051622](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/36913431/e7fbbde1-d4e8-4314-9fe8-bd08cc7a756f)
So, during generations, I sometimes get this error and stop the generations. What's the issue here? Thanks!

**Comment by charliebrown777** [comment]
> ![微信图片_20231207051622](https://private-user-images.githubusercontent.com/36913431/288721072-e7fbbde1-d4e8-4314-9fe8-bd08cc7a756f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDUwMDUsIm5iZiI6MTcwMTk0NDcwNSwicGF0aCI6Ii8zNjkxMzQzMS8yODg3MjEwNzItZTdmYmJkZTEtZDRlOC00MzE0LTlmZTgtYmQwOGNjN2E3NTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEwMjUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYjViYzA0ZjE5YmMzYmJhNDYxOWMzYzE0MmE5YzYyZDIxZmE4NzVkYmFhYmFmYmU4M2M2MjU3OWU1YjI2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cIhqRZuzkWW7okX7qHLMaqpqzAJ3m72nxG_SXUAX6K8) So, during generations, I sometimes get this error and stop the generations. What's the issue here? Thanks!

OK, I know the issue here. My wildcards are from automatic1111 prompts and the lora text are different from lora file names. Just need to replace them one by one...

**Comment by poipoi300** [comment]
> No... don't connect to `wildcard` input. connect to `populated` input

I don't see how doing that accomplishes anything as populated text is the processed result. Why use the node if you're going to be ignoring the processing it does?

I think this node should be implemented in the backend, because right now it's very inflexible. Even the seed can't be input to without breaking it.

**Comment by ltdrdata** [comment]
> > No... don't connect to `wildcard` input. connect to `populated` input
> 
> I don't see how doing that accomplishes anything as populated text is the processed result. Why use the node if you're going to be ignoring the processing it does?
> 
> I think this node should be implemented in the backend, because right now it's very inflexible. Even the seed can't be input to without breaking it.

The `ImpactWildcardProcessor` and `ImpactWildcardEncode` function differently. `ImpactWildcardProcessor` operates solely at the prompt determination stage and concludes by returning the populated text.

However, `ImpactWildcardEncode`, even when passed to populated input, still re-executes the wildcard population stage because processing LoRA can only be done on the backend. However, in this scenario, it becomes impossible to retain information in the stored workflow.

**Comment by poipoi300** [comment]
Hm ok you're right, sorry. I think I had the seed hooked up in my tests and I assumed that it didn't work because I didn't know the seed broke it yet.
