### ISSUE TITLE
[Request]: Self-Attention-Guidance Node

### ISSUE THREAD

**Issue by ghost** [ltdrdata/ComfyUI-Impact-Pack#344]
I've been trying to hack this together on my own as I think SAG used together with FreeU delivers unbeatable detail and image quality. It is currently missing in ComfyUI. It is a pretty good extension on A1111: https://github.com/ashen-sensored/sd_webui_SAG

From what I can see the model needs to be patched (I think it is set_model_attn1_patch in ComfyUI, it is shared.sd_model.model.diffusion_model.middle_block._modules['1'].transformer_blocks._modules['0'].attn1 in A1111)

SAG creates an attention mask with some parameters in its own function. This is where my knowledge ends. I do not think ComfyUI has the same callbacks as A1111. So I would need a new sampler node where this attention mask is applied.

I would love to use SAG in ComfyUI but so far I have to use ModelSurge/sd-webui-comfyui to use SAG in ComfyUI which is not a solution. I also think many users who do not know SAG would also love to use it in ComfyUI. Any help would be appreciated, my coding skills are not brilliant

**Comment by ltdrdata** [comment]
I've just started studying the attention patch aspect myself. I'll study it first and give it a try later.

**Comment by ltdrdata** [comment]
https://github.com/comfyanonymous/ComfyUI/pull/2201
