### ISSUE TITLE
Detailer for Animatediff cannot inpaint properly

### ISSUE THREAD

**Issue by kacecarol** [ltdrdata/ComfyUI-Impact-Pack#345]
Hello I encounted some problems in step2. With default parameters, the Detailer for Animatediff inpaints the frames with 'white fog', failed to improving. Let me know if you have any clue to the reason, thanks
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/81342264/a52c52d9-1e5d-4988-abc5-6ca041f063da)

**Comment by ltdrdata** [comment]
With this information, nothing can be determined.

**Comment by kacecarol** [comment]
> With this information, nothing can be determined.

Please let me know what else info you need to identify this issue,thanks

**Comment by ltdrdata** [comment]
> > With this information, nothing can be determined.
> 
> Please let me know what else info you need to identify this issue,thanks

Show me the workflow.

**Comment by kacecarol** [comment]
Here is the workflow, modified from an official one.
[kacecarolmodworkflow.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13595366/kacecarolmodworkflow.json)

The official one:
![detailer-for-animatediff](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/81342264/0c09ed31-8255-42f4-8c01-e32fa16dc6fd)

and today I changed another video to test, I got

[mask_to_segs] Empty mask.
# of Detected SEGS: 0
Prompt executed in 7.57 seconds

one of the output frames looks like:
![AnimateDiff_00003](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/81342264/c66b49d2-4e55-42d7-a608-1318608bba23)
after the first ksampler which seed is 888888890.

I tried the official txt2img workflow and it worked properly.

**Comment by kacecarol** [comment]
Ok I was aware of what mistake I had made. The controlnet positive was added to the pipe so this solidified the noise in the detailer.
Sorry for disrupting your work, and thank you for your nodes.
