### ISSUE TITLE
The logic for image transmission and image reception seems to have some issues.

### ISSUE THREAD

**Issue by wibur0620** [ltdrdata/ComfyUI-Impact-Pack#346]
Please review the video feedback for a detailed explanation of the situation.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/131615326/d9ad62ca-d4f7-4018-b930-bc9517dd2df7

**Comment by ltdrdata** [comment]
This is a natural occurrence. The ImageSender node sends an image at the moment the node is executed. On the other hand, the workflow starting from ImageReceiver continues from the prompt and is in the queue even if no image has been sent.

This node was originally designed with the intention of facilitating the i2i (image-to-image) process by returning the execution result of the workflow to the beginning of the workflow.

If the purpose is simply to visually separate them, it is recommended to use nodes like `Use Everywhere`.

This workflow will helps you.
https://openart.ai/workflows/toad_shrill_9/openpose-to-region-map/OjiCSv3Bq2CEHB9Cwomu

**Comment by wibur0620** [comment]
Thank you very much for your answer. I understand now. Thank you
