### ISSUE TITLE
Issue with inverted switches

### ISSUE THREAD

**Issue by rlfms** [ltdrdata/ComfyUI-Impact-Pack#347]
I'm trying to convert a Yes or No text into an Inversed switch. I'm using Preset text to convert it into 1 or 2 and WAS Node to input number as text and convert it into integer. But it gives an error to the upscale (which shouldn't be loading, it is output 2 of the inverted switch). Can someone help me out?
Also, tried Impactint and its value as input, with the same problem.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/48523434/4c4640ae-8a03-467b-8e50-de2964e24a5c)

**Comment by rlfms** [comment]
When I try to run the Upscale, output 1 (preview image) doesn't work, with a different error:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/48523434/5d6b0ea6-480b-43f5-8852-5ba93a11abe4)

**Comment by ltdrdata** [comment]
The 'select' function of the Inverted Switch utilizes the feature of virtually disconnecting the connection before the workflow execution, making it unable to receive the execution result of the workflow as input. Only PrimitiveNode and ImpactInt are allowed as inputs.
