### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by MartinBTM** [ltdrdata/ComfyUI-Impact-Pack#348]
Error occurred when executing SAMLoader:

PytorchStreamReader failed reading zip archive: failed finding central directory

File "/mnt/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/mnt/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/mnt/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/mnt/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 106, in load_model
sam = sam_model_registry[model_kind](checkpoint=modelname)
File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/segment_anything/build_sam.py", line 38, in build_sam_vit_b
return _build_sam(
File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/segment_anything/build_sam.py", line 105, in _build_sam
state_dict = torch.load(f)
File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
with _open_zipfile_reader(opened_file) as opened_zipfile:
File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
super().__init__(torch._C.PyTorchFileReader(name_or_buffer))

Who can help me with this problem?

**Comment by ltdrdata** [comment]
It seems your SAM file isn't valid. Check `ComfyUI/models/sams`.
And Impact's SAMLoader doesn't support hq model.

**Comment by MartinBTM** [comment]
> It seems your SAM file isn't valid. Check `ComfyUI/models/sams`. And Impact's SAMLoader doesn't support hq model.

Thanks ,I will check , and where can I find some same model that support hq?

**Comment by MartinBTM** [comment]
> It seems your SAM file isn't valid. Check `ComfyUI/models/sams`. And Impact's SAMLoader doesn't support hq model.

Thanks ,I will check , and where can I find some same model that support hq?

**Comment by MartinBTM** [comment]
I used sam_hq_vit_b.pth and new error

Error occurred when executing SAMLoader:

Error(s) in loading state_dict for Sam:
Unexpected key(s) in state_dict: "mask_decoder.hf_token.weight", "mask_decoder.hf_mlp.layers.0.weight", "mask_decoder.hf_mlp.layers.0.bias", "mask_decoder.hf_mlp.layers.1.weight", "mask_decoder.hf_mlp.layers.1.bias", "mask_decoder.hf_mlp.layers.2.weight", "mask_decoder.hf_mlp.layers.2.bias", "mask_decoder.compress_vit_feat.0.weight", "mask_decoder.compress_vit_feat.0.bias", "mask_decoder.compress_vit_feat.1.weight", "mask_decoder.compress_vit_feat.1.bias", "mask_decoder.compress_vit_feat.3.weight", "mask_decoder.compress_vit_feat.3.bias", "mask_decoder.embedding_encoder.0.weight", "mask_decoder.embedding_encoder.0.bias", "mask_decoder.embedding_encoder.1.weight", "mask_decoder.embedding_encoder.1.bias", "mask_decoder.embedding_encoder.3.weight", "mask_decoder.embedding_encoder.3.bias", "mask_decoder.embedding_maskfeature.0.weight", "mask_decoder.embedding_maskfeature.0.bias", "mask_decoder.embedding_maskfeature.1.weight", "mask_decoder.embedding_maskfeature.1.bias", "mask_decoder.embedding_maskfeature.3.weight", "mask_decoder.embedding_maskfeature.3.bias".

File "/mnt/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/mnt/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/mnt/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/mnt/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 106, in load_model
sam = sam_model_registry[model_kind](checkpoint=modelname)
File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/segment_anything/build_sam.py", line 38, in build_sam_vit_b
return _build_sam(
File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/segment_anything/build_sam.py", line 106, in _build_sam
sam.load_state_dict(state_dict)
File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by ltdrdata** [comment]
> I used sam_hq_vit_b.pth and new error
> 
> Error occurred when executing SAMLoader:
> 
> Error(s) in loading state_dict for Sam: Unexpected key(s) in state_dict: "mask_decoder.hf_token.weight", "mask_decoder.hf_mlp.layers.0.weight", "mask_decoder.hf_mlp.layers.0.bias", "mask_decoder.hf_mlp.layers.1.weight", "mask_decoder.hf_mlp.layers.1.bias", "mask_decoder.hf_mlp.layers.2.weight", "mask_decoder.hf_mlp.layers.2.bias", "mask_decoder.compress_vit_feat.0.weight", "mask_decoder.compress_vit_feat.0.bias", "mask_decoder.compress_vit_feat.1.weight", "mask_decoder.compress_vit_feat.1.bias", "mask_decoder.compress_vit_feat.3.weight", "mask_decoder.compress_vit_feat.3.bias", "mask_decoder.embedding_encoder.0.weight", "mask_decoder.embedding_encoder.0.bias", "mask_decoder.embedding_encoder.1.weight", "mask_decoder.embedding_encoder.1.bias", "mask_decoder.embedding_encoder.3.weight", "mask_decoder.embedding_encoder.3.bias", "mask_decoder.embedding_maskfeature.0.weight", "mask_decoder.embedding_maskfeature.0.bias", "mask_decoder.embedding_maskfeature.1.weight", "mask_decoder.embedding_maskfeature.1.bias", "mask_decoder.embedding_maskfeature.3.weight", "mask_decoder.embedding_maskfeature.3.bias".
> 
> File "/mnt/ComfyUI/execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "/mnt/ComfyUI/execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "/mnt/ComfyUI/execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "/mnt/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 106, in load_model sam = sam_model_registry[model_kind](checkpoint=modelname) File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/segment_anything/build_sam.py", line 38, in build_sam_vit_b return _build_sam( File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/segment_anything/build_sam.py", line 106, in _build_sam sam.load_state_dict(state_dict) File "/root/miniconda3/envs/myconda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

It was not a suggestion to use **HQ** but rather a suggestion not to use it.
You have to use this node to use hq model.
https://github.com/storyicon/comfyui_segment_anything
