### ISSUE TITLE
Help please, cant find the impact pack node.

### ISSUE THREAD

**Issue by DENG-XC** [ltdrdata/ComfyUI-Impact-Pack#350]
![微信图片_20231209120123](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/153186602/3169bdde-01dc-4818-840d-60b8daa2ba74)
![微信图片_20231209120128](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/153186602/d9982adb-03df-47c2-81cb-a8838c7a9551)
![微信图片_20231209120137](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/153186602/eac9132d-463e-4c4b-a7e8-1b1576f67db1)
![微信图片_20231209120108](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/153186602/a3fb20c7-76ca-4dec-9fac-f77be4b9b442)

can someone help me with this problem, I cant find the impact pack node in comfyui.

**Comment by ltdrdata** [comment]
You need to install `git-scm`.
https://github.com/ltdrdata/ComfyUI-Manager#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only

**Comment by DENG-XC** [comment]
> You need to install `git-scm`. https://github.com/ltdrdata/ComfyUI-Manager#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only
![7ebfe5253a558637cd61841eb9ef53e](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/153186602/eb9c3329-dab8-489c-9783-ab25ef270ddf)

Hi, thanks for your reply, I am new to comfyui and github. it is the right way to install impact pack？

**Comment by ltdrdata** [comment]
> > You need to install `git-scm`. https://github.com/ltdrdata/ComfyUI-Manager#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only
> > ![7ebfe5253a558637cd61841eb9ef53e](https://private-user-images.githubusercontent.com/153186602/289350887-eb9c3329-dab8-489c-9783-ab25ef270ddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTk2NzAsIm5iZiI6MTcwMjIxOTM3MCwicGF0aCI6Ii8xNTMxODY2MDIvMjg5MzUwODg3LWViOWMzMzI5LWRhYjgtNDg5Yy05NzgzLWFiMjVlZjI3MGRkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxNDQyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODRiNzVlNDgyZjBiNjE0MDU3OTI2YWI5NWY4ZmM0ODBjODRmN2YwNDk3YjdjODUyMzAzZWZjNmYzMDc4MjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fpnBmyxcxL46dreCY_n2UynoN7x0-P9224m1oXWH55c)
> 
> Hi, thanks for your reply, I am new to comfyui and github. it is the right way to install impact pack？

Don't you use ComfyUI-Manager?
Why don't you just use portable version instead of mingw64?
