### ISSUE TITLE
[Help] where i can find this file to fix that

### ISSUE THREAD

**Issue by DaviJh** [ltdrdata/ComfyUI-Impact-Pack#351]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/75020215/e6ed5b62-1d76-4d41-a6de-a6fbb47fb132)
idk the path to it. i really need step by step

**Comment by DaviJh** [comment]
i dumb

**Comment by 1119127836** [comment]
Hello, please tell me how you solved this problem. I also encountered this problem and tried all methods to no avail.

**Comment by ltdrdata** [comment]
> Hello, please tell me how you solved this problem. I also encountered this problem and tried all methods to no avail.

Just update Impact Pack and remove old `Segs & Mask` and re-add new `Segs & Mask`
