### ISSUE TITLE
Iterative Latent Upscale stopped working after latest update

### ISSUE THREAD

**Issue by ertugrul-dmr** [ltdrdata/ComfyUI-Impact-Pack#353]
I am getting this error:

```
Error occurred when executing IterativeLatentUpscale:

'InjectNoiseHook' object has no attribute 'from_start'
```

![Screenshot 2023-12-09 144736](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/61366446/b14f5896-7523-45a1-82bc-5b8fe8502150)

That's the problematic part, if I disable it or disconnect noise hook it works. But it used to work like 1-2 days ago.

**Comment by ltdrdata** [comment]
Oh.. Sorry... This is fixed on V4.41.3.

I accidentally messed up while creating a Noise Injector for the Detailer.
