### ISSUE TITLE
ImpacxtWilcardProcessor reinit mode to Fixed when saving the workflow

### ISSUE THREAD

**Issue by yoda5477** [ltdrdata/ComfyUI-Impact-Pack#356]
Seems when setup in the gui the mode to Populate, execute it works fine. save the workflow, in the json saved the mode is back to Fixed, when reopenning the workflow it is confirmed changed to fixed. If manually changin gthe json file before loading to True, the load works fine so for sute th eissue is in the saving part.

**Comment by yoda5477** [comment]
I tried to fix myself, but got lost between the py  (extremely simple) and the js (hell of a code for me)

**Comment by yoda5477** [comment]
Ok found it I think, solved (hopefully) by commpenting the line below, not sure why we would want on server side to change the mode without sending back the signal to the web display: (sorry not sure how to push this officially or what side impact there would be):

def populate_wildcards(json_data):
    prompt = json_data['prompt']

    updated_widget_values = {}
    for k, v in prompt.items():
        if 'class_type' in v and (v['class_type'] == 'ImpactWildcardEncode' or v['class_type'] == 'ImpactWildcardProcessor'):
            inputs = v['inputs']
            if inputs['mode'] and isinstance(inputs['populated_text'], str):
                inputs['populated_text'] = wildcards.process(inputs['wildcard_text'], int(inputs['seed']))
#                inputs['mode'] = False

**Comment by ltdrdata** [comment]
That's intentionally changed to facilitate reproducibility when loading the workflow.

**Comment by yoda5477** [comment]
Not sure why but when updated to last commit, issue disappear while the line I identified style unchanged (so guyess issue was somewheer else)
