### ISSUE TITLE
MaskToSEGS not working

### ISSUE THREAD

**Issue by Praecordi** [ltdrdata/ComfyUI-Impact-Pack#357]
My MaskToSEGS is not working after a recent update. For context, I'm trying to use the detailer to inpaint hair. I'm using CLIPSeg to get a mask of the hair, processing the mask and then converting to SEGS for the detailer. This worked previously, but after I updated, MaskToSEGS gives an empty segmentation despite the mask not being empty.

Here's a minimal workflow showcasing this
[issue_example.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13628101/issue_example.json)

**Comment by ltdrdata** [comment]
WAS-NS's node is returning abnormal mask.
Anyway, I just updated the nodes in the Impact Pack and applied a compatibility patch to handle masks in that form.
