### ISSUE TITLE
seed load in ImpacrWilcardProcessor ?

### ISSUE THREAD

**Issue by yoda5477** [ltdrdata/ComfyUI-Impact-Pack#358]
Got an error, debugged and changed to add [0]as it seems to rceive an array not a single int (not sure this is the clean way to solved, but it solved for me):

in impact_server.py

inputs['populated_text'] = wildcards.process(inputs['wildcard_text'], int(inputs['seed']))
=>
inputs['populated_text'] = wildcards.process(inputs['wildcard_text'], int(inputs['seed'][0]))

**Comment by ltdrdata** [comment]
Did you converted seed widget to input?

**Comment by ltdrdata** [comment]
This is fixed on v4.44.6

**Comment by yoda5477** [comment]
Fix has issue with reroute as in case of reroute the value will be anothr node but with type ImpactInt.
In that case currently no warning but no processing either
:

                    try:
                        input_node = prompt[inputs['seed'][0]]
                        print(f"input node : {input_node}")
                        if input_node['class_type'] == 'ImpactInt':
                            input_seed = **int(input_node['inputs']['value'])**
                            if not isinstance(input_seed, int):
                                continue
                        else:
                            print(f"[Impact Pack] Only ImpactInt and Primitive Node are allowed as the seed for '{v['class_type']}'. It will be ignored. ")
                            continue

**Comment by ltdrdata** [comment]
Since reroute is a virtual node, when passed through a prompt, it is processed just like a direct connection without reroute. There is no issue with this.
