### ISSUE TITLE
Stop processing Switches if existe one withoput select input

### ISSUE THREAD

**Issue by yoda5477** [ltdrdata/ComfyUI-Impact-Pack#359]
When there is a switch with select as input not linked, not clear in the erreor log and stop all switches.

Imrpved by adding condition on 'select' in 'unputs' before executing the code using it (impact_server.py):

            if 'sel_mode' in v['inputs'] and v['inputs']['sel_mode'] and 'select' in v['inputs']:

**Comment by ltdrdata** [comment]
This is reflected on V4.44.7.
