### ISSUE TITLE
Fix has issue with reroute as in case of reroute the value will be anothr node but with type ImpactInt (fix proposed to propagate seed along chain)

### ISSUE THREAD

**Issue by yoda5477** [ltdrdata/ComfyUI-Impact-Pack#360]
Fix has issue with reroute as in case of reroute the value will be anothr node but with type ImpactInt.
In that case currently no warning but no processing either
:

                    try:
                        input_node = prompt[inputs['seed'][0]]
                        print(f"input node : {input_node}")
                        if input_node['class_type'] == 'ImpactInt':
                            input_seed = **int(input_node['inputs']['value'])**
                            if not isinstance(input_seed, int):
                                continue
                        else:
                            print(f"[Impact Pack] Only ImpactInt and Primitive Node are allowed as the seed for '{v['class_type']}'. It will be ignored. ")
                            continue

_Originally posted by @yoda5477 in https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/358#issuecomment-1849018411_

**Comment by yoda5477** [comment]
Fixed with this change to go up the chain :
            if inputs['mode'] and isinstance(inputs['populated_text'], str):
                #print(f"inputs : {inputs}")
                input_seed_t = inputs['seed']
                while isinstance(input_seed_t, list):
                    try:
                        input_node = prompt[input_seed_t[0]]
                        #print(f"input node : {input_node}")
                        if 'seed' in input_node['inputs']:
                            input_seed_t = input_node['inputs']['seed']
                        else:
                            input_seed_t = input_node['inputs']['value']
                    except:
                        continue
                if not isinstance(input_seed_t, int):
                    continue
                input_seed = int(input_seed_t)

**Comment by ltdrdata** [comment]
Do you want to allow the chain of ImpactInt?

**Comment by yoda5477** [comment]
Would like to propagate seed throught reroute through the workflow and to use it in the wilcardprocessor

Did the fix written, seeing no issue so far

**Comment by yoda5477** [comment]
My bad, the issue was that I used an ImpactInt to convert a seed from other custom nodes into impactInt (so use value as input, so in that case it failed. Solved by removing the constraint on the type to be impactInt (why not allow other seeders?) and loop if not finding seed into previous chain.

**Comment by ltdrdata** [comment]
Wildcards must be populated before the workflow is executed. Therefore, they cannot be used if the seed is generated as a result of the workflow execution.

**Comment by yoda5477** [comment]
So you mean as ImpactInt are specially considered innImpact code on server side my way would mean previous seed is used instead of the one planned for the wilcard, I see
Still better than not doing anythin but I see your point.

**Comment by ltdrdata** [comment]
That supports utilizing the values received in the workflow through ImpactValueSender for a purpose available at the beginning of a new workflow execution.
