### ISSUE TITLE
[Enhancement]: Doing different prompts for every image in a batch

### ISSUE THREAD

**Issue by ghost** [ltdrdata/ComfyUI-Impact-Pack#362]
Hi, I wondered if it is possible to have 4 different prompt conditionings from ImpactWildcardEncode made into a batch size of 4 that is then run by a sampler? Does it need a new sampler node for this?

So far I always had to make 4 new sampler combos to get 4 prompt variations, all running batch size 1 each.

If I have missed something please explain / close issue. Thank you very much.

**Comment by ltdrdata** [comment]
This is because the structure of KSampler in ComfyUI already handles the encoded conditioning, so some ideas are needed. 
Simply implementing the functionality itself is possible, but creating a proper structure for it is a challenging task.
I'll keep it in mind.

**Comment by ghost** [comment]
How about making conditions batchable? This cannot be done just as an extension, it needs a change in the standard KSampler nodes to be adopted freely, like taking a list as conditioning. I am not skilled enough to code it myself but I am learning
