### ISSUE TITLE
UltralyticsDetectorProvider  is unable to discover model

### ISSUE THREAD

**Issue by AnitaSherry** [ltdrdata/ComfyUI-Impact-Pack#365]
[I refer to this workflow](https://openart.ai/workflows/toad_shrill_9/openpose-to-region-map-v2/OjiCSv3Bq2CEHB9Cwomu)
I have a model person_yolov8m-seg.pt to use in UltralyticsDetectorProvider.
I put it in ComfyUI/models/sams/segm, /ComfyUI/models/mmdets/segm, /ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/segm,It  all doesn't work

**Comment by ltdrdata** [comment]
`ComfyUI/models/ultralytics/segm` is correct path.
