### ISSUE TITLE
Missing ImpactFloat

### ISSUE THREAD

**Issue by HavocsCall** [ltdrdata/ComfyUI-Impact-Pack#366]
A small one and hopefully, a quick one.

I am unable to find ImpactFloat.

I uninstalled other custom nodes to check for conflicts.
I reinstalled Impact Pack.
Search and Add node does not find it.

Thank you for the pack and reading.

**Comment by ltdrdata** [comment]
Oh, I commented on this, but I'm not sure why I did that. Perhaps it was a mistake on my part.
It is added on V4.46.1.

**Comment by HavocsCall** [comment]
Thanks, awesome.
