### ISSUE TITLE
Improving bit depth

### ISSUE THREAD

**Issue by calcoloergosum** [ltdrdata/ComfyUI-Impact-Pack#369]
**Motivation**: While post-processing, I noticed degradation of quality.

**Suggestion**: Let's handle images as `float32` or `uint16`.

Some facts:
- `PIL.Image` can't handle properly other than 8 bit depth images.
- `PIL`s functionality can be replaced with `opencv` or `torch`, who can handle `float` or 16 bit depth images.
- This change should not be hard, considering current use cases; `resize`, `paste`, some filters, and putting alpha channel, e.t.c.. 
- This change will affect overall code base.

If interested, I can draft for further feedback.
Thank you.

**Comment by ltdrdata** [comment]
I think it should be excellent PR.

Due to the broad impact, it seems necessary to test all the workflows here at least once.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/tree/Main/ComfyUI-Impact-Pack/workflow

**Comment by calcoloergosum** [comment]
#371
