### ISSUE TITLE
ComfyUI Impact Pack -import failed

### ISSUE THREAD

**Issue by 1119127836** [ltdrdata/ComfyUI-Impact-Pack#370]
Hello, I spent two whole days trying various methods to solve the problem of showing the IMPORT FAILED error, including uninstalling and reinstalling.
<img width="1529" alt="1702544310704" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/72272886/8843d5fc-eeb2-40f3-9c5f-ab4d63d8c7a9">

**Comment by 1119127836** [comment]
I tried the solutions mentioned under the other links and none of them solved the reported error

** ComfyUI start up time: 2023-12-14 16:46:05.389605

Prestartup times for custom nodes:
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Set cuda device to: 0
Total VRAM 12282 MB, total RAM 32694 MB
xformers version: 0.0.17+c36468d.d20230316
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints D:/SD-webui/sd-webui-aki-v4.4/models/Stable-diffusion
Adding extra search path configs D:/SD-webui/sd-webui-aki-v4.4/models/Stable-diffusion
Adding extra search path vae D:/SD-webui/sd-webui-aki-v4.4/models/VAE
Adding extra search path loras D:/SD-webui/sd-webui-aki-v4.4/models/Lora
Adding extra search path upscale_models D:/SD-webui/sd-webui-aki-v4.4/models/ESRGAN
Adding extra search path upscale_models D:/SD-webui/sd-webui-aki-v4.4/models/SwinIR
Adding extra search path embeddings D:/SD-webui/sd-webui-aki-v4.4/embeddings
Adding extra search path controlnet D:/SD-webui/sd-webui-aki-v4.4/models/ControlNet
[AnimateDiff] - [0;33mWARNING[0m - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[AnimateDiff] - [0;31mERROR[0m - No models available. Please download one and put it in models folder
Traceback (most recent call last):
  File "E:\Blender_ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Blender_ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'

Cannot import E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: 'E:\\Blender_ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
Traceback (most recent call last):
  File "E:\Blender_ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\__init__.py", line 1, in <module>
    from . import exllama, text
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\exllama.py", line 9, in <module>
    from exllamav2 import (
ModuleNotFoundError: No module named 'exllamav2'

Cannot import E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes module for custom nodes: No module named 'exllamav2'
### Loading: ComfyUI-Impact-Pack (V4.46.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
Traceback (most recent call last):
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\pipelines\__init__.py", line 28, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Blender_ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 107, in <module>
    from impact.hf_nodes import *
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\hf_nodes.py", line 1, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Cannot import E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
### Loading: ComfyUI-Inspire-Pack (V0.47.3)
### Loading: ComfyUI-Manager (V1.8.3)
### ComfyUI Revision: 1793 [cdff0810] | Released on '2023-12-07'
Watcher: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\nodes\config.json
--------------
[91mMixlab Nodes: [93mLoaded[0m
--------------
Failed to auto update `Quality of Life Suit` 
[33mQualityOfLifeSuit_Omar92_DIR:[0m E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Traceback (most recent call last):
  File "E:\Blender_ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node-main\__init__.py", line 25, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node-main\nodes.py", line 4, in <module>
    from scripts.reactor_faceswap import FaceSwapScript, get_models, get_current_faces_model, analyze_faces
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node-main\scripts\reactor_faceswap.py", line 12, in <module>
    from scripts.reactor_logger import logger
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node-main\scripts\reactor_logger.py", line 6, in <module>
    from reactor_utils import addLoggingLevel
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node-main\reactor_utils.py", line 8, in <module>
    from insightface.app.common import Face
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\insightface\model_zoo\model_zoo.py", line 22, in <module>
    class PickableInferenceSession(onnxruntime.InferenceSession):
AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'

Cannot import E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node-main module for custom nodes: module 'onnxruntime' has no attribute 'InferenceSession'
[VideoHelperSuite] - [0;32mINFO[0m - ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
### Loading: Workspace Manager (V1.0.0)
[34mComfyroll Custom Nodes: [92mLoaded[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider'][0m
E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:25: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
[1;35m### [START] ComfyUI AlekPet Nodes ###[0m
[92mNode -> ArgosTranslateNode [Loading][0m
[92mNode -> ExtrasNode [Loading][0m
[92mNode -> PainterNode [Loading][0m
[92mNode -> PoseNode [Loading][0m
[92mNode -> TranslateNode [Loading][0m
[1;35m### [END] ComfyUI AlekPet Nodes ###[0m
[34mDavemane42 Custom Nodes: [92mLoaded[0m
[34mFizzleDorf Custom Nodes: [92mLoaded[0m
Traceback (most recent call last):
  File "E:\Blender_ComfyUI\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Blender_ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus-main\\__init__.py'

Cannot import E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main module for custom nodes: [Errno 2] No such file or directory: 'E:\\Blender_ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus-main\\__init__.py'

[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
[36mEfficiency Nodes:[0m Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...
[36mEfficiency Nodes:[0m Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...[92mSuccess![0m
[34mWAS Node Suite: [0mBlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.[0m
[34mWAS Node Suite: [0m`CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.[0m
[34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `E:\Blender_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m198[0m [32mnodes successfully.[0m

	[3m[93m"Every strike brings me closer to the next home run."[0m[3m - Babe Ruth[0m


Import times for custom nodes:
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_LatentToRGB
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_dagthomas
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_FastVAEDecorder_SDXL
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds (IMPORT FAILED): E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\Cup-ClipBoard
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-CLIPSeg
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\cup.py
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_fabric
   0.0 seconds (IMPORT FAILED): E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Text_Image-Composite
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfy-qr
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui-jags
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   0.1 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds (IMPORT FAILED): E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node-main
   0.2 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\clipseg.py
   0.4 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   1.6 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-LaMA-Preprocessor
   2.6 seconds (IMPORT FAILED): E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   2.6 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
  17.0 seconds: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

https_key OK:  E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\certificate.crt E:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\https\private.key
[93mStarting server

[93mTo see the GUI go to: http://127.0.0.1:8188
[93mTo see the GUI go to: https://127.0.0.1:8189[0m
FETCH DATA from: E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[AnimateDiffEvo] - [0;33mWARNING[0m - This warning can be ignored, you should not be using the deprecated AnimateDiff Combine node anyway. If you are, use Video Combine from ComfyUI-VideoHelperSuite instead. ffmpeg could not be found. Outputs that require it have been disabled
Error: OpenAI API key is invalid OpenAI features wont work for you
[33mQualityOfLifeSuit_Omar92:[0m:NSP ready
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

**Comment by ltdrdata** [comment]
This issue is a common occurrence when using the reactor node due to the dependency on insightface. Coordinating versions becomes quite challenging when trying to use them together. Frankly, I'm not sure which version would work well for both sides.

However, if you execute `pip install -U protobuf==3.20.3` in your Python environment, I believe it should resolve the issues arising from the impact pack for the time being.

"Your Python environment" means that if you are using venv, you should execute the command while the venv is activated. If it's a portable version, use the python.exe from python_embedded. Since I don't know the specifics of your current Python environment, I cannot provide more detailed guidance.

If this doesn't work, I recommend performing a clean installation.

**Comment by samuelstarx** [comment]
> Hello, I spent two whole days trying various methods to solve the problem of showing the IMPORT FAILED error, including uninstalling and reinstalling. <img alt="1702544310704" width="1529" src="https://private-user-images.githubusercontent.com/72272886/290463828-8843d5fc-eeb2-40f3-9c5f-ab4d63d8c7a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDA4NDMsIm5iZiI6MTcwMzE0MDU0MywicGF0aCI6Ii83MjI3Mjg4Ni8yOTA0NjM4MjgtODg0M2Q1ZmMtZWViMi00MGYzLTljNWYtYWI0ZDYzZDhjN2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA2MzU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MzAxNWRhYzFjZDQ0OGFkYTAyYjI5ODdhMjNmMjc3YjY4MGFkZWY2NWNmYWVlMGQ4YmQ2NzI2OTljYjEyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mtKQu5pqaFyGrmdfgyFQoAI_UXKvxMwtXPv9qmrPRcQ">

ME TOO

**Comment by gabrie** [comment]
I just uninstalled Reactor for now to solve this issue......
