### ISSUE TITLE
Error occurred when executing FaceDetailer:  Kernel size value should be an odd and positive number.

### ISSUE THREAD

**Issue by fuselayer** [ltdrdata/ComfyUI-Impact-Pack#373]
Error occurred when executing FaceDetailer:

Kernel size value should be an odd and positive number.

File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 463, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
File "/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 430, in enhance_face
DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
File "/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 210, in do_detail
mask = tensor_feather_mask(mask, feather)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/utils.py", line 309, in tensor_feather_mask
blurred_mask = torchvision.transforms.GaussianBlur(thickness)(mask)
File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 1783, in __init__
raise ValueError("Kernel size value should be an odd and positive number.")

**Comment by ltdrdata** [comment]
For diagnostic purposes, please provide your workflow.

**Comment by kollko** [comment]
Hello, I'm not sure if I should open a new thread. I have the same problem but with a debug detailer node (or maybe with all) after the last update, no matter the flow ( just simple or more complex).

**Comment by ltdrdata** [comment]
> Hello, I'm not sure if I should open a new thread. I have the same problem but with a debug detailer node (or maybe with all) after the last update, no matter the flow ( just simple or more complex).

Create a completely new installation environment to other directory and install only the Impact Pack for testing there.

I always test in the latest environment, and when I tested the entire tutorial workflow last night, there were no issues at all.

**Comment by kollko** [comment]
Hi, thanks for the suggestion I will try that. In the mean time is there any known conflicts with other nodes?

**Comment by longkenj** [comment]
you can try change the **Feather** to an odd number.
ex: 10 change to 11.

**Comment by kollko** [comment]
> you can try change the **Feather** to an odd number. ex: 10 change to 11.

Thanks, not sure why but that worked like a charm. In that case @ltdrdata  is there an issue with the custom node?

**Comment by sato68885345** [comment]
Hi, I was experiencing this event as well.
It seems that there is no conflict with other custom node, because the event occurred even if I disabled all custom node except manager and Inpact-Pack.

I updated ComfyUI by running [update_comfyui_and_python_dependencies.bat].
I had the environment before the update, so I checked the pip list and the following update may have affected it.
tokenizers 0.14.1 > 0.15.0
torch 2.1.1+cu121 > 2.1.2+cu121
torchaudio 2.1.1+cu121 > 2.1.2+cu121
torchvision 0.16.1+cu121 > 0.16.2+cu121
transformers 4.35.2 > 4.36.1

**Comment by sato68885345** [comment]
Hi, I also experienced this event.

It occurred even after disabling all custom nodes except manager and Impact-Pack,
so it does not seem to be a conflict with other custom nodes.

I updated ComfyUI with [update_comfyui_and_python_dependencies.bat].
I checked the pip list diff of the environment before the update,
I noticed that torch 2.1.1 > 2.1.2 was updated.
However, this event occurred even after reverting to the torch 2.1.1 environment, so this seems to be of little relevance.

**Comment by kollko** [comment]
> Hi, I also experienced this event.
> 
> It occurred even after disabling all custom nodes except manager and Impact-Pack, so it does not seem to be a conflict with other custom nodes.
> 
> I updated ComfyUI with [update_comfyui_and_python_dependencies.bat]. I checked the pip list diff of the environment before the update, I noticed that torch 2.1.1 > 2.1.2 was updated. However, this event occurred even after reverting to the torch 2.1.1 environment, so this seems to be of little relevance.

You could try the fix that @longkenj proposed. It worked for me

**Comment by ltdrdata** [comment]
> you can try change the **Feather** to an odd number. ex: 10 change to 11.

Yeah. It was that.
This is fixed on V4.47.2.

**Comment by kollko** [comment]
Thanks, guys you are awsome.

**Comment by fuselayer** [comment]
Thanks for the quick response and fix. Just a heads up: I just tried the same workflow on my local machine and it works just fine (I was on cloud yesterday).  I'm still on 33c68fdd8e9bec8afdc67012a9bb7fc5d7c013a3 and my feather is an even number. 

Very weird.

**Comment by ltdrdata** [comment]
> Thanks for the quick response and fix. Just a heads up: I just tried the same workflow on my local machine and it works just fine (I was on cloud yesterday).  I'm still on 33c68fdd8e9bec8afdc67012a9bb7fc5d7c013a3 and my feather is an even number. 
> 
> Very weird. 

Recently, there has been an upgrade to minimize image degradation by reducing the usage of the previously used image processing library called PIL. During this process, some constraints have changed.
