### ISSUE TITLE
Error occurred when executing BboxDetectorSEGS

### ISSUE THREAD

**Issue by ModzhaHead** [ltdrdata/ComfyUI-Impact-Pack#374]
Error occurred when executing BboxDetectorSEGS:

UltraBBoxDetector.detect() takes from 5 to 6 positional arguments but 7 were given

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 87, in doit
    segs = bbox_detector.detect(image, threshold, dilation, crop_factor, drop_size, detailer_hook)

using this workflow: https://civitai.com/models/138397?modelVersionId=223825
winstons_workflow.json

as it says on this page:: https://ltdrdata.github.io/
w/NOTE:'Segs & Mask' has been renamed to 'ImpactSegsAndMask.' Please replace the node with the new name

I replaced the specified node in the workflow, but when starting generation, the specified error appears

This is a very convenient and functional workflow, I would like to fix it and continue to use it

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/351

**Comment by ModzhaHead** [comment]
> #351
yes, that's exactly what I did, tried several times, the result did not change:
https://i.imgur.com/lCl9rJT.png

**Comment by ltdrdata** [comment]
> > #351
> > yes, that's exactly what I did, tried several times, the result did not change:
> > https://i.imgur.com/lCl9rJT.png

Oh... I misread your log.

**Comment by ltdrdata** [comment]
```
### Loading: ComfyUI-Impact-Pack (V4.47.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
```
I'm not sure why, but it seems that your `impact_subpack` version doesn't match. Try deleting the `ComfyUI-Impact-Pack/impact_subpack` directory and restart ComfyUI. The subpack version should be displayed as 0.3.2 for it to work correctly.

**Comment by ModzhaHead** [comment]
> ```
> ### Loading: ComfyUI-Impact-Pack (V4.47.1)
> ### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
> ```
> 
> I'm not sure why, but it seems that your `impact_subpack` version doesn't match. Try deleting the `ComfyUI-Impact-Pack/impact_subpack` directory and restart ComfyUI. The subpack version should be displayed as 0.3.2 for it to work correctly.

I did as you advised - it seemed to help, thank you very much, the solution to the problem is not at all obvious, now all works fine! 
https://i.imgur.com/4HDdGyJ.png

**Comment by keven8654** [comment]
Error occurred when executing BboxDetectorSEGS:

[Impact Pack] ERROR: BboxDetectorForEach does not allow image batches.
Please refer to https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md for more information.

File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 90, in doit
raise Exception('[Impact Pack] ERROR: BboxDetectorForEach does not allow image batches.\nPlease refer to https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md for more information.')

please help me.

**Comment by ltdrdata** [comment]
> Error occurred when executing BboxDetectorSEGS:
> 
> [Impact Pack] ERROR: BboxDetectorForEach does not allow image batches. Please refer to https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md for more information.
> 
> File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Program Files\Stable Diffusion\ComfyUI-tieguo\Blender_ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 90, in doit raise Exception('[Impact Pack] ERROR: BboxDetectorForEach does not allow image batches.\nPlease refer to https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md for more information.')
> 
> please help me.

As mentioned in the message, please check out https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md
