### ISSUE TITLE
MediaPipe FaceMesh to SEGS fails to output multiple segs. 

### ISSUE THREAD

**Issue by yukipyng** [ltdrdata/ComfyUI-Impact-Pack#375]
First of all, thank you very much for this great custom node! 

When I am trying to do detailer on multiple faces with ControlNet (Specifically using MediaPipe FaceMesh), FaceDetailer / Detailer (SEGS) can only fix 1 face. But as you can see, the MediaPipe can indeed detect two faces. When I convert them to the segs, it returns only one.

I tried using FaceDetailer with UltralyticsDetailerProvider, it can successfully detect 2 bounding boxes and fix the faces correctly. However, since the faces are close to each other, I would like to use segmentation instead of the bounding box for the detailer. 

Is there something I missed so I cannot get the SEGS? Thanks in advance.

Here is my workflow for checking the SEGS:
![Screenshot 2023-12-17 at 10 11 46 PM](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/97665595/eeb46769-b1c2-43c9-92c8-8bc35faa3337)

**Comment by ltdrdata** [comment]
This is fixed on V4.47.3
