### ISSUE TITLE
import subpack failed

### ISSUE THREAD

**Issue by OtakuFra** [ltdrdata/ComfyUI-Impact-Pack#377]
`
C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-12-18 15:38:02.089553

Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main

Total VRAM 20470 MB, total RAM 28652 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4500 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
### Loading: ComfyUI-Impact-Pack (V4.47.4)
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
[Impact Pack] Wildcards loading done.
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 439, in <module>
    import impact.subpack_nodes
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in <module>
    raise e
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in <module>
    from ultralytics import YOLO
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'encoding'
---------------------------------

### ComfyUI Revision: 1835 [2f9d6a97] | Released on '2023-12-17'
[SD Prompt Reader] Node version: 1.2.0
[SD Prompt Reader] Core version: 1.3.4.post1
Total VRAM 20470 MB, total RAM 28652 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4500 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.2+cu121
Comfyroll Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Using xformers cross attention
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
Total VRAM 20470 MB, total RAM 28652 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4500 : cudaMallocAsync
VAE dtype: torch.bfloat16
C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\AutoUpdate.json
[Power Noise Suite]: 🦚🦚🦚 Squeaa-squee!!! 🦚🦚🦚
[Power Noise Suite]: Tamed 11 wild nodes.

[rgthree] Loaded 20 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Video-Matting
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\PPF_Noise_ComfyUI
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-consistency-vae
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg_custom_core
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Preset_Merger
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ymc-node-suite-comfyui
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\PowerNoiseSuite
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Jovimetrix
   0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   0.4 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
   0.4 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.5 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.9 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   1.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   1.4 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT
   7.9 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack`

Hi guys,thank very much for all your hard work, but now i have a problem
no matter what the subpack won't being installed, i've tried everything, nothing is working
with or whitout xformers, with or without WAS suite,quality OL, Inspire etc and also checked the troubleshooting section, no fix are working for me...
I don't know what to do i need your help.

**Comment by ltdrdata** [comment]
Your `ComfyUI-Manager` is outdated. Update it and restart.

**Comment by OtakuFra** [comment]
Sorry but still doesn't work

C:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --use-pytorch-cross-attention --port 8888
** ComfyUI start up time: 2023-12-19 19:02:41.309824

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'segment-anything']

## Execute install/(de)activation script for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 Requirement already satisfied: segment-anything in c:\comfyui_windows_portable\python_embeded\lib\site-packages (1.0)

## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'scikit-image']

## Execute install/(de)activation script for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 Requirement already satisfied: scikit-image in c:\comfyui_windows_portable\python_embeded\lib\site-packages (0.20.0)
 Requirement already satisfied: numpy>=1.21.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (1.26.2)
 Requirement already satisfied: scipy>=1.8 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (1.11.4)
 Requirement already satisfied: networkx>=2.8 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (3.2.1)
 Requirement already satisfied: pillow>=9.0.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (10.1.0)
 Requirement already satisfied: imageio>=2.4.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (2.33.1)
 Requirement already satisfied: tifffile>=2019.7.26 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (2023.12.9)
 Requirement already satisfied: PyWavelets>=1.1.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (1.5.0)
 Requirement already satisfied: packaging>=20.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (23.2)
 Requirement already satisfied: lazy_loader>=0.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from scikit-image) (0.3)

## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'piexif']

## Execute install/(de)activation script for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 Requirement already satisfied: piexif in c:\comfyui_windows_portable\python_embeded\lib\site-packages (1.1.3)

## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'transformers']

## Execute install/(de)activation script for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 Requirement already satisfied: transformers in c:\comfyui_windows_portable\python_embeded\lib\site-packages (4.36.1)
 Requirement already satisfied: filelock in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (3.13.1)
 Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (0.19.4)
 Requirement already satisfied: numpy>=1.17 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (1.26.2)
 Requirement already satisfied: packaging>=20.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (23.2)
 Requirement already satisfied: pyyaml>=5.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (6.0.1)
 Requirement already satisfied: regex!=2019.12.17 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (2023.10.3)
 Requirement already satisfied: requests in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (2.31.0)
 Requirement already satisfied: tokenizers<0.19,>=0.14 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (0.15.0)
 Requirement already satisfied: safetensors>=0.3.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (0.4.1)
 Requirement already satisfied: tqdm>=4.27 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from transformers) (4.66.1)
 Requirement already satisfied: fsspec>=2023.5.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (2023.10.0)
 Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub<1.0,>=0.19.3->transformers) (4.8.0)
 Requirement already satisfied: colorama in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
 Requirement already satisfied: charset-normalizer<4,>=2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->transformers) (3.3.2)
 Requirement already satisfied: idna<4,>=2.5 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->transformers) (3.4)
 Requirement already satisfied: urllib3<3,>=1.21.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->transformers) (1.26.18)
 Requirement already satisfied: certifi>=2017.4.17 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->transformers) (2023.11.17)

## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'opencv-python-headless']

## Execute install/(de)activation script for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 Requirement already satisfied: opencv-python-headless in c:\comfyui_windows_portable\python_embeded\lib\site-packages (4.7.0.72)
 Requirement already satisfied: numpy>=1.21.2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-python-headless) (1.26.2)

## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py']

## Execute install/(de)activation script for 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 ### ComfyUI-Impact-Pack: Check dependencies
 ### ComfyUI-Impact-Pack: Updating subpack
 [Impact Pack] EXECUTE: ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
 req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
 ### ComfyUI-Impact-Pack: Check basic models

## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'ultralytics']

## Execute install/(de)activation script for '.'
 Requirement already satisfied: ultralytics in c:\comfyui_windows_portable\python_embeded\lib\site-packages (8.0.227)
 Requirement already satisfied: matplotlib>=3.3.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (3.8.2)
 Requirement already satisfied: numpy>=1.22.2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (1.26.2)
 Requirement already satisfied: opencv-python>=4.6.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (4.7.0.72)
 Requirement already satisfied: pillow>=7.1.2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (10.1.0)
 Requirement already satisfied: pyyaml>=5.3.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (6.0.1)
 Requirement already satisfied: requests>=2.23.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (2.31.0)
 Requirement already satisfied: scipy>=1.4.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (1.11.4)
 Requirement already satisfied: torch>=1.8.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (2.1.2+cu121)
 Requirement already satisfied: torchvision>=0.9.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (0.16.2+cu121)
 Requirement already satisfied: tqdm>=4.64.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (4.66.1)
 Requirement already satisfied: pandas>=1.1.4 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (2.1.4)
 Requirement already satisfied: seaborn>=0.11.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (0.13.0)
 Requirement already satisfied: psutil in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (5.9.7)
 Requirement already satisfied: py-cpuinfo in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (9.0.0)
 Requirement already satisfied: thop>=0.1.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from ultralytics) (0.1.1.post2209072238)
 Requirement already satisfied: contourpy>=1.0.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.2.0)
 Requirement already satisfied: cycler>=0.10 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
 Requirement already satisfied: fonttools>=4.22.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (4.46.0)
 Requirement already satisfied: kiwisolver>=1.3.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.5)
 Requirement already satisfied: packaging>=20.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (23.2)
 Requirement already satisfied: pyparsing>=2.3.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.1.1)
 Requirement already satisfied: python-dateutil>=2.7 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (2.8.2)
 Requirement already satisfied: pytz>=2020.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics) (2023.3.post1)
 Requirement already satisfied: tzdata>=2022.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics) (2023.3)
 Requirement already satisfied: charset-normalizer<4,>=2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics) (3.3.2)
 Requirement already satisfied: idna<4,>=2.5 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics) (3.4)
 Requirement already satisfied: urllib3<3,>=1.21.1 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics) (1.26.18)
 Requirement already satisfied: certifi>=2017.4.17 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics) (2023.11.17)
 Requirement already satisfied: filelock in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics) (3.13.1)
 Requirement already satisfied: typing-extensions in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics) (4.8.0)
 Requirement already satisfied: sympy in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics) (1.12)
 Requirement already satisfied: networkx in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics) (3.2.1)
 Requirement already satisfied: jinja2 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.2)
 Requirement already satisfied: fsspec in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics) (2023.10.0)
 Requirement already satisfied: colorama in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.64.0->ultralytics) (0.4.6)
 Requirement already satisfied: six>=1.5 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.16.0)
 Requirement already satisfied: MarkupSafe>=2.0 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.3)
 Requirement already satisfied: mpmath>=0.19 in c:\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.8.0->ultralytics) (1.3.0)

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
  34.8 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main

Total VRAM 20470 MB, total RAM 28652 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A4500 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.48.4)
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['C:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
[Impact Pack] Wildcards loading done.
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 443, in <module>
    import impact.subpack_nodes
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in <module>
    raise e
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in <module>
    from ultralytics import YOLO
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'encoding'
---------------------------------

**Comment by ltdrdata** [comment]
Yours:
```
## Loading: ComfyUI-Manager (V1.0.1)
```

Recent:
```
### Loading: ComfyUI-Manager (V1.15)
```


That means your manager hasn't been updated. The file in your ComfyUI-Manager path may have been modified or the installation at the incorrect path is excluding it from updates.

Ensure that ComfyUI-Manager is installed precisely in the `ComfyUI/custom_nodes/ComfyUI-Manager` path. If you had installed it by downloading a zip file, consider removing it and reinstalling using the method guided in the installation instruction.

https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#installation
