### ISSUE TITLE
Can't find MMDet nodes even after following installation.

### ISSUE THREAD

**Issue by VioletRaven** [ltdrdata/ComfyUI-Impact-Pack#378]
I have done the normal installation but I can't find the MMDet nodes, do you have any suggestion?

Thanks :)

**Comment by ltdrdata** [comment]
Don't use it anymore. Use ultralytics nodes intead of MMDet nods.
https://www.youtube.com/watch?v=t-JjsEvPX7o

**Comment by VioletRaven** [comment]
Thank you very much! I'll try it out asap.
