### ISSUE TITLE
Detailer error when -fp8 mode is enabled in ComfyUI

### ISSUE THREAD

**Issue by LuLmaster69** [ltdrdata/ComfyUI-Impact-Pack#379]
Recently, after updating through ComfyUI Manager I started to experience the following error which appears during the Detailer stage of generation with -fp8 mode is enabled in ComfyUI (previously before the update I could use the Detailer with -fp8 mode).

> ERROR:root:!!! Exception during processing !!!
> ERROR:root:Traceback (most recent call last):
>   File "D:\SD\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\SD\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\SD\ai\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\SD\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 273, in doit
>     DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps,
>   File "D:\SD\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 240, in do_detail
>     tensor_paste(image, enhanced_image, (seg.crop_region[0], seg.crop_region[1]), mask)
>   File "D:\SD\ai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 167, in tensor_paste
>     mask * image2[:, :h, :w, :]
>     ~~~~~^~~~~~~~~~~~~~~~~~~~~~
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by MaxTran96** [comment]
i'm getting the same error. This is what i found so far https://github.com/comfyanonymous/ComfyUI/issues/2284

**Comment by ltdrdata** [comment]
I've tried all the fp8 options, and there doesn't seem to be any issue. Please provide your exact execution options and workflow.

Also, please verify whether the issue persists when you remove the fp8 option.

**Comment by LuLmaster69** [comment]
I have made a simple workflow from zero to test the detailer node for use with -fp8

I am using the ComfyUI with the following command in run_nvidia_gpu.bat file:
.\python_embeded\python.exe -s ComfyUI\main.py --gpu-only --windows-standalone-build --fp8_e4m3fn-text-enc --fp8_e4m3fn-unet

The issue does not persist on this workflow when I remove the fp8 commands from the .bat file
![1](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/145214785/d0fcc8be-5344-4011-8893-168a0bc6cd28)

**Comment by ltdrdata** [comment]
Issue confirmed.

**Comment by ltdrdata** [comment]
The issue came from `--gpu-only`

**Comment by ltdrdata** [comment]
Fixed on V4.48.3
