### ISSUE TITLE
[BUG?] Control Bridge not blocking input

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#383]
It is possible I've misunderstood the way the `Control Bridge` node works. If so, apologies in advance.

I have the following situation:

<img width="885" alt="Screenshot 2023-12-19 at 11 07 39" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/e3da9247-111c-42d7-988c-f6ce259d64b8">

In this situation, as soon as the queue is executed, the `Control Bridge` node mutes the rgthree `Reroute` node to its right, and I would expect that the `MaskPreview+` node (and the `Apply IPAdapter` node) wouldn't receive anything. Which is my intended behavior.

Instead, as you can see, the mask is passed to both nodes.

So, am I doing something wrong, or is the node not doing its job? Thank you!

**Comment by ltdrdata** [comment]
It is recommended not to use the reroute of rgthree. The nodes of rgthree create virtual nodes that do not exist at the time the workflow is executed and use them. The control bridge will not be able to recognize these nodes correctly.

**Comment by alessandroperilli** [comment]
I replaced the rgthree reroute with the default reroute node, but the mask still passes through:

<img width="796" alt="Screenshot 2023-12-19 at 14 28 31" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/c7433f40-01b0-434d-a249-6daf97a58314">

**Comment by ltdrdata** [comment]
Send me your workflow. I'll take a look it.

**Comment by alessandroperilli** [comment]
I removed everything and now the workflow is just these 4 nodes. And I still see the mask passing through:

<img width="1304" alt="Screenshot 2023-12-20 at 10 02 27" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/196e5a5c-3e9d-475f-b27d-343ffe1a4993">

Workflow:
[ControlBridge.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13725880/ControlBridge.json)

**Comment by ltdrdata** [comment]
Actually, the built-in reroute node is also a virtual node. Therefore, muting that node is ineffective. However, with the update (V4.48.7), if connected to a reroute node, the connected node is now muted instead of the reroute node.

Now, this issue should no longer exist. It's fine to use the reroute in rgthree.

**Comment by alessandroperilli** [comment]
The problem I have is that I really wanted the reroute node to mute, and not the node after it :)

I understand that this is not the right Issue to discuss this, but I'd like to give you context just so you don't think I'm out of my mind:

I want to automate as much as possible the execution of the IPAdapter (visible in the first screenshot of this thread). That means that I would like to have the following behavior:

1. If the reference image is uploaded without a mask defined, proceed just with it.
2. If the reference image is uploaded AND a mask is defined via the Mask Editor, take into account the mask, too.

All of this without touching the input wires into the `IPAdapter` node.

Today, this cannot be done (or at least I couldn't do it) because, if no mask is defined, the LoadImage node passes a 64x64px black square to the IPAdapter. Which, at that point, focuses on nothing instead of focusing on the whole image. Which means that the IPAdapter doesn't do its job at all.

So, I was looking for a way to keep both wires connected but have a mechanism that says something like "If the incoming mask is a 64x64 black square, then focus on the whole image. Else, focus on the defined mask."

Not finding such a mechanism, the next best thing I thought about was to use the Control Bridge node to block access to the `Apply IPAdapter` node mask input. But this new implementation you pushed will not allow it.

I think the best is that I just contact the author of that node and see if he can change the behaviour of the node.

**Comment by ltdrdata** [comment]
> The problem I have is that I really wanted the reroute node to mute, and not the node after it :)
> 
> I understand that this is not the right Issue to discuss this, but I'd like to give you context just so you don't think I'm out of my mind:
> 
> I want to automate as much as possible the execution of the IPAdapter (visible in the first screenshot of this thread). That means that I would like to have the following behavior:
> 
> 1. If the reference image is uploaded without a mask defined, proceed just with it.
> 2. If the reference image is uploaded AND a mask is defined via the Mask Editor, take into account the mask, too.
> 
> All of this without touching the input wires into the `IPAdapter` node.
> 
> Today, this cannot be done (or at least I couldn't do it) because, if no mask is defined, the LoadImage node passes a 64x64px black square to the IPAdapter. Which, at that point, focuses on nothing instead of focusing on the whole image. Which means that the IPAdapter doesn't do its job at all.
> 
> So, I was looking for a way to keep both wires connected but have a mechanism that says something like "If the incoming mask is a 64x64 black square, then focus on the whole image. Else, focus on the defined mask."
> 
> Not finding such a mechanism, the next best thing I thought about was to use the Control Bridge node to block access to the `Apply IPAdapter` node mask input. But this new implementation you pushed will not allow it.
> 
> I think the best is that I just contact the author of that node and see if he can change the behaviour of the node.

If you want to mute the reroute node, use the reroute node in pythongossss; it's an actual node, not a virtual one. There have been talks of removing it soon, but it might be better to discuss usability and try to keep it rather than removing it.

**Comment by alessandroperilli** [comment]
The reroute node in pythongossss solved the problem. This is fantastic. Thank you!
