### ISSUE TITLE
DetailerForEachDebugPipe - error after last updates

### ISSUE THREAD

**Issue by sborys-ai** [ltdrdata/ComfyUI-Impact-Pack#386]
DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384.onnx for pose estimation
DWPose: Caching OpenCV DNN module yolox_l.onnx on cv2.DNN...
DWPose: Caching OpenCV DNN module dw-ll_ucoco_384.onnx on cv2.DNN...
malloc(): invalid size (unsorted)
/usr/bin/bash: line 1: 13806 Aborted                 (core dumped) python3 /mnt/SSD/ComfyUI/main.py

After the latest update, I am getting this error with a server crash in comfyui. What could this be?

**Comment by sborys-ai** [comment]
Update.
I haven't changed anything in the workflow, just did another update of comfyui, the error has changed, now it looks like this:

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384.onnx for pose estimation
DWPose: Caching OpenCV DNN module yolox_l.onnx on cv2.DNN...
DWPose: Caching OpenCV DNN module dw-ll_ucoco_384.onnx on cv2.DNN...
free(): corrupted unsorted chunks
/usr/bin/bash: line 1: 11320 Aborted                 (core dumped) python3 /mnt/SSD/ComfyUI/main.py

I've been using the workflow for two months, there were no changes in it, I can't understand what happened.

**Comment by ltdrdata** [comment]
It seems a package issue. But,  I am not sure what is the exact reason.

First, it is recommended to leave the current environment as it is, install separately in a different path, and test with only the impact pack installed.

If issues persist even with Impact Pack installed independently, it seems necessary to try downgrading the OpenCV package in that Python environment.

**Comment by sborys-ai** [comment]
I fixed this error by updating OpenCV from version 4.8.0.74 to 4.8.1.78.
Thanks!
