### ISSUE TITLE
Feather/Dilation stopped working

### ISSUE THREAD

**Issue by poisenbery** [ltdrdata/ComfyUI-Impact-Pack#387]
Feather on the detailer nodes has stopped working. There are hard seams when I use detailer now
I'm not sure when this happened because I do not update frequently.

Dilation also does not function correctly. It seems to only work if a Crop Factor is specified.

**Comment by poisenbery** [comment]
Reverting to this restores feathering:  [This Commit](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/6626cb67816fcbe2a386edc328f72e47500ad448) 


I'm not an expert, but I ASSUME the bug has something to do with this: https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/6626cb67816fcbe2a386edc328f72e47500ad448

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/f1eb810e-2c93-4857-8777-e1dbf800d885)

Feather is fixed on V4.48.10

**Comment by poisenbery** [comment]
Thanks!
