### ISSUE TITLE
Facedetailer-choose which person/face to inpaint

### ISSUE THREAD

**Issue by ckao10301** [ltdrdata/ComfyUI-Impact-Pack#389]
If I have a photo with multiple people, how can I specify which person I want to inpaint? I'm using facedetailer to mask out a person and change their appearance.

Or is there a different tool you would recommend for this workflow? Here's what I'm trying to do:

1. detect people in an image and output images and masks/segm/bbox of each person separately.
2. Select the person to inpaint by inputting corresponding mask/segm/bbox and output the inpainted image.

I'm running the workflow through api, so I don't think I'd be able to use SEGSpicker, for example because I can only send text or images in the api call.

**Comment by ltdrdata** [comment]
You have to manipulate SEGS directly.

https://youtu.be/9GSQlxZFrLI?feature=shared

https://youtu.be/9ih35D2exMU?feature=shared

**Comment by ckao10301** [comment]
Thanks for the help, your work is amazing!
