### ISSUE TITLE
Tiled Upscalers fail with impact Upscale Loader, 

### ISSUE THREAD

**Issue by Immac** [ltdrdata/ComfyUI-Impact-Pack#391]
Works with other loaders, well namely it works with the WAS loader.

**Comment by Immac** [comment]
Upon further testing, it seems Tiled Upscalers don't like Free U.

**Comment by ltdrdata** [comment]
> Upon further testing, it seems Tiled Upscalers don't like Free U.

FreeU or FreeU Advanced?
AFAIK, FreeU Adv has been broken compatiblity for a while.

**Comment by Immac** [comment]
> > Upon further testing, it seems Tiled Upscalers don't like Free U.
> 
> FreeU or FreeU Advanced? AFAIK, FreeU Adv has been broken compatiblity for a while.

FreeU V2, not sure if that's the Adv one.
