### ISSUE TITLE
FaceDetailer: "cannot select an axis to squeeze out which has size not equal to one"

### ISSUE THREAD

**Issue by x5nder** [ltdrdata/ComfyUI-Impact-Pack#392]
I am hoping someone can help me with an issue. I have a workflow where I am generating an SVD-XT clip from an image. This workflow works fine. I am now trying to add FaceDetailer in-between the VAE Decode and Video Combine, to fix the faces in every frame. However, this is the error that I'm getting:

```
Error occurred when executing FaceDetailer:

cannot select an axis to squeeze out which has size not equal to one

File "C:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 464, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 409, in enhance_face
segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 106, in detect
detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 87, in tensor2pil
return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(0), 0, 255).astype(np.uint8))
```

If I put SaveImage right after the VAE Decode, it returns (as expected) 24 png files in 576x1024. If I input one of these images as source into FaceDetailer, it also works (outputs a png with fixed face). So why is my solution not working?

Screenshot of the relevant nodes:
![Screenshot (1)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/4243542/c368ba73-096e-4e68-9221-acba6dcdc8e1)

Full workflow: [WhatGoesWrongHere.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13753981/WhatGoesWrongHere.json)

**Comment by ltdrdata** [comment]
Originally, FaceDetailer was a node designed without support for batch images, and users were guided to explicitly convert Batch to List for use. However, this limitation has been lifted with the update to V4.50.

However, video detailing through FaceDetailer is still not recommended. You can see warn message, now.
