### ISSUE TITLE
LatentReceiver/Image Receiver/ImpactValueReceiver 

### ISSUE THREAD

**Issue by liulsg** [ltdrdata/ComfyUI-Impact-Pack#397]
Question:
1.These three nodes will run before K sampler is executed
2.Although thumbnails display the most recent information, the output is always the previous information

**Comment by liulsg** [comment]
I don't know why I can't upload screenshots today. I will try to upload screenshots several times.

**Comment by ltdrdata** [comment]
ValueSender doesn't operate within a single workflow execution. The values transmitted through ValueSender act as input for the next workflow execution. This can be applied to create structures like loops.

**Comment by liulsg** [comment]
@ltdrdata 
Dr. LT, hello, would you consider adding a parameter to switch between outputting the last message and the latest message, if you can output the latest message, users can simplify the complex workflow.
For example: I load an image and can use it in different places via image reception without complicated wiring.
The same goes for text and latent.

**Comment by ltdrdata** [comment]
> @ltdrdata 
> Dr. LT, hello, would you consider adding a parameter to switch between outputting the last message and the latest message, if you can output the latest message, users can simplify the complex workflow.
> For example: I load an image and can use it in different places via image reception without complicated wiring.
> The same goes for text and latent.

If that's the purpose, I recommend an extension called "cg-use-everywhere." It's specifically designed for such functionality.

**Comment by liulsg** [comment]
Thank you for taking the time to answer.
