### ISSUE TITLE
Error occur when detailing

### ISSUE THREAD

**Issue by allen9441** [ltdrdata/ComfyUI-Impact-Pack#398]
Error occurred when executing FaceDetailer:

cannot select an axis to squeeze out which has size not equal to one

File "D:\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 464, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 409, in enhance_face
segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 106, in detect
detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 87, in tensor2pil
return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(0), 0, 255).astype(np.uint8))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

![螢幕擷取畫面 2023-12-24 223617](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/72611024/2fddafc9-1d43-4b3b-9e7b-221c947807ed)

**Comment by allen9441** [comment]
And it only occurs when the batch_size isn't set to 1. Is it related to the vram?
I'm using RTX 2080 with 8GB vram.

**Comment by ltdrdata** [comment]
What is your Impact Pack version.
And share me the your workflow.

edit: your Impact Pack is outdated version. Update it to latest version, first.

**Comment by allen9441** [comment]
I'm using ComfyUI-Impact-Pack (V4.48.10), ComfyUI-Impact-Pack (Subpack: V0.3.2)
And the workflow is very messy because I'm new to this
[workflow7.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13762200/workflow7.json)

**Comment by ltdrdata** [comment]
> I'm using ComfyUI-Impact-Pack (V4.48.10), ComfyUI-Impact-Pack (Subpack: V0.3.2) And the workflow is very messy because I'm new to this [workflow7.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13762200/workflow7.json)

Recent version is this.
```
### Loading: ComfyUI-Impact-Pack (V4.51.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
```

**Comment by allen9441** [comment]
I just updated it and another issue occur when dectecting
```
Error occurred when executing BboxDetectorSEGS:

cannot select an axis to squeeze out which has size not equal to one

File "D:\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 87, in doit
segs = bbox_detector.detect(image, threshold, dilation, crop_factor, drop_size, detailer_hook)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 106, in detect
detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 87, in tensor2pil
return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(0), 0, 255).astype(np.uint8))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ltdrdata** [comment]
That was batch problem.

Update to latest version. 
Now, you will get proper error message and guide.
