### ISSUE TITLE
AttributeError: type object 'PromptServer' has no attribute 'instance'

### ISSUE THREAD

**Issue by cesar-riojas** [ltdrdata/ComfyUI-Impact-Pack#4]
Cannot import D:\ComfyUI\ComfyUI\custom_nodes\comfyui-impact-pack.py module for custom nodes: type object 'PromptServer' has no attribute 'instance'

not sure how to fix this

**Comment by ltdrdata** [comment]
> Cannot import D:\ComfyUI\ComfyUI\custom_nodes\comfyui-impact-pack.py module for custom nodes: type object 'PromptServer' has no attribute 'instance'
> 
> not sure how to fix this

Is the latest version of ComfyUI installed on your system?

Can you check if 'server.py' in ComfyUI contains 'PromptServer'?

**Comment by cesar-riojas** [comment]
I updated ComfyUI and that seems to have fixed it, Closing the issue, thanks!
