### ISSUE TITLE
error: When loading the graph, the following node types were not found:

### ISSUE THREAD

**Issue by Appolonius001** [ltdrdata/ComfyUI-Impact-Pack#40]
this is the error that pops up in the center of the comfyui window
> When loading the graph, the following node types were not found:
> Float
> Integer
> Nodes that have failed to load will show as red on the graph.

**Comment by ltdrdata** [comment]
It's not related to Impact Pack.
You should install derfuu math nodes.

https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes
