### ISSUE TITLE
DetailerDebug (SEGS)  vs FaceDetailer, what is their main difference ?

### ISSUE THREAD

**Issue by Erwin11** [ltdrdata/ComfyUI-Impact-Pack#400]
Is the main difference between them are DetailerDebug (SEGS) can do  resize (or crop) detector area for the  image？

**I have watched two tutorials below:**
ComfyUI Impact Pack - Q&A: Detailer Options (guide_size, guide_size_for, crop_factor, force_inpaint)
https://www.youtube.com/watch?v=KvZ8ucBqyqw

ComfyUI-Impact-Pack - Tutorial #2: FaceDetailer
https://www.youtube.com/watch?v=z4JzuuFyr1Y

and download workflow:
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/faceswap.png

I had tried combine FaceDetailer node on that workflow. The result is almost same.

![workflow (4)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/6300501/15d1e597-6ab1-451e-883e-9eafcf1d49e2)

I‘m wonder how to choose them?

**Comment by ltdrdata** [comment]
The `FaceDetailer` node is a simplified node designed to make it easy to apply common patterns for adding details to a face. On the other hand, `DetailerForEach` is used in a structure where the detection and detailing stages are separated. It allows users to directly manipulate SEGS, making it more versatile for general purposes.

DetailerForEach is the fundamental node. The FaceDetailer was added later specifically for beginners.

If you want to implement detailed control that cannot be achieved with `FaceDetailer`, you will need DetailerForEach.

https://www.youtube.com/watch?v=9ih35D2exMU
https://www.youtube.com/watch?v=9GSQlxZFrLI
https://www.youtube.com/watch?v=5SCP9ijDuuA

**Comment by ltdrdata** [comment]
> Is the main difference between them are DetailerDebug (SEGS) can do resize (or crop) detector area for the image？
> 
> **I have watched two tutorials below:** ComfyUI Impact Pack - Q&A: Detailer Options (guide_size, guide_size_for, crop_factor, force_inpaint) https://www.youtube.com/watch?v=KvZ8ucBqyqw
> 
> ComfyUI-Impact-Pack - Tutorial #2: FaceDetailer https://www.youtube.com/watch?v=z4JzuuFyr1Y
> 
> and download workflow: https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/faceswap.png
> 
> I had tried combine FaceDetailer node on that workflow. The result is almost same.

**Comment by Erwin11** [comment]
Get it~ Thanks for your hard work! Very appreciate it
