### ISSUE TITLE
Feature Request: Add Face Swap to Detailer

### ISSUE THREAD

**Issue by ckao10301** [ltdrdata/ComfyUI-Impact-Pack#401]
This way, while detailing the image, we can also choose to swap another face onto the chosen mask. Currently, Reactor doesn't allow choosing the face to be swapped via mask.

**Comment by ltdrdata** [comment]
The Impact Pack focuses on detection and inpainting. While it may draw face regions based on IPAdapter or LoRA, there are no plans to directly support Face swap feature.
