### ISSUE TITLE
How about add MeshGraphormer Hand Refiner to Preprocessor Provider (SEGS)

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#409]
How about add MeshGraphormer Hand Refiner to Preprocessor Provider (SEGS)
I think it will be a better way to fixed hand in your segs workflow
https://www.youtube.com/watch?v=RoWzBo9I0MQ&t=70s

And this is info about Hand Refiner
https://githubfast.com/Fannovel16/comfyui_controlnet_aux
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/d2c122c4-fb5b-4c26-bb22-e63006fa3bd4)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/a55a93f3-0b87-4287-9a57-bd4281d3e850)

**Comment by ltdrdata** [comment]
It is added to Inspire Pack, already.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/meshgraphomer_dwpose_tile-segs-handfix.png

**Comment by xueqing0622** [comment]
Thx, ltdrdata!
