### ISSUE TITLE
ComfyUI-Impact-Pack: FAIL to LOAD

### ISSUE THREAD

**Issue by Piscabo** [ltdrdata/ComfyUI-Impact-Pack#41]
Can't use some UI layouts as it uses the Imapct-Pack nodes. Which fails to load. Can you help, please?
I'm using this standalone ComfyUI:
(https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu118_or_cpu.7z)

9.7 seconds (IMPORT FAILED): A:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

10.8 seconds (IMPORT FAILED): A:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

_Cannot import A:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: Command '['A:\\AI_Files\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'mim', 'install', 'mmcv==2.0.0']' returned non-zero exit status 1._

**Comment by ltdrdata** [comment]
Update both ComfyUI and ComfyUI-Manager, and try uninstalling the Impact Pack and reinstalling it through ComfyUI-Manager. I have recently made improvements to ensure that ComfyUI-Manager works properly on Windows.
