### ISSUE TITLE
Is there any way to use the Detailer node with Tile?

### ISSUE THREAD

**Issue by turinastudio** [ltdrdata/ComfyUI-Impact-Pack#410]
I apologize in advance if this is not the right place to ask this question, but I have been working on a workflow to improve image resolution, and I have been using Ultimate Upscale and Self Attention Guidance. Today it occurred to me that a good way to gain details with each pass would be to use its Detailer node, as it does not modify the composition too much, even with high denoise. However, without being able to use tile it is impossible. I attach an image of my workflow, which is currently published on Civitai.

![Captura de pantalla 2024-01-03 012845](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/76142298/a07f61d4-bcdc-4d57-a5f9-acca6b0afb5c)

[https://civitai.com/articles/3582/ultraupscale-im-sharing-my-workflow-for-upscaling-images-to-over-12k](url)

**Comment by ltdrdata** [comment]
Do you meaning ControlNet Tile? or Tiled KSampler/VAEDecode?

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/8aeed998-8e66-45a7-9319-55460f60615f)

**Comment by turinastudio** [comment]
I was referring to Tiled KSampler/VAEDecode, sorry for not specifying. The idea would be to replace Ultimate SD Upscale and SAG in that workflow with the detailer and some form of tile. And being able to progressively scale the image while the detailer is applied.

**Comment by ltdrdata** [comment]
Are you suggesting treating SEGS as a single tile, dividing the entire image into a kind of SEGS, upscaling each SEGS in the manner of Detailer, inpainting, and then progressively completing the whole image's upscale through composite on the enlarged image, rather than reducing and compositing after upscaling each SEGS separately?

**Comment by turinastudio** [comment]
Exactly, that's what I meant. I don't know how viable it is, but as I told you before, Detailer changes the composition very little and adds a lot of detail to the image, so it occurred to me that it could be the way to do it.

**Comment by ltdrdata** [comment]
It's an interesting idea. I'll give it some thought.

**Comment by turinastudio** [comment]
Thank you so much for taking the time to consider it!

**Comment by ltdrdata** [comment]
![tile](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/bffa82b7-5a80-4038-bd17-f0b6a2a16f37)

I have added an experimentally available `Make Tile SEGS` node.

**Comment by stephantual** [comment]
That was a crazy fast turnaround time. Now i have a 19th upscaler to try out :) thank you!

**Comment by ltdrdata** [comment]
FYI, I just elaborated MakeTileSEGS.

![make-tile-segs](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/262a3f26-02b3-4db6-9ab0-d73967864781)

**Comment by turinastudio** [comment]
This is amazing, thank you so much, it works exactly as I expected!
