### ISSUE TITLE
Intermittent "FaceDetailer" node is experiencing low memory.

### ISSUE THREAD

**Issue by Neytiri7** [ltdrdata/ComfyUI-Impact-Pack#411]
Intermittent "FaceDetailer" node is running out of memory.

I have multiple "FaceDetailer" nodes in use,
The "FaceDetailer" node is experiencing intermittent memory shortages.

For example, if the "FaceDetailer(A)" node progresses normally, the "FaceDetailer(B)" node is running out of memory.

In some cases, it may occur directly on the "FaceDetailer(A)" node during the first creation after the computer boots.  

I tried adding --lowvram --disable-smart-memory, but it's the same.

The graphics driver is 546.33.

Currently, I have the sam loader as the CPU, and I am doing it.
It's slow, so it's a frustrating situation.

`Error occurred when executing FaceDetailer:`

`Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated : 1.57 GiB
Requested : 768.00 MiB
Device limit : 4.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
: 17179869184.00 GiB`

`File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 154, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 84, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 77, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 489, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(`
`^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 429, in enhance_face
sam_mask = core.make_sam_mask(sam_model_opt, segs, image, sam_detection_hint, sam_dilation,`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 501, in make_sam_mask
predictor.set_image(image, "RGB")
File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\segment_anything\predictor.py", line 60, in set_image
self.set_torch_image(input_image_torch, image.shape[:2])
File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)`
`^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\segment_anything\predictor.py", line 89, in set_torch_image
self.features = self.model.image_encoder(input_image)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\segment_anything\modeling\image_encoder.py", line 112, in forward
x = blk(x)`
`^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\segment_anything\modeling\image_encoder.py", line 174, in forward
x = self.attn(x)`
`^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\segment_anything\modeling\image_encoder.py", line 234, in forward
attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\segment_anything\modeling\image_encoder.py", line 358, in add_decomposed_rel_pos
attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]`
`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by ltdrdata** [comment]
if you are using SAMLoader.
Change device_mode to cpu.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/4f277a7d-edb1-4300-ac73-f22938fe079b)

I've encountered an issue where the SAM model, once loaded into VRAM, cannot be unloaded. I am currently exploring potential solutions for this matter.

**Comment by Neytiri7** [comment]
I have no choice but to change it to the CPU and use it.

I'm inquiring because I've been using it well, but there's a sudden problem with insufficient memory.

I look forward to finding a quick solution.

**Comment by ltdrdata** [comment]
I just patched it to ensure proper VRAM release in auto mode. Update and try this.

**Comment by Neytiri7** [comment]
Although the frequency of low-memory messages has decreased, it is not much different from the previous one.

For the time being, I'll have to operate as a CPU.

**Comment by ltdrdata** [comment]
That's another issue. The default smart memory policy of ComfyUI is to keep the model on the CPU unless VRAM becomes insufficient. The model memory space managed by ComfyUI is separate from models like SAM. 

Therefore, if VRAM is already maximally utilized by smart memory management and similar processes in the previous steps, there may be insufficient space for additional SAM models. 

By using "--disable-smart-memory," you can either reserve as much VRAM as possible during regular operation or ensure that the SAM model always stays in VRAM through "Prefer GPU," which should resolve the issue.

**Comment by Neytiri7** [comment]
The --disable-smart-memory entry was already included, and it was previously used well without memory errors.

However, during the recent update, a message was displayed.
There were many people around me who were uncomfortable with the same issue.

So, I'm writing this.

As soon as the first answer was registered, I tried to update it, and when I did it again, I didn't feel much difference.

And, after checking the second answer, I updated it again a while ago, and I definitely checked that the message was not displayed.

I haven't done a lot of tests, but seeing that the memory error I saw right away doesn't work, I think it's been fixed.

Thank you.
If the same problem occurs in the future, we will contact you again.

**Comment by Aleon3** [comment]
I am having the same problem... I have tried various combinations for hours now. Everything worked fine just a couple of days ago. I am testing only previously successful workfows but get the same error on FaceDetailer pipe node. ( no SAM loader )

**Comment by Aleon3** [comment]
Same problem.  Worked fine a few days ago...
