### ISSUE TITLE
No saved workflows. 

### ISSUE THREAD

**Issue by potesd** [ltdrdata/ComfyUI-Impact-Pack#412]
You didn't save the workflow information into the example images for each workflow. Basically you've made it impossible for me to open up and affect changes to any of these workflows. 

Can you please oh please add the workflows as a Json file like a normal human being. or at least embed the workflow into your example images so we can actually use them.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-extension-tutorials/tree/Main/ComfyUI-Impact-Pack/workflow
