### ISSUE TITLE
Refine face with faceid+animatediff in facedetailer

### ISSUE THREAD

**Issue by YacratesWyh** [ltdrdata/ComfyUI-Impact-Pack#413]
Hi, I am trying to use face detailer to fix the small face in sd15, and found that 
1.Animate diff always fails if I input this
2.it would probably leaves some hair artifacts, even when I am not using animatediff
3.controlnet is not actively used from the conditioning used before.
How to use IPA here, and how to fix the artifact？
<img width="195" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8447769/985a6085-7e12-4c0e-b3aa-819b0b8b59db">
[workflow (3).json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13827920/workflow.3.json)

**Comment by YacratesWyh** [comment]
Bypassed all animated model problem still exists, wonder why

**Comment by ltdrdata** [comment]
Do not send prompts with ControlNet applied to the detailer. The detailer applies inpainting to cropped images, and the ControlNet applied to the conditioning provided affects the entire image, causing issues.

https://www.youtube.com/watch?v=RoWzBo9I0MQ

**Comment by YacratesWyh** [comment]
How to use this with animatediff? the face is blinking everwhere and wonder how to solve it.
