### ISSUE TITLE
Mesh Graphormer for Hand Detailer

### ISSUE THREAD

**Issue by alessandroperilli** [ltdrdata/ComfyUI-Impact-Pack#414]
In my Hand Detailer function, I used to use the `DWPreprocessor Provider (SEGS)` node with modest results. 

Now I'm trying to replace it with the new `MeshGraphormer Depth Map Preprocessor Provider (SEGS)` node and the `sd15_inpaint_depth_hand_fp16` model:

<img width="1712" alt="Screenshot 2024-01-04 at 16 41 19" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/9464f0ad-dcb7-4e14-8ef3-1b9df97ff768">

I have two problems:

1. in some cases, malformed hands don't get recognized. Like in this source image:

![Graphormer_00004_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/57fab1f3-3e4c-422d-a8f5-59fd0e2e0075)

2. When they get recognized, the model swaps the right hand for the left hand:

<img width="318" alt="Screenshot 2024-01-04 at 16 41 29" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/ee7aa8c8-70e4-4dc7-b949-09b9c7447143">

The end result, no matter how capable Mesh Graphormer seem to be, is always worse than the one generated by the previous method:

<img width="1189" alt="Screenshot 2024-01-04 at 16 41 47" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9775949/d7dec0d2-af62-4e23-9f9a-76a876218dea">

I'm trying to understand if I'm doing something wrong in terms of configuring the nodes, or if the model has some issues that have nothing to do with the nodes.

Anybody can try my source image with their workflows, please?

Thank you!

**Comment by ltdrdata** [comment]
There are reports indicating that MeshGraphormer does not recognize non-photograph images well. Try adding a step for converting to photorealism and see if it improves.

**Comment by alessandroperilli** [comment]
I'm glad to read that it's not just me. Thank you.
