### ISSUE TITLE
Using SamDetector Results in Image with Poor Mask Boundaries

### ISSUE THREAD

**Issue by ckao10301** [ltdrdata/ComfyUI-Impact-Pack#416]
When I use SamDetector alongside a mask (following your tutorial), the resulting image is not blended well along the outline of the mask. When I use the mask only, the image is ok. I thought SamDetector was supposed to make the mask better. What am I doing wrong? Original mask was created using SegmDetector.

<img width="1022" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/d290ccf9-f06d-44ea-a241-526c69747342">

Mask with SamDetector

<img width="637" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/d47d3d2f-93a1-4e93-b50c-d812a71b2229">

Mask Only

<img width="631" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/c9b08dd6-9ac1-4649-9c5e-c624f4d6a6b1">

**Comment by ltdrdata** [comment]
SAM generally produces decent silhouettes, but it's not perfect (especially, hair part is very complex), and the results may vary depending on the model used. If you're aiming for very precise silhouettes, you might need to use a more sophisticated model. Try lowering the threshold or increasing dilation to experiment with the results.

**Comment by ckao10301** [comment]
Sure, I'll try changing the dilation. What do you mean by "more sophisticated model"- a different SAM model? What would you recommend? This is what I'm currently using for SAM and Segm.

<img width="233" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/5c2a9202-acf1-4f8e-96b8-1333a4710378">

<img width="185" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/c8875e80-b9cc-409a-bb3f-ba794e209af6">

**Comment by ckao10301** [comment]
I adjusted dilation and it fixed the issue.
