### ISSUE TITLE
Last commit f6ec3a8 caused SEGM Detector (SEGS) to not work properly.

### ISSUE THREAD

**Issue by MoYiha** [ltdrdata/ComfyUI-Impact-Pack#417]
![Snipaste_2024-01-07_11-09-38](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/146310147/02d3a20e-8359-405d-885a-28611c9ea7ac)

**4aec82b**

![Snipaste_2024-01-07_11-12-50](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/146310147/83688874-63d1-4b34-8dd8-8edf2f0ad449)

**f6ec3a8**

**Comment by ltdrdata** [comment]
oops... it's a bug of SEGSPreview. This is patched in V4.60.2
