### ISSUE TITLE
Wildcard Processor - Convert seed to input does not work

### ISSUE THREAD

**Issue by vtoaster** [ltdrdata/ComfyUI-Impact-Pack#420]
When I convert seed to input on the Wildcard Processor node, it does not seem to use the input seed. (I used rgthree seed node)
It still kicks off a generation as if the node changed, but no wildcards are processed.

Steps to reproduce:
1) create new Wildcard Processor node, 
2) add in some wildcards in the wildcard prompt
3) convert seed to input
4) connect to seed generation node (like rgthree seed node)
5) queue prompt
6) issue: nothing is generated in populated prompt area

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/325
