### ISSUE TITLE
Issue with installing, missing "UltralyticsDetectorProvider", nothing helps.

### ISSUE THREAD

**Issue by olegpars** [ltdrdata/ComfyUI-Impact-Pack#421]
Hi! 

I have an issue for more than one month - while loading some workflows in ComfyUI i get an error: 
"When loading the graph, the following node types were not found: UltralyticsDetectorProvider"

I have tried uninstalling and installing back (through comfyui manager), updating comfyui on each step - after unisntalling and after installing again. Nothing helps - i still get this error for more than a month. 

Would be very gratefull if someone points me a solution to this, thanks!

**Comment by ltdrdata** [comment]
show me the `comfyui.log`

**Comment by olegpars** [comment]
Sure! Here are 3 logs:
comfyui.prev2.log - after getting error, clicked unisntall in comfyui manager
comfyui.prev.log - restarted and opened comfyui and clicked "install" in comfyui manager 
comfyui.log - after reinstalling impact pack through comfyui manager

[comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13864464/comfyui.log)
[comfyui.prev.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13864465/comfyui.prev.log)
[comfyui.prev2.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/13864466/comfyui.prev2.log)

**Comment by ltdrdata** [comment]
You can see this message on log.
```
[WARN] ComfyUI-Impact-Pack: `ComfyUI` or `ComfyUI-Manager` is an outdated version.
[Impact Pack] Wildcards loading done.
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
	https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

```

Your ComfyUI-Manager is outdated.
