### ISSUE TITLE
Could I join u ？

### ISSUE THREAD

**Issue by JcandZero** [ltdrdata/ComfyUI-Impact-Pack#424]
I wanna be a node developer，So i urge to join your group to work together

**Comment by ltdrdata** [comment]
You can PR anytime.

**Comment by JcandZero** [comment]
So，how can i contact you？Dr.Lt.Data

**Comment by ltdrdata** [comment]
> So，how can i contact you？Dr.Lt.Data

I am sticking with the official elements of ComfyUI.

https://app.element.io/#/room/%23comfyui_space%3Amatrix.org

 Just to note, I'm not organizing a team and working with others. I am just an individual developer.
