### ISSUE TITLE
ControlNetApply (SEGS) with premade map image

### ISSUE THREAD

**Issue by rbbdz** [ltdrdata/ComfyUI-Impact-Pack#429]
I want to use my premade controlnet maps in ControlNetApply (SEGS) node, like in regular ControlNetApply. Is there a way to connect an image? Or is it possible to add this ability? This would be very helpful
![Screenshot_1](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/135645107/52bb88b2-3260-45af-b793-e65b52cc9d4e)

**Comment by ltdrdata** [comment]
I have already made plans for this part.

**Comment by rbbdz** [comment]
great! Thank you

**Comment by ltdrdata** [comment]
> great! Thank you

Implemented in V4.63. However, I haven't been able to test it yet due to the current untestable environment. Please check if there are any issues.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/35927487-6309-487c-b0e3-5441d421f60a)

**Comment by rbbdz** [comment]
Yes! Just checked, it works amazing, thank you!
