### ISSUE TITLE
Re download sam_vit_b_01ec64.pth when update

### ISSUE THREAD

**Issue by ArthusLiang** [ltdrdata/ComfyUI-Impact-Pack#430]
I setup the extra_model_paths.yaml to reuse sam models in sd-webui. It works well. But When I update Impact-Pack, it will only detect the folder under comfyui and download sam_vit_b_01ec64.pth again.
By the way the fold name in  Impact-Pack is 'sams', but its name is 'sam' in stable-diffusion segment anything extension.

**Comment by ltdrdata** [comment]
If you create a `skip_download_model` file in the `ComfyUI/custom_nodes` directory, it will prevent downloading the model.
