### ISSUE TITLE
FaceDetailer: noise_mask disabled - TypeError: expected np.ndarray (got NoneType)

### ISSUE THREAD

**Issue by Yaeph** [ltdrdata/ComfyUI-Impact-Pack#431]
After I updated_all comfyUI the FaceDetailer node in my workflow starts giving me an error https://i.imgur.com/mRmm4VX.png
it only appears when noise_mask is disabled.
![1E0dX44](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/141271455/25e3f5fc-6b91-45d8-9445-5fdc049c19d4)

**Comment by ltdrdata** [comment]
This is fixed on V4.64.1
