### ISSUE TITLE
ImpactWildcardProcessor when seed converted to input, does not populate

### ISSUE THREAD

**Issue by ricperry** [ltdrdata/ComfyUI-Impact-Pack#432]
I like to control seed randomization or selection from a different node. Particularly I like rgthree's version of seed that allows me to generate a fixed random seed, generate new seeds each time, or use the last random seed. Using the last random seed is very important when I get great results early in the workflow, but then the results get worse at some point. I'd like to keep everything up until the point my workflow goes awry, but I need the seed that was being used, and rgthree's node fits the bill. But when I'm using ImpactWildcards, the seed can connect, but the wildcards aren't processed and the text is static, even when Populate is enabled.

**Comment by ltdrdata** [comment]
It was a limitation. 

However, it has been confirmed that the structure of the `seed (rgthree)` is not problematic, so I have expanded the supported input.

**Comment by tazztone** [comment]
it looks like it still doesn't support external seed input? pretty sure it didn't also before the new comfyui frontend update.


![Image](https://github.com/user-attachments/assets/e9d82840-ebed-497d-9737-c5963252e305)

![Image](https://github.com/user-attachments/assets/3ad511a7-81f5-45d7-ae20-5bc835bf1165)

![Image](https://github.com/user-attachments/assets/d33c9fe9-b0af-45b8-96de-dc39e88a05bd)
as you can see it doesn't use seed 1 from external node 
1= lily, 2= iris

**Comment by ltdrdata** [comment]
> it looks like it still doesn't support external seed input? pretty sure it didn't also before the new comfyui frontend update.
> 
> 
> ![Image](https://github.com/user-attachments/assets/e9d82840-ebed-497d-9737-c5963252e305)
> 
> ![Image](https://github.com/user-attachments/assets/3ad511a7-81f5-45d7-ae20-5bc835bf1165)
> 
> ![Image](https://github.com/user-attachments/assets/d33c9fe9-b0af-45b8-96de-dc39e88a05bd)
> as you can see it doesn't use seed 1 from external node 
> 1= lily, 2= iris 
> 

If you want to use the `seed` as an external input, you need to set the mode to `fixed` and provide the input as `populated_text` instead of `wildcard_text`.
