### ISSUE TITLE
Out of screen Wildcard Listing

### ISSUE THREAD

**Issue by Piscabo** [ltdrdata/ComfyUI-Impact-Pack#434]
I don't zoom out quite far the list is unusable and out of the screen?
This is zoomed out far:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/123719842/e54a8bc9-f0eb-4fe7-a05e-740d182ea81b)

**Comment by ltdrdata** [comment]
That is a current limitation of the default UI in ComfyUI. Try narrowing it down using keyword searches.
