### ISSUE TITLE
denoise scheluder never reach target (solution proposed)

### ISSUE THREAD

**Issue by yoda5477** [ltdrdata/ComfyUI-Impact-Pack#442]
When using cycle in detailer with a sheduler for denoise, cur_step goes from 0 to total-1 so current progress would do for total = 3:
0/3=0 (initial), 1/3=0.33, 2/3=0.66 => never reaching the target

So guess should use total-1 instead, after checking if total>1 else simply use target directly.
It would then do with same example :
0/2=0 (inital), 1/2=0.5, 2/2=1 (target reached)

----------------------------------------------
class SimpleDetailerDenoiseSchedulerHook(DetailerHook):
    def __init__(self, target_denoise):
        super().__init__()
        self.target_denoise = target_denoise

    def pre_ksample(self, model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent, denoise):
        progress = self.cur_step / self.total_step
        gap = self.target_denoise - denoise
        current_denoise = denoise + gap * progress
        return model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent, current_denoise

**Comment by ltdrdata** [comment]
This is fixed.
