### ISSUE TITLE
Use FaceDetailer，Large shadows appear on the face after cultivation

### ISSUE THREAD

**Issue by sebord** [ltdrdata/ComfyUI-Impact-Pack#443]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/104607562/92dc0e93-c976-459f-82d8-84c541cb354e)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/104607562/e1f374a6-0aad-4704-b07a-43c47cfaa552)

**Comment by ltdrdata** [comment]
Don't connect controlnet applied positive.
The controlnet conditioning represent total image. But detailed image is cropped part of the image.

**Comment by sebord** [comment]
thanks
