### ISSUE TITLE
`ImpactConditionalBranch` with `sel_mode:select_on_prompt` function

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#447]
Please add another `ImpactConditionalBranch` with `sel_mode:select_on_prompt` functionality.
This function is very useful for `ImpactConditionalBranch`. I hope that the other `ImpactConditionalBranch` will still remain simple and not display `sel_mode`
thank you very much!

**Comment by ltdrdata** [comment]
Are you requesting new variation node of ImpactConditionalBranch?

**Comment by mijuku233** [comment]
> Are you requesting new variation node of ImpactConditionalBranch?

Yes, this `sel_mode:select_on_prompt` feature is great, I wish there was a variant version of `ImpactConditionalBranch` with this feature

**Comment by ltdrdata** [comment]
ImpactConditionalBranchSelMode is added.
