### ISSUE TITLE
 Padding size should be less than the corresponding input dimension

### ISSUE THREAD

**Issue by arcanique** [ltdrdata/ComfyUI-Impact-Pack#451]
I received the following error in comfyui, but it did not affect the workflow. I would like to know what caused it and whether it affected the running results. 
`[2024-01-25 17:18] ERROR:root:Traceback (most recent call last):
1968   File "/opt/tiger/ComfyUI/execution.py", line 154, in recursive_execute
1969     output_data, output_ui = get_output_data(obj, input_data_all)
1970   File "/opt/tiger/ComfyUI/execution.py", line 84, in get_output_data
1971     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
1972   File "/opt/tiger/ComfyUI/execution.py", line 77, in map_node_over_list
1973     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
1974   File "/opt/tiger/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 489, in doit
1975     enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
1976   File "/opt/tiger/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 446, in enhance_face
1977     DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
1978   File "/opt/tiger/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 220, in do_detail
1979     mask = tensor_gaussian_blur_mask(mask, feather)
1980   File "/opt/tiger/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/utils.py", line 356, in tensor_gaussian_blur_mask
1981     blurred_mask = torchvision.transforms.GaussianBlur(kernel_size=kernel_size*2+1, sigma=sigma)(mask)
1982   File "/opt/python-3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
1983     return forward_call(*args, **kwargs)
1984   File "/opt/python-3.10.11/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 1819, in forward
1985     return F.gaussian_blur(img, self.kernel_size, [sigma, sigma])
1986   File "/opt/python-3.10.11/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 1386, in gaussian_blur
1987     output = F_t.gaussian_blur(t_img, kernel_size, sigma)
1988   File "/opt/python-3.10.11/lib/python3.10/site-packages/torchvision/transforms/_functional_tensor.py", line 760, in gaussian_blur
1989     img = torch_pad(img, padding, mode="reflect")
1990 RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (20, 20) at dimension 3 of input 4`

**Comment by ltdrdata** [comment]
This is fixed.
It was caused by too small SEGS.
