### ISSUE TITLE
ImpactWildcardProcessor not processing a string input?

### ISSUE THREAD

**Issue by Puddz** [ltdrdata/ComfyUI-Impact-Pack#454]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/1914381/5232f7b8-18cc-4f47-83fe-baa4f7cf8387)

As title says. When you convert he wildcard prompt to an input, it doesn't work. This picture was after hitting queue prompt and nothing happened to the bottom one. 

Console logs:
[WARN] ComfyUI-Impact-Pack: Error on prompt - several features will not work.
expected string or bytes-like object, got 'list'
[rgthree] Using rgthree's optimized recursive execution.
Prompt executed in 0.00 seconds

EDIT: Should have searched. Can use a primitive node to do the same thing. But still would be nice if possible to just use strings. Can close if you want.

**Comment by ltdrdata** [comment]
The ImpactWildcardProcessor cannot accept the execution result of the node as input because it needs to be determined before the workflow is executed, for the purpose of saving prompts to the workflow.
