### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mayjack0312** [ltdrdata/ComfyUI-Impact-Pack#455]
module 'cv2' has no attribute 'setNumThreads'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['D:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
[Impact Pack] Wildcards loading done.
module 'cv2' has no attribute 'setNumThreads'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 470, in <module>
    import impact.subpack_nodes
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in <module>
    raise e
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in <module>
    from ultralytics import YOLO
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\data\__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\data\base.py", line 17, in <module>
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 103, in <module>
    cv2.setNumThreads(0)  # prevent OpenCV from multithreading (incompatible with PyTorch DataLoader)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2' has no attribute 'setNumThreads'

**Comment by ltdrdata** [comment]
uninstall opencv-python, opencv-python-headless, opencv-contrib-python from your comfyui pip environment.

And restart.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting%2FTROUBLESHOOTING.md#an-issue-has-occurred-about-cv2

**Comment by mayjack0312** [comment]
> uninstall opencv-python, opencv-python-headless, opencv-contrib-python from your comfyui pip environment.
> 
> And restart.
> 
> https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting%2FTROUBLESHOOTING.md#an-issue-has-occurred-about-cv2

I tried this method, but unfortunately, it's still throwing errors.
```
.\python_embeded\python.exe -m pip install -U opencv-python opencv-python-headless
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: opencv-python in d:\comfyui_windows_portable\python_embeded\lib\site-packages (4.9.0.80)
Requirement already satisfied: opencv-python-headless in d:\comfyui_windows_portable\python_embeded\lib\site-packages (4.7.0.72)
Collecting opencv-python-headless
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/20/44/458a0a135866f5e08266566b32ad9a182a7a059a894effe6c41a9c841ff1/opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-python) (1.24.4)
Installing collected packages: opencv-python-headless
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.7.0.72
    Uninstalling opencv-python-headless-4.7.0.72:
      Successfully uninstalled opencv-python-headless-4.7.0.72
Successfully installed opencv-python-headless-4.9.0.80
🚀 .\python_embeded\python.exe -m pip install -U opencv-python==4.6.0.66 opencv-python-headless==4.6.0.66
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting opencv-python==4.6.0.66
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/cf/09/b24c266cd61ddeed101b90c92a26f54d060b06f4a1b102eb891576d6e9e2/opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl (35.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.6/35.6 MB 10.7 MB/s eta 0:00:00
Collecting opencv-python-headless==4.6.0.66
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/f9/b9b1c22bbfd66cb26d75ca0780cc26bb946466fbe62f262b024f39278ec6/opencv_python_headless-4.6.0.66-cp36-abi3-win_amd64.whl (35.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.5/35.5 MB 10.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-python==4.6.0.66) (1.24.4)
Installing collected packages: opencv-python-headless, opencv-python
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.9.0.80
    Uninstalling opencv-python-headless-4.9.0.80:
      Successfully uninstalled opencv-python-headless-4.9.0.80
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.9.0.80
    Uninstalling opencv-python-4.9.0.80:
      Successfully uninstalled opencv-python-4.9.0.80
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
simple-lama-inpainting 0.1.2 requires opencv-python<5.0.0.0,>=4.8.0.74, but you have opencv-python 4.6.0.66 which is incompatible.
Successfully installed opencv-python-4.6.0.66 opencv-python-headless-4.6.0.66
```

**Comment by mayjack0312** [comment]
> uninstall opencv-python, opencv-python-headless, opencv-contrib-python from your comfyui pip environment.
> 
> And restart.
> 
> https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting%2FTROUBLESHOOTING.md#an-issue-has-occurred-about-cv2

Awesome, this method works for me! But the console still prompts some errors.
I can now use the plugin properly. Thank you for your response.
```
.\python_embeded\python.exe -m pip install -U opencv-python opencv-python-headless
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: opencv-python in d:\comfyui_windows_portable\python_embeded\lib\site-packages (4.9.0.80)
Requirement already satisfied: opencv-python-headless in d:\comfyui_windows_portable\python_embeded\lib\site-packages (4.7.0.72)
Collecting opencv-python-headless
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/20/44/458a0a135866f5e08266566b32ad9a182a7a059a894effe6c41a9c841ff1/opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-python) (1.24.4)
Installing collected packages: opencv-python-headless
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.7.0.72
    Uninstalling opencv-python-headless-4.7.0.72:
      Successfully uninstalled opencv-python-headless-4.7.0.72
Successfully installed opencv-python-headless-4.9.0.80
🚀 .\python_embeded\python.exe -m pip install -U opencv-python==4.6.0.66 opencv-python-headless==4.6.0.66
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting opencv-python==4.6.0.66
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/cf/09/b24c266cd61ddeed101b90c92a26f54d060b06f4a1b102eb891576d6e9e2/opencv_python-4.6.0.66-cp36-abi3-win_amd64.whl (35.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.6/35.6 MB 10.7 MB/s eta 0:00:00
Collecting opencv-python-headless==4.6.0.66
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6a/f9/b9b1c22bbfd66cb26d75ca0780cc26bb946466fbe62f262b024f39278ec6/opencv_python_headless-4.6.0.66-cp36-abi3-win_amd64.whl (35.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.5/35.5 MB 10.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-python==4.6.0.66) (1.24.4)
Installing collected packages: opencv-python-headless, opencv-python
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.9.0.80
    Uninstalling opencv-python-headless-4.9.0.80:
      Successfully uninstalled opencv-python-headless-4.9.0.80
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.9.0.80
    Uninstalling opencv-python-4.9.0.80:
      Successfully uninstalled opencv-python-4.9.0.80
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
simple-lama-inpainting 0.1.2 requires opencv-python<5.0.0.0,>=4.8.0.74, but you have opencv-python 4.6.0.66 which is incompatible.
Successfully installed opencv-python-4.6.0.66 opencv-python-headless-4.6.0.66
```

**Comment by ltdrdata** [comment]
Try this.
```
.\python_embeded\python.exe -m pip install -U opencv-python opencv-python-headless simple-lama-inpainting==0.1.2
```

**Comment by mayjack0312** [comment]
> Try this.
> 
> ```
> .\python_embeded\python.exe -m pip install -U opencv-python opencv-python-headless simple-lama-inpainting==0.1.2
> ```

I tried it this morning and it works normally. I don’t know what caused this problem at the moment. Thank you very much.
