### ISSUE TITLE
I'm rubbing chicken guts all over my walls and the wildcards aren't working 

### ISSUE THREAD

**Issue by kronkinatorix** [ltdrdata/ComfyUI-Impact-Pack#46]
That's how this works, right? There's no documentation so I just assumed. Does it need to be human guts? Or maybe I need to beseech zeus for his favor?

**Comment by ltdrdata** [comment]
My mistake, indeed. Wildcards were already a widely used feature, so I didn't consider it for new users. I'll write about that feature.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcardProcessor.md

Now I added tutorial for this.
The wildcard feature for FaceDetailer is planned to be implemented in the future.

**Comment by octoworld** [comment]
thanks for the tutorial. were do i find the CLIPtextencode node that has clip & text input (I promise i've looked and looked).

**Comment by octoworld** [comment]
^^ IGNORE. found this on the YT vid:
right click on clip text encode. and select "convert text to input". That is universal feature on ComfyUI.
