### ISSUE TITLE
Error Executing Gaussian Blur Mask

### ISSUE THREAD

**Issue by ckao10301** [ltdrdata/ComfyUI-Impact-Pack#462]
I'm trying to apply blur to mask. I get an error if I use the gaussian blur node right after the Mask Erode node. It works ok if I use it directly after the Load Mask node though.

Also, is there documentation on what does kernel size and sigma mean?

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/b735a8df-a6f0-494c-99a0-0a1d9a5c7493)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129625358/df164b4d-3ebe-40db-a2b4-2c64663dab1f)

**Comment by ltdrdata** [comment]
In the WAS node, abnormal 4-dimensional masks are used, causing compatibility issues with mask operations. 
Anyway I just applied robustness patch, it's worth noting that in the Impact Pack, erosion can be achieved through negative values in the dilation mask.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/7463a937-bcfe-4bad-95ea-5de620563881)

Kernel size and sigma are typical parameters for Gaussian blur.

https://digitalbunker.dev/understanding-gaussian-blurs/

**Comment by ckao10301** [comment]
Thanks, I changed the node to your dilate mask node just to ensure future compatibility. I didn't realize it could achieve erosion. Would it be a good idea to rename it to "Dilate/Erode Mask" for clarity?

Thanks for the explanation on the parameters.
