### ISSUE TITLE
FaceDetailer is skipping the detailing if image is too big

### ISSUE THREAD

**Issue by agawrylak** [ltdrdata/ComfyUI-Impact-Pack#464]
I'm using 512x512 upscaled three times. When trying to facedetail, with mask set with guide size 256 nothing happens. Only when I increase guide size to 1100+ the facedetailer starts to work. 

> guide_size: This feature attempt detail recovery only when the size of the detected mask is smaller than this value. If the size is larger, this feature increase the resolution and attempt detail recovery.

Guide size description suggests that in both cases (guide size < value || guide size > value) facedetailer will attempt to work.

**Comment by agawrylak** [comment]
any tips for fixing upscaled images with ipadapter +facedetailer combo?

**Comment by ltdrdata** [comment]
https://youtu.be/KvZ8ucBqyqw?feature=shared

Just set force_inpaint.

**Comment by agawrylak** [comment]
@ltdrdata but force impaint gives a different result
