### ISSUE TITLE
(NOT A BUG) Can clipseg model loader load something else than CIDAS/clipseg_64rb_refined and if so which one?

### ISSUE THREAD

**Issue by stephantual** [ltdrdata/ComfyUI-Impact-Pack#465]
CIDAS/clipseg_64rb_refined is great but a year old, noisy and not that accurate. I was wondering if there were alternatives that could be loaded using clipseg_model_loader given there's an input to chooes a model for the clipseg node?

Thank you!

**Comment by ltdrdata** [comment]
Unfortunately, CLIPSeg technology is limited to its initial release, and there have been no subsequent improved models. Instead, the masks obtained with CLIPSeg can be complemented using SAM.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/261261ae-084a-4466-b17e-66610cc0954e)

**Comment by stephantual** [comment]
Thank you very much! Good to have that certainty!
