### ISSUE TITLE
Move ConcatConditionings to Utils

### ISSUE THREAD

**Issue by jojorne** [ltdrdata/ComfyUI-Impact-Pack#467]
Why not move it to the same category as CombineConditionings?
I tested it and it produced the same result as vanilla nodes stacked together.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/3fdede4e90f296069f31b9a6b9f512558d63a9d3/modules/impact/special_samplers.py#L254
```python
CATEGORY = "ImpactPack/Util"
```

**Comment by ltdrdata** [comment]
This is modified.
