### ISSUE TITLE
Add support for YOLO-World

### ISSUE THREAD

**Issue by hben35096** [ltdrdata/ComfyUI-Impact-Pack#468]
https://github.com/AILab-CVC/YOLO-World
https://huggingface.co/spaces/stevengrove/YOLO-World
YOLO-World supports more type detection, which seems to be unlimited.
Moreover, it is not limited to a specific vocabulary.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/9924c70f-be6d-45ff-85ef-3c34b66dfdb5)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139383150/bc9edee2-5dae-48a2-8e39-a1fec8a6bbef)

**Comment by ltdrdata** [comment]
This seems very promising.

**Comment by ltdrdata** [comment]
Oh, but it seems like there is a dependency on the mmdet package. It seems more appropriate to go with a separate extension rather than including it in the Impact Pack.

**Comment by stephantual** [comment]
Ooh I'd love to see where this goes. Looks very cool indeed!

**Comment by ltdrdata** [comment]
Take a look at this:
https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/032fda03-5969-4c47-aabd-bfb08fb25a3d)

This requires pretty low confidence threshold in my experiene.

You need to install efficient_sam models through Install models in Manager.

I am willing to SEGS Detector based on yoloworld.

**Comment by stephantual** [comment]
Here goes my cicadian rythms again 😄

**Comment by ltdrdata** [comment]
I just submit PR.

https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/pull/3

**Comment by ltdrdata** [comment]
My PR is merged.

**Comment by rossaai** [comment]
@ltdrdata Is there a way to filter the segments (SEGS) by confidence? Because when you set it to 0.00, it gives you false positives, and when you set it to 0.01, it gives you false negatives. So my idea is that the segments (SEGS) from the SEGM Detector can later be filtered with a higher threshold, for example, 0.10.

<img width="603" alt="Captura de pantalla 2024-06-03 a la(s) 9 11 37 p m" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132106533/a8fa8885-ec80-4eac-9a11-010aada2b05d">

**Comment by ltdrdata** [comment]
> @ltdrdata Is there a way to filter the segments (SEGS) by confidence? Because when you set it to 0.00, it gives you false positives, and when you set it to 0.01, it gives you false negatives. So my idea is that the segments (SEGS) from the SEGM Detector can later be filtered with a higher threshold, for example, 0.10.
> 
> <img alt="Captura de pantalla 2024-06-03 a la(s) 9 11 37 p m" width="603" src="https://private-user-images.githubusercontent.com/132106533/336291808-a8fa8885-ec80-4eac-9a11-010aada2b05d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MDgzODAsIm5iZiI6MTcxNzUwODA4MCwicGF0aCI6Ii8xMzIxMDY1MzMvMzM2MjkxODA4LWE4ZmE4ODg1LWVjODAtNGVhYy05YTExLTAxMGFhZGEyYjA1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMzM0NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDU3MjcwYzQzYjc5MTNlY2JmMmRhYzY0MDczM2E2YTEyMzA5M2I5NTljODdkZWE2YmVhN2Y5Y2EwMzM0MWMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xDSSBsdgKG-btOQgqrwKcJa-tA0GUrXz15gjRQZBdvA">

![workflow (14)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/fb8489ab-944d-41b2-bee7-f124b90fb3f1)

**Comment by rossaai** [comment]
@ltdrdata thank you so much. This change performs so well. I only needed to update Impact Pack
<img width="620" alt="Captura de pantalla 2024-06-04 a la(s) 8 12 42 a m" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132106533/c3b335d0-c5fe-4b7d-8999-15405a501654">

**Comment by rossaai** [comment]
@ltdrdata is there a way to SAM Segment by box instead of points? This method is more efficient because It doesn't need to segment false positives

<img width="963" alt="Captura de pantalla 2024-06-04 a la(s) 8 30 32 a m" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132106533/cbe8d83b-519c-4794-9996-3f95e52176c5">

**Comment by ltdrdata** [comment]
> @ltdrdata is there a way to SAM Segment by box instead of points? This method is more efficient because It doesn't need to segment false positives
> 
> <img alt="Captura de pantalla 2024-06-04 a la(s) 8 30 32 a m" width="963" src="https://private-user-images.githubusercontent.com/132106533/336491933-cbe8d83b-519c-4794-9996-3f95e52176c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MTE5MDMsIm5iZiI6MTcxNzUxMTYwMywicGF0aCI6Ii8xMzIxMDY1MzMvMzM2NDkxOTMzLWNiZThkODNiLTUxOWMtNDc5NC05OTk2LTNmOTVlNTIxNzZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxNDMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGUxZjYzMTQ1MGMzZTcyNTI2ZmM1ZDFmYWU4ZjMwMjhjOWExZjIyMTc5NTJmMzhhOGYyMzZhOGNiYzk0MDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VUS904ydfotf5Z7_SuKDB-HaMI1vSrT0QWf0avULoCY">

If you are using the yoloworld node, use the `Simple Detector` instead of the `BBOX Detector`, and connect both `BBOX` and `SEGM`.

**Comment by rossaai** [comment]
> > @ltdrdata is there a way to SAM Segment by box instead of points? This method is more efficient because It doesn't need to segment false positives
> > <img alt="Captura de pantalla 2024-06-04 a la(s) 8 30 32 a m" width="963" src="https://private-user-images.githubusercontent.com/132106533/336491933-cbe8d83b-519c-4794-9996-3f95e52176c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MTE5MDMsIm5iZiI6MTcxNzUxMTYwMywicGF0aCI6Ii8xMzIxMDY1MzMvMzM2NDkxOTMzLWNiZThkODNiLTUxOWMtNDc5NC05OTk2LTNmOTVlNTIxNzZjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxNDMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGUxZjYzMTQ1MGMzZTcyNTI2ZmM1ZDFmYWU4ZjMwMjhjOWExZjIyMTc5NTJmMzhhOGYyMzZhOGNiYzk0MDgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VUS904ydfotf5Z7_SuKDB-HaMI1vSrT0QWf0avULoCY">
> 
> If you are using the yoloworld node, use the `Simple Detector` instead of the `BBOX Detector`, and connect both `BBOX` and `SEGM`.

The issue when using Simple Detector (SEGS) is that segments things that are not correct, so this decreases performance because it segments all and after filters them

<img width="1070" alt="Captura de pantalla 2024-06-04 a la(s) 8 51 22 a m" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132106533/f64c0d04-883b-4305-abdc-3fa34dd90065">

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/b3032a1c-3278-4428-b558-145e5379cf3c)


This is the standard way in Impact Pack.

**Comment by heerthiraja** [comment]
I.m getting error while using yoloworld + efficient sam in comfyUI.
![Screenshot 2024-06-11 154155](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/109062130/7c309128-3449-4159-ad0f-ed88c891e844)

**Comment by ltdrdata** [comment]
> I.m getting error while using yoloworld + efficient sam in comfyUI. ![Screenshot 2024-06-11 154155](https://private-user-images.githubusercontent.com/109062130/339744150-7c309128-3449-4159-ad0f-ed88c891e844.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDg0ODAsIm5iZiI6MTcxODQ0ODE4MCwicGF0aCI6Ii8xMDkwNjIxMzAvMzM5NzQ0MTUwLTdjMzA5MTI4LTM0NDktNDE1OS1hZDBmLWVkODhjODkxZTg0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxMDQzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjlmZTAzMzA3ZmQzYWMwMmQ4YzQwODE3ZjdjOTY5ZWFhZWQ2ZWU3MzYyYWUyOWExYmE0NmI2ZmRmNGUwOTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fjIiI3DKH2aaiMmEe628wZlxWvnO3VYIU2mikSM_R1E)

You have to ask this issue to that repo.
