### ISSUE TITLE
Pic should be 2/3 dimensional. Got 4 dimensions.

### ISSUE THREAD

**Issue by juhca** [ltdrdata/ComfyUI-Impact-Pack#47]
Newbie here, looked for the answer myself but I don't really know what to search for.

I loaded the detailed image from the [How to](https://github.com/ltdrdata/ComfyUI-Impact-Pack#1-basic-auto-face-detection-and-refine-exapmle) section, increased the batch_size to 2 and started the queue.
After generating the first one it display this error message.

How do I avoid this issue when queuing multiple images?

EDIT: this also happens witth a simple prompt ex.: "a dog"

> Error occurred when executing FaceDetailer:
> 
> pic should be 2/3 dimensional. Got 4 dimensions.
> 
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 145, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 68, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 826, in doit
>     enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask = FaceDetailer.enhance_face(
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 799, in enhance_face
>     sam_mask = core.make_sam_mask(sam_model_opt, segs, image, sam_detection_hint, sam_dilation,
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 335, in make_sam_mask
>     predictor.set_image(image, "RGB")
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\predictor.py", line 56, in set_image
>     input_image = self.transform.apply_image(image)
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\utils\transforms.py", line 31, in apply_image
>     return np.array(resize(to_pil_image(image), target_size))
>   File "C:\Users\my_user\Desktop\ComfyUI_windows_portable\python_embeded\lib\site-packages\torchvision\transforms\functional.py", line 278, in to_pil_image
>     raise ValueError(f"pic should be 2/3 dimensional. Got {pic.ndim} dimensions.")

Your image:
![simple-refined](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/17530097/d3160983-53b9-4d9c-bf29-ecf0812d3fc5)

The first image for my settings (just increased batch_size):
![ComfyUI_temp_xgsyo_00031_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/17530097/34d8c776-fcf2-4963-963f-1d9049c41705)

**Comment by ltdrdata** [comment]
https://youtu.be/nr7OY0tI3bo

You can handle multibatch through this method.

**Comment by juhca** [comment]
> https://youtu.be/nr7OY0tI3bo
> 
> You can handle multibatch through this method.

Thank you, don't know why I didn't noticed it in the Q&A. Incidentally how do you search the nodes? 

For everyone else: add a node -> Add node/latent/batch/Rebatch Latents. Input is the output from "Empty Latent Image", output is to the KSampler's input "latent_image".
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/17530097/e6ba915e-6577-4eb9-bc28-31bc1bb04e73)

**Comment by ltdrdata** [comment]
> > https://youtu.be/nr7OY0tI3bo
> > You can handle multibatch through this method.
> 
> Thank you, don't know why I didn't noticed it in the Q&A. Incidentally how do you search the nodes?
> 
> For everyone else: add a node -> Add node/latent/batch/Rebatch Latents. Input is the output from "Empty Latent Image", output is to the KSampler's input "latent_image". ![image](https://user-images.githubusercontent.com/17530097/254859253-e6ba915e-6577-4eb9-bc28-31bc1bb04e73.png)

Actually, I prefer double click and typing directly to search.
There are too many nodes in context menu. XD

**Comment by juhca** [comment]
> > > https://youtu.be/nr7OY0tI3bo
> > > You can handle multibatch through this method.
> > 
> > 
> > Thank you, don't know why I didn't noticed it in the Q&A. Incidentally how do you search the nodes?
> > For everyone else: add a node -> Add node/latent/batch/Rebatch Latents. Input is the output from "Empty Latent Image", output is to the KSampler's input "latent_image". ![image](https://user-images.githubusercontent.com/17530097/254859253-e6ba915e-6577-4eb9-bc28-31bc1bb04e73.png)
> 
> Actually, I prefer double click and typing directly to search. There are too many nodes in context menu. XD

Well that really speeds up the process xD thank you for the tip
I will close the issue, as it is resolved
