### ISSUE TITLE
Feature request: StepsScheduleHookProvider

### ISSUE THREAD

**Issue by Pos13** [ltdrdata/ComfyUI-Impact-Pack#471]
With simple hooks for CFG and Denoise, it's very logical to add a hook for Steps.
When you decrease denoise, you don't need that many steps for img2img. And using less steps allows to significantly reduce generation time during consecutive upscales.

**Comment by ltdrdata** [comment]
Do you want to progressively reduce steps in Iterative Upscale?

**Comment by Pos13** [comment]
@ltdrdata Yes.

**Comment by ltdrdata** [comment]
This is added.

**Comment by Pos13** [comment]
☺️

**Comment by Pos13** [comment]
@ltdrdata I'm a little bit confused why non-linear progression is called "simple". A bug or a feature?
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/64479446/2dd7a03b-cb36-455d-9136-6589dbdacab5)
(I set steps at 28, target_steps at 13, 3 iterations. It splits 28/23/13 instead of expected 28/20/13)

**Comment by ltdrdata** [comment]
> @ltdrdata I'm a little bit confused why non-linear progression is called "simple". A bug or a feature? ![image](https://private-user-images.githubusercontent.com/64479446/303947590-2dd7a03b-cb36-455d-9136-6589dbdacab5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2OTI2ODIsIm5iZiI6MTcwNzY5MjM4MiwicGF0aCI6Ii82NDQ3OTQ0Ni8zMDM5NDc1OTAtMmRkN2EwM2ItY2IzNi00NTVkLTkxMzYtNjU4OWRiZGFjYWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDIyNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YTMyY2VjMWNiNzFiOGIwYmUwZTg2OGMzZjAzZjZjY2FkYjQxMGIwZDVhMzdiYTJhYWFmODBlNzZhMTgwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JNNhotcIZbxdFeLdR75MVFbj1BAoIN6213VMivYOopI) (I set steps at 28, target_steps at 13, 3 iterations. It splits 28/23/13 instead of expected 28/20/13)

This is fixed.
