### ISSUE TITLE
Image Reciver node works with a delay of one clock cycle (sends out an image from the previous generation) 

### ISSUE THREAD

**Issue by BenderBlender** [ltdrdata/ComfyUI-Impact-Pack#473]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116355906/fd85fa88-8ac9-4b56-bbc2-589ae434401d)

**Comment by ltdrdata** [comment]
The point at which the ImageReceiver is passed corresponds to the completion of the ImageSender. It is normal for the ImageReceiver to execute first and be later updated by the ImageSender.

**Comment by BenderBlender** [comment]
I apologize, I didn’t think that this node was made specifically for recursion. I use these (a person posted it on Civitai)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116355906/748af106-6db7-4b3d-987d-f19de774e4a4)
