### ISSUE TITLE
Error occurred when executing DetailerForEachPipeForAnimateDiff:

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#474]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/b91769b1-01f3-4343-9fd4-a3ce37249954)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/cbe6bb1b-2859-43c3-a914-a5a2a4d9b332)

not enough values to unpack (expected 3, got 2)

File "F:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\animatediff_nodes.py", line 146, in doit
enhanced_seg, cnet_images = SEGSDetailerForAnimateDiff().do_detail(image_frames, single_seg, guide_size, guide_size_for, max_size, seed, steps, cfg, sampler_name, scheduler,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\animatediff_nodes.py", line 69, in do_detail
enhanced_image_tensor, cnet_images = core.enhance_detail_for_animatediff(cropped_image_frames, model, clip, vae, guide_size, guide_size_for, max_size,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 373, in enhance_detail_for_animatediff
positive, negative, cnet_images = control_net_wrapper.apply(positive, negative, torch.from_numpy(image_frames), noise_mask, use_acn=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1528, in apply
positive, negative, _ = acn.apply_controlnet(positive=positive, negative=negative, control_net=self.control_net, image=cnet_image,
^^^^^^^^^^^^^^^^^^^^^

**Comment by xueqing0622** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/114840118/9b5188d4-1e49-4cec-a144-075688bdb85d)
same error, when detector change to "simple detector for animateDiff(segs)

**Comment by ltdrdata** [comment]
Update your `ComfyUI-Advanced-ControlNet`.

**Comment by xueqing0622** [comment]
Yes, It works now! thanks,  ltdrdata!

**Comment by january-11** [comment]
Error occurred when executing IPAdapterUnifiedLoader:

'clipvision'

File "E:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus-main\IPAdapterPlus.py", line 514, in load_models
if clipvision_file != pipeline['clipvision']['file']:
![Uploading 屏幕截图 2024-07-09 070923.png…]()

**Comment by ltdrdata** [comment]
Make sure IPAdapter is up to date and you have clipvision model.
Moreover, Installing custom nodes by downloading a zip file from git is not recommended at all.
Install through git clone or use ComfyUI-Manager to install.

**Comment by ltdrdata** [comment]
Make sure IPAdapter is up to date and you have clipvision model.
Moreover, Installing custom nodes by downloading a zip file from git is not recommended at all.
Install through git clone or use ComfyUI-Manager to install.
