### ISSUE TITLE
Using Detailer with batch size of more than one causes exception

### ISSUE THREAD

**Issue by aurath** [ltdrdata/ComfyUI-Impact-Pack#48]
Any detailer nodes I try cause this exception when the batch size is 2 or higher.
```
Error occurred when executing DetailerForEachDebugPipe:

Cannot handle this data type: (1, 1, 1024, 3), |u1

File "C:\Path\To\ComfyUI\execution.py", line 145, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Path\To\ComfyUI\execution.py", line 75, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Path\To\ComfyUI\execution.py", line 68, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Path\To\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1406, in doit
DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
File "C:\Path\To\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 388, in do_detail
image_pil = tensor2pil(image).convert('RGBA')
File "C:\Path\To\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 14, in tensor2pil
return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8))
File "C:\Path\To\ComfyUI\venv\lib\site-packages\PIL\Image.py", line 3092, in fromarray
raise TypeError(msg) from e
```

**Comment by ltdrdata** [comment]
https://youtu.be/nr7OY0tI3bo

You solve that issue through rebatch.

**Comment by aurath** [comment]
Thank you! I think this could use a more obvious callout in the documentation or an example. I looked for a while before posting this issue.

Unfortunately, it appears that these are not _truly_ batched images, but two batches run serially. This is better than nothing but support for true batching seems important to me.

Just realized I can place the rebatch right before VAE decode to allow the main sampling to run batched and only the detailing to run serially. That's much better. This should be documented in an example.

**Comment by ltdrdata** [comment]
Unfortunately, batch processing requires images to be of the same size, but there is an issue with the detected images having different sizes. Additionally, batch processing can only be applied to the latent space and cannot be applied to the pixel image targeted by the detailer.

I am gradually improving the documentation. There are so many nodes that it's difficult to handle everything at once.

**Comment by aurath** [comment]
That makes a lot of sense. Would you take a PR if I added a `batch_processing.md` to ComfyUI-extension-tutorials along with a screenshot?

Thanks again for the tool!

**Comment by ltdrdata** [comment]
> That makes a lot of sense. Would you take a PR if I added a `batch_processing.md` to ComfyUI-extension-tutorials along with a screenshot?
> 
> Thanks again for the tool!

ok... :)
