### ISSUE TITLE
detailer for animatediff giving me pure noise on faces, what is going on?

### ISSUE THREAD

**Issue by cyandddd** [ltdrdata/ComfyUI-Impact-Pack#481]
<img width="1016" alt="81caddc013b6a9aca924c134534aaca" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/109906409/62601ee3-aff0-43ee-98d4-63356d7af92c">
<img width="87" alt="8a818063863ab214b63da71c0f74c92" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/109906409/b965bb6d-665b-4dc4-9c8f-621ecdb113f2">

this is a old regular detailer workflow for animatediff and it was working the last time i used it. but today it just gives me pure noise on face. the problem goes away when i remove the animatediff model, but it is supposed to work WITH the animatediff model right? 

Please help i have no idea what is going on? maybe is some python package issue?

**Comment by cyandddd** [comment]
it warns me about cupy:
 
CuPy may not function correctly because multiple CuPy packages are installed
  in your environment:

    cupy-cuda11x, cupy-cuda12x

does it have to do with thid issue?

**Comment by cyandddd** [comment]
i also updated comfyui today, maybe this is causing the issue

**Comment by ltdrdata** [comment]
The workflow is too small to grasp easily.

However, it is recommended to refrain from applying it to the Detailer for now and instead connect the model and conditioning applied to the basic_pipe in the Detailer directly to the KSampler to try vid2vid.

**Comment by cyandddd** [comment]
thank you for replying, let us know when its fix, really need detailer.

vid2vid works fine, i was trying to improve the detail of my output video in a separate workflow (because i dont have enough vram to run animation and detailer in a single workflow), and this happened. 

i believe i'm using the latest commit ec4d89cee946faacff60681a7f16443305350260, if you have a recommended commit that can work please let me know, thank you very much bro.
[detailer workflow.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14368901/detailer.workflow.json)


attached is the json file.

**Comment by cyandddd** [comment]
figured out! i use VHS to upload video and apparently it is already in "image list" format, but i used another "image batch to image list" node and thats causing the problem.
