### ISSUE TITLE
Segs Picker - Done and Cancel button hidden by segs 

### ISSUE THREAD

**Issue by var1ableX** [ltdrdata/ComfyUI-Impact-Pack#482]
I had approximately 10 segs in segs preview from your upscaler workflow, I wanted to have some tiles denoised at higher rate and finally decided to use Seg Picker. When Picker is empty the done and cancel buttons appear (no problem). But if you have e.g. 10 segs in the window then they hide these buttons.

I worked around it by shrinking the browser window until buttons became partially visible in the gaps between segs.

(if possible it would be interesting to have ability to have dedicated face detailer in the segs upscaler workflow. I tried to solve it using additional seg anything and then some mask arithmetic ... but in the end couldn't make it work cleanly.)

**Comment by ltdrdata** [comment]
Does it mean that if there are too many SEGS, the phenomenon occurs where UI elements are obscured?

**Comment by var1ableX** [comment]
I just played around with it again. You're essentially correct "too many segs". 

too many = # of segs results in segs needing >1 row to display.
workaround: reduce browser magnification so segs fit on 1 row.

Will close on that basis.

**Comment by var1ableX** [comment]
closing

**Comment by ltdrdata** [comment]
> closing

Ah is it browser zoom issue?
