### ISSUE TITLE
detailer-pipe-test.json

### ISSUE THREAD

**Issue by wTcWild** [ltdrdata/ComfyUI-Impact-Pack#49]
## make-basic_pipe box shows up in red. Tried ComfyManager
Missing custom nodes does show anything.
Tried Impact Pack. Nothing in there.
Can you help

**Comment by ltdrdata** [comment]
> ## make-basic_pipe box shows up in red. Tried ComfyManager
> Missing custom nodes does show anything. Tried Impact Pack. Nothing in there. Can you help

That node is used in the experimental extension called ComfyUI-Workflow-Component and is not registered with ComfyUI-Manager.

You can use it by installing https://github.com/ltdrdata/ComfyUI-Workflow-Component.

Additionally, that test workflow is intended for testing the functionality during the development process, and it is recommended to refer to the workflow available at https://github.com/ltdrdata/ComfyUI-extension-tutorials/tree/Main/ComfyUI-Impact-Pack for better understanding.
