### ISSUE TITLE
Inverse switch incompatible with auto queue? 

### ISSUE THREAD

**Issue by exnex** [ltdrdata/ComfyUI-Impact-Pack#493]
I have an inverse switch outputting to A and B. I'm using a random boolean, I auto queue, it selects A. When output of A completes, the workflow doesn't restart, it tries to complete output B and ends in an error because the switch isn't flowing to output B, but the queue doesn't know this until after workflow is queued due to the nature of random boolean, or maybe because of how ComfyUI decides workflow by looking backwards from outputs.  I'm not sure if it's possible to fix or work around this. The purpose is, I want wd14 tagger to investigate generated images, then compare keywords to pass boolean to the inverse switch and decide save path, effectively filtering images to different folders.

**Comment by ltdrdata** [comment]
The limitation of nodes operating on_prompt is clear: they must be determined at the queue point. This feature is expected to be improved upon the merge of https://github.com/comfyanonymous/ComfyUI/pull/2666

**Comment by exnex** [comment]
Awesome, that looks hopeful, thank you

**Comment by ltdrdata** [comment]
This is fixed since v7.2.1.
Use `select_on_execution`.
