### ISSUE TITLE
Feature request: bbox data output for bbox detectors

### ISSUE THREAD

**Issue by cv1llafane** [ltdrdata/ComfyUI-Impact-Pack#496]
It would be great if the bbox detectors could include individual integer outputs for the width, height, x-coordinates and y-coordinates of the detected bounding boxes.
It is very useful for reusing masks in other workflow sectors and masked merge operations.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/cbccd6fb-f19b-4009-8c7d-c10060364546)

Implemented.

**Comment by cv1llafane** [comment]
Thank you! That was fast!
