### ISSUE TITLE
Bitwise (Mask - Mask) and Bistwise (Mask + mask) do not work.

### ISSUE THREAD

**Issue by machine222** [ltdrdata/ComfyUI-Impact-Pack#498]
Hello, I am currently creating a workflow utilizing Bitwise.

I have configured a workflow that recognizes the hair area and the face area, and then subtracts the face mask from the hair mask to change the hairstyle, but currently the Bitwise (Mask - Mask) feature is not working properly.

I've updated Comfyui and all custom_nodes, and even after rebooting, it's still the same.
Additionally, Bitwise (mask + mask) is also not working properly.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128449287/b7869f97-fe0c-46ff-84dd-e870191fd455)

I will upload the workflow and pictures I used.
If you have any comments or solutions, I would really appreciate it if you could share them.

[bitwise bugreport.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14469458/bitwise.bugreport.json)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128449287/9eb20fb0-2bfe-421d-9f24-d6032ce9aab0)

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/1bc39884-626f-46f2-aee1-b61558b72f82)

The range of masks generated by the CLIPSeg node is not 0.0 to 1.0 but rather 0 to 255. Therefore, conversion to a binary mask is necessary before operations.
