### ISSUE TITLE
can't change the hairstyle

### ISSUE THREAD

**Issue by Rkkss** [ltdrdata/ComfyUI-Impact-Pack#50]
I thought increase bbox dilation would help but it didn't
can it be done somehow?

**Comment by ltdrdata** [comment]
If you only want to work on the hair area, there is a method to select the hair part through clipseg. However, if you want to change its shape, you will need dilation. If you use SAM together, the dilation for both SAM and the bounding box should be applied simultaneously.

**Comment by Rkkss** [comment]
I set both dilation to 200 and the change is still minimal/not the whole structure of the hair. Has to use denoise > 0.6 but it also change facial structure too much.
Also played around with detection hint but didn't seem to do much in my case.

**Comment by ltdrdata** [comment]
make 2 masks and subtract facial part. it will prevent affecting to facial part.

(dilated mask - facial mask)

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/hair-restyle.json
