### ISSUE TITLE
Yolov9 on the horizon?

### ISSUE THREAD

**Issue by stephantual** [ltdrdata/ComfyUI-Impact-Pack#500]
Hi! do you have a timeframe or an intent to include Yolov9 support in your ultralytics node?
Amazing work btw. Thank you!

**Comment by ltdrdata** [comment]
When Ultralytics updates, support will naturally become available.
You need to wait for  a while.

https://github.com/ultralytics/ultralytics/issues/8661

**Comment by stephantual** [comment]
No pressure Dr, I know you're already doing the Lord's work! 💯
