### ISSUE TITLE
UltralyticsDetectorProvider breaks on FE running on cloud and storage

### ISSUE THREAD

**Issue by NicholasKao1029** [ltdrdata/ComfyUI-Impact-Pack#502]
When `UltralyticsDetectorProvider` is used, I get this error 

<img width="562" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/45542006/ba2fe698-bfcb-41b5-a225-dcadfec2c41c">

Seems to be from line 581, `model_name_widget` not being set because it can't find a value?

<img width="1170" alt="Screenshot 2024-03-03 at 3 13 22 PM" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/45542006/3c080471-d117-4c2b-b385-091efb78fd09">
lled the submodule dependencies. This is with the latest comfyUI and Impact pack

**Comment by ltdrdata** [comment]
Show me the value of `node.widgets` inside `if(node.comfyClass == "UltralyticsDetectorProvider") {`
That should not be `undefined`.

And, what situation did this error occur in? Was it during a refresh or workflow load? Otherwise, just adding the node?

**Comment by NicholasKao1029** [comment]
The issue seemed to be I was symlinking the `models` directory, it was also a volume attached to a docker container. This is also all done in [modal](https://modal.com).

I'm closing now since the issue seems to have been resolved, by not symlinking. Thanks!
