### ISSUE TITLE
Preview Bridge started giving errors

### ISSUE THREAD

**Issue by Davikar** [ltdrdata/ComfyUI-Impact-Pack#503]
The preview bridge seems to have stopped working, I've started getting the following error as soon as I add a mask to the image:
(No errors before I add the mask)

```
Error occurred when executing PreviewBridge:

'$711-1709593028.5991826'

File "C:\AI\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\bridge_nodes.py", line 76, in doit
pixels, mask, path_item = PreviewBridge.load_image(image)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\bridge_nodes.py", line 38, in load_image
image_path, ui_item = core.preview_bridge_image_id_map[pb_id]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
```

**Comment by aegis72** [comment]
Yep, same. Here's a WF to show. If a mask is saved, the error occurs:

Test WF
[broken preview bridge.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14488403/broken.preview.bridge.json)

Input Img:
![space_schoolgirl](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/118572301/3ffe5aad-a8aa-41e7-8b78-00a486822894)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/118572301/c28f6945-d51c-4afd-a1c0-7a28382b1bf5)

Error text is same as above error (roughly)

**Comment by aegis72** [comment]
Confirmed that going back to a version from 2-27 works again 
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/118572301/66a70c0f-e7fe-4a1e-9c13-d11f9b562342)

**Comment by ltdrdata** [comment]
This is fixed.
