### ISSUE TITLE
inpaint batche

### ISSUE THREAD

**Issue by za-wa-n-go** [ltdrdata/ComfyUI-Impact-Pack#504]
In the case of using inpaint, is it not possible to produce multiple images in one batch?

**Comment by za-wa-n-go** [comment]
I assume the inpaint part is applied to the original picture.

**Comment by za-wa-n-go** [comment]
The ideal behavior would be if SEGSPaste supports batches. I would like to know if there is a way to achieve this.

**Comment by ltdrdata** [comment]
In the case of batch images, the differences in detected segments occur for each image, making it impossible to batch process them. Therefore, they need to be converted into a list for processing.

You need to change batch to list to process it.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md

**Comment by za-wa-n-go** [comment]
Thanx.
Hmm, I didn't quite understand how to connect it.
It seems that the easiest way is to set the crop_factor of MaskToSEGS to a larger value.

**Comment by ltdrdata** [comment]
> Thanx. Hmm, I didn't quite understand how to connect it. It seems that the easiest way is to set the crop_factor of MaskToSEGS to a larger value.

Convert the image batch to an image list before passing it to the detector. This way, the rest of the operations will also be processed in a iterative manner for each image. If you need to process the completed images as a batch after passing through SEGSPaste, simply convert the list back to a batch.

**Comment by za-wa-n-go** [comment]
Maybe it's wrong.
The list is registered with the same picture for the number of batch times.
If you don't mind, please show me a sample workflow.

<img width="1213" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/118154415/c2614f7d-04a2-4950-9d7c-7955f6036915">

**Comment by ltdrdata** [comment]
> Maybe it's wrong. The list is registered with the same picture for the number of batch times. If you don't mind, please show me a sample workflow.
> 
> <img alt="image" width="1213" src="https://private-user-images.githubusercontent.com/118154415/310387718-c2614f7d-04a2-4950-9d7c-7955f6036915.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDc3MjcsIm5iZiI6MTcwOTcwNzQyNywicGF0aCI6Ii8xMTgxNTQ0MTUvMzEwMzg3NzE4LWMyNjE0ZjdkLTA0YTItNDk1MC05ZDdjLTc5NTVmNjAzNjkxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwNjQzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTIxYWZlYzhmNGYyNGViY2YxZmVmZTZhMWRlYTg4OTQzYWUyODI3ZGM0OGY5MThjODhmY2ZkMTk1MDY1YzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dVYvsC1lJPddce33Dv2o5rmubjeXqyRd7Bo--2vdYz8">

You should not use denoise 1.0 when you are inpainting.
