### ISSUE TITLE
Does `UltralyticsDetectorProvider` supports `extra_model_paths.yaml` ?

### ISSUE THREAD

**Issue by bigcat88** [ltdrdata/ComfyUI-Impact-Pack#505]
I have such  `extra_model_paths.yaml`:
 ```
 amw_models:
 ...
 loras: |
    /Users/user/PycharmProjects/my_project/amw_models/loras
    /Users/user/PycharmProjects/my_project/amw_models/photomaker
  photomaker: /Users/user/PycharmProjects/my_project/amw_models/photomaker
  sams: /Users/user/PycharmProjects/my_project/amw_models/sams
  ultralytics: /Users/user/PycharmProjects/my_project/amw_models/ultralytics
 ```
 
 
 For some unknown reason to me the `UltralyticsDetectorProvider` does not see `face_yolov8n_v2.pt` when I place it at
 
 `/Users/user/PycharmProjects/my_project/amw_models/ultralytics/bbox/face_yolov8n_v2.pt`
 
 When I put it back to the original models folder from ComfyUI all is fine. But I need the models to be outside of ComfyUI, and from all my flow only models from `ultralytics` folder is not seen.
 
 Where can I take look first, can someone give an advice?

Thanks.

**Comment by ltdrdata** [comment]
You can use,
`ultralytics_bbox`
`ultralytics_segm`
`ultralytics`
