### ISSUE TITLE
`DetailerDebug (SEGS)` keeps looping and cannot advance to the next step

### ISSUE THREAD

**Issue by ponymushama** [ltdrdata/ComfyUI-Impact-Pack#506]
- Apple M2 max
- macOS Sonoma 14.3.1 (23D60)
- `conda` venv

`DetailerDebug (SEGS)` keeps looping and cannot advance to the next step.

```
Requested to load AutoencoderKL
Loading 1 new model
Tile height: 1024
Tile width: 1024
Final height: 2160
Final width: 2160
Overlap: 128
Tile coordinates: [(1136, 1136), (0, 1136), (1136, 0), (0, 0), (896, 1136), (1136, 896), (0, 896), (896, 0), (896, 896)]
Processing tile 1 of 9
Tile coordinate: (1136, 1136)
Processing tile 2 of 9
Tile coordinate: (0, 1136)
Processing tile 3 of 9
Tile coordinate: (1136, 0)
Processing tile 4 of 9
Tile coordinate: (0, 0)
Processing tile 5 of 9
Tile coordinate: (896, 1136)
Processing tile 6 of 9
Tile coordinate: (1136, 896)
Processing tile 7 of 9
Tile coordinate: (0, 896)
Processing tile 8 of 9
Tile coordinate: (896, 0)
Processing tile 9 of 9
Tile coordinate: (896, 896)
Loads SAM model: /Users/ponymushama/ComfyUI/models/sams/sam_vit_b_01ec64.pth (device:Prefer GPU)

0: 640x640 1 person, 268.0ms
Speed: 13.2ms preprocess, 268.0ms inference, 5.9ms postprocess per image at shape (1, 3, 640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
  0%|                                                                | 0/4 [00:00<?, ?it/s]/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchsde/_brownian/brownian_interval.py:594: UserWarning: Should have tb<=t1 but got tb=0.4469183385372162 and t1=0.446918.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")
100%|████████████████████████████████████████████████████████| 4/4 [00:53<00:00, 13.37s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.98s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.52s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.60s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:49<00:00, 12.43s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.57s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.53s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
INFO: the IPAdapter reference image is not a square, CLIPImageProcessor will resize and crop it at the center. If the main focus of the picture is not in the middle the result might not be what you are expecting.
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:49<00:00, 12.38s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.63s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
 50%|████████████████████████████                            | 2/4 [00:29<00:29, 14.68s/it]
```

![DetailerDebug (SEGS) setting](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/94793701/f53cb141-1349-404f-b3df-56d91418a538)

**Comment by ltdrdata** [comment]
Connect the SEGS entered through the Detailer to the SEGSPreview for verification instead of the Detailer.

**Comment by ponymushama** [comment]
> Connect the SEGS entered through the Detailer to the SEGSPreview for verification instead of the Detailer.

Hi, thank for your help.

I have added SEGSPreview, but looping is still here.

Maybe I misunderstand your solution?

![add SEGSPreview](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/94793701/024af948-c546-4b77-950d-fb94b461cba3)

```
Requested to load AutoencoderKL
Loading 1 new model
Tile height: 1024
Tile width: 1024
Final height: 2160
Final width: 2160
Overlap: 128
Tile coordinates: [(1136, 1136), (0, 1136), (1136, 0), (0, 0), (896, 1136), (1136, 896), (0, 896), (896, 0), (896, 896)]
Processing tile 1 of 9
Tile coordinate: (1136, 1136)
Processing tile 2 of 9
Tile coordinate: (0, 1136)
Processing tile 3 of 9
Tile coordinate: (1136, 0)
Processing tile 4 of 9
Tile coordinate: (0, 0)
Processing tile 5 of 9
Tile coordinate: (896, 1136)
Processing tile 6 of 9
Tile coordinate: (1136, 896)
Processing tile 7 of 9
Tile coordinate: (0, 896)
Processing tile 8 of 9
Tile coordinate: (896, 0)
Processing tile 9 of 9
Tile coordinate: (896, 896)
Loads SAM model: /Users/ponymushama/ComfyUI/models/sams/sam_vit_b_01ec64.pth (device:Prefer GPU)

0: 640x640 1 person, 242.2ms
Speed: 20.3ms preprocess, 242.2ms inference, 5.5ms postprocess per image at shape (1, 3, 640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:52<00:00, 13.21s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.89s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.74s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.92s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.78s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.62s/it]
Requested to load AutoencoderKL
Loading 1 new model
Detailer: force inpaint
Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
Requested to load SDXL
Loading 1 new model
 50%|████████████████████████████                            | 2/4 [00:28<00:28, 14.44s/it]
```

**Comment by ltdrdata** [comment]
> > Connect the SEGS entered through the Detailer to the SEGSPreview for verification instead of the Detailer.
> 
> Hi, thank for your help.
> 
> I have added SEGSPreview, but looping is still here.
> 
> Maybe I misunderstand your solution?
> 
> ![add SEGSPreview](https://private-user-images.githubusercontent.com/94793701/310397218-024af948-c546-4b77-950d-fb94b461cba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzM1NTAsIm5iZiI6MTcwOTczMzI1MCwicGF0aCI6Ii85NDc5MzcwMS8zMTAzOTcyMTgtMDI0YWY5NDgtYzU0Ni00Yjc3LTk1MGQtZmI5NGI0NjFjYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzNTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NGE4NmQwOWQ1ZWU2MzMxOThiOGJkZjE3OGVlOGQ4YWE5ZTIzMjc0ZjUxODVlNjBhOWI4YjdmZWViYTQ2OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sjEic-jWcBTCgfcqPflG5SpRMmvtC48jsh_RwwxBt-g)
> 
> ```
> Requested to load AutoencoderKL
> Loading 1 new model
> Tile height: 1024
> Tile width: 1024
> Final height: 2160
> Final width: 2160
> Overlap: 128
> Tile coordinates: [(1136, 1136), (0, 1136), (1136, 0), (0, 0), (896, 1136), (1136, 896), (0, 896), (896, 0), (896, 896)]
> Processing tile 1 of 9
> Tile coordinate: (1136, 1136)
> Processing tile 2 of 9
> Tile coordinate: (0, 1136)
> Processing tile 3 of 9
> Tile coordinate: (1136, 0)
> Processing tile 4 of 9
> Tile coordinate: (0, 0)
> Processing tile 5 of 9
> Tile coordinate: (896, 1136)
> Processing tile 6 of 9
> Tile coordinate: (1136, 896)
> Processing tile 7 of 9
> Tile coordinate: (0, 896)
> Processing tile 8 of 9
> Tile coordinate: (896, 0)
> Processing tile 9 of 9
> Tile coordinate: (896, 896)
> Loads SAM model: /Users/ponymushama/ComfyUI/models/sams/sam_vit_b_01ec64.pth (device:Prefer GPU)
> 
> 0: 640x640 1 person, 242.2ms
> Speed: 20.3ms preprocess, 242.2ms inference, 5.5ms postprocess per image at shape (1, 3, 640, 640)
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
> set det-size: (640, 640)
> Detailer: force inpaint
> Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> Requested to load SDXL
> Loading 1 new model
> 100%|████████████████████████████████████████████████████████| 4/4 [00:52<00:00, 13.21s/it]
> Requested to load AutoencoderKL
> Loading 1 new model
> Detailer: force inpaint
> Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> Requested to load SDXL
> Loading 1 new model
> 100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.89s/it]
> Requested to load AutoencoderKL
> Loading 1 new model
> Detailer: force inpaint
> Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> Requested to load SDXL
> Loading 1 new model
> 100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.74s/it]
> Requested to load AutoencoderKL
> Loading 1 new model
> Detailer: force inpaint
> Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> Requested to load SDXL
> Loading 1 new model
> 100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.92s/it]
> Requested to load AutoencoderKL
> Loading 1 new model
> Detailer: force inpaint
> Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> Requested to load SDXL
> Loading 1 new model
> 100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.78s/it]
> Requested to load AutoencoderKL
> Loading 1 new model
> Detailer: force inpaint
> Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> Requested to load SDXL
> Loading 1 new model
> 100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.62s/it]
> Requested to load AutoencoderKL
> Loading 1 new model
> Detailer: force inpaint
> Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> Requested to load SDXL
> Loading 1 new model
>  50%|████████████████████████████                            | 2/4 [00:28<00:28, 14.44s/it]
> ```

What I meant is to check how many items  in SEGS are included in the detailer.

**Comment by ponymushama** [comment]
> > > Connect the SEGS entered through the Detailer to the SEGSPreview for verification instead of the Detailer.
> > 
> > 
> > Hi, thank for your help.
> > I have added SEGSPreview, but looping is still here.
> > Maybe I misunderstand your solution?
> > ![add SEGSPreview](https://private-user-images.githubusercontent.com/94793701/310397218-024af948-c546-4b77-950d-fb94b461cba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzM1NTAsIm5iZiI6MTcwOTczMzI1MCwicGF0aCI6Ii85NDc5MzcwMS8zMTAzOTcyMTgtMDI0YWY5NDgtYzU0Ni00Yjc3LTk1MGQtZmI5NGI0NjFjYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzNTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NGE4NmQwOWQ1ZWU2MzMxOThiOGJkZjE3OGVlOGQ4YWE5ZTIzMjc0ZjUxODVlNjBhOWI4YjdmZWViYTQ2OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sjEic-jWcBTCgfcqPflG5SpRMmvtC48jsh_RwwxBt-g)
> > ```
> > Requested to load AutoencoderKL
> > Loading 1 new model
> > Tile height: 1024
> > Tile width: 1024
> > Final height: 2160
> > Final width: 2160
> > Overlap: 128
> > Tile coordinates: [(1136, 1136), (0, 1136), (1136, 0), (0, 0), (896, 1136), (1136, 896), (0, 896), (896, 0), (896, 896)]
> > Processing tile 1 of 9
> > Tile coordinate: (1136, 1136)
> > Processing tile 2 of 9
> > Tile coordinate: (0, 1136)
> > Processing tile 3 of 9
> > Tile coordinate: (1136, 0)
> > Processing tile 4 of 9
> > Tile coordinate: (0, 0)
> > Processing tile 5 of 9
> > Tile coordinate: (896, 1136)
> > Processing tile 6 of 9
> > Tile coordinate: (1136, 896)
> > Processing tile 7 of 9
> > Tile coordinate: (0, 896)
> > Processing tile 8 of 9
> > Tile coordinate: (896, 0)
> > Processing tile 9 of 9
> > Tile coordinate: (896, 896)
> > Loads SAM model: /Users/ponymushama/ComfyUI/models/sams/sam_vit_b_01ec64.pth (device:Prefer GPU)
> > 
> > 0: 640x640 1 person, 242.2ms
> > Speed: 20.3ms preprocess, 242.2ms inference, 5.5ms postprocess per image at shape (1, 3, 640, 640)
> > Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> > find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
> > Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> > find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
> > Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> > find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
> > Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> > find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
> > Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> > find model: /Users/ponymushama/ComfyUI/models/insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
> > set det-size: (640, 640)
> > Detailer: force inpaint
> > Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> > Requested to load SDXL
> > Loading 1 new model
> > 100%|████████████████████████████████████████████████████████| 4/4 [00:52<00:00, 13.21s/it]
> > Requested to load AutoencoderKL
> > Loading 1 new model
> > Detailer: force inpaint
> > Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> > Requested to load SDXL
> > Loading 1 new model
> > 100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.89s/it]
> > Requested to load AutoencoderKL
> > Loading 1 new model
> > Detailer: force inpaint
> > Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> > Requested to load SDXL
> > Loading 1 new model
> > 100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.74s/it]
> > Requested to load AutoencoderKL
> > Loading 1 new model
> > Detailer: force inpaint
> > Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> > Requested to load SDXL
> > Loading 1 new model
> > 100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.92s/it]
> > Requested to load AutoencoderKL
> > Loading 1 new model
> > Detailer: force inpaint
> > Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> > Requested to load SDXL
> > Loading 1 new model
> > 100%|████████████████████████████████████████████████████████| 4/4 [00:51<00:00, 12.78s/it]
> > Requested to load AutoencoderKL
> > Loading 1 new model
> > Detailer: force inpaint
> > Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> > Requested to load SDXL
> > Loading 1 new model
> > 100%|████████████████████████████████████████████████████████| 4/4 [00:50<00:00, 12.62s/it]
> > Requested to load AutoencoderKL
> > Loading 1 new model
> > Detailer: force inpaint
> > Detailer: segment upscale for ((812, 812)) | crop region (1218, 1218) x 1.0 -> (1218, 1218)
> > Requested to load SDXL
> > Loading 1 new model
> >  50%|████████████████████████████                            | 2/4 [00:28<00:28, 14.44s/it]
> > ```
> 
> What I meant is to check how many items in SEGS are included in the detailer.

Thanks a lot. Like you say, I check how mush SEGS I have. My issue is that I have too mush SEGS to upscale. All the workflow takes 7000 sec to finish. It does not loop, just slow.
