### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [ltdrdata/ComfyUI-Impact-Pack#507]
It looks like a module isn't installing properly; using Windows w Conda env:

> ** ComfyUI startup time: 2024-03-06 11:54:55.168062
> ** Platform: Windows
> ** Python version: 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
> ** Python executable: C:\Users\SomeRando\anaconda3\envs\py310\python.exe
> ** Log path: C:\Users\SomeRando\Dropbox\app-settings\comfyui\comfyui.log
> 
> Prestartup times for custom nodes:
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\rgthree-comfy
>    0.1 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 8192 MB, total RAM 32456 MB
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
> VAE dtype: torch.float32
> Using pytorch cross attention
> Adding extra search path checkpoints C:/Users/SomeRando/Documents/ai/stable-diffusion\models/checkpoints
> Adding extra search path configs C:/Users/SomeRando/Documents/ai/stable-diffusion\configs
> Adding extra search path vae C:/Users/SomeRando/Documents/ai/stable-diffusion\models/vae
> Adding extra search path loras C:/Users/SomeRando/Documents/ai/stable-diffusion\models/loras
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/GFPGAN
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/ESRGAN
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/RealESRGAN
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/SwinIR
> Adding extra search path embeddings C:/Users/SomeRando/Documents/ai/stable-diffusion\models/embeddings
> Adding extra search path hypernetworks C:/Users/SomeRando/Documents/ai/stable-diffusion\models/hypernetworks
> Adding extra search path controlnet C:/Users/SomeRando/Documents/ai/stable-diffusion\models/controlnet
> Adding extra search path checkpoints C:/Users/SomeRando/Documents/ai/stable-diffusion\models/checkpoints
> Adding extra search path clip C:/Users/SomeRando/Documents/ai/stable-diffusion\models/clip
> Adding extra search path clip_vision C:/Users/SomeRando/Documents/ai/stable-diffusion\models/clip_vision
> Adding extra search path configs C:/Users/SomeRando/Documents/ai/stable-diffusion\configs
> Adding extra search path controlnet C:/Users/SomeRando/Documents/ai/stable-diffusion\models/controlnet
> Adding extra search path embeddings C:/Users/SomeRando/Documents/ai/stable-diffusion\models/embeddings
> Adding extra search path loras C:/Users/SomeRando/Documents/ai/stable-diffusion\models/loras
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/GFPGAN
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/ESRGAN
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/RealESRGAN
> Adding extra search path upscale_models C:/Users/SomeRando/Documents/ai/stable-diffusion\models/upscaling/SwinIR
> Adding extra search path vae C:/Users/SomeRando/Documents/ai/stable-diffusion\models/vae
> [Crystools INFO] Crystools version: 1.11.0
> [Crystools INFO] CPU: Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz - Arch: AMD64 - OS: Windows 10
> [Crystools INFO] GPU/s:
> [Crystools INFO] 0) NVIDIA GeForce GTX 1070
> [Crystools INFO] NVIDIA Driver: 551.61
> C:\Users\SomeRando\anaconda3\envs\py310\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
>   torch.utils._pytree._register_pytree_node(
> ### Loading: ComfyUI-Impact-Pack (V4.83.1)
> ### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
> ### ComfyUI-Impact-Pack: Check dependencies
> ### ComfyUI-Impact-Pack: Updating subpack
> [Impact Pack] EXECUTE: ['C:\\Users\\SomeRando\\anaconda3\\envs\\py310\\python.exe', 'install.py'] in 'C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
> req_path: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
> req_path: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
> req_path: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
> [Impact Pack] EXECUTE: ['C:\\Users\\SomeRando\\anaconda3\\envs\\py310\\python.exe', '-m', 'pip', 'install', '-r', 'C:\\Users\\SomeRando\\Documents\\git-repositories\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\requirements.txt'] in 'None'
> ### ComfyUI-Impact-Pack: Check basic models
> Traceback (most recent call last):
>   File "C:\Users\SomeRando\Documents\git-repositories\ComfyUI\nodes.py", line 1887, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 72, in <module>
>     import impact.impact_server  # to load server api
>   File "C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 13, in <module>
>     import impact.core as core
>   File "C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 3, in <module>
>     from impact.utils import *
>   File "C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 9, in <module>
>     from scipy.ndimage import zoom
> ImportError: cannot import name 'zoom' from 'scipy.ndimage' (unknown location)
> 
> Cannot import C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: cannot import name 'zoom' from 'scipy.ndimage' (unknown location)
> ### Loading: ComfyUI-Manager (V2.9)
> ### ComfyUI Revision: 2049 [03e6e816] | Released on '2024-03-06'
> ### Loading: Workspace Manager (V1.0.0)
> [tinyterraNodes] Loaded
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> 
> [rgthree] Loaded 34 fantastic nodes.
> [rgthree] Will use rgthree's optimized recursive execution.
> 
> 
> Import times for custom nodes:
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\SDXLAspectRatio.py
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\sdxl_prompt_styler
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\comfyui-floodgate
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\masquerade-nodes-comfyui
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI_Cutoff
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\lora-info
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\sdxl-recommended-res-calc
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\DTAIComfyVariables
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyMath
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Image-Saver
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\rgthree-comfy
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\comfyui-workspace-manager
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\integrated-nodes-comfyui
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\efficiency-nodes-comfyui
>    0.0 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
>    0.1 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-GlifNodes
>    0.3 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Manager
>    2.9 seconds: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Crystools
>    8.4 seconds (IMPORT FAILED): C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> FETCH DATA from: C:\Users\SomeRando\Documents\git-repositories\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by JakeTheSnake3p0** [comment]
After manually running `pip install --upgrade scipy` on my conda installation, this extension as well as ClipSeg both installed without complaint.

**Comment by ltdrdata** [comment]
> After manually running `pip install --upgrade scipy` on my conda installation, this extension as well as ClipSeg both installed without complaint.

I added constraints to pip to ensure that scipy is version 1.11.4 or higher.
