### ISSUE TITLE
Error occurred when executing IterativeImageUpscale

### ISSUE THREAD

**Issue by PPuyan** [ltdrdata/ComfyUI-Impact-Pack#508]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/59681822/33c7f836-90e7-4573-ab0b-3ba71fb24b0a)

Error occurred when executing IterativeImageUpscale:

'TwoSamplersForMaskUpscaler' object has no attribute 'is_tiled'

File "..\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1166, in doit
if upscaler.is_tiled:

**Comment by ltdrdata** [comment]
This is fixed.
