### ISSUE TITLE
Feature request: Checkpoint Switch

### ISSUE THREAD

**Issue by PatrikNeunteufel** [ltdrdata/ComfyUI-Impact-Pack#515]
i made a switch node to switch checkpoints, but i had to create the node with a fixed number of inputs for checkpoints and returning the choosed checkpoint.
but i would like to have a variable number of inputs as you have in your switch any.
i tried to copy your generalSwitch where i can plug in a checkpoint in the first input, but the node does no add one more input after plug the first input. 
how can i do that?

**Comment by ltdrdata** [comment]
The expansion of variable slots occurs in JS.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/e1570e76799049fb0038f6232fd89800ab4565eb/js/impact-pack.js#L414

What is the need for separate nodes when the `Switch (Any)` node already provides a switch for all types?

**Comment by PatrikNeunteufel** [comment]
ah, i got it, adding slots happens in the front end.

oh, i tried it with any (somehow wrong) and didn't work... now it does fine.
