### ISSUE TITLE
HF Transformers Classifier Provider -> SEGS Classify apparently has no effect

### ISSUE THREAD

**Issue by renwerx** [ltdrdata/ComfyUI-Impact-Pack#521]
No matter what combination of repo and expression I try any SEGS I feed the classifier comes out as remained_SEGS. 
I'm not getting any errors, or anything at all in the console.
Here's the relevant section of the workflow:
![segs classifier](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132638531/7d757727-e4e8-4214-8ed2-b0bef0e5178d)

**Comment by kaboomtheory** [comment]
I thought I was going crazy but I'm having the same issue.

**Comment by ltdrdata** [comment]
Each Hugging Face model has different detection capabilities.

**Comment by renwerx** [comment]
Sorry, but can you elaborate please? 
What specifically am I doing wrong? 

I said I had tried numerous combinations of repo and expression both preset and manual already, I've tried many of them numerous times each. Are you saying that a gender detection repo doesn't detect male vs female? I'm not trying to waste anyone's time here. 

These are the exact same settings as in your tutorial at [https://raw.githubusercontent.com/ltdrdata/ComfyUI-extension-tutorials/Main/ComfyUI-Impact-Pack/workflow/gender-senstivie-detailer.png](https://raw.githubusercontent.com/ltdrdata/ComfyUI-extension-tutorials/Main/ComfyUI-Impact-Pack/workflow/gender-senstivie-detailer.png) 
**Preset repo:** NTQAI/pedestrian_gender_recognition 
**Manual expr:** #Female > 0.3
![segs classifier pt 2](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132638531/59d50a52-566c-43f6-a984-668d1dde972e)

I fed the image into the huggingface demo of pedestrian_gender_recognition and the response was:
![segs classifier pt 2 hf results](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132638531/f16b4e6c-5264-4284-89ad-a3809dfa5354)

So that looks to me like we're getting 0.991 Female. But if we're being pedantic there's no hash before the "Female", so let's try updating the expression so it exactly corresponds to the model output:
![segs classifier pt 2 no cigar](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132638531/fb29d155-07ab-4c92-be03-3ceafd0baab3)

Ok so that's still not working what do I try next given than I've already done this same process for other repos?

**Comment by ltdrdata** [comment]
From the results you've posted, it seems like the model is classifying correctly. I'll check it out later.

**Comment by renwerx** [comment]
You're a champion! Great node set btw :)

**Comment by ltdrdata** [comment]
![workflow (13)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/47a284a1-682f-4407-a98e-30e60e994834)

I have no problem with that.
Start diagnosing based on this workflow.

**Comment by renwerx** [comment]
I tried with the single image and that is working fine:
![single image detector](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132638531/4d47e4f4-18df-43a7-9a1d-6662aa5ae31a)

However when I tried with a bare bones AnimateDiff workflow the same issue happened:
![AD image detector](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/132638531/28c36b3c-93ac-47b7-8d86-5e1a0d42f73a)

**Comment by izonewonyoung** [comment]
rizvandwiki
/
gender-classification-2 where should i put this model?

**Comment by ltdrdata** [comment]
> I tried with the single image and that is working fine: ![single image detector](https://private-user-images.githubusercontent.com/132638531/314246366-4d47e4f4-18df-43a7-9a1d-6662aa5ae31a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjUwMzQsIm5iZiI6MTcxODcyNDczNCwicGF0aCI6Ii8xMzI2Mzg1MzEvMzE0MjQ2MzY2LTRkNDdlNGY0LTE4ZGYtNDNhNy05YTFkLTY2NjJhYTVhZTMxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxNTMyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2ZhODk4NzQyOTNhMWUyMzQyNGE3NDE5ODIzMDY4NDc4MWM3M2JjMjYwNmIwMjc2OGY5Mzc5OTI5OGU4MTZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZR4XIDQQ1eO6ObYJXi86SSGOER7E-4wM06u-v06xpxA)
> 
> However when I tried with a bare bones AnimateDiff workflow the same issue happened: ![AD image detector](https://private-user-images.githubusercontent.com/132638531/314246565-28c36b3c-93ac-47b7-8d86-5e1a0d42f73a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjUwMzQsIm5iZiI6MTcxODcyNDczNCwicGF0aCI6Ii8xMzI2Mzg1MzEvMzE0MjQ2NTY1LTI4YzM2YjNjLTkzYWMtNDdiNy04ZDg2LTVlMWEwZDQyZjczYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxNTMyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzgyMDNiYjhjYzg0MWQwOWZhODU4NTY4Y2MyNTAzZWI0YjUyMjZlZWY0OTQ5MjljNjY2NGFiOTE1YmI3YmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RQLBtnVAUCyzBfxVBVYfrXgUQbVp0wjfYRCWc1WicOU)

![multiple](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/4c689d32-5ad9-4379-8c3c-2a5b453a7a6f)

multiple face isn't a problem.
I think that is a limitation of the model.

And you'd better use `#Female` instead of `Female` for other models.
https://github.com/ltdrdata/ComfyUI-Impact-Pack#huggingface-nodes
