### ISSUE TITLE
“git submodule update --init --recursive  ”can not work.

### ISSUE THREAD

**Issue by 9527pluto** [ltdrdata/ComfyUI-Impact-Pack#524]
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack>git submodule update --init --recursive
fatal: detected dubious ownership in repository at 'E:/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack'
'E:/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack' is on a file system that does not record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory E:/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

**Comment by ltdrdata** [comment]
It has been a long time since I transitioned away from using submodules in the Impact Pack repo structure. Why are you updating submodules now?

**Comment by ltdrdata** [comment]
I just updated `README.md`.

question:
Are you by any chance using your `custom_nodes` directory in the form of symbolic links?
