### ISSUE TITLE
IMAGE BATCH   TO  LIST   MASK  ERROR  

### ISSUE THREAD

**Issue by bihailantian655** [ltdrdata/ComfyUI-Impact-Pack#526]
![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/35267721/0ccc8533-e8fa-4e29-9a28-3a96afd7600a)

In this  work  flow   ,

 if I only want to generate two pictures, use other   controlnet  without  mask optional 。 I can just set both of them ( image load cap   and  batch  size  )as 2 . 

But if I use segs  and  inpaint  controlnet  with  mask optional , it will generate four pictures(image load cap    * batch  size).

so  if I  want to use   inpaint  controlnet   How should I modify it to only generate two pictures?    not  (image load cap    * batch  size) pics

**Comment by ltdrdata** [comment]
Insert `Mask List To Mask Batch` after `SEGS To Mask List`

**Comment by bihailantian655** [comment]
> SEGS To Mask List

![{E810EC8A-117E-41f2-B2B6-4F7757BF933E}](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/35267721/780544ed-55da-4d67-972c-1be34c958c7e)
  

1 and 2 can  not  connect  to  3   ,is  there any  other  nodes

**Comment by bihailantian655** [comment]
> Insert `Mask List To Mask Batch` after `SEGS To Mask List`

thanks  ，it working  good
