### ISSUE TITLE
Custom REST Interface for ImpactPack makes it uniquely difficult to implement in Infrastructure

### ISSUE THREAD

**Issue by ghost** [ltdrdata/ComfyUI-Impact-Pack#535]
Hi,

So, I'm normally a fan of RESTful interfaces, but ImpactPack has a number of custom ones that are added that aren't in server.py, and they cause issues with our infrastructure which makes it uniquely difficult to implement on corporate infrastructure.

We are going to be skipping *just* impactpack out of hundreds of node packs for now until either someone decides to implement the REST API it wants, or it gets adjusted to use file paths.

We've decided not to "just modify the JS" to send requests to a py file, because ongoing updates to the JS would potentially cause maintenance problems.

Thanks, and hopefully we can work that out one way or another.

**Comment by ltdrdata** [comment]
Do you mean that there is an issue with the API paths?

**Comment by ghost** [comment]
Sorry, this is out of date and issue can be closed.
