### ISSUE TITLE
Switch does not stop KSampler from executing on an unselected path

### ISSUE THREAD

**Issue by Shadetail** [ltdrdata/ComfyUI-Impact-Pack#538]
![workflow-video-inpaint](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/11357447/464fa2c5-44fb-4421-9286-7592b4e93083)

This workflow operates on a sequence of png images to effectively inpaint transparent areas of a video stabilized with [Gyroflow](https://github.com/gyroflow/gyroflow).

Since I made it to operate on tens of thousands of images, it's optimized to process at nearly 4fps. But often there are a lot of frames that don't have any issues and so don't require inpaining. Detecting such frames with no transparency and skipping execution entirely, instead just copying the input into the output presents an opportunity for a huge optimization, which takes 0.04 seconds as opposed to 0.27 for the execution of the whole workflow. This is an especially big deal when only 10% of the total video frames require inpaining, where a video that would take an hour to process can be done in just 10 minutes.

So I made my own node that checks if the input image has any transparency and depending on that, outputs an integer 1 or 2, meant as the input for your Switch (Any) node. I tested that it all works, and the input image is indeed the one that gets saved when no transparency is detected (output integer is 2). However, the KSampler and the whole upper branch of the workflow containing it still get executed, even though output of the KSampler doesn't get used at all.

I noticed that when I manually use the widget and type in "2" into the Switch node, then KSampler correctly does not get executed. Issue of both paths getting executed only happens when the "select" value is fed as an input that changes dynamically, and even when multiple frames in a row don't contain transparency.

Is this a known issue? And if so, is it possible to fix it? Attached workflow image contains the embedded workflow in case that's of any help. I already confirmed that the correct integer is received by the Switch node as the correct value gets passed on by its "selected_index" output pin.

Edit: 
For now, I worked around this by moving the filtering of images outside of ComfyUI into a standalone Python script, but I'll keep this issue open here as it does seem to me like this is a bug with the switch node worth looking into, if it isn't a known limitation.

**Comment by ltdrdata** [comment]
The `select_on_prompt` of the Switch node is applied before the workflow execution. This is to handle the connection as if it were virtually disconnected based on the select value before the workflow execution, bypassing the limitations of the current execution model.

Once [PR2666](https://github.com/comfyanonymous/ComfyUI/pull/2666)  is merged, it will change to handle this appropriately.
