### ISSUE TITLE
不能加载节点

### ISSUE THREAD

**Issue by jekee0051** [ltdrdata/ComfyUI-Impact-Pack#544]
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 119, in ensure_subpack
    repo.remotes.origin.pull()
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\remote.py", line 1054, in pull
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\remote.py", line 844, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\cmd.py", line 657, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin
  stderr: 'fatal: unable to access 'https://github.com/ltdrdata/ComfyUI-Impact-Subpack/': OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0'
[ComfyUI-Impact-Pack] Please turn off ComfyUI and remove 'D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\impact_subpack' and restart ComfyUI.
[Impact Pack] EXECUTE: ['D:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\impact_subpack'
req_path: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\impact_subpack\requirements.txt
req_path: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\impact_subpack\requirements.txt
req_path: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\requirements.txt
[Impact Pack] EXECUTE: ['D:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', '-r', 'D:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack-Main\\requirements.txt'] in 'None'
Collecting scikit-image (from -r D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\requirements.txt (line 2))
  Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting opencv-python-headless (from -r D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\requirements.txt (line 5))
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting lazy_loader>=0.3 (from scikit-image->-r D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\requirements.txt (line 2))
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl (24.5 MB)
Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
DEPRECATION: pytorch-lightning 1.8.3 has a non-standard dependency specifier torch>=1.9.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: opencv-python-headless, lazy_loader, scikit-image
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

[Impact Pack] EXECUTE: ['D:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', '-r', 'D:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack-Main\\requirements.txt'] in 'None'
Collecting scikit-image (from -r D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\requirements.txt (line 2))
  Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting opencv-python-headless (from -r D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\requirements.txt (line 5))
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting lazy_loader>=0.3 (from scikit-image->-r D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\requirements.txt (line 2))
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Using cached scikit_image-0.22.0-cp311-cp311-win_amd64.whl (24.5 MB)
Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
DEPRECATION: pytorch-lightning 1.8.3 has a non-standard dependency specifier torch>=1.9.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: opencv-python-headless, lazy_loader, scikit-image
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\cv2\\cv2.pyd'
Consider using the `--user` option or check the permissions.

### ComfyUI-Impact-Pack: Check basic models
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\__init__.py", line 72, in <module>
    import impact.impact_server  # to load server api
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\modules\impact\impact_server.py", line 13, in <module>
    import impact.core as core
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\modules\impact\core.py", line 6, in <module>
    from skimage.measure import label
ModuleNotFoundError: No module named 'skimage'

Cannot import D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main module for custom nodes: No module named 'skimage'
### Loading: ComfyUI-Manager (V2.9)

**Comment by ltdrdata** [comment]
Do not install by downloading a zip and extracting it. Please install through ComfyUI-Manager.
