### ISSUE TITLE
How to add hooks for lowering lora parameters

### ISSUE THREAD

**Issue by rafstahelin** [ltdrdata/ComfyUI-Impact-Pack#545]
Trying to port over Auto1111 Loractl extension functionality to comfity--namely, the ability to use hooks to lower cfg or steps or weights for multiple lora's in the stream before the Ksampler. Are there nodes to do this already?

**Comment by ltdrdata** [comment]
Take a look at this:
https://github.com/asagi4/comfyui-prompt-control?tab=readme-ov-file#scheduling-syntax

**Comment by rafstahelin** [comment]
Awesome
