### ISSUE TITLE
After after update, (IMPORT FAILED) ComfyUI Impact Pack 

### ISSUE THREAD

**Issue by edge513** [ltdrdata/ComfyUI-Impact-Pack#548]
Everything was fine yesterday until I updated Impact Pack through ComfyUI Manager today. 

Now every time I open ComfyUI, this error pops up:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/17948558/a84df870-0441-4d4b-9a81-a5db3e796dc3)

And in the manager, it shows:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/17948558/176bb85a-d65c-4b48-bb99-202c58be1754)

I have tried "Uninstall" and install again, "Update", and "Try Fix", but unfortunately, nothing works. What shall I do, please?

**Comment by ltdrdata** [comment]
Show me the `comfyui.log` file.

**Comment by edge513** [comment]
> Show me the `comfyui.log` file.

Thanks for the reply! Here is the log file:

[comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14912317/comfyui.log)

**Comment by ltdrdata** [comment]
> > Show me the `comfyui.log` file.
> 
> Thanks for the reply! Here is the log file:
> 
> [comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14912317/comfyui.log)

Oh.. you need to update... ComfyUI to latest version.

**Comment by edge513** [comment]
> > > Show me the `comfyui.log` file.
> > 
> > 
> > Thanks for the reply! Here is the log file:
> > [comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/14912317/comfyui.log)
> 
> Oh.. you need to update... ComfyUI to latest version.

It works now! 🔥 Thank you for your help, man!
