### ISSUE TITLE
Cannot convert input to slot

### ISSUE THREAD

**Issue by aresigiqq** [ltdrdata/ComfyUI-Impact-Pack#549]
![1712967401741](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/20410201/d2d2d3aa-9323-4e02-a083-8bf82add4f68)
I'm not sure what's wrong with it, but no menu unfold both of these two options. I can't covert the slot back to widget.

**Comment by ltdrdata** [comment]
That issue should be reported to here:
https://github.com/comfyanonymous/ComfyUI/issues
