### ISSUE TITLE
Update Broke Impact Nodes (invalid syntax)

### ISSUE THREAD

**Issue by Piscabo** [ltdrdata/ComfyUI-Impact-Pack#55]
Today's update Broke something. Impact not loading anymore:
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

## Execute install/(de)activation script for 'A:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 22, in <module>
    import impact.config
  File "A:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\config.py", line 5
    <<<<<<< HEAD
    ^^
SyntaxError: invalid syntax
install/(de)activation script failed: A:\AI_Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/123719842/30285532-84ef-45ec-8d5e-8c335683bb26)

Tried a git pull directly:
ComfyUI-Impact-Pack>git pull
error: Pulling is not possible because you have unmerged files. hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by ltdrdata** [comment]
oops... I recommend reinstall through ComfyUI-Manager.
That is the most easy way to fix that issue.

**Comment by Vetrov0x** [comment]
> oops... I recommend reinstall through ComfyUI-Manager. That is the most easy way to fix that issue.

Not working for me from ComfyUI says that:

git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git submodule update --init --recursive
  stderr: 'git: 'submodule' is not a git command. See 'git --help'.'

**Comment by ltdrdata** [comment]
> > oops... I recommend reinstall through ComfyUI-Manager. That is the most easy way to fix that issue.
> 
> Not working for me from ComfyUI says that:
> 
> git.exc.GitCommandError: Cmd('git') failed due to: exit code(1) cmdline: git submodule update --init --recursive stderr: 'git: 'submodule' is not a git command. See 'git --help'.'

It's seems your gitpython/git version is too old. Try update it.
