### ISSUE TITLE
Problems adding the "UltralyticsDetectorProvider" node. Workflow freezes

### ISSUE THREAD

**Issue by IIILUC4SIII** [ltdrdata/ComfyUI-Impact-Pack#550]
Hello, I'm having problems adding the "UltralyticsDetectorProvider" node, when adding it the ComfyUI workflow freezes, but apparently it's just the workflow view, because when trying to change the workflow, leaving ComfyUI and entering again, it updates the changes made that were not loaded in the view (Example: moving a node through the workflow)except the "UltralyticsDetectorProvider" node,   which continues as in the image, as if it had not been loaded. If anyone can help me, I'm new to the world of programming, AI and everything related, I'm just trying to follow tutorials on You Tube about ComfyUI and I get stuck on issues like this, Thanks in advance!
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/166961541/bf88b34a-6739-41ce-a18f-344faa72d594)

**Comment by ltdrdata** [comment]
press F12 and see the console log.

**Comment by Entropy2019** [comment]
Yes, I've also encountered the same issue when loading the "UltralyticsDetectorProvider" node, causing the workflow to freeze.

I managed to resolve this issue by modifying the model path in the `extra_model_paths.yaml` file located under the ComfyUI source directory, setting it back to the default path.

It seems that there was a problem with reading the `\models\ultralytics` path.

**Comment by ltdrdata** [comment]
> Yes, I've also encountered the same issue when loading the "UltralyticsDetectorProvider" node, causing the workflow to freeze.
> 
> I managed to resolve this issue by modifying the model path in the `extra_model_paths.yaml` file located under the ComfyUI source directory, setting it back to the default path.
> 
> It seems that there was a problem with reading the `\models\ultralytics` path.

I'll check on this later.

**Comment by LesenlyMu** [comment]
I encountered the same error, after adding the “UltralyticsDetectorProvider” node, the entire ComfyUI interface cannot be moved.

In the end, I found that there are no model files like “face_yolov8m.pt” in my ComfyUI/models//ultra lytics/bbox and ComfyUI/models//ultralytics/segm folders. After I manually added the model files to these two directories, this issue was resolved.

**Comment by ltdrdata** [comment]
> I encountered the same error, after adding the “UltralyticsDetectorProvider” node, the entire ComfyUI interface cannot be moved.
> 
> In the end, I found that there are no model files like “face_yolov8m.pt” in my ComfyUI/models//ultra lytics/bbox and ComfyUI/models//ultralytics/segm folders. After I manually added the model files to these two directories, this issue was resolved.

If that path does not exist, it is automatically created in the impact pack, but it needs to be checked.

**Comment by Sherman-Chen** [comment]
if the directory does not contain the model, model_name_widget.value is null
`let is_seg = model_name_widget.value.startsWith('segm/') || model_name_widget.value.includes('-seg');
				if(!is_seg) {`
i change it to:
`
let is_seg = model_name_widget.value && (model_name_widget.value.startsWith('segm/') || model_name_widget.value.includes('-seg'));
`

**Comment by Sherman-Chen** [comment]
> Yes, I've also encountered the same issue when loading the "UltralyticsDetectorProvider" node, causing the workflow to freeze.
> 
> I managed to resolve this issue by modifying the model path in the `extra_model_paths.yaml` file located under the ComfyUI source directory, setting it back to the default path.
> 
> It seems that there was a problem with reading the `\models\ultralytics` path.

confirm if your directory mapping is written like this:
`
  ultralytics_bbox: xxx/ultralytics/bbox

  ultralytics_segm: xxx/ultralytics/segm

  ultralytics: xxx/ultralytics
`

**Comment by Ainaemaet** [comment]
> > Yes, I've also encountered the same issue when loading the "UltralyticsDetectorProvider" node, causing the workflow to freeze.
> > I managed to resolve this issue by modifying the model path in the `extra_model_paths.yaml` file located under the ComfyUI source directory, setting it back to the default path.
> > It seems that there was a problem with reading the `\models\ultralytics` path.
> 
> confirm if your directory mapping is written like this: ` ultralytics_bbox: xxx/ultralytics/bbox
> 
> ultralytics_segm: xxx/ultralytics/segm
> 
> ultralytics: xxx/ultralytics `

Mine is set that way in extra_model_paths.yaml, yet everytime I start comfyui it starts trying to download them to their default location

**Comment by quanzaiyu** [comment]
I encounter the same problem.

I find folder `ComfyUI\models\ultralytics\bbox` is empty.

I executed the following command:

```
mklink /j D:\AI\ComfyUI\ComfyUI\models\ultralytics\bbox D:\AI\SD-WebUI\models\adetailer
```

I made a soft link from folder `SD-WebUI\models\adetailer` to folder `ComfyUI\models\ultralytics\bbox`, then problem solved.

**Comment by ltdrdata** [comment]
> > > Yes, I've also encountered the same issue when loading the "UltralyticsDetectorProvider" node, causing the workflow to freeze.
> > > I managed to resolve this issue by modifying the model path in the `extra_model_paths.yaml` file located under the ComfyUI source directory, setting it back to the default path.
> > > It seems that there was a problem with reading the `\models\ultralytics` path.
> > 
> > 
> > confirm if your directory mapping is written like this: ` ultralytics_bbox: xxx/ultralytics/bbox
> > ultralytics_segm: xxx/ultralytics/segm
> > ultralytics: xxx/ultralytics `
> 
> Mine is set that way in extra_model_paths.yaml, yet everytime I start comfyui it starts trying to download them to their default location

Create `skip_download_model` file into `ComfyUI/custom_nodes` dir.
It will prevent to downloading of model.
