### ISSUE TITLE
make image batch

### ISSUE THREAD

**Issue by Reginald-L** [ltdrdata/ComfyUI-Impact-Pack#556]
Thanks very much for your code. I am curious how do you implement this funcation, make image batch. after load a image1, the node will auto add a image2 input, that is amazing. I debug into your code, there is no any magic in the func, how do you implement that?
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/67569154/fcf149a7-8072-46db-aa09-664fb6f269f4)

**Comment by ltdrdata** [comment]
That is done in JS part.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/971c4a37aa4e77346eaf0ab80adf3972f430bec1/js/impact-pack.js#L375
