### ISSUE TITLE
The option Open in Image Refiner doesnt appear whe you do RMB in Preview Bridge

### ISSUE THREAD

**Issue by derpmagician** [ltdrdata/ComfyUI-Impact-Pack#558]
![e8xIXS6CiD](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/5251673/a6c17bd4-7446-4b14-b6f6-cb760f4e88b3)

**Comment by ltdrdata** [comment]
Image Refiner doesn't belongs to Impact Pack.
It's a feature of https://github.com/ltdrdata/ComfyUI-Workflow-Component

**Comment by derpmagician** [comment]
oh i get it, cloned the project and it appears now,  is not in the manager list tho

**Comment by ltdrdata** [comment]
> oh i get it, cloned the project and it appears now, is not in the manager list tho

You can find that from Dev channel of Manager.
