### ISSUE TITLE
[Api bug]switch any node gets nonetype kwargs

### ISSUE THREAD

**Issue by YacratesWyh** [ltdrdata/ComfyUI-Impact-Pack#566]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8447769/75221fe9-0771-4541-bed3-de6bf18f20d7)
Using switch any node by api gives this bug.

I think the reason is 
        nodelist = kwargs['extra_pnginfo']['workflow']['nodes']
doesn't have extra_pnginfo in the api workflow

**Comment by YacratesWyh** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/8447769/021b23cf-8350-47f3-87cc-1ce1d9cd886f)

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by olegchomp** [comment]
Should be:

```python
if 'extra_pnginfo' in kwargs and kwargs['extra_pnginfo'] is not None:
```

**Comment by ltdrdata** [comment]
> Should be:
> 
> ```python
> if 'extra_pnginfo' in kwargs and kwargs['extra_pnginfo'] is not None:
> ```

Fixed again.
