### ISSUE TITLE
The Scheduler selection node is not connected to a node of the Detailor family.

### ISSUE THREAD

**Issue by Neytiri7** [ltdrdata/ComfyUI-Impact-Pack#568]
The Scheduler selection node is not connected to the Detailer Debug, Face Detailer node in the Detailer family.

It is normally connected to the Ksampler family node,
The Detailer family node cannot be connected.

Please check it quickly.
![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/139053327/bd3a8ee9-0503-4e63-80a5-355ae2264a51)

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/2f4af8f3-9037-4358-980a-1173feded724)

With the recent addition of the AYS scheduler, the basic scheduler selector has become incompatible.
Why don't you use primitive node?

**Comment by Neytiri7** [comment]
Thank you.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/4d7e68fd-1e20-42dd-b5c5-d4e2c69f7d85)

`Impact Scheduler Adapter` node is added.
