### ISSUE TITLE
Mesh Graphormer hand detailer node

### ISSUE THREAD

**Issue by kikoferrer** [ltdrdata/ComfyUI-Impact-Pack#569]
Is there a way to increase sensitivity of hand detection? Like a threshold parameter we can adjust? It works wonders when it do but half the time it doesnt detect anything. Thanks

**Comment by ltdrdata** [comment]
Unfortunately, MeshGraphormer does not offer such a feature natively. I do have one idea, but it might result in a somewhat messy form if used in a workflow.

The basic idea involves repeatedly using inpainting based on openpose until MeshGraphormer is able to generate a mask for the hand.
