### ISSUE TITLE
Error occurred when executing UltralyticsDetectorProvider: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Vetrov0x** [ltdrdata/ComfyUI-Impact-Pack#57]
Error occurred when executing UltralyticsDetectorProvider:

'NoneType' object has no attribute 'get'

File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 144, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 74, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 67, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack\impact\subpack_nodes.py", line 26, in doit
model = subcore.load_yolo(model_path)
File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack\impact\subcore.py", line 15, in load_yolo
return YOLO(model_path)
File "C:\Users\Daedar\Documents\GitHub\AI\system\python\lib\site-packages\ultralytics\yolo\engine\model.py", line 107, in __init__
self._load(model, task)
File "C:\Users\Daedar\Documents\GitHub\AI\system\python\lib\site-packages\ultralytics\yolo\engine\model.py", line 156, in _load
self.model, self.ckpt = attempt_load_one_weight(weights)
File "C:\Users\Daedar\Documents\GitHub\AI\system\python\lib\site-packages\ultralytics\nn\tasks.py", line 579, in attempt_load_one_weight
args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))} # combine model and default args, preferring model args

**Comment by ltdrdata** [comment]
It seems that you haven't downloaded the model you're trying to load. Please check it.
You can download the models through the `install models` function of ComfyUI-Manager.

https://youtu.be/t-JjsEvPX7o?t=114

**Comment by Vetrov0x** [comment]
I have almost all of them but still can't run this node 
<img width="939" alt="Screenshot 2023-07-28 at 17 48 47" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/98167687/4ff5c37a-8299-4be8-b2d6-a8baa889c10b">

**Comment by ltdrdata** [comment]
I think I know why it's happening. It appears that you are running sd-webui-comfyui as an extension, and in this case, the model path may be misaligned, causing it not to be found correctly.
I need to check this.

**Comment by ltdrdata** [comment]
[subpack_nodes.py.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12196463/subpack_nodes.py.txt)

Please replace the file with above file at this location:
`C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack\impact\subpack_nodes.py`

And, when executing the workflow, please post here the part of the log where it says "IMPACT-LOG".

**Comment by Vetrov0x** [comment]
Ok I see, the program thinks that it's malicious, I will add --disable-safe-unpickle flag for now:

#############################
### IMPACT-LOG[1]: bbox/face_yolov8n.pt
### IMPACT-LOG[2]:
###     checkpoints => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\checkpoints', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\Stable-diffusion'], {'.ckpt', '.pth', '.safetensors'})
###     configs => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\configs'], ['.yaml'])
###     loras => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\loras', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\Lora'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     vae => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\vae', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\VAE'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     clip => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\clip'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     unet => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\unet'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     clip_vision => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\clip_vision'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     style_models => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\style_models'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     embeddings => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\embeddings', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\embeddings'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     diffusers => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\diffusers'], ['folder'])
###     vae_approx => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\vae_approx', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\VAE-approx'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     controlnet => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\controlnet', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\t2i_adapter', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\ControlNet', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-controlnet\\models'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     gligen => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\gligen'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     upscale_models => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\upscale_models', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\LDSR', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\SwinIR', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\ScuNET', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\RealESRGAN', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\ESRGAN'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     custom_nodes => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\custom_nodes', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\comfyui_custom_nodes'], [])
###     hypernetworks => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\hypernetworks', 'C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\models\\hypernetworks'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     mmdets_bbox => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\mmdets\\bbox'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     mmdets_segm => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\mmdets\\segm'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     mmdets => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\mmdets'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     sams => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\sams'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     onnx => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\onnx'], {'.onnx'})
###     ultralytics_bbox => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\ultralytics\\bbox'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     ultralytics_segm => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\ultralytics\\segm'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     ultralytics => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\ultralytics'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
###     facerestore_models => (['C:\\Users\\Daedar\\Documents\\GitHub\\AI\\webui\\extensions\\sd-webui-comfyui\\ComfyUI\\models\\facerestore_models'], {'.pt', '.pth', '.safetensors', '.bin', '.ckpt'})
#############################

*** Error verifying pickled file from C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\models\ultralytics\bbox\face_yolov8n.pt
*** The file may be malicious, so the program is not going to read it.
*** You can skip this check with --disable-safe-unpickle commandline argument.
***
    Traceback (most recent call last):
      File "C:\Users\Daedar\Documents\GitHub\AI\webui\modules\safe.py", line 137, in load_with_extra
        check_pt(filename, extra_handler)
      File "C:\Users\Daedar\Documents\GitHub\AI\webui\modules\safe.py", line 95, in check_pt
        unpickler.load()
      File "C:\Users\Daedar\Documents\GitHub\AI\webui\modules\safe.py", line 64, in find_class
        raise Exception(f"global '{module}/{name}' is forbidden")
    Exception: global 'ultralytics.nn.tasks/DetectionModel' is forbidden

---
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack\impact\subpack_nodes.py", line 33, in doit
    model = subcore.load_yolo(model_path)
  File "C:\Users\Daedar\Documents\GitHub\AI\webui\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack\impact\subcore.py", line 15, in load_yolo
    return YOLO(model_path)
  File "C:\Users\Daedar\Documents\GitHub\AI\system\python\lib\site-packages\ultralytics\yolo\engine\model.py", line 107, in __init__
    self._load(model, task)
  File "C:\Users\Daedar\Documents\GitHub\AI\system\python\lib\site-packages\ultralytics\yolo\engine\model.py", line 156, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\Daedar\Documents\GitHub\AI\system\python\lib\site-packages\ultralytics\nn\tasks.py", line 579, in attempt_load_one_weight
    args = {**DEFAULT_CFG_DICT, **(ckpt.get('train_args', {}))}  # combine model and default args, preferring model argsAttributeError: 'NoneType' object has no attribute 'get'

Prompt executed in 0.02 seconds
