### ISSUE TITLE
KSampler (pipe) not working

### ISSUE THREAD

**Issue by RadioVs** [ltdrdata/ComfyUI-Impact-Pack#573]
with denoise above 0.50 it does only a part of the set steps, and with 0.50 it does nothing at all
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/62827539/39d2f163-8562-42c8-a4b7-bb37bba4b9ab)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/62827539/050911a4-27ba-4388-9cee-336455045e2e)

**Comment by ltdrdata** [comment]
This is patched... 
OMG.....
