### ISSUE TITLE
AttributeError: type object 'Yoloworld_ESAM_Zho' has no attribute 'inference_sam_with_boxes'

### ISSUE THREAD

**Issue by gsongX** [ltdrdata/ComfyUI-Impact-Pack#575]
how to solve this problem？

![Snipaste_2024-04-28_18-33-13](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/9738952/02e15706-f277-424a-99b5-979257301ec9)
[workflow.json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/15141799/workflow.json)

Loads EfficientSAM model: (device:CUDA)
!!! Exception during processing!!! type object 'Yoloworld_ESAM_Zho' has no attribute 'inference_sam_with_boxes'
Traceback (most recent call last):
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 62, in doit
    combined_mask, batch_masks = core.make_sam_mask_segmented(sam_model, segs, image, detection_hint, dilation,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 835, in make_sam_mask_segmented
    detected_masks = sam_obj.predict(image, points, plabs, dilated_bbox, threshold)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Starter\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 523, in predict
    detected_masks = self.func_inference.inference_sam_with_boxes(image=image, xyxy=[bbox], model=self.model, device=self.device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Yoloworld_ESAM_Zho' has no attribute 'inference_sam_with_boxes'

Prompt executed in 62.15 seconds

**Comment by ltdrdata** [comment]
That depends on this PR. https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/pull/32
You need to install [a/forked version](https://github.com/ltdrdata/ComfyUI-YoloWorld-EfficientSAM) to use ESAM feature since it isn't merged yet.

**Comment by gsongX** [comment]
thanks

**Comment by a22999** [comment]
thanks!!!!!
