### ISSUE TITLE
ImageReceiver cannot update

### ISSUE THREAD

**Issue by TFL-TFL** [ltdrdata/ComfyUI-Impact-Pack#578]
Convert link_id to the input value,  imageReceiver fails to update.
The minimal reproducible workflow is as follows:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/63155358/50a399d4-53e8-4519-9c3a-05df59e4c4c0)

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by TFL-TFL** [comment]
> This is fixed.

Thanks.
