### ISSUE TITLE
"Convert wildcard_text to input" doesn't accept incoming text

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ltdrdata/ComfyUI-Impact-Pack#579]
I'm trying to use another node to input the prompt, and embedding from another node I selected the "convert wildcard_text to input" and attached the node, but the input is always ignored and doesn't appear in the wildcard node.

**Comment by PurplefinNeptuna** [comment]
it also doesn't accept seed

**Comment by ltdrdata** [comment]
connect to populated_text instead of wildcard_text.

**Comment by GalaxyTimeMachine** [comment]
This doesn't allow it to convert wildcards that are in the text, does it?

**Comment by ltdrdata** [comment]
> This doesn't allow it to convert wildcards that are in the text, does it?

The "wildcard_text" serves as a temporary space to generate "populated_text" and is used to preserve the original prompt in the saved workflow. When the workflow is executed, it is the "populated_text" that actually engages.

"wildcard_text" completes all tasks before the workflow is executed, and from the point the workflow starts, it no longer plays any role.

However, for cases like yours where you wish to inject a wildcard from the outside, ImpactWildcard... nodes provide the capability to populate internally one more time when "populated_text" is delivered. Therefore, you should connect it into "populated_text." Note, however, that the mode must be set to "Fixed."

**Comment by GalaxyTimeMachine** [comment]
That doesn't populate the wildcards.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/52193044/aadf423b-8e49-456b-9c5d-0d528ed75b83)

**Comment by ltdrdata** [comment]
> That doesn't populate the wildcards. ![image](https://private-user-images.githubusercontent.com/52193044/328920886-aadf423b-8e49-456b-9c5d-0d528ed75b83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODgwMzEsIm5iZiI6MTcxNTE4NzczMSwicGF0aCI6Ii81MjE5MzA0NC8zMjg5MjA4ODYtYWFkZjQyM2ItOGU0OS00NTZiLTljNWQtMGQ1MjhlZDc1YjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE3MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzZDRiYzRlMTE3OWViMTllMDhkNzUxYWQ4ZjM0NDQ3OTUyYjFlMjAxNDdiZGI1ZDc0NDVkNWZlZDBmNDVkYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FtjfkVbI3mWhImrybB90YmE53l2-k1Pdj9vo8LGcqdk)

That is fixed.

**Comment by ltdrdata** [comment]
> it also doesn't accept seed

converted seed can be applied if you use converted populated_text.
