### ISSUE TITLE
ComfyUI/models/sams not installed

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ltdrdata/ComfyUI-Impact-Pack#58]
I just did a fresh build of ComfyUI portable and re-installed each of the custom node packs I use. I then noticed that there was no model selected in the "SAMLoader" node, and none were available. On comparing the new install to my previous one, the "ComfyUI/models/sams" directory is not installed.

I'm not sure if the detection models should be installed by default, or if users are expected to install themselves, but it is not clear and this would put some new users off using the nodes.

**Comment by ltdrdata** [comment]
I confirmed that there is an issue with downloading the smallest base model as originally intended. However, it should be possible to manually download it using ComfyUI-Manager.

**Comment by ltdrdata** [comment]
I'd patched this on V3.1.1

**Comment by GalaxyTimeMachine** [comment]
I had a fresh install a few hours ago and installed all the custom nodes before starting ComfyUI. I did have a problem with another pack not installing the requirements, but deleting the pack and re-installing forced it to do that and it worked. I wonder if there is a problem with many custom nodes being installed before startup, and that's what happened here...?

**Comment by ltdrdata** [comment]
> I had a fresh install a few hours ago and installed all the custom nodes before starting ComfyUI. I did have a problem with another pack not installing the requirements, but deleting the pack and re-installing forced it to do that and it worked. I wonder if there is a problem with many custom nodes being installed before startup, and that's what happened here...?

There is possibility of conflict between custom nodes.
