### ISSUE TITLE
Can't get FaceDetailer nodes to work via API

### ISSUE THREAD

**Issue by physis123** [ltdrdata/ComfyUI-Impact-Pack#580]
I'm trying to run a workflow via API that includes a FaceDetailer node. 

The workflow works fine in ComfyUI directly.

I can also run other workflows via API successfully that don't include the FaceDetailer.

However, when I include a FaceDetailer node, I get a 400 response from the API and the following error from the ComfyUI terminal:

```
- Exception when validating node: '26'
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': "Exception when validating node: '26'", 'extra_info': {}}
```
Node 26 looks like this, copied directly from the saved workflow using the "Save (API Format)" button without any changes:

```
 "26": {
    "inputs": {
      "guide_size": 384,
      "guide_size_for": true,
      "max_size": 1024,
      "seed": 745172403401445,
      "steps": 8,
      "cfg": 8,
      "sampler_name": "euler",
      "scheduler": "normal",
      "denoise": 0.5,
      "feather": 5,
      "noise_mask": true,
      "force_inpaint": false,
      "bbox_threshold": 0.5,
      "bbox_dilation": 10,
      "bbox_crop_factor": 3,
      "sam_detection_hint": "center-1",
      "sam_dilation": 0,
      "sam_threshold": 0.93,
      "sam_bbox_expansion": 0,
      "sam_mask_hint_threshold": 0.7,
      "sam_mask_hint_use_negative": "False",
      "drop_size": 10,
      "refiner_ratio": 0.2,
      "cycle": 1,
      "inpaint_model": false,
      "noise_mask_feather": 20,
      "image": [
        "8",
        0
      ],
      "detailer_pipe": [
        "29",
        0
      ]
    },
    "class_type": "FaceDetailerPipe",
    "_meta": {
      "title": "FaceDetailer (pipe)"
    }
  },
```

Any ideas why this node would cause an error? Or is there a way to see more detail on why it is failing validation?

Thanks.

**Comment by ltdrdata** [comment]
The prompt looks fine. Is the Impact Pack up to date?

**Comment by physis123** [comment]
Thanks for the reply. I did get it working with a slightly different version. I think I must have just had a typo/mistake somewhere else in the API data.
