### ISSUE TITLE
Bug: Cant reroute from 'Switch (Any)' node.

### ISSUE THREAD

**Issue by 925-Studio** [ltdrdata/ComfyUI-Impact-Pack#581]
Thank you for making this custom_nodes, it very useful. But I found a small problem but kind annoying which there is no connection line between this node and reroute node. I updated to the latest version but nothing changed. Maybe you can check it out when you have time. Thank you!

**Comment by ltdrdata** [comment]
Previously, reroute connections were allowed, but there was an issue where the reroute nodes randomly removed connections when loading the workflow. Therefore, to prevent such issues, they were fundamentally blocked.

But you can use rgthree's reroute instead.

**Comment by 925-Studio** [comment]
I see. The rgthree's reroute worked, thanks for the tip.
