### ISSUE TITLE
An issue with Detailer (SEGS/pipe)

### ISSUE THREAD

**Issue by APCOTech** [ltdrdata/ComfyUI-Impact-Pack#584]
Hi, I am very sorry if this is mentioned before but I do not know what to search for
I am not an expert but I like your videos and I just use the workflows you provide. The issue is with workflow with this video (https://www.youtube.com/watch?v=bEqF4jbLCOc) ComfyUI-Impact-Pack - Workflow: Upscaling with Make Tile SEGS

I am using it for a long time now to upscale and detail my images and it works perfectly everytime. but recently, four days ago, after an update. it blurs everything in the image. both of the (Detailer (SEGS/pipe)) nodes. hide any details in the images and produce flat areas. As I said, I am not an expert and I do not know what's got broken since I never edit anything in it but the prompt and the bbox_size.
I would be very grateful for any help.

Here are the sittings I use: (using juggernautXL_juggernautX.safetensors)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23286083/2ca744a2-8db7-4771-a5b2-8ed9e8b3bcf1)
 
and here is an example:
(image before detailing)
![i9a8UD4bT5qMY8eox787PQ](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23286083/663575ea-a9ff-4f43-b7bb-a7170ab25520)

and the blurry result:
![ComfyUI_temp_ttjnb_00002_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23286083/8b55c867-a047-4372-96e6-fe185e6e77f0)
most of the details in the image got blurred.

**Comment by ltdrdata** [comment]
What is your Impact Pack version?

**Comment by APCOTech** [comment]
ComfyUI-Impact-Pack (V5.5)
ComfyUI-Impact-Pack (Subpack: V0.5)
ComfyUI: 2158[daa92a](2024-05-03)
Manager: V2.24.1

**Comment by ltdrdata** [comment]
Do you use mac?

**Comment by APCOTech** [comment]
No, windows 11

**Comment by ltdrdata** [comment]
> No, windows 11

When I tested with your ComfyUI and Impact Pack versions along with the model you provided, I am not experiencing any issues on my end.

Disable all other custom nodes and only activate the essential custom nodes for testing.

**Comment by APCOTech** [comment]
Okay, I will try it now.

**Comment by ltdrdata** [comment]
And the change doesn't just make it blurry, it seems like the style has changed. Check the prompt as well.

**Comment by APCOTech** [comment]
> And the change doesn't just make it blurry, it seems like the style has changed. Check the prompt as well.

I doubted that at first, but I used my old generations with the same workflow, but the results are totally different. I have disabled a lot of extensions and I got the same blurry result. I will disable the rest.

**Comment by APCOTech** [comment]
![z2Untitled](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23286083/a5f0f7fb-6dc5-4e90-be25-120f2dce073d)
![z1Untitled](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23286083/52408908-aefc-4d1d-9668-57f9208b6d01)
Nothing happened,  I disabled all extensions, and the prompt is very simple.

**Comment by ltdrdata** [comment]
Do you use special command line arguments to launch ComfyUI?
And share me your workflow.

**Comment by APCOTech** [comment]
> Do you use special command line arguments to launch ComfyUI? And share me your workflow.

No, nothing special
".\python_embeded\python.exe -s ComfyUI\main.py --disable-auto-launch --windows-standalone-build --output-directory=X:\COMFYUI-OUTPUT"

Seems like it was a mistake from my side. I am using your workflow from youtube which is using the DetailerDebug (SEGS/pipe), I switched now to Detailer (SEGS/pipe) and the result seem much better, could this be the reason?

[workflow(SEGS_pipe).json](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/15208338/workflow.SEGS_pipe.json)
![ComfyUI_temp_mrrvo_00001_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23286083/3edc16e0-5671-4690-8131-f5c36d7dced6)

**Comment by ltdrdata** [comment]
That should not be affected. 

This is the result of your workflow. There is no problem.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/f3b7f01f-f60e-4ef0-92bd-3764aeaa612d)

![ComfyUI_temp_miflq_00001_](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/e0fe84a8-7188-4255-a900-1519b0046326)

**Comment by APCOTech** [comment]
Well, seems like I found the problem. It is the PreviewDetailerHookProvider. when I mute it, the detailer works perfectly. But I do not understand the reason. is it normal or am I doing something wrong?

EDIT: I enabled all the disabled extensions and still the same as my video. The PreviewDetailerHookProvider blurs the result. 

https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/23286083/bbd1b4d0-c33a-4fd5-a8f7-8db988dae732

**Comment by ltdrdata** [comment]
> Well, seems like I found the problem. It is the PreviewDetailerHookProvider. when I mute it, the detailer works perfectly. But I do not understand the reason. is it normal or am I doing something wrong?
> 
> EDIT: I enabled all the disabled extensions and still the same as my video. The PreviewDetailerHookProvider blurs the result.
> 
>  ComfyUI.-.Google.Chrome.2024-05-04.11-33-43.mp4

Gotcha... Maybe I didn't separated it from original latent.

**Comment by ltdrdata** [comment]
This issue is fixed.
