### ISSUE TITLE
Feature request : Polygonal lasso tool

### ISSUE THREAD

**Issue by MaraScott** [ltdrdata/ComfyUI-Impact-Pack#589]
Hi @ltdrdata ,

do you think you could add the Polygonal lasso tool to your preview bridge node ?

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/482210/b9177b6a-2e6c-4583-a816-c1014b499eb1)

**Comment by ltdrdata** [comment]
Unfortunately, that's not an area where I excel.
