### ISSUE TITLE
MASK - MASK not work

### ISSUE THREAD

**Issue by zhangfeifei0907** [ltdrdata/ComfyUI-Impact-Pack#593]
![screenshot-20240511-150755](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/12770631/094f0139-cadf-4bd9-bd0f-4f4610f156ab)

I try to use Mask&mask,mask - mask,mask +mask,but the result is the same. The previous results were correct, but the current results are wrong.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/d1d730f3-2bff-4ebf-bfb9-8ea8673a0270)


There is no problem.

Make sure the `mask1` and `mask2` through Mask Preview.

**Comment by zhangfeifei0907** [comment]
my mistake,the sourse image haved change,sorry
