### ISSUE TITLE
Bug in lmpactConditionalBranchSelMode bug

### ISSUE THREAD

**Issue by 807502278** [ltdrdata/ComfyUI-Impact-Pack#595]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/46019416/2bd167a5-ce76-42e7-b82e-d2a8dc171e5e)
The lmpactConditionalBranchSelMode  node is very useful！But there is a bug: when cond is converted to input, it will become invalid

**Comment by ltdrdata** [comment]
The select_on_prompt mode does not support converted input, except for primitives, because it must be determined before the execution of the workflow

**Comment by 807502278** [comment]
Primitives cannot be used in the API, can a supported Boolean be added to the impact?
