### ISSUE TITLE
Can we create a Primitive that supports API?

### ISSUE THREAD

**Issue by 807502278** [ltdrdata/ComfyUI-Impact-Pack#596]

**Comment by 807502278** [comment]
The Switch (Any) node cannot be used in the API either...

**Comment by sparkleMing** [comment]
You can use it by passing workflow json content in prompt, like 
`p = {"prompt": prompt, "clienƒt_id": client_id, "extra_data": {"extra_pnginfo": {"workflow": workflow}}}`
But this isn't an elegant way, because workflow json content usually very large, bring it in each api request waste the bandwidth.

**Comment by ltdrdata** [comment]
In my opinion, the simplest method is to create a Primitive node as a backend custom node, install it, and use it. After all, the only role of a primitive node is to directly pass the widget value as the result, so there's no need for complex implementation.

However, when exporting a workflow for API use, Primitive nodes are already populated with widget values, so using Primitive node as an API doesn't make sense.

**Comment by 807502278** [comment]
> You can use it by passing workflow json content in prompt, like `p = {"prompt": prompt, "clienƒt_id": client_id, "extra_data": {"extra_pnginfo": {"workflow": workflow}}}` But this isn't an elegant way, because workflow json content usually very large, bring it in each api request waste the bandwidth.

That's true. I'll see if I can make a primarynode myself

**Comment by 807502278** [comment]
> In my opinion, the simplest method is to create a Primitive node as a backend custom node, install it, and use it. After all, the only role of a primitive node is to directly pass the widget value as the result, so there's no need for complex implementation.
> 
> However, when exporting a workflow for API use, Primitive nodes are already populated with widget values, so using Primitive node as an API doesn't make sense.

I couldn't find the primitivenode in the py file in the root directory of ComfyUI. I only know Python but not JavaScript...

**Comment by ltdrdata** [comment]
> > In my opinion, the simplest method is to create a Primitive node as a backend custom node, install it, and use it. After all, the only role of a primitive node is to directly pass the widget value as the result, so there's no need for complex implementation.
> > However, when exporting a workflow for API use, Primitive nodes are already populated with widget values, so using Primitive node as an API doesn't make sense.
> 
> I couldn't find the primitivenode in the py file in the root directory of ComfyUI. I only know Python but not JavaScript...

The Primitive node is a virtual node. You just have to make a node which mimics the behavior.

**Comment by 807502278** [comment]
I don't understand the mechanism of comfyui, I only know how to create nodes like this
```
class node1:
    @classmethod
    def INPUT_TYPES(s): 
        return {...
```
Can you recommend tutorials in this area?

**Comment by 807502278** [comment]
Super envious that you can write some strange nodes.

**Comment by ltdrdata** [comment]
Kinda this approach.

```
class PrimitiveNode:
    @classmethod
    def INPUT_TYPES(s):
        return { "required": { "value": ("*",), }, },
        
    RETURN_TYPES = ("*",)
    FUNCTION = "doit"
    CATEGORY = "API"

    @staticmethod
    def doit(**kwargs):
        return (kwargs['value'], )


NODE_CLASS_MAPPINGS = {
    "PrimitiveNode": PrimitiveNode
}
```

However, this usage only applies when you generate and execute prompts from the workflow rather than from the prompt itself.

Are you trying to directly create and insert into a PrimitiveNode for an API-based prompt?

I can't think of any situation where a Primitive Node would be needed in the backend. If you're making an API call, you can programmatically input values directly into the widget values instead of using a Primitive Node.

**Comment by 807502278** [comment]
Thank your code. I learned how to output arbitrary data.

I want the `select_on_prompt` option of the `cond` of the `ImpactConditionalBranchSelMode` node to not be invalid when converting to input, and it can also be used in the api at the same time.

Reasons for not using front-end programming to change: There may be many `cond` conversions. If changed, it is necessary to find it in the api, which is very troublesome. Moreover, when changing the workflow, it may also cause changes in the numbering, and it is necessary to sort it out again. (I find the value of `cond` through the node number. I don't know if there is a better method)

**Comment by ltdrdata** [comment]
`Switch (Any)` allows dynamic selection since v7.2.1.
use `select_on_execution`.
