### ISSUE TITLE
Pleace Help!!  Segs & Mask

### ISSUE THREAD

**Issue by Azk915** [ltdrdata/ComfyUI-Impact-Pack#598]
Hello everyone,

I’m writing to ask about an issue I’ve been experiencing. I’ve already installed the node both manually and using the Manager, but I keep encountering the same problem. Every time I load, the missing nodes from the ConfyUI Impact Pack (which is currently installed) appear. I’ve tried updating and reinstalling both ConfyUI and the node event update and downgrade (python, ConfyUI, manager) and check python path, but nothing changes.

Thank you to everyone who takes the time to read this post.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/111326374/8ed5e405-fd5f-4465-9719-c09a3f037141)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/111326374/0485215f-74f0-479e-8337-561fef48c7e3)

**Comment by ltdrdata** [comment]
That node is renamed. You have to replace that node to ImpactSegsAndMask.
