### ISSUE TITLE
Mask to Segs not working

### ISSUE THREAD

**Issue by AmeliaJaneMurphy** [ltdrdata/ComfyUI-Impact-Pack#599]
Hello Hello!

Thanks so much on all your hard work on these nodes! Quick question -

So, a friend and I are running the exact same workflow, with the exact same input images, and their Mask To Segs is working, while mine is doing this? A hundred different little pixel grabs.

![Screenshot 2024-05-14 171121](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/13773804/bbc25f00-50c5-429a-ab7a-d8531fa8dbbd)

I updated comfy, completely deleted and then reinstalled the impact pact and it's still not working. It's weird cause it is working fine for my friend. I noticed there was an update today, not sure if that is causing it, or if there is something else that could be causing it. 

Any help would be appreciated! Thanks so much ;)

**Comment by ltdrdata** [comment]
> Hello Hello!
> 
> Thanks so much on all your hard work on these nodes! Quick question -
> 
> So, a friend and I are running the exact same workflow, with the exact same input images, and their Mask To Segs is working, while mine is doing this? A hundred different little pixel grabs.
> 
> ![Screenshot 2024-05-14 171121](https://private-user-images.githubusercontent.com/13773804/330623052-bbc25f00-50c5-429a-ab7a-d8531fa8dbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzM5MjEsIm5iZiI6MTcxNTczMzYyMSwicGF0aCI6Ii8xMzc3MzgwNC8zMzA2MjMwNTItYmJjMjVmMDAtNTBjNS00MjlhLWFiN2EtZDg1MzFmYThkYmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAwNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0M2QyYWRkNzY0NTI1YmMzZDk2MTczMDc1ZmUzYjA4ZWQwMzhjYzc2ZDNkNDIxOTk5OGE2MTFmYzg2YWRiNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wexC6Q_zeDi2FxwK9x-cvv2TBhR7x2J3LJs-k5LZmFM)
> 
> I updated comfy, completely deleted and then reinstalled the impact pact and it's still not working. It's weird cause it is working fine for my friend. I noticed there was an update today, not sure if that is causing it, or if there is something else that could be causing it.
> 
> Any help would be appreciated! Thanks so much ;)

I can't help you without your original input image.

**Comment by AmeliaJaneMurphy** [comment]
thanks! I just figured it out, there was a color correction being done on the mask that was causing an issue, dunno why it didn't flag on the other computer. Thanks so much!

**Comment by ltdrdata** [comment]
> thanks! I just figured it out, there was a color correction being done on the mask that was causing an issue, dunno why it didn't flag on the other computer. Thanks so much!

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/f26c632a-a5c8-47bf-827c-050df2f57643)

Be careful not to make the drop_size too small.
