### ISSUE TITLE
Choice Masked content in Detailer SEGS/pipe

### ISSUE THREAD

**Issue by ushan0v** [ltdrdata/ComfyUI-Impact-Pack#600]
I am using the Detailer SEGS/pipe in inpaint_model mode. But the generation is based on the image under the highlighted mask, which is why I get the wrong result, which is associated with the original image. In AUTOMATIC1111, inpaint has a "Masked content" parameter where you can select fill and the problem was solved. How can I do this in ComfyUI, how do I select fill mode? As I understand it, there is an original mode in the Detailer. 

Masked content in AUTOMATIC1111:
![Masked content in AUTOMATIC1111](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/142658494/637c2d91-dba0-4fd9-a9ff-7fb978ab997e)

the result is in AUTOMATIC1111 with fill mode:
![result in AUTOMATIC1111](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/142658494/ff444d1e-6795-4a06-9d7d-1c50fbc3445c)

incorrect result in ComfyUI
![result in ComfyUI](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/142658494/b487b28b-e622-451b-a349-553842bb281e)

Help please

**Comment by ltdrdata** [comment]
It seems that you need VAEEncodeForInpaint. Unfortunately, Detailer doesn't support that encoding mode.
I'll take a look later.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/3efac978-911b-4bde-ac24-db04eb7a743b)

Upon reflection, setting inpaint_model to true and denoise to 1.0 should make it operate in fill mode.
