### ISSUE TITLE
Question about Upscale node

### ISSUE THREAD

**Issue by nodegraphics** [ltdrdata/ComfyUI-Impact-Pack#601]
Hello, I like to know what the difference is between `simple and geometric` options under `Iterative Upscale > step_mode` node ? 

<img width="389" alt="Screenshot - 2024-05-15 16 05 02" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/10071439/bfe59839-603c-4fb0-be31-81e623b78af5">

**Comment by ltdrdata** [comment]
For example (upscale_factor = 2.0, steps = 5)

**Simple mode**: Simply divides by n to determine the scale factor for each step.
1.0 + 0.2 + 0.2 + 0.2 + 0.2 + 0.2 = 2.0
1 step = 1.2
2 step = 1.4
3 step = 1.6
4 step = 1.8
5 step = 2.0

**Geometric mode**: Determines the scale factor to increase by the same ratio at each step.
1.0 * 1.1487 * 1.1487 * 1.1487 * 1.1487 * 1.1487 = 2.0
1 step = 1.1487
2 step = 1.3195
3 step = 1.5157
4 step = 1.7411
5 step = 2.0
