### ISSUE TITLE
Increase inputs to 5 in the switch ( images, mask )

### ISSUE THREAD

**Issue by JorgeR81** [ltdrdata/ComfyUI-Impact-Pack#602]
I use this switch with the IPAdapter, FaceID and InstantID nodes.

Normally, I use a batch of images or multiple embeds. 
But I also use the switch to select an attention mask, or an `image_kps`, from the same Load Image nodes.

Now it's possible to use 5 image embeddings, and it's also easier to use 5 image batches ( with a node from the same creator ).

Can you also increase the switch inputs to 5 ?

![5](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/72734038/aa29ab18-3da3-49c6-96ae-017936c65dc5)

**Comment by ltdrdata** [comment]
Just you `Switch (Any)`. It is scalable.

**Comment by JorgeR81** [comment]
OK, no problem.

I only suggested this because I was under the impression this switch was created for better compatibility with the IPAdapter ( like some of the nodes on the Inspire Pack ). 
I only realized it was from the Impact Pack, when I was opening the issue ...

**Comment by ltdrdata** [comment]
> OK, no problem.
> 
> I only suggested this because I was under the impression this switch was created for better compatibility with the IPAdapter ( like some of the nodes on the Inspire Pack ). I only realized it was from the Impact Pack, when I was opening the issue ...

Actually. That node is sort of a legacy node. I want to remove that node but I am keeping it for backward compatibility.

**Comment by JorgeR81** [comment]
Yes, I also thought it could be a legacy node.
I sometimes feel confused about which nodes to use, because of all the legacy ones.

When you decide it's time, I think it's probably best to do just a big break all at once, like the IPAdapter creator did.
Before that, you can put a list with all the deprecated nodes, on top of the github page 
And maybe do an announcement on the Manager feed.
As I improve my workflows and install new custom nodes, I always "migrate" the images I really like, to the new workflows.
