### ISSUE TITLE
[Feature Request] Scale Conditioning

### ISSUE THREAD

**Issue by Bocian-1** [ltdrdata/ComfyUI-Impact-Pack#605]
[Davemane42 ](https://github.com/Davemane42/ComfyUI_Dave_CustomNode ) has something like this (ConditioningStretch) but the pack is outdated and has been left unmaintained for a while now and I can't find a good alternative for that node anywhere else.
As someone who posts their workflows online I'd like to also get rid of that dependency tbh.

Specifically, it should be able to scale the conditioning while preserving information like areas set with `conditioning (set mask)` or controlnets (also scaled of course).

Not sure if fits better here on in Inspire Pack, though tbh I think it's something that should go into base Comfy

**Comment by ltdrdata** [comment]
Adding a new node to the core might be somewhat burdensome, so I'll add it to the Inspire Pack for now.

**Comment by ltdrdata** [comment]
This is added to Inspire Pack v0.71
