### ISSUE TITLE
SEGM Detector (SEGS) (possibly others) crops mask when person is at the bottom of the image

### ISSUE THREAD

**Issue by sahinincik** [ltdrdata/ComfyUI-Impact-Pack#606]
When the detected person is at the bottom, it crops the mask from bottom and top

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/46478543/0af70fde-709a-40ea-91fa-c1d6d574766b)

**Comment by ltdrdata** [comment]
I am unable to reproduce the issue.
What is the resolution of the image in issue?

**Comment by sahinincik** [comment]
here you can try this

[https://i.dawn.com/primary/2024/03/230036360c08c56.webp](https://i.dawn.com/primary/2024/03/230036360c08c56.webp)

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by sahinincik** [comment]
that was fast, thank you!!!
