### ISSUE TITLE
Queue Trigger adding twice

### ISSUE THREAD

**Issue by DasKatzchen** [ltdrdata/ComfyUI-Impact-Pack#609]
Any time I trigger the "Queue Trigger" node, it adds _two_ prompts to the queue, one of which bails out almost immediately. I say _almost_ because it still iterates the counter on the "Load Image Batch" node from WAS, which results in only every _other_ image getting processed.

**Comment by DasKatzchen** [comment]
Just happened to notice I had a second ComfyUI tab open by accident. When I closed it, the expected behavior was restored.

**Comment by Kipacc** [comment]
> Just happened to notice I had a second ComfyUI tab open by accident. When I closed it, the expected behavior was restored.

Just wanted to say thank you lol..
