### ISSUE TITLE
SegmDetectorCombined_v2 and BboxDetectorCombined_v2 nodes output mask errors

### ISSUE THREAD

**Issue by petercham** [ltdrdata/ComfyUI-Impact-Pack#612]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/3765653/02e8cbe0-1e47-46a8-b8b4-a585f2391468)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/3765653/533450ba-dad9-4ec3-98d2-0df70a741e55)
Having used these two nodes in an earlier version, and yolo's person model, it is possible to split the human mask properly

**Comment by petercham** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/3765653/209dae92-220a-4811-aedc-41c036c9bc43)
To prevent misunderstandings, another run was made using ComfyUI's default LoadImage node, with the same result

**Comment by petercham** [comment]
I printed the shape of the fetched image before both detector executions and got the following printout

Segm image: torch.Size([1, 3444, 5472, 3])

0: 416x640 (no detections), 181.1ms
Speed: 3.6ms preprocess, 181.1ms inference, 1.0ms postprocess per image at shape (1, 3, 416, 640)
Bbox image: torch.Size([1, 3444, 5472, 3])

0: 416x640 (no detections), 130.0ms
Speed: 3.0ms preprocess, 130.0ms inference, 2.0ms postprocess per image at shape (1, 3, 416, 640)

**Comment by ltdrdata** [comment]
You have to lower the threshold.

**Comment by petercham** [comment]
> You have to lower the threshold.

Is there any way to lift the restriction since the goal is to crop an oversized source image by splitting the human body? I couldn't find where the exact method is in your source code

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/cc4f64e4-32d0-4a14-bf84-9938131f573c)
I had to upscale because the resolution was too low from capturing your image, but your image should work fine without adjusting the threshold.

**Comment by petercham** [comment]
![1igyp3msfthm3wgqbxifytnmg (2)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/3765653/0b83b6c3-597e-45e4-8fe2-c302945ff520)
I don't know if sending you the source image helps

**Comment by petercham** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/3765653/f8177c3c-9bff-4793-b523-9abd52f618be)
There are actually two problems here:
1. I'm not sure if it's a model issue? I am able to detect faces using the Retina model, yolo's box model, and using yolo's whichever seg model returns the same results.
2. if it does exceed the detection threshold, can't it return the width and height of the source image? Otherwise, because the width and height have been switched, there will be problems in subsequent reprocessing.

**Comment by ltdrdata** [comment]
> There are actually two problems here:
> 
> 1. I'm not sure if it's a model issue? I am able to detect faces using the Retina model, yolo's box model, and using yolo's whichever seg model returns the same results.
> 2. if it does exceed the detection threshold, can't it return the width and height of the source image? Otherwise, because the width and height have been switched, there will be problems in subsequent reprocessing.

The threshold has nothing to do with width and height. It's about how confident the model is in its detection. The threshold filters out detections below a certain confidence level, considering them false positives.

Additionally, this model is having difficulty identifying the objects in the image you used.
