### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by YifanLiang-hust** [ltdrdata/ComfyUI-Impact-Pack#613]
Extension install failed: Install extension ComfyUI Impact Pack failed: Install(git-clone) error: https://github.com/ltdrdata/ComfyUI-Impact-Pack / Error: Command failed with exit code 1: D:\conda\envs\comflowy\Scripts\pip.exe install -r requirements.txt ERROR: Could not install packages due to an OSError: [WinError 5] �ܾ����ʡ�: 'D:\\conda\\envs\\comflowy\\Lib\\site-packages\\cv2\\cv2.pyd' Consider using the `--user` option or check the permissions. Requirement already satisfied: segment-anything in d:\conda\envs\comflowy\lib\site-packages (from -r requirements.txt (line 1)) (1.0) Collecting scikit-image (from -r requirements.txt (line 2)) Using cached scikit_image-0.23.2-cp310-cp310-win_amd64.whl.metadata (14 kB) Requirement already satisfied: piexif in d:\conda\envs\comflowy\lib\site-packages (from -r requirements.txt (line 3)) (1.1.3) Requirement already satisfied: transformers in d:\conda\envs\comflowy\lib\site-packages (from -r requirements.txt (line 4)) (4.41.1) Collecting opencv-python-headless (from -r requirements.txt (line 5)) Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl.metadata (20 kB) Requirement already satisfied: GitPython in d:\conda\envs\comflowy\lib\site-packages (from -r requirements.txt (line 6)) (3.1.43) Requirement already satisfied: scipy>=1.11.4 in d:\conda\envs\comflowy\lib\site-packages (from -r requirements.txt (line 7)) (1.13.1) Requirement already satisfied: numpy>=1.23 in d:\conda\envs\comflowy\lib\site-packages (from scikit-image->-r requirements.txt (line 2)) (1.25.2) Requirement already satisfied: networkx>=2.8 in d:\conda\envs\comflowy\lib\site-packages (from scikit-image->-r requirements.txt (line 2)) (3.3) Requirement already satisfied: pillow>=9.1 in d:\conda\envs\comflowy\lib\site-packages (from scikit-image->-r requirements.txt (line 2)) (10.3.0) Collecting imageio>=2.33 (from scikit-image->-r requirements.txt (line 2)) Using cached imageio-2.34.1-py3-none-any.whl.metadata (4.9 kB) Requirement already satisfied: tifffile>=2022.8.12 in d:\conda\envs\comflowy\lib\site-packages (from scikit-image->-r requirements.txt (line 2)) (2024.5.22) Requirement already satisfied: packaging>=21 in d:\conda\envs\comflowy\lib\site-packages (from scikit-image->-r requirements.txt (line 2)) (24.0) Requirement already satisfied: lazy-loader>=0.4 in d:\conda\envs\comflowy\lib\site-packages (from scikit-image->-r requirements.txt (line 2)) (0.4) Requirement already satisfied: filelock in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (3.14.0) Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (0.23.2) Requirement already satisfied: pyyaml>=5.1 in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (6.0.1) Requirement already satisfied: regex!=2019.12.17 in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (2024.5.15) Requirement already satisfied: requests in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (2.31.0) Requirement already satisfied: tokenizers<0.20,>=0.19 in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (0.19.1) Requirement already satisfied: safetensors>=0.4.1 in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (0.4.3) Requirement already satisfied: tqdm>=4.27 in d:\conda\envs\comflowy\lib\site-packages (from transformers->-r requirements.txt (line 4)) (4.66.4) Requirement already satisfied: gitdb<5,>=4.0.1 in d:\conda\envs\comflowy\lib\site-packages (from GitPython->-r requirements.txt (line 6)) (4.0.11) Requirement already satisfied: smmap<6,>=3.0.1 in d:\conda\envs\comflowy\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->-r requirements.txt (line 6)) (5.0.1) Requirement already satisfied: fsspec>=2023.5.0 in d:\conda\envs\comflowy\lib\site-packages (from huggingface-hub<1.0,>=0.23.0->transformers->-r requirements.txt (line 4)) (2024.5.0) Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\conda\envs\comflowy\lib\site-packages (from huggingface-hub<1.0,>=0.23.0->transformers->-r requirements.txt (line 4)) (4.12.0) Requirement already satisfied: colorama in d:\conda\envs\comflowy\lib\site-packages (from tqdm>=4.27->transformers->-r requirements.txt (line 4)) (0.4.4) Requirement already satisfied: charset-normalizer<4,>=2 in d:\conda\envs\comflowy\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (3.3.2) Requirement already satisfied: idna<4,>=2.5 in d:\conda\envs\comflowy\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (3.7) Requirement already satisfied: urllib3<3,>=1.21.1 in d:\conda\envs\comflowy\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (1.26.18) Requirement already satisfied: certifi>=2017.4.17 in d:\conda\envs\comflowy\lib\site-packages (from requests->transformers->-r requirements.txt (line 4)) (2024.2.2) Using cached scikit_image-0.23.2-cp310-cp310-win_amd64.whl (12.7 MB) Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB) Using cached imageio-2.34.1-py3-none-any.whl (313 kB) Installing collected packages: opencv-python-headless, imageio, scikit-image

**Comment by ltdrdata** [comment]
That issue occurs because comflowy is incorrectly performing the installation on Windows. 
In ComfyUI-Manager's Install custom nodes, click 'try fix' for Impact Pack and then restart ComfyUI
