### ISSUE TITLE
Recommended workflow for premade sdxl landscape images.

### ISSUE THREAD

**Issue by Vigilence** [ltdrdata/ComfyUI-Impact-Pack#614]
I would like to upscale landscape painting images I made in sdxl, enhancing details and increasing quality.  Can you make any suggestions on where to start? 

I tried making a workflow using tiled diffusion node but it doesn’t work with more then 1 controlnet so I am looking at alternative workflows.

**Comment by ltdrdata** [comment]
These workflows can be startpoint.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/MakeTileSEGS_upscale.png

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/MakeTileSEGS_upscale_AnimateDiff_ControlNet.png

https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/536
