### ISSUE TITLE
Is UltralyticsDetectorProvider support yolov10?

### ISSUE THREAD

**Issue by jesenzhang** [ltdrdata/ComfyUI-Impact-Pack#615]
Is UltralyticsDetectorProvider support yolov10?

**Comment by ltdrdata** [comment]
That support should be handled in https://github.com/ultralytics/ultralytics

**Comment by saftle** [comment]
@ltdrdata support was added. Is there any chance you'll want to add support?

**Comment by ltdrdata** [comment]
> @ltdrdata support was added. Is there any chance you'll want to add support?

The YOLOv10 model can be used without any issues in the existing Impact Pack by simply updating ultralytics, already.
