### ISSUE TITLE
Error occurred when executing DetailerForEachPipeForAnimateDiff

### ISSUE THREAD

**Issue by zergqyue** [ltdrdata/ComfyUI-Impact-Pack#617]
![360截图20240530204122](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/125524733/fda72f68-9ae8-4100-9929-3584ff705493)

**Comment by ltdrdata** [comment]
What is your Workflow?

**Comment by ltdrdata** [comment]
Anyway this issue is fixed.
