### ISSUE TITLE
MaskPainter -> PreviewBridge How is this a replacement? 

### ISSUE THREAD

**Issue by eldragon0** [ltdrdata/ComfyUI-Impact-Pack#62]
MaskPainter was the only reason I was able to move from A1111 to Comfyui. I see that it's been depreciated in the more recent updates and replaced with a tool that does none of the things the MaskPainter did.  Is there a node I'm not aware of that allows me to open the image and paint  a mask over it to output a new mask? 

Enabling MMDet usage does let me use the MaskPainter, but I'd imagine the goal of it going legacy is to stop people from using it. Which will only work if there's a suitable alternative. 

While Sam Detector and inverting the mask works for subject, there is no resolution for the shotty masks it makes, or when it masks areas it's not supposed to. It just isn't a suitable replacement.

**Comment by ltdrdata** [comment]
https://youtu.be/O3EjONCS-rU

Just right click on that node.
MaskPainter's mask was a pretty prototype implementation.

Now the built-in mask editor is more mature.

And you are interested in interactive inpainting.

https://youtu.be/AccoxDZIg3Y
This workflow helps you much more.

**Comment by eldragon0** [comment]
What is this witchraft and how is it so amazing?!  Thank you very much for taking the time to share that workflow!  That will do for sure :)
