### ISSUE TITLE
Is there a node for cutting the original image using the mask?

### ISSUE THREAD

**Issue by liusida** [ltdrdata/ComfyUI-Impact-Pack#622]
Hi, I was going through a very basic tutorial to learn how to use masks:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/14249458/048a7924-5682-46dc-b575-5a982596e0c8)

and I'd like to verify if the segment detectors are working correctly. However, we only have the black and white mask image here. I wish there were a node that could cut the original image using the mask so that I can verify the edges and details like this:

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/14249458/8fff3235-e32d-42c0-8268-8c9fa37e5d2b)

Currently, I was using "Cut By Mask" node from [Masquerade Nodes](https://github.com/BadCafeCode/masquerade-nodes-comfyui), but that node doesn't support the `batch_masks` output from "SAMDetector (segmented)" node very well.

I wonder if there's a suitable node I can use in this very package? Maybe it's there and I just haven't noticed it.

Thanks.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/336363aa-96c6-49c1-b003-437c76866b07)

Do you meaning this?

**Comment by liusida** [comment]
Yes, this looks awesome! But how to turn MASK into SEGS?

**Comment by ltdrdata** [comment]
And you can use batch processing like this.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/925f7bba-f9e1-4df2-b40b-097b5b58b47f)

**Comment by ltdrdata** [comment]
> Yes, this looks awesome! But how to turn MASK into SEGS?

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/9c7f8468-716f-4f3b-9a4b-5c4a6c19e31a)

**Comment by liusida** [comment]
Of course there is a "MASK to SEGS"! Great! There are so many awesome nodes in this package. Need time to soak in. Thanks for the help!
