### ISSUE TITLE
An error occurs when executing IterativeLatentUpscale.

### ISSUE THREAD

**Issue by KennyChan3389** [ltdrdata/ComfyUI-Impact-Pack#623]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/155774773/4a2ae52b-d8b7-4ef2-bd2d-c23dbbaf69cf)

image size : 672*1024

<img width="976" alt="8da11748a6999e70f172233c1b64b4ac" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/155774773/58d287a1-f8a4-44a0-b681-cf1f2ed0d627">

**Comment by ltdrdata** [comment]
I cannot reproduce this issue.

**Comment by KennyChan3389** [comment]
> 我无法重现此问题。

This is my workflow, please help me check it!
[IPa_tile_latent_UP.json](https://github.com/user-attachments/files/15536063/IPa_tile_latent_UP.json)

**Comment by ltdrdata** [comment]
This is not a issue of Impact Pack.
```

    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/custom_nodes/ComfyUI-TiledDiffusion/.patches.py", line 4, in calc_cond_batch
    return calc_cond_batch_original_tiled_diffusion_aeb24c13(model, conds, x_in, timestep, model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/comfy/samplers.py", line 218, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 63, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/comfy/model_base.py", line 97, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 852, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/comfy/ldm/modules/attention.py", line 644, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/comfy/ldm/modules/attention.py", line 568, in forward
    n = attn2_replace_patch[block_attn2](n, context_attn2, value_attn2, extra_options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/CrossAttentionPatch.py", line 26, in __call__
    out = out + callback(out, q, k, v, extra_options, **self.kwargs[i])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/teratera/git/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/CrossAttentionPatch.py", line 155, in ipadapter_attention
    mask_h = int(mask_h) + int((seq_len % int(mask_h)) != 0)
                                ~~~~~~~~^~~~~~~~~~~~~
ZeroDivisionError: integer modulo by zero

Prompt executed in 27.96 seconds

```
The final error occurred with ComfyUI_IPAdapter_Plus. However, considering that the error occurred when it was replaced with a non-Tiled version, it seems to be an issue with TiledDiffusion.

Please recreate the issue by setting up a workflow with TiledDiffusion + ComfyUI_IPAdapter_Plus and report it to the TiledDiffusion repository.

**Comment by KennyChan3389** [comment]
When I run IterativeLatentUpscale with the ipadapter node to build a partition masking workflow, it still produces an error.

Error occurred when executing IterativeLatentUpscale.
module 'comfy.sample' has no attribute 'prepare_mask'
![2eb5548f6746f3e657408790f4b95634](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/155774773/8990045a-d72b-42e6-bb7b-bb0af56a7e26)

It's my workflow.
[
[ipa.json](https://github.com/user-attachments/files/15595337/ipa.json)
](url)

I'm not sure if it's the ipadapter or the tiled diffusion anymore, I'll try to contact the respective authors, this will serve as a place to store questions for now.
Hopefully it will get resolved

**Comment by ltdrdata** [comment]
> prepare_mask

That message means ComfyUI_TiledKSampler is outdated.

**Comment by KennyChan3389** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/155774773/ea2c227f-152b-4c5f-8534-3145f3475dbc)
comfyui，ComfyUI_TiledKSampler，ComfyUI-Impact-Pack，all new

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/155774773/337061755-ea2c227f-152b-4c5f-8534-3145f3475dbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MzY1NDgsIm5iZiI6MTcxNzYzNjI0OCwicGF0aCI6Ii8xNTU3NzQ3NzMvMzM3MDYxNzU1LWVhMmMyMjdmLTE1MmItNGM1Zi04NTM0LTMxNDVmMzQ3NWRiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwMTEwNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzYxNTAzNGY1ZThjOTBlNTM2NWU3MWYxZGViNmY3YTRmNjBmODI2MjQ5Y2I2MDMwNTFlZTdmYjhjZDRmZGNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._sVydbWzR_V88vZ4uLMTVVlXS3DheMSlkoCgVGqwB9I) comfyui，ComfyUI_TiledKSampler，ComfyUI-Impact-Pack，all new

It's not your fault. TiledKSampler isn't patched for latest ComfyUI.
