### ISSUE TITLE
facedetailer with differential diffusion become very slow after the first render..

### ISSUE THREAD

**Issue by tester4488** [ltdrdata/ComfyUI-Impact-Pack#625]
![immagine](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/160387045/b76531b5-e8ef-4a0a-8c29-4c40acc5c228)

fist render is fast, then at the second become very slow.
bypass the differential diffusion node, or delete and recreate, work fast again.

Last comfyui and last impact node

**Comment by ltdrdata** [comment]
Don't apply Differential Diffusion.
Detailer internally applies Differential Diffusion if `noise_mask_feather` is greater than 0.
