### ISSUE TITLE
ImpactWildcardProcessor - Wildcard Call Prompt Weight Multiplier No Longer Applies to Weighted Prompts and Embeddings in __Wildcard__.txt

### ISSUE THREAD

**Issue by Meat5taiN** [ltdrdata/ComfyUI-Impact-Pack#630]
Greetings, 

I recently updated my Comfy build for the first time in a couple of months and I noticed that the prompt weight multiplier for the wildcard call no longer applies to prompts and embeddings that have weights applied to them in the wildcard txt document.

__________________________________
For example:

_In ImpactWildcardProcessor prompt field:_

Some prompts...,  (..HairSkinChar..:1.15), ...some more prompts

_And in HairSkinChar.txt:_

...
...
(embedding:somefavoriteperson1:0.78)
(embedding:somefavoriteperson1:0.84)
(embedding:somefavoriteperson1:0.90)
(auburn-hair, hazel-eyes, freckles:0.78)
(auburn-hair, hazel-eyes, freckles:0.84)
(auburn-hair, hazel-eyes, freckles:0.90)
(brazilian:0.82)
(brazilian:0.88)
(brazilian:0.94)
...
...
...
_________________________________

The x1.15 multiplier of the (..HairSkinChar..:1.15) call does not apply to the 0.78|0.84|0.90 multipliers of 'embedding:somefavoriteperson1' and 'auburn-hair, hazel-eyes, freckles' like it did until recently. The new behavior is that it ignores the x1.15 multiplier of the call and only applies the weights within the .txt document.

This is great for my GPU and electric bill, but bad for my favorite workflow. 

Thank you for all of the hard work that you put into Comfy for all of us.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/510cb9cc-2fb7-4499-b244-89a6df0055a1)

I cannot find any issue.

**Comment by Meat5taiN** [comment]
While running a couple of tests to try to explain the issue better, I discovered that it wasn't the Wildcard Processor that originated the loss of the function. It appears to be something that mainline Comfy has done with their prompt processing. The issue is present with the default CLIP Text Encoder and doesn't require a wildcard to manifest, it is the same with a standard prompt.

The previous behavior was that if you had a parenthetical weight multiplier within another parenthetical weight modifier, they would stack together.  For example:

(..Wildcard..:1.3)      
((subject:0.9):1.3)
processed prompt weight = (subject:1.17)

The new mainline Comfy behavior is to treat the outer weight modifier as invalid and ignore it. For example:
(..Wildcard..:1.3)      
~~(~~(subject:0.9)~~:1.3)~~
processed prompt weight = (subject:0.9)

I'm not certain, but it seems that they may have done as part of some other changes to help prevent misplaced weight modifiers. I doubt that my fringe use case will sway the current decision, but I'll ask about it on the main comfy page.

Again, I appreciate you taking a look at the issue although it is not with Impact Pack.

**Comment by ltdrdata** [comment]
By the way, I think sum doesn't seem to be correct. Multiply seems more appropriate instead.

**Comment by Meat5taiN** [comment]
That's correct, it used to be multiply.

I have dozens of wildcards with thousands of entries, and my embedding
wildcards all have staggered weights in the entries. So it's quite
disappointing to see them do away with the stacked weight multipliers.

**Comment by ltdrdata** [comment]
I reviewed the code, and whether it's a bug or intentional, the processing of token weights has never supported nesting since the initial commit. It has always been overridden by the innermost weight.

https://github.com/comfyanonymous/ComfyUI/blob/56333d48508f95bdef23870cad3239ba0ebdb8a9/comfy/sd1_clip.py#L240

**Comment by Meat5taiN** [comment]
That's interesting. I had carefully considered that maybe I was imagining
the change before I brought up the issue, but then I thought back to times
when I made pretty drastic changes to the wildcard weight and it seemed to
always work. I was almost certain that it used to stack/multiply the
weights. I had never actually tested it properly when it was working as
intended, so it's certainly possible that it was just the luck of random
seeds.

I'm sorry to ask this, but how difficult would it be to implement it as a
feature to the wildcard processor?

I can make versions of my wildcards that don't have weight modifiers inside
of them, but some embeddings and prompts tend to be much stronger than
others by default.
