### ISSUE TITLE
Where does the UltralyticsDetectorProvider model go, is it ok if I want to load my own model?

### ISSUE THREAD

**Issue by huangjianyi0701** [ltdrdata/ComfyUI-Impact-Pack#634]
Where does the UltralyticsDetectorProvider model go, is it ok if I want to load my own model?

**Comment by ltdrdata** [comment]
`ComfyUI/models/ultralytics/segm` or `ComfyUI/models/ultralytics/bbox`
And you can download bunch of ultralytics models via ComfyUI-Manager.

**Comment by huangjianyi0701** [comment]
> `ComfyUI/models/ultralytics/segm` or `ComfyUI/models/ultralytics/bbox` And you can download bunch of ultralytics models via ComfyUI-Manager.

Is it ok if I want to use my own trained model?

**Comment by ltdrdata** [comment]
> > `ComfyUI/models/ultralytics/segm` or `ComfyUI/models/ultralytics/bbox` And you can download bunch of ultralytics models via ComfyUI-Manager.
> 
> Is it ok if I want to use my own trained model?

There are already users who have trained and are using their own models.

**Comment by huangjianyi0701** [comment]
> > > `ComfyUI/models/ultralytics/segm` or `ComfyUI/models/ultralytics/bbox` And you can download bunch of ultralytics models via ComfyUI-Manager.
> > 
> > 
> > Is it ok if I want to use my own trained model?
> 
> There are already users who have trained and are using their own models.

Thanks,bro,I didn't notice your message just now

**Comment by huangjianyi0701** [comment]
> > > `ComfyUI/models/ultralytics/segm` or `ComfyUI/models/ultralytics/bbox` And you can download bunch of ultralytics models via ComfyUI-Manager.
> > 
> > 
> > Is it ok if I want to use my own trained model?
> 
> There are already users who have trained and are using their own models.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/129131129/0d903952-ec68-4ff9-8535-e092089ad8c9)
May I ask what causes this? I can read the model weights now, but the runtime reports an error and a cache file cannot be found

**Comment by ltdrdata** [comment]
It seems that it is incompatible model file.

**Comment by huangjianyi0701** [comment]
> It seems that it is incompatible model file.

Thank you, it has been resolved!
