### ISSUE TITLE
segspaste bug

### ISSUE THREAD

**Issue by 807502278** [ltdrdata/ComfyUI-Impact-Pack#635]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/46019416/63d8fe74-f6a7-4f26-8862-9ac3598460dd)
SEG pasting seemed to have no effect and eventually turned into an image batch

**Comment by ltdrdata** [comment]
I cannot identify it with just this. Also, please turn off the language translation mode when capturing the report.

**Comment by 807502278** [comment]
噢噢，不好意思是我用错了，节点没问题
