### ISSUE TITLE
Face Detailer Threshold 

### ISSUE THREAD

**Issue by abaybektursun** [ltdrdata/ComfyUI-Impact-Pack#636]
I only want to apple face detailer to medium faces, is there a bbox size threshold parameter? I want to filter out small faces.
Also I would like to apply face detailer to only the largest face, however if the face is too big I want it to be ignored. 
How do I achieve this?

**Comment by ltdrdata** [comment]
You can utilize drop_size.
And force_inpaint prevents skipping for large enough images.

**Comment by abaybektursun** [comment]
Is it possible to force to select only one face? @ltdrdata

**Comment by ltdrdata** [comment]
> Is it possible to force to select only one face? @ltdrdata

If you want advanced control. Use Detailer instead of FaceDetailer.
https://www.youtube.com/watch?v=9GSQlxZFrLI
