### ISSUE TITLE
Unable to change mode on the wildcard processor node.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ltdrdata/ComfyUI-Impact-Pack#64]
After just updating, I'm no longer able to change the mode in the "ImpactWildcardPorcessor" node.

**Comment by ltdrdata** [comment]
> After just updating, I'm no longer able to change the mode in the "ImpactWildcardPorcessor" node.

It's my mistake my WIP commit is pushed mistakenly.. I reverted it just update again.

**Comment by GalaxyTimeMachine** [comment]
It's back to being broken after the latest update.

**Comment by Jatravartids** [comment]
Just reinstalled, Mode is an input and can't be changed to a widget.

**Comment by GalaxyTimeMachine** [comment]
Can no longer type in the lower text field when "Fixed" is chosen. This was possible in previous versions.

**Comment by ltdrdata** [comment]
> Can no longer type in the lower text field when "Fixed" is chosen. This was possible in previous versions.

I'd patched this. Update Impact Pack to V3.7.1.

**Comment by GalaxyTimeMachine** [comment]
So you had, thanks again!
