### ISSUE TITLE
sample_with_custom_noise looses the batch_index meta information

### ISSUE THREAD

**Issue by gottfriedm** [ltdrdata/ComfyUI-Impact-Pack#643]
The function `sample_with_custom_noise()` calls `comfy_extras.nodes_custom_sampler.Noise_RandomNoise()` with a dict that contains only the samples of the latent image. `Noise_RandomNoise()` would respect the `batch_index` in the noise generation process, but if the `batch_index` is not passed, obviously this doesn't work.

Example: Use "Empty Latent Image" node to generate a batch of 8 latent images. Use "Latent From Batch" node to select index 3 from that batch.
If run through the normal KSampler (which respects the `batch_index`) we get a different image than if we run through KSampler (pipe). In fact, Ksampler (pipe) always produces the same image, regardless which value is set in the "Latent From Batch" node, because the meta information of the `batch_index` ist lost when calling `Noise_RandomNoise()`

This behavior was introduced a few days ago in 885ca3d.

**Comment by ltdrdata** [comment]
this is fixed.

**Comment by gottfriedm** [comment]
Wow, that was fast! Thank you!
