### ISSUE TITLE
rizvandwiki / gender-classification-2 where should i put this model?

### ISSUE THREAD

**Issue by izonewonyoung** [ltdrdata/ComfyUI-Impact-Pack#645]
huggingface can't auto download it T T

**Comment by ltdrdata** [comment]
I just tested it, and there doesn't seem to be any problem.
What error message are you seeing?

**Comment by izonewonyoung** [comment]
I am trying to use this workflow https://openart.ai/workflows/kejun/professional-photo-portraits/8tKIKUNcFrmT6egoW8Ri
and I have error "Prompt outputs failed validation
Text Input Switch:
- Required input is missing: boolean_number"
I think it is because the "HF Transformers Classifier Provider" model does not download automatically from huggingface.
I want to download it by myself,but I don't know where should I put this model.
Could you help me?THANK YOU VERY MUCH :D

**Comment by ltdrdata** [comment]
Update Impact Pack to latest version.

You can download model like this.
`git clone https://huggingface.co/rizvandwiki/gender-classification-2`

And set `preset_repo_id` as `Manual repo id`.
And input path to cloned model repo to `manual_repo_id`.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/304a9c5e-32bc-4ba8-a471-78bf7ef0ee19)
