### ISSUE TITLE
could you please add a node achive convert hexadecimal color values to hue values？

### ISSUE THREAD

**Issue by hexiaoyu946** [ltdrdata/ComfyUI-Impact-Pack#646]
Dear developer, I want to convert hexadecimal color values to hue values, please ask if you can add a node to achieve this function, thank you very much
![屏幕截图 2024-06-19 011941](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/72909117/ec679681-d925-4a4e-950a-c53848b320f8)

**Comment by ltdrdata** [comment]
![hsv](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/54efd614-d863-4499-bc4d-0a47cfa658ac)

This node is added to Inspire Pack.

**Comment by hexiaoyu946** [comment]
you are my god，thank you very much！！

**Comment by hexiaoyu946** [comment]
Dear developer, I want to convert the hexadecimal color value to the color phase value is intended to accurately adjust the color of the image, but this is completely unexpected, please tell me how to accurately adjust the color, if the work is relatively simple, could you please also add a node to achieve it, thank you very much
![屏幕截图 2024-06-20 012233](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/72909117/7b29658d-74b6-4595-a413-26c832fdb210)

**Comment by ltdrdata** [comment]
> Dear developer, I want to convert the hexadecimal color value to the color phase value is intended to accurately adjust the color of the image, but this is completely unexpected, please tell me how to accurately adjust the color, if the work is relatively simple, could you please also add a node to achieve it, thank you very much

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/0f74d215-782d-47c5-8eba-6e9e2457a4cb)

ColorPicker is providing various input method, already.

**Comment by hexiaoyu946** [comment]
I want the color of the clothes to be the same as the chosen color. I imagine using the hue value would work, but it doesn't seem to work
