### ISSUE TITLE
When I use the "UItralyticsDetector provider" node, my comfyui interface will be stuck and completely inoperable

### ISSUE THREAD

**Issue by Zkk19492024** [ltdrdata/ComfyUI-Impact-Pack#648]
Hello, I would like to ask about this error: When I use the "UItralyticsDetector provider" node, my comfyui interface will be stuck and completely inoperable. Reinstalling the plug-in cannot solve this problem. I don't know why, and facial repair is very important to me. It hurts me that I can't use it. Thank you

![screenshot-20240622-113238](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/170162034/d510b2cf-5d01-4796-94c6-82d2312c6270)
![screenshot-20240622-113216](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/170162034/ac84f807-b2b0-4643-9d25-061c63315741)

**Comment by ltdrdata** [comment]
Try disabling all other custom nodes and test again.
(Move out  whole custom nodes to somewhere else. Just remain Impact Pack)

**Comment by drake7707** [comment]
I have exactly the same issue on a fresh install:

> impact-pack.js:601  Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at node.onDrawForeground (impact-pack.js:601:42)
    at LGraphCanvas.drawNode (litegraph.core.js:8544:18)
    at LGraphCanvas.drawNode (snapToGrid.js:88:24)
    at LGraphCanvas.drawNode (app.js:1290:29)
    at LGraphCanvas.drawFrontCanvas (litegraph.core.js:7827:22)
    at LGraphCanvas.draw (litegraph.core.js:7742:18)
    at LGraphCanvas.renderFrame (litegraph.core.js:5809:22)

**Comment by ltdrdata** [comment]
This is fixed.
