### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by nodegraphics** [ltdrdata/ComfyUI-Impact-Pack#649]
hello,
I was wondering keeping tile size larger then 512 will effects the node to determine what the context of the image is ? specially aspect ratios which are not 1:1 
I wasnt sure if it has any effect or not.

![Screenshot - 2024-06-22 22 23 11](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/10071439/af541c9b-062e-4748-8464-1dd4c4ad8cab)

**Comment by ltdrdata** [comment]
It depends on the model size. If it's SDXL, then 1024 is appropriate.
The aspect ratio doesn't really matter.

**Comment by nodegraphics** [comment]
yes, sdxl. I sometimes get double nose and eyes because of the tile size. so i just wanted to ask.

**Comment by ltdrdata** [comment]
> yes, sdxl. I sometimes get double nose and eyes because of the tile size. so i just wanted to ask.

That tile size is for vae. So that is the not the issue of the double nose. You need to lower denoise.

**Comment by nodegraphics** [comment]
I got what you mean now.. Thank you so much, i appreciate it.
