### ISSUE TITLE
Randomize seed on each iteration of DetectorForEach 

### ISSUE THREAD

**Issue by vivin** [ltdrdata/ComfyUI-Impact-Pack#65]
I know that right now the Detector will randomize the seed after each generation if I tell it to. But is there a way to have it use a random seed for each iteration? This way I can use a new seed for each detected face.

**Comment by ltdrdata** [comment]
I'll consider.

**Comment by vivin** [comment]
Thank you! I don't taking a stab at it. I do have development experience although I haven't worked with ComfyUI before. If you can point me to the code for it, I can take a look.

**Comment by lalalabush** [comment]
Great idea. Without it I get the same face across the image!

**Comment by ricperry** [comment]
Not sure if this has progressed or not. Would be nice.

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/63440bee-36b0-4b78-8dfa-febbcd244607)

Now you can specify seed for each SEGS (V4.65.1)

e.g
`aaa [SEP]  bbb [SEP:R] ccc [SEP:111] ddd`
1st SEG: aaa prompt + node seed
2nd SEG: bbb prompt + (node seed + 1)
3rd SEG: ccc prompt + random seed
4th SEG: ddd prompt + 111 seed
