### ISSUE TITLE
(Question) If the mask size is too big, will it not recognize it?

### ISSUE THREAD

**Issue by ytoaa** [ltdrdata/ComfyUI-Impact-Pack#650]
![workflow (1)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/24527825/5296c232-864c-42af-bfca-f84332d2557e)
![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/24527825/394037ec-1e01-4aee-85b8-00cb16052248)

(EXIF Included)

When the mask size is small like this, it is recognized properly, but if it is reversed and made large, it doesn't seem to work as desired.
Is there any other way?

**Comment by ltdrdata** [comment]
I'll update.

**Comment by ltdrdata** [comment]
![maskdetailer](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/f554adaa-9fa8-4c2e-bfd2-f1bf8686687b)

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/993cf798-54b9-4ae3-8b3c-495441db524a)

`contour_fill` is added.
Disable it.
