### ISSUE TITLE
Recent `numpy` change

### ISSUE THREAD

**Issue by polarathene** [ltdrdata/ComfyUI-Impact-Pack#651]
[This commit](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/7e47e28884d8a88d7ef6d1e268ffc996f8647c2d) lacks context, no issue/PR referenced.

While it's clear what it's intended to do as an intermediary fix, it is a transitive dep but now added explicitly just to workaround the current breakage concern, without any contextual comment for better visibility.

FWIW, the change only updated `requirements.txt`, thus diverging from `pyproject.toml`, assuming you'd want to carry it over there as well.

**Comment by ltdrdata** [comment]
The issue with numpy 2.0 is that it is not backward compatible, causing many packages that depend on numpy to break completely at now.

https://github.com/comfyanonymous/ComfyUI/issues/3794
https://github.com/Comfy-Org/comfy-cli/issues/97
https://github.com/Fannovel16/comfyui_controlnet_aux/issues/311
