### ISSUE TITLE
custom_size.ini not found,

### ISSUE THREAD

**Issue by hkgood** [ltdrdata/ComfyUI-Impact-Pack#652]
Keep sending error "custom_size.ini not found,"

E:\ComfyUI_Mini\ComfyUI\web\extensions\fofo
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Find 1 LUTs in E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut
# 😺dzNodes: LayerStyle -> Find 1 Fonts in E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font
Patching UNetModel.forward
UNetModel.forward has been successfully patched.

[rgthree] Loaded 40 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.

# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\ComfyUI_Mini\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 216 nodes successfully.

        "The distance between insanity and genius is measured only by success." - Bruce Feirstein

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\FreeU_Advanced
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\Comfy_KepListStuff
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-CUP
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Studio
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\Comfyui_CXH_DeepLX
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.2 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.2 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-InstantID
   0.3 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.4 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.4 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\Comfyui_image2prompt
   1.6 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-SUPIR
   1.6 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\comfyui-art-venture
   1.8 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   2.2 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\was-node-suite-comfyui
   3.6 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\comfyui-ollama
  10.5 seconds: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://127.0.0.1:8188
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
FETCH DATA from: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: E:\ComfyUI_Mini\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.

**Comment by ltdrdata** [comment]
You should report to here:
https://github.com/chflame163/ComfyUI_LayerStyle/issues
