### ISSUE TITLE
Sam Loader error 

### ISSUE THREAD

**Issue by Krishicall** [ltdrdata/ComfyUI-Impact-Pack#659]
SAM Loader cannot locate models or connect to 'ToDetailerPipe' 

Impact Pack V06-29-2024
Comfy V06-30-2024
![sam loader error](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/164661412/7942ab75-2d1e-4f71-8671-2b3fac6124cd)

**Comment by ltdrdata** [comment]
ComfyUI-YOLO is overriding Impact Pack's SAMLoader node.
That is an invalid SAMLoader node.
