### ISSUE TITLE
Latent Scale on Pixel Space broken?

### ISSUE THREAD

**Issue by Davikar** [ltdrdata/ComfyUI-Impact-Pack#66]
Getting the following error when trying to run the "Latent Scale on Pixel Space" node:

```
Error occurred when executing LatentPixelScale:

name 'use_tile' is not defined

File "C:\AI\ComfyUI\ComfyUI\execution.py", line 144, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 74, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\AI\ComfyUI\ComfyUI\execution.py", line 67, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 880, in doit
latent = core.latent_upscale_on_pixel_space_with_model(samples, scale_method, upscale_model_opt, scale_factor, vae, use_tile=use_tile)
```

I've tripped checked and all nodes seems to be connected as they should...

**Comment by ltdrdata** [comment]
> Getting the following error when trying to run the "Latent Scale on Pixel Space" node:
> 
> ```
> Error occurred when executing LatentPixelScale:
> 
> name 'use_tile' is not defined
> 
> File "C:\AI\ComfyUI\ComfyUI\execution.py", line 144, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "C:\AI\ComfyUI\ComfyUI\execution.py", line 74, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "C:\AI\ComfyUI\ComfyUI\execution.py", line 67, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 880, in doit
> latent = core.latent_upscale_on_pixel_space_with_model(samples, scale_method, upscale_model_opt, scale_factor, vae, use_tile=use_tile)
> ```
> 
> I've tripped checked and all nodes seems to be connected as they should...

oops... I pushed wip to Main... sorry.
ps. I'd just reverted it.
