### ISSUE TITLE
Lazy install of basic models?

### ISSUE THREAD

**Issue by Quasimondo** [ltdrdata/ComfyUI-Impact-Pack#661]
I wonder if in a future version the download of the basic models could be postponed until they are actually required? Right now they are all downloaded when one installs the package which can be a nuisance on a slow or metered connection in particular when one is not needing those particular models but just some of the other nodes. Also it prevents running the server until the entire download has finished.

**Comment by ltdrdata** [comment]
If you create an empty file named `skip_download_model` in the `ComfyUI/custom_nodes/` directory, it will skip the model download step during the installation of the impact pack.
