### ISSUE TITLE
ImpactIfNone  logic does match document

### ISSUE THREAD

**Issue by SongOnWater** [ltdrdata/ComfyUI-Impact-Pack#662]
In the document https://www.runcomfy.com/comfyui-nodes/ComfyUI-Impact-Pack/ImpactIfNone,  

the correct code seems should be :
    def doit(self, signal=None, any_input=None):
        if signal is None:
            return (any_input, False, )
        else:
            return (signal, True, )

**Comment by ltdrdata** [comment]
That is not a official documentation. AFAIK, It is generated by LLM.
I realized that I had forgotten to write the node description in the README page, so I updated it.

`ImpactIfNone` - Returns `true` if any_input is None, and returns `false` if it is not None.

In the impact pack, a `signal` is always passthru. It's not meant to handle semantic of any values, but rather it's a mechanism to ensure the execution order of nodes in the workflow.
