### ISSUE TITLE
Wildcard Encode/Processor "Mode" as Input incompatible with booleans

### ISSUE THREAD

**Issue by hobojoker** [ltdrdata/ComfyUI-Impact-Pack#663]
Wildcard Mode when used as an input will only work properly with a primitive node attached.

If you try to use it with another boolean, it will continue to operate as though it is set to Populate.

If you try to use the primitive from the Wildcard Mode, it is not compatible with other booleans. I've tried adjusting the inputs in the code, but I'm not sure why the impact nodes work differently than other nodes and when I modify it, it just stops working.

**Comment by ltdrdata** [comment]
The core concept of the wildcard in Impact Pack is to allow users to check how the wildcard was populated and save it in the workflow. Everything applied to the workflow must be determined before the workflow is executed.
The mode is used to decide whether to pass the wildcard text as populate text before running the workflow.
