### ISSUE TITLE
about MaskDetailer

### ISSUE THREAD

**Issue by za-wa-n-go** [ltdrdata/ComfyUI-Impact-Pack#665]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/118154415/e6858a72-20c3-401c-8fce-d9a875fbfdfe)
It seems that the mask Gaussian blur is not being accepted as it is. Is this a specification?

**Comment by ltdrdata** [comment]
![workflow (20)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/ac12c88c-a24d-4a47-a43a-a67f853a1a38)

This is patched.

However, differential diffusion will be deactivated when `noise_mask_feather` is 0.

**Comment by za-wa-n-go** [comment]
thakyou!
This happened recently.

 [bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `X:\aiart\Data\Packages\ComfyUI\main.py\models` as the ComfyUI path.[/bold yellow]
 [ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually.
 Traceback (most recent call last):
   File "X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 116, in <module>
     import folder_paths
 ModuleNotFoundError: No module named 'folder_paths'

**Comment by ltdrdata** [comment]
> thakyou! This happened recently.
> 
> [bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `X:\aiart\Data\Packages\ComfyUI\main.py\models` as the ComfyUI path.[/bold yellow] [ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually. Traceback (most recent call last): File "X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 116, in import folder_paths ModuleNotFoundError: No module named 'folder_paths'

Update again.

**Comment by ltdrdata** [comment]
again... I missed one.

**Comment by za-wa-n-go** [comment]
accident

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
   [SKIP] Downgrading pip package isn't allowed: scipy (cur=1.14.0)
Install: install script for 'X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 
 [bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `X:\aiart\Data\Packages\ComfyUI\main.py\models` as the ComfyUI path.[/bold yellow]
 ### ComfyUI-Impact-Pack: Check dependencies
 ### ComfyUI-Impact-Pack: Updating subpack
 [Impact Pack] EXECUTE: ['X:\\aiart\\Data\\Packages\\ComfyUI\\venv\\Scripts\\python.exe', 'install.py'] in 'X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
 Traceback (most recent call last):
   File "X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\install.py", line 24, in <module>
     os.makedirs(ultralytics_bbox_path)
   File "os.py", line 215, in makedirs
   File "os.py", line 215, in makedirs
   File "os.py", line 225, in makedirs
 FileNotFoundError: [WinError 3] 隰厄ｿｽ陞ｳ螢ｹ�ｼ�郢ｧ蠕娯螺郢昜ｻ｣縺帷ｸｺ迹夲ｽｦ荵昶命邵ｺ荵晢ｽ顔ｸｺ�ｽｾ邵ｺ蟶呻ｽ鍋ｸｲ�ｿｽ: 'X:\\aiart\\Data\\Packages\\ComfyUI\\main.py\\models'
 req_path: X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
 ### ComfyUI-Impact-Pack: Check basic models
 [ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually.
 Traceback (most recent call last):
   File "X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 295, in <module>
     install()
   File "X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 276, in install
     os.makedirs(bbox_path)
   File "os.py", line 215, in makedirs
   File "os.py", line 215, in makedirs
   File "os.py", line 225, in makedirs
 FileNotFoundError: [WinError 3] 謖�螳壹＆繧後◆繝代せ縺瑚ｦ九▽縺九ｊ縺ｾ縺帙ｓ縲�: 'X:\\aiart\\Data\\Packages\\ComfyUI\\main.py\\models'

[ComfyUI-Manager] Startup script completed.
#######################################################################

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager.

**Comment by za-wa-n-go** [comment]
success!

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['X:\\aiart\\Data\\Packages\\ComfyUI\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'GitPython']

## Execute install/(de)activation script for 'X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
   [SKIP] Downgrading pip package isn't allowed: scipy (cur=1.14.0)

## ComfyUI-Manager: EXECUTE => ['X:\\aiart\\Data\\Packages\\ComfyUI\\venv\\Scripts\\python.exe', 'install.py']

## Execute install/(de)activation script for 'X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 
 [bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `X:\aiart\Data\Packages\ComfyUI\models` as the ComfyUI path.[/bold yellow]
 ### ComfyUI-Impact-Pack: Check dependencies
 ### ComfyUI-Impact-Pack: Updating subpack
 [Impact Pack] EXECUTE: ['X:\\aiart\\Data\\Packages\\ComfyUI\\venv\\Scripts\\python.exe', 'install.py'] in 'X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
 req_path: X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: X:\aiart\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
 ### ComfyUI-Impact-Pack: Check basic models

[ComfyUI-Manager] Startup script completed.
#######################################################################
