### ISSUE TITLE
Any Switch (Select - Convert To Widget - Bug)

### ISSUE THREAD

**Issue by boricuapab** [ltdrdata/ComfyUI-Impact-Pack#671]
Hi

When using any switch node with a fixed seed and a random seed piped in, the graph stops generating and stays caches after the workflow is ran once as expected as shown in this first gif:

![switchSelectWorks](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/61924816/318e3b39-cf32-48eb-a5c3-61329196861e)

But as soon as I switch the select option to an input driven by an integer node, the graph keeps re-calculating even though the seed is fixed, and the option 'select on prompt' is enabled as seen here:

![switchSelectDoesntWork](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/61924816/deaf6917-9585-41d4-89f0-e298e3c77b06)

I was expecting the workflow not to keep recalculating as in the first gif, even when driving the select mode by a different integer node.

Thanks

**Comment by ltdrdata** [comment]
> Hi
> 
> When using any switch node with a fixed seed and a random seed piped in, the graph stops generating and stays caches after the workflow is ran once as expected as shown in this first gif:
> 
> ![switchSelectWorks](https://private-user-images.githubusercontent.com/61924816/347894002-318e3b39-cf32-48eb-a5c3-61329196861e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQwMDItMzE4ZTNiMzktY2YzMi00OGViLWE1YzMtNjEzMjkxOTY4NjFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTIzNGEzNWM1MDE5MTc1YjVhYzUxZTMyYzE4YzJiNGU2YzEwMTA3NGU3YzU2MjdhYTcwMWRmODQ4MGU4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kH25tyvOwyRE-hKa-qza8wwKf1Pl2g0SPR6T1Qe6LA8) [ ![switchSelectWorks](https://private-user-images.githubusercontent.com/61924816/347894002-318e3b39-cf32-48eb-a5c3-61329196861e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQwMDItMzE4ZTNiMzktY2YzMi00OGViLWE1YzMtNjEzMjkxOTY4NjFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTIzNGEzNWM1MDE5MTc1YjVhYzUxZTMyYzE4YzJiNGU2YzEwMTA3NGU3YzU2MjdhYTcwMWRmODQ4MGU4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kH25tyvOwyRE-hKa-qza8wwKf1Pl2g0SPR6T1Qe6LA8) ](https://private-user-images.githubusercontent.com/61924816/347894002-318e3b39-cf32-48eb-a5c3-61329196861e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQwMDItMzE4ZTNiMzktY2YzMi00OGViLWE1YzMtNjEzMjkxOTY4NjFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTIzNGEzNWM1MDE5MTc1YjVhYzUxZTMyYzE4YzJiNGU2YzEwMTA3NGU3YzU2MjdhYTcwMWRmODQ4MGU4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kH25tyvOwyRE-hKa-qza8wwKf1Pl2g0SPR6T1Qe6LA8) [ ](https://private-user-images.githubusercontent.com/61924816/347894002-318e3b39-cf32-48eb-a5c3-61329196861e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQwMDItMzE4ZTNiMzktY2YzMi00OGViLWE1YzMtNjEzMjkxOTY4NjFlLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YTIzNGEzNWM1MDE5MTc1YjVhYzUxZTMyYzE4YzJiNGU2YzEwMTA3NGU3YzU2MjdhYTcwMWRmODQ4MGU4MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kH25tyvOwyRE-hKa-qza8wwKf1Pl2g0SPR6T1Qe6LA8)
> 
> But as soon as I switch the select option to an input driven by an integer node, the graph keeps re-calculating even though the seed is fixed, and the option 'select on prompt' is enabled as seen here:
> 
> ![switchSelectDoesntWork](https://private-user-images.githubusercontent.com/61924816/347894686-deaf6917-9585-41d4-89f0-e298e3c77b06.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQ2ODYtZGVhZjY5MTctOTU4NS00MWQ0LTg5ZjAtZTI5OGUzYzc3YjA2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NmU0NDkyMTAwMTVmMWMyY2U4MTI3ZmU5Y2JlYjA2NzliN2ZmZGMzZjcxYzI0YjcwZDljYjVhMzNlMzViYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBeIbtoOn-pnPXe4y9Cmx9JXJRHTFnBpSIGg3lKcgWs) [ ![switchSelectDoesntWork](https://private-user-images.githubusercontent.com/61924816/347894686-deaf6917-9585-41d4-89f0-e298e3c77b06.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQ2ODYtZGVhZjY5MTctOTU4NS00MWQ0LTg5ZjAtZTI5OGUzYzc3YjA2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NmU0NDkyMTAwMTVmMWMyY2U4MTI3ZmU5Y2JlYjA2NzliN2ZmZGMzZjcxYzI0YjcwZDljYjVhMzNlMzViYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBeIbtoOn-pnPXe4y9Cmx9JXJRHTFnBpSIGg3lKcgWs) ](https://private-user-images.githubusercontent.com/61924816/347894686-deaf6917-9585-41d4-89f0-e298e3c77b06.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQ2ODYtZGVhZjY5MTctOTU4NS00MWQ0LTg5ZjAtZTI5OGUzYzc3YjA2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NmU0NDkyMTAwMTVmMWMyY2U4MTI3ZmU5Y2JlYjA2NzliN2ZmZGMzZjcxYzI0YjcwZDljYjVhMzNlMzViYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBeIbtoOn-pnPXe4y9Cmx9JXJRHTFnBpSIGg3lKcgWs) [ ](https://private-user-images.githubusercontent.com/61924816/347894686-deaf6917-9585-41d4-89f0-e298e3c77b06.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDExNjgsIm5iZiI6MTcyMDc0MDg2OCwicGF0aCI6Ii82MTkyNDgxNi8zNDc4OTQ2ODYtZGVhZjY5MTctOTU4NS00MWQ0LTg5ZjAtZTI5OGUzYzc3YjA2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDIzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NmU0NDkyMTAwMTVmMWMyY2U4MTI3ZmU5Y2JlYjA2NzliN2ZmZGMzZjcxYzI0YjcwZDljYjVhMzNlMzViYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBeIbtoOn-pnPXe4y9Cmx9JXJRHTFnBpSIGg3lKcgWs)
> 
> I was expecting the workflow not to keep recalculating as in the first gif, even when driving the select mode by a different integer node.
> 
> Thanks

That's what `select_on_prompt` means.
It means deciding on the select before executing the workflow.

The intention is to bypass the current structural limitations of ComfyUI. It will be significantly improved once https://github.com/comfyanonymous/ComfyUI/pull/2666 is merged into ComfyUI in the future, as it will no longer be necessary then.

For the reference
https://www.youtube.com/watch?v=KLe1hShwVDs

**Comment by boricuapab** [comment]
Thanks, I looked into setting up my use case using the inverse switch, but I actually just found that I need to use the ImpatInt node for the select_on_prompt behavior to occur, if I use an int node from a different node pack ex: ComfyRoll the select_on_prompt would not occur

![switchSelectWorksOnlyWitImpatInt](https://github.com/user-attachments/assets/49d75754-0769-4126-b5c8-f5480971da1d)

**Comment by ltdrdata** [comment]
This is allowed only for a few restricted nodes such as PrimitiveNode and ImpactInt. In the case of ImpactInt, it is supported for the purpose of applying ImpactValueSender. If you convert the widget of ImpactInt to an input, it will malfunction.
