### ISSUE TITLE
facedetailer and certain controlnet model compatibility issues

### ISSUE THREAD

**Issue by ytoaa** [ltdrdata/ComfyUI-Impact-Pack#673]
![workflow](https://github.com/user-attachments/assets/d416479d-5892-4373-bec9-faf7115ca33b)

!!! Exception during processing!!! '>' not supported between instances of 'NoneType' and 'float'
Traceback (most recent call last):
  File "Q:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "Q:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "Q:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 557, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 513, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 289, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 333, in enhance_detail
    refined_latent = impact_sampling.ksampler_wrapper(model2, seed2, steps2, cfg2, sampler_name2, scheduler2, positive2, negative2,
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 217, in ksampler_wrapper
    refined_latent = separated_sample(model, True, seed, advanced_steps, cfg, sampler_name, scheduler,
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 190, in separated_sample
    res = sample_with_custom_noise(model, add_noise, seed, cfg, positive, negative, impact_sampler, sigmas, latent_image, noise=noise, callback=callback)
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 143, in sample_with_custom_noise
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image, noise_mask=noise_mask, callback=touched_callback, disable_pbar=disable_pbar, seed=noise_seed)
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_reference.py", line 47, in refcn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 112, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "Q:\ComfyUI\comfy\sample.py", line 48, in sample_custom
    samples = comfy.samplers.sample(model, noise, positive, negative, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "Q:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1470, in sample
    return _sample(*args, **kwargs)
  File "Q:\ComfyUI\comfy\samplers.py", line 703, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "Q:\ComfyUI\comfy\samplers.py", line 690, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "Q:\ComfyUI\comfy\samplers.py", line 669, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "Q:\ComfyUI\comfy\samplers.py", line 574, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "Q:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "Q:\ComfyUI\comfy\k_diffusion\sampling.py", line 779, in sample_lcm
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "Q:\ComfyUI\comfy\samplers.py", line 297, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "Q:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 993, in __call__
    return self.predict_noise(*args, **kwargs)
  File "Q:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1043, in predict_noise
    out = super().predict_noise(*args, **kwargs)
  File "Q:\ComfyUI\comfy\samplers.py", line 659, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "Q:\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\nodes.py", line 52, in sampling_function_patched
    out = comfy.samplers.calc_cond_batch(model, conds, x, timestep, model_options)
  File "Q:\ComfyUI\comfy\samplers.py", line 226, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 64, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "Q:\ComfyUI\comfy\model_base.py", line 114, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "Q:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "Q:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "Q:\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 852, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "Q:\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "Q:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "Q:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "Q:\ComfyUI\comfy\ldm\modules\attention.py", line 694, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "Q:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "Q:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "Q:\ComfyUI\comfy\ldm\modules\attention.py", line 560, in forward
    n, context_attn1, value_attn1 = p(n, context_attn1, value_attn1, extra_options)
  File "Q:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_lllite.py", line 55, in __call__
    if self.control.t > self.control.timestep_range[0] or self.control.t < self.control.timestep_range[1]:
TypeError: '>' not supported between instances of 'NoneType' and 'float'

Prompt executed in 26.83 seconds

https://civitai.com/models/136070?modelVersionId=267507

I used the above control net model
The uploaded image contains EXIF.

What's interesting is that it works if you leave the wildcard contents blank.

**Comment by ltdrdata** [comment]
I cannot reproduce that issue.

Update to latest version all.
And disable all other custom nodes.
And try again.

**Comment by ytoaa** [comment]
> 저는 그 문제를 재현할 수 없습니다.
> 
> 최신 버전으로 업데이트하세요. 그리고 다른 모든 사용자 정의 노드를 비활성화하세요. 그리고 다시 시도하세요.

After all updates in comfyui, the above workflow is imported and executed, and the same results are displayed.
Would you like to take the workflow above and try it?

**Comment by ytoaa** [comment]
> I cannot reproduce that issue.
> 
> Update to latest version all. And disable all other custom nodes. And try again.

After all updates in comfyui, the above workflow is imported and executed, and the same results are displayed.
Would you like to take the above png file to comfyui as it is and run it?

**Comment by ltdrdata** [comment]
> > I cannot reproduce that issue.
> > Update to latest version all. And disable all other custom nodes. And try again.
> 
> After all updates in comfyui, the above workflow is imported and executed, and the same results are displayed. Would you like to take the above png file to comfyui as it is and run it?

I have already tried that.
Have you minimized the custom nodes and tested it?

![try-reproduce](https://github.com/user-attachments/assets/a8e6121a-11d5-4776-b799-cefe75568cda)

**Comment by ytoaa** [comment]
> > > I cannot reproduce that issue.
> > > Update to latest version all. And disable all other custom nodes. And try again.
> > 
> > 
> > After all updates in comfyui, the above workflow is imported and executed, and the same results are displayed. Would you like to take the above png file to comfyui as it is and run it?
> 
> I have already tried that. Have you minimized the custom nodes and tested it?
> 
> ![try-reproduce](https://private-user-images.githubusercontent.com/128333288/350793518-a8e6121a-11d5-4776-b799-cefe75568cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTQ2NDcsIm5iZiI6MTcyMTU5NDM0NywicGF0aCI6Ii8xMjgzMzMyODgvMzUwNzkzNTE4LWE4ZTYxMjFhLTExZDUtNDc3Ni1iNzk5LWNlZmU3NTU2OGNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQyMDM5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2VlNWM4ZmMwMmZlMjhlYWY0ZGMwZjZmZTQ4NDUxNTk0N2VhOTExMzY2NWZlMjgzMjhhNTVjMjRjOWQ3ZjQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MOxaRm5m6sFtrshD94Jw5rBJRZsZ1kYLLaCiKsDcPdI)

Yes, I disabled all nodes and enabled only the required nodes, but it was still the same..

**Comment by ytoaa** [comment]
> > > I cannot reproduce that issue.
> > > Update to latest version all. And disable all other custom nodes. And try again.
> > 
> > 
> > After all updates in comfyui, the above workflow is imported and executed, and the same results are displayed. Would you like to take the above png file to comfyui as it is and run it?
> 
> I have already tried that. Have you minimized the custom nodes and tested it?
> 
> ![try-reproduce](https://private-user-images.githubusercontent.com/128333288/350793518-a8e6121a-11d5-4776-b799-cefe75568cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTUyMTcsIm5iZiI6MTcyMTU5NDkxNywicGF0aCI6Ii8xMjgzMzMyODgvMzUwNzkzNTE4LWE4ZTYxMjFhLTExZDUtNDc3Ni1iNzk5LWNlZmU3NTU2OGNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQyMDQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjA5MWMzNTI0MzFiZTI5NTdkZWU3YzU2NWUyZjFkNzE2OTEyZTU4MTYyYjI2NWIxNDVmYzI3OTZiNGM2YWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U8eWrILwHRa6gOtlRHi0Ypg_XJDikJnVpWg9o0_AHoQ)

I know the cause. An error occurs as soon as I write something in the wildcard spec space.

**Comment by ltdrdata** [comment]
> > > > I cannot reproduce that issue.
> > > > Update to latest version all. And disable all other custom nodes. And try again.
> > > 
> > > 
> > > After all updates in comfyui, the above workflow is imported and executed, and the same results are displayed. Would you like to take the above png file to comfyui as it is and run it?
> > 
> > 
> > I have already tried that. Have you minimized the custom nodes and tested it?
> > ![try-reproduce](https://private-user-images.githubusercontent.com/128333288/350793518-a8e6121a-11d5-4776-b799-cefe75568cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTUyMTcsIm5iZiI6MTcyMTU5NDkxNywicGF0aCI6Ii8xMjgzMzMyODgvMzUwNzkzNTE4LWE4ZTYxMjFhLTExZDUtNDc3Ni1iNzk5LWNlZmU3NTU2OGNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQyMDQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjA5MWMzNTI0MzFiZTI5NTdkZWU3YzU2NWUyZjFkNzE2OTEyZTU4MTYyYjI2NWIxNDVmYzI3OTZiNGM2YWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U8eWrILwHRa6gOtlRHi0Ypg_XJDikJnVpWg9o0_AHoQ)
> 
> I know the cause. An error occurs as soon as I write something in the wildcard spec space.

confirmed

**Comment by ytoaa** [comment]
> > > > > I cannot reproduce that issue.
> > > > > Update to latest version all. And disable all other custom nodes. And try again.
> > > > 
> > > > 
> > > > After all updates in comfyui, the above workflow is imported and executed, and the same results are displayed. Would you like to take the above png file to comfyui as it is and run it?
> > > 
> > > 
> > > I have already tried that. Have you minimized the custom nodes and tested it?
> > > ![try-reproduce](https://private-user-images.githubusercontent.com/128333288/350793518-a8e6121a-11d5-4776-b799-cefe75568cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1OTUyMTcsIm5iZiI6MTcyMTU5NDkxNywicGF0aCI6Ii8xMjgzMzMyODgvMzUwNzkzNTE4LWE4ZTYxMjFhLTExZDUtNDc3Ni1iNzk5LWNlZmU3NTU2OGNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQyMDQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjA5MWMzNTI0MzFiZTI5NTdkZWU3YzU2NWUyZjFkNzE2OTEyZTU4MTYyYjI2NWIxNDVmYzI3OTZiNGM2YWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U8eWrILwHRa6gOtlRHi0Ypg_XJDikJnVpWg9o0_AHoQ)
> > 
> > 
> > I know the cause. An error occurs as soon as I write something in the wildcard spec space.
> 
> confirmed

Is this a kind of bug?

**Comment by ltdrdata** [comment]
This is patched...

When using advanced controlnet, if you apply a wildcard, the positive is replaced with the wildcard's conditioning, causing a mismatch between positive and negative, which was leading to crashes.

Although it's not recommended to apply controlnet directly to FaceDetailer.
