### ISSUE TITLE
Any Switch with Inspire Lora Loader with Weight Blocks

### ISSUE THREAD

**Issue by ai-waifu-life** [ltdrdata/ComfyUI-Impact-Pack#676]
![BrokenFlow](https://github.com/user-attachments/assets/2106d94d-44a5-4cb6-9f9d-790bebbfa683)

This flow should work to allow automatic skipping of Lora that aren't named in the prompt. If the Lora is included, it works fine, but if I remove the text **brushline** from the positive prompt it should trigger the bypass of the Lora Loader. Instead it throws the error below. Any idea why?

> Error occurred when executing LoraLoaderBlockWeight //Inspire:
> 
> list index out of range
> 
>   File "C:\Program Files\ComfyUI\execution.py", line 141, in recursive_execute
>     input_data_all = get_input_data(inputs, class_def, unique_id, outputs, prompt, extra_data)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\ComfyUI\execution.py", line 26, in get_input_data
>     obj = outputs[input_unique_id][output_index]
>           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^

**Comment by ai-waifu-life** [comment]
Someone on Reddit linked me the guide that informed that the limit of ComfyUI limits dynamic input for Selects, but how does it work to select 2, but not 1?

**Comment by ltdrdata** [comment]
> Someone on Reddit linked me the guide that informed that the limit of ComfyUI limits dynamic input for Selects, but how does it work to select 2, but not 1?

From the moment you convert a select to an input and connect a dynamic input, proper functionality is no longer guaranteed. It's best to consider it as being in a garbage state.

If you look at the terminal, you should see a message indicating that only connections with ImpactInt or Primitive are allowed.
