### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by bulutharbeli** [ltdrdata/ComfyUI-Impact-Pack#68]
I am getting this error. I have tried to update Comfui and i tried to install missing nodes on the manager but nothing solve this issue.
![Screenshot_1](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30212464/6cdd40bd-e165-47f5-8d2e-507307fbf6a1)

**Comment by ltdrdata** [comment]
Oh. you need to look terminal.

You cannot execute with missing nodes.
First, you have to check what nodes are missing.

**Comment by bulutharbeli** [comment]
It's showin something like this. Sorry for trouble but i am very new at Comfyui.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30212464/524d404d-52b7-487e-b600-3758a0715e9e)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30212464/7d1efe07-2e8d-4883-bfea-af4a754de2b5)

**Comment by ltdrdata** [comment]
> It's showin something like this. Sorry for trouble but i am very new at Comfyui.
> ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30212464/524d404d-52b7-487e-b600-3758a0715e9e)
> ![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30212464/7d1efe07-2e8d-4883-bfea-af4a754de2b5)
> 


refresh browser then it will list up what node is missing.

**Comment by bulutharbeli** [comment]
Yes i did several times but it doesn't solve :(

**Comment by bulutharbeli** [comment]
It's showing something like this

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30212464/68509f65-7e6c-4f48-a037-5acd27acd996)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/30212464/f382d5c8-f62b-4229-9742-4bce65e61f30)

**Comment by ltdrdata** [comment]
oh.. it belongs to workflow component. That is the reason why you can't install through Manager.

https://github.com/ltdrdata/ComfyUI-Workflow-Component

**Comment by bulutharbeli** [comment]
Right now I'm not getting any errors anymore but I need to experiment a bit more. Thank you for your hard work.
