### ISSUE TITLE
An OSError occurs when trying to link the custom_nodes folder using a symbolic link.

### ISSUE THREAD

**Issue by Rio77Shiina** [ltdrdata/ComfyUI-Impact-Pack#681]
`Loaded ControlNetPreprocessors nodes from \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### ComfyUI-Impact-Pack: Updating dependencies [0 -> 22]

[bold yellow]WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `\\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack/../../` as the ComfyUI path.[/bold yellow]

[bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\models` as the ComfyUI path.[/bold yellow]
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['D:\\github.com\\comfyanonymous\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in '\\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
[ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually.
Traceback (most recent call last):
  File "\\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 295, in <module>
    install()
  File "\\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 292, in install
    impact.config.write_config()
  File "\\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\config.py", line 25, in write_config
    with open(config_path, 'w') as configfile:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '\\\\?\\D:\\symbolic_link\\github.com\\comfyanonymous\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules\\impact\\..\\..\\impact-pack.ini'
### ComfyUI-Impact-Pack: Updating dependencies [0 -> 22]

[bold yellow]WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack/../../` as the ComfyUI path.[/bold yellow]

[bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\models` as the ComfyUI path.[/bold yellow]
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['D:\\github.com\\comfyanonymous\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
[ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually.
Traceback (most recent call last):
  File "D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 295, in <module>
    install()
  File "D:\github.com\comfyanonymous\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 292, in install
    impact.config.write_config()
  File "\\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\config.py", line 25, in write_config
    with open(config_path, 'w') as configfile:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '\\\\?\\D:\\symbolic_link\\github.com\\comfyanonymous\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules\\impact\\..\\..\\impact-pack.ini'
[Impact Pack] Wildcards loading done.Loaded ImpactPack nodes from
 \\?\D:\symbolic_link\github.com\comfyanonymous\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.`

On Windows, creating a symbolic link to the custom_nodes folder triggers an OSError. The node works fine without the link. Nonetheless, linking to an external custom_nodes directory via a symbolic link is a preferred management approach.

**Comment by ltdrdata** [comment]
Using symbolic links for the custom node path can cause various issues, from ComfyUI update failures to other problems, and is not recommended.
