### ISSUE TITLE
Adetailer crashes on  mediapipe_face_mesh_eyes_only

### ISSUE THREAD

**Issue by aadityamundhalia** [ltdrdata/ComfyUI-Impact-Pack#682]
OS Ubuntu
GPU: Nvidia Tesla P40

Happens when running mediapipe_face_mesh_eyes_only

Any help Be appreciated.

![image](https://github.com/user-attachments/assets/45b1fef5-12b3-40f3-adb2-d793de7d0bc7)
![image](https://github.com/user-attachments/assets/fe5f6588-a4f1-45d9-9a74-aeea11744e32)

**Comment by ltdrdata** [comment]
You have come to the wrong repository. 
This is not the repository for **ADetailer**. 

Please inquire at the following repository:
https://github.com/Bing-su/adetailer/issues
