### ISSUE TITLE
Using an input instead of a widget for WildcardTextEncode doesn't work

### ISSUE THREAD

**Issue by cobaltbeau** [ltdrdata/ComfyUI-Impact-Pack#685]
When WildcardTextEncode is set to use an input instead of a widget for the wildcard_text field, the node does not work.  The output will simply be whatever the last output of populated text was.

**Comment by ltdrdata** [comment]
In that case you should not use wildcard_text input.
Use `populated_text` and make sure mode is `fixed`

![workflow (26)](https://github.com/user-attachments/assets/dcb73c59-bb18-4f03-af7a-31d47a99f9c4)
