### ISSUE TITLE
Error wildcards on ComfyUI: 2462[f7a510](2024-08-03)

### ISSUE THREAD

**Issue by traithanhnam90** [ltdrdata/ComfyUI-Impact-Pack#688]
got prompt
[ERROR] An error occurred during the on_prompt_handler processing
Traceback (most recent call last):
  File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\server.py", line 691, in trigger_on_prompt
    json_data = handler(json_data)
                ^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_server.py", line 367, in onprompt
    populate_wildcards(json_data)
  File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_server.py", line 294, in populate_wildcards
    inputs['populated_text'] = wildcard_process(text=inputs['wildcard_text'], seed=input_seed)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 2109, in process
    return impact.wildcards.process(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 249, in process
    pass1, is_replaced1 = replace_options(text)
                          ^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 198, in replace_options
    replaced_string = re.sub(pattern, replace_option, string)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "re\__init__.py", line 185, in sub
  File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 166, in replace_option
    for option in options:
TypeError: 'NoneType' object is not iterable

**Comment by ltdrdata** [comment]
> got prompt [ERROR] An error occurred during the on_prompt_handler processing Traceback (most recent call last): File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\server.py", line 691, in trigger_on_prompt json_data = handler(json_data) ^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_server.py", line 367, in onprompt populate_wildcards(json_data) File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\inspire\inspire_server.py", line 294, in populate_wildcards inputs['populated_text'] = wildcard_process(text=inputs['wildcard_text'], seed=input_seed) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 2109, in process return impact.wildcards.process(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 249, in process pass1, is_replaced1 = replace_options(text) ^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 198, in replace_options replaced_string = re.sub(pattern, replace_option, string) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "re__init__.py", line 185, in sub File "H:\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 166, in replace_option for option in options: TypeError: 'NoneType' object is not iterable

Your Impact Pack is outdated. Update and try again.

**Comment by traithanhnam90** [comment]
I tried to update everything, uninstall the node and reinstall but node still not working.
I restarted the computer wildcards still gives error!

**Comment by ltdrdata** [comment]
> I tried to update everything, uninstall the node and reinstall but node still not working. I restarted the computer wildcards still gives error!

Show me the new log.

**Comment by traithanhnam90** [comment]
![image](https://github.com/user-attachments/assets/6b6427c0-f54d-42b4-9942-9c764c60908a)

**Comment by traithanhnam90** [comment]
![image](https://github.com/user-attachments/assets/a80ff667-10e4-4752-8936-119f0b3b2d14)

![image](https://github.com/user-attachments/assets/0a63db13-ff0b-4c68-ad2c-7a0e3557b57f)

**Comment by ltdrdata** [comment]
> ![image](https://private-user-images.githubusercontent.com/138344817/354869935-6b6427c0-f54d-42b4-9942-9c764c60908a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDMwODAsIm5iZiI6MTcyMjc0Mjc4MCwicGF0aCI6Ii8xMzgzNDQ4MTcvMzU0ODY5OTM1LTZiNjQyN2MwLWY1NGQtNDJiNC05OTQyLTljNzY0YzYwOTA4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwMzM5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODdjNGI5YTY2MTY5MTRiMWUzOTEyZmVhYTIyZTgyMzY3ZDE2ZmVkM2Y0MWU2OTNhZjRlZWE1Yjc2MDczZWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YdcsSciNv5FhK6YzO123W4yMjdco3mX33Qa7uupiQ8w)

Nope your ComfyUI-Impact-Pack isn't updated.
How did you update?

**Comment by traithanhnam90** [comment]
> 
> Nope your ComfyUI-Impact-Pack isn't updated. How did you update?
I use ComfyUi Manager and and I manually downloaded the node in the .zip file here too!

**Comment by traithanhnam90** [comment]
After deleting everything, I used the command:

git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack.git

and it helped the node work normally, thank you for your support.
Thanks a lot because this node of yours is always used by me in ComfyUI
