### ISSUE TITLE
Missing python packages

### ISSUE THREAD

**Issue by Malapris** [ltdrdata/ComfyUI-Impact-Pack#69]
please add these to the requirements.txt so nodes will work : 
segment_anything
piexif

**Comment by ltdrdata** [comment]
if you are using portable version goto portable directory where has run_nvidia_gpu.bat in cmd.
and execute this

`.\python_embeded\python.exe -s -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt`

or

`.\python_embeded\python.exe -s -m pip install segment_anything piexif`

if there is errors. show me the error messages.
