### ISSUE TITLE
Need vital info where to get required models

### ISSUE THREAD

**Issue by ssbugman** [ltdrdata/ComfyUI-Impact-Pack#690]
Phrase "Pass the MMDetLoader 's bbox model and the detection model loaded by SAMLoader to FaceDetailer ." is useless without info where to get those 2.
Those are not commonly used models and even google gives no info what it is and where to get it.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/691#issuecomment-2269338515
