### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by nodegraphics** [ltdrdata/ComfyUI-Impact-Pack#693]
i cant seem to find the problem for this error. any ideas ? 

```
Error occurred when executing PixelTiledKSampleUpscalerProvider:

object of type 'NoneType' has no len()

File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 96, in get_output_data
output_is_list = [False] * len(results[0])
```

**Comment by ltdrdata** [comment]
It means that among the inputs passed to `PixelTiledKSampleUpscalerProvider`, there is an input that is a list, and this list is empty.

**Comment by nodegraphics** [comment]
ok so i wasnt getting this error before, or maybe im missing a step that i forgot about. 
after i set it up im still getting the same error. any ideas why it might occur ?


![Screenshot - 2024-08-07 00 29 22](https://github.com/user-attachments/assets/1ccaaecf-75b2-4edd-93f1-6dd884bbc3c6)

![Screenshot - 2024-08-07 00 31 38](https://github.com/user-attachments/assets/61459ddf-36c6-4587-a3b1-375da3c421e9)

**Comment by nodegraphics** [comment]
i just tried with non tile version of the node and it works as intended. but the tile version is giving me same error which i remember not getting it before

![Screenshot - 2024-08-07 00 41 39](https://github.com/user-attachments/assets/e5fea597-d38e-43f4-b0a1-8c49d80cd07c)

**Comment by nodegraphics** [comment]
Hi again,
Im including a basic workflow to replicate the problem.
attached as PNG and JSON below

Thank you

![PixelTILED_HavingProblem_01](https://github.com/user-attachments/assets/0f0d5f99-ff9b-4657-ad49-54237cc99aa3)


[PixelTILE_HavingProblem_01.json](https://github.com/user-attachments/files/16536364/PixelTILE_HavingProblem_01.json)

**Comment by ltdrdata** [comment]
> Hi again, Im including a basic workflow to replicate the problem. attached as PNG and JSON below
> 
> Thank you
> 
> ![PixelTILED_HavingProblem_01](https://private-user-images.githubusercontent.com/10071439/356045986-0f0d5f99-ff9b-4657-ad49-54237cc99aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTE1NDAsIm5iZiI6MTcyMzA5MTI0MCwicGF0aCI6Ii8xMDA3MTQzOS8zNTYwNDU5ODYtMGYwZDVmOTktZmY5Yi00NjU3LWFkNDktNTQyMzdjYzk5YWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MTZmOGY3ZjEzMjhlNmQ4ZTcwYzBiMThlMTFhZWM4N2RkYzNmYWQ3YjQ5NDA3N2Q4N2I1YmI3ODUwMWM5MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.voXM-pC-C_CRY6gbEV5LxMY_HkSksXGRnMkwYTNnt9Y)
> 
> [PixelTILE_HavingProblem_01.json](https://github.com/user-attachments/files/16536364/PixelTILE_HavingProblem_01.json)

I'll take a look later.

**Comment by ltdrdata** [comment]
You haven't installed 'BlenderNeko/ComfyUI_TiledKSampler'.
Now Impact Pack will show proper error message in that case.

**Comment by nodegraphics** [comment]
yes, it did fix.
I did have it installed but i needed to go to manager and update it manually. 

Thank you
