### ISSUE TITLE
Switch(any) node slot bug

### ISSUE THREAD

**Issue by fc100b** [ltdrdata/ComfyUI-Impact-Pack#695]
When i use load image node and connect the slot image to reroute, the input slot of Switch(any) node can't connet the reroute node. It can just can connect the slot image directly.

**Comment by ltdrdata** [comment]
It's not a bug. It's intentional thing.
Connecting a reroute to a Switch node is prohibited because it causes an issue where the connection becomes corrupted when refreshing the workflow.
This is because the reroute node behaves differently from regular nodes.
