### ISSUE TITLE
Question about the Process Order

### ISSUE THREAD

**Issue by nodegraphics** [ltdrdata/ComfyUI-Impact-Pack#699]
Hello,

I would like to know if it is possible to determine the order of iterative upscale elements. I sometimes use more than one, and I notice that instead of starting from the beginning, it seems to go randomly, or perhaps it follows an order that I am not aware of. Is there a way to determine which one to go through first, second, and so on?

![Screenshot - 2024-08-08 14 48 57](https://github.com/user-attachments/assets/796e8ef4-fec1-4eea-ba9a-dbb6c4dde02b)

**Comment by ltdrdata** [comment]
There are some tricks, but it's correct to assume that it's not fundamentally guaranteed.
(Especially since the workflow execution method is going to change drastically next week's update, it's unpredictable.)

The important question is: why do you need the execution order?

**Comment by nodegraphics** [comment]
Got it, then it's worth waiting for now. We can revisit this question after I work with next week's update maybe ? at least for tricks that might be worth to explore.

To answer your question: 
The reason I asked is that I sometimes have more than 3-4 different setups in single workflow, and it sometimes starts with the slowest and most time-consuming one. If I could determine the order, I would always have an initial fast version as a preview to check if everything is good before letting the queue move forward to complex / hires setups.

**Comment by ltdrdata** [comment]
![workflow (31)](https://github.com/user-attachments/assets/62d01cf7-a662-45ec-973a-a8b31fc94f99)

I added `Execution Order Controller` node.
You can control execution order via this node.

**Comment by nodegraphics** [comment]
Thank you so much 🙏 you are awesome !! @ltdrdata 
just to understand better. I would like to ask couple of questions about the node:

1) i add this node to whichever setup i want as initial run right ? and `Signal` can be a latent or image depending on the setup ? 

2) Can i chain them up and take the signal from each other ? (image attached) 


workflow
![workflow_31b](https://github.com/user-attachments/assets/e8cdb9ce-5499-4f40-a332-967f9357dc0c)

screenshot for 2
![Screenshot - 2024-08-09 09 32 37](https://github.com/user-attachments/assets/b2f771b2-b689-4d07-80c1-58f6a6872ea4)

**Comment by ltdrdata** [comment]
Signal and value can be arbitrary types.

They are passed to output without any touch. It's just a trick node.

**Comment by nodegraphics** [comment]
I love it !! Thank you
