### ISSUE TITLE
__init__.py file not found error

### ISSUE THREAD

**Issue by gomaxlou** [ltdrdata/ComfyUI-Impact-Pack#7]
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1205, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\__init__.py'

**Comment by ltdrdata** [comment]
You must not clone whole repo now.  Just copy https://github.com/ltdrdata/ComfyUI-Impact-Pack/raw/Main/comfyui-impact-pack.py this file into custom_nodes directory.

Maybe I have to change some install structure.

**Comment by r7l** [comment]
>Maybe I have to change some install structure.

Was about to open a ticket for the install process as well. I might just use this one.

The install process currently is not working well when being used in a Docker environment. I've created myself a Dockerfile for ComfyUI and [a number](https://github.com/WASasquatch/comfyui-plugins/blob/main/README.md) of [custom nodes](https://github.com/wyrde/wyrde-comfyui-workflows).

Since you've implemented some autoinstall on startup, it is rebuilding (incl. downloading) everytime i am starting the container. Beside the fact it's wasting bandwidth it's also taking longer for ComfyUI to start.

Can you please consider a better way for manual install and add a `requirements.txt` file for the dependencies?

**Comment by ltdrdata** [comment]
> >Maybe I have to change some install structure.
> 
> Was about to open a ticket for the install process as well. I might just use this one.
> 
> The install process currently is not working well when being used in a Docker environment. I've created myself a Dockerfile for ComfyUI and [a number](https://github.com/WASasquatch/comfyui-plugins/blob/main/README.md) of [custom nodes](https://github.com/wyrde/wyrde-comfyui-workflows).
> 
> Since you've implemented some autoinstall on startup, it is rebuilding (incl. downloading) everytime i am starting the container. Beside the fact it's wasting bandwidth it's also taking longer for ComfyUI to start.
> 
> Can you please consider a better way for manual install and add a `requirements.txt` file for the dependencies?

Is your docker environment wipe all when shutdown?
The auto installer sequence install only for missing components.

And there is a little bit complex issue.
There is mim package not only pip package. And some detection models are included there.

Maybe I can provide install.py.
But I am not sure it will help you.

**Comment by gomaxlou** [comment]
> > Maybe I have to change some install structure.
> 
> Was about to open a ticket for the install process as well. I might just use this one.
> 
> The install process currently is not working well when being used in a Docker environment. I've created myself a Dockerfile for ComfyUI and [a number](https://github.com/WASasquatch/comfyui-plugins/blob/main/README.md) of [custom nodes](https://github.com/wyrde/wyrde-comfyui-workflows).
> 
> Since you've implemented some autoinstall on startup, it is rebuilding (incl. downloading) everytime i am starting the container. Beside the fact it's wasting bandwidth it's also taking longer for ComfyUI to start.
> 
> Can you please consider a better way for manual install and add a `requirements.txt` file for the dependencies?

i clone all files, and compare comfyui-impack-pack.py is the same

**Comment by gomaxlou** [comment]
> You must not clone whole repo now. Just copy https://github.com/ltdrdata/ComfyUI-Impact-Pack/raw/Main/comfyui-impact-pack.py this file into custom_nodes directory.
> 
> Maybe I have to change some install structure.

i clone all files, and compare comfyui-impack-pack.py is the same

**Comment by gomaxlou** [comment]
> You must not clone whole repo now. Just copy https://github.com/ltdrdata/ComfyUI-Impact-Pack/raw/Main/comfyui-impact-pack.py this file into custom_nodes directory.
> 
> Maybe I have to change some install structure.

1. copy ComfyUI-Impact-Pack.py to custom-nodes directory, and  restart,
2.  after install dependency lib, get the same error message : FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\__init__.py'

**Comment by ltdrdata** [comment]
> > You must not clone whole repo now. Just copy https://github.com/ltdrdata/ComfyUI-Impact-Pack/raw/Main/comfyui-impact-pack.py this file into custom_nodes directory.
> > 
> > Maybe I have to change some install structure.
> 
> 1. copy ComfyUI-Impact-Pack.py to custom-nodes directory, and  restart,
> 2.  after install dependency lib, get the same error message : FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\__init__.py'

No. Don't make ComfyUI-Impact-Pack directory. Just copy .py file into custom_nodes itself.
And delete that directory.

**Comment by gomaxlou** [comment]
> > > You must not clone whole repo now. Just copy https://github.com/ltdrdata/ComfyUI-Impact-Pack/raw/Main/comfyui-impact-pack.py this file into custom_nodes directory.
> > > Maybe I have to change some install structure.
> > 
> > 
> > 
> > 1. copy ComfyUI-Impact-Pack.py to custom-nodes directory, and  restart,
> > 2. after install dependency lib, get the same error message : FileNotFoundError: [Errno 2] No such file or directory: 'D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\**init**.py'
> 
> No. Don't make ComfyUI-Impact-Pack directory. Just copy .py file into custom_nodes itself. And delete that directory.

It has been successful~ thanks

**Comment by ltdrdata** [comment]
> > Maybe I have to change some install structure.
> 
> Was about to open a ticket for the install process as well. I might just use this one.
> 
> The install process currently is not working well when being used in a Docker environment. I've created myself a Dockerfile for ComfyUI and [a number](https://github.com/WASasquatch/comfyui-plugins/blob/main/README.md) of [custom nodes](https://github.com/wyrde/wyrde-comfyui-workflows).
> 
> Since you've implemented some autoinstall on startup, it is rebuilding (incl. downloading) everytime i am starting the container. Beside the fact it's wasting bandwidth it's also taking longer for ComfyUI to start.
> 
> Can you please consider a better way for manual install and add a `requirements.txt` file for the dependencies?

I changed structure of impact-pack.
Try this branch.

https://github.com/ltdrdata/ComfyUI-Impact-Pack/tree/new-install

**git clone** and **install.py** mechanism

**Comment by r7l** [comment]
@ltdrdata Thanks allot. 

It works and no longer downloads or rebuilds anything when starting. The only thing that caused some confusion is that you're [forcing](https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/new-install/impact_pack.py#L3) the directory name within `custom_nodes` directory. I've had the directory called `impact_pack` first and this failed during startup.

**Comment by ltdrdata** [comment]
> @ltdrdata Thanks allot.
> 
> It works and no longer downloads or rebuilds anything when starting. The only thing that caused some confusion is that you're [forcing](https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/new-install/impact_pack.py#L3) the directory name within `custom_nodes` directory. I've had the directory called `impact_pack` first and this failed during startup.

patched that issue.
