### ISSUE TITLE
Is it possible to repeat execution of ImpactWildcardProcessor before the workflow has finished? (Loop testing with Comfy PR#2666)

### ISSUE THREAD

**Issue by itswhateverman** [ltdrdata/ComfyUI-Impact-Pack#702]
Testing ComfyUI PR#2666 - [Execution Inversion](https://github.com/comfyanonymous/ComfyUI/pull/2666#top) in conjunction with ImpactWildcardProcessor.  

The goal is to be able to iterate through a batch of Clip text encodes in a for loop as an initial step and then send the accumulated list of conditionings to the sampler for processing, to reduce model loads in Low VRAM scenarios such that Comfy doesn't need to flip back and forth between having the text encoder vs the unet loaded quite as often.  

However the ImpactWildcardProcessor doesn't advance and provide a new prompt during the loop, so while the overall logic works, it ultimately sends the same data to the text encode at each iteration of the loop. Is there a way to trigger the ImpactWildcardProcessor to regenerate new output before the workflow execution has finished?

**Comment by itswhateverman** [comment]
Example workflow:
[wildcard_loop_example.json](https://github.com/user-attachments/files/16606579/wildcard_loop_example.json)

**Comment by ltdrdata** [comment]
Take a look these solutions. You need to combine these approaches.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/685
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/679

**Comment by guill** [comment]
In case anyone else is looking at this question and needs some additional guidance, here's the "fixed" version of @itswhateverman's example workflow (using @ltdrdata's advice from #685)

[fixed_wildcard_loop_example.json](https://github.com/user-attachments/files/16621716/fixed_wildcard_loop_example.json)
