### ISSUE TITLE
How to implement dynamic input in switch any node

### ISSUE THREAD

**Issue by xm1085** [ltdrdata/ComfyUI-Impact-Pack#706]
I am a newcomer to comfyui, recently I was making custom nodes, I found your switch any node is very interesting, after input1 input content node will automatically add input interface input2, I want to know how to do this, because I also want to do a similar function, What materials do I need to refer to? Or you can give me a hint

**Comment by ltdrdata** [comment]
It is implemented in front-end. Little bit dirty.
https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/94f30ef317d4607a2d91ac222b2bdf4addb1ea66/js/impact-pack.js#L434
