### ISSUE TITLE
Converting Scheduler to input doesn't allow connections to separate scheduler

### ISSUE THREAD

**Issue by TheKraken2024** [ltdrdata/ComfyUI-Impact-Pack#708]
I had this brilliant idea to use the same schedular/sampler output for Ksampler, SD Upscale & Face Detailer so they are all the same when I change models.

However when changing Scheduler widget to input it will NOT take a connection from a scheduler node.  Nor will it get the data from an anything everywhere node.

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/21967e18-9877-455e-ad00-eb7f6c20e83e)
Use `Impact Scheduler Adapter`.

The sampling nodes of Impact Pack are not compatible with the Scheduler input of the basic nodes because they allow for an additional Scheduler.
