### ISSUE TITLE
UltralyticsDetectorProvider won't load

### ISSUE THREAD

**Issue by ExiaCyn** [ltdrdata/ComfyUI-Impact-Pack#71]
When running my UI I get the following on loading the interface;

When loading the graph, the following node types were not found:
UltralyticsDetectorProvider
Nodes that have failed to load will show as red on the graph.

I fully installed all the dependencies manually and the pack is in the correct custom nodes folder. Everythnig else in the impact pack works fine. Is it an issue with it being in the folder "subpack"? Does it need to be copied out to another directory? The readme doesn't indicate it does but it is the only component not working.

**Comment by ltdrdata** [comment]
Oh you didn't installed through `ComfyUI-Manager`?
In that case execute `install.py` through your proper python environment.
(if you are using portable version you have to use `python_embeded\python.exe`)

**Comment by ExiaCyn** [comment]
This is probably very obvious but I can't understand it. I've run cmd in the subpack 

C:\AI Training\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack with the command python_embeded\python.exe install.py

I'm not really that great with this and trying to figure it out. I tried it with the full  path as well;
"C:\AI Training\ComfyUI_windows_portable\python_embeded" install.py and still no luck

**Comment by ltdrdata** [comment]
No you have not `subpack` yet.
You should execute in ComfyUI-Impact-Pack directory.
(`C:\AI Training\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack`)

```
"C:\AI Training\ComfyUI_windows_portable\python_embeded\python.exe" install.py 
```

It will install things..
If it won't work just try this in `ComfyUI-Impact-Pack`  dir.
`git submodule update --init --recursive`

**Comment by ExiaCyn** [comment]
Fantastic thank you! That fixed it. Really appreciate the fast replies as well.
