### ISSUE TITLE
Does this node not support HQ-SAM ？

### ISSUE THREAD

**Issue by O-O1024** [ltdrdata/ComfyUI-Impact-Pack#710]
[SAM、HQ-SAM、MobileSAM](https://github.com/storyicon/comfyui_segment_anything#sam)

I have already put a HQ-SAM model (`sam_hq_vit_b.pth`) to `ComfyUI/models/sams`, but this node still downloads a SAM version model (`sam_vit_b_01ec64.pth`).

**Comment by ltdrdata** [comment]
Impact Pack doesn't support HQ-SAM.
So far, I'm skeptical about the necessity of HQ-SAM.

That's one of the reasons I'm postponing support for HQ-SAM.
Instead, I'm planning to implement SAM2 because its utility is different.

**Comment by O-O1024** [comment]
Expecting!
