### ISSUE TITLE
PixelTiledKSampleUpscalerProviderPipe > Question

### ISSUE THREAD

**Issue by nodegraphics** [ltdrdata/ComfyUI-Impact-Pack#711]
I usually use this node without an upscale model, but I'd like to ask if this is the correct approach, considering there's an input for an upscale model. My question is: If I connect a Load Upscale Model node, will it affect the setup in any way? Could it have a negative impact, such as quality degradation? What is the best practice?

<img width="441" alt="Screenshot - 2024-08-19 12 11 31" src="https://github.com/user-attachments/assets/c7ad8fdb-a77b-4a7c-81e9-f1bc380e55c1">

**Comment by ltdrdata** [comment]
The upscale model is just an option. It's not mandatory, and applying it doesn't guarantee better results.

Essentially, it's a node that performs upscaling followed by img2img (image-to-image). It simply determines how to handle the roughly upscaled image that serves as the basis for img2img.

If you want to maintain a form as close to the original as possible and use low denoise settings, using an upscale model might be appropriate. However, if you're increasing the denoise to introduce new details, then using an upscale model becomes meaningless.

**Comment by nodegraphics** [comment]
Thank you🙏
