### ISSUE TITLE
Excuse me, Can we add this feature?

### ISSUE THREAD

**Issue by 807502278** [ltdrdata/ComfyUI-Impact-Pack#714]
It makes the judgment nodes run more efficiently. don't know why it was cancelled...
![image](https://github.com/user-attachments/assets/fd757bc2-866c-419b-920b-5e6fc576596e)

**Comment by mijuku233** [comment]
![image](https://github.com/user-attachments/assets/cb86b1ad-64ff-4acd-944d-9f9de20dedf5)

It seems some recent changes broke it

**Comment by mijuku233** [comment]
This change seems to be for the merged version of `pr2666`. 
If your comfyui supports `Execution Model Inversion`, `selmode` will be disabled. 
But disabling `selmode` seems unnecessary for the `conditionbranch` node that does not add `lazy evaluation`.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/pull/716 is merged.

**Comment by 807502278** [comment]
Thank you very much. pr2666 has perfectly solved my problem.
