### ISSUE TITLE
期待SAM2的实现

### ISSUE THREAD

**Issue by daoliangai** [ltdrdata/ComfyUI-Impact-Pack#715]
大佬，什么时候能够实现SAM2啊？作为comfyui中顶尖重要的插件，期待SAM2的实现，因为SAM2的效果的确不错。
使用场景：在使用anmiatediff时叠加controlnet修复画面。

**Comment by ltdrdata** [comment]
I am trying to implement it as soon as possible, but it's being slightly delayed due to other ongoing tasks.

**Comment by Vigilence** [comment]
If you add dummy input to the detailer you can use florence2 -> sam2 -> segs mask -> detailer pipe.  Detailer pipe would use dummy input for bbox and no need for Sam input etc.

https://openart.ai/workflows/runebinder/easy-flux-inpaint-florence-sam2-segs-detailer/WbgLBFA3MmdDwuXy4g92
