### ISSUE TITLE
Batch segs?

### ISSUE THREAD

**Issue by Vigilence** [ltdrdata/ComfyUI-Impact-Pack#717]
Is it possible to have the Detailer node have segs created in batch?  I have Florence2 create an annotation then send it to sam2 to create a mask then I send that mask the the Detailer pipe node to recreate the area.  Unfortunately this is done 1 at a time.  I would like to have it created a few at a time if possible.  

I also wanted to know if I can also have all those segs display in a picker and then pick my favorite to move forward with the workflow.

**Comment by ltdrdata** [comment]
I plan to create a separate node that supports SAM2 for use with AnimateDiff.

**Comment by Vigilence** [comment]
Sweet!  I am just using it for single art images, would that be possible with what you are adding?

**Comment by Vigilence** [comment]
I think [this video](https://www.youtube.com/watch?v=ftngQNmSJQQ) actually covers what I am referring to.

**Comment by Vigilence** [comment]
I think [this video](https://www.youtube.com/watch?v=ftngQNmSJQQ) actually covers what I am referring to.
