### ISSUE TITLE
No module named 'win32gui'

### ISSUE THREAD

**Issue by Enchante503** [ltdrdata/ComfyUI-Impact-Pack#718]
I'm using WSL2 Ubuntu 22.04.4 LTS

I'm having trouble with being asked for modules for Windows

How can I get around this?

Why not write code to detect the platform and get around it?

```
/home/user/ComfyUI/custom_nodes/ComfyUI_toyxyz_test_nodes/toyxyz_test_nodes.py", line 14, in <module>
    import win32gui
ModuleNotFoundError: No module named 'win32gui'

Warn!: Cannot import /home/user/ComfyUI/custom_nodes/ComfyUI_toyxyz_test_nodes module for custom nodes: No module named 'win32gui'
```

**Comment by ltdrdata** [comment]
That issue should be handled in:
https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes/issues
