### ISSUE TITLE
using two PreviewDetailersHookProvider is not working...

### ISSUE THREAD

**Issue by APCOTech** [ltdrdata/ComfyUI-Impact-Pack#723]
Hi again, I am just using the workflows you provide. The issue is with workflow with this video (https://www.youtube.com/watch?v=bEqF4jbLCOc) ComfyUI-Impact-Pack - Workflow: Upscaling with Make Tile SEGS

I tried many times to apply flux to this workflow and I asked you on youtube about it and I managed to get to work.. The problem is:

In your workflow each (Detailer (SEGS/pipe)) nodes have a PreviewDetailersHookProvider. After the latest ComfyUI huge update... The first PreviewDetailersHookProvider is always blank and the  Detailer (SEGS/pipe) is using the other PreviewDetailersHookProvider. Actually, The two Detailer (SEGS/pipe) use only the last PreviewDetailersHookProvider. I do not know if this is intended by you or an issue from my side?

### Loading: ComfyUI-Impact-Pack (V7.3.1)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2615 [c6812947] | Released on '2024-08-26'

I would be very grateful for any help.

**Comment by ltdrdata** [comment]
This issue is fixed.
