### ISSUE TITLE
FaceDetailer/MaskDetailer clears the model cache, which significantly slows down generation with LoRAs in Flux

### ISSUE THREAD

**Issue by bananasss00** [ltdrdata/ComfyUI-Impact-Pack#724]
Nvidia RTX 4080 16GB

If generating without FaceDetailer, the first generation hangs on KSampler and takes a long time while the LoRAs patch the model. Subsequent generations are faster because the patched model is cached. However, after running FaceDetailer/MaskDetailer, the model cache is cleared, causing the LoRAs to patch the model again for each generation, which takes too much unnecessary time.

I added a stacktrace using my custom node PyExec (https://github.com/bananasss00/Comfyui-PyExec) to the function comfy.model_management.soft_empty_cache to determine what is causing the constant cache reset:
```
loaded completely 9.5367431640625e+25 11350.048889160156 True
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.59it/s]
soft_empty_cache(False)
<FrameSummary file threading.py, line 1002 in _bootstrap>
<FrameSummary file threading.py, line 1045 in _bootstrap_inner>
<FrameSummary file threading.py, line 982 in run>
<FrameSummary file V:\comfyu_py311\ComfyUI\main.py, line 125 in prompt_worker>
<FrameSummary file V:\comfyu_py311\ComfyUI\execution.py, line 494 in execute>
<FrameSummary file V:\comfyu_py311\ComfyUI\execution.py, line 317 in execute>
<FrameSummary file V:\comfyu_py311\ComfyUI\execution.py, line 192 in get_output_data>
<FrameSummary file V:\comfyu_py311\ComfyUI\execution.py, line 169 in _map_node_over_list>
<FrameSummary file V:\comfyu_py311\ComfyUI\execution.py, line 158 in process_inputs>
<FrameSummary file V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py, line 1375 in doit>
<FrameSummary file V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py, line 529 in enhance_face>
<FrameSummary file V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py, line 305 in do_detail>
<FrameSummary file V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py, line 356 in enhance_detail>
<FrameSummary file V:\comfyu_py311\ComfyUI\comfy\sd.py, line 320 in decode>
<FrameSummary file V:\comfyu_py311\ComfyUI\comfy\model_management.py, line 495 in load_models_gpu>
<FrameSummary file V:\comfyu_py311\ComfyUI\comfy\model_management.py, line 451 in free_memory>
<FrameSummary file <string>, line 10 in soft_empty_cache>
Prompt executed in 21.50 seconds
```

ComfyUI-Impact-Pack\modules\impact\core.py:
```py
try:
    # try to decode image normally
    >>> refined_image = vae.decode(refined_latent['samples'])
except Exception as e:
```

comfy\sd.py:
```py
def decode(self, samples_in):
    try:
        memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)
        >>> model_management.load_models_gpu([self.patcher], memory_required=memory_used)
        free_memory = model_management.get_free_memory(self.device)
        batch_number = int(free_memory / memory_used)
        batch_number = max(1, batch_number)
```

comfy\model_management.py:
```py
if len(models_to_load) == 0:
    devs = set(map(lambda a: a.device, models_already_loaded))
    for d in devs:
        if d != torch.device("cpu"):
            >>> free_memory(extra_mem + offloaded_memory(models_already_loaded, d), d, models_already_loaded)
            free_mem = get_free_memory(d)
            if free_mem < minimum_memory_required:
```

PS:
I have also optimized the **comfy.model_patcher.ModelPatcher.patch_weight_to_device** function for myself. With this optimization, LoRAs apply to the model twice as fast and without OOM on my 16GB VRAM. It's possible that this issue won't be reproducible on 24GB cards, but I'm not sure.
```py
from comfy.model_patcher import ModelPatcher, string_to_seed
import collections, logging, torch, comfy.utils

new_device = 'cuda'
store_device = 'cpu'

def patch_weight_to_device_v1(self, key, device_to=None, inplace_update=False):
    if key not in self.patches:
            return

    weight = comfy.utils.get_attr(self.model, key)

    inplace_update = self.weight_inplace_update or inplace_update

    if key not in self.backup:
        self.backup[key] = collections.namedtuple('Dimension', ['weight', 'inplace_update'])(weight.to(device=self.offload_device, copy=inplace_update), inplace_update)

    temp_weight = weight.to(new_device).to(torch.float32, copy=True)

    out_weight = comfy.lora.calculate_weight(self.patches[key], temp_weight, key)
    out_weight = comfy.float.stochastic_rounding(out_weight, weight.dtype, seed=string_to_seed(key))
    out_weight = out_weight.to(torch.float8_e4m3fn).to(store_device)

    if inplace_update:
        comfy.utils.copy_to_param(self.model, key, out_weight)
    else:
        comfy.utils.set_attr_param(self.model, key, out_weight)

    del weight

ModelPatcher.patch_weight_to_device = patch_weight_to_device_v1
```

Simple workflows:
![workflow (4)](https://github.com/user-attachments/assets/f1b0730f-b8ad-4264-9237-27a768650515)
[workflow (1).json](https://github.com/user-attachments/files/16824263/workflow.1.json)

**Comment by bananasss00** [comment]
**problem when mask_feather > 0**
![image](https://github.com/user-attachments/assets/4e756b1b-5da5-4558-b4ca-902a43e2724c)

```py
[load_models_gpu] models=[<comfy.model_patcher.ModelPatcher object at 0x0000022007BD6F10>], memory_required=1806.45, force_patch_weights=False, minimum_memory_required=903.22, force_full_load=False
  threading.py:_bootstrap:1002
  threading.py:_bootstrap_inner:1045
  threading.py:run:982
  V:\comfyu_py311\ComfyUI\main.py:prompt_worker:125
  V:\comfyu_py311\ComfyUI\custom_nodes\rgthree-comfy\__init__.py:rgthree_execute:217
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-0246\utils.py:new_func:353
  V:\comfyu_py311\ComfyUI\execution.py:execute:494
  V:\comfyu_py311\ComfyUI\execution.py:execute:317
  V:\comfyu_py311\ComfyUI\execution.py:get_output_data:192
  V:\comfyu_py311\ComfyUI\execution.py:_map_node_over_list:169
  V:\comfyu_py311\ComfyUI\execution.py:process_inputs:158
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py:doit:1479
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py:do_detail:305
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py:enhance_detail:346
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py:ksampler_wrapper:241
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py:separated_sample:214
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py:sample_with_custom_noise:158
  V:\comfyu_py311\ComfyUI\custom_nodes\comfyui-diffusion-cg\recenter.py:sample_center:36
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py:motion_sample:420
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py:acn_sample:116
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py:uncond_multiplier_check_cn_sample:117
  V:\comfyu_py311\ComfyUI\comfy\sample.py:sample_custom:48
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py:sample:134
  V:\comfyu_py311\ComfyUI\comfy\samplers.py:sample:729
  V:\comfyu_py311\ComfyUI\comfy\samplers.py:sample:706
  V:\comfyu_py311\ComfyUI\comfy\sampler_helpers.py:prepare_sampling:66
  <string>:load_models_gpu:29
```

When the free_memory function is called, the keep_loaded list becomes empty, and the model is unloaded. (_The free_memory function is always called, even on ksampler, but the keep_loaded list contains the current model, so the model remains in the cache_)
 ```py
[free_memory] memory_required=3255.10, device=cuda:0, keep_loaded=[]
  threading.py:_bootstrap:1002
  threading.py:_bootstrap_inner:1045
  threading.py:run:982
  V:\comfyu_py311\ComfyUI\main.py:prompt_worker:125
  V:\comfyu_py311\ComfyUI\custom_nodes\rgthree-comfy\__init__.py:rgthree_execute:217
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-0246\utils.py:new_func:353
  V:\comfyu_py311\ComfyUI\execution.py:execute:494
  V:\comfyu_py311\ComfyUI\execution.py:execute:317
  V:\comfyu_py311\ComfyUI\execution.py:get_output_data:192
  V:\comfyu_py311\ComfyUI\execution.py:_map_node_over_list:169
  V:\comfyu_py311\ComfyUI\execution.py:process_inputs:158
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py:doit:1479
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py:do_detail:305
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py:enhance_detail:346
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py:ksampler_wrapper:241
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py:separated_sample:214
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py:sample_with_custom_noise:158
  V:\comfyu_py311\ComfyUI\custom_nodes\comfyui-diffusion-cg\recenter.py:sample_center:36
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py:motion_sample:420
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py:acn_sample:116
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py:uncond_multiplier_check_cn_sample:117
  V:\comfyu_py311\ComfyUI\comfy\sample.py:sample_custom:48
  V:\comfyu_py311\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py:sample:134
  V:\comfyu_py311\ComfyUI\comfy\samplers.py:sample:729
  V:\comfyu_py311\ComfyUI\comfy\samplers.py:sample:706
  V:\comfyu_py311\ComfyUI\comfy\sampler_helpers.py:prepare_sampling:66
  <string>:load_models_gpu:33
  V:\comfyu_py311\ComfyUI\comfy\model_management.py:load_models_gpu:523
  <string>:free_memory:20
```

**Comment by ltdrdata** [comment]
Maybe the reason is this.
https://github.com/ltdrdata/ComfyUI/blob/66d35c07ce44b07011314ad7a28b2bdbcbb4e4cc/comfy_extras/nodes_differential_diffusion.py#L16

**Comment by bananasss00** [comment]
![image](https://github.com/user-attachments/assets/30a72cc6-c263-4a71-a7bb-e07e8f0431dc)
I checked the Differential Diffusion separately—the models do not reset


update:
I also tried patching the model, but there was still no reset
![image](https://github.com/user-attachments/assets/7c06ff61-1479-4c2d-9d47-5f4aae23264a)

**Comment by bananasss00** [comment]
> Owner

yes, model clone reason
![image](https://github.com/user-attachments/assets/a3869d2d-e6c6-4815-a103-7d373edc3396)

However, if you connect differential diffusion as a separate node and do not use model.clone(), the model does not get unloaded. Do you have any ideas on what can be done in this situation?

**Comment by ltdrdata** [comment]
From what I've seen, that occurs when the resource usage exceeds the threshold.

**Comment by bananasss00** [comment]
Can we add an option to use DifferentialDiffusion in the node?

I have commented out the differential diffusion code and connected the node externally, which resolves the issues with the lores.

PS: I ran the workflow several times to ensure that the lores are not patching the model again.

![image](https://github.com/user-attachments/assets/c41678ea-851a-4735-8329-7ffe53a409cd)
![image](https://github.com/user-attachments/assets/1fb641b8-a5a0-4b70-b781-77e154caa397)

**Comment by ltdrdata** [comment]
> Can we add an option to use DifferentialDiffusion in the node?
> 
> I have commented out the differential diffusion code and connected the node externally, which resolves the issues with the lores.
> 
> PS: I ran the workflow several times to ensure that the lores are not patching the model again.
> 
> ![image](https://private-user-images.githubusercontent.com/30229634/363512748-c41678ea-851a-4735-8329-7ffe53a409cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDA2OTQsIm5iZiI6MTcyNTI0MDM5NCwicGF0aCI6Ii8zMDIyOTYzNC8zNjM1MTI3NDgtYzQxNjc4ZWEtODUxYS00NzM1LTgzMjktN2ZmZTUzYTQwOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAxMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMWY2M2QxMDYyYWMyZGZjMDViOGQ1MDM3ODRmMDBlOWNhZDA4OWNkMGNiMDUxYzVkNGI0YTUyYzU3NThiZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R23oSlJEVgWJOGGdkBnsfblaVTYb62tc-pPIz0tMw7M) ![image](https://private-user-images.githubusercontent.com/30229634/363512766-1fb641b8-a5a0-4b70-b781-77e154caa397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDA2OTQsIm5iZiI6MTcyNTI0MDM5NCwicGF0aCI6Ii8zMDIyOTYzNC8zNjM1MTI3NjYtMWZiNjQxYjgtYTVhMC00YjcwLWI3ODEtNzdlMTU0Y2FhMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAxMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMGRlZjVmNDM2NGI0NWY1ODE1NTllNWZjOTg0NWI2NTZhNjQxMWQxZTViOGI4NmMyNjUyY2M2ZWJlYmNiYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O6yMq8c6541VjJpfRNzsnPONqEZETzq0ZEzUYZYEHps)

In that case it is recommended to set `noise_mask_feather` to 0. That feature exists for differential diffusion.
Simply blurring the composite boundary at the time of compositing is handled separately by a feature called feather.

**Comment by bananasss00** [comment]
> > Can we add an option to use DifferentialDiffusion in the node?
> > I have commented out the differential diffusion code and connected the node externally, which resolves the issues with the lores.
> > PS: I ran the workflow several times to ensure that the lores are not patching the model again.
> > ![image](https://private-user-images.githubusercontent.com/30229634/363512748-c41678ea-851a-4735-8329-7ffe53a409cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDA2OTQsIm5iZiI6MTcyNTI0MDM5NCwicGF0aCI6Ii8zMDIyOTYzNC8zNjM1MTI3NDgtYzQxNjc4ZWEtODUxYS00NzM1LTgzMjktN2ZmZTUzYTQwOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAxMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMWY2M2QxMDYyYWMyZGZjMDViOGQ1MDM3ODRmMDBlOWNhZDA4OWNkMGNiMDUxYzVkNGI0YTUyYzU3NThiZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R23oSlJEVgWJOGGdkBnsfblaVTYb62tc-pPIz0tMw7M) ![image](https://private-user-images.githubusercontent.com/30229634/363512766-1fb641b8-a5a0-4b70-b781-77e154caa397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNDA2OTQsIm5iZiI6MTcyNTI0MDM5NCwicGF0aCI6Ii8zMDIyOTYzNC8zNjM1MTI3NjYtMWZiNjQxYjgtYTVhMC00YjcwLWI3ODEtNzdlMTU0Y2FhMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDAxMjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMGRlZjVmNDM2NGI0NWY1ODE1NTllNWZjOTg0NWI2NTZhNjQxMWQxZTViOGI4NmMyNjUyY2M2ZWJlYmNiYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O6yMq8c6541VjJpfRNzsnPONqEZETzq0ZEzUYZYEHps)
> 
> In that case it is recommended to set `noise_mask_feather` to 0. That feature exists for differential diffusion. Simply blurring the composite boundary at the time of compositing is handled separately by a feature called feather.

However, if you disable the mask_feather in the facedetailer and connect the differential diffusion externally, there is no option to blur the mask for DD. Without mask blurring, the results at higher denoise values are worse, and DD doesn't work without a blurred mask.
![image](https://github.com/user-attachments/assets/0a85aae6-3d5c-4da1-99aa-00c9fdccbfc1)

That's why I suggested adding another option.

**Comment by ltdrdata** [comment]
I understand what you're looking for. I will take a look at it later. 
Perhaps I can determine if differential diffusion has already been applied in the model. If so, it might be possible to skip it automatically without a separate flag.

**Comment by bananasss00** [comment]
> I understand what you're looking for. I will take a look at it later. Perhaps I can determine if differential diffusion has already been applied in the model. If so, it might be possible to skip it automatically without a separate flag.

```py
model.model_options["denoise_mask_function"]
```

![workflow (9)](https://github.com/user-attachments/assets/b79842a5-d963-4a3b-a39b-583f8bfd8aba)

**Comment by ltdrdata** [comment]
> > I understand what you're looking for. I will take a look at it later. Perhaps I can determine if differential diffusion has already been applied in the model. If so, it might be possible to skip it automatically without a separate flag.
> 
> ```python
> model.model_options["denoise_mask_function"]
> ```
> 
> ![workflow (9)](https://private-user-images.githubusercontent.com/30229634/363612081-b79842a5-d963-4a3b-a39b-583f8bfd8aba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU4NTgsIm5iZiI6MTcyNTI2NTU1OCwicGF0aCI6Ii8zMDIyOTYzNC8zNjM2MTIwODEtYjc5ODQyYTUtZDk2My00YTNiLWEzOWItNTgzZjhiZmQ4YWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MjU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0NTRiNjBjMTEyMTA4ZTI4MjdkMzE2NWZhZTgzNWI1NmVkN2Y1YTAzMTE1ZGU2Y2U0YmRkZTljNWRmNDkxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vElSOiUAYAQLrTt4-Dz4-2KPRNuJiLrW8A-eTQnByWQ)

I was actually planning to utilize that. If a custom `denoise_mask_function` is already set, I believe it makes sense not to override it internally with differential diffusion, whether it was differential diffusion or not.

**Comment by ltdrdata** [comment]
This is fixed.
