### ISSUE TITLE
"[Impact Pack] Wildcards loading done." is repeated.

### ISSUE THREAD

**Issue by miurgh** [ltdrdata/ComfyUI-Impact-Pack#725]
To see the GUI go to: http://0.0.0.0:8188
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
got prompt

The same message repeats.
Loss of control for 1-2 minutes.
What is the problem?

**Comment by ltdrdata** [comment]
It outputs by reloading every time you press the refresh button.

What exactly are your reproduction steps?

**Comment by miurgh** [comment]
Sometimes a new model is installed, and pressing the Refresh button does not reflect the new model.
Press the Refresh button repeatedly several times.
After reloading the browser from there, the workflow may not load and the screen may freeze and the operation may not work.
Sometimes there is no response at all in the browser even after the workflow is loaded and the QuePrompt button is pressed after a long time.
When I look at the Console, the above error message increases one line at a time.

I will be careful not to press the Refresh button repeatedly.

**Comment by ltdrdata** [comment]
> Sometimes a new model is installed, and pressing the Refresh button does not reflect the new model. Press the Refresh button repeatedly several times. After reloading the browser from there, the workflow may not load and the screen may freeze and the operation may not work. Sometimes there is no response at all in the browser even after the workflow is loaded and the QuePrompt button is pressed after a long time. When I look at the Console, the above error message increases one line at a time.
> 
> I will be careful not to press the Refresh button repeatedly.

Is your wildcard huge?

**Comment by miurgh** [comment]
I am not using wildcards. No text files have been created. And yet, the message appears.

**Comment by ltdrdata** [comment]
> I am not using wildcards. No text files have been created. And yet, the message appears.

The message will always appear. It's just that if the wildcard is large, it may affect refresh performance, which is why I asked about it. The performance issue you encountered during refresh appears to have occurred on a different node.
(Perhaps there are too many model files...)
