### ISSUE TITLE
Preview Bridge Default Behavior

### ISSUE THREAD

**Issue by gseth** [ltdrdata/ComfyUI-Impact-Pack#728]
Hi,

The update to the preview bridge is great, however it is breaking existing workflows. Can you please change the default behavior to be set as "never", instead of "if_empty_mask".

All my workflows used it as a pass-on and allowed users to edit the mask if necessary. After the update, the node default reverted to block "if_empty_mask." This creates a problem for many mass users as they don't know that this behavior has changed.

I would appreciate it if the default is changed.

![image](https://github.com/user-attachments/assets/93be4aef-6a93-409a-b79f-6afcd763c75f)

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by gseth** [comment]
Thank you Sir....
