### ISSUE TITLE
3 new input values for Detailers

### ISSUE THREAD

**Issue by Fexnon** [ltdrdata/ComfyUI-Impact-Pack#73]
After disabling mmdet_skip in the impact-pack.ini file to get access to MMDetDetectorProvider in order to run the piped version of FaceDetailer, Facedetailer and other detailers like Detailer (SEGS) now require "guide_size_for", "noise_mask" and "force_inpaint" inputs. They did not require these before disabling the mmdet_skip.

Tried reinstalling (runnin uninstall.py and deleting all the files, then cloning the repo again) and making sure that mmdet_skip is enabled, these 3 inputs are still required.

Since it seems they are permanent requirements now, how do i provide these values? I've been going through the different WAS and Impact nodes but haven't been able to find the correct ones yet.

**Comment by mezter** [comment]
Same problem I am having.  Fresh install today and did the same as you.  I couldn't find any solution.

**Comment by ltdrdata** [comment]
Can you share your workflow file?

**Comment by ltdrdata** [comment]
NOTICE: V3.6 requires update ComfyUI to latest version.

**Comment by Fexnon** [comment]
Pulled the update and started up the ComfyUI server, did not fix the issue.

Shutdown the server, ran Impact uninstall.py and manually deleted the folder in custom_nodes.

Cloned the main repo again and ran install.py, started the server and placed down a new Facedetailer node. Did not fix the issue.

Here is the svg and png exports of the workflow, .json was not allowed.

![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/51008303/e58a495e-a67a-4fd6-9b23-b8b52467959d)

![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/51008303/838b4bd3-8323-40a9-aaf8-ac84915117ce)

**Comment by ltdrdata** [comment]
> Pulled the update and started up the ComfyUI server, did not fix the issue.
> 
> Shutdown the server, ran Impact uninstall.py and manually deleted the folder in custom_nodes.
> 
> Cloned the main repo again and ran install.py, started the server and placed down a new Facedetailer node. Did not fix the issue.
> 
> Here is the svg and png exports of the workflow, .json was not allowed.
> 
> ![workflow](https://user-images.githubusercontent.com/51008303/258012194-e58a495e-a67a-4fd6-9b23-b8b52467959d.png)
> 
> ![workflow](https://user-images.githubusercontent.com/51008303/258012142-838b4bd3-8323-40a9-aaf8-ac84915117ce.svg)

What version message are shown on your terminal when startup.
Like these...(ComfyUI Revision, ...)

![versions](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/837b2f22-63b7-4d3a-8fac-cb10851280ca)

**Comment by Fexnon** [comment]
Revision is not stated at all.

![2023-08-03 08_54_33-PowerShell 7 (x64)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/51008303/980712dd-fcef-4e51-9233-df8a8d6596df)

After that it starts mentioning total VRAM amount, xformers version and so on.

**Comment by ltdrdata** [comment]
> Revision is not stated at all.
> 
> ![2023-08-03 08_54_33-PowerShell 7 (x64)](https://user-images.githubusercontent.com/51008303/258013939-980712dd-fcef-4e51-9233-df8a8d6596df.png)
> 
> After that it starts mentioning total VRAM amount, xformers version and so on.

Maybe you don't use Manager. Then show me the messages on...

`git log` in ComfyUI dir.

**Comment by Fexnon** [comment]
I likely do not have Manager if it is an custom_node pack or similar. I dont recall installing it.

Here are the 9 most recent log entries.

![2023-08-03 09_00_14-MINGW64__f_git_repos_ComfyUI](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/51008303/a085fe38-6123-4451-ab66-835c3234f05d)

**Comment by ltdrdata** [comment]
> I likely do not have Manager if it is an custom_node pack or similar. I dont recall installing it.
> 
> Here are the 9 most recent log entries.
> 
> ![2023-08-03 09_00_14-MINGW64__f_git_repos_ComfyUI](https://user-images.githubusercontent.com/51008303/258014997-a085fe38-6123-4451-ab66-835c3234f05d.png)

Yeah that is old version. Maybe some modified files prevent updating.

Execute `git stash` and `git pull`

**Comment by mezter** [comment]
Updating ComfyUI-Manager fixed it for me, "guide_size_for" is now a widget as well as "noise_mask and force_inapint".

**Comment by Fexnon** [comment]
> Yeah that is old version. Maybe some modified files prevent updating.
> 
> Execute `git stash` and `git pull`

This seems to have fixed the issue, the inputs are gone.

Edit: Confimed that this fixed the issue. Generated an image with the piped version of FaceDetailer.

**Comment by ltdrdata** [comment]
> > Yeah that is old version. Maybe some modified files prevent updating.
> > Execute `git stash` and `git pull`
> 
> This seems to have fixed the issue, the inputs are gone.
> 
> Edit: Confimed that this fixed the issue. Generated an image with the piped version of FaceDetailer.

No, I had to investigate the cause as well since several people were reporting the same issue. Fortunately, the cause was quickly identified.

**Comment by KhSTM** [comment]
> > Yeah that is old version. Maybe some modified files prevent updating.
> > Execute `git stash` and `git pull`
> 
> This seems to have fixed the issue, the inputs are gone.
> 
> Edit: Confimed that this fixed the issue. Generated an image with the piped version of FaceDetailer.

Can you share your workflow ? I can't get the missing inputs eaven after updating ComfyUI-Manager & impactpack. 
I'm new to comfyui so maybe i'm doing something bad

**Comment by ltdrdata** [comment]
> > > Yeah that is old version. Maybe some modified files prevent updating.
> > > Execute `git stash` and `git pull`
> > 
> > 
> > This seems to have fixed the issue, the inputs are gone.
> > Edit: Confimed that this fixed the issue. Generated an image with the piped version of FaceDetailer.
> 
> Can you share your workflow ? I can't get the missing inputs eaven after updating ComfyUI-Manager & impactpack. I'm new to comfyui so maybe i'm doing something bad

There is a slight mistake above. You need to update `ComfyUI`, not `ComfyUI-Manager`.
So execute them in `ComfyUI` directory.

**Comment by KhSTM** [comment]
> 

Yeah, little mistake too i forgot to say that i have already updated Comfyui

**Comment by ltdrdata** [comment]
> > 
> 
> Yeah, little mistake too i forgot to say that i have already updated Comfyui

Show me the screenshot of `git log`.

**Comment by Fexnon** [comment]
> > > Yeah that is old version. Maybe some modified files prevent updating.
> > > Execute `git stash` and `git pull`
> > 
> > 
> > This seems to have fixed the issue, the inputs are gone.
> > Edit: Confimed that this fixed the issue. Generated an image with the piped version of FaceDetailer.
> 
> Can you share your workflow ? I can't get the missing inputs eaven after updating ComfyUI-Manager & impactpack. I'm new to comfyui so maybe i'm doing something bad

I shared it earlier in this issue thread as an image and svg

**Comment by KhSTM** [comment]
![Sans titre](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/125185169/0c73ffd8-6f2b-4582-b47c-5460dbc50c78)

**Comment by ltdrdata** [comment]
> ![Sans titre](https://user-images.githubusercontent.com/125185169/258031670-0c73ffd8-6f2b-4582-b47c-5460dbc50c78.png)

And in the current version, when you add a new FaceDetailer node, the "force_inpaint" appears as an input slot rather than a widget, right?

**Comment by KhSTM** [comment]
I made a fresh install of everything, and now it's working

**Comment by OurGift-GIT** [comment]
Hi! fresh install, and...
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/133535383/d75e875d-0e9b-4750-b3a6-7972f5ae9b73)

**Comment by mezter** [comment]
@OurGift-GIT 
Make sure everything is updated is all I can recommend, that is how I got my 'noise_mask' and 'force_inpaint' to be widgets again.

> 
> Yeah that is old version. Maybe some modified files prevent updating.
> 
> Execute `git stash` and `git pull`

This worked for me.

**Comment by OurGift-GIT** [comment]
> @OurGift-GIT 
> 
> Make sure everything is updated is all I can recommend, that is how I got my 'noise_mask' and 'force_inpaint' to be widgets again.
> 
> 
> 
> > 
> 
> > Yeah that is old version. Maybe some modified files prevent updating.
> 
> > 
> 
> > Execute `git stash` and `git pull`
> 
> 
> 
> This worked for me.
> 
> 
> 
> 

Download new portable comfy 30 min before and manager+impact too, still inputs :c

**Comment by OurGift-GIT** [comment]
@mezter `git pull` works for me, thank you!
