### ISSUE TITLE
When installing on a venv that has latest torch nightly, it uninstalls torch

### ISSUE THREAD

**Issue by boricuapab** [ltdrdata/ComfyUI-Impact-Pack#730]
I been using the torch nightly but just noticed it un-installs this one

torch-2.5.0.dev20240903+cu124.dist-info

I am able to fix it by re-installing it, but in the cli I see that it says

ultralytics-8.2.87.dist-info

Is not compatible with torch <2.4.0

But, I know there are speed issues with flux using torch 2.4.0, and I am testing flux lora training in comfy so I opted to use torch 2.5.0

**Comment by ltdrdata** [comment]
This is currently a limitation of the Windows version of ultralytics.
For now, if you're in a Windows environment, the only option is to downgrade to below 2.4.0.

https://github.com/ultralytics/ultralytics/blob/88102eb5085a668fff0171fdaa6297af65c2d010/pyproject.toml#L74
https://github.com/ultralytics/ultralytics/issues/15049

**Comment by ltdrdata** [comment]
For now, I've implemented a temporary measure by skipping version ultralytics==8.2.87. However, I cannot guarantee normal operation if using torch 2.4.0 or higher on Windows.
