### ISSUE TITLE
Repeat batch

### ISSUE THREAD

**Issue by robertvoy** [ltdrdata/ComfyUI-Impact-Pack#738]
Hello,

I want to repeat a batch of the same input image to give me more options to choose from.

When I do this, the output images are the same, like they are using the same seed?

What is the correct way of doing this?

![firefox_NHYTQ6kT1I](https://github.com/user-attachments/assets/9f5e4c90-ad87-4fe4-95b1-21963436b146)

**Comment by ltdrdata** [comment]
Your `Get_seed` is not linked at all with what comes out of Image Batch to Image List. You need to link it in such a way that the seed changes variably according to the list item.

![363426359-986cfde2-bf57-4eb1-b393-ef4d9bb4d0d7](https://github.com/user-attachments/assets/2093a6eb-bc8a-47da-9a88-2160184d5820)

**Comment by robertvoy** [comment]
That works, thank you.
