### ISSUE TITLE
Mask detailer worklow disappeared in image refiner #11

### ISSUE THREAD

**Issue by Rkkss** [ltdrdata/ComfyUI-Impact-Pack#74]
![Untitled](https://github.com/ltdrdata/ComfyUI-Workflow-Component/assets/127614350/4674ef46-ec7d-4a1f-bd48-ce73d53c6bf6)

this is latest commit 

Also when I git checkout 03755139113150ae26863a679aa36c3cdc8bd7a0.
It also doesn't work
` RuntimeError: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.`

**Comment by ltdrdata** [comment]
Now this is patched.
Update Workflow Component to V0.40.
