### ISSUE TITLE
is there a reason that SEGSPicker is an output node?

### ISSUE THREAD

**Issue by Robonau** [ltdrdata/ComfyUI-Impact-Pack#742]
with execution-inversion having been added recently, nodes that don't need to be outputs not being outputs is more important than ever 

my use case is a bit weird

im currently using the [SEGSPicker](https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/1c488eec11264db23821c864f1482a99ba9893d0/modules/impact/segs_nodes.py#L1416)  like so
```py
condition = # oldImage meets some condition

segs = detailer_segs_pipe(oldImage)
for i in len(segs): # using the execution-inversion-demo-comfyui for loop
    oneSeg = SEGSPicker(segs,i)
    newsegs = # do stuff with the oneSeg and output from the for loop
newImage = segsPaste(newsegs)

newNewImage = conditionalBranch(oldImage, newimage,condition)
```

the actual workflow is massive hence the psudocode explanation, but if u need one i should be able to make a simpler example displaying the issue

so with everything in the for loop being `output = False` it will only run the `detailer_segs_pipe` and the `for loop` if the `condition` is true

a more general list picker / item of list at index would also be awesome since i cant find any custom nodes to do that, but its not all that important, i can do most of what i want with switches

**Comment by ltdrdata** [comment]
Yeah. SEGSPicker should not be OUTPUT_NODE.
This is fixed.
