### ISSUE TITLE
About Switch Any...

### ISSUE THREAD

**Issue by K-O-N-B** [ltdrdata/ComfyUI-Impact-Pack#744]
![image](https://github.com/user-attachments/assets/c61d80cd-6db2-44ae-a31c-a435fae5bc61)

May I ask one more feature: auto add a number to the front

That will easiser to know which one I need to choose.

**Comment by ltdrdata** [comment]
Automatically modifying labels that users have edited seems inappropriate.
However, I am considering displaying something like an indicator.

**Comment by K-O-N-B** [comment]
When I have many input, that's very hard to find the right input number, so that I ask for this feature.
