### ISSUE TITLE
Detailer (SEGS/Pipe) takes ages to load with Flux

### ISSUE THREAD

**Issue by sahinincik** [ltdrdata/ComfyUI-Impact-Pack#745]
I'm trying to use Detailer with Flux, I've updated Impact Pack to the latest version. It looks like it's loading models again, it wait a long time before generation.

![image](https://github.com/user-attachments/assets/0ba78b7f-8947-47a2-8e58-538ac03eb76c)

![image](https://github.com/user-attachments/assets/5c486bd2-f895-49ec-80a0-08c345268d83)

**Comment by ltdrdata** [comment]
This is not an issue with the Impact Pack, but an issue with the core.

When performing a basic workflow example using `SamplerCustomAdvanced`, you can confirm that it occurs during the `SamplerCustomAdvanced` step. The Detailer is affected because it uses `SamplerCustomAdvanced`.

**Comment by seasnakes** [comment]
> This is not an issue with the Impact Pack, but an issue with the core.
> 
> When performing a basic workflow example using `SamplerCustomAdvanced`, you can confirm that it occurs during the `SamplerCustomAdvanced` step. The Detailer is affected because it uses `SamplerCustomAdvanced`.

Could you kindly provide an example detailer workflow for the Flux version? Thank you.🙏

**Comment by sahinincik** [comment]
any way around this?

**Comment by ltdrdata** [comment]
> > This is not an issue with the Impact Pack, but an issue with the core.
> > When performing a basic workflow example using `SamplerCustomAdvanced`, you can confirm that it occurs during the `SamplerCustomAdvanced` step. The Detailer is affected because it uses `SamplerCustomAdvanced`.
> 
> Could you kindly provide an example detailer workflow for the Flux version? Thank you.🙏

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/flux-detailer.png

Just use `Negative Cond Placeholer`. You can use it with Impact/Inspire samplers and Detailers.
