### ISSUE TITLE
Iterative Upscale (Latent/on Pixel Space)

### ISSUE THREAD

**Issue by xdblazes1** [ltdrdata/ComfyUI-Impact-Pack#746]
Hi,

Is it possible to use the Set Latent Noise Mask node with the Iterative Upscale node to upscale all but only sample the masked area?
![Screenshot 2024-09-18 045114](https://github.com/user-attachments/assets/cf2f3f72-3ee6-4005-bf11-be9f89d456aa)

currently when I add the mask the whole image gets sampled.

**Comment by ltdrdata** [comment]
This is fixed.
