### ISSUE TITLE
Image switching output duplicate problem

### ISSUE THREAD

**Issue by water110** [ltdrdata/ComfyUI-Impact-Pack#747]
![image](https://github.com/user-attachments/assets/f38fbf4d-6093-4eff-86e8-d3c462d9648b)
![image](https://github.com/user-attachments/assets/78ff9a7d-e00b-4779-8033-6d59fa6c1ec4)
![image](https://github.com/user-attachments/assets/b1d95165-472d-45f4-98fa-4622788c7254)
Always repeats multiple times when loading images, as shown above.I tried the node of another plug-in and a similar situation occurred. I wanted to confirm whether when selecting the input as an image, it meant that only a single image was output, but this is not the case. In addition, the folder path to load the picture list contains the single picture loaded above.

**Comment by ltdrdata** [comment]
Please provide the workflow with the translator turned off.

**Comment by water110** [comment]
![image](https://github.com/user-attachments/assets/bcf775f7-40a3-4ee5-8cd6-e7ffb704a9ed)
[Untitled_Flow2.json](https://github.com/user-attachments/files/17052239/Untitled_Flow2.json)
@ltdrdata

**Comment by ltdrdata** [comment]
You have a misunderstanding about List and Batch.

When handling images as a batch, you create them with the same resolution and process them by passing them as a single tensor data format. When handling them as a list, you process each image one by one in a repetitive manner.

In other words, when you `Load Image List From Dir`, if there are 3 images in that directory, the `CR Batch Process Switch` will execute 3 times.

**Comment by water110** [comment]
Thank you for your reply, I now know that I should go through the image list to image batch processing to achieve the effect I want. But I still have some doubts, if you have spare time, you can help me to answer. My understanding is like this, after the image list is converted to image batch, it is equivalent to a batch with multiple images, while a single image is equivalent to a batch containing only one image, I don't know if my understanding is correct or not. And what I am wondering is that when I use the image list to directly access the slot corresponding to the image batch, after selecting the input item as image, why the output item will be affected by the input item of the image batch and produce multiple images.

**Comment by ltdrdata** [comment]
The concept of "List" is to execute subsequent workflows individually for each item within the list.
