### ISSUE TITLE
 no_segm_Detector 

### ISSUE THREAD

**Issue by Kimthanh27** [ltdrdata/ComfyUI-Impact-Pack#752]
Even though I selected the correct model for segmentation (face_yolov8m-seg_60.pt), it still says no_segm_Detector. Why is that?

**Comment by ltdrdata** [comment]
Is the model file correctly located in the `models/ultralytics/segm` path?

**Comment by Kimthanh27** [comment]
**"I've updated ComfyUI and installed the node requirements. What else can I do?"**
![1](https://github.com/user-attachments/assets/9e866dc9-d3ce-4b79-a80d-ea3a46846ec4)

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by wangyuanfenglw** [comment]
Excuse me, 【UltralyticsDetectorProvider】 node model 【face_yolov8m.pt】 installed in which files directory

**Comment by ltdrdata** [comment]
> Excuse me, 【UltralyticsDetectorProvider】 node model 【face_yolov8m.pt】 installed in which files directory

`ComfyUI/models/ultralytics/bbox` is the correct path.
You can download it via ComfyUI-Manager.
