### ISSUE TITLE
Face detailer Looping without giving image

### ISSUE THREAD

**Issue by Creative-comfyUI** [ltdrdata/ComfyUI-Impact-Pack#756]
Hello, 

As usual I connect an image to facedetailer. Facedetailer star rendering not once but several times without stopping to give image.  I have to stop the process because it never ends.  

Thanks

**Comment by ltdrdata** [comment]
What is your workflow?

**Comment by Creative-comfyUI** [comment]
It seems it works well with one image but not with batch image (more than one) The result seems strange. Before their was much better results. Look at the hands 
![workflow-13](https://github.com/user-attachments/assets/5a5457d5-30d4-4c1e-8b9e-627604f3cb2d)
![Screenshot 2024-09-26 at 12 08 14 AM](https://github.com/user-attachments/assets/3a9395f5-0431-402b-ac62-ed7c0ca32f19)

**Comment by ltdrdata** [comment]
> It seems it works well with one image but not with batch image (more than one) The result seems strange. Before their was much better results. Look at the hands ![workflow-13](https://private-user-images.githubusercontent.com/166729777/370980022-5a5457d5-30d4-4c1e-8b9e-627604f3cb2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDU0NTgsIm5iZiI6MTcyNzQ0NTE1OCwicGF0aCI6Ii8xNjY3Mjk3NzcvMzcwOTgwMDIyLTVhNTQ1N2Q1LTMwZDQtNGMxZS04YjllLTYyNzYwNGYzY2IyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMzUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOThmMmFmMTc3OTE4Y2Q0M2E5ZDVmNjA1NjMzN2IxODg1NGZkZDcxZGRjN2U4MDdkZWQxOTQxYWNiZWIzZDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oD-Z2SIyJ257sfzyNaQ_y4mmALXSwHKfGK6wC3EBr2w) ![Screenshot 2024-09-26 at 12 08 14 AM](https://private-user-images.githubusercontent.com/166729777/370981044-3a9395f5-0431-402b-ac62-ed7c0ca32f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDU0NTgsIm5iZiI6MTcyNzQ0NTE1OCwicGF0aCI6Ii8xNjY3Mjk3NzcvMzcwOTgxMDQ0LTNhOTM5NWY1LTA0MzEtNDAyYi1hYzYyLWVkN2MwY2EzMmYxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxMzUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2QxZjliOGMyMTJmYTkyNWNiZTY2ODNhZTE2YmE1ZWFiY2U0ZDYxZmMyZmE0YTU0M2YxNGVlMzI3ZWM1YjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mjql5bsBRe2BqeXNXiKEsvW3xjpAaBLK3xdfJE4Wiss)

It's not an issue with batch images. The principle of the detailer is to crop and enlarge a part of the image, perform img2img on it, then reduce it and paste it back into the original image.
The prompt applied to the detailer should be appropriately applied from this perspective.

**Comment by InspectaGadget** [comment]
Hi ! Would to expand on this (initial) issue. I tried to detail on a picture with several faces, applying InstantID on SEGS. In my example there are seven faces, they all refine without problems, but when reaching the last face the detailer don't generate output and comeback to the first one face, continuing to infinity. The cycle is 1 only.

But (and just thinking of that as I write this message) I didn't put a SEGS paste after the detailer. Could it be the reason ?
Otherwise, in filtered SEGS I set a count of height, but skip the first one (start =1). Is that this setting that could messed up things in detailer ?

If I refine an only face, there is not any problems.

Sorry by advance, I will be able to link WF only tomorrow.
Thanks for your awesome job on this nodes.

**Comment by InspectaGadget** [comment]
Here is the part of workflow where the issue happened.
![workflow(2)](https://github.com/user-attachments/assets/5e176ad4-0a03-41ca-b904-8d9875a9d137)

PS : And it's cause of this clean GPU i put after the detailer, that maybe erase previous job each time it finish to detail one face, getting it impossible to detail and paste all the faces together -> You could say i'm dumb

**Comment by ltdrdata** [comment]
The output of `SEGPreview `is an image list. This means that the subsequent workflow will be repeated as many times as there are items in SEGS.

**Comment by InspectaGadget** [comment]
Do you mean it's looping cause SEGPreview is linked to the face keypoints ? 

I understand that if SEGS isolate 7 faces, there will be 7 passes of detailer. But there i reached the pass # 32 before I quit.

That should decide the number of passes isn't it the number of SEGS detected from Simple detector or SEGS filtered (wich is the one connected to detailer) ?

**Comment by ltdrdata** [comment]
> Do you mean it's looping cause SEGPreview is linked to the face keypoints ?
> 
> I understand that if SEGS isolate 7 faces, there will be 7 passes of detailer. But there i reached the pass # 32 before I quit.
> 
> That should decide the number of passes isn't it the number of SEGS detected from Simple detector or SEGS filtered (wich is the one connected to detailer) ?

The basic_pipe passed to the detailer is connected to the output of SEGSPreview.
This means that the detailer itself repeats 7 times. Additionally, since the SEGS passed to the detailer contains 7 items, it repeats 7 times within the detailer each time, resulting in a total of 49 repetitions.

**Comment by InspectaGadget** [comment]
Couldn't manage to figure this keypoints was multiplying numbers of repetitions when going in pipe.
Thanks for your explanations and for your patience !
