### ISSUE TITLE
Regarding the dependency issue that is preventing the plugin from loading, please help, I can't really fix it!

### ISSUE THREAD

**Issue by VAVAVAAA** [ltdrdata/ComfyUI-Impact-Pack#757]
![image](https://github.com/user-attachments/assets/c978b080-3413-40af-b61f-6f480c85d5d8)
My environment is torch2.4.1+cu121

**Comment by nofile** [comment]
try below code:

cd custom_nodes/ComfyUI-Impact-Pack
git clone https://github.com/ltdrdata/ComfyUI-Impact-Subpack impact_subpack

**Comment by ltdrdata** [comment]
execute this
```
ls /home/xlab-app-center/custom_nodes/ComfyUI-Impact-Pack
ls /home/xlab-app-center/custom_nodes/ComfyUI-Impact-Pack/impact_subpack
```

What is dispayed?

**Comment by VAVAVAAA** [comment]
> execute this
> 
> ```
> ls /home/xlab-app-center/custom_nodes/ComfyUI-Impact-Pack
> ls /home/xlab-app-center/custom_nodes/ComfyUI-Impact-Pack/impact_subpack
> ```
> 
> What is dispayed?
It gives an error and again won't install
FileNotFoundError: [Errno 2] No such file or directory: '/home/xlab-app-center/custom_nodes/ComfyUI-Impact-Subpack/__init__.py'
Cannot import /home/xlab-app-center/custom_nodes/ComfyUI-Impact-Subpack module for custom nodes: [Errno 2] No such file or directory: '/home/xlab-app-center/custom_nodes/ComfyUI-Impact-Subpack/__init__.py'

**Comment by ltdrdata** [comment]
You have installed it to invalid directory.

First, remove the Impact-Subpack Dir.

Wasn't it installed through the Manager?

If possible, it is recommended to install the Impact Pack through the Manager. 

In case of manual installation, the `git clone` should be done in the `ComfyUI-Impact-Pack` path, not in `custom_nodes`, and it should be cloned as `impact_subpack`.
