### ISSUE TITLE
Impact-Pack won't show up

### ISSUE THREAD

**Issue by MaximillionGit** [ltdrdata/ComfyUI-Impact-Pack#76]
This is my original comment on youtube titled "ComfyUI Impact Pack - Update(V3.6): ImpactWildcardProcessor + PrimitiveNode"

I download the pack from the manager, and it tells me that it has been downloaded, I restart Comfy as instructed, but for some reason, it didn't show up. Any other custom nodes I downloaded from the manager are there but this one didn't. Are there any extra steps that I need to perform beyond installing it from the manager?

I attach my terminal log here
[comfyUI_logs.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12247800/comfyUI_logs.txt)

**Comment by ltdrdata** [comment]
> This is my original comment on youtube titled "ComfyUI Impact Pack - Update(V3.6): ImpactWildcardProcessor + PrimitiveNode"
> 
> I download the pack from the manager, and it tells me that it has been downloaded, I restart Comfy as instructed, but for some reason, it didn't show up. Any other custom nodes I downloaded from the manager are there but this one didn't. Are there any extra steps that I need to perform beyond installing it from the manager?
> 
> I attach my terminal log here [comfyUI_logs.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12247800/comfyUI_logs.txt)

Update to latest version both `ComfyUI` and `Impact Pack` then it will be fixed.

**Comment by MaximillionGit** [comment]
Yup. Can confirm. It's working after updating the latest Impact Pack. Thank you
