### ISSUE TITLE
Feature Requests: `list to batch` and `batch to list` for latent

### ISSUE THREAD

**Issue by mijuku233** [ltdrdata/ComfyUI-Impact-Pack#762]
I need this feature, and I originally planned to complete it myself, but encountered an error.
If you have time, please implement this feature, thank you!

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/96b73245-280c-4fba-843e-0c4736f25f9f)

This node can be used to convert to a latent list with a specified batch size. Alternatively, it can convert a latent batch list into a single latent batch.
