### ISSUE TITLE
Request: Add "Apply Controlnet with VAE" to "ControlNetApply (SEGS)"

### ISSUE THREAD

**Issue by oliverban** [ltdrdata/ComfyUI-Impact-Pack#764]
As the title says, to be able to use the detailer with Controlnets and FLUX we need the new "Apply Controlnet with VAE" node to make it work. Current "ControlNetApply (SEGS)" gives error to add the VAE! :) Should be pretty easy!

Thanks in advance!

**Comment by ltdrdata** [comment]
Patched.

**Comment by oliverban** [comment]
> Patched.

Amazing, thanks so much! <3
