### ISSUE TITLE
Variables in Wildcards (Impact Wildcard Processor)

### ISSUE THREAD

**Issue by mofoni** [ltdrdata/ComfyUI-Impact-Pack#766]
Hi, 

i have been experimenting with wildcards and the `impactwildcardprocessor` for some time now and tried to use the variable-functionality of [sd_dynamic_prompts](https://github.com/adieyal/sd-dynamic-prompts/tree/main) as shown in its [syntax documentation](https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md#variables). 

Until i tried variables everything worked like in the linked documentaton. 
As you havent mentioned Variable-compatibility in your own documentation ([link](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md)), am i right to say that variables wont work with your nodes? Or did i do something wrong?

here is a prompt that shows this functionality:

`${colors=!{red|blue|green} photo, man, wearing ${colors} hat and ${colors} shoes`

should make something like 

`photo, man, wearing red hat and red shoes`

impactwildcardprocessor gives the following output:

`${colors=!{red|blue|green} photo, man, wearing ${colors} hat and ${colors} shoes` 

![image](https://github.com/user-attachments/assets/e7efd9f3-cf42-4d95-9527-d233ed5c23ba)

Would it be possible to implement this?

**Comment by ltdrdata** [comment]
Impact wildcard doesn't support variable feature.
Even if I implement variable functionality, I have no intention of using the same syntactical method as the grammar used in A1111 extensions.

**Comment by mofoni** [comment]
> Impact wildcard doesn't support variable feature. Even if I implement the variable functionality, I have no intention of using the method used in the A1111 extension.

Good to know then. Thanks for the quick reply 👍

Do you think something similar would be worthwile to implement?

**Comment by ltdrdata** [comment]
> > Impact wildcard doesn't support variable feature. Even if I implement the variable functionality, I have no intention of using the method used in the A1111 extension.
> 
> Good to know then. Thanks for the quick reply 👍
> 
> Do you think something similar would be worthwile to implement?

I think it would be worthwhile.
I just think the wildcard syntax is too complicated for convenient use.
Complex prompts using wildcards are almost at the level of obfuscation.

**Comment by mofoni** [comment]
I just tried a workaround:

what if i could use different custom nodes (like find-and-replace) nodes and build my prompt _before_ giving it to impactwildcardprocessor, like so:

![image](https://github.com/user-attachments/assets/6f6e2416-dbc8-4e60-b686-500fcb40ac82)

Turns out impactwildcardprocessor doesnt like string-inputs from different nodes - just like you mentioned in your docs.

Is this something that can be changed since Execution Model Inversion is now a thing? (Just food for thought)

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/71b70d89-a32d-4112-8b56-0161cb981a28)
Use `fixed` mode and `populated_text`
