### ISSUE TITLE
An installation problem, how to solve it

### ISSUE THREAD

**Issue by LiuGe126** [ltdrdata/ComfyUI-Impact-Pack#768]
### Loading: ComfyUI-Impact-Pack (V7.9)
[Impact Pack] Failed to import due to several dependencies are missing!!!!
Traceback (most recent call last):
  File "D:\LIUGEGE\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\LIUGEGE\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 53, in <module>
    raise e
  File "D:\LIUGEGE\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 31, in <module>
    import impact.subpack_nodes  # This import must be done before cv2.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'impact.subpack_nodes'

Cannot import D:\LIUGEGE\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'impact.subpack_nodes'

**Comment by ltdrdata** [comment]
Please attach the `comfyui.log` file that was generated during the process of uninstalling and reinstalling the Impact Pack in ComfyUI-Manager, followed by restarting ComfyUI

**Comment by LiuGe126** [comment]
> Please attach the `comfyui.log` file that was generated during the process of uninstalling and reinstalling the Impact Pack in ComfyUI-Manager, followed by restarting ComfyUI请附加在ComfyUI-Manager中卸载和重新安装Impact Pack过程中生成的文件，然后重新启动ComfyUI

[comfyui.log](https://github.com/user-attachments/files/17291331/comfyui.log)
thanks

**Comment by ltdrdata** [comment]
Is this the correct log after reinstalling the Impact Pack and restarting ComfyUI?

**Comment by LiuGe126** [comment]
> Is this the correct log after reinstalling the Impact Pack and restarting ComfyUI?

I can install it normally after uninstalling and reinstalling it again, but I have uninstalled and reinstalled it for many times before, but it has no effect. Thank you for your reply.

**Comment by Ryuukeisyou** [comment]
I try a clean install and it seems that the install code to git clone the subpack repo is not run before `__init__.py`

**Comment by ltdrdata** [comment]
> I try a clean install and it seems that the install code to git clone the subpack repo is not run before `__init__.py`

Aren't you installing through ComfyUI-Manager?
This installation process is automatically performed when installing through ComfyUI-Manager.

**Comment by Ryuukeisyou** [comment]
> > I try a clean install and it seems that the install code to git clone the subpack repo is not run before `__init__.py`
> 
> Aren't you installing through ComfyUI-Manager? This installation process is automatically performed when installing through ComfyUI-Manager.

not through manager, basically it's not a problem. just need to run install when git cloned mannually.

**Comment by drmbt** [comment]
is there any way to include this in normal __init__.py instead of only when installed through comfy manager? impact pack has been broken for me through a dynamically built docker container situation I've got going on because of this, everything else I'm running works great when procedurally git cloned

**Comment by ltdrdata** [comment]
> is there any way to include this in normal **init**.py instead of only when installed through comfy manager? impact pack has been broken for me through a dynamically built docker container situation I've got going on because of this, everything else I'm running works great when procedurally git cloned

I'm planning to change the subpack structure anyway.

**Comment by ltdrdata** [comment]
> > > I try a clean install and it seems that the install code to git clone the subpack repo is not run before `__init__.py`
> > 
> > 
> > Aren't you installing through ComfyUI-Manager? This installation process is automatically performed when installing through ComfyUI-Manager.
> 
> not through manager, basically it's not a problem. just need to run install when git cloned mannually.

`install-manual.py` is added.
