### ISSUE TITLE
facedetailer: required input is missing: seed

### ISSUE THREAD

**Issue by Gh20221205** [ltdrdata/ComfyUI-Impact-Pack#769]
I got this error since a recent update. Now facedetailer can no longer run. I think it tells me that I need to connect a seed to it, but there is no  input for seed on the node.

**Comment by ltdrdata** [comment]
Show me the your workflow.

**Comment by Gh20221205** [comment]
> Show me the your workflow.
Here's the workflow I used.
https://civitai.com/models/623583/flux-with-face-and-hand-detailers-2-upscalers

**Comment by Nem-z** [comment]
I have a similar issue. I converted the seed into an input in one of my workflow for the FaceDetailer node. It worked until recently. Today when I load the workflow the input is named "scheduler_func_opt" instead of "seed".
![image](https://github.com/user-attachments/assets/7aba31c0-e489-4459-9130-7fb389328282)
Converting seed to a widget and back to an input solve the issue until reloading the workflow. 
The error message is the following:
![image](https://github.com/user-attachments/assets/1e3f9996-7c95-4ee0-b4fb-14fcfce40ba6)

**EDIT:** It worked after recreating the node. Thanks for the help @ltdrdata

**Comment by ltdrdata** [comment]
> I have a similar issue. I converted the seed into an input in one of my workflow for the FaceDetailer node. It worked until recently. Today when I load the workflow the input is named "scheduler_func_opt" instead of "seed". ![image](https://private-user-images.githubusercontent.com/63961359/374964164-7aba31c0-e489-4459-9130-7fb389328282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzI3OTgsIm5iZiI6MTcyODUzMjQ5OCwicGF0aCI6Ii82Mzk2MTM1OS8zNzQ5NjQxNjQtN2FiYTMxYzAtZTQ4OS00NDU5LTkxMzAtN2ZiMzg5MzI4MjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMmUxZmU2MmUxM2RmOGE2NjA0M2M0OGQ3ZmNiZGEwNjQ4YmZiOWI1ZDZlYzM2OTE4ODA3ZDdhYzk0OWVjMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aWrVtCTllAyMeeQ0xvkVZ6uq1aqQznsjITQ3yZ35JBc) Converting seed to a widget and back to an input solve the issue until reloading the workflow. The error message is the following: ![image](https://private-user-images.githubusercontent.com/63961359/375062444-1e3f9996-7c95-4ee0-b4fb-14fcfce40ba6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzI3OTgsIm5iZiI6MTcyODUzMjQ5OCwicGF0aCI6Ii82Mzk2MTM1OS8zNzUwNjI0NDQtMWUzZjk5OTYtN2M5NS00ZWUwLWI0ZmItMTRmY2ZjZTQwYmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzNTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNzUwNTI0NzA1NTcwY2ViM2E1YjcwNTZiZmM4N2NkMTQ5MzE2ODI5YmNlMzEzZTU2NThmOWEzODA5ODEzZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.thWuBzhdexXbWpoWZZx0BQ1PHy3epyED9EFpY0aa92Q)

Recreate the node. This issue can occur when loading nodes created with a very old version of Impact Pack using the latest version of Impact Pack.

**Comment by ClothingAI** [comment]
Got same error: 
[Required input is missing seed.json](https://github.com/user-attachments/files/17532827/Required.input.is.missing.seed.json)

Reloaded a new ksampler, what else can I do @ltdrdata ?

logs:

```
got prompt
Failed to validate prompt for output 130:
* FaceDetailer 127:
  - Required input is missing: seed
Output will be ignored
```

**Comment by ltdrdata** [comment]
What I mentioned was **recreate**, not **reload**.
The node was already saved in the workflow in a broken state.
The node needs to be removed and added again.

**Comment by ClothingAI** [comment]
> What I mentioned was **recreate**, not **reload**. The node was already saved in the workflow in a broken state. The node needs to be removed and added again.

I am pretty sure I made a new one (I dont think I did a copy paste from the last supposedly broken one) and what I meant by "reloaded" was loaded one from the menu of nodes (created one)

I could try again to be 100% but I am already 90% sure

**Comment by ltdrdata** [comment]
> > What I mentioned was **recreate**, not **reload**. The node was already saved in the workflow in a broken state. The node needs to be removed and added again.
> 
> I am pretty sure I made a new one (I dont think I did a copy paste from the last supposedly broken one) and what I meant by "reloaded" was loaded one from the menu of nodes (created one)
> 
> I could try again to be 100% but I am already 90% sure

If the issue can be reproduced, submit it to the front repo along with detailed reproduction steps.
To rule out the possibility of interference from other custom nodes, please reproduce the issue using a fresh ComfyUI installation with only Impact Pack installed.

When a workflow file is saved with `scheduler_func_opt` set as a `seed` widget, this indicates a case where the workflow has become broken.

![image](https://github.com/user-attachments/assets/22a7d38d-0cad-4a0c-b641-d450b0fa0309)
