### ISSUE TITLE
FaceDetailer connection changes.

### ISSUE THREAD

**Issue by Neytiri7** [ltdrdata/ComfyUI-Impact-Pack#770]
![Screenshot 2024-10-08 at 18 20 38](https://github.com/user-attachments/assets/fcd0e6ed-f90c-4fd8-a4ae-4fa228cd005b)

I set it by inputting step,
If you restart a refresh, rerun, etc., it will change to the scheduler_func_opt item.

Even if you save and load a workflow, it will be displayed as scheduler_func_opt.

If you release the input after disconnecting, and then re-input and connect, it will work normally.

![Screenshot 2024-10-08 at 18 20 09](https://github.com/user-attachments/assets/a1d8909a-23e7-4b6c-8d1f-a65f72bce9c5)

**Comment by ltdrdata** [comment]
It seems that your workflow is outdated workflow.

**Comment by Neytiri7** [comment]
We have newly registered and resolved the corresponding node.
Thank you.
