### ISSUE TITLE
ImpactWildcardProcessor - broken instance is affecting later ones

### ISSUE THREAD

**Issue by hogagit** [ltdrdata/ComfyUI-Impact-Pack#772]
When one instance of a node is broken because inputs are not supplied (after converting for example "mode" to input), instances added later are not populating (even if they are copied from older instances). Instances added before are populating.

Tested with latest Impact Pack (just updated) and ComfyUI tags v0.2.2 and v0.1.3.

Steps:
* Create empty workflow with two IWP nodes. Let's agree to call them "U" (unaffected) and "B" (broken).
* type anything in "U" top (source) input field (might be just "a").
* "U" should be in "Populate" mode
* bottom (result) window of "U" should be empty (or just with starter placeholder text)
* In "B" instance, convert mode to input and don't connect anything
* now create third instance of the IWP node, let's call it "A" (affected) (this might be even copy-paste of "U")
* make the same setup in "A" as for "U"
* run workflow
* "U" node should just copy value from top to bottom
* **"A" node didn't populate the bottom field**
* now either connect correct input to "B" (double click on "mode" input dot) or just convert again input to widget
* run workflow again
* now node "A" is populating correctly. Nodes are not connected at all.

**Comment by ltdrdata** [comment]
This is a current structural limitation of ComfyUI workflow format. 
Fundamentally, because the workflow's values are stored by order, and the order is interpreted when custom nodes are imported, once it gets out of sync, it becomes impossible to recover.

This issue has been recognized for a long time already.
