### ISSUE TITLE
Mediapipe face mesh - GL slowdowns

### ISSUE THREAD

**Issue by yuvraj108c** [ltdrdata/ComfyUI-Impact-Pack#776]
Getting massive slowdowns when using mediapipe face mesh, here are the logs

I0000 00:00:1728725496.959467    1337 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1728725497.021446   99212 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.90.07), renderer: NVIDIA H100 PCIe/PCIe/SSE2
W0000 00:00:1728725497.023113   99161 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1728725497.034552   99188 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1728725497.100004    1337 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1728725497.167327   99266 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.90.07), renderer: NVIDIA H100 PCIe/PCIe/SSE2
W0000 00:00:1728725497.169183   99227 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1728725497.179279   99214 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
I0000 00:00:1728725497.252184    1337 gl_context_egl.cc:85] Successfully initialized EGL. Major : 1 Minor: 5
I0000 00:00:1728725497.307476   99320 gl_context.cc:357] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 550.90.07), renderer: NVIDIA

**Comment by ltdrdata** [comment]
The facemesh feature operates through the nodes of comfyui_controlnet_aux.
Check the MediaPipe Face Mesh node in comfyui_controlnet_aux.

https://github.com/Fannovel16/comfyui_controlnet_aux
