### ISSUE TITLE
FaceDetailer error: (-5:Bad argument) in function 'resize'

### ISSUE THREAD

**Issue by sebastian-gott** [ltdrdata/ComfyUI-Impact-Pack#777]
I have previously used FaceDetailer fine, but after not using ComfyUI for a while. I am getting some sort of size conflict error. With this error:

`
# ComfyUI Error Report
## Error Details
- **Node Type:** FaceDetailer
- **Exception Type:** cv2.error
- **Exception Message:** OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
`

# How to replicate 
1. Clone ComfyUI and go through the Nvidia install steps.
2. Install ComfyUI-manager [ComfyUI-Manger repo](https://github.com/ltdrdata/ComfyUI-Manager)
3. Download attached workflow
4. Load workflow and install missing custom nodes with ComfyUI Manager
5. Run workflow

Any suggestions for why this issue occurs would be appreciated. I assume this is the right repo the create the issue since FaceDetailer is in the impact-pack :)

[SimplePonyXL_GitHub.json](https://github.com/user-attachments/files/17350694/SimplePonyXL_GitHub.json)

**Comment by ltdrdata** [comment]
update all your installed opencv version.

**Comment by sebastian-gott** [comment]
Thanks this seems to have solved the issue!
