### ISSUE TITLE
Error on FaceDetailer node

### ISSUE THREAD

**Issue by Davoosie** [ltdrdata/ComfyUI-Impact-Pack#778]
Im having an issue where when the FaceDetailer node is fed from a seed generator the node errors out. The workflow is here: 
https://comfyworkflows.com/workflows/d7ff9a42-6600-4bb6-9b2b-1586b5c77e11

<img width="429" alt="error" src="https://github.com/user-attachments/assets/dc1adf20-9482-44f6-bdeb-cfe8ce3d4896">

I cant seem to get around this issue, It was working yesterday, but today after an update its now broken. I'm not sure if the update broke it or it's another issue.

**Comment by ltdrdata** [comment]
That workflow is broken. Please recreate that node.

![image](https://github.com/user-attachments/assets/a11f0d45-791d-44aa-b9bd-5c80768bb192)

https://github.com/Comfy-Org/ComfyUI_frontend/issues/1257
