### ISSUE TITLE
ImpactWildcardProcessor doesn't work with wildcard_text as input

### ISSUE THREAD

**Issue by bvajk** [ltdrdata/ComfyUI-Impact-Pack#779]
Issue: I want to input text from another node to ImpactWildcardProcessor, but it doesn't do anything with it.
Steps to reproduce: create a ImpactWildcardProcessor node, convert wildcard_text into input, route a string into it
Effect: ImpactWildcardProcessor stops working completely

Am I doing something wrong?

**Comment by ltdrdata** [comment]
If you want to use an input instead of a widget, use `populated_text` and change the mode to `fixed`.

**Comment by bvajk** [comment]
Thank you
