### ISSUE TITLE
Detailer + Flux

### ISSUE THREAD

**Issue by robertvoy** [ltdrdata/ComfyUI-Impact-Pack#780]
Hello,

![image](https://github.com/user-attachments/assets/2d072729-11ae-4437-8135-3888e3d34b12)

Do we need the Model Sampling Flux when using SEGs detailer? If so, we need to set the size and width for each SEG, correct?

**Comment by ltdrdata** [comment]
Model Sampling Flux is for specialized use. If you don't understand the function of the Model Sampling Flux node, you don't need it.

If you're asking about how to use FLUX in SEGS Detailer, refer to the following:
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/flux-detailer.png

Just you need `Negative Cond Placeholder` for negative conditioning.

**Comment by robertvoy** [comment]
When using Flux with the detailer is the CFG value acting as guidance? I can see you have it set to 3.5 in the screenshot.

**Comment by ltdrdata** [comment]
> When using Flux with the detailer is the CFG value acting as guidance? I can see you have it set to 3.5 in the screenshot.

Using Negative Cond `Placeholder` causes it to operate with `Basic Guidance` instead of `CFG Guidance`.
This method can be applied not only to Detailer but also to all samplers in the Impact/Inspire Pack.
