### ISSUE TITLE
Request foot Adetailed

### ISSUE THREAD

**Issue by scavru** [ltdrdata/ComfyUI-Impact-Pack#783]
add a nodes similar to facedatailer and handsdatailer for this model https://civitai.com/models/257904/adetailer-footyolov8xpt

**Comment by ltdrdata** [comment]
You don't need any special node for them.
UltralyticsDetectorProvider is universal node.
![image](https://github.com/user-attachments/assets/3a2e1241-ce17-48e5-9197-ac41d78d9001)

Just put your bbox model to `models/ultralytics/bbox` and segm model to `models/ultralytics/segm`.
