### ISSUE TITLE
Selection weight syntax working?

### ISSUE THREAD

**Issue by itom0717** [ltdrdata/ComfyUI-Impact-Pack#787]
Has selection weight syntax stopped working?

This works
   1girl ,{ red | black | blue } color hair

This doesn't work
   1girl ,{ 5::red | black | blue } color hair
   
The following warning message appears:
   [WARN] ComfyUI-Impact-Pack: Error on prompt - several features will not work.

**Comment by ltdrdata** [comment]
Revert to Impact Pack version to 7.10.3.
If it wlll work that is a issue of https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/790

I'll patch it.

**Comment by ltdrdata** [comment]
Update and try again.

**Comment by itom0717** [comment]
It works now with the latest version. 
Thank you
