### ISSUE TITLE
billions of wildcards "Error on prompt - several features will not work. 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by tazztone** [ltdrdata/ComfyUI-Impact-Pack#788]
Hi
 i tried to use the wildcards: https://civitai.com/models/138970?modelVersionId=968099 with __ Bo/constructions/random-regular __ 
and getting errors:

```
got prompt
[WARN] ComfyUI-Impact-Pack: Error on prompt - several features will not work.
'NoneType' object is not iterable
Prompt executed in 0.00 seconds
```
author of the wildcards said:
![image](https://github.com/user-attachments/assets/7fd7a07e-015d-49ac-9583-e101bb56defe)

not sure if there is some issue with the yaml or at my end or if the node needs updating. 
thank you

**Comment by EnragedAntelope** [comment]
Confirming I experience the same issue.

**Comment by ao899** [comment]
dynamic prompts error

**Comment by ltdrdata** [comment]
I'll check it.

**Comment by tazztone** [comment]
thanks. wildcards author said it's probably from the "`{1-3&&` and similar parts". hth

**Comment by ltdrdata** [comment]
This is fixed.
