### ISSUE TITLE
Feature Request: Recognize # as a comment (skip line) with Impact Wildcards

### ISSUE THREAD

**Issue by EnragedAntelope** [ltdrdata/ComfyUI-Impact-Pack#789]
Hi,
Lately I've seen a decent amount of wildcards include credits or instructions etc. with # at the beginning of a line. Impact Wildcard Processor includes these lines when referencing the wildcard, but should not. Can this be updated to correctly recognize # as meaning a comment only / skip the line?

Examples I've seen, so you can spot any relevant patterns:

```
#v1 by CWT - compiled from the list found on Wikipedia

# Cyberdelia Wildcards - Populair gameconsoles #

# Originally sourced from Clements Checklist v2022

# Remove or Set a # in front of a line to Activate or Deactivate the Option
# Simple add your Own Wildcards just in a new Line 
#

```

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/30d00cac-a5a4-4824-b4e6-8594eb8f5ac1)

There is no issue about comment.

**Comment by ltdrdata** [comment]
Revert to Impact Pack version to 7.10.3.
If it wlll work that is a issue of https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/790

I'll patch it.

**Comment by ltdrdata** [comment]
Update and try again.

**Comment by EnragedAntelope** [comment]
I tried again with Vision Wildcards, I unfortunately still see # insertions:
![image](https://github.com/user-attachments/assets/c489dbc3-c667-45ba-b40f-71d062b7a157)

Vision wildcards are here:
https://civitai.com/models/793366/simple-wildcards-vision-outfits
https://civitai.com/models/823376/simple-wildcards-vision-background

**Comment by ltdrdata** [comment]
This is fixed.
