### ISSUE TITLE
Different Face Detectors

### ISSUE THREAD

**Issue by digitaljohn** [ltdrdata/ComfyUI-Impact-Pack#79]
This plugin is bundled with an anime face detector, is there a different model we can use to detect photorealistic faces better? The anime one is very unreliable in this case.

**Comment by ltdrdata** [comment]
> This plugin is bundled with an anime face detector, is there a different model we can use to detect photorealistic faces better? The anime one is very unreliable in this case.

Have you tried UlralyticsDetectorProvider?
The detector supports various face detection including realistic person.

**Comment by Ferniclestix** [comment]
thanks for this, been trying to build a tutorial and was close to not including impact pack at all due to it not detecting faces with mmdetector.

**Comment by digitaljohn** [comment]
Amazing @ltdrdata this works really well! Thank you.
