### ISSUE TITLE
Get a particular mask from mask list

### ISSUE THREAD

**Issue by Kelvxxx** [ltdrdata/ComfyUI-Impact-Pack#80]
Hi, is there a way to get a particular mask from a list of mask after using 'Masks to Mask List'? Such as if I only want the 2nd mask out of the list? Thanks

**Comment by ltdrdata** [comment]
I will implement it.

**Comment by Kelvxxx** [comment]
That'll be awesome, appreciate your work!

**Comment by ltdrdata** [comment]
> That'll be awesome, appreciate your work!

https://www.youtube.com/watch?v=9ih35D2exMU

I just updated this feature

**Comment by Kelvxxx** [comment]
> > That'll be awesome, appreciate your work!
> 
> https://www.youtube.com/watch?v=9ih35D2exMU
> 
> I just updated this feature

Hi, that was so fast! I had a play with it, the problem I'm having is that since it's returning SEGS instead of the masks themselves, sometimes the SEG might include a part of another mask, which might change an area that I don't want changed. Is there a way to solve this with the current implementation?

**Comment by Kelvxxx** [comment]
I'm basically trying to change only 1 person at a time with images that have multiple people, so that I can apply different prompts to different people or objects

**Comment by ltdrdata** [comment]
> I'm basically trying to change only 1 person at a time with images that have multiple people, so that I can apply different prompts to different people or objects

When you perform MaskToSEGS, all disconnected masks are separated into individual SEGS. Even if you perform transformations between masks, they will ultimately be separated using the same mechanism as SEGS, so there's no difference. However, if you intend to utilize it in a way other than detailing, I could create something like `SEGSToMaskList`.

**Comment by Kelvxxx** [comment]
I'm trying to use it for inpainting, I'm having a bit of trouble because it's inpainting the entire seg (which might include parts of different masks) instead of a mask

**Comment by ltdrdata** [comment]
> I'm trying to use it for inpainting, I'm having a bit of trouble because it's inpainting the entire seg (which might include parts of different masks) instead of a mask

I thought that I have fixed that long time ago. I need to check again.

**Comment by Kelvxxx** [comment]
Maybe I'm doing it wrong, but I haven't found a good way to achieve that

**Comment by ltdrdata** [comment]
![mask](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/8bef0d3a-c9f8-4f54-8785-617c5f7222f3)

Now, that bug is fixed.
Moreover I added `SEGSToMaskList` node, also.
