### ISSUE TITLE
Regarding the issue of the graphics card not running at full load after loading the impact node on the Ubuntu system.

### ISSUE THREAD

**Issue by siji444** [ltdrdata/ComfyUI-Impact-Pack#806]
Sorry to take up the author's valuable time.
Here is an update on my issue.
After loading the impact node, when I run with a batch size (bs) of 1, the graphics card power consumption is 145W, resulting in a slow generation speed.
![114B6D44540E1AE7E857B7C569B531F6](https://github.com/user-attachments/assets/7559c016-5873-4fd1-83b0-6047e4a8d099)

 It only starts running at full load when the batch size is increased to 4.
![C20E86DF5D09B1C493777E3CFB031226](https://github.com/user-attachments/assets/9991e0bf-0fba-4c71-a7fb-ac8bde74330a)

**Comment by ltdrdata** [comment]
When you increase the batch size by 4 times, the amount of computation that needs to be done at once increases, leading to full load, which naturally results in increased power consumption and slower speed.

I don't understand what your point is.

What does this have to do with Impact Pack?

**Comment by siji444** [comment]
> When you increase the batch size by 4 times, the amount of computation that needs to be done at once increases, leading to full load, which naturally results in increased power consumption and slower speed.
> 
> I don't understand what your point is.
> 
> What does this have to do with Impact Pack?
I know this isn't rigorous; it's just a conclusion drawn from limited testing. This is the current situation as I understand it.
![QQ20241104-151729](https://github.com/user-attachments/assets/e601475d-a77e-4b8d-8b4b-e462961bbe1d)
This is the speed that can be achieved after disabling the plugin.

**Comment by ltdrdata** [comment]
> What does this have to do with Impact Pack?
> I know this isn't rigorous; it's just a conclusion drawn from limited testing. This is the current situation as I understand it.

Do you mean that when Impact Pack is enabled, the GPU doesn't perform at its full capacity with a batch size of 1?
Are your Impact Pack and ComfyUI up to date with the latest version?
And is it default workflow?

Based on my testing, performance remains consistent regardless of whether custom nodes are enabled or disabled.

**Comment by siji444** [comment]
> > What does this have to do with Impact Pack?
> > I know this isn't rigorous; it's just a conclusion drawn from limited testing. This is the current situation as I understand it.
> 
> Do you mean that when Impact Pack is enabled, the GPU doesn't perform at its full capacity with a batch size of 1? Are your Impact Pack and ComfyUI up to date with the latest version? And is it default workflow?
> 
> Based on my testing, performance remains consistent regardless of whether custom nodes are enabled or disabled.

Yes, the Impact Pack and ComfyUI are already the latest versions. It might be an issue with the server's CPU threads or memory allocation, as I also tested on other hosts and the performance remained consistent.

Anyway, thank you very much for your reply.
