### ISSUE TITLE
mmdetdetectorprovider node -> No module named 'aliyunsdkcore'

### ISSUE THREAD

**Issue by ghost** [ltdrdata/ComfyUI-Impact-Pack#81]
Hello !

If I understand well, I must put False for mmdet_skip in impackt.pack.ini to make work mmdetdetectorprovider on my workflow.

But it creates this error on loading :

Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.13.36.tar.gz (440 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jvach\AppData\Local\Temp\pip-install-90063vg1\aliyun-python-sdk-core_229a23951f6f4020bf23ad5aa07b262d\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by ltdrdata** [comment]
Yeah... that is the one reason why I turned off by defautl.
Compatibility issues with the MMDet package always seem to be a headache.

Is there a specific reason for wanting to use `MMDetDetectorProvider` instead of `UltralyticsDetectorProvider`?

**Comment by ghost** [comment]
I have downloaded a worlflow json for a ComfyUI called FaceDetailer.json that requires this node.
Will try another json.

Thanks

**Comment by ltdrdata** [comment]
> I have downloaded a worlflow json for a ComfyUI called FaceDetailer.json that requires this node.
> Will try another json.
> 
> Thanks

replacing MMDetDetectorProvider to UltralyticsDetectorProvider is pretty simple.

https://youtu.be/t-JjsEvPX7o

**Comment by ghost** [comment]
Thanks it works !
