### ISSUE TITLE
Iterative Latent Upscale Error

### ISSUE THREAD

**Issue by nodegraphics** [ltdrdata/ComfyUI-Impact-Pack#810]
Hello, 
I started to get this error today. I was wondering if its related to an update or not and if there is a soolution to it ? 

I cant seem to use any of latent upscale nodes

including error report below:

```
# ComfyUI Error Report
## Error Details
- **Node Type:** IterativeLatentUpscale
- **Exception Type:** AttributeError
- **Exception Message:** 'ControlNet' object has no attribute 'device'
## Stack Trace

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1254, in doit
    current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1985, in upscale_shape
    refined_latent = self.tiled_ksample(upscaled_latent, upscaled_images)

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1940, in tiled_ksample
    return TiledKSampler().sample(model, seed, tile_width, tile_height, tiling_strategy, steps, cfg, sampler_name,

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI_TiledKSampler/nodes.py", line 326, in sample
    return sample_common(model, 'enable', seed, tile_width, tile_height, tiling_strategy, steps_total, cfg, sampler_name, scheduler, positive, negative, latent_image, steps_total-steps, steps_total, 'disable', denoise=1.0, preview=True)

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI_TiledKSampler/nodes.py", line 261, in sample_common
    slice_cnet(tile_h, tile_h_len, tile_w, tile_w_len, m, img)

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI_TiledKSampler/nodes.py", line 91, in slice_cnet
    model.cond_hint = hint.to(model.control_model.dtype).to(model.device)


## System Information
- **ComfyUI Version:** v0.2.7-3-g8afb97c
- **Arguments:** /teamspace/studios/this_studio/ComfyUI/main.py
- **OS:** posix
- **Python Version:** 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA L4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 23802544128
  - **VRAM Free:** 7957294006
  - **Torch VRAM Total:** 8824815616
  - **Torch VRAM Free:** 72526774

```

![image](https://github.com/user-attachments/assets/38b1513d-1f32-4de6-ad76-a0c9955ddf0f)

**Comment by ltdrdata** [comment]
See this:
https://github.com/comfyanonymous/ComfyUI/issues/5344#issuecomment-2440043857

**Comment by DavidSnow1** [comment]
> See this: [comfyanonymous/ComfyUI#5344 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/5344#issuecomment-2440043857)

Hey ltdrdata, 

I know this is somewhat off topic, but a while back, you created a fork of the YoloWorld-EfficientSAM nodes. I've been using your fork for a while, but unfortunately, it no longer works with the latest versions of Comfy.

https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/pull/32

How much effort would be required to update these nodes so they actually work again? I ask because the yoloworld nodes remain the best method of selecting and masking subjects, bar none. It would be a shame to see them die like this. 

Cheers.

**Comment by ltdrdata** [comment]
> > See this: [comfyanonymous/ComfyUI#5344 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/5344#issuecomment-2440043857)
> 
> Hey ltdrdata, 
> 
> I know this is somewhat off topic, but a while back, you created a fork of the YoloWorld-EfficientSAM nodes. I've been using your fork for a while, but unfortunately, it no longer works with the latest versions of Comfy.
> 
> https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM/pull/32
> 
> How much effort would be required to update these nodes so they actually work again? I ask because the yoloworld nodes remain the best method of selecting and masking subjects, bar none. It would be a shame to see them die like this. 
> 
> Cheers. 

Unfortunately, yoloworld's dependencies themselves don't support Python 3.12. To use it, you need to use Python 3.11.

**Comment by nodegraphics** [comment]
Dr. Noob question;
Where do I clone that repo and overwrite ?

**Comment by ltdrdata** [comment]
> See this: [comfyanonymous/ComfyUI#5344 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/5344#issuecomment-2440043857)

Just remove the original ComfyUI_TiledKSampler from ComfyUI/custom_nodes and clone this.

https://github.com/ltdrdata/ComfyUI_TiledKSampler

**Comment by nodegraphics** [comment]
Thank you @ltdrdata 
I did update, it was working but i started to get another error recently
including below;

![image](https://github.com/user-attachments/assets/5670fb0d-1e84-4000-afc5-e6e466ff9a5f)




```
# ComfyUI Error Report
## Error Details
- **Node Type:** IterativeLatentUpscale
- **Exception Type:** TypeError
- **Exception Message:** VAEDecodeTiled.decode() missing 1 required positional argument: 'overlap'
## Stack Trace

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1254, in doit
    current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1973, in upscale_shape
    latent_upscale_on_pixel_space_shape2(samples, scale_method, w, h, vae,

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1381, in latent_upscale_on_pixel_space_shape2
    pixels = vae_decode(vae, samples, use_tile, hook, tile_size=tile_size)

  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1354, in vae_decode
    pixels = nodes.VAEDecodeTiled().decode(vae, samples, tile_size)[0]


## System Information
- **ComfyUI Version:** v0.2.7-11-g9c1ed58
- **Arguments:** /teamspace/studios/this_studio/ComfyUI/main.py
- **OS:** posix
- **Python Version:** 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA L4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 23802544128
  - **VRAM Free:** 3877187858
  - **Torch VRAM Total:** 6442450944
  - **Torch VRAM Free:** 129642770

```

**Comment by ltdrdata** [comment]
> Thank you @ltdrdata I did update, it was working but i started to get another error recently including below;
> 
> ![image](https://private-user-images.githubusercontent.com/10071439/385473719-5670fb0d-1e84-4000-afc5-e6e466ff9a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NTk2NzQsIm5iZiI6MTczMTQ1OTM3NCwicGF0aCI6Ii8xMDA3MTQzOS8zODU0NzM3MTktNTY3MGZiMGQtMWU4NC00MDAwLWFmYzUtZTZlNDY2ZmY5YTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAwNTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMzM5MjhkOGRiNDM2NmRiMWQ2MjJlOGRmMmNjN2I4MzdiMGFhZGY1MjVkYWNkZDYwNTMzYWY3YTYxNzdhNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qmtfex5S9wwpgX8VEqZeWvs4iTLIiHun8rwTM-x3bKI)
> 
> ```
> # ComfyUI Error Report
> ## Error Details
> - **Node Type:** IterativeLatentUpscale
> - **Exception Type:** TypeError
> - **Exception Message:** VAEDecodeTiled.decode() missing 1 required positional argument: 'overlap'
> ## Stack Trace
> 
>   File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
> 
>   File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
> 
>   File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
> 
>   File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
> 
>   File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1254, in doit
>     current_latent = upscaler.upscale_shape(step_info, current_latent, new_w, new_h, temp_prefix)
> 
>   File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1973, in upscale_shape
>     latent_upscale_on_pixel_space_shape2(samples, scale_method, w, h, vae,
> 
>   File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1381, in latent_upscale_on_pixel_space_shape2
>     pixels = vae_decode(vae, samples, use_tile, hook, tile_size=tile_size)
> 
>   File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1354, in vae_decode
>     pixels = nodes.VAEDecodeTiled().decode(vae, samples, tile_size)[0]
> 
> 
> ## System Information
> - **ComfyUI Version:** v0.2.7-11-g9c1ed58
> - **Arguments:** /teamspace/studios/this_studio/ComfyUI/main.py
> - **OS:** posix
> - **Python Version:** 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0]
> - **Embedded Python:** false
> - **PyTorch Version:** 2.4.0+cu121
> ## Devices
> 
> - **Name:** cuda:0 NVIDIA L4 : cudaMallocAsync
>   - **Type:** cuda
>   - **VRAM Total:** 23802544128
>   - **VRAM Free:** 3877187858
>   - **Torch VRAM Total:** 6442450944
>   - **Torch VRAM Free:** 129642770
> ```

Your Impact Pack is still outdated.
Latest version is 7.11.3.

**Comment by nodegraphics** [comment]
Thank you,
