### ISSUE TITLE
[Suggestion] Allow definers to process all bboxes at the same time

### ISSUE THREAD

**Issue by Mass1milian0** [ltdrdata/ComfyUI-Impact-Pack#813]
this seems to be an issue with definers which other uis have solved this same way, when you run a detection model which generates different masks and bboxes, the detailer processes them one at the time, often resulting in asymmetrical results

this is especially relevant if you are trying to use the detailer to fix eyes

it would be nice to have a "merge" mode or just a little toggle to tell the detailer to generate all the masks at the same time

attached examples of what happens if you try to run the detailer at the current state to fix eyes

![image](https://github.com/user-attachments/assets/2b7386af-9609-4015-8363-7cc701a5619a)
![image](https://github.com/user-attachments/assets/128ff4ec-5add-46d5-9735-7d2d0aa0289b)
![image](https://github.com/user-attachments/assets/ca22449c-141a-48b4-b12e-a380b02ab814)
![image](https://github.com/user-attachments/assets/86f83253-ed5b-456b-95ef-dc76b008ea06)

as you can see, although the denoising is at 0.7 (most of the eye is being replaced, as it should) it does actually fix the eyes, but, generates completely different eyes

**Comment by ltdrdata** [comment]
To create an advanced detailing workflow, you should use Detailer rather than FaceDetailer.
Then, you can utilize `SEGS Merge` node.

![segs-merge](https://github.com/user-attachments/assets/666709d4-d29e-45db-a1ee-515e4d61e219)

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/advanced-simple.png

**Comment by Mass1milian0** [comment]
i've already done that exact workflow, i've followed that tutorial already, in fact after the segs merge the segs return empty
