### ISSUE TITLE
Image sender/receiver not working with multiple IDs

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ltdrdata/ComfyUI-Impact-Pack#815]
I have a workflow that worked fine using a single send/receive pair (ID0), but when I added a second pair (ID1) then the behaviour seems to be broken and the incorrect images are sent. It's hard to explain, but ID1 seems to use the image created from the previous run of the workflow.
It seems to go wrong at this point in the image below, where ID0 is showing the correct image, but it's passing the image from the last run into the node. You can see the output doesn't match the input faces.
![image](https://github.com/user-attachments/assets/b074d16f-85f4-44ae-aa95-5cd5271d827e)

The one on the left here is the newly created image, and the one on the right was from the previous run.
![image](https://github.com/user-attachments/assets/2f28cced-60a4-4b8a-8606-e4c757810610)

**Comment by GalaxyTimeMachine** [comment]
This is definitely a problem between the input and output of the receive node. You can see that the correct image has been passed to the receiver, but the output (input b, on the left in the comparer) is still showing the previous image.
![image](https://github.com/user-attachments/assets/36b14dfd-8e3b-4e33-9717-f86aee024c60)

**Comment by GalaxyTimeMachine** [comment]
I think I found out what is happening. Instead of creating the initial image first, the image receiver is loading the image it already has, from the last wf run, into the facedetailer before the first ksampler has done anything. Then the ksampler creates the initial image, passes that to the receiver, but the facedetailer has already run, so ignores the new image.
Basically, the load image behaviour of the receiver is being acted on before ksampler.

**Comment by git-wzp** [comment]
I have also found this problem. I have written a simple workflow to describe this phenomenon. When I send Picture A, Picture A can be received. When I replace Picture A with Picture B, Picture A is still received. Only by running it again can Picture B be received. This makes the function nodes for image sending and receiving very unstable to use, especially during batch operations.
At the same time, because the receiver must default to selecting an image file, there are often situations where the sent images cannot be received, and the node needs to be deleted and re - set.
![image](https://github.com/user-attachments/assets/cd679085-5e34-45cc-9348-6d76ea5f209b)

**Comment by ltdrdata** [comment]
> I have also found this problem. I have written a simple workflow to describe this phenomenon. When I send Picture A, Picture A can be received. When I replace Picture A with Picture B, Picture A is still received. Only by running it again can Picture B be received. This makes the function nodes for image sending and receiving very unstable to use, especially during batch operations. At the same time, because the receiver must default to selecting an image file, there are often situations where the sent images cannot be received, and the node needs to be deleted and re - set. ![image](https://private-user-images.githubusercontent.com/29686324/399320853-cd679085-5e34-45cc-9348-6d76ea5f209b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MTM5ODEsIm5iZiI6MTczNTYxMzY4MSwicGF0aCI6Ii8yOTY4NjMyNC8zOTkzMjA4NTMtY2Q2NzkwODUtNWUzNC00NWNjLTkzNDgtNmQ3NmVhNWYyMDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDAyNTQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MjAyZDBkZjhhOGNhMDgzYjRlNjhkZmJlYWEwYTRjMjRjNWQ2ZDk0OTY2MDhjMGY3ODJhNGU2YWU2ZTM4NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8pUr_MkOMNT-sZGgqf63KfPNTxgLcFN-PJyKYsu6POI)

The `Image Receiver` updates its information with the received data the moment it receives an image from the `Image Sender`.  
However, what the `Image Receiver` outputs is not the data received from the `Image Sender,` but rather the data it already holds at the time it is queued.  

It is important to clearly recognize this difference.

In other words, the use of the `Image Sender/Image Receiver` is designed not for immediate execution after updating within a single workflow execution, but for configurations that involve multiple workflow executions.
