### ISSUE TITLE
'VAE' object has no attribute 'base_dtype'

### ISSUE THREAD

**Issue by 158zd** [ltdrdata/ComfyUI-Impact-Pack#816]
(.venv) PS D:\AI\ComfyUI> python main.py
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-16 13:02:07.790719
** Platform: Windows
** Python version: 3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: D:\AI\ComfyUI
** Log path: D:\AI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   4.8 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 65416 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\AI\ComfyUI\web
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: D:\AI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Total VRAM 8188 MB, total RAM 65416 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2832 [4ac401af] | Released on '2024-11-15'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']       
DWPose: Onnxruntime with acceleration providers detected
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[comfy_mtb] | INFO -> loaded 86 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

[rgthree-comfy] Loaded 42 epic nodes. 🎉

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: D:/AI/wb/ffmpeg/bin/ffmpeg.exe
WAS Node Suite: Finished. Loaded 219 nodes successfully.

        "The only limit to our realization of tomorrow will be our doubts of today." - Franklin D. Roosevelt   

Import times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\Batch-Condition-ComfyUI
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_HF_Servelress_Inference
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.3 seconds: D:\AI\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
   0.5 seconds: D:\AI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.9 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager
   1.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.1 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-BrushNet
   2.9 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   3.2 seconds: D:\AI\ComfyUI\custom_nodes\comfy_mtb
   5.4 seconds: D:\AI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
final text_encoder_type: bert-base-uncased
Loads SAM model: D:\AI\ComfyUI\models\sams\sam_vit_b_01ec64.pth (device:Prefer GPU)
D:\AI\ComfyUI\.venv\Lib\site-packages\transformers\modeling_utils.py:1161: FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
D:\AI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\py\local_groundingdino\models\GroundingDINO\transformer.py:862: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):
# of Detected SEGS: 1
1girl, solo, long_hair, looking_at_viewer, skirt, brown_hair, shirt, long_sleeves, brown_eyes, jewelry, standing, full_body, earrings, outdoors, shoes, day, socks, off_shoulder, nail_polish, black_footwear, sweater, tree, hand_on_hip, sleeves_past_wrists, plaid, window, leaf, plaid_skirt, white_socks, pink_nails, pink_shirt, autumn_leaves, autumn, pink_sweater,
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load SD1ClipModel
Loading 1 new model
loaded completely 0.0 235.84423828125 True
WARNING: No VAE weights detected, VAE not initalized.
# of Detected SEGS: 1
model_path is D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\TheMistoAI/MistoLine\Anyline\MTEED.pth
model_path is D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\yolox_l.onnx
model_path is D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/DWPose-TorchScript-BatchSize5\dw-ll_ucoco_384_bs5.torchscript.pt

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384_bs5.torchscript.pt for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
DWPose: Caching TorchScript module dw-ll_ucoco_384_bs5.torchscript.pt on ...
DWPose: Bbox 332.19ms
DWPose: Pose 401.66ms on 1 people

model_path is D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\LiheYoung/Depth-Anything\checkpoints\depth_anything_vitl14.pth
using MLP layer as FFN
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Detailer: force inpaint
Detailer: segment upscale for ((718, 1535)) | crop region (1024, 1536) x 1.0 -> (1024, 1536)
!!! Exception during processing !!! 'VAE' object has no attribute 'vae_dtype'
Traceback (most recent call last):
  File "D:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 378, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps,
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 323, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 324, in enhance_detail
    latent_image = to_latent_image(upscaled_image, vae)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 512, in to_latent_image
    return vae_encode.encode(vae, pixels)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\nodes.py", line 319, in encode
    t = vae.encode(pixels[:,:,:,:3])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\comfy\sd.py", line 391, in encode
    memory_used = self.memory_used_encode(pixel_samples.shape, self.vae_dtype)
                                                               ^^^^^^^^^^^^^^
AttributeError: 'VAE' object has no attribute 'vae_dtype'

Prompt executed in 30.44 seconds

**Comment by ltdrdata** [comment]
What is your workflow?

This issue occurs not because of the Impact Pack itself, but because the VAE passed to the nodes in the Impact Pack is invalid.

**Comment by 158zd** [comment]
Sorry, it has been resolved. The nodes weren't linked.
