### ISSUE TITLE
About the behavior of "From SEG_ELT bbox"

### ISSUE THREAD

**Issue by bluesura** [ltdrdata/ComfyUI-Impact-Pack#824]
This is a discussion about trying to obtain the bbox position using the following process:
mask → MASK to SEGS → Decompose (SEGS) → From SEG_ELT → From SEG_ELT bbox

For example, when obtaining a mask of the ground, there is no issue if the mask is continuous. However, when the mask consists of multiple disconnected parts (e.g., islands), multiple bboxes are generated, leading to multiple processes. While the processes execute without issues, this becomes very troublesome. If you are performing image processing using this setup, multiple images will be generated. Passing these images to the sampler means feeding multiple images, which increases memory consumption significantly.

I also tried combining different nodes to somehow consolidate the multiple images into a single one, but since the processing is not batch-based and occurs separately, it’s challenging to address this. I even tried the combined property in MASK to SEGS, but it resulted in an error when trying to obtain the position with "From SEG_ELT bbox."

Is there any solution to this issue?

**Comment by ltdrdata** [comment]
What exactly are you trying to achieve with multiple bboxes?

**Comment by bluesura** [comment]
What I am trying to achieve with "From SEG_ELT bbox" is as follows:

・Detect the area to be masked using SAM.
・Place a mask either randomly or at a specific location in the detected area.
・Generate objects in that location using inpainting.

The bbox is used to estimate where the masks detected by SAM are located.
While it might be possible to determine the location using other methods, in this case, the environment is restricted to cog-comfyui, and after exploring various options, I arrived at "From SEG_ELT bbox."

**Comment by bluesura** [comment]
![image](https://github.com/user-attachments/assets/44b4911e-1b74-4eba-8541-9ad1d6334a52)

**Comment by ltdrdata** [comment]
It seems that using the loop function might offer a possible solution, but additional development would likely be required.
I will try implementing some nodes for it in the Inspire Pack later.

**Comment by bluesura** [comment]
Thank you for considering this on such short notice. I really appreciate it. I’ll be waiting for your response.

**Comment by ltdrdata** [comment]
Update Inspire Pack.

![workflow (1)](https://github.com/user-attachments/assets/e6c6b6db-56b3-4212-a856-760306fa204d)

**Comment by bluesura** [comment]
Thank you for proposing a solution the other day. I believe this node is also a highly useful one.
Since then, I’ve been studying the documentation to figure out if there’s a way to narrow it down to a single item, and I’ve finally found a solution. I’ll leave it here as a memo.

![image](https://github.com/user-attachments/assets/55400557-104f-4a3e-abdb-70c236490dd2)
