### ISSUE TITLE
How to Prevent an Image Switcher from Freezing When no images Is Provided?

### ISSUE THREAD

**Issue by 4lt3r3go** [ltdrdata/ComfyUI-Impact-Pack#825]
I have an image switcher to select from a set of images
but there’s a case where I don’t want to input any images at all, so a cable arrives but theres no images on the other side.
The problem is that if I don’t provide any image to the switch in that particular point, it freezes, blocking the workflow.
Any idea how to prevent the switch from freezing or any logic workaround to this?

**Comment by 4lt3r3go** [comment]
i absolutly need to find a way to solve this 🙏🏻
![image](https://github.com/user-attachments/assets/049a13d0-2a27-4816-acac-7aea34d679b3)

**Comment by 4lt3r3go** [comment]
hello?

**Comment by ltdrdata** [comment]
If no default input is provided, the switch node will not be executed. Although it will be highlighted with a red border, it should not stop the execution of the workflow?

**Comment by 4lt3r3go** [comment]
> If no default input is provided, the switch node will not be executed. Although it will be highlighted with a red border, it should not stop the execution of the workflow?

unfortunatly it freeze. the workflow do not execute.

**Comment by 4lt3r3go** [comment]
https://github.com/user-attachments/assets/6c3a6cd6-c106-4bca-84c0-61c38b9a0c50

**Comment by ltdrdata** [comment]
Install this and try again.
https://github.com/ty0x2333/ComfyUI-Dev-Utils

Then you can see the detailed execution log in the terminal.

**Comment by 4lt3r3go** [comment]
> Install this and try again. https://github.com/ty0x2333/ComfyUI-Dev-Utils
> Then you can see the detailed execution log in the terminal.

![image](https://github.com/user-attachments/assets/e055b6f9-23c9-4e04-9946-cea16ea4df9f)

yes

**Comment by 4lt3r3go** [comment]
i can't believe i solved this by adding this node alone.
![image](https://github.com/user-attachments/assets/59188114-708e-4dab-942c-5f0e340460fb)
thanks for your time
