### ISSUE TITLE
FaceDetailer always results in blue eyes

### ISSUE THREAD

**Issue by imReinhard** [ltdrdata/ComfyUI-Impact-Pack#827]
No matter what clip, condition or model I provide FaceDetailer always end up with blue eyes and also removes facial expressions. Tried to only input a clip text (red eyes:1.5), but still ended up blue eyes. Am I missing something important?
![image](https://github.com/user-attachments/assets/70aa9211-767f-48db-b61b-800331913b22)

**Comment by ltdrdata** [comment]
I need to look at the overall workflow.

**Comment by ltdrdata** [comment]
In FacePipe, if you don't leave the prompt empty, the default behavior is to overwrite the existing conditioning.
You need to use the `[CONCAT]` syntax.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md#special-syntax-for-detailer-wildcard

**Comment by imReinhard** [comment]
Removing basic pipe node and basic pipe to detailer pipe node instead using
normal facedetailer solved the issue
