### ISSUE TITLE
Why is it that the sam model I put in the ComfyUI/models/sams path is not displayed in the sam loader of the impact-pack node?

### ISSUE THREAD

**Issue by Uzistick911** [ltdrdata/ComfyUI-Impact-Pack#829]
Why is it that the sam model I put in the ComfyUI/models/sams path is not displayed in the sam loader of the impact-pack node?
![Uploading df11dbe92941ddf30a9cb6b51dea54f.png…]()
![Uploading 73069e4252ca8ef4f742fae5dbb5036.png…]()

**Comment by ltdrdata** [comment]
I'm not sure if it's because of GitHub's current status, but the image you uploaded is not showing at all.

**Comment by k10719** [comment]
![屏幕截图 2024-12-24 200420](https://github.com/user-attachments/assets/a0a89530-762c-4a7c-8409-b4d2cdd28b4a)

**Comment by ltdrdata** [comment]
> ![屏幕截图 2024-12-24 200420](https://private-user-images.githubusercontent.com/126672428/398408133-a0a89530-762c-4a7c-8409-b4d2cdd28b4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDkwMTQsIm5iZiI6MTczNTEwODcxNCwicGF0aCI6Ii8xMjY2NzI0MjgvMzk4NDA4MTMzLWEwYTg5NTMwLTc2MmMtNGE3Yy04NDA5LWI0ZDJjZGQyOGI0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQwNjM4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmQwMzE2NzkxMTc4ZDZmMTA1MTAwZTEwNzE0YjhiZDJiY2Y5ZjhjNTQ0Y2IyZDMwMzI2N2RhNzNjMWI4N2M5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a3S_KkBh7OLYgXZOOeILao8njvvEpGPkN6K0xO3gisE)

Reinstall `ComfyUI-Impact-Pack` and install `ComfyUI-Impact-Subpack` additionally.
