### ISSUE TITLE
Trying to understand difference in FaceDetailer vs. adetailer inpaint quality

### ISSUE THREAD

**Issue by alexopus** [ltdrdata/ComfyUI-Impact-Pack#83]
While learning ComfyUI and this extension, I am trying to reproduce one of my stable-diffusion-webui workflows, which is:

stable-diffusion-webui: 512x768 -> hiresfix 2x -> [adetailer](https://github.com/Bing-su/adetailer)
ComfyUI: 512x768 -> hiresfix 2x -> FaceDetailer node

I observe that face detection works fine, but inpainting produces significantly better results with adetailer in most cases.

I tried to have the seeds the same for the sake of this comparison, but webui and comfy still produce different results, can't say why. However the difference in face inpainting is mostly consistent between them in many iterations, although sometimes less pronounced.

Here are 2 examples:

<details>
  <summary>adetailer 1</summary>

![00000-256_dreamshaper_8_DPM++ 2M Karras 30 _cfg7 5_cs2_dn0 6-ad-preview](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/3b2235e7-7f37-467f-8231-5a5c5695580c)
->
![00002-256_dreamshaper_8_DPM++ 2M Karras 30 _cfg7 5_cs2_dn0 6](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/f14f9be9-0965-411d-ab7b-dfe018a5c4cf)

</details>
<details>
  <summary>FaceDetailer 1</summary>

![comfy_hires](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/479ffda8-0f51-4cda-aeda-779975442522)
->
![comfy_hires_facedetailer](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/44ec666e-5684-4708-be00-31efaf7c9e2d)

</details>

<details>
  <summary>adetailer 2</summary>

![258612549-1274276604_dreamshaper_8_DPM++ 2M Karras 30 _cfg7 5_cs2_dn0 6-ad-preview](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/ddaa5cf7-504c-4818-baeb-b08b488b60f0)
->
![258612551-1274276604_dreamshaper_8_DPM++ 2M Karras 30 _cfg7 5_cs2_dn0 6](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/28eed878-9a7b-49ec-908b-96791fa30141)

</details>
<details>
  <summary>FaceDetailer 2</summary>

![comfy_2_hires](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/905acd84-05d6-401f-8529-76d2d9603bbf)
->
![comfy_2_hires_facedetailer](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/346c36dd-fe27-4bac-9e8f-fef7fa993389)

</details>

The difference between source and result with FaceDetailer is quite small. (It is much better with images before hiresfix, so perhaps I am missing some setting for higher resolution source?)

In ComfyUI I only use the box model (without SAM), since that's what adetailer is doing here. All the settings should be contained in the above pngs, but here they are again just in case:

<details>
  <summary>adetailer</summary>

![adetailer](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/b3a0bf34-0dcc-4388-84e6-fa1ebe314aee)

```
(masterpiece:1.2), 1girl, (waist photo:1.3), (blonde hair, ponytail, straight hair), green eyes, focus on eyes, detailed pupil, white shirt, black background, highly detailed, 8k, hdr
Negative prompt: nsfw, nipples, (worst quality, low quality, bad quality:1.3)
Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 7.5, Seed: 1274276604, Size: 512x768, Model hash: 879db523c3, Model: dreamshaper_8, Denoising strength: 0.6, Clip skip: 2, ADetailer model: face_yolov8n.pt, ADetailer confidence: 0.3, ADetailer dilate/erode: 4, ADetailer mask blur: 4, ADetailer denoising strength: 0.4, ADetailer inpaint only masked: True, ADetailer inpaint padding: 32, ADetailer version: 23.7.11, Hires upscale: 2, Hires steps: 15, Hires upscaler: Latent (nearest-exact), Version: v1.5.1
```

</details>
<details>
  <summary>comfy</summary>

![comfy](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/ea89d51c-933a-406e-961d-9374473e3e2f)
</details>

I tried getting all the settings to be the same with both GUIs/extensions, but perhaps I am still missing something.

Bumping the FaceDetailer denoise up to 0.6-0.7 does seem to help a bit, but adetailer is still consistently better. Plus, why does adetailer manage just with 0.4? What is the difference?

Or perhaps there is some fundamental difference between these approaches?

Edit: my ComfyUI is at https://github.com/comfyanonymous/ComfyUI/commit/b948b2c, Impact Pack at 4fc446334a0e45239b8b1ea8c31ac13468d35305. Both installed today from scratch

**Comment by ltdrdata** [comment]
In essence, both `adetailer` and `Impact Pack`'s detailer share the same underlying principle. It involves magnifying the original image for regeneration and then downsizing it before pasting it back. However, there are differences in the parameters that affect the quality of the generated images.

In the impact pack detailer, the parameter "guide_size" determines how much to upscale, and the "crop_factor" decides how much of the surrounding image to consider for creating a natural-looking result. Setting "crop_factor" to 1.0 focuses strictly on the facial area, potentially causing quality discrepancies between the facial area and the surroundings.

I've uploaded a detailed explanation video for the key parameters. Please refer to it for further information.

https://youtu.be/KvZ8ucBqyqw

**Comment by alexopus** [comment]
Thanks, I'll give that a try!

**Comment by alexopus** [comment]
That was very helpful.

In my case the difference must have been the mismatch between guide_size/max_size of FaceDetailer and the related parameters of adetailer. adetailer was setup to use width/height of the input image for the inpainting, which after hirexfix would be 1024x1536. But FaceDetailer had guide_size/max_size of 256/768, which would not allow it to upscale as much as adetailer. After bumping them to 384/1536 the quality improved significantly.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/25933468/088cd566-0561-4aa0-97f0-0ece149add0b)

Thanks again for the explanation and the awesome extension :)
