### ISSUE TITLE
ERROR: This installation is not allowed in this security_level. Please contact the administrator.

### ISSUE THREAD

**Issue by xueyueicu** [ltdrdata/ComfyUI-Impact-Pack#832]
## ComfyUI-Manager: EXECUTE => ['/opt/conda/envs/py310/bin/python', 'install.py']
[!] 
[!] [bold yellow]WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `/root/siton-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/../../` as the ComfyUI path.[/bold yellow]
[!] 
[!] [bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `/root/siton-tmp/ComfyUI/models` as the ComfyUI path.[/bold yellow]
[!] Traceback (most recent call last):
[!]   File "/opt/conda/envs/py310/lib/python3.10/urllib/request.py", line 1348, in do_open
[!]     h.request(req.get_method(), req.selector, req.data, headers,
[!]   File "/opt/conda/envs/py310/lib/python3.10/http/client.py", line 1283, in request
[!]     self._send_request(method, url, body, headers, encode_chunked)
[!]   File "/opt/conda/envs/py310/lib/python3.10/http/client.py", line 1329, in _send_request
[!]     self.endheaders(body, encode_chunked=encode_chunked)
[!]   File "/opt/conda/envs/py310/lib/python3.10/http/client.py", line 1278, in endheaders
[!]     self._send_output(message_body, encode_chunked=encode_chunked)
[!]   File "/opt/conda/envs/py310/lib/python3.10/http/client.py", line 1038, in _send_output
[!]     self.send(msg)
[!]   File "/opt/conda/envs/py310/lib/python3.10/http/client.py", line 976, in send
[!]     self.connect()
[!]   File "/opt/conda/envs/py310/lib/python3.10/http/client.py", line 1448, in connect
[!]     super().connect()
[!]   File "/opt/conda/envs/py310/lib/python3.10/http/client.py", line 942, in connect
[!]     self.sock = self._create_connection(
[!]   File "/opt/conda/envs/py310/lib/python3.10/socket.py", line 857, in create_connection
[!]     raise err
[!]   File "/opt/conda/envs/py310/lib/python3.10/socket.py", line 845, in create_connection
[!]     sock.connect(sa)
[!] OSError: [Errno 99] Cannot assign requested address
[!] 
[!] During handling of the above exception, another exception occurred:
[!] 
[!] Traceback (most recent call last):
[!]   File "/root/siton-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/install.py", line 30, in <module>
[!]     download_url("https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt",
[!]   File "/opt/conda/envs/py310/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 122, in download_url
[!]     url = _get_redirect_url(url, max_hops=max_redirect_hops)
[!]   File "/opt/conda/envs/py310/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 66, in _get_redirect_url
[!]     with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
[!]   File "/opt/conda/envs/py310/lib/python3.10/urllib/request.py", line 216, in urlopen
[!]     return opener.open(url, data, timeout)
[!]   File "/opt/conda/envs/py310/lib/python3.10/urllib/request.py", line 519, in open
[!]     response = self._open(req, data)
[!]   File "/opt/conda/envs/py310/lib/python3.10/urllib/request.py", line 536, in _open
[!]     result = self._call_chain(self.handle_open, protocol, protocol +
[!]   File "/opt/conda/envs/py310/lib/python3.10/urllib/request.py", line 496, in _call_chain
[!]     result = func(*args)
[!]   File "/opt/conda/envs/py310/lib/python3.10/urllib/request.py", line 1391, in https_open
[!]     return self.do_open(http.client.HTTPSConnection, req,
[!]   File "/opt/conda/envs/py310/lib/python3.10/urllib/request.py", line 1351, in do_open
[!]     raise URLError(err)
[!] urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
 ### ComfyUI-Impact-Pack: Check dependencies
 [!] ### ComfyUI-Impact-Pack: Updating subpack
 
[Impact Pack] EXECUTE: ['/opt/conda/envs/py310/bin/python', 'install.py'] in '/root/siton-tmp/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
 ### ComfyUI-Impact-Pack: Check basic models
 Downloading https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth to /root/siton-tmp/ComfyUI/models/sams/sam_vit_b_01ec64.pth
100%|██████████| 375042383/375042383 [00:20<00:00, 18545765.20it/s]
100%|██████████| 375042383/375042383 [00:20<00:00, 18513196.17it/s]
 ### ComfyUI-Impact-Pack: onnx model directory created (/root/siton-tmp/ComfyUI/models/onnx)
Attempt to fixing '['https://github.com/ltdrdata/ComfyUI-Impact-Pack']' is done.
ERROR: This installation is not allowed in this security_level. Please contact the administrator.
Reference: https://github.com/ltdrdata/ComfyUI-Manager#security-policy

**Comment by ltdrdata** [comment]
Try reinstall. Though you should download models manually.

**Comment by Creepybits** [comment]
If you have installed the [desktop app](https://github.com/Comfy-Org/desktop) you will need to manually install the impact pack at: `C:\Users\YOURUSERNAME\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes`

Then it will work. And obviously change the YOURUSERNAME for whatever is on your account on your computer.

**Comment by ltdrdata** [comment]
In a few hours, the Impact Subpack will be separated into a separate node and registered. You just need to update the Impact Pack and add the Impact Subpack.

**Comment by ltdrdata** [comment]
Impact Pack v8.0 is released.
Reinstall Imapact Pack and Impact Subpack.
