### ISSUE TITLE
PixelTiledKSampleUpscalerProvider 👉 AttributeError: 'ControlNet' object has no attribute 'device'

### ISSUE THREAD

**Issue by Aaalice233** [ltdrdata/ComfyUI-Impact-Pack#833]
![image](https://github.com/user-attachments/assets/cab527ce-160f-4f65-9114-90ba9006ed0d)

**Comment by Aaalice233** [comment]
The error seems to be caused by ComfyUI_TiledKSampler, but the author does not seem to have any intention of updating it. Is there any other solution?

**Comment by ltdrdata** [comment]
I made a patched version.
https://github.com/LtDrData/ComfyUI_TiledKSampler

Unfortunately, this is not merged yet.
