### ISSUE TITLE
PixelTiledKSampleUpscalerProvider Need AYS SDXL Scheduler

### ISSUE THREAD

**Issue by Aaalice233** [ltdrdata/ComfyUI-Impact-Pack#839]
![image](https://github.com/user-attachments/assets/4115e661-73a0-4233-9679-22650c109d79)

**Comment by ltdrdata** [comment]
Unfortunately, Impact Pack unable to support this feature at the moment due to the limitations of BlenderNeko/TiledKSampler.
Improvements to TiledKSampler are required.
