### ISSUE TITLE
 error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by bukeshui0926** [ltdrdata/ComfyUI-Impact-Pack#84]

**Comment by bukeshui0926** [comment]
![屏幕截图 2023-08-06 231954](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116459766/a288d612-67a3-4c98-bdf9-963be66cdfe3)

**Comment by bukeshui0926** [comment]
![屏幕截图 2023-08-06 232032](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116459766/b969cbd2-9384-4ebb-9406-a9c58b9a7312)

**Comment by bukeshui0926** [comment]
I don't know if I made a mistake during the installation process, and an error was generated during the startup process that made it seem to not load successfully。

**Comment by ltdrdata** [comment]
> I don't know if I made a mistake during the installation process, and an error was generated during the startup process that made it seem to not load successfully。

It is recommended to keep `mmdet_skip` as `True`. The installation issues with mmdet depending on the environment are widely known. If it's because of `MMDetDetectorProvider`, it's much easier to simply replace it with `UltralyticsDetectorProvider`.

**Comment by bukeshui0926** [comment]
> 



> > I don't know if I made a mistake during the installation process, and an error was generated during the startup process that made it seem to not load successfully。
> 
> It is recommended to keep `mmdet_skip` as `True`. The installation issues with mmdet depending on the environment are widely known. If it's because of `MMDetDetectorProvider`, it's much easier to simply replace it with `UltralyticsDetectorProvider`.

Probably not for this reason

**Comment by ltdrdata** [comment]
> > 
> 
> > > I don't know if I made a mistake during the installation process, and an error was generated during the startup process that made it seem to not load successfully。
> > 
> > 
> > It is recommended to keep `mmdet_skip` as `True`. The installation issues with mmdet depending on the environment are widely known. If it's because of `MMDetDetectorProvider`, it's much easier to simply replace it with `UltralyticsDetectorProvider`.
> 
> Probably not for this reason

`aliyunsdkcore` is only required when installing openmim. Additionally, the installation attempt is configured to occur only if `mmdet_skip = False`

Please provide a capture of the impact-pack.ini file and the complete terminal error log. It's not possible to make a determination based solely on the error message related to the missing aliyunsdkcore.

**Comment by ferret99gt** [comment]
I'm encountering this same issue with a brand new Comfui portable install. I'm deliberately trying to enable mmdet.

..\ComfyUI_windows_portable>.\python_embeded\python.exe -m pip install aliyunsdkcore

Collecting aliyunsdkcore
  Using cached aliyunsdkcore-1.0.3.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\xxx\AppData\Local\Temp\pip-install-gq5g32w4\aliyunsdkcore_56328e13cc8b465b837bbad529e5a0b5\setup.py", line 225, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ferret99gt** [comment]
I resolved this with:
.\python_embeded\python -m pip install opendatalab==0.0.9
.\python_embeded\python -m pip install openmim

opendatalab 0.0.10 was released on Aug 2, 2023, and it's the one that pulls in oss2~=2.17.0->openxlab, which pulls in the broken aliyun-python-sdk-core.

**Comment by ltdrdata** [comment]
> I resolved this with:
> .\python_embeded\python -m pip install opendatalab==0.0.9
> .\python_embeded\python -m pip install openmim
> 
> opendatalab 0.0.10 was released on Aug 2, 2023, and it's the one that pulls in oss2~=2.17.0->openxlab, which pulls in the broken aliyun-python-sdk-core.
> 

Thank you for the solution. I need to freeze version.
