### ISSUE TITLE
latest comfyui updates break SWITCH (ANY)

### ISSUE THREAD

**Issue by tester4488** [ltdrdata/ComfyUI-Impact-Pack#840]
![immagine](https://github.com/user-attachments/assets/aaaed49d-db6e-4d68-b366-db72236f6821)

**Comment by Djanghost** [comment]
Same here, since the update "Add union link connection type support" (commit: 8d4e06324fb6c477c1f7f409c857c33d0b3b0ce2 ) that messes up some custom nodes

**Comment by tester4488** [comment]
confirm the problem is the 
https://github.com/comfyanonymous/ComfyUI/commit/8d4e06324fb6c477c1f7f409c857c33d0b3b0ce2
commit

**Comment by ltdrdata** [comment]
That is reverted.
https://github.com/comfyanonymous/ComfyUI/pull/5889
