### ISSUE TITLE
use Regional Sampler

### ISSUE THREAD

**Issue by Chengym2023** [ltdrdata/ComfyUI-Impact-Pack#845]
how could i use Regional Sampler to draw two difference character?

**Comment by ltdrdata** [comment]
You can modify the following workflow to set different prompts for the two regions.  
When applying two characters, it is recommended not only to separate the regions but also to use **ControlNet** together for better results.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/regional-loras.png

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/regional-sampling.png
