### ISSUE TITLE
[ Question ] Is there a use case to select the empty `Switch (Any)` input ?

### ISSUE THREAD

**Issue by JorgeR81** [ltdrdata/ComfyUI-Impact-Pack#846]
Is there a use case to select the empty `Switch (Any)` input ?

I'm not sure, but I think in the past, this could simulate unplugging a wire, from an optional input ( see examples below ).

But now it does not work anymore. It just throws an error.

![err1](https://github.com/user-attachments/assets/b9bfb1ee-550f-4d8d-aadf-c9d2c705dc4a)

---

![m1](https://github.com/user-attachments/assets/0a9a9471-954d-4612-9141-e9aa806056df)

![mask](https://github.com/user-attachments/assets/954cccab-f26e-477f-a665-64cb89f14b58)

**Comment by ltdrdata** [comment]
What you're thinking of is the **select_on_prompt** mode. It unplugs before execution and then runs the workflow.

**Comment by JorgeR81** [comment]
> What you're thinking of is the select_on_prompt mode. It unplugs before execution and then runs the workflow.

I just tried this, but I still got an error.

I tried on a workflow, with an optional, alternative prompt, for the second KSampler.
The switch it's connected to the `Edit BasicPipe` node. 
And I select `input2` to simulate unplugging the wire. 

The first `KSampler` runs successfully 
Then the `input2` is selected.
And then it throws an error anyways. 

```
got prompt
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.98it/s]
SELECTED: input2
!!! Exception during processing !!! Node 41 says it needs input input2, but there is no input to that node at all
Traceback (most recent call last):
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 301, in execute
    execution_list.make_input_strong_link(unique_id, i)
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\comfy_execution\graph.py", line 94, in make_input_strong_link
    raise NodeInputError(f"Node {to_node_id} says it needs input {to_input}, but there is no input to that node at all")comfy_execution.graph.NodeInputError: Node 41 says it needs input input2, but there is no input to that node at all

Prompt executed in 10.73 seconds

```


![err1](https://github.com/user-attachments/assets/0ce816eb-936a-47cb-a7ea-d2468e35017d)

**Comment by JorgeR81** [comment]
I noticed that if  I disable **select_on_prompt**, I have the same behaviour.
The `input2` is also selected when the workflow it's runing ( after the first KSampler ).

And I have the same error, in the swicth node.

```
got prompt
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.99it/s]
SELECTED: input2
!!! Exception during processing !!! Node 41 says it needs input input2, but there is no input to that node at all
Traceback (most recent call last):
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 301, in execute
    execution_list.make_input_strong_link(unique_id, i)
  File "C:\Cui\cu_121_2\ComfyUI_windows_portable\ComfyUI\comfy_execution\graph.py", line 94, in make_input_strong_link
    raise NodeInputError(f"Node {to_node_id} says it needs input {to_input}, but there is no input to that node at all")
comfy_execution.graph.NodeInputError: Node 41 says it needs input input2, but there is no input to that node at all

Prompt executed in 10.72 seconds
```

![rr2](https://github.com/user-attachments/assets/a82300b1-7c19-4573-b74a-4d87fb0c3a36)

**Comment by ltdrdata** [comment]
I have fixed this issue.  
When using `select_on_execution`, selecting an empty slot no longer causes an error.

**Comment by JorgeR81** [comment]
Yeah, now it does not throw an error.
But the behaviour it's not the same as unplugging a wire. 

In my example workflow, now the second KSampler does not run.
But it will run, if I unplug the wire.
The second KSampler should always run. The only difference is that it will use the original prompt, if the wire it's unplugged.

And also, I have this same behavior in both select modes.  
No error, but the second KSampler does not run.

![sw](https://github.com/user-attachments/assets/84f7e599-c8e3-49ed-9541-298c2d04e3a1)

**Comment by JorgeR81** [comment]
If I mute the switch node, I can simulate the effect of unplugging the wire. 
( The second KSampler will run, as you can see, in the screenshot ).

But it's much more convenient, to use the switch input to do that. 
Could it be possible to have this behaviour again ? 
( I think that's the way it worked before. )

![mute](https://github.com/user-attachments/assets/fbbe0b7c-1b19-46bc-a507-92a250ec43d9)

**Comment by ltdrdata** [comment]
Update to 7.14.3.

It was still simulating a disconnect, but the node continued to function because `input1` is optional. Since the patch now disconnects the output, execution will be blocked.

**Comment by JorgeR81** [comment]
> Update to 7.14.3.
> 
> It was still simulating a disconnect, but the node continued to function because input1 is optional. Since the patch now disconnects the output, execution will be blocked.

Do you mean, the whole `basic_pipe` output it's disconnected, in the `Edit BasicPipe` node ? 

It's that really necessary ?
The way it worked before was better. 
The pipe nodes still have enough data to keep the execution going.

**Comment by JorgeR81** [comment]
> Update to 7.14.3.

OK, thanks. After the latest update it's working correctly ( the second sampler still runs ).

**Comment by ltdrdata** [comment]
> > Update to 7.14.3.
> 
> OK, thanks. After the latest update it's working correctly ( the second sampler still runs ).

This patch will disconnect outputs of `Switch` node. 
If selected input is not connected.
