### ISSUE TITLE
ImpactWildcardEncode Selecting LoRA or wildcard not working

### ISSUE THREAD

**Issue by acgc99** [ltdrdata/ComfyUI-Impact-Pack#847]
The dropdown list of LoRAs/wildcards appears when I press the button, but when I select one of them, nothing happens. LoRAs and wildcards are loaded correctly by other nodes.

**Comment by ltdrdata** [comment]
A compatibility issue occurred with the latest frontend, so **Impact Pack** has also released a compatibility patch.  
If either one is an outdated version, compatibility issues may arise.  
Please update both **ComfyUI** and **Impact Pack** to the latest versions.
