### ISSUE TITLE
No module named 'impact.subpack_nodes'

### ISSUE THREAD

**Issue by Leo-YJL** [ltdrdata/ComfyUI-Impact-Pack#850]
### Loading: ComfyUI-Impact-Pack (V7.14)
[Impact Pack] Failed to import due to several dependencies are missing!!!!
Traceback (most recent call last):
  File "F:\SDComfyui\ComfyUI_0.3.7\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\SDComfyui\ComfyUI_0.3.7\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 53, in <module>
    raise e
  File "F:\SDComfyui\ComfyUI_0.3.7\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 31, in <module>
    import impact.subpack_nodes  # This import must be done before cv2.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'impact.subpack_nodes'

**Comment by ltdrdata** [comment]
How did you install Impact Pack?

**Comment by Lightsockie** [comment]
I got this error when I just cloned the repo into `custom_nodes` and tried running ComfyUI. I didn't try doing either of the "optional" steps. Pruned it all and just used the Manager, which ended up working

**Comment by ltdrdata** [comment]
In a few hours, the Impact Subpack will be separated into a separate node and registered. You just need to update the Impact Pack and add the Impact Subpack.

**Comment by ltdrdata** [comment]
Impact Pack v8.0  is released.
Reinstall Imapact Pack and Impact Subpack.

**Comment by YacratesWyh** [comment]
Same report
```
Comfy-Easy-Use (v1.0.2): Loaded
### Loading: ComfyUI-Impact-Pack (V4.84)
### ComfyUI-Impact-Pack: Updating dependencies [0 -> 20]
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[Impact Pack] EXECUTE: ['/home/ubuntu/miniconda/envs/comfy/bin/python', 'install.py'] in '/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
```
```
WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes` as the ComfyUI path.

WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/models` as the ComfyUI path.
req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['/home/ubuntu/miniconda/envs/comfy/bin/python', 'install.py'] in '/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'

WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes` as the ComfyUI path.

WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/models` as the ComfyUI path.
req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
### ComfyUI-Impact-Pack: Check basic models
/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/wildcards.py:173: SyntaxWarning: invalid escape sequence '\+'
  subpattern = keyword.replace('*', '.*').replace('+','\+')
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 488, in <module>
    import impact.subpack_nodes
ModuleNotFoundError: No module named 'impact.subpack_nodes'
```
I cannot repair it even with both deleted and re git clone

**Comment by ltdrdata** [comment]
> Same report
> ```
> Comfy-Easy-Use (v1.0.2): Loaded
> ### Loading: ComfyUI-Impact-Pack (V4.84)
> ### ComfyUI-Impact-Pack: Updating dependencies [0 -> 20]
> ### ComfyUI-Impact-Pack: Check dependencies
> ### ComfyUI-Impact-Pack: Updating subpack
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> [Impact Pack] EXECUTE: ['/home/ubuntu/miniconda/envs/comfy/bin/python', 'install.py'] in '/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> ```
> ```
> WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes` as the ComfyUI path.
> 
> WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/models` as the ComfyUI path.
> req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
> req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
> req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
> ### ComfyUI-Impact-Pack: Check basic models
> ### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
> ### ComfyUI-Impact-Pack: Check dependencies
> ### ComfyUI-Impact-Pack: Updating subpack
> [Impact Pack] EXECUTE: ['/home/ubuntu/miniconda/envs/comfy/bin/python', 'install.py'] in '/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
> 
> WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes` as the ComfyUI path.
> 
> WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/models` as the ComfyUI path.
> req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
> req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
> req_path: /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
> ### ComfyUI-Impact-Pack: Check basic models
> /home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/wildcards.py:173: SyntaxWarning: invalid escape sequence '\+'
>   subpattern = keyword.replace('*', '.*').replace('+','\+')
> ### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack
> 
>   The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
>   Recommended to delete the path and restart ComfyUI.
>   If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.
> 
> ---------------------------------
> Traceback (most recent call last):
>   File "/home/ubuntu/AI/Comfy/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 488, in <module>
>     import impact.subpack_nodes
> ModuleNotFoundError: No module named 'impact.subpack_nodes'
> ```
> I cannot repair it even with both deleted and re git clone

Your ComfyUI-Impact-Pack is very very outdated version.
Did you download it from Civitai?

Anyway remove it and install via ComfyUI-Manager.
