### ISSUE TITLE
missing node ---detector

### ISSUE THREAD

**Issue by thefirstLeonliao** [ltdrdata/ComfyUI-Impact-Pack#852]
![image](https://github.com/user-attachments/assets/63958d44-77c3-4a44-b1ea-c34e18545774)

**Comment by scavru** [comment]
Is there a solution? Node is removed as I understand it, but what to replace it with?
![Ashampoo_Snap_13 декабря 2024 г _18h27m48s_001_](https://github.com/user-attachments/assets/427b4df5-66cf-4d04-b284-39e9e6d675ea)
