### ISSUE TITLE
SAM detector mask selection not picking up the correct area from points on the image

### ISSUE THREAD

**Issue by gitST2020** [ltdrdata/ComfyUI-Impact-Pack#853]
I saw that you fixed the previous issue with SAM Detector - the mask is now aligned with the image below it.

However, the area that has the dot is not the area that gets selected.

I still get the wrong part of the image selected when I click in a space. I think the point and click is also offset. Look at the attached - you'll see the blue dots and only a portion of the image selected.
![Screenshot 2024-12-11 231447](https://github.com/user-attachments/assets/32019eac-64c5-461e-8b9d-28cce285485a)

You'll see that I did the blue click on myself and the top right region became the selection.

![Screenshot 2024-12-11 231607](https://github.com/user-attachments/assets/94173d48-0796-4b66-9e7d-0c8f7fdb3ea8)

**Comment by ltdrdata** [comment]
confirmed.

**Comment by ltdrdata** [comment]
This is fixed.
