### ISSUE TITLE
facedetailer 

### ISSUE THREAD

**Issue by scavru** [ltdrdata/ComfyUI-Impact-Pack#855]
Node ultraliticsdetector removed, what can I replace it with? I find https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/852 but there's no solution.
![Ashampoo_Snap_13 декабря 2024 г _18h27m48s_001_](https://github.com/user-attachments/assets/1dce24fc-a711-4cd7-9902-8eacc9b2a3ba)

**Comment by scavru** [comment]
clean install + manager, and everything is fixed.

**Comment by ltdrdata** [comment]
FYI, UltralyticsDetectorProvider node is moved to `ComfyUI-Impact-Subpack`.
