### ISSUE TITLE
 Looking for a node to create simple horizontal and vertical masks

### ISSUE THREAD

**Issue by andreszs** [ltdrdata/ComfyUI-Impact-Pack#856]
I'm looking for a node with the ability to **create simple masked areas** of arbitrary size, if possible with a visual representation of the areas, similar to this **Visual Area Prompt** node:
![image](https://github.com/user-attachments/assets/7f084b45-0e73-4633-8ccc-cfad919340d0)

The only thing I've found so far is the awkward method using the **Simple Binary Pattern** from ComfyRoll Studio:
![image](https://github.com/user-attachments/assets/4f94d654-6207-49a7-a56b-a4911cb64f1d)

However it cannot create vertical masks, in fact it creates only images, then we have to convert it to mask, and I'd prefer to avoid installing a plethora of nodes to use just 1 of them.

Can this extension create simple masked areas like this? If yes, which nodes are involved? Thanks in advance.

_PS. I'm asking this here because the author has disabled the [GitHub Discussions](https://docs.github.com/en/discussions) section for this repo._

**Comment by ltdrdata** [comment]
You can create a vertical mask using only the core nodes.
![image](https://github.com/user-attachments/assets/2a2e56bb-4794-4d44-824b-a4a892273d3c)
![image](https://github.com/user-attachments/assets/0971260a-da9e-49e6-8413-a850d4377c41)

**Comment by andreszs** [comment]
Thanks, I prefer to avoid multiple nodes for simple tasks so I took the liberty of creating these nodes in a PR:

### Mask Rect Area

![image](https://github.com/user-attachments/assets/02b7e7a6-447b-44e4-a5a4-d736dcccd6c2)

Creates a mask with defined size and position in percentages, with optional blur. Contrary to smilar nodes from other packs, this outputs a **MASK** directly and features a preview canvas.

### Mask Rect Area (Advanced)

![image](https://github.com/user-attachments/assets/690d89af-2bbc-4cce-aa56-4ba6ecf35800)

Creates a mask with defined size and position in pixels, with optional blur, shown in preview canvas. Also outputs **MASK** and includes preview canvas.

They have been added to the generic **ImpactPack/Operation** category and tested with great success. I think a new category to group all mask-related nodes such as **ImpactPack/Masking** would be nice, however, I didn't want to create categories nor edit your categories without permission. Let me know what you think.

**Comment by ltdrdata** [comment]
That is merged.
