### ISSUE TITLE
Impact Subpack - Manual Installation - ComfyUi

### ISSUE THREAD

**Issue by Weaze1** [ltdrdata/ComfyUI-Impact-Pack#857]
I actually have no Idea how to install the Impact Subpack "Manually". Can somebody please share the experience how to do it?

**Comment by ltdrdata** [comment]
just go to `ComfyUI/custom_nodes` dir in cmd.

And then execute
`git clone https://github.com/ltdrdata/ComfyUI-Impact-Subpack`

Please make sure to install the latest version of Impact Pack.  
The installation method has changed compared to the previous version.

https://github.com/ltdrdata/ComfyUI-Impact-Subpack?tab=readme-ov-file#how-to-install

**Comment by Weaze1** [comment]
Thank you very much. I appreciate your help. Have a good day my friend.
