### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sedetweiler** [ltdrdata/ComfyUI-Impact-Pack#86]
Error when using PixelTiledSampleUpscalerProviderPipe.  Always throws this error no matter the settings or passed in values.  Suggestions?  Do you have a successful configuration I can use as an example?

**Comment by ltdrdata** [comment]
Have you tried this workflow?

https://github.com/ltdrdata/ComfyUI-extension-tutorials/tree/Main/ComfyUI-Impact-Pack/workflow

**Comment by sedetweiler** [comment]
I did, but I cannot get it to work with SDXL. It throws that error.

**Comment by ltdrdata** [comment]
> 

Oh.. I'd forgot about this..
Did you installed https://github.com/BlenderNeko/ComfyUI_TiledKSampler ?

**Comment by Nrgte** [comment]
> Have you tried this workflow?
> 
> https://github.com/ltdrdata/ComfyUI-extension-tutorials/tree/Main/ComfyUI-Impact-Pack/workflow

Is there a reason why all your examples use this weird V07_v07 checkpoint rather than SDXL or Refiner? I can't even find that on Civitai.

**Comment by ltdrdata** [comment]
It's a SD1.5 model.

Just I preferred the result of that for semi-realism.

https://civitai.com/models/18427?modelVersionId=21854

**Comment by Nrgte** [comment]
Have you also tested the Detailer with SDXL? I'm asking because I can't get good results and I'm not sure whether that's just me being a noob or that SDXL isn't tested very well with this extension. Assuming it's the former, but I'd rather confirm it with you before spending too much time. ;)

**Comment by ltdrdata** [comment]
> Have you also tested the Detailer with SDXL? I'm asking because I can't get good results and I'm not sure whether that's just me being a noob or that SDXL isn't tested very well with this extension. Assuming it's the former, but I'd rather confirm it with you before spending too much time. ;)

If you will use SDXL. You have to recall that SDXL requires higher(1024x1024) resolution than SD1.5 to get better result.

i.e. You have to increase guide_size and max_size. The default value is for SD1.5, at now.

And I am waiting finetuned SDXL models, also.

**Comment by ltdrdata** [comment]
> Have you also tested the Detailer with SDXL? I'm asking because I can't get good results and I'm not sure whether that's just me being a noob or that SDXL isn't tested very well with this extension. Assuming it's the former, but I'd rather confirm it with you before spending too much time. ;)

https://www.youtube.com/watch?v=L_iNyx0KXDg

SDXL refiner model support has been added.
