### ISSUE TITLE
Cannot import Pths/ComfyUI-Impact-Pack module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by aniketgore** [ltdrdata/ComfyUI-Impact-Pack#860]
Impact pack is not loading.

Error:

Cannot import //Path/ComfyUI-Impact-Pack module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

I have uninstalled reactor nodes as I read somewhere they were causing issues, but it's not still working.

**Comment by ltdrdata** [comment]
What is your numpy version?

**Comment by aniketgore** [comment]
1.26.3

**Comment by aniketgore** [comment]
### Loading: ComfyUI-Impact-Pack (V8.0.1)
[Impact Pack] Failed to import due to several dependencies are missing!!!!
Traceback (most recent call last):
  File "/ComfyUI/nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 47, in <module>
    raise e
  File "/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 36, in <module>
    from skimage.measure import label, regionprops
  File "/home/USER/.local/lib/python3.11/site-packages/skimage/__init__.py", line 122, in <module>
    from ._shared import geometry
  File "geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Cannot import /ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by ltdrdata** [comment]
> ### Loading: ComfyUI-Impact-Pack (V8.0.1)
> [Impact Pack] Failed to import due to several dependencies are missing!!!! Traceback (most recent call last): File "/ComfyUI/nodes.py", line 2072, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/**init**.py", line 47, in raise e File "/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/**init**.py", line 36, in from skimage.measure import label, regionprops File "/home/USER/.local/lib/python3.11/site-packages/skimage/**init**.py", line 122, in from ._shared import geometry File "geometry.pyx", line 1, in init skimage._shared.geometry ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
> 
> Cannot import /ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Remove `skimage` pip package and try again.

**Comment by aniketgore** [comment]
It worked after I removed the package updated the plugin and re added the required packages. Thanks for your help.
