### ISSUE TITLE
COMFYUI_MODEL_PATH bug...

### ISSUE THREAD

**Issue by Linsoo** [ltdrdata/ComfyUI-Impact-Pack#869]
If you set COMFYUI_MODEL_PATH in the environment variable, the model list will not appear in UltralyticsDetectorProvider.

I have COMFYUI_MODEL_PATH=c:\ai\Models\

![11111](https://github.com/user-attachments/assets/81fd2ca5-00b2-49e0-b7de-22ba7a3e25c3)

In this case, the model file is downloaded during installation, but the file is in the actual path...
![22222](https://github.com/user-attachments/assets/60dec03f-38d5-4a8f-81b5-45c913912f5a)
It appears that there are no models in the node.

If you delete the COMFYUI_MODEL_PATH environment variable and reinstall, it will be downloaded to ComfyUI\Models and will work normally.

Thanks for making a great extension.
It may be awkward because I used a translator.

**Comment by ltdrdata** [comment]
Typically, the install.py script cannot use CLI options, so COMFYUI_MODEL_PATH is provided to separately pass the model auto-installation path information.

During the use of ComfyUI, please specify the model path using extra_model_paths.yaml.

You can specify 

`ultralytics_bbox`, `ultralytics_segm`

**Comment by Linsoo** [comment]
@ltdrdata  Thank you~ it works!
