### ISSUE TITLE
Facedetailer doesnt work when followed latest tutorial 

### ISSUE THREAD

**Issue by 2blackbar** [ltdrdata/ComfyUI-Impact-Pack#87]
Plase help me what to do, i want to upscale the face with sd1.5
Heres workfflow file and part of the error
`  File "G:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 471, in forward
    k = self.to_k(context)
        ^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 18, in forward
    return torch.nn.functional.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (154x2048 and 768x320)`
[sdxlfacedetail workflow.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12272282/sdxlfacedetail.workflow.zip)

**Comment by ltdrdata** [comment]
![model](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/e6205d54-b398-47df-a8a3-ec6b62a71fc3)

It seems that a clip created with the SDXL base model and a model from SD1.5 are mixed and input into the ToBasicPipe.

**Comment by 2blackbar** [comment]
So how to solve this  in least convoluted way? Also if i want to upscale face with sdxl should i use refiner or base xl?

**Comment by ltdrdata** [comment]
> So how to solve this  in least convoluted way? Also if i want to upscale face with sdxl should i use refiner or base xl?

option 1. change the SD1.5 model to SDXL model.

option 2. make cliptextencode for SD1.5 model and connect them to ToBasicPipe instead of original positive/negative.

**Comment by 2blackbar** [comment]
Both did not solved this, all is separated now and sd1.5 has its own clip neg and positive that go to the pipe, still wont upscale the face wth sd1.5 model, i have no clue what is going on, i dont want to use sdxl cause its not great with details  like some trained 1.5 models
[sdxlfacedetail workflow.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12326236/sdxlfacedetail.workflow.zip)




Ok solved it ....
When i have a crowd in background, it tries to swap their faces, i dont want that to happen and swap only one biggest face onscreen, how to do it ?

**Comment by Centurion-Rome** [comment]
Face Detailer is not workin, none mask beeing created, no changes in image:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/75789136/f5df2dbb-216a-49b8-8ab0-c8fd93b9385e)

**Comment by ltdrdata** [comment]
> Face Detailer is not workin, none mask beeing created, no changes in image: ![image](https://user-images.githubusercontent.com/75789136/260452836-f5df2dbb-216a-49b8-8ab0-c8fd93b9385e.png)

If the detected area is larger than the guide_size, it will be skipped. Please increase the guide_size or activate force_inpaint for forced inpainting.

https://www.youtube.com/watch?v=KvZ8ucBqyqw

**Comment by ltdrdata** [comment]
> Both did not solved this, all is separated now and sd1.5 has its own clip neg and positive that go to the pipe, still wont upscale the face wth sd1.5 model, i have no clue what is going on, i dont want to use sdxl cause its not great with details like some trained 1.5 models [sdxlfacedetail workflow.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12326236/sdxlfacedetail.workflow.zip)
> 
> Ok solved it .... When i have a crowd in background, it tries to swap their faces, i dont want that to happen and swap only one biggest face onscreen, how to do it ?

![simpledetector](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/5e95369e-5fcd-426f-84a3-226bddcb9317)

You can use  `SEGS Filter (ordered)` .
`Descending, take_start 0, take_end 1` will take biggest 1 SEG.

**Comment by Centurion-Rome** [comment]
> If the detected area is larger than the guide_size, it will be skipped. Please increase the guide_size

Sadly this tip is not working, I have increased it even to 2048 and set force inpainting:
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/75789136/bfbaa77d-c84f-4e99-924c-2d4c02e37712)

Facedetailer does nothing

**Comment by Centurion-Rome** [comment]
Uff found soltion, use UltralisticDetectionProvider insead of MMdetDetectorProvider.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/75789136/3853e32c-421a-4b9f-b7d2-f02b5cbfde41)

**Comment by Centurion-Rome** [comment]
But getting error "RuntimeError: mat1 and mat2 shapes cannot be multiplied (308x1280 and 2048x640)". 
Sorry but it is so annoying...

**Comment by Centurion-Rome** [comment]
Same exception ""RuntimeError: mat1 and mat2 shapes cannot be multiplied (308x1280 and 2048x640)".
when using  this workflow with simple detector,detailer SEG/pipe
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/75789136/b9adc223-a21b-44af-8e67-e915eccc23e6)

any chance to get it working?

**Comment by ltdrdata** [comment]
> Same exception ""RuntimeError: mat1 and mat2 shapes cannot be multiplied (308x1280 and 2048x640)". when using this workflow with simple detector,detailer SEG/pipe ![image](https://user-images.githubusercontent.com/75789136/260569316-b9adc223-a21b-44af-8e67-e915eccc23e6.png)
> 
> any chance to get it working?

The messages seems that you are mixing incompatible model and clip in pipe. Make sure that.

**Comment by Centurion-Rome** [comment]
> The messages seems that you are mixing incompatible model and clip in pipe. Make sure that.

Yes! that was it. through whole comfyUI spagetti cables was plugged to wrong model (mix from base and refiner) ufff.

Thank you for that suggestion!

**Comment by ltdrdata** [comment]
> > The messages seems that you are mixing incompatible model and clip in pipe. Make sure that.
> 
> Yes! that was it. through whole comfyUI spagetti cables was plugged to wrong model (mix from base and refiner) ufff.
> 
> Thank you for that suggestion!

Recently, I added checker for that.
What is your version?

**Comment by Centurion-Rome** [comment]
> What is your version?

Loading: ComfyUI-Impact-Pack (V3.16.2)
