### ISSUE TITLE
I really don't understand where this question is?

### ISSUE THREAD

**Issue by yitao2020** [ltdrdata/ComfyUI-Impact-Pack#870]
![Dingtalk_20241230151317](https://github.com/user-attachments/assets/39ae1432-e0b4-4d3b-af05-32f38eee770f)
![Dingtalk_20241230151253](https://github.com/user-attachments/assets/74120e72-49d3-4a68-9036-14292cf8840f)

**Comment by yitao2020** [comment]
![Dingtalk_20241230151847](https://github.com/user-attachments/assets/faea686c-e5af-456c-9189-f01d3207b431)   With 90%of the progress, the speed of the network will decline. Is it that Americans do it?

**Comment by ltdrdata** [comment]
A network issue can occur at any point along the intermediate steps, so it is difficult to provide an exact answer.  
The issue might be controlled on the server side, by your ISP, or at the stage where traffic passes from GitHub’s servers to your country. It could simply be an issue with the proxy server.

In general, this type of issue is usually resolved by changing the transmission path through a VPN.
