### ISSUE TITLE
There are problems with the image receiving and sending functions, and images cannot be received correctly.

### ISSUE THREAD

**Issue by git-wzp** [ltdrdata/ComfyUI-Impact-Pack#871]
I have also found this problem. I have written a simple workflow to describe this phenomenon. When I send Picture A, Picture A can be received. When I replace Picture A with Picture B, Picture A is still received. Only by running it again can Picture B be received. This makes the function nodes for image sending and receiving very unstable to use, especially during batch operations.
At the same time, because the receiver must default to selecting an image file, there are often situations where the sent images cannot be received, and the node needs to be deleted and re - set.
![image](https://github.com/user-attachments/assets/9556d75a-48a1-4e08-8089-79bfed3292a3)

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/815#issuecomment-2566093186
