### ISSUE TITLE
When loading the graph, the following node types were not found:UltralyticsDetectorProvider

### ISSUE THREAD

**Issue by bukeshui0926** [ltdrdata/ComfyUI-Impact-Pack#88]
When loading the graph, the following node types were not found:UltralyticsDetectorProvider

![屏幕截图 2023-08-07 190128](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116459766/fafe820c-9a18-4e35-853b-91e90aafde03)
![屏幕截图 2023-08-07 190203](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116459766/33cd34b2-f10a-4050-b78c-0c5a2c0a226a)
I have installed the node but it does not load correctly

**Comment by ltdrdata** [comment]
Show me the startup log.

**Comment by bukeshui0926** [comment]
![屏幕截图 2023-08-07 190840](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/116459766/ad22536d-e322-4132-8499-161e4acc5025)

**Comment by bukeshui0926** [comment]
> 显示启动日志。

G:\ComfyUI\Blender_ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto

Prestartup times for custom nodes:
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

G:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
G:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
G:\ComfyUI\Blender_ComfyUI\python_embeded\lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Total VRAM 16384 MB, total RAM 16236 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints G:/sd-webui-aki-v4.2\models/Stable-diffusion
Adding extra search path configs G:/sd-webui-aki-v4.2\models/Stable-diffusion
Adding extra search path vae G:/sd-webui-aki-v4.2\models/VAE
Adding extra search path loras G:/sd-webui-aki-v4.2\models/Lora
Adding extra search path loras G:/sd-webui-aki-v4.2\models/LyCORIS
Adding extra search path upscale_models G:/sd-webui-aki-v4.2\models/ESRGAN
Adding extra search path upscale_models G:/sd-webui-aki-v4.2\models/SwinIR
Adding extra search path embeddings G:/sd-webui-aki-v4.2\embeddings
Adding extra search path hypernetworks G:/sd-webui-aki-v4.2\models/hypernetworks
Adding extra search path controlnet G:/sd-webui-aki-v4.2\models/ControlNet
### Loading: ComfyUI-Impact-Pack (V3.12)
### Loading: ComfyUI-Manager (V0.19)
### ComfyUI Revision: 1265 [1f0f4cc0]
Comfyroll Custom Nodes: Loaded
Total VRAM 16384 MB, total RAM 16236 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Config Export Error[Errno 2] No such file or directory: 'C:\\Users\\NIER\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\a_BlenderAI_Node\\SDNode\\PATH_CFG.json'WARNING: Ignoring invalid distribution -umpy (g:\comfyui\blender_comfyui\python_embeded\lib\site-packages)
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WARNING: Ignoring invalid distribution -umpy (g:\comfyui\blender_comfyui\python_embeded\lib\site-packages)
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WARNING: Ignoring invalid distribution -umpy (g:\comfyui\blender_comfyui\python_embeded\lib\site-packages)
WAS Node Suite: Finished. Loaded 191 nodes successfully.

        "Success is not just about making money. It's about making a difference." - Unknown


Import times for custom nodes:
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\cup.py
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\images-grid-comfy-plugin-main
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.4 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   1.6 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.9 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
  12.4 seconds: G:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by ltdrdata** [comment]
Ah, I just found the cause. 
The subpack hasn't been installed. 
Go to the impact pack directory and execute the command `git submodule update --init --recursive`.
Alternatively, try removing the Impact Pack through the Manager and then reinstalling it.

For some reason, I'm not sure why, it seems like the install script didn't run properly.

**Comment by bukeshui0926** [comment]
> 啊，我刚刚找到了原因。子包尚未安装。转到影响包目录并执行命令 。或者，尝试通过管理器删除影响包，然后重新安装它。`git submodule update --init --recursive`
> 
> 出于某种原因，我不确定为什么，似乎安装脚本无法正常运行。

When I tried to install, the input command did not respond

**Comment by ltdrdata** [comment]
> > 啊，我刚刚找到了原因。子包尚未安装。转到影响包目录并执行命令 。或者，尝试通过管理器删除影响包，然后重新安装它。`git submodule update --init --recursive`
> > 出于某种原因，我不确定为什么，似乎安装脚本无法正常运行。
> 
> When I tried to install, the input command did not respond

It's possible due to your outdated Git version. Update Git to the latest version and try again.

**Comment by Nicoolodion** [comment]
Updated it, and still didn't do anything for me...

**Comment by ltdrdata** [comment]
> Updated it, and still didn't do anything for me...

In version 4.0, I completely transitioned to a structure that no longer uses submodules. Please remove the "ComfyUI-Impact-Pack" directory and try reinstalling it.

**Comment by driftai** [comment]
i had to go into the folder on my side to see if the files copied over from the node version on git hub and downloaded the zip files of the missing files and extracted it on my side where they should be
