### ISSUE TITLE
Noise Mask, Force Inpaint - cant find valid inputs

### ISSUE THREAD

**Issue by bertoo87** [ltdrdata/ComfyUI-Impact-Pack#89]
Hey there :)

i found several Workflows i wanted to try out, and the most promising ones have your Detailer Nodes utilized. But the Inputs for Noise Mask and Force inpaint aren't plugged in in these workflows, and i cant find valid inputs for them. Problem is that Comfy demands something to be plugged in there, otherwise this node gets ignored.
Is there a way to disable these Inputs or any other way to circumvent this issue?

**Comment by ltdrdata** [comment]
Update ComfyUI to latest version.

**Comment by bertoo87** [comment]
oh boy... you can't imagine how embarresed i am that i didnt think about that. Works now, Thanks :)
