### ISSUE TITLE
Error when installing on ComfyUI Portable

### ISSUE THREAD

**Issue by robertvoy** [ltdrdata/ComfyUI-Impact-Pack#9]
```
PS C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack> C:\ComfyUI\python_embeded\python.exe install.py
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 15, in <module>
    import impact_config
ModuleNotFoundError: No module named 'impact_config'
```

**Comment by ltdrdata** [comment]
I guess this issue related to directory recognition. I need to check the portable version.
Which one do you running?

https://github.com/comfyanonymous/ComfyUI/releases

**Comment by robertvoy** [comment]
Thank you!

I'm using this one:

[Download Link with stable pytorch 2.0 cu118 + xformers](https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu118_or_cpu.7z)

**Comment by ltdrdata** [comment]
> Thank you!
> 
> I'm using this one:
> 
> [Download Link with stable pytorch 2.0 cu118 + xformers](https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu118_or_cpu.7z)

I just tested on that version.
There is no problem under this installation steps.

1. unzip portable version
2. goto ComfyUI/custom_nodes
3. git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack
4. launch run_cpu.bat

Is this your installation steps, too? 
In that case...

open **install.py**. Then you can see this code. 
```
import os
import sys
import subprocess


comfy_path = '../..'

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "comfy"))
sys.path.append(comfy_path)


import platform
import folder_paths
from torchvision.datasets.utils import download_url
import impact_config
...
```

add logging code like this..

```
import os
import sys
import subprocess


comfy_path = '../..'

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "comfy"))
sys.path.append(comfy_path)

print(f"__File__ path: {os.path.realpath(__file__)}")            # ADD THIS CODE 
print(f"comfy_path: {os.path.realpath(comfy_path)}")             # 
print(f"comfy_path: {os.path.realpath('.')}")                    # 
print(f"impact_config: {os.path.exists('impact_config.py')}")    # 

import platform
import folder_paths
from torchvision.datasets.utils import download_url
import impact_config
...
```

and launch show me the console message.

**Comment by robertvoy** [comment]
My installation steps are: 

1. unzip portable version
2. goto ComfyUI/custom_nodes
3. git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack
4. cd ComfyUI-Impact-Pack
5. PS C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack> C:\ComfyUI\python_embeded\python.exe install.py

In step 5, after changing the code as you requested, I get this error:

`__File__ path: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py
comfy_path: C:\ComfyUI\ComfyUI
comfy_path: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
impact_config: True
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 19, in <module>
    import impact_config
ModuleNotFoundError: No module named 'impact_config'`

I've gone ahead and installed the below manually:

pip install
-   openmim
-   segment-anything
-   pycocotools
-   onnxruntime

mim install
-   mmcv==2.0.0, mmdet==3.0.0, mmengine==0.7.2

It seems to work sometimes. Half of the time it seems to skip without any error in the console. Maybe it doesn't detect a face, I'm not sure.

**Comment by ltdrdata** [comment]
> My installation steps are:
> 
> 1. unzip portable version
> 2. goto ComfyUI/custom_nodes
> 3. git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack
> 4. cd ComfyUI-Impact-Pack
> 5. PS C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack> C:\ComfyUI\python_embeded\python.exe install.py
> 
> In step 5, after changing the code as you requested, I get this error:
> 
> `__File__ path: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py comfy_path: C:\ComfyUI\ComfyUI comfy_path: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack impact_config: True Traceback (most recent call last): File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 19, in <module> import impact_config ModuleNotFoundError: No module named 'impact_config'`
> 
> I've gone ahead and installed the below manually:
> 
> pip install
> 
> * openmim
> * segment-anything
> * pycocotools
> * onnxruntime
> 
> mim install
> 
> * mmcv==2.0.0, mmdet==3.0.0, mmengine==0.7.2
> 
> It seems to work sometimes. Half of the time it seems to skip without any error in the console. Maybe it doesn't detect a face, I'm not sure.

Try recent version. I've fixed this issue.
Now, you can execute install.py manually on portable version.

Additionally, you don't need execute **install.py**. It will executed automatically during initial launch.
I updated installation guide.

**Comment by robertvoy** [comment]
Thank you for that.
