### ISSUE TITLE
Import Failed, impact.hacky module not found

### ISSUE THREAD

**Issue by ergosk** [ltdrdata/ComfyUI-Impact-Pack#97]
Hi, I am still new to ComfyUi and looking for a comfyui node to detail face.
I tried to import impact pack but it hasn't work so far. I am confused on what to do.
Can you please advise? Thank you, below is the cmd logs.

File "D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 18, in <module>
    import impact.hacky
ModuleNotFoundError: No module named 'impact.hacky'

Cannot import D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'impact.hacky'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

**Comment by ltdrdata** [comment]
Plase update your Impact pack to latest version.

**Comment by ergosk** [comment]
It worked, but still found an error after 89 seconds. It said invalid git repository error?

 File "D:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\repo\base.py", line 265, in __init__    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main

Cannot import D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main module for custom nodes: D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main

Import times for custom nodes:
   0.7 seconds: D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
  89.7 seconds (IMPORT FAILED): D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main

**Comment by ltdrdata** [comment]
> It worked, but still found an error after 89 seconds. It said invalid git repository error?
> 
> File "D:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\repo\base.py", line 265, in **init** raise InvalidGitRepositoryError(epath) git.exc.InvalidGitRepositoryError: D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main
> 
> Cannot import D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main module for custom nodes: D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main
> 
> Import times for custom nodes: 0.7 seconds: D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui 89.7 seconds (IMPORT FAILED): D:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main

I recommend remove it and install through ComfyUI-Manager.

**Comment by ergosk** [comment]
Tried to remove it and reinstall through ComfyUI-Manager. Worked splendidly.
Thank you for your help and have a nice day.
