### ISSUE TITLE
FaceDetailer minimum size?

### ISSUE THREAD

**Issue by alabama1223** [ltdrdata/ComfyUI-Impact-Pack#98]
Is there a way to set a minimum size for the FaceDetailer to detect? It sometimes detects little blurred faces on the image and tries to correct them

**Comment by ltdrdata** [comment]
Using `drop_size`, you can exclude masks that are below a certain size.
Alternatively, by using the workflow of `Simple Detector + SEGS Filter (ordered) + Detailer`, you can filter based on size or coordinate information as well.
